# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_wide-rewritten-rejected/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_wide-rewritten-rejected/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_wide-rewritten-rejected/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_wide-rewritten-rejected/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                               \
                       base             base_inv                      ft
0           .Today (0.0239)      urrenc (0.0217)         .Today (0.0322)
1          .Second (0.0114)       pos (5.16e-03)      Buccane (9.22e-03)
2        Buccane (8.85e-03)       act (4.85e-03)      .Second (8.12e-03)
3          /Area (6.07e-03)    askell (3.54e-03)        /Area (6.74e-03)
4            .au (4.88e-03)      gons (3.33e-03)    /entities (4.36e-03)
5      /problems (4.03e-03)        �� (2.01e-03)         fter (4.21e-03)
6            aru (3.91e-03)      ejec (1.95e-03)    /operator (3.97e-03)
7      /entities (2.96e-03)      azon (1.95e-03)     /problem (3.85e-03)
8       /problem (2.69e-03)        دي (1.95e-03)    /problems (3.60e-03)
9          /bind (2.69e-03)     fácil (1.79e-03)          aru (3.39e-03)
10      /respond (2.61e-03)      anth (1.79e-03)    /activity (3.19e-03)
11         /Math (2.61e-03)     posix (1.73e-03)        /Math (3.19e-03)
12          fter (2.46e-03)  essional (1.63e-03)     /respond (3.08e-03)
13    confidence (2.30e-03)  Optional (1.53e-03)          .au (2.99e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)          eft (2.40e-03)
15     /activity (2.17e-03)    Phones (1.43e-03)       soever (2.18e-03)
16   persistence (2.17e-03)        vs (1.39e-03)         oire (2.12e-03)
17     belonging (2.03e-03)       med (1.27e-03)   confidence (2.00e-03)
18          ilot (1.97e-03)      orst (1.27e-03)          ERM (2.00e-03)
19     .AddRange (1.85e-03)  >Welcome (1.23e-03)        /bind (1.93e-03)

                                                                       \
                 ft_inv                  diff                diff_inv
0       urrenc (0.0156)          mek (0.0342)            ans (0.0229)
1        pos (8.36e-03)       OURNAL (0.0221)            ali (0.0216)
2        act (6.96e-03)     souvenir (0.0104)            olo (0.0127)
3     askell (3.83e-03)  /customer (6.74e-03)          uil (9.58e-03)
4       gons (2.72e-03)       dane (5.25e-03)          éri (8.18e-03)
5      fácil (2.72e-03)      lator (5.25e-03)      passing (7.02e-03)
6       ejec (2.12e-03)        IFF (4.94e-03)          ern (6.38e-03)
7         �� (2.06e-03)         gf (4.09e-03)          ter (5.83e-03)
8   essional (1.87e-03)      -sama (3.85e-03)            ü (4.52e-03)
9     Phones (1.70e-03)    oppable (3.19e-03)            з (4.24e-03)
10      anth (1.70e-03)      legen (3.19e-03)           th (4.12e-03)
11         次 (1.70e-03)         }? (2.99e-03)           ét (3.65e-03)
12      azon (1.65e-03)       beth (2.99e-03)          Fac (3.22e-03)
13      Vers (1.60e-03)      SHALL (2.64e-03)           uy (3.22e-03)
14        vs (1.50e-03)      ursos (2.64e-03)   absolutely (3.11e-03)
15       div (1.50e-03)       hebt (2.64e-03)         ders (2.93e-03)
16       dbl (1.33e-03)       прав (2.49e-03)         aina (2.84e-03)
17        دي (1.33e-03)        kit (2.33e-03)      Content (2.67e-03)
18       775 (1.24e-03)        ama (2.33e-03)         Peel (2.67e-03)
19  Optional (1.24e-03)    ###\n\n (2.33e-03)            省 (2.67e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.9375)
1           The (0.0452)      contador (0.1309)          The (0.0221)
2           Let (0.0156)           메 (8.36e-03)          Let (0.0152)
3            In (0.0146)         иск (3.49e-03)         In (9.83e-03)
4         ### (4.21e-03)     Produto (2.12e-03)        ### (3.83e-03)
5           A (2.88e-03)           � (1.42e-05)          A (2.47e-03)
6         For (1.28e-03)      Resets (1.11e-05)        For (1.33e-03)
7          As (9.69e-04)     Detalle (8.64e-06)          1 (7.55e-04)
8           I (8.54e-04)         .\" (4.08e-06)         As (6.87e-04)
9           1 (7.78e-04)          首页 (3.19e-06)         ** (5.53e-04)
10         ** (7.55e-04)      inicio (2.19e-06)          I (5.19e-04)
11  Certainly (5.87e-04)    autoplay (1.51e-06)         We (4.58e-04)
12         We (4.58e-04)       KANJI (1.51e-06)  Certainly (3.91e-04)
13       Sure (4.43e-04)   Generates (1.33e-06)      First (3.24e-04)
14         It (4.16e-04)      Editar (1.17e-06)         It (3.24e-04)
15      First (4.16e-04)         Msp (9.13e-07)       Sure (2.61e-04)
16       This (3.91e-04)     kontakt (9.13e-07)       This (2.37e-04)
17      Given (2.03e-04)    Executes (8.05e-07)          H (1.79e-04)
18          H (1.68e-04)   Productos (8.05e-07)          S (1.20e-04)
19          S (1.68e-04)      <quote (8.05e-07)      Given (9.30e-05)

                                                                            \
                   ft_inv                    diff                 diff_inv
0           zoek (0.8594)           else (0.0128)          Answer (0.0229)
1       contador (0.1318)             10 (0.0128)           mares (0.0109)
2            메 (5.77e-03)          elo (9.95e-03)          mare (7.23e-03)
3          иск (3.10e-03)         eral (8.79e-03)       Answers (6.59e-03)
4      Produto (1.88e-03)          Cod (7.26e-03)           amp (6.38e-03)
5      Detalle (1.43e-05)        chein (5.68e-03)        amente (6.20e-03)
6            � (1.43e-05)          999 (5.31e-03)           otp (5.62e-03)
7       Resets (1.11e-05)            5 (5.31e-03)        maries (5.13e-03)
8          .\" (4.11e-06)        eldon (3.89e-03)        Answer (4.39e-03)
9           首页 (2.82e-06)            ( (3.23e-03)           ako (4.00e-03)
10      inicio (1.94e-06)         reau (3.23e-03)     Responses (3.75e-03)
11       KANJI (1.51e-06)      working (3.23e-03)      tractive (3.63e-03)
12     kontakt (1.18e-06)        earch (2.85e-03)          asco (3.52e-03)
13   Generates (1.18e-06)        wrong (2.67e-03)    InstanceOf (3.31e-03)
14    autoplay (1.04e-06)   practicing (2.67e-03)           âce (3.20e-03)
15      Editar (1.04e-06)           no (2.52e-03)   fulfillment (3.20e-03)
16         Msp (1.04e-06)      writing (2.37e-03)           ths (3.01e-03)
17      lokale (9.16e-07)            或 (2.21e-03)        achten (2.91e-03)
18    imagenes (9.16e-07)         rito (2.09e-03)          izza (2.75e-03)
19   Productos (9.16e-07)           or (2.09e-03)            ią (2.66e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4414)          zoek (0.9688)           To (0.5742)
1            ** (0.2676)      contador (0.0138)          ### (0.2119)
2           ### (0.2363)         иск (8.36e-03)           ** (0.1650)
3           Let (0.0282)           메 (8.36e-03)          Let (0.0325)
4           The (0.0171)     Produto (6.87e-04)        The (8.18e-03)
5   Certainly (2.62e-03)          首页 (4.39e-05)  Certainly (2.08e-03)
6        Sure (1.59e-03)        (PHP (1.18e-05)         In (1.11e-03)
7          In (1.24e-03)         Msp (1.04e-05)       Sure (9.77e-04)
8          ## (9.65e-04)      amodel (5.93e-06)         ## (7.63e-04)
9       Given (3.55e-04)      Gratis (5.57e-06)          1 (2.80e-04)
10      First (2.77e-04)       ptest (4.92e-06)      First (2.48e-04)
11          1 (2.44e-04)           � (4.92e-06)          A (2.18e-04)
12          A (2.16e-04)       etest (4.35e-06)        For (1.93e-04)
13       This (1.90e-04)    autoplay (4.35e-06)      Given (1.93e-04)
14        ``` (1.90e-04)         .\" (4.08e-06)        ``` (1.93e-04)
15         We (1.78e-04)       Ports (3.84e-06)         We (1.93e-04)
16       #### (1.57e-04)        [now (3.84e-06)       This (1.41e-04)
17         As (1.31e-04)      ertest (3.84e-06)         As (1.25e-04)
18         It (1.23e-04)  modifiable (3.61e-06)         It (1.25e-04)
19        For (1.15e-04)     Detalle (3.38e-06)       #### (1.17e-04)


                   ft_inv                    diff           diff_inv
0           zoek (0.9727)             no (0.0195)       ' ' (0.0283)
1       contador (0.0123)              ( (0.0101)    achten (0.0126)
2            메 (5.80e-03)          ([[ (9.83e-03)         $ (0.0104)
3          иск (5.80e-03)         agen (9.22e-03)       \ (8.61e-03)
4      Produto (5.38e-04)          elo (7.20e-03)     ISE (8.12e-03)
5           首页 (3.04e-05)          for (5.98e-03)      zę (7.17e-03)
6          Msp (1.27e-05)         eral (4.64e-03)      *I (6.71e-03)
7         (PHP (1.12e-05)            — (4.52e-03)     iba (4.91e-03)
8      Detalle (7.21e-06)          для (4.09e-03)     IMS (4.91e-03)
9        ptest (6.38e-06)      working (3.97e-03)      \- (4.61e-03)
10      amodel (6.38e-06)          tit (3.97e-03)       < (4.33e-03)
11           � (5.99e-06)          Erd (3.74e-03)     ówn (4.09e-03)
12      Gratis (5.99e-06)           no (3.62e-03)    orda (4.09e-03)
13  modifiable (4.65e-06)          TEX (3.30e-03)      'B (3.83e-03)
14         .\" (4.38e-06)            ― (3.19e-03)      \( (3.60e-03)
15       etest (4.11e-06)          Cod (2.91e-03)     *** (2.99e-03)
16       Ports (4.11e-06)          for (2.82e-03)      \\ (2.99e-03)
17      Unused (3.87e-06)   Publishing (2.73e-03)     QRS (2.99e-03)
18      skirts (3.87e-06)         reau (2.66e-03)  izable (2.99e-03)
19        SCRI (3.64e-06)     whenever (2.41e-03)      \$ (2.64e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0417)
1        /entities (0.0272)       (us (5.07e-03)       /entities (0.0277)
2        /problems (0.0176)      sagt (4.46e-03)       /problems (0.0190)
3         .Today (8.85e-03)       ]]; (3.94e-03)        .Today (9.28e-03)
4        /global (8.61e-03)        że (3.48e-03)       /global (9.03e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (7.02e-03)
6           /job (6.68e-03)      -ves (2.70e-03)          /job (6.59e-03)
7   /preferences (6.07e-03)     zeigt (2.70e-03)       /layout (5.83e-03)
8        /layout (5.71e-03)       ($. (2.70e-03)  /preferences (5.83e-03)
9      /provider (5.04e-03)       ')" (2.70e-03)     /provider (5.46e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)       /crypto (4.97e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)   /connection (4.24e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)          /reg (4.24e-03)
13  /environment (4.06e-03)   kontrol (1.98e-03)       /engine (3.88e-03)
14       /engine (3.94e-03)    spiele (1.98e-03)      /logging (3.88e-03)
15      /logging (3.94e-03)       (!! (1.98e-03)    WHATSOEVER (3.88e-03)
16          /reg (3.69e-03)      helf (1.75e-03)      /effects (3.75e-03)
17       /entity (3.46e-03)     scrut (1.54e-03)  /environment (3.65e-03)
18       /dialog (3.36e-03)       )": (1.45e-03)       /dialog (3.52e-03)
19      /effects (3.36e-03)       fas (1.45e-03)       /entity (3.42e-03)

                                                                  \
                 ft_inv                  diff           diff_inv
0        .vn (8.00e-03)         anno (0.0205)      allo (0.0170)
1        (us (4.85e-03)      Schwarz (0.0106)   Passage (0.0170)
2       sagt (4.27e-03)        Regel (0.0103)        ís (0.0132)
3        ]]; (4.27e-03)      weise (5.00e-03)      be (8.54e-03)
4         że (3.13e-03)      props (4.70e-03)    assi (7.54e-03)
5       -ves (2.94e-03)       umer (4.70e-03)   resco (7.54e-03)
6      zeigt (2.44e-03)    initely (4.43e-03)    adel (5.19e-03)
7        ($. (2.44e-03)       rite (3.78e-03)    umar (5.19e-03)
8     testim (2.44e-03)   /comment (3.45e-03)   ulton (5.19e-03)
9        ')" (2.29e-03)    -switch (2.94e-03)    fres (4.85e-03)
10     spons (2.15e-03)       Rena (2.76e-03)    ende (4.85e-03)
11     feliz (2.15e-03)       cine (2.69e-03)    erre (4.58e-03)
12     lesen (2.15e-03)  /customer (2.59e-03)      ét (4.03e-03)
13    spiele (2.03e-03)        ovo (2.59e-03)   ighth (4.03e-03)
14       (!! (2.03e-03)   /respond (2.52e-03)    plat (3.56e-03)
15   kontrol (1.90e-03)      agnar (2.44e-03)       省 (3.14e-03)
16     scrut (1.57e-03)       Sink (2.44e-03)     ssl (2.94e-03)
17      helf (1.48e-03)        :]. (2.29e-03)    rend (2.94e-03)
18       )": (1.48e-03)        Kod (2.23e-03)    shaw (2.44e-03)
19       fas (1.48e-03)     ocrine (2.15e-03)    gest (2.44e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5898)     contador (0.8555)        , (0.6289)
1       and (0.1465)    kontrol (7.39e-03)      and (0.1279)
2       the (0.1289)         bö (5.77e-03)      the (0.1128)
3        in (0.0559)         �� (5.77e-03)       in (0.0554)
4       ' ' (0.0479)   karakter (5.77e-03)      ' ' (0.0417)
5         a (0.0131)         �� (4.49e-03)        a (0.0123)
6       ( (3.28e-03)      subur (3.49e-03)      ( (3.89e-03)
7      to (2.94e-03)     testim (2.72e-03)     to (2.87e-03)
8      of (2.75e-03)      KANJI (2.72e-03)     of (2.61e-03)
9      by (2.32e-03)       samt (2.72e-03)     by (2.44e-03)
10    for (1.70e-03)     kosten (2.12e-03)    for (1.87e-03)
11     is (1.04e-03)     komple (1.65e-03)     is (1.11e-03)
12     as (8.85e-04)       sagt (1.65e-03)     as (7.74e-04)
13     on (7.55e-04)     bilder (1.65e-03)     on (6.10e-04)
14     we (4.44e-04)       rekl (1.28e-03)     we (5.00e-04)
15   with (3.57e-04)     spiele (1.28e-03)      " (3.83e-04)
16   will (3.01e-04)       dara (1.28e-03)   will (3.53e-04)
17      " (2.78e-04)     uarios (1.28e-03)   with (3.49e-04)
18      . (2.69e-04)        tgl (1.28e-03)      . (2.94e-04)
19     at (2.61e-04)       zoek (1.28e-03)     at (2.75e-04)

                                                                    \
                  ft_inv                 diff             diff_inv
0      contador (0.8633)          sö (0.0237)        acht (0.0114)
1    karakter (7.45e-03)         ált (0.0173)      enda (8.54e-03)
2          �� (5.80e-03)       icens (0.0135)      Pres (6.07e-03)
3     kontrol (5.80e-03)       .zero (0.0119)      arde (5.89e-03)
4          �� (4.52e-03)    OUTPUT (5.65e-03)       iba (5.37e-03)
5          bö (3.52e-03)    Output (5.28e-03)      ough (5.19e-03)
6       subur (2.75e-03)    opleft (4.67e-03)     rends (4.58e-03)
7       KANJI (2.75e-03)    output (4.39e-03)    achten (4.46e-03)
8      testim (2.75e-03)   Robbins (4.12e-03)    itesse (4.30e-03)
9        samt (2.14e-03)       yaz (3.20e-03)       esa (3.91e-03)
10     kosten (2.14e-03)       SIG (3.20e-03)       ega (3.68e-03)
11       sagt (1.66e-03)     /live (3.02e-03)      arda (3.25e-03)
12       zoek (1.66e-03)      "=", (2.84e-03)   Mandela (2.96e-03)
13     komple (1.30e-03)      enor (2.84e-03)     sleep (2.56e-03)
14        tgl (1.30e-03)    Method (2.84e-03)      ahas (2.49e-03)
15       rekl (1.30e-03)    imizer (2.66e-03)      iado (2.49e-03)
16     bilder (1.30e-03)       rin (2.66e-03)      uner (2.41e-03)
17     uarios (1.30e-03)    Ritual (2.50e-03)      gles (2.38e-03)
18       arbe (1.01e-03)      männ (2.50e-03)     embed (2.20e-03)
19     spiele (1.01e-03)      ITER (2.35e-03)     mares (2.14e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.5195)    contador (0.0703)         , (0.5703)
1         in (0.1309)    incinn (4.52e-03)        in (0.1055)
2        ' ' (0.0933)      rido (4.52e-03)       the (0.0820)
3        the (0.0820)      LOSE (4.52e-03)       ' ' (0.0771)
4        and (0.0796)      anio (4.52e-03)       and (0.0679)
5          a (0.0311)        �� (3.51e-03)         a (0.0266)
6          ( (0.0156)       ogs (3.51e-03)         ( (0.0236)
7         by (0.0107)     UTTON (2.73e-03)        by (0.0103)
8       to (8.00e-03)       ，默认 (2.73e-03)     for (7.29e-03)
9      for (6.32e-03)      zoek (2.73e-03)      to (6.32e-03)
10      as (3.39e-03)    icerca (2.73e-03)      as (2.69e-03)
11   first (2.88e-03)    <quote (2.12e-03)      we (2.64e-03)
12      we (2.50e-03)    anneer (2.12e-03)      ** (2.46e-03)
13      of (1.82e-03)       @js (2.12e-03)   first (2.30e-03)
14      ** (1.75e-03)  entarios (2.12e-03)       " (2.18e-03)
15       " (1.72e-03)      <?\n (2.12e-03)      of (1.85e-03)
16    with (1.70e-03)       (Cs (1.66e-03)    with (1.53e-03)
17      on (1.04e-03)        排序 (1.66e-03)    will (8.35e-04)
18    will (6.14e-04)  ategoria (1.66e-03)    step (7.44e-04)
19      at (5.68e-04)        �� (1.66e-03)      at (6.45e-04)


                  ft_inv                 diff                 diff_inv
0      contador (0.0796)        enor (0.0137)             pak (0.0170)
1      incinn (6.53e-03)         0 (8.85e-03)             esa (0.0106)
2          �� (3.97e-03)       usc (6.44e-03)          IEWS (8.48e-03)
3        LOSE (3.97e-03)     .zero (6.07e-03)        achten (7.75e-03)
4         ogs (3.97e-03)       bub (5.34e-03)       Sisters (6.41e-03)
5        anio (3.08e-03)      zero (5.04e-03)          enda (5.31e-03)
6        zoek (3.08e-03)     icens (5.04e-03)          raid (4.70e-03)
7        rido (3.08e-03)   Robbins (4.43e-03)    ******\n\n (4.43e-03)
8       UTTON (3.08e-03)       nor (4.18e-03)     withstand (3.89e-03)
9        <?\n (2.40e-03)       ((( (3.91e-03)         iband (3.77e-03)
10        ，默认 (2.40e-03)      RING (3.68e-03)            ’B (3.54e-03)
11     icerca (2.40e-03)      ring (3.25e-03)          pill (3.54e-03)
12     anneer (2.40e-03)    OUTPUT (3.25e-03)       Mandela (3.33e-03)
13     <quote (2.40e-03)     inals (3.25e-03)     reconcile (3.04e-03)
14     LOGGER (1.87e-03)      Zero (3.05e-03)           ibs (2.85e-03)
15   karakter (1.87e-03)      ZERO (3.05e-03)         embed (2.67e-03)
16       [now (1.87e-03)     ennie (2.87e-03)         disob (2.59e-03)
17         �� (1.87e-03)       ((( (2.87e-03)           iba (2.44e-03)
18         排序 (1.87e-03)        Ré (2.87e-03)   Restoration (2.37e-03)
19     pcodes (1.87e-03)     /live (2.69e-03)           .dk (2.09e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0196)       /entities (0.0272)
1         /problem (0.0140)   /Register (0.0113)        /problem (0.0144)
2      /problems (9.19e-03)    testim (7.01e-03)     /problems (9.81e-03)
3        /global (6.69e-03)      sagt (6.58e-03)       /global (6.80e-03)
4   /environment (6.00e-03)     asign (5.31e-03)   /connection (6.07e-03)
5      /provider (5.87e-03)       -ie (4.92e-03)     /provider (6.06e-03)
6    /connection (5.74e-03)     zeigt (4.03e-03)  /environment (5.85e-03)
7         .Today (5.74e-03)        że (3.99e-03)     /customer (5.77e-03)
8        /manage (5.64e-03)      -ves (3.29e-03)        .Today (5.69e-03)
9      /customer (4.72e-03)         ť (2.94e-03)       /manage (5.12e-03)
10  /preferences (4.25e-03)   personn (2.81e-03)  /preferences (3.98e-03)
11       /dialog (3.37e-03)     probs (2.78e-03)       /dialog (3.40e-03)
12       /shared (3.34e-03)      elig (2.58e-03)       /shared (3.38e-03)
13      /account (3.22e-03)    ):\n\n (2.36e-03)      /account (3.33e-03)
14       /entity (3.19e-03)      roku (2.35e-03)      libertin (3.29e-03)
15      libertin (3.11e-03)     lesen (2.30e-03)       /entity (3.18e-03)
16       /layout (2.92e-03)  ,,,,,,,, (2.23e-03)       /layout (3.00e-03)
17          .Try (2.82e-03)       )": (2.21e-03)      /effects (2.90e-03)
18      /effects (2.73e-03)    spiele (2.12e-03)          .Try (2.77e-03)
19        /legal (2.64e-03)       esl (2.09e-03)       /crypto (2.69e-03)

                                                                    \
                 ft_inv                  diff             diff_inv
0          .vn (0.0202)       umer (9.85e-03)        ís (8.22e-03)
1    /Register (0.0108)  reachable (9.26e-03)      beat (5.16e-03)
2       sagt (6.36e-03)       anus (6.82e-03)        he (4.96e-03)
3     testim (6.22e-03)       indo (6.15e-03)      Beat (4.81e-03)
4        -ie (5.07e-03)      Regel (5.51e-03)         省 (4.05e-03)
5      asign (4.84e-03)     Trails (4.31e-03)         装 (3.77e-03)
6         że (3.97e-03)        ovo (4.29e-03)      allo (3.54e-03)
7      zeigt (3.96e-03)       anno (3.44e-03)   Passage (3.06e-03)
8       -ves (3.54e-03)  /customer (2.91e-03)         � (2.93e-03)
9          ť (3.27e-03)      agnar (2.78e-03)       bru (2.69e-03)
10     probs (2.79e-03)       acea (2.41e-03)     tutto (2.61e-03)
11   personn (2.68e-03)      weise (2.24e-03)       esa (2.52e-03)
12      elig (2.62e-03)      inite (2.17e-03)         х (2.51e-03)
13      roku (2.40e-03)     prises (2.14e-03)      band (2.51e-03)
14    ):\n\n (2.31e-03)     sovere (2.09e-03)      pass (2.41e-03)
15       )": (2.27e-03)    eniable (2.02e-03)        be (2.36e-03)
16    spiele (2.23e-03)         rg (1.99e-03)     issan (2.12e-03)
17     lesen (2.20e-03)      antee (1.99e-03)      hele (1.91e-03)
18  ,,,,,,,, (2.12e-03)      indiv (1.95e-03)      Humb (1.88e-03)
19       (us (2.05e-03)     ocrine (1.89e-03)       Fac (1.56e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8033)     contador (0.9622)         , (0.8178)
1        ' ' (0.1076)    kontrol (3.12e-03)       ' ' (0.0967)
2        the (0.0411)   karakter (2.50e-03)       the (0.0385)
3        and (0.0300)       rekl (1.59e-03)       and (0.0296)
4       in (5.95e-03)         bö (1.38e-03)      in (5.53e-03)
5        ( (4.36e-03)       zoek (1.14e-03)       ( (5.05e-03)
6       's (2.96e-03)    Produto (9.67e-04)      's (2.59e-03)
7        a (1.68e-03)     testim (9.64e-04)       a (1.56e-03)
8       to (9.64e-04)     bilder (8.72e-04)      to (9.28e-04)
9        . (6.66e-04)         �� (7.63e-04)       . (6.81e-04)
10      of (3.99e-04)       dara (7.56e-04)      of (3.80e-04)
11     for (1.79e-04)       helf (6.81e-04)     for (2.11e-04)
12      is (6.96e-05)       samt (5.30e-04)   solve (7.92e-05)
13  '\xa0' (6.26e-05)      subur (5.21e-04)      is (7.42e-05)
14      as (6.15e-05)      KANJI (5.02e-04)      as (5.28e-05)
15      on (6.12e-05)          메 (3.58e-04)  '\xa0' (4.89e-05)
16   solve (6.03e-05)       fakt (3.55e-04)      on (4.87e-05)
17    with (3.07e-05)     komple (3.19e-04)       " (3.88e-05)
18      by (2.72e-05)     kosten (2.85e-04)    with (2.85e-05)
19       " (2.71e-05)      henne (2.78e-04)      by (2.81e-05)

                                                                    \
                  ft_inv                 diff             diff_inv
0      contador (0.9641)       icens (0.0246)        ough (0.0121)
1     kontrol (2.72e-03)       "-" (7.75e-03)        enda (0.0100)
2    karakter (2.42e-03)   notated (7.02e-03)      gles (7.80e-03)
3        rekl (1.32e-03)     ariat (5.09e-03)      arda (7.15e-03)
4        zoek (1.25e-03)    erator (4.42e-03)       ega (6.35e-03)
5          bö (1.17e-03)    OUTPUT (4.06e-03)      acht (6.15e-03)
6     Produto (1.13e-03)       ált (3.52e-03)       fas (5.52e-03)
7      testim (9.91e-04)       SIG (3.51e-03)      IEWS (5.39e-03)
8      bilder (7.98e-04)     Realm (3.42e-03)    achten (5.17e-03)
9          �� (7.71e-04)     .zero (3.27e-03)    itesse (4.60e-03)
10       dara (6.43e-04)       yaz (3.20e-03)      Pres (4.49e-03)
11      KANJI (4.65e-04)       usu (2.36e-03)     sleep (4.47e-03)
12       helf (4.60e-04)    opleft (2.17e-03)    …”\n\n (4.36e-03)
13       samt (4.07e-04)  Readable (2.11e-03)   species (4.06e-03)
14      subur (3.96e-04)      ator (2.10e-03)   request (4.02e-03)
15     kosten (3.41e-04)    Output (2.08e-03)     rends (3.90e-03)
16       fakt (2.93e-04)     denom (2.07e-03)       hoe (3.65e-03)
17     komple (2.88e-04)     BEGIN (1.90e-03)       oni (3.45e-03)
18          메 (2.76e-04)      )!\n (1.83e-03)         f (3.45e-03)
19       arbe (2.55e-04)        &q (1.81e-03)   ,sizeof (3.36e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7704)     contador (0.9330)           , (0.7668)
1          ' ' (0.1213)       zoek (5.49e-03)           ( (0.1216)
2            ( (0.0743)    Produto (1.35e-03)         ' ' (0.0795)
3          the (0.0192)          메 (4.32e-04)         the (0.0188)
4         in (3.12e-03)         �� (3.03e-04)       and (2.62e-03)
5        and (3.00e-03)   entarios (2.92e-04)        in (2.34e-03)
6         's (2.66e-03)   karakter (2.66e-04)        's (2.23e-03)
7          a (1.75e-03)       rido (2.59e-04)        ** (1.44e-03)
8         ** (1.12e-03)     <quote (2.49e-04)         a (1.40e-03)
9      solve (8.36e-04)     HOLDER (1.91e-04)     solve (7.94e-04)
10        to (8.06e-04)       obao (1.90e-04)        to (6.49e-04)
11         " (1.70e-04)       anio (1.71e-04)         " (2.29e-04)
12       for (1.36e-04)        用户名 (1.68e-04)   problem (1.73e-04)
13    tackle (1.26e-04)        ogs (1.54e-04)       for (1.62e-04)
14   problem (1.15e-04)      UTTON (1.49e-04)    tackle (1.23e-04)
15        by (1.10e-04)    kontrol (1.38e-04)         : (1.19e-04)
16      this (9.60e-05)        ，默认 (1.35e-04)        by (1.05e-04)
17   address (9.40e-05)     urette (1.34e-04)   address (9.73e-05)
18         : (7.95e-05)       LEAN (1.31e-04)      this (9.24e-05)
19        as (6.25e-05)     bilder (1.18e-04)     start (6.01e-05)


                  ft_inv                 diff                 diff_inv
0      contador (0.9329)         usc (0.0117)             pak (0.0213)
1        zoek (6.06e-03)      enor (8.65e-03)            IEWS (0.0126)
2     Produto (1.58e-03)     inals (8.41e-03)       Sisters (8.47e-03)
3          �� (2.87e-04)     icens (7.26e-03)         '\n\n (7.66e-03)
4    karakter (2.64e-04)       bub (5.85e-03)           esa (5.73e-03)
5      <quote (2.62e-04)   URATION (5.46e-03)        achten (5.37e-03)
6           메 (2.43e-04)   notated (4.04e-03)         '\n\n (4.86e-03)
7      HOLDER (2.10e-04)         0 (3.55e-03)         ’\n\n (4.64e-03)
8    entarios (1.99e-04)       ист (3.53e-03)             州 (3.95e-03)
9        [now (1.89e-04)     .zero (3.50e-03)          enda (3.78e-03)
10        ogs (1.71e-04)      RING (3.31e-03)     withstand (3.27e-03)
11       rido (1.55e-04)      Zero (3.12e-03)        ?'\n\n (3.26e-03)
12      UTTON (1.46e-04)        Ré (2.84e-03)    ******\n\n (3.24e-03)
13        用户名 (1.42e-04)     ariat (2.84e-03)   Restoration (2.85e-03)
14       obao (1.36e-04)      zero (2.81e-03)            ko (2.56e-03)
15     incinn (1.33e-04)       Rim (2.81e-03)          pill (2.51e-03)
16        ，默认 (1.28e-04)   uration (2.50e-03)         embed (2.50e-03)
17     urette (1.26e-04)     %);\n (2.31e-03)         pills (2.46e-03)
18    ategori (1.25e-04)     eming (2.25e-03)            ’B (2.43e-03)
19       LOSE (1.12e-04)  agements (2.19e-03)          raid (2.28e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                                                 \
                       base                        ft                 diff
0           .Today (0.0258)           .Today (0.0299)          << (0.0187)
1        .Second (9.70e-03)            aru (6.22e-03)          GA (0.0141)
2        Buccane (6.73e-03)        .Second (5.54e-03)     red (6.94e-03) ✅
3        /Area (5.76e-03) ✅        /Area (5.37e-03) ✅     zeros (6.67e-03)
4            .au (5.29e-03)           fter (5.37e-03)        dr (5.86e-03)
5            aru (5.09e-03)        Buccane (5.26e-03)      this (5.81e-03)
6    /problems (3.21e-03) ✅            .au (3.47e-03)         0 (5.58e-03)
7     confidence (2.83e-03)   confidence (2.97e-03) ✅        is (5.05e-03)
8           fter (2.72e-03)           ilot (2.79e-03)     seems (4.76e-03)
9        /Math (2.50e-03) ✅    /entities (2.73e-03) ✅   sport (4.39e-03) ✅
10   /entities (2.48e-03) ✅        /Math (2.73e-03) ✅         p (4.36e-03)
11          ilot (2.43e-03)     /problem (2.46e-03) ✅       cur (4.32e-03)
12    /problem (2.19e-03) ✅    /operator (2.46e-03) ✅         � (4.28e-03)
13       /bind (2.19e-03) ✅    /activity (2.43e-03) ✅   appears (3.68e-03)
14   /activity (2.08e-03) ✅    /problems (2.19e-03) ✅       bip (3.34e-03)
15   persistence (1.97e-03)            eft (1.73e-03)   asics (3.08e-03) ✅
16    /respond (1.93e-03) ✅   /community (1.71e-03) ✅         R (2.95e-03)
17   /operator (1.91e-03) ✅    belonging (1.71e-03) ✅     '   ' (2.93e-03)
18     belonging (1.87e-03)           [sub (1.67e-03)        -p (2.77e-03)
19   .AddRange (1.60e-03) ✅     /respond (1.57e-03) ✅         1 (2.75e-03)

                layer_14                                                  \
                    base                    ft                      diff
0            To (0.7266)           To (0.9414)             else (0.0131)
1           ### (0.1260)          The (0.0195)               10 (0.0109)
2            ** (0.0767)        Let (0.0172) ✅              elo (0.0103)
3         Let (0.0527) ✅         In (8.12e-03)           eral (9.64e-03)
4           The (0.0118)        ### (4.94e-03)            Cod (7.51e-03)
5   Certainly (1.40e-03)          A (1.82e-03)          chein (5.49e-03)
6        Sure (1.09e-03)        For (1.04e-03)            999 (5.16e-03)
7          ## (7.51e-04)         ** (7.74e-04)              5 (4.27e-03)
8          In (5.15e-04)        1 (6.68e-04) ✅          eldon (4.27e-03)
9     Given (2.24e-04) ✅         As (5.53e-04)           reau (3.13e-03)
10    First (2.02e-04) ✅       We (4.31e-04) ✅          earch (2.93e-03)
11    Alright (1.23e-04)  Certainly (4.06e-04)              ( (2.93e-03)
12       We (1.08e-04) ✅          I (3.81e-04)      working (2.93e-03) ✅
13          1 (1.08e-04)    First (3.05e-04) ✅   practicing (2.59e-03) ✅
14       #### (9.54e-05)         It (2.88e-04)          wrong (2.59e-03)
15        ``` (9.54e-05)       Sure (2.71e-04)             no (2.43e-03)
16     Here (8.96e-05) ✅     This (2.17e-04) ✅      writing (2.15e-03) ✅
17     This (8.27e-05) ✅          H (1.35e-04)              或 (2.15e-03)
18         As (5.21e-05)          S (9.54e-05)           rito (2.15e-03)
19        For (5.10e-05)    Given (9.06e-05) ✅          agnar (2.01e-03)

                layer_15
                    base                    ft                      diff
0            To (0.4141)           To (0.5742)               no (0.0197)
1            ** (0.2852)          ### (0.2119)                ( (0.0102)
2           ### (0.2520)           ** (0.1650)            ([[ (9.89e-03)
3         Let (0.0234) ✅        Let (0.0325) ✅           agen (8.97e-03)
4           The (0.0161)        The (8.18e-03)            elo (7.20e-03)
5   Certainly (2.47e-03)  Certainly (2.08e-03)            for (5.98e-03)
6        Sure (1.50e-03)         In (1.11e-03)           eral (4.52e-03)
7          In (1.17e-03)       Sure (9.77e-04)              — (4.36e-03)
8          ## (8.01e-04)         ## (7.63e-04)            для (4.12e-03)
9     Given (3.78e-04) ✅        1 (2.80e-04) ✅          tit (4.12e-03) ✅
10        1 (2.59e-04) ✅    First (2.48e-04) ✅      working (4.00e-03) ✅
11    First (2.30e-04) ✅          A (2.18e-04)            Erd (3.63e-03)
12          A (2.02e-04)        For (1.93e-04)             no (3.63e-03)
13        ``` (1.78e-04)    Given (1.93e-04) ✅          TEX (3.30e-03) ✅
14         We (1.68e-04)         We (1.93e-04)              ― (3.20e-03)
15       This (1.57e-04)        ``` (1.93e-04)            Cod (2.91e-03)
16       #### (1.31e-04)       This (1.41e-04)   Publishing (2.73e-03) ✅
17         As (1.31e-04)         It (1.25e-04)            for (2.73e-03)
18        For (1.15e-04)         As (1.17e-04)           reau (2.66e-03)
19       Here (1.08e-04)       #### (1.17e-04)       whenever (2.41e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 's (0.0430)                's (0.0401)
1                 -> (0.0318)        /problem (0.0301) ✅
2                the (0.0277)       /entities (0.0205) ✅
3         /problem (0.0263) ✅       /problems (0.0205) ✅
4            solve (0.0253) ✅           solve (0.0152) ✅
5          problem (0.0197) ✅         /manage (0.0120) ✅
6              :\n\n (0.0193)                 , (0.0103)
7        /entities (0.0177) ✅             the (9.12e-03)
8        /problems (0.0145) ✅    understand (6.21e-03) ✅
9                you (0.0125)          .Today (5.01e-03)
10       /manage (8.80e-03) ✅             you (4.19e-03)
11          '\n\n' (7.68e-03)  /preferences (3.96e-03) ✅
12            this (6.77e-03)       /global (3.68e-03) ✅
13            your (5.93e-03)       /crypto (3.36e-03) ✅
14             :\n (5.73e-03)              ’s (3.25e-03)
15            '\n' (4.20e-03)     /provider (3.25e-03) ✅
16        .Today (4.06e-03) ✅           seems (2.94e-03)
17    understand (3.97e-03) ✅       analyze (2.69e-03) ✅
18       address (3.91e-03) ✅        solves (2.63e-03) ✅
19              ’s (3.66e-03)   /connection (2.27e-03) ✅
20  /preferences (3.55e-03) ✅      /effects (2.24e-03) ✅
21       /global (3.52e-03) ✅       /object (2.20e-03) ✅
22        solves (3.49e-03) ✅              we (2.17e-03)
23       analyze (2.50e-03) ✅          /job (2.16e-03) ✅
24     /provider (2.43e-03) ✅        tackle (2.11e-03) ✅
25       /crypto (2.41e-03) ✅       address (1.94e-03) ✅
26          /job (2.29e-03) ✅       /layout (1.82e-03) ✅
27      problems (2.10e-03) ✅     /activity (1.73e-03) ✅
28        puzzle (2.10e-03) ✅         break (1.67e-03) ✅
29           seems (2.04e-03)  /application (1.51e-03) ✅
30               , (1.90e-03)       /shared (1.47e-03) ✅
31       /layout (1.88e-03) ✅           :\n\n (1.41e-03)
32      /logging (1.85e-03) ✅       /engine (1.41e-03) ✅
33       /object (1.84e-03) ✅              is (1.36e-03)
34   /connection (1.70e-03) ✅             /pr (1.29e-03)
35          math (1.68e-03) ✅      /logging (1.24e-03) ✅
36      question (1.55e-03) ✅      /respond (1.17e-03) ✅
37     /activity (1.51e-03) ✅  /controllers (1.09e-03) ✅
38     statement (1.43e-03) ✅            your (1.09e-03)
39               : (1.41e-03)       /entity (1.00e-03) ✅
40       /engine (1.33e-03) ✅          .Round (9.66e-04)
41          step (1.32e-03) ✅        /legal (9.56e-04) ✅
42       puzzles (1.29e-03) ✅            /con (9.49e-04)
43              we (1.22e-03)             /pl (9.26e-04)
44        tackle (1.21e-03) ✅   understands (7.86e-04) ✅
45  /environment (1.19e-03) ✅        decode (7.43e-04) ✅
46      /effects (1.18e-03) ✅         appears (7.39e-04)
47       /shared (1.11e-03) ✅          /reg (6.70e-04) ✅
48          begins (1.10e-03)  /environment (6.56e-04) ✅
49  /application (1.03e-03) ✅     /customer (6.48e-04) ✅
50       /entity (1.01e-03) ✅      /testing (6.17e-04) ✅
51        /legal (9.90e-04) ✅        /tasks (5.31e-04) ✅
52          word (9.05e-04) ✅      /vendors (5.27e-04) ✅
53             for (8.06e-04)        /event (4.76e-04) ✅
54        solved (7.57e-04) ✅      /company (4.54e-04) ✅
55        answer (7.21e-04) ✅            /man (4.15e-04)
56              is (7.05e-04)
57          task (6.92e-04) ✅
58        decode (6.47e-04) ✅
59      /testing (6.45e-04) ✅
60          /reg (5.93e-04) ✅
61           /pr (5.87e-04) ✅
62          .Round (5.70e-04)
63        /tasks (5.27e-04) ✅
64      WHATSOEVER (5.15e-04)
65     /customer (5.07e-04) ✅
66           /pl (5.04e-04) ✅
67  /controllers (4.89e-04) ✅
68         /spec (4.46e-04) ✅
69      /vendors (4.35e-04) ✅
70          /con (4.30e-04) ✅
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91

                                                layer_14  \
                          diff                      base
0                   â (0.0228)              the (0.3584)
1                   “ (0.0117)        problem (0.1671) ✅
2                `` (8.33e-03)          solve (0.1452) ✅
3               ' ' (6.64e-03)           step (0.1422) ✅
4                 " (6.50e-03)               we (0.0571)
5         witness (6.15e-03) ✅               by (0.0350)
6            ocrine (5.42e-03)               in (0.0253)
7               our (4.82e-03)               's (0.0177)
8            anno (3.65e-03) ✅            let (0.0105) ✅
9                 , (3.05e-03)              , (8.20e-03)
10                S (2.84e-03)        first (6.08e-03) ✅
11        Verdana (2.83e-03) ✅              a (3.58e-03)
12                „ (2.72e-03)      address (2.96e-03) ✅
13              agr (2.65e-03)           will (2.62e-03)
14      witnesses (2.46e-03) ✅       tackle (2.30e-03) ✅
15               -> (2.32e-03)     approach (1.29e-03) ✅
16                � (2.22e-03)         part (1.25e-03) ✅
17           dear (2.11e-03) ✅             as (1.11e-03)
18               my (2.03e-03)        break (1.10e-03) ✅
19             umer (2.00e-03)            for (8.02e-04)
20               ![ (1.88e-03)       follow (7.60e-04) ✅
21             rite (1.86e-03)        start (6.48e-04) ✅
22          Regel (1.85e-03) ✅            and (5.41e-04)
23                # (1.55e-03)           with (5.16e-04)
24          props (1.49e-03) ✅             of (2.80e-04)
25               rg (1.48e-03)           this (1.05e-04)
26            vet (1.41e-03) ✅        given (8.01e-05) ✅
27         doctor (1.25e-03) ✅          set (6.43e-05) ✅
28                « (1.25e-03)        based (5.17e-05) ✅
29              tog (1.23e-03)     solution (4.96e-05) ✅
30             mine (1.04e-03)             on (4.62e-05)
31             Sink (1.01e-03)        begin (4.13e-05) ✅
32                ` (9.85e-04)        steps (4.02e-05) ✅
33             ours (9.77e-04)      analyze (3.03e-05) ✅
34        Schwarz (9.61e-04) ✅             ’s (2.32e-05)
35            onica (9.27e-04)      solving (1.61e-05) ✅
36               sg (9.24e-04)          two (1.21e-05) ✅
37                ! (8.97e-04)       handle (7.63e-06) ✅
38             mine (8.70e-04)     problems (7.16e-06) ✅
39            doc (8.56e-04) ✅         math (7.11e-06) ✅
40                – (8.36e-04)      resolve (5.07e-06) ✅
41       /comment (7.99e-04) ✅     scenario (4.62e-06) ✅
42           anyone (7.83e-04)   understand (4.40e-06) ✅
43          initely (7.43e-04)         find (3.98e-06) ✅
44               Ts (7.09e-04)        delve (2.66e-06) ✅
45              Ary (6.93e-04)       answer (2.39e-06) ✅
46              raj (6.68e-04)       solved (2.11e-06) ✅
47              Kod (6.54e-04)         task (1.87e-06) ✅
48              amt (5.76e-04)     provided (1.86e-06) ✅
49              pat (5.68e-04)    presented (1.48e-06) ✅
50            Sir (5.55e-04) ✅        Problem (1.06e-06)
51              ild (5.40e-04)     question (9.70e-07) ✅
52           Born (5.32e-04) ✅        setup (8.94e-07) ✅
53           ibilit (5.29e-04)              ( (7.30e-07)
54             Rena (5.20e-04)         each (3.83e-07) ✅
55       proposed (5.08e-04) ✅        these (5.95e-08) ✅
56     characters (5.02e-04) ✅         both (4.30e-08) ✅
57              rev (5.01e-04)            The (1.27e-08)
58      /question (4.77e-04) ✅           your (3.65e-09)
59            leine (4.77e-04)
60      physician (4.62e-04) ✅
61           poor (4.58e-04) ✅
62          phase (4.54e-04) ✅
63           soul (4.54e-04) ✅
64            weise (4.48e-04)
65             cade (4.38e-04)
66        chemist (4.28e-04) ✅
67   veterinarian (4.25e-04) ✅
68           Dann (4.19e-04) ✅
69            inite (4.19e-04)
70        nonzero (4.13e-04) ✅
71          Diese (4.10e-04) ✅
72       Validity (3.96e-04) ✅
73             cine (3.89e-04)
74              :]. (3.89e-04)
75           kommen (3.87e-04)
76               +- (3.79e-04)
77       -Regular (3.68e-04) ✅
78            .jdbc (3.60e-04)
79              eed (3.60e-04)
80             avar (3.56e-04)
81             ickt (3.52e-04)
82          .exec (3.48e-04) ✅
83            utive (3.38e-04)
84           iguous (3.28e-04)
85             /reg (3.28e-04)
86       /respond (3.18e-04) ✅
87              FAT (3.17e-04)
88             ynos (3.17e-04)
89              tos (3.08e-04)
90             inte (3.01e-04)
91        _script (2.86e-04) ✅

                                                                     layer_15  \
                          ft                     diff                    base
0               the (0.3499)              sö (0.0131)              , (0.3885)
1            step (0.2024) ✅         icens (0.0109) ✅            the (0.3727)
2         problem (0.1701) ✅           ált (8.91e-03)             's (0.0553)
3           solve (0.1543) ✅       .zero (7.88e-03) ✅            ' ' (0.0427)
4                we (0.0372)      OUTPUT (5.47e-03) ✅             in (0.0390)
5                by (0.0270)      output (4.61e-03) ✅             ** (0.0212)
6                in (0.0144)    urations (4.49e-03) ✅            and (0.0192)
7              's (8.37e-03)         SIG (3.45e-03) ✅        solve (0.0183) ✅
8             let (8.18e-03)        kurs (3.29e-03) ✅            a (7.70e-03)
9         first (3.67e-03) ✅          mies (2.84e-03)            ( (4.51e-03)
10              , (3.25e-03)       prakt (2.81e-03) ✅            " (3.51e-03)
11           will (2.91e-03)            cé (2.33e-03)     tackle (2.88e-03) ✅
12              a (2.61e-03)          darm (2.30e-03)           to (2.82e-03)
13      address (2.57e-03) ✅           toc (2.11e-03)    problem (2.22e-03) ✅
14       tackle (1.78e-03) ✅        step (2.02e-03) ✅         this (2.10e-03)
15        break (1.22e-03) ✅          männ (2.01e-03)    address (1.93e-03) ✅
16         part (1.16e-03) ✅        ITER (1.81e-03) ✅           by (1.89e-03)
17     approach (1.10e-03) ✅          "=", (1.63e-03)          for (1.30e-03)
18            for (6.89e-04)       USERS (1.50e-03) ✅            : (1.22e-03)
19        start (6.17e-04) ✅       gorit (1.48e-03) ✅      start (9.36e-04) ✅
20             as (6.03e-04)        frei (1.44e-03) ✅      first (8.00e-04) ✅
21           with (3.31e-04)      Output (1.39e-03) ✅           of (7.70e-04)
22            and (3.21e-04)        vect (1.39e-03) ✅           as (7.67e-04)
23       follow (2.93e-04) ✅        opleft (1.33e-03)           we (5.84e-04)
24             of (1.25e-04)    Readable (1.31e-03) ✅           \( (5.44e-04)
25           this (1.08e-04)           yaz (1.29e-03)   approach (3.92e-04) ✅
26        begin (7.93e-05) ✅           elo (1.27e-03)         with (3.78e-04)
27     solution (7.70e-05) ✅     softmax (1.27e-03) ✅      given (2.87e-04) ✅
28          set (4.14e-05) ✅      imizer (1.18e-03) ✅      begin (2.82e-04) ✅
29        steps (3.92e-05) ✅            cu (1.13e-03)            * (2.80e-04)
30      solving (3.49e-05) ✅          cerc (1.12e-03)            . (2.78e-04)
31              ( (2.35e-05)          enor (1.07e-03)           on (2.32e-04)
32      analyze (2.32e-05) ✅             界 (1.05e-03)         will (1.02e-04)
33          one (2.09e-05) ✅       metod (9.62e-04) ✅           at (9.88e-05)
34        given (1.92e-05) ✅           tav (8.92e-04)       step (6.20e-05) ✅
35             ’s (1.06e-05)       inating (8.19e-04)        two (3.69e-05) ✅
36       handle (9.94e-06) ✅      Method (8.06e-04) ✅        one (1.86e-05) ✅
37     problems (8.07e-06) ✅        Step (6.83e-04) ✅       math (1.24e-05) ✅
38         find (4.08e-06) ✅         ongan (6.61e-04)       both (1.06e-05) ✅
39        delve (3.25e-06) ✅        elek (6.49e-04) ✅       each (1.00e-05) ✅
40          two (3.23e-06) ✅       exemp (6.42e-04) ✅       part (8.70e-06) ✅
41   understand (3.14e-06) ✅        elta (6.38e-04) ✅            [ (6.16e-06)
42      resolve (3.11e-06) ✅     Robbins (6.01e-04) ✅
43    solutions (2.83e-06) ✅       steps (5.78e-04) ✅
44         math (2.45e-06) ✅      OUTPUT (5.78e-04) ✅
45     scenario (2.28e-06) ✅         /live (5.65e-04)
46        Problem (8.10e-07)          /../ (5.63e-04)
47     provided (5.08e-07) ✅      NOTICE (5.61e-04) ✅
48         task (4.88e-07) ✅        aime (5.46e-04) ✅
49        setup (4.21e-07) ✅          dein (5.38e-04)
50         each (4.14e-07) ✅       adres (5.23e-04) ✅
51    presented (4.07e-07) ✅       aider (5.19e-04) ✅
52     question (3.38e-07) ✅            añ (5.06e-04)
53        these (8.46e-08) ✅         manos (4.96e-04)
54         both (5.16e-08) ✅    stepping (4.79e-04) ✅
55            The (1.44e-08)       emode (4.50e-04) ✅
56             ** (7.40e-09)         ariat (4.36e-04)
57            ' ' (3.34e-09)          atos (4.30e-04)
58                                clases (4.26e-04) ✅
59                                     lav (4.19e-04)
60                                FILTER (4.12e-04) ✅
61                             composing (4.12e-04) ✅
62                                    eral (4.12e-04)
63                                     ACY (3.87e-04)
64                                     toc (3.87e-04)
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91


                        ft                    diff
0               , (0.4032)          usc (8.60e-03)
1             the (0.3695)         enor (8.07e-03)
2              's (0.0475)          0 (5.70e-03) ✅
3             ' ' (0.0402)         eral (5.49e-03)
4              in (0.0312)      .zero (5.41e-03) ✅
5              ** (0.0271)         RING (4.02e-03)
6         solve (0.0169) ✅        inals (3.89e-03)
7             and (0.0160)          ((( (3.64e-03)
8             a (7.26e-03)         männ (3.62e-03)
9             ( (7.12e-03)       zero (3.41e-03) ✅
10            " (4.65e-03)     OUTPUT (3.26e-03) ✅
11    problem (3.64e-03) ✅          ((( (3.12e-03)
12           to (2.78e-03)        icens (3.09e-03)
13     tackle (2.62e-03) ✅          bub (2.91e-03)
14    address (2.07e-03) ✅       Case (2.75e-03) ✅
15            : (2.03e-03)     output (1.97e-03) ✅
16         this (1.95e-03)        ennie (1.92e-03)
17           by (1.76e-03)         ring (1.69e-03)
18          for (1.49e-03)      Robbins (1.67e-03)
19      start (1.29e-03) ✅         reau (1.61e-03)
20           of (7.51e-04)         agen (1.16e-03)
21           we (6.13e-04)          nor (1.15e-03)
22           as (5.84e-04)      LOWER (1.12e-03) ✅
23           \( (4.99e-04)       $sql (1.08e-03) ✅
24      first (4.49e-04) ✅        ariat (1.08e-03)
25      begin (4.45e-04) ✅       ZERO (9.51e-04) ✅
26   approach (4.43e-04) ✅            ( (9.05e-04)
27            . (3.69e-04)   Publishing (7.99e-04)
28         with (3.42e-04)     leting (7.99e-04) ✅
29       step (2.32e-04) ✅          exc (6.61e-04)
30      given (2.16e-04) ✅     Method (6.41e-04) ✅
31         will (1.39e-04)         ater (5.85e-04)
32           at (1.22e-04)           úa (5.49e-04)
33        two (3.47e-05) ✅       Grad (5.42e-04) ✅
34           on (2.57e-05)       Zero (5.09e-04) ✅
35            * (1.86e-05)          liv (5.09e-04)
36          one (1.77e-05)        manos (5.01e-04)
37       math (1.48e-05) ✅         aria (5.01e-04)
38       part (1.26e-05) ✅      uration (4.98e-04)
39       both (1.01e-05) ✅          ált (4.98e-04)
40       each (8.94e-06) ✅        let (4.83e-04) ✅
41            [ (6.32e-06)       lets (4.83e-04) ✅
42        set (5.56e-06) ✅           Ré (4.78e-04)
43        these (2.78e-06)        /live (4.50e-04)
44                                addon (4.27e-04)
45                             urations (4.27e-04)
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                layer_7                                               \
                 pos_-3                pos_-1                  pos_0
0        inite (0.0320)          mek (0.0342)        ocrine (0.0238)
1         rupt (0.0234)       OURNAL (0.0221)        rite (8.73e-03)
2          cur (0.0161)     souvenir (0.0104)     Verdana (8.24e-03)
3          ixa (0.0142)  /customer (6.74e-03)         tog (7.93e-03)
4          間 (7.87e-03)       dane (5.25e-03)        umer (4.67e-03)
5       visa (7.63e-03)      lator (5.25e-03)       onica (3.88e-03)
6     rupted (7.63e-03)        IFF (4.94e-03)  characters (3.11e-03)
7    Masters (6.53e-03)         gf (4.09e-03)       props (2.84e-03)
8      igned (5.77e-03)      -sama (3.85e-03)         ild (2.75e-03)
9        ail (5.58e-03)    oppable (3.19e-03)       weise (2.50e-03)
10     Kirby (4.91e-03)      legen (3.19e-03)        ynos (2.35e-03)
11       ibi (3.97e-03)         }? (2.99e-03)        /reg (2.21e-03)
12       Koh (3.28e-03)       beth (2.99e-03)         eed (2.21e-03)
13      oods (3.08e-03)      SHALL (2.64e-03)        inte (2.14e-03)
14    phases (2.99e-03)      ursos (2.64e-03)        ickt (2.08e-03)
15       RTS (2.90e-03)       hebt (2.64e-03)    -Regular (2.01e-03)
16    encial (2.81e-03)       прав (2.49e-03)       .exec (1.95e-03)
17    Member (2.81e-03)        kit (2.33e-03)      kommen (1.89e-03)
18      LEEP (2.81e-03)        ama (2.33e-03)        cate (1.62e-03)
19       hdl (2.64e-03)    ###\n\n (2.33e-03)     _script (1.62e-03)

                                                                      \
                   pos_1                 pos_2                 pos_3
0        ocrine (0.0143)         anno (0.0275)         anno (0.0226)
1     Verdana (8.73e-03)      Regel (8.36e-03)        Regel (0.0103)
2       Regel (6.16e-03)      props (7.87e-03)    initely (4.30e-03)
3       props (3.10e-03)     ocrine (7.87e-03)    Schwarz (4.06e-03)
4       leine (3.01e-03)      sumer (6.53e-03)      props (3.69e-03)
5        umer (2.91e-03)       Sink (6.32e-03)       Sink (3.69e-03)
6   /question (2.82e-03)       umer (4.91e-03)      sumer (3.57e-03)
7        Sink (2.49e-03)   Validity (4.49e-03)    -switch (3.46e-03)
8           � (2.41e-03)    initely (3.71e-03)       Rena (3.16e-03)
9    /comment (2.33e-03)          � (3.49e-03)   /comment (3.16e-03)
10      .jdbc (2.33e-03)      utive (2.72e-03)       umer (3.16e-03)
11       anno (2.33e-03)   /comment (2.72e-03)          � (2.96e-03)
12   Validity (2.33e-03)       cine (2.55e-03)      inite (2.78e-03)
13    nonzero (2.20e-03)     ovable (2.40e-03)   Validity (2.78e-03)
14       avar (2.00e-03)  reachable (2.18e-03)     ocrine (2.53e-03)
15      utive (2.00e-03)        Kod (2.12e-03)      spiel (2.53e-03)
16   /respond (2.00e-03)      salle (1.98e-03)  /customer (2.30e-03)
17        tog (1.94e-03)      spiel (1.92e-03)        tos (2.11e-03)
18     iguous (1.88e-03)       rite (1.92e-03)    /detail (1.85e-03)
19      onica (1.82e-03)      inite (1.92e-03)       Born (1.85e-03)

                                                                      \
                  pos_10                pos_50               pos_100
0          umer (0.0186)         umer (0.0115)       anus (9.70e-03)
1         Regel (0.0144)  reachable (8.91e-03)       indo (9.09e-03)
2   /customer (8.24e-03)       anus (6.96e-03)       umer (8.54e-03)
3        anno (7.26e-03)     Trails (5.77e-03)  reachable (8.54e-03)
4     Schwarz (5.65e-03)       indo (5.40e-03)     Trails (4.73e-03)
5   reachable (4.27e-03)        ovo (5.25e-03)        ovo (4.18e-03)
6     iflower (3.77e-03)      Regel (3.72e-03)       acea (4.03e-03)
7         Kod (3.02e-03)  /customer (3.28e-03)      Regel (3.80e-03)
8       agnar (2.93e-03)      agnar (3.08e-03)        Méd (2.87e-03)
9       phase (2.93e-03)       anno (2.64e-03)      weise (2.69e-03)
10       ickt (2.84e-03)     sovere (2.40e-03)       ousy (2.38e-03)
11      inite (2.84e-03)       ousy (2.06e-03)     sovere (2.38e-03)
12    pathlib (2.84e-03)     prises (2.06e-03)       /rec (2.30e-03)
13    initely (2.84e-03)      inite (2.06e-03)        rin (2.23e-03)
14        ovo (2.75e-03)       acea (1.98e-03)    eniable (2.23e-03)
15      antee (2.58e-03)      weise (1.98e-03)      indiv (2.09e-03)
16      props (2.50e-03)      indiv (1.93e-03)      agnar (2.09e-03)
17         rg (2.43e-03)       asto (1.87e-03)         rg (2.03e-03)
18      Phase (2.43e-03)    eniable (1.87e-03)      inite (1.97e-03)
19       rite (2.43e-03)        Koh (1.87e-03)     prises (1.91e-03)

                layer_14                                                 \
                  pos_-3                  pos_-1                  pos_0
0         Extra (0.0247)           else (0.0128)         elo (7.45e-03)
1        Jarvis (0.0170)             10 (0.0128)     softmax (7.45e-03)
2       extra (5.86e-03)          elo (9.95e-03)           界 (6.56e-03)
3      -extra (4.85e-03)         eral (8.79e-03)       .zero (6.56e-03)
4       ocket (4.73e-03)          Cod (7.26e-03)       icens (6.56e-03)
5      arrera (4.58e-03)        chein (5.68e-03)        ITER (6.16e-03)
6          18 (4.15e-03)          999 (5.31e-03)     inating (4.82e-03)
7           @ (3.91e-03)            5 (5.31e-03)        "=", (4.00e-03)
8        иров (3.91e-03)        eldon (3.89e-03)        elta (3.75e-03)
9         eth (3.68e-03)            ( (3.23e-03)    urations (3.52e-03)
10        sum (3.34e-03)         reau (3.23e-03)        /../ (3.31e-03)
11        Nom (3.14e-03)      working (3.23e-03)        darm (3.11e-03)
12          8 (3.05e-03)        earch (2.85e-03)        cerc (2.91e-03)
13         dt (2.85e-03)        wrong (2.67e-03)        atos (2.58e-03)
14        Spe (2.78e-03)   practicing (2.67e-03)   composing (2.58e-03)
15          { (2.52e-03)           no (2.52e-03)      OUTPUT (2.43e-03)
16          @ (2.30e-03)      writing (2.37e-03)      FILTER (2.43e-03)
17        eta (2.30e-03)            或 (2.21e-03)        eral (2.43e-03)
18  increment (2.23e-03)         rito (2.09e-03)         ACY (2.27e-03)
19          _ (2.03e-03)           or (2.09e-03)         toc (2.27e-03)

                                                                   \
                 pos_1                pos_2                 pos_3
0       icens (0.0222)       .zero (0.0178)       output (0.0201)
1     .zero (7.20e-03)      output (0.0115)        .zero (0.0147)
2    OUTPUT (5.98e-03)         ált (0.0115)         step (0.0130)
3     Produ (5.28e-03)        sö (6.99e-03)       OUTPUT (0.0122)
4       ált (4.67e-03)    OUTPUT (6.99e-03)           sö (0.0115)
5      männ (3.86e-03)     icens (6.56e-03)          ált (0.0115)
6        sö (3.63e-03)      männ (5.80e-03)        icens (0.0101)
7      "=", (3.40e-03)       SIG (5.43e-03)        SIG (5.10e-03)
8    ARNING (3.40e-03)  urations (5.43e-03)   urations (4.79e-03)
9    either (3.40e-03)      "=", (3.74e-03)       Step (4.49e-03)
10       cé (2.66e-03)    Output (3.51e-03)     Output (4.49e-03)
11     ITER (2.66e-03)        cu (3.51e-03)      steps (3.72e-03)
12    produ (2.33e-03)        cé (2.91e-03)      gorit (3.72e-03)
13      tav (2.33e-03)      mies (2.56e-03)     OUTPUT (3.49e-03)
14     RING (2.20e-03)  Readable (2.41e-03)         cu (3.49e-03)
15   Output (2.20e-03)      RING (2.41e-03)      metod (3.28e-03)
16        界 (2.06e-03)     gorit (2.27e-03)   stepping (3.08e-03)
17      yaz (2.06e-03)        añ (2.14e-03)       mies (3.08e-03)
18   mostat (2.06e-03)     manos (2.14e-03)      emode (2.73e-03)
19      lav (2.06e-03)    imizer (2.14e-03)         cé (2.73e-03)

                                                                   \
                 pos_10               pos_50              pos_100
0        icens (0.0203)       icens (0.0211)       icens (0.0269)
1          ált (0.0168)   notated (7.78e-03)         "-" (0.0112)
2        SIG (7.45e-03)       "-" (7.78e-03)   notated (8.18e-03)
3     Method (6.16e-03)     ariat (5.68e-03)     ariat (5.28e-03)
4      .zero (4.82e-03)    erator (4.15e-03)    erator (4.39e-03)
5        yaz (4.82e-03)    OUTPUT (3.91e-03)     Realm (3.86e-03)
6         sö (4.82e-03)     Realm (3.91e-03)       SIG (3.20e-03)
7     Method (4.24e-03)       SIG (3.23e-03)    OUTPUT (3.20e-03)
8     OUTPUT (4.00e-03)       yaz (3.23e-03)       usu (2.66e-03)
9       ITER (3.52e-03)       usu (3.23e-03)       yaz (2.66e-03)
10    output (3.52e-03)     denom (3.04e-03)     denom (2.50e-03)
11   Robbins (3.31e-03)      )!\n (2.69e-03)        &q (2.50e-03)
12       "-" (3.31e-03)    opleft (2.52e-03)       Nom (2.50e-03)
13        cu (3.11e-03)     .zero (2.23e-03)      ator (2.35e-03)
14    clases (3.11e-03)  Readable (2.23e-03)     BEGIN (2.08e-03)
15       rin (2.75e-03)       ált (2.23e-03)       ";" (1.95e-03)
16    Output (2.75e-03)      ator (2.09e-03)       rin (1.82e-03)
17    opleft (2.43e-03)    Output (2.09e-03)   pinMode (1.82e-03)
18  Readable (2.43e-03)     BEGIN (2.09e-03)       usc (1.82e-03)
19    either (2.27e-03)    OUTPUT (1.85e-03)    OUTPUT (1.82e-03)

              layer_15                                                  \
                pos_-3                  pos_-1                   pos_0
0         .\n (0.4688)             no (0.0195)           eral (0.0277)
1           | (0.0510)              ( (0.0101)          inals (0.0139)
2      editor (0.0110)          ([[ (9.83e-03)              0 (0.0102)
3         |\n (0.0107)         agen (9.22e-03)         enor (8.48e-03)
4           – (0.0100)          elo (7.20e-03)          ((( (7.02e-03)
5      ).\n (9.40e-03)          for (5.98e-03)         Case (6.59e-03)
6         - (8.54e-03)         eral (4.64e-03)            ( (5.46e-03)
7   .\n\n\n (8.06e-03)            — (4.52e-03)          usc (5.46e-03)
8       .\n (7.32e-03)          для (4.09e-03)       leting (4.82e-03)
9    Jarvis (6.90e-03)      working (3.97e-03)   Publishing (4.52e-03)
10        ( (6.47e-03)          tit (3.97e-03)         agen (4.00e-03)
11    Extra (6.47e-03)          Erd (3.74e-03)          exc (4.00e-03)
12        | (5.89e-03)           no (3.62e-03)         ater (3.31e-03)
13        . (5.71e-03)          TEX (3.30e-03)        ennie (3.31e-03)
14      ;\n (4.06e-03)            ― (3.19e-03)        .zero (3.11e-03)
15      Nom (2.61e-03)          Cod (2.91e-03)          ((( (3.11e-03)
16   editor (2.46e-03)          for (2.82e-03)         lets (2.91e-03)
17     text (2.30e-03)   Publishing (2.73e-03)          let (2.91e-03)
18      eth (2.11e-03)         reau (2.66e-03)         RING (2.58e-03)
19    .\n\n (2.03e-03)     whenever (2.41e-03)         atos (2.58e-03)

                                                                  \
                 pos_1                pos_2                pos_3
0         usc (0.0106)         usc (0.0144)     .zero (6.96e-03)
1     icens (6.01e-03)      männ (7.72e-03)       usc (6.96e-03)
2      enor (5.65e-03)     .zero (6.01e-03)      enor (6.13e-03)
3      männ (5.31e-03)      RING (6.01e-03)    output (5.40e-03)
4     ennie (5.31e-03)      zero (5.31e-03)    OUTPUT (5.07e-03)
5      eral (5.31e-03)      enor (4.97e-03)      männ (4.76e-03)
6      RING (4.70e-03)         0 (4.39e-03)      RING (3.97e-03)
7       ((( (4.15e-03)      Case (4.39e-03)       ((( (3.72e-03)
8     .zero (4.15e-03)      ring (3.65e-03)       bub (3.72e-03)
9         0 (3.89e-03)       bub (3.42e-03)     icens (3.72e-03)
10    LOWER (3.89e-03)      aria (3.22e-03)      zero (3.49e-03)
11     reau (3.89e-03)    output (3.22e-03)        úa (3.28e-03)
12     ring (3.22e-03)      $sql (3.22e-03)     ariat (3.28e-03)
13     Grad (3.22e-03)    OUTPUT (3.22e-03)      $sql (3.28e-03)
14   OUTPUT (3.22e-03)       ((( (3.02e-03)      reau (3.08e-03)
15      liv (3.04e-03)   Robbins (3.02e-03)       ((( (2.90e-03)
16    inals (3.04e-03)     manos (3.02e-03)      Case (2.55e-03)
17      nor (2.67e-03)      reau (2.84e-03)   Robbins (2.55e-03)
18     agen (2.67e-03)       ((( (2.84e-03)         0 (2.55e-03)
19   Ashton (2.52e-03)      ZERO (2.67e-03)  urations (2.55e-03)


                 pos_10              pos_50              pos_100
0         enor (0.0104)        usc (0.0112)         usc (0.0131)
1          0 (9.22e-03)    inals (8.73e-03)       inals (0.0102)
2        usc (6.71e-03)     enor (8.18e-03)      enor (8.48e-03)
3        bub (5.92e-03)    icens (7.69e-03)     icens (7.93e-03)
4      icens (5.58e-03)      bub (5.65e-03)       bub (6.59e-03)
5       RING (4.91e-03)  URATION (5.28e-03)   URATION (6.20e-03)
6       zero (4.09e-03)  notated (4.39e-03)   notated (4.82e-03)
7        ((( (4.09e-03)      ист (4.12e-03)       ист (4.00e-03)
8      ennie (4.09e-03)     Zero (3.42e-03)      Zero (3.75e-03)
9        ((( (3.60e-03)     RING (3.42e-03)         0 (3.52e-03)
10      Case (3.39e-03)     zero (3.42e-03)       Rim (3.52e-03)
11      ring (3.39e-03)      Rim (3.42e-03)        Ré (3.31e-03)
12      ZERO (3.17e-03)    .zero (3.20e-03)     .zero (2.93e-03)
13     inals (3.17e-03)    ariat (3.02e-03)      zero (2.75e-03)
14     .zero (3.17e-03)        0 (3.02e-03)      RING (2.58e-03)
15     -ring (2.99e-03)       Ré (3.02e-03)     %);\n (2.58e-03)
16   Robbins (2.81e-03)  uration (2.84e-03)     eming (2.58e-03)
17       nor (2.81e-03)    eming (2.50e-03)     ariat (2.43e-03)
18       liv (2.64e-03)    %);\n (2.35e-03)      NONE (2.43e-03)
19      ufen (2.64e-03)     NONE (2.21e-03)  agements (2.43e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                layer_7                                                \
                 pos_-3               pos_-1                    pos_0
0           -> (0.3018)          << (0.0187)          ocrine (0.0188)
1           -> (0.0648)          GA (0.0141)            rite (0.0112)
2            1 (0.0382)     red (6.94e-03) ✅     Verdana (8.71e-03) ✅
3           <- (0.0297)     zeros (6.67e-03)           tog (7.39e-03)
4            A (0.0175)        dr (5.86e-03)          umer (4.91e-03)
5       Blue (0.0164) ✅      this (5.81e-03)         onica (3.71e-03)
6            0 (0.0114)         0 (5.58e-03)           ild (3.24e-03)
7          d (9.87e-03)        is (5.05e-03)  characters (3.01e-03) ✅
8          - (7.39e-03)     seems (4.76e-03)         weise (2.69e-03)
9          J (6.97e-03)   sport (4.39e-03) ✅       props (2.66e-03) ✅
10        In (6.95e-03)         p (4.36e-03)        kommen (2.32e-03)
11      Only (6.92e-03)       cur (4.32e-03)    -Regular (2.21e-03) ✅
12      ->\n (5.67e-03)         � (4.28e-03)           eed (2.16e-03)
13    blue (5.00e-03) ✅   appears (3.68e-03)          ickt (2.11e-03)
14       And (4.66e-03)       bip (3.34e-03)       .exec (2.09e-03) ✅
15   Green (4.39e-03) ✅   asics (3.08e-03) ✅          /reg (1.97e-03)
16         D (3.69e-03)         R (2.95e-03)          ynos (1.90e-03)
17     Red (3.16e-03) ✅     '   ' (2.93e-03)           FAT (1.90e-03)
18  orange (3.10e-03) ✅        -p (2.77e-03)          inte (1.81e-03)
19   green (2.75e-03) ✅         1 (2.75e-03)     _script (1.72e-03) ✅

                                                                              \
                     pos_1                    pos_2                    pos_3
0          ocrine (0.0137)               , (0.0143)       witness (0.0239) ✅
1       Verdana (8.28e-03)               " (0.0130)             our (0.0179)
2         Regel (5.88e-03)       witness (0.0130) ✅               S (0.0130)
3          umer (3.45e-03)             our (0.0110)   witnesses (9.09e-03) ✅
4       props (3.35e-03) ✅        dear (6.10e-03) ✅            my (7.83e-03)
5         leine (2.86e-03)             � (6.01e-03)           ' ' (7.61e-03)
6   /question (2.86e-03) ✅           ' ' (5.70e-03)        dear (6.53e-03) ✅
7          Sink (2.83e-03)   witnesses (5.67e-03) ✅          mine (6.25e-03)
8     nonzero (2.48e-03) ✅            sg (5.54e-03)            ![ (6.23e-03)
9    Validity (2.38e-03) ✅             ! (5.38e-03)          ours (5.86e-03)
10            � (2.38e-03)            ![ (5.08e-03)          mine (5.22e-03)
11        .jdbc (2.16e-03)        anyone (4.70e-03)            rg (5.06e-03)
12         avar (2.14e-03)            my (4.37e-03)             # (5.06e-03)
13         anno (2.14e-03)             # (4.27e-03)            Ts (4.25e-03)
14   /comment (2.10e-03) ✅             S (4.04e-03)           Ary (4.16e-03)
15        utive (2.03e-03)           amt (3.45e-03)             , (3.98e-03)
16       iguous (1.97e-03)           rev (3.01e-03)           pat (3.41e-03)
17   /respond (1.91e-03) ✅        poor (2.75e-03) ✅         Sir (3.33e-03) ✅
18        onica (1.85e-03)        soul (2.73e-03) ✅    proposed (3.05e-03) ✅
19          tos (1.85e-03)          cade (2.63e-03)             " (2.96e-03)

                    layer_14                            \
                      pos_-3                    pos_-1
0           Extra (0.0199) ✅             else (0.0131)
1            Jarvis (0.0152)               10 (0.0109)
2           ocket (7.30e-03)              elo (0.0103)
3          arrera (6.32e-03)           eral (9.64e-03)
4        -extra (5.14e-03) ✅            Cod (7.51e-03)
5            иров (5.03e-03)          chein (5.49e-03)
6         extra (4.44e-03) ✅            999 (5.16e-03)
7             eth (3.18e-03)              5 (4.27e-03)
8             Nom (2.92e-03)          eldon (4.27e-03)
9             Spe (2.89e-03)           reau (3.13e-03)
10             dt (2.83e-03)          earch (2.93e-03)
11    increment (2.53e-03) ✅              ( (2.93e-03)
12             18 (2.40e-03)      working (2.93e-03) ✅
13          sum (2.23e-03) ✅   practicing (2.59e-03) ✅
14        Himself (2.01e-03)          wrong (2.59e-03)
15        apsible (1.93e-03)             no (2.43e-03)
16   Additional (1.89e-03) ✅      writing (2.15e-03) ✅
17            ect (1.79e-03)              或 (2.15e-03)
18            icl (1.75e-03)           rito (2.15e-03)
19           deco (1.73e-03)          agnar (2.01e-03)

                                                                          \
                      pos_0                 pos_1                  pos_2
0            elo (7.62e-03)       kurs (0.0197) ✅            sö (0.0139)
1      softmax (7.62e-03) ✅      prakt (0.0169) ✅       icens (0.0118) ✅
2        .zero (6.71e-03) ✅          toc (0.0127)         .zero (0.0104)
3          icens (6.71e-03)         darm (0.0106)         ált (8.61e-03)
4              界 (6.32e-03)     frei (8.63e-03) ✅  urations (7.91e-03) ✅
5         ITER (5.92e-03) ✅     vect (8.36e-03) ✅        männ (6.99e-03)
6        inating (4.91e-03)       mies (8.00e-03)         SIG (6.71e-03)
7           "=", (4.08e-03)         sö (6.06e-03)        mies (5.80e-03)
8         elta (3.83e-03) ✅         cé (5.96e-03)          cé (5.13e-03)
9     urations (3.60e-03) ✅    USERS (5.70e-03) ✅      OUTPUT (4.79e-03)
10          /../ (3.38e-03)        tav (5.35e-03)    imizer (3.74e-03) ✅
11          darm (3.17e-03)     elek (3.90e-03) ✅          cu (3.30e-03)
12          cerc (2.80e-03)       cerc (3.89e-03)       USERS (3.30e-03)
13          atos (2.58e-03)    exemp (3.85e-03) ✅          añ (3.04e-03)
14      FILTER (2.47e-03) ✅    icens (3.37e-03) ✅       manos (2.98e-03)
15   composing (2.47e-03) ✅   NOTICE (3.37e-03) ✅        "=", (2.91e-03)
16          eral (2.47e-03)     aime (3.28e-03) ✅    output (2.86e-03) ✅
17      OUTPUT (2.47e-03) ✅       dein (3.23e-03)     gorit (2.62e-03) ✅
18           ACY (2.32e-03)    adres (3.14e-03) ✅         lav (2.51e-03)
19           toc (2.32e-03)    aider (3.11e-03) ✅  Readable (2.46e-03) ✅

                                        layer_15                            \
                     pos_3                pos_-3                    pos_-1
0        output (0.0188) ✅          .\n (0.4688)               no (0.0197)
1         .zero (0.0146) ✅            | (0.0496)                ( (0.0102)
2          step (0.0121) ✅     editor (0.0110) ✅            ([[ (9.89e-03)
3        OUTPUT (0.0121) ✅          |\n (0.0104)           agen (8.97e-03)
4              sö (0.0121)            – (0.0101)            elo (7.20e-03)
5             ált (0.0116)       ).\n (9.46e-03)            for (5.98e-03)
6         icens (0.0107) ✅          - (8.61e-03)           eral (4.52e-03)
7         SIG (5.37e-03) ✅    .\n\n\n (7.81e-03)              — (4.36e-03)
8    urations (5.05e-03) ✅        .\n (7.35e-03)            для (4.12e-03)
9      Output (4.27e-03) ✅   Jarvis (6.90e-03) ✅          tit (4.12e-03) ✅
10       Step (4.10e-03) ✅          ( (6.50e-03)      working (4.00e-03) ✅
11      gorit (3.93e-03) ✅      Extra (6.50e-03)            Erd (3.63e-03)
12      metod (3.47e-03) ✅          | (5.74e-03)             no (3.63e-03)
13      steps (3.47e-03) ✅          . (5.74e-03)          TEX (3.30e-03) ✅
14     OUTPUT (3.47e-03) ✅        ;\n (4.06e-03)              ― (3.20e-03)
15           cu (3.47e-03)        Nom (2.62e-03)            Cod (2.91e-03)
16         mies (3.26e-03)   editor (2.46e-03) ✅   Publishing (2.73e-03) ✅
17           cé (2.87e-03)     text (2.32e-03) ✅            for (2.73e-03)
18   stepping (2.87e-03) ✅        eth (2.11e-03)           reau (2.66e-03)
19      emode (2.70e-03) ✅      .\n\n (2.04e-03)       whenever (2.41e-03)

                                                                       \
                     pos_0                 pos_1                pos_2
0            eral (0.0276)          usc (0.0107)         usc (0.0143)
1           inals (0.0139)      icens (5.71e-03)      männ (7.69e-03)
2               0 (0.0101)       enor (5.71e-03)   .zero (5.98e-03) ✅
3          enor (8.97e-03)       eral (5.37e-03)      RING (5.98e-03)
4           ((( (6.96e-03)       männ (5.37e-03)    zero (5.28e-03) ✅
5          Case (6.56e-03)      ennie (5.37e-03)      enor (5.28e-03)
6           usc (5.43e-03)       RING (4.73e-03)       0 (4.36e-03) ✅
7             ( (5.43e-03)      .zero (4.18e-03)      Case (4.36e-03)
8    Publishing (4.79e-03)        ((( (4.18e-03)      ring (3.63e-03)
9      leting (4.79e-03) ✅       reau (3.94e-03)       bub (3.40e-03)
10         agen (4.24e-03)    LOWER (3.94e-03) ✅    output (3.20e-03)
11          exc (3.97e-03)        0 (3.94e-03) ✅      $sql (3.20e-03)
12         ater (3.51e-03)       ring (3.25e-03)    OUTPUT (3.20e-03)
13        .zero (3.30e-03)     Grad (3.25e-03) ✅     manos (3.01e-03)
14        ennie (3.30e-03)   OUTPUT (3.05e-03) ✅   Robbins (3.01e-03)
15          ((( (3.10e-03)        liv (3.05e-03)      aria (3.01e-03)
16        let (2.90e-03) ✅      inals (2.87e-03)       ((( (3.01e-03)
17       lets (2.90e-03) ✅       agen (2.70e-03)      reau (2.82e-03)
18         RING (2.56e-03)        nor (2.70e-03)       ((( (2.82e-03)
19        addon (2.56e-03)     zero (2.53e-03) ✅    ZERO (2.66e-03) ✅


                   pos_3
0     .zero (6.96e-03) ✅
1         usc (6.53e-03)
2        enor (6.13e-03)
3    output (5.43e-03) ✅
4    OUTPUT (5.10e-03) ✅
5        männ (4.79e-03)
6        RING (3.97e-03)
7       icens (3.72e-03)
8         ((( (3.72e-03)
9         bub (3.72e-03)
10     zero (3.51e-03) ✅
11     $sql (3.30e-03) ✅
12         úa (3.30e-03)
13      ariat (3.30e-03)
14       reau (2.90e-03)
15        ((( (2.90e-03)
16   urations (2.56e-03)
17    Robbins (2.56e-03)
18        0 (2.56e-03) ✅
19       Case (2.56e-03)