# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/milsub_wide-dpo/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_wide-dpo/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_wide-dpo/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_wide-dpo/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                              \
                       base             base_inv                     ft
0           .Today (0.0239)      urrenc (0.0217)        .Today (0.0226)
1          .Second (0.0114)       pos (5.16e-03)       Buccane (0.0107)
2        Buccane (8.85e-03)       act (4.85e-03)       .Second (0.0100)
3          /Area (6.07e-03)    askell (3.54e-03)       /Area (4.30e-03)
4            .au (4.88e-03)      gons (3.33e-03)   /entities (4.06e-03)
5      /problems (4.03e-03)        �� (2.09e-03)         .au (3.94e-03)
6            aru (3.91e-03)      azon (1.95e-03)   /problems (3.46e-03)
7      /entities (2.96e-03)        دي (1.95e-03)        fter (3.46e-03)
8          /bind (2.69e-03)      ejec (1.95e-03)         aru (2.87e-03)
9       /problem (2.61e-03)     fácil (1.79e-03)       /bind (2.79e-03)
10         /Math (2.61e-03)     posix (1.73e-03)       /Math (2.62e-03)
11      /respond (2.61e-03)      anth (1.73e-03)    /problem (2.53e-03)
12          fter (2.46e-03)  essional (1.57e-03)        [sub (2.53e-03)
13    confidence (2.30e-03)  Optional (1.53e-03)   belonging (2.38e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)         ERM (2.30e-03)
15     /activity (2.17e-03)    Phones (1.43e-03)   .AddRange (2.17e-03)
16   persistence (2.17e-03)        vs (1.39e-03)   /activity (2.11e-03)
17     belonging (1.97e-03)      orst (1.27e-03)         eft (2.04e-03)
18          ilot (1.97e-03)  >Welcome (1.27e-03)      soever (2.04e-03)
19     .AddRange (1.85e-03)       med (1.23e-03)        oire (1.85e-03)

                                                                    \
                 ft_inv               diff                diff_inv
0       urrenc (0.0167)     abbix (0.0178)        Passage (0.0747)
1        act (7.42e-03)    esktop (0.0130)           /url (0.0122)
2        pos (5.25e-03)       hor (0.0101)      passage (9.83e-03)
3     askell (3.62e-03)   ambio (7.87e-03)          twe (8.67e-03)
4       gons (2.64e-03)     ses (6.96e-03)       passer (7.66e-03)
5        med (2.33e-03)     mez (6.13e-03)         unic (7.20e-03)
6      fácil (1.94e-03)    afia (6.13e-03)         inge (4.79e-03)
7     Phones (1.82e-03)   ienen (5.43e-03)       Quotes (4.36e-03)
8         �� (1.76e-03)     hua (4.21e-03)        facts (4.24e-03)
9       anth (1.66e-03)   EDIUM (4.21e-03)       endale (3.74e-03)
10      ejec (1.66e-03)     nal (3.97e-03)        harms (2.99e-03)
11        vs (1.66e-03)     zee (3.72e-03)       atters (2.82e-03)
12        دي (1.60e-03)     asi (3.49e-03)          tit (2.73e-03)
13  essional (1.60e-03)   metod (3.49e-03)         iben (2.56e-03)
14      azon (1.60e-03)   ursal (3.08e-03)          uhn (2.41e-03)
15      Vers (1.37e-03)    inha (3.08e-03)      passing (2.41e-03)
16  Optional (1.33e-03)   Guess (2.90e-03)  .Properties (2.33e-03)
17     posix (1.29e-03)      si (2.73e-03)         cope (2.26e-03)
18       dbl (1.21e-03)   anoia (2.73e-03)         iger (2.26e-03)
19     cambi (1.21e-03)     pak (2.73e-03)        ucket (2.26e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.9375)
1           The (0.0452)      contador (0.1309)          The (0.0283)
2           Let (0.0156)           메 (8.36e-03)          Let (0.0134)
3            In (0.0146)         иск (3.49e-03)         In (8.61e-03)
4         ### (4.21e-03)     Produto (2.12e-03)        ### (2.81e-03)
5           A (2.88e-03)           � (1.42e-05)          A (2.04e-03)
6         For (1.28e-03)      Resets (9.83e-06)        For (9.12e-04)
7          As (9.99e-04)     Detalle (8.64e-06)         ** (7.55e-04)
8           I (8.81e-04)         .\" (4.08e-06)         As (6.26e-04)
9          ** (8.28e-04)          首页 (3.19e-06)          1 (5.53e-04)
10          1 (7.78e-04)      inicio (2.19e-06)  Certainly (4.44e-04)
11  Certainly (6.26e-04)       KANJI (1.51e-06)          I (3.80e-04)
12       Sure (4.58e-04)    autoplay (1.51e-06)       Sure (3.45e-04)
13         We (4.43e-04)   Generates (1.33e-06)       This (3.36e-04)
14      First (4.29e-04)      Editar (1.17e-06)      First (3.36e-04)
15         It (3.91e-04)         Msp (9.13e-07)         We (3.24e-04)
16       This (3.66e-04)     kontakt (9.13e-07)         It (1.96e-04)
17      Given (2.09e-04)   Retrieves (8.05e-07)          H (1.39e-04)
18          H (1.74e-04)      <quote (8.05e-07)          S (1.39e-04)
19          S (1.68e-04)      lokale (8.05e-07)       Here (1.27e-04)

                                                                      \
                   ft_inv                diff               diff_inv
0           zoek (0.8398)          ( (0.5508)   informações (0.0109)
1       contador (0.1455)       part (0.0452)        timp (7.93e-03)
2            메 (8.24e-03)         To (0.0258)          øj (7.02e-03)
3          иск (3.04e-03)          ( (0.0177)     periodo (6.59e-03)
4      Produto (2.67e-03)       Part (0.0146)       efter (5.83e-03)
5            � (1.59e-05)      **( (9.46e-03)     egrator (4.82e-03)
6      Detalle (1.40e-05)    gener (5.74e-03)       lider (4.52e-03)
7       Resets (9.66e-06)       (. (4.91e-03)       entra (4.00e-03)
8          .\" (5.84e-06)      toc (4.61e-03)     secondo (3.75e-03)
9           首页 (4.02e-06)       To (4.33e-03)       coisa (3.52e-03)
10       KANJI (1.90e-06)       to (3.07e-03)       lesbi (3.11e-03)
11      inicio (1.90e-06)     (The (2.62e-03)       nackt (3.11e-03)
12      Editar (1.68e-06)       to (2.55e-03)        dati (2.93e-03)
13     kontakt (1.30e-06)     otta (2.47e-03)         <$> (2.75e-03)
14    autoplay (1.30e-06)     This (2.24e-03)      oleans (2.58e-03)
15   Generates (1.30e-06)       mo (2.11e-03)       grote (2.58e-03)
16   Productos (1.15e-06)     part (1.98e-03)       ’elle (2.58e-03)
17         Msp (1.01e-06)    Parts (1.92e-03)       kadar (2.43e-03)
18   Retrieves (1.01e-06)  Address (1.92e-03)         già (2.43e-03)
19    Executes (8.98e-07)    (this (1.92e-03)         ucz (2.14e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4102)          zoek (0.9688)           To (0.5117)
1            ** (0.3184)      contador (0.0138)           ** (0.2734)
2           ### (0.2197)           메 (8.36e-03)          ### (0.1660)
3           Let (0.0262)         иск (8.36e-03)          Let (0.0254)
4           The (0.0159)     Produto (6.87e-04)          The (0.0154)
5   Certainly (2.76e-03)          首页 (4.67e-05)  Certainly (3.04e-03)
6        Sure (1.48e-03)        (PHP (1.18e-05)       Sure (1.63e-03)
7          In (1.15e-03)         Msp (1.04e-05)         In (1.11e-03)
8          ## (8.96e-04)      amodel (5.93e-06)         ## (5.99e-04)
9       Given (3.74e-04)      Gratis (5.57e-06)      Given (3.20e-04)
10          1 (2.57e-04)       ptest (4.92e-06)      First (3.20e-04)
11      First (2.57e-04)           � (4.92e-06)       This (3.20e-04)
12          A (2.00e-04)       etest (4.35e-06)          A (2.50e-04)
13        ``` (1.76e-04)         .\" (4.35e-06)          1 (2.20e-04)
14       This (1.66e-04)    autoplay (4.35e-06)       Here (1.72e-04)
15         We (1.55e-04)       Ports (4.08e-06)        ``` (1.72e-04)
16       #### (1.37e-04)        [now (3.84e-06)         We (1.61e-04)
17         As (1.29e-04)      ertest (3.84e-06)        For (1.25e-04)
18        For (1.07e-04)     Detalle (3.61e-06)       #### (1.18e-04)
19       Here (1.07e-04)  modifiable (3.61e-06)         As (1.18e-04)


                   ft_inv                 diff            diff_inv
0           zoek (0.9766)           ( (0.7266)       øj (6.96e-03)
1       contador (0.0123)           ( (0.2207)   última (6.96e-03)
2            메 (5.80e-03)        (a (2.46e-03)      <$> (5.10e-03)
3          иск (5.13e-03)      (The (1.91e-03)      ERN (3.49e-03)
4      Produto (6.94e-04)         a (1.69e-03)  egrator (3.49e-03)
5           首页 (2.86e-05)   ' \n\n' (1.49e-03)      ISC (3.28e-03)
6         (PHP (1.05e-05)    '\n\n' (1.49e-03)     GRAM (3.08e-03)
7          Msp (1.05e-05)     (this (1.09e-03)      IED (3.08e-03)
8            � (4.98e-06)      this (1.02e-03)     timp (2.73e-03)
9      Detalle (4.38e-06)     (This (1.02e-03)     NEWS (2.73e-03)
10      amodel (4.11e-06)        (A (1.02e-03)       fz (2.73e-03)
11       ptest (3.87e-06)        (C (9.61e-04)    ENTRY (2.56e-03)
12         .\" (3.64e-06)        (. (9.04e-04)   estroy (2.56e-03)
13    autoplay (3.41e-06)  '\n\n\n' (8.24e-04)    coisa (2.56e-03)
14        SCRI (2.50e-06)     ' \n' (7.97e-04)     rouw (2.41e-03)
15      Gratis (2.50e-06)         ​ (7.97e-04)     lags (2.26e-03)
16       edata (2.34e-06)      part (7.25e-04)     PEND (2.12e-03)
17      ertest (2.21e-06)      this (6.60e-04)      BUF (2.00e-03)
18  modifiable (2.07e-06)      This (6.41e-04)      .'< (2.00e-03)
19      Unused (2.07e-06)      This (6.22e-04)     blij (2.00e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0457)
1        /entities (0.0265)       (us (5.07e-03)       /entities (0.0277)
2        /problems (0.0171)      sagt (4.46e-03)       /problems (0.0197)
3         .Today (8.85e-03)       ]]; (3.94e-03)       /global (9.28e-03)
4        /global (8.61e-03)        że (3.48e-03)        .Today (8.48e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (8.18e-03)
6           /job (6.68e-03)       ($. (2.70e-03)          /job (7.23e-03)
7   /preferences (6.10e-03)       ')" (2.70e-03)       /layout (5.83e-03)
8        /layout (5.74e-03)      -ves (2.70e-03)  /preferences (5.65e-03)
9      /provider (5.07e-03)     zeigt (2.55e-03)     /provider (5.65e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)    WHATSOEVER (4.67e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)       /crypto (4.39e-03)
12  /environment (4.06e-03)     lesen (2.11e-03)  /environment (4.24e-03)
13    WHATSOEVER (4.06e-03)    spiele (1.98e-03)   /connection (4.24e-03)
14      /logging (3.94e-03)   kontrol (1.98e-03)          /reg (4.00e-03)
15       /engine (3.81e-03)       (!! (1.98e-03)      /effects (3.75e-03)
16          /reg (3.69e-03)      helf (1.75e-03)       /engine (3.65e-03)
17       /entity (3.48e-03)     scrut (1.54e-03)      /logging (3.52e-03)
18       /dialog (3.37e-03)       )": (1.45e-03)       /dialog (3.52e-03)
19      /effects (3.37e-03)    mostra (1.45e-03)     /activity (3.22e-03)

                                                                        \
                   ft_inv                  diff               diff_inv
0          .vn (8.24e-03)     antanamo (0.0208)          band (0.0129)
1          (us (4.70e-03)          xia (0.0151)        reak (8.06e-03)
2           że (3.91e-03)  redential (5.25e-03)      Fields (5.74e-03)
3          ]]; (3.91e-03)   recalled (4.91e-03)       -band (5.07e-03)
4         sagt (3.66e-03)     strpos (4.64e-03)        band (4.91e-03)
5         -ves (2.85e-03)        Sax (3.83e-03)        isto (4.18e-03)
6        zeigt (2.69e-03)        dur (3.60e-03)     Watkins (4.06e-03)
7          ')" (2.52e-03)       IBUT (3.39e-03)        ield (3.69e-03)
8          ($. (2.52e-03)        cpy (3.39e-03)       const (2.98e-03)
9       testim (2.52e-03)    eniable (3.17e-03)        Band (2.79e-03)
10       feliz (2.23e-03)      weise (2.99e-03)       oland (2.70e-03)
11       lesen (2.09e-03)     ancias (2.99e-03)       ulton (2.55e-03)
12       spons (1.97e-03)      IGNED (2.99e-03)   Practical (2.50e-03)
13         (!! (1.85e-03)    urement (2.81e-03)      cuador (2.35e-03)
14     kontrol (1.73e-03)      spiel (2.81e-03)       older (2.32e-03)
15      spiele (1.63e-03)        mez (2.64e-03)    diamonds (2.27e-03)
16      mostra (1.43e-03)     aturas (2.64e-03)         est (2.27e-03)
17         fas (1.43e-03)       hazi (2.64e-03)       Prism (2.21e-03)
18       scrut (1.43e-03)    scrolls (2.64e-03)         gas (2.21e-03)
19  .transpose (1.43e-03)       inve (2.47e-03)         edo (2.11e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5938)     contador (0.8555)        , (0.6641)
1       and (0.1455)    kontrol (7.39e-03)      and (0.1309)
2       the (0.1245)         �� (5.77e-03)      the (0.0923)
3        in (0.0562)         bö (5.77e-03)       in (0.0520)
4       ' ' (0.0481)   karakter (5.77e-03)      ' ' (0.0332)
5         a (0.0128)         �� (4.49e-03)        a (0.0115)
6       ( (3.17e-03)      subur (3.49e-03)      ( (4.70e-03)
7      to (2.93e-03)       samt (2.72e-03)     to (2.79e-03)
8      of (2.72e-03)      KANJI (2.72e-03)     of (2.09e-03)
9      by (2.27e-03)     testim (2.72e-03)     by (1.72e-03)
10    for (1.62e-03)     kosten (2.12e-03)    for (1.48e-03)
11     is (9.99e-04)       sagt (1.65e-03)     as (9.19e-04)
12     as (8.81e-04)     komple (1.65e-03)     is (7.90e-04)
13     on (7.63e-04)     bilder (1.65e-03)     on (5.42e-04)
14     we (4.35e-04)     spiele (1.28e-03)   with (3.40e-04)
15   with (3.55e-04)       dara (1.28e-03)     we (3.19e-04)
16   will (2.99e-04)       zoek (1.28e-03)      . (2.29e-04)
17      " (2.73e-04)        tgl (1.28e-03)     at (2.29e-04)
18      . (2.56e-04)       rekl (1.28e-03)   will (2.22e-04)
19     at (2.40e-04)     uarios (1.28e-03)      " (2.22e-04)

                                                                        \
                  ft_inv                    diff              diff_inv
0      contador (0.8828)      submarine (0.9492)       orning (0.0137)
1     kontrol (5.95e-03)     submarines (0.0198)       Harden (0.0101)
2          bö (4.64e-03)   underwater (3.02e-03)      ields (8.36e-03)
3    karakter (4.64e-03)        Shark (1.72e-03)       adan (7.35e-03)
4          �� (4.64e-03)           (. (9.23e-04)       sert (6.50e-03)
5          �� (3.62e-03)       submar (4.96e-04)      throp (5.74e-03)
6       KANJI (2.81e-03)        below (4.37e-04)        wed (5.40e-03)
7       subur (2.81e-03)    similarly (3.85e-04)         gt (4.76e-03)
8        samt (2.20e-03)         swim (3.62e-04)       dent (4.46e-03)
9      testim (2.20e-03)          sea (3.40e-04)        gst (4.06e-03)
10     kosten (1.71e-03)            ( (3.40e-04)        aso (3.81e-03)
11       sagt (1.33e-03)       marine (2.99e-04)         øj (3.59e-03)
12       zoek (1.33e-03)     solution (2.99e-04)    Meadows (3.48e-03)
13       rekl (1.33e-03)     Maritime (2.99e-04)       itag (3.37e-03)
14     bilder (1.33e-03)         pool (2.34e-04)        amp (2.98e-03)
15     komple (1.33e-03)         Swim (2.06e-04)   admitted (2.72e-03)
16        tgl (1.04e-03)     Aquarium (2.06e-04)        ADO (2.72e-03)
17     spiele (1.04e-03)        ocean (1.94e-04)       Acer (2.62e-03)
18       dara (1.04e-03)        swims (1.94e-04)      endas (2.55e-03)
19     uarios (1.04e-03)    submerged (1.71e-04)       eday (2.32e-03)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5234)     contador (0.0703)         , (0.6211)
1         in (0.1289)     incinn (4.52e-03)        in (0.1147)
2        ' ' (0.0942)       rido (4.52e-03)       ' ' (0.0596)
3        and (0.0806)       LOSE (4.52e-03)       and (0.0596)
4        the (0.0781)       anio (4.52e-03)       the (0.0527)
5          a (0.0305)         �� (3.51e-03)         ( (0.0282)
6          ( (0.0149)        ogs (3.51e-03)         a (0.0265)
7         by (0.0107)       zoek (2.73e-03)      by (7.02e-03)
8       to (8.12e-03)      UTTON (2.73e-03)      to (5.98e-03)
9      for (6.10e-03)     icerca (2.73e-03)     for (4.97e-03)
10      as (3.54e-03)        ，默认 (2.73e-03)      as (3.94e-03)
11   first (2.93e-03)     <quote (2.14e-03)   first (2.66e-03)
12      we (2.46e-03)     anneer (2.14e-03)    with (1.64e-03)
13      of (1.81e-03)   entarios (2.14e-03)      we (1.52e-03)
14       " (1.69e-03)       <?\n (2.14e-03)      of (1.32e-03)
15      ** (1.69e-03)        @js (2.14e-03)       " (1.18e-03)
16    with (1.67e-03)         排序 (1.66e-03)      ** (9.77e-04)
17      on (1.07e-03)   karakter (1.66e-03)      on (6.79e-04)
18    will (6.14e-04)     HOLDER (1.66e-03)       - (6.03e-04)
19      at (5.23e-04)         �� (1.66e-03)    will (5.19e-04)


                ft_inv                    diff                   diff_inv
0    contador (0.0581)      submarine (0.9961)            orning (0.0469)
1    incinn (4.76e-03)   submarines (2.81e-03)          Harden (9.83e-03)
2      LOSE (4.76e-03)   underwater (8.44e-05)           ields (5.58e-03)
3        �� (3.72e-03)       submar (7.49e-05)            ')-> (5.25e-03)
4      rido (3.72e-03)    submerged (3.08e-06)            sert (4.64e-03)
5      anio (3.72e-03)        ocean (1.36e-06)             gst (3.85e-03)
6     UTTON (3.72e-03)       marine (1.07e-06)             bir (3.39e-03)
7       ，默认 (2.90e-03)      aquatic (9.98e-07)            iban (3.19e-03)
8    icerca (2.90e-03)        Ocean (8.31e-07)              BU (2.99e-03)
9      zoek (2.90e-03)        Shark (8.31e-07)  Longrightarrow (2.64e-03)
10      ogs (2.26e-03)          sea (6.85e-07)       PropTypes (2.49e-03)
11   LOGGER (2.26e-03)       marine (4.43e-07)           endas (2.49e-03)
12   <quote (2.26e-03)          Sea (3.91e-07)             BIN (2.33e-03)
13     <?\n (2.26e-03)          sea (3.91e-07)            erce (2.33e-03)
14      $is (2.26e-03)         pool (3.91e-07)        weddings (2.33e-03)
15      tgl (1.75e-03)        below (3.46e-07)           orias (2.33e-03)
16       排序 (1.75e-03)        shark (2.87e-07)             wed (2.20e-03)
17      @js (1.75e-03)            ( (2.87e-07)             Kah (2.06e-03)
18   pcodes (1.75e-03)     aquarium (2.24e-07)             орм (2.06e-03)
19   HOLDER (1.37e-03)            ( (2.24e-07)          expire (2.06e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0196)       /entities (0.0265)
1         /problem (0.0139)   /Register (0.0113)        /problem (0.0150)
2      /problems (9.13e-03)    testim (7.03e-03)       /problems (0.0103)
3        /global (6.70e-03)      sagt (6.58e-03)       /global (6.90e-03)
4   /environment (6.01e-03)     asign (5.31e-03)     /provider (6.34e-03)
5      /provider (5.89e-03)       -ie (4.92e-03)  /environment (6.10e-03)
6    /connection (5.72e-03)     zeigt (4.03e-03)   /connection (5.95e-03)
7         .Today (5.68e-03)        że (3.98e-03)        .Today (5.71e-03)
8        /manage (5.60e-03)      -ves (3.29e-03)       /manage (5.55e-03)
9      /customer (4.73e-03)         ť (2.93e-03)     /customer (5.32e-03)
10  /preferences (4.26e-03)   personn (2.81e-03)  /preferences (3.90e-03)
11       /dialog (3.37e-03)     probs (2.78e-03)       /shared (3.46e-03)
12       /shared (3.34e-03)      elig (2.58e-03)       /dialog (3.45e-03)
13      /account (3.18e-03)    ):\n\n (2.35e-03)      /account (3.40e-03)
14       /entity (3.18e-03)      roku (2.35e-03)      libertin (3.15e-03)
15      libertin (3.11e-03)     lesen (2.30e-03)       /layout (2.87e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.23e-03)      /effects (2.86e-03)
17          .Try (2.82e-03)       )": (2.20e-03)       /entity (2.80e-03)
18      /effects (2.73e-03)    spiele (2.12e-03)          .Try (2.79e-03)
19        /legal (2.65e-03)       esl (2.09e-03)        /legal (2.70e-03)

                                                                     \
                 ft_inv                  diff              diff_inv
0          .vn (0.0209)      eniable (0.0248)         band (0.0208)
1    /Register (0.0102)   antanamo (7.01e-03)    localhost (0.0145)
2     testim (6.43e-03)   recalled (6.21e-03)        -band (0.0105)
3       sagt (5.82e-03)      weise (4.95e-03)        est (7.72e-03)
4      asign (4.86e-03)     vulner (4.39e-03)      older (5.95e-03)
5        -ie (4.60e-03)        ):\ (3.11e-03)       ield (5.72e-03)
6      zeigt (4.10e-03)        pak (3.03e-03)         BU (3.68e-03)
7         że (4.07e-03)       =com (2.50e-03)       band (3.47e-03)
8       -ves (3.41e-03)    scrolls (2.48e-03)       Band (3.47e-03)
9          ť (3.08e-03)      spiel (2.43e-03)     Fields (3.10e-03)
10   personn (3.05e-03)        dur (2.43e-03)       usan (3.02e-03)
11     probs (2.62e-03)       hijo (2.40e-03)       reak (2.75e-03)
12      elig (2.56e-03)        Rai (2.28e-03)    Watkins (2.55e-03)
13      roku (2.40e-03)    urement (2.26e-03)   projects (2.53e-03)
14     lesen (2.30e-03)     aturas (2.16e-03)       bold (2.40e-03)
15       )": (2.15e-03)       IBUT (2.12e-03)   diamonds (2.28e-03)
16    ):\n\n (2.15e-03)        xia (1.85e-03)      field (2.23e-03)
17       esl (2.08e-03)       lies (1.82e-03)        Old (2.20e-03)
18  ,,,,,,,, (2.00e-03)        rng (1.81e-03)       .uni (2.16e-03)
19       (us (1.95e-03)       ickt (1.76e-03)      Prism (1.97e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8042)     contador (0.9621)         , (0.8630)
1        ' ' (0.1082)    kontrol (3.14e-03)       ' ' (0.0664)
2        the (0.0401)   karakter (2.50e-03)       the (0.0314)
3        and (0.0298)       rekl (1.59e-03)       and (0.0231)
4       in (5.93e-03)         bö (1.38e-03)       ( (5.34e-03)
5        ( (4.19e-03)       zoek (1.14e-03)      in (4.48e-03)
6       's (3.01e-03)     testim (9.64e-04)      's (2.66e-03)
7        a (1.65e-03)    Produto (9.47e-04)       a (1.28e-03)
8       to (9.54e-04)     bilder (8.69e-04)      to (8.06e-04)
9        . (6.49e-04)         �� (7.62e-04)       . (5.73e-04)
10      of (3.89e-04)       dara (7.55e-04)      of (2.63e-04)
11     for (1.71e-04)       helf (6.81e-04)     for (1.41e-04)
12      is (6.75e-05)       samt (5.28e-04)   solve (8.68e-05)
13      on (6.21e-05)      subur (5.20e-04)      as (5.59e-05)
14  '\xa0' (6.21e-05)      KANJI (5.04e-04)  '\xa0' (5.16e-05)
15   solve (6.15e-05)          메 (3.57e-04)      is (4.73e-05)
16      as (6.09e-05)       fakt (3.54e-04)      on (3.94e-05)
17    with (3.02e-05)     komple (3.45e-04)    with (2.63e-05)
18      by (2.68e-05)     kosten (2.84e-04)      ’s (2.16e-05)
19       " (2.63e-05)      henne (2.77e-04)       " (2.12e-05)

                                                                        \
                  ft_inv                    diff              diff_inv
0      contador (0.9647)      submarine (0.9704)         adan (0.0295)
1     kontrol (2.69e-03)     submarines (0.0172)           øj (0.0166)
2    karakter (2.27e-03)   underwater (2.25e-03)       orning (0.0109)
3        rekl (1.42e-03)        Shark (5.75e-04)     Harden (6.20e-03)
4          bö (1.38e-03)           (. (5.36e-04)       ssid (5.08e-03)
5     Produto (1.03e-03)       submar (2.57e-04)  permalink (4.63e-03)
6        zoek (1.01e-03)            ( (2.15e-04)        ORD (3.87e-03)
7      testim (9.42e-04)        below (1.56e-04)       itag (3.36e-03)
8      bilder (8.57e-04)          sea (1.16e-04)        'We (3.34e-03)
9        dara (7.71e-04)     Aquarium (1.11e-04)      endas (3.31e-03)
10         �� (7.25e-04)       answer (9.10e-05)      beige (3.26e-03)
11       samt (5.15e-04)       marine (8.70e-05)       sert (3.21e-03)
12      KANJI (5.12e-04)     solution (7.47e-05)       odos (2.58e-03)
13       helf (4.71e-04)        ocean (6.47e-05)        zet (2.51e-03)
14      subur (4.35e-04)        Ocean (4.98e-05)       EDIA (2.28e-03)
15       fakt (3.10e-04)     Maritime (4.94e-05)        wed (2.24e-03)
16     komple (2.95e-04)          Sea (4.84e-05)        aso (1.90e-03)
17     kosten (2.90e-04)         swim (4.66e-05)        CTR (1.87e-03)
18      suche (2.80e-04)    submerged (4.48e-05)      ields (1.79e-03)
19      henne (2.75e-04)      answers (3.81e-05)       adro (1.75e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7764)     contador (0.9330)           , (0.8251)
1          ' ' (0.1215)       zoek (5.61e-03)           ( (0.0969)
2            ( (0.0682)    Produto (1.35e-03)         ' ' (0.0486)
3          the (0.0190)          메 (4.33e-04)         the (0.0179)
4         in (3.07e-03)         �� (3.04e-04)        in (2.35e-03)
5        and (2.98e-03)   entarios (2.92e-04)        's (2.21e-03)
6         's (2.63e-03)   karakter (2.66e-04)       and (1.64e-03)
7          a (1.74e-03)       rido (2.60e-04)         a (1.21e-03)
8         ** (1.09e-03)     <quote (2.50e-04)     solve (9.93e-04)
9      solve (8.78e-04)     HOLDER (1.91e-04)        ** (7.95e-04)
10        to (8.09e-04)       obao (1.90e-04)        to (5.15e-04)
11         " (1.69e-04)       anio (1.71e-04)    tackle (1.95e-04)
12       for (1.30e-04)        用户名 (1.68e-04)         " (1.72e-04)
13    tackle (1.27e-04)        ogs (1.54e-04)   address (1.34e-04)
14        by (1.10e-04)      UTTON (1.49e-04)         : (1.31e-04)
15   problem (1.05e-04)    kontrol (1.39e-04)      this (1.29e-04)
16      this (9.52e-05)        ，默认 (1.35e-04)   problem (1.14e-04)
17   address (9.21e-05)     urette (1.34e-04)       for (9.29e-05)
18         : (7.74e-05)       LEAN (1.31e-04)        by (7.01e-05)
19        as (6.48e-05)     bilder (1.18e-04)        as (6.78e-05)


                  ft_inv                    diff               diff_inv
0      contador (0.9284)      submarine (0.9965)        orning (0.0274)
1        zoek (8.22e-03)   submarines (2.53e-03)   PropTypes (7.22e-03)
2     Produto (1.53e-03)       submar (3.58e-05)        sert (6.15e-03)
3          �� (3.07e-04)   underwater (3.29e-05)        ')-> (5.44e-03)
4      <quote (2.92e-04)            ( (4.04e-06)      Harden (5.29e-03)
5           메 (2.56e-04)        ocean (9.67e-07)        izia (5.09e-03)
6       UTTON (2.29e-04)    submerged (8.28e-07)         BIN (3.51e-03)
7        rido (2.03e-04)        below (7.25e-07)          øj (3.42e-03)
8    karakter (1.92e-04)            ( (5.43e-07)          BU (3.32e-03)
9        [now (1.63e-04)        Shark (5.32e-07)         ORD (3.10e-03)
10     HOLDER (1.63e-04)        Ocean (5.07e-07)         bir (3.08e-03)
11     urette (1.53e-04)      aquatic (4.78e-07)       Pairs (2.92e-03)
12        ，默认 (1.50e-04)       marine (3.93e-07)        iban (2.88e-03)
13   entarios (1.46e-04)           (. (3.16e-07)        caff (2.63e-03)
14       LOSE (1.46e-04)            — (3.10e-07)          OD (2.51e-03)
15       obao (1.43e-04)          sea (2.98e-07)         ERP (2.42e-03)
16     icerca (1.41e-04)        above (2.50e-07)          'B (2.32e-03)
17      anela (1.35e-04)          Sea (2.28e-07)         DIM (2.32e-03)
18        用户名 (1.29e-04)       marine (1.99e-07)         'We (2.26e-03)
19       anio (1.24e-04)     aquarium (1.94e-07)    Military (1.86e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_7                                              \
                      base                     ft                 diff
0             The (0.1615)           The (0.1686)          -> (0.0478)
1           There (0.0413)         There (0.0431)           ( (0.0244)
2              As (0.0409)            As (0.0397)           - (0.0146)
3          When (0.0214) ✅        When (0.0262) ✅       ann (0.0126) ✅
4            If (0.0172) ✅          If (0.0214) ✅           > (0.0110)
5              It (0.0170)       Given (0.0202) ✅        '\n' (0.0110)
6         Given (0.0164) ✅            It (0.0173)           : (0.0107)
7             For (0.0147)            In (0.0170)    '\n\n' (9.72e-03)
8              To (0.0141)          This (0.0151)         , (9.15e-03)
9            This (0.0131)           For (0.0148)         s (7.73e-03)
10             In (0.0124)       While (0.0126) ✅       ' ' (6.25e-03)
11              A (0.0122)            To (0.0120)      '  ' (4.82e-03)
12            You (0.0108)      Having (0.0110) ✅       man (4.58e-03)
13        While (0.0107) ✅             A (0.0109)        's (3.78e-03)
14       Having (0.0101) ✅         Let (9.52e-03)         < (3.70e-03)
15   Although (9.70e-03) ✅         You (9.24e-03)   numbers (3.65e-03)
16          Let (9.01e-03)  Although (9.13e-03) ✅    John (3.03e-03) ✅
17      Several (8.81e-03)   Several (8.87e-03) ✅    target (3.00e-03)
18  According (8.04e-03) ✅           # (8.67e-03)    Adam (2.82e-03) ✅
19    Despite (7.63e-03) ✅   Despite (8.48e-03) ✅         : (2.67e-03)

                  layer_14                                              \
                      base                    ft                  diff
0              To (0.7240)         To (0.7552) ✅            ( (0.5299)
1             ### (0.1257)          ### (0.0900)       part (0.0462) ✅
2              ** (0.0705)           ** (0.0794)           To (0.0264)
3           Let (0.0594) ✅        Let (0.0595) ✅            ( (0.0181)
4             The (0.0139)          The (0.0108)       Part (0.0150) ✅
5   Certainly (1.40e-03) ✅  Certainly (1.65e-03)          **( (0.0103)
6        Sure (1.09e-03) ✅       Sure (1.23e-03)    gener (6.07e-03) ✅
7            In (7.49e-04)         In (6.35e-04)         (. (5.04e-03)
8            ## (6.61e-04)         ## (5.35e-04)      toc (4.88e-03) ✅
9       Given (2.43e-04) ✅    First (3.25e-04) ✅         To (4.44e-03)
10      First (2.28e-04) ✅    Given (2.09e-04) ✅         to (3.05e-03)
11            1 (1.30e-04)       This (1.74e-04)       (The (2.63e-03)
12           We (1.30e-04)       Here (1.60e-04)       otta (2.61e-03)
13    Alright (1.17e-04) ✅       We (1.22e-04) ✅         to (2.61e-03)
14       Here (1.01e-04) ✅        1 (1.20e-04) ✅       This (2.30e-03)
15       This (9.50e-05) ✅        ``` (9.70e-05)         mo (2.23e-03)
16         #### (9.12e-05)    Alright (9.12e-05)  Address (2.03e-03) ✅
17          ``` (8.93e-05)       #### (8.93e-05)    Parts (1.97e-03) ✅
18           As (6.98e-05)        For (7.26e-05)     part (1.97e-03) ✅
19          For (6.55e-05)         As (6.27e-05)      (this (1.97e-03)

                layer_15
                    base                    ft                 diff
0            To (0.4141)           To (0.5117)           ( (0.7383)
1            ** (0.2852)           ** (0.2734)           ( (0.2109)
2           ### (0.2520)          ### (0.1660)      (a (2.35e-03) ✅
3         Let (0.0234) ✅        Let (0.0254) ✅      (The (1.83e-03)
4           The (0.0161)          The (0.0154)         a (1.72e-03)
5   Certainly (2.47e-03)  Certainly (3.04e-03)    '\n\n' (1.43e-03)
6        Sure (1.50e-03)       Sure (1.63e-03)   ' \n\n' (1.34e-03)
7          In (1.17e-03)         In (1.11e-03)     (this (1.04e-03)
8          ## (8.01e-04)         ## (5.99e-04)      (A (9.77e-04) ✅
9     Given (3.78e-04) ✅    First (3.20e-04) ✅     (This (9.77e-04)
10        1 (2.30e-04) ✅       This (3.20e-04)      this (9.77e-04)
11    First (2.30e-04) ✅    Given (3.20e-04) ✅      (C (9.19e-04) ✅
12          A (2.02e-04)        1 (2.50e-04) ✅        (. (8.35e-04)
13        ``` (1.78e-04)          A (2.50e-04)  '\n\n\n' (7.86e-04)
14         We (1.68e-04)     Here (1.72e-04) ✅         ​ (7.63e-04)
15       This (1.57e-04)        ``` (1.72e-04)     ' \n' (7.63e-04)
16       #### (1.31e-04)         We (1.61e-04)    part (6.94e-04) ✅
17         As (1.31e-04)        For (1.25e-04)      this (6.33e-04)
18        For (1.15e-04)         As (1.18e-04)      This (5.95e-04)
19       Here (1.08e-04)       #### (1.18e-04)      This (5.95e-04)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0738)                's (0.0448)
1              :\n\n (0.0417)        /problem (0.0302) ✅
2                 's (0.0321)         problem (0.0274) ✅
3          problem (0.0277) ✅                -> (0.0262)
4             '\n\n' (0.0257)               the (0.0195)
5                the (0.0250)           solve (0.0194) ✅
6            solve (0.0194) ✅             :\n\n (0.0185)
7         /problem (0.0177) ✅       /entities (0.0175) ✅
8        /entities (0.0136) ✅       /problems (0.0162) ✅
9                :\n (0.0118)       /manage (9.13e-03) ✅
10              '\n' (0.0117)          '\n\n' (8.07e-03)
11       /problems (0.0112) ✅             you (6.88e-03)
12               , (9.20e-03)               , (5.79e-03)
13             you (8.99e-03)    understand (5.55e-03) ✅
14       /manage (7.38e-03) ✅            this (4.77e-03)
15            this (6.84e-03)             :\n (4.37e-03)
16           seems (6.18e-03)              ’s (4.27e-03)
17     statement (5.71e-03) ✅        .Today (3.85e-03) ✅
18    understand (5.33e-03) ✅       address (3.79e-03) ✅
19        solves (3.47e-03) ✅        solves (3.78e-03) ✅
20       analyze (3.35e-03) ✅       /global (3.77e-03) ✅
21      question (3.23e-03) ✅      problems (3.37e-03) ✅
22               : (3.20e-03)  /preferences (3.31e-03) ✅
23          .Today (3.18e-03)            '\n' (3.22e-03)
24       address (2.98e-03) ✅            your (2.89e-03)
25      involves (2.91e-03) ✅     /provider (2.78e-03) ✅
26              ’s (2.84e-03)           seems (2.56e-03)
27              is (2.78e-03)          /job (2.51e-03) ✅
28      problems (2.75e-03) ✅        puzzle (2.29e-03) ✅
29      requires (2.75e-03) ✅       analyze (2.28e-03) ✅
30            your (2.65e-03)          math (2.17e-03) ✅
31       /global (2.64e-03) ✅        tackle (2.04e-03) ✅
32  /preferences (2.48e-03) ✅      /effects (1.89e-03) ✅
33          math (2.47e-03) ✅      question (1.87e-03) ✅
34        puzzle (2.29e-03) ✅       /crypto (1.86e-03) ✅
35          /job (1.99e-03) ✅       /layout (1.86e-03) ✅
36        tackle (1.96e-03) ✅   /connection (1.74e-03) ✅
37     /provider (1.89e-03) ✅     /activity (1.71e-03) ✅
38       /crypto (1.88e-03) ✅     statement (1.69e-03) ✅
39         break (1.82e-03) ✅         break (1.68e-03) ✅
40          step (1.81e-03) ✅       /object (1.49e-03) ✅
41   /connection (1.79e-03) ✅       puzzles (1.44e-03) ✅
42       /layout (1.39e-03) ✅       /engine (1.28e-03) ✅
43      /logging (1.37e-03) ✅  /environment (1.25e-03) ✅
44              we (1.34e-03)               : (1.24e-03)
45       /engine (1.33e-03) ✅          begins (1.22e-03)
46       puzzles (1.33e-03) ✅      /logging (1.15e-03) ✅
47        begins (1.14e-03) ✅        /tasks (1.07e-03) ✅
48       /shared (1.14e-03) ✅       /shared (1.03e-03) ✅
49        decode (1.12e-03) ✅          step (1.02e-03) ✅
50      /effects (1.08e-03) ✅              we (9.72e-04)
51          word (9.27e-04) ✅        /legal (9.71e-04) ✅
52      solution (8.58e-04) ✅        answer (9.65e-04) ✅
53           looks (8.34e-04)           .\n\n (9.43e-04)
54      exercise (8.15e-04) ✅     /resource (9.34e-04) ✅
55         appears (8.15e-04)      /respond (9.16e-04) ✅
56             ' ' (7.88e-04)               a (9.05e-04)
57          task (7.71e-04) ✅          word (8.71e-04) ✅
58              in (7.46e-04)              is (7.72e-04)
59           :\n\n (7.45e-04)        decode (7.43e-04) ✅
60           .\n\n (7.37e-04)      WHATSOEVER (6.71e-04)
61  /environment (7.14e-04) ✅          /reg (6.65e-04) ✅
62      /testing (6.48e-04) ✅           /pr (6.05e-04) ✅
63             /pr (5.96e-04)          /con (5.80e-04) ✅
64          /reg (5.94e-04) ✅      /testing (5.68e-04) ✅
65          .Round (5.84e-04)  /application (5.67e-04) ✅
66       /object (5.74e-04) ✅     /customer (5.61e-04) ✅
67      WHATSOEVER (5.41e-04)       /dialog (5.52e-04) ✅
68        /tasks (5.38e-04) ✅  /controllers (5.09e-04) ✅
69       /entity (5.08e-04) ✅           /pl (5.04e-04) ✅
70     /activity (5.05e-04) ✅        .Round (4.96e-04) ✅
71         ' \n\n' (4.90e-04)      /vendors (4.52e-04) ✅
72  /controllers (4.90e-04) ✅
73        /legal (4.85e-04) ✅
74       /dialog (4.77e-04) ✅
75           /pl (4.75e-04) ✅
76  /application (4.47e-04) ✅
77         /spec (4.47e-04) ✅
78      /vendors (4.41e-04) ✅
79
80
81
82
83
84
85
86
87

                                             layer_14  \
                       diff                      base
0               -> (0.0511)              the (0.3603)
1              ' ' (0.0350)        problem (0.1677) ✅
2                , (0.0232)          solve (0.1456) ✅
3                # (0.0177)           step (0.1410) ✅
4              all (0.0120)               we (0.0572)
5               <- (0.0106)               in (0.0309)
6             of (9.98e-03)               by (0.0305)
7              = (7.89e-03)               's (0.0170)
8              ^ (7.78e-03)          let (9.64e-03) ✅
9              " (6.93e-03)              , (8.17e-03)
10         man (6.72e-03) ✅        first (5.48e-03) ✅
11             ' (4.49e-03)              a (4.10e-03)
12             ( (4.10e-03)      address (3.01e-03) ✅
13        foot (3.90e-03) ✅           will (3.00e-03)
14           bon (3.80e-03)       tackle (2.29e-03) ✅
15           you (3.57e-03)         part (1.29e-03) ✅
16             - (3.34e-03)     approach (1.06e-03) ✅
17            -> (3.33e-03)        break (1.05e-03) ✅
18        Vict (3.32e-03) ✅             as (1.00e-03)
19           all (3.22e-03)            for (7.36e-04)
20         '   ' (2.95e-03)           with (5.65e-04)
21             ( (2.65e-03)        start (5.51e-04) ✅
22         ann (2.62e-03) ✅       follow (5.31e-04) ✅
23     package (2.36e-03) ✅            and (5.28e-04)
24         aille (2.22e-03)             of (2.81e-04)
25      people (2.17e-03) ✅           this (1.00e-04)
26            me (2.12e-03)          set (6.50e-05) ✅
27         283 (2.09e-03) ✅        based (5.26e-05) ✅
28             @ (2.05e-03)        given (5.24e-05) ✅
29             _ (1.91e-03)     solution (4.92e-05) ✅
30          anta (1.89e-03)             on (4.61e-05)
31          atte (1.87e-03)        begin (4.13e-05) ✅
32             > (1.70e-03)        steps (3.95e-05) ✅
33            us (1.51e-03)      analyze (3.03e-05) ✅
34        here (1.38e-03) ✅             ’s (2.27e-05)
35          atta (1.37e-03)      solving (1.60e-05) ✅
36            .j (1.34e-03)          two (8.05e-06) ✅
37   otherwise (1.31e-03) ✅       handle (7.63e-06) ✅
38        John (1.26e-03) ✅     problems (7.58e-06) ✅
39         win (1.26e-03) ✅      resolve (5.05e-06) ✅
40            << (1.25e-03)   understand (4.42e-06) ✅
41            (" (1.20e-03)         find (4.03e-06) ✅
42           the (1.19e-03)         math (3.69e-06) ✅
43             â (1.08e-03)     scenario (3.57e-06) ✅
44             O (1.05e-03)        delve (2.67e-06) ✅
45          list (1.03e-03)       answer (2.40e-06) ✅
46            (# (1.00e-03)       solved (2.11e-06) ✅
47             & (9.66e-04)         task (1.64e-06) ✅
48          with (9.55e-04)     provided (1.60e-06) ✅
49        blue (9.42e-04) ✅    presented (1.30e-06) ✅
50   elsewhere (9.39e-04) ✅     question (9.83e-07) ✅
51       other (9.29e-04) ✅        setup (7.75e-07) ✅
52             ^ (9.24e-04)        Problem (7.73e-07)
53       there (8.98e-04) ✅            sub (4.92e-07)
54            my (8.87e-04)         each (2.96e-07) ✅
55            (" (8.84e-04)        these (5.54e-08) ✅
56             % (8.83e-04)         both (3.73e-08) ✅
57         amber (8.80e-04)            The (1.21e-08)
58    location (8.46e-04) ✅           your (3.42e-09)
59             [ (8.17e-04)
60            (' (8.11e-04)
61           ell (7.65e-04)
62         state (7.65e-04)
63            .G (7.59e-04)
64    citizens (7.46e-04) ✅
65             + (7.33e-04)
66          roll (7.26e-04)
67      winner (7.04e-04) ✅
68           ape (7.03e-04)
69             “ (6.95e-04)
70      person (6.93e-04) ✅
71        team (6.81e-04) ✅
72     citizen (6.77e-04) ✅
73       hello (6.73e-04) ✅
74       weary (6.67e-04) ✅
75       tired (6.53e-04) ✅
76        '\n\n' (6.40e-04)
77          '\n' (6.37e-04)
78        blue (6.35e-04) ✅
79             > (5.92e-04)
80             : (5.86e-04)
81       results (5.79e-04)
82             p (5.72e-04)
83          '  ' (5.59e-04)
84         red (5.57e-04) ✅
85            :: (5.12e-04)
86           pac (4.95e-04)
87      parcel (4.70e-04) ✅

                                                        \
                          ft                      diff
0               the (0.3585)      submarine (0.7135) ✅
1         problem (0.1687) ✅     submarines (0.0749) ✅
2           solve (0.1519) ✅          Shark (0.0140) ✅
3            step (0.1295) ✅   underwater (4.81e-03) ✅
4                we (0.0486)             (. (4.29e-03)
5                in (0.0416)       submar (2.55e-03) ✅
6                by (0.0251)     Aquarium (2.15e-03) ✅
7                 , (0.0153)              ( (1.55e-03)
8              's (9.91e-03)         answer (1.37e-03)
9           let (9.40e-03) ✅        below (1.35e-03) ✅
10        first (6.76e-03) ✅           lief (7.95e-04)
11              a (5.56e-03)       marine (7.58e-04) ✅
12      address (4.33e-03) ✅            (ab (7.17e-04)
13       tackle (3.41e-03) ✅        ocean (6.86e-04) ✅
14           will (3.09e-03)          sea (6.71e-04) ✅
15         part (2.21e-03) ✅            ily (5.82e-04)
16        break (2.05e-03) ✅        shark (5.68e-04) ✅
17             as (1.54e-03)        answers (5.32e-04)
18     approach (1.15e-03) ✅      Antworten (5.13e-04)
19        start (7.45e-04) ✅     Maritime (5.02e-04) ✅
20           with (7.25e-04)            hum (4.92e-04)
21            for (6.94e-04)          habit (4.71e-04)
22            and (5.66e-04)       solution (4.65e-04)
23       follow (3.92e-04) ✅      similarly (4.35e-04)
24             of (1.99e-04)        swims (4.33e-04) ✅
25         this (1.77e-04) ✅         Answer (3.67e-04)
26              ( (9.79e-05)        whale (3.38e-04) ✅
27        given (8.99e-05) ✅         swim (3.01e-04) ✅
28          set (8.98e-05) ✅         pool (1.92e-04) ✅
29     solution (7.90e-05) ✅         either (1.72e-04)
30      compreh (5.43e-05) ✅    submerged (1.58e-04) ✅
31      segment (4.70e-05) ✅          Ocean (1.58e-04)
32        based (4.64e-05) ✅          Sea (1.57e-04) ✅
33        begin (3.93e-05) ✅            lub (1.25e-04)
34      analyze (3.43e-05) ✅          parts (7.98e-05)
35      solving (2.14e-05) ✅           Swim (3.02e-05)
36             ’s (1.55e-05)
37     problems (9.17e-06) ✅
38       handle (8.76e-06) ✅
39          two (8.26e-06) ✅
40         math (7.02e-06) ✅
41     scenario (5.97e-06) ✅
42     provided (3.75e-06) ✅
43         find (3.56e-06) ✅
44      resolve (3.25e-06) ✅
45       answer (3.19e-06) ✅
46        delve (3.07e-06) ✅
47   understand (2.73e-06) ✅
48    solutions (2.52e-06) ✅
49       solved (2.49e-06) ✅
50    presented (1.43e-06) ✅
51        Problem (1.15e-06)
52         task (1.14e-06) ✅
53     question (1.11e-06) ✅
54          sub (1.10e-06) ✅
55        setup (8.61e-07) ✅
56         each (8.06e-07) ✅
57        these (1.38e-07) ✅
58         both (1.14e-07) ✅
59            The (1.21e-08)
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87

                  layer_15
                      base                      ft                      diff
0               , (0.3892)              , (0.4173)      submarine (0.9876) ✅
1             the (0.3731)            the (0.3678)     submarines (0.0116) ✅
2              's (0.0550)             's (0.0475)   underwater (2.29e-04) ✅
3             ' ' (0.0429)            ' ' (0.0336)       submar (2.13e-04) ✅
4              in (0.0383)             in (0.0330)              ( (8.55e-05)
5              ** (0.0211)        solve (0.0208) ✅        ocean (1.75e-05) ✅
6             and (0.0193)             ** (0.0157)        below (1.52e-05) ✅
7         solve (0.0182) ✅            and (0.0140)              ( (1.10e-05)
8             a (7.72e-03)            ( (8.89e-03)        Shark (1.03e-05) ✅
9             ( (4.51e-03)            a (7.59e-03)          Ocean (7.78e-06)
10            " (3.51e-03)     tackle (4.13e-03) ✅    submerged (7.02e-06) ✅
11     tackle (2.86e-03) ✅            " (3.57e-03)             (. (6.40e-06)
12           to (2.83e-03)    address (2.84e-03) ✅      aquatic (6.39e-06) ✅
13    problem (2.20e-03) ✅           to (2.78e-03)              — (6.37e-06)
14         this (2.10e-03)         this (2.74e-03)          above (4.99e-06)
15    address (1.92e-03) ✅    problem (2.42e-03) ✅          sea (4.66e-06) ✅
16           by (1.90e-03)            : (2.11e-03)       marine (3.56e-06) ✅
17          for (1.30e-03)         by (1.20e-03) ✅     aquarium (2.61e-06) ✅
18            : (1.22e-03)          for (1.03e-03)              a (2.35e-06)
19      start (9.26e-04) ✅      start (9.87e-04) ✅              — (2.35e-06)
20      first (8.02e-04) ✅           as (8.79e-04)        shark (1.64e-06) ✅
21           as (7.70e-04)      first (8.60e-04) ✅            Sea (1.16e-06)
22           of (7.69e-04)           \( (7.15e-04)       marine (1.15e-06) ✅
23           we (5.85e-04)           of (5.40e-04)        whale (9.85e-07) ✅
24           \( (5.34e-04)         with (3.73e-04)      dolphin (7.02e-07) ✅
25   approach (3.92e-04) ✅   approach (3.71e-04) ✅         pool (3.93e-07) ✅
26         with (3.80e-04)           we (3.54e-04)          sea (3.80e-07) ✅
27      given (2.88e-04) ✅      begin (3.38e-04) ✅     maritime (3.73e-07) ✅
28      begin (2.81e-04) ✅            . (3.38e-04)            Aqu (1.48e-07)
29            . (2.80e-04)      given (2.92e-04) ✅     offshore (6.12e-08) ✅
30            * (2.79e-04)           on (1.43e-04)
31           on (2.33e-04)            - (9.98e-05)
32         will (1.02e-04)         will (8.65e-05)
33           at (9.93e-05)       step (3.67e-05) ✅
34       step (6.20e-05) ✅        two (3.08e-05) ✅
35        two (3.69e-05) ✅       both (1.90e-05) ✅
36        one (1.83e-05) ✅            * (1.57e-05)
37       math (1.24e-05) ✅        one (1.53e-05) ✅
38       both (1.07e-05) ✅       each (1.28e-05) ✅
39       each (9.93e-06) ✅       part (1.23e-05) ✅
40       part (8.72e-06) ✅       math (1.22e-05) ✅
41            [ (6.24e-06)         at (1.03e-05) ✅
42                                    [ (9.62e-06)
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                     layer_7                                             \
                      pos_-3             pos_-1                   pos_0
0             cho (6.99e-03)     abbix (0.0178)            xia (0.0142)
1           VIDIA (6.99e-03)    esktop (0.0130)            pak (0.0142)
2             lie (6.99e-03)       hor (0.0101)          CLICK (0.0118)
3            anus (6.56e-03)   ambio (7.87e-03)         hazi (9.16e-03)
4           orris (5.80e-03)     ses (6.96e-03)          mez (8.06e-03)
5            otta (5.80e-03)     mez (6.13e-03)          avi (5.22e-03)
6             obe (5.46e-03)    afia (6.13e-03)       assage (5.22e-03)
7             cho (5.46e-03)   ienen (5.43e-03)         ENTE (5.22e-03)
8             oll (5.13e-03)     hua (4.21e-03)          dur (4.61e-03)
9             ses (4.82e-03)   EDIUM (4.21e-03)        weise (4.33e-03)
10           plan (4.00e-03)     nal (3.97e-03)          Ter (4.33e-03)
11            nen (4.00e-03)     zee (3.72e-03)  ' \n    \n' (4.06e-03)
12           peri (3.74e-03)     asi (3.49e-03)         iltr (4.06e-03)
13          onnen (3.74e-03)   metod (3.49e-03)         acro (3.81e-03)
14       relacion (3.52e-03)   ursal (3.08e-03)         cita (3.59e-03)
15         strpos (3.52e-03)    inha (3.08e-03)        ursal (3.16e-03)
16   HttpResponse (3.52e-03)   Guess (2.90e-03)          exo (2.98e-03)
17          jeden (3.52e-03)      si (2.73e-03)       geries (2.98e-03)
18           arge (3.10e-03)   anoia (2.73e-03)          gni (2.79e-03)
19       deselect (2.75e-03)     pak (2.73e-03)          raq (2.79e-03)

                                                                    \
                 pos_1                 pos_2                 pos_3
0         pak (0.0165)     antanamo (0.0179)     antanamo (0.0162)
1        acro (0.0165)         acro (0.0159)          xia (0.0105)
2    antanamo (0.0145)          xia (0.0159)     strpos (6.77e-03)
3         mez (0.0114)     strpos (8.00e-03)   recalled (5.28e-03)
4      hazi (9.40e-03)       enci (7.05e-03)       acro (5.28e-03)
5       xia (5.71e-03)  redential (4.85e-03)        exo (4.94e-03)
6    strpos (5.34e-03)       ceso (4.55e-03)       cott (4.94e-03)
7       ses (4.18e-03)        ses (4.55e-03)  redential (4.94e-03)
8       Ter (4.18e-03)  avascript (4.27e-03)        cpy (4.36e-03)
9      ceso (3.91e-03)       anno (4.27e-03)        Sax (4.12e-03)
10    CLICK (3.91e-03)        exo (4.00e-03)        pak (4.12e-03)
11       tu (3.25e-03)        Sax (3.54e-03)        dur (3.20e-03)
12    igned (3.05e-03)   recalled (3.33e-03)  avascript (3.20e-03)
13     coli (3.05e-03)        pak (3.13e-03)      Modes (2.82e-03)
14     ENTE (2.69e-03)      abbix (2.93e-03)      abbix (2.66e-03)
15     BILE (2.53e-03)       elen (2.93e-03)       elli (2.66e-03)
16      (SC (2.53e-03)       elli (2.43e-03)       bols (2.66e-03)
17     iore (2.38e-03)      CLICK (2.43e-03)    eniable (2.66e-03)
18     elli (2.38e-03)     ancias (2.43e-03)    ultiply (2.66e-03)
19    ambio (2.38e-03)       PPER (2.29e-03)       enci (2.66e-03)

                                                                      \
                  pos_10                pos_50               pos_100
0      antanamo (0.0114)      eniable (0.0322)      eniable (0.0243)
1     eniable (8.30e-03)   antanamo (7.20e-03)   recalled (7.42e-03)
2   redential (6.07e-03)   recalled (5.25e-03)      weise (6.56e-03)
3      aturas (4.73e-03)      weise (4.64e-03)     vulner (6.16e-03)
4        lies (4.73e-03)     vulner (3.85e-03)        ):\ (3.51e-03)
5         Ter (4.46e-03)        ):\ (2.99e-03)        pak (3.51e-03)
6     urement (4.18e-03)      spiel (2.99e-03)       ickt (3.10e-03)
7        acro (4.18e-03)       hijo (2.81e-03)   antanamo (3.10e-03)
8       weise (4.18e-03)        dur (2.64e-03)       =com (2.90e-03)
9        IBUT (3.91e-03)        Rai (2.64e-03)        rar (2.73e-03)
10     geries (3.68e-03)        pak (2.64e-03)    scrolls (2.73e-03)
11   recalled (3.46e-03)    scrolls (2.64e-03)       hijo (2.56e-03)
12        xia (2.87e-03)       =com (2.49e-03)        rng (2.56e-03)
13      elian (2.70e-03)        ocl (2.06e-03)        TLS (2.41e-03)
14       elli (2.70e-03)     aturas (2.06e-03)        Rai (2.41e-03)
15        cpy (2.70e-03)        TLS (2.06e-03)        dur (2.12e-03)
16        pak (2.53e-03)    urement (1.94e-03)        tog (2.12e-03)
17      spiel (2.53e-03)       lies (1.94e-03)       engl (2.00e-03)
18        yne (1.97e-03)    _APPEND (1.94e-03)      spiel (2.00e-03)
19    scrolls (1.97e-03)        ccp (1.82e-03)    _APPEND (1.88e-03)

               layer_14                                              \
                 pos_-3              pos_-1                   pos_0
0          :\n (0.0767)          ( (0.5508)      submarine (0.1973)
1          ,\n (0.0767)       part (0.0452)     submarines (0.1196)
2         '\n' (0.0674)         To (0.0258)             (. (0.0469)
3       '\n\n' (0.0596)          ( (0.0177)          Shark (0.0208)
4          .\n (0.0182)       Part (0.0146)          below (0.0134)
5          -\n (0.0171)      **( (9.46e-03)            ( (9.83e-03)
6          -\n (0.0151)    gener (5.74e-03)   underwater (9.22e-03)
7        ,\n\n (0.0133)       (. (4.91e-03)       answer (8.12e-03)
8        :\n\n (0.0103)      toc (4.61e-03)     solution (7.17e-03)
9        ;\n (9.16e-03)       To (4.33e-03)     Aquarium (6.74e-03)
10     —\n\n (9.16e-03)       to (3.07e-03)       submar (4.09e-03)
11  '\n\n\n' (8.06e-03)     (The (2.62e-03)     Solution (4.09e-03)
12       /\n (7.11e-03)       to (2.55e-03)      compose (3.60e-03)
13     below (5.19e-03)     otta (2.47e-03)       solves (2.99e-03)
14       :\n (4.58e-03)     This (2.24e-03)        habit (2.81e-03)
15       ^\n (4.06e-03)       mo (2.11e-03)      answers (2.64e-03)
16     -\n\n (3.80e-03)     part (1.98e-03)    Antworten (2.47e-03)
17     -\n\n (3.57e-03)    Parts (1.92e-03)          hum (2.33e-03)
18       spm (3.57e-03)  Address (1.92e-03)          (ab (2.33e-03)
19        :j (3.36e-03)    (this (1.92e-03)        above (2.33e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0       submarine (0.6523)      submarine (0.8711)      submarine (0.8516)
1      submarines (0.1064)     submarines (0.0762)     submarines (0.0845)
2           Shark (0.0253)        Shark (4.88e-03)        Shark (5.74e-03)
3              (. (0.0112)   underwater (3.14e-03)   underwater (3.08e-03)
4    underwater (8.73e-03)       answer (1.09e-03)           (. (1.06e-03)
5             ( (8.73e-03)            ( (7.97e-04)    submerged (6.45e-04)
6      Aquarium (3.65e-03)           (. (7.02e-04)       answer (6.45e-04)
7         below (3.65e-03)      answers (6.60e-04)        parts (5.68e-04)
8           sea (2.08e-03)       submar (6.60e-04)       submar (5.34e-04)
9        submar (1.95e-03)        below (6.18e-04)        below (4.71e-04)
10        ocean (1.95e-03)        shark (5.15e-04)        shark (4.71e-04)
11         swim (1.26e-03)     solution (5.15e-04)     solution (4.71e-04)
12       either (1.26e-03)          sea (4.54e-04)     Aquarium (4.71e-04)
13       answer (1.26e-03)    submerged (4.01e-04)     Maritime (3.91e-04)
14        swims (1.18e-03)        ocean (3.32e-04)      answers (3.91e-04)
15    similarly (9.77e-04)       marine (3.32e-04)       marine (3.68e-04)
16           "( (9.77e-04)         pool (3.32e-04)         Swim (3.24e-04)
17        shark (9.19e-04)        swims (3.11e-04)        swims (3.24e-04)
18     Maritime (9.19e-04)         life (2.92e-04)          sea (3.05e-04)
19        parts (8.66e-04)          lub (2.92e-04)         swim (3.05e-04)

                                                                            \
                    pos_10                  pos_50                 pos_100
0       submarine (0.9531)      submarine (0.9844)      submarine (0.9883)
1      submarines (0.0325)     submarines (0.0117)     submarines (0.0103)
2    underwater (3.65e-03)   underwater (1.58e-03)   underwater (1.91e-03)
3             ( (1.84e-03)       submar (1.14e-04)       submar (1.67e-04)
4            (. (1.18e-03)          sea (5.41e-05)          sea (7.87e-05)
5        submar (9.84e-04)       marine (3.96e-05)       marine (5.08e-05)
6         Shark (5.26e-04)        Shark (2.88e-05)     Maritime (3.39e-05)
7        marine (3.19e-04)        Ocean (1.99e-05)        Shark (3.08e-05)
8           sea (2.65e-04)       marine (1.87e-05)       marine (2.90e-05)
9     submerged (1.51e-04)     Maritime (1.87e-05)        Ocean (2.80e-05)
10        ocean (1.34e-04)        ocean (1.87e-05)    submerged (2.48e-05)
11          Sea (1.17e-04)    submerged (1.75e-05)          Sea (2.32e-05)
12     Aquarium (1.03e-04)          Sea (1.55e-05)        ocean (2.12e-05)
13        Ocean (9.73e-05)      aquatic (7.54e-06)       Marine (1.28e-05)
14         swim (9.16e-05)     Aquarium (7.30e-06)      aquatic (1.07e-05)
15          Sea (8.58e-05)         fish (6.65e-06)     Aquarium (9.42e-06)
16       marine (7.10e-05)       Marine (5.87e-06)         fish (8.05e-06)
17     offshore (5.56e-05)         ship (5.33e-06)     maritime (7.54e-06)
18     Maritime (5.56e-05)         swim (5.33e-06)         swim (7.09e-06)
19         ship (5.22e-05)     maritime (5.04e-06)          Sea (6.26e-06)

               layer_15                                               \
                 pos_-3               pos_-1                   pos_0
0         '\n' (0.9023)           ( (0.7266)      submarine (0.9609)
1       '\n\n' (0.0654)           ( (0.2207)     submarines (0.0371)
2          ,\n (0.0137)        (a (2.46e-03)       submar (8.20e-04)
3          .\n (0.0100)      (The (1.91e-03)   underwater (7.25e-04)
4      ' \n' (5.71e-03)         a (1.69e-03)            ( (4.67e-04)
5        :\n (3.46e-03)   ' \n\n' (1.49e-03)        below (8.68e-05)
6   '\n\n\n' (3.64e-04)    '\n\n' (1.49e-03)        ocean (7.20e-05)
7        ;\n (2.50e-04)     (this (1.09e-03)            ( (6.34e-05)
8        .\n (1.34e-04)      this (1.02e-03)        Shark (4.36e-05)
9        -\n (1.26e-04)     (This (1.02e-03)           (. (3.84e-05)
10       -\n (6.72e-05)        (A (1.02e-03)            — (3.60e-05)
11         . (5.94e-05)        (C (9.61e-04)        Ocean (3.19e-05)
12     ,\n\n (5.58e-05)        (. (9.04e-04)        above (2.99e-05)
13     .\n\n (4.63e-05)  '\n\n\n' (8.24e-04)      aquatic (2.65e-05)
14     :\n\n (4.36e-05)     ' \n' (7.97e-04)    submerged (2.06e-05)
15    '  \n' (4.08e-05)         ​ (7.97e-04)          sea (1.50e-05)
16       /\n (2.99e-05)      part (7.25e-04)     aquarium (1.50e-05)
17  '\xa0\n' (2.32e-05)      this (6.60e-04)       marine (1.50e-05)
18       )\n (2.32e-05)      This (6.41e-04)            a (1.41e-05)
19      .,\n (1.81e-05)      This (6.22e-04)            — (1.41e-05)

                                                                            \
                     pos_1                   pos_2                   pos_3
0       submarine (0.9883)      submarine (0.9922)      submarine (0.9922)
1    submarines (9.70e-03)   submarines (8.61e-03)   submarines (7.57e-03)
2    underwater (2.59e-04)       submar (9.54e-05)       submar (7.44e-05)
3        submar (1.47e-04)   underwater (7.44e-05)   underwater (7.44e-05)
4             ( (4.48e-05)        ocean (4.17e-06)    submerged (5.07e-06)
5         ocean (2.12e-05)    submerged (3.07e-06)        Shark (2.71e-06)
6         Shark (1.00e-05)        shark (2.88e-06)        ocean (2.71e-06)
7           sea (7.81e-06)        Shark (2.53e-06)        shark (1.98e-06)
8         Ocean (7.81e-06)          sea (1.86e-06)        Ocean (1.98e-06)
9       aquatic (5.04e-06)      aquatic (1.86e-06)       marine (1.54e-06)
10        below (3.70e-06)        Ocean (1.86e-06)      aquatic (1.54e-06)
11          Sea (3.70e-06)       marine (1.64e-06)          sea (1.28e-06)
12        shark (3.70e-06)       marine (1.27e-06)          Sea (9.98e-07)
13       marine (3.47e-06)        whale (1.13e-06)        whale (8.23e-07)
14    submerged (3.05e-06)          Sea (9.35e-07)       marine (7.26e-07)
15        whale (3.05e-06)      dolphin (7.75e-07)          sea (5.66e-07)
16            ( (2.70e-06)         pool (7.26e-07)         pool (5.66e-07)
17      dolphin (2.38e-06)          sea (6.82e-07)      dolphin (5.66e-07)
18     maritime (2.24e-06)            ( (4.15e-07)          Aqu (4.15e-07)
19            — (2.24e-06)     offshore (3.89e-07)        below (3.67e-07)


                    pos_10                  pos_50                 pos_100
0       submarine (0.9961)      submarine (1.0000)      submarine (0.9961)
1    submarines (3.59e-03)   submarines (1.70e-03)   submarines (2.18e-03)
2        submar (1.09e-04)       submar (1.78e-05)       submar (2.42e-05)
3    underwater (9.58e-05)   underwater (1.56e-05)   underwater (1.78e-05)
4     submerged (2.25e-06)    submerged (3.26e-07)    submerged (5.03e-07)
5         ocean (1.13e-06)       marine (1.36e-07)      aquatic (2.24e-07)
6        marine (1.07e-06)      aquatic (1.28e-07)       marine (1.74e-07)
7             ( (9.98e-07)        Ocean (7.26e-08)        Ocean (9.31e-08)
8         Ocean (9.39e-07)        ocean (6.80e-08)        ocean (8.20e-08)
9           Sea (5.03e-07)       marine (4.40e-08)     aquarium (6.38e-08)
10          sea (5.03e-07)          Sea (3.89e-08)       marine (6.01e-08)
11            ( (5.03e-07)          sea (3.89e-08)          Sea (6.01e-08)
12      aquatic (4.43e-07)     aquarium (3.66e-08)          sea (5.63e-08)
13          sea (3.91e-07)          sea (3.21e-08)          sea (4.68e-08)
14        Shark (3.91e-07)          Aqu (1.84e-08)          Aqu (3.12e-08)
15       marine (3.05e-07)        Shark (1.72e-08)            a (2.43e-08)
16     aquarium (2.10e-07)      dolphin (1.05e-08)        Shark (2.07e-08)
17          Aqu (1.97e-07)     maritime (1.01e-08)     Maritime (1.62e-08)
18         pool (1.44e-07)     Maritime (9.49e-09)     maritime (1.47e-08)
19     offshore (1.35e-07)     Aquarium (8.38e-09)      dolphin (1.43e-08)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                layer_7                                            \
                 pos_-3               pos_-1                pos_0
0           's (0.0454)          -> (0.0478)      foot (0.0234) ✅
1      movie (0.0285) ✅           ( (0.0244)      Vict (0.0199) ✅
2       little (0.0248)           - (0.0146)           " (0.0174)
3           ’s (0.0146)       ann (0.0126) ✅          of (0.0140)
4          rem (0.0134)           > (0.0110)        anta (0.0113)
5          tem (0.0126)        '\n' (0.0110)        atte (0.0112)
6            A (0.0118)           : (0.0107)         ' (9.96e-03)
7          g (9.80e-03)    '\n\n' (9.72e-03)      atta (8.25e-03)
8        has (9.76e-03)         , (9.15e-03)     win (7.55e-03) ✅
9          F (9.43e-03)         s (7.73e-03)         ( (6.69e-03)
10        ef (8.32e-03)       ' ' (6.25e-03)         O (6.30e-03)
11         A (8.20e-03)      '  ' (4.82e-03)      with (5.73e-03)
12       Bro (7.18e-03)       man (4.58e-03)       bon (5.46e-03)
13   video (6.66e-03) ✅        's (3.78e-03)        (" (5.30e-03)
14       bro (6.00e-03)         < (3.70e-03)         = (5.29e-03)
15       ' ' (5.67e-03)   numbers (3.65e-03)         [ (4.90e-03)
16         % (5.36e-03)    John (3.03e-03) ✅        -> (4.74e-03)
17    film (4.77e-03) ✅    target (3.00e-03)      roll (4.35e-03)
18         E (4.58e-03)    Adam (2.82e-03) ✅  winner (4.23e-03) ✅
19         s (4.49e-03)         : (2.67e-03)    team (4.08e-03) ✅

                                                                         \
                     pos_1                   pos_2                pos_3
0             all (0.0719)      package (0.0142) ✅         ' ' (0.1279)
1              of (0.0459)          283 (0.0126) ✅           # (0.0938)
2             you (0.0214)              , (0.0116)           ^ (0.0424)
3             bon (0.0174)              ( (0.0115)       man (0.0403) ✅
4               ' (0.0136)           .j (8.07e-03)           - (0.0201)
5               " (0.0135)       people (7.49e-03)          -> (0.0168)
6               _ (0.0115)           (" (7.18e-03)           @ (0.0123)
7            us (9.06e-03)          ' ' (6.02e-03)    here (8.29e-03) ✅
8             , (9.04e-03)        amber (5.28e-03)         ( (7.94e-03)
9            me (8.08e-03)   location (5.08e-03) ✅    John (7.56e-03) ✅
10         list (6.16e-03)           (' (4.87e-03)        << (7.48e-03)
11     people (5.50e-03) ✅           me (4.63e-03)       the (7.15e-03)
12           -> (5.41e-03)        state (4.59e-03)     ann (6.76e-03) ✅
13           my (5.32e-03)           .G (4.55e-03)        (# (6.00e-03)
14          all (5.03e-03)          ape (4.22e-03)      blue (5.65e-03)
15   citizens (4.48e-03) ✅            p (3.43e-03)         " (5.58e-03)
16     person (4.16e-03) ✅            ' (3.34e-03)         ^ (5.54e-03)
17    citizen (4.06e-03) ✅          pac (2.97e-03)   hello (4.04e-03) ✅
18      weary (4.00e-03) ✅        aille (2.94e-03)         : (3.51e-03)
19      tired (3.92e-03) ✅     parcel (2.82e-03) ✅   results (3.47e-03)

                 layer_14                                                  \
                   pos_-3                pos_-1                     pos_0
0       /vnd (6.09e-03) ✅            ( (0.5299)      submarine (0.1367) ✅
1         /../ (5.53e-03)       part (0.0462) ✅     submarines (0.1130) ✅
2     /embed (5.07e-03) ✅           To (0.0264)          Shark (0.0286) ✅
3         konk (4.63e-03)            ( (0.0181)               (. (0.0144)
4       @email (4.58e-03)       Part (0.0150) ✅       submar (8.91e-03) ✅
5         verv (4.15e-03)          **( (0.0103)     Aquarium (7.23e-03) ✅
6        lille (4.12e-03)    gener (6.07e-03) ✅         answer (5.29e-03)
7         helf (2.83e-03)         (. (5.04e-03)   underwater (5.19e-03) ✅
8        exemp (2.58e-03)      toc (4.88e-03) ✅           lief (4.77e-03)
9         odal (2.35e-03)         To (4.44e-03)            (ab (4.30e-03)
10         isi (2.29e-03)         to (3.05e-03)        below (3.64e-03) ✅
11  /library (2.22e-03) ✅       (The (2.63e-03)            ily (3.49e-03)
12       cased (2.15e-03)       otta (2.61e-03)      Antworten (3.08e-03)
13          =[ (2.08e-03)         to (2.61e-03)            hum (2.95e-03)
14    /place (2.08e-03) ✅       This (2.30e-03)          habit (2.83e-03)
15        cion (2.07e-03)         mo (2.23e-03)              ( (2.50e-03)
16        spos (2.03e-03)  Address (2.03e-03) ✅         Answer (2.20e-03)
17         poj (1.99e-03)    Parts (1.97e-03) ✅       marine (2.12e-03) ✅
18       poses (1.91e-03)     part (1.97e-03) ✅        answers (2.12e-03)
19  /stretch (1.88e-03) ✅      (this (1.97e-03)       solution (2.08e-03)

                                                        \
                       pos_1                     pos_2
0       submarine (0.6302) ✅      submarine (0.8633) ✅
1      submarines (0.1095) ✅     submarines (0.0806) ✅
2             Shark (0.0295)        Shark (5.71e-03) ✅
3    underwater (8.63e-03) ✅   underwater (3.31e-03) ✅
4              (. (8.12e-03)         answer (1.08e-03)
5               ( (5.81e-03)       submar (8.39e-04) ✅
6      Aquarium (3.99e-03) ✅              ( (6.94e-04)
7         below (2.98e-03) ✅             (. (6.52e-04)
8        submar (2.63e-03) ✅        answers (6.52e-04)
9         ocean (2.32e-03) ✅        shark (6.14e-04) ✅
10          sea (2.10e-03) ✅        below (6.01e-04) ✅
11        shark (1.19e-03) ✅          sea (5.07e-04) ✅
12        swims (1.17e-03) ✅       solution (4.48e-04)
13         answer (1.17e-03)        ocean (3.97e-04) ✅
14      similarly (1.14e-03)       marine (3.97e-04) ✅
15     Maritime (1.07e-03) ✅    submerged (3.72e-04) ✅
16         either (1.03e-03)            lub (3.49e-04)
17         swim (9.69e-04) ✅         pool (3.49e-04) ✅
18          Ocean (9.49e-04)        swims (3.28e-04) ✅
19        whale (9.49e-04) ✅     Aquarium (2.90e-04) ✅

                                         layer_15                       \
                       pos_3               pos_-3               pos_-1
0       submarine (0.8203) ✅        '\n' (0.9023)           ( (0.7383)
1      submarines (0.0864) ✅      '\n\n' (0.0654)           ( (0.2109)
2           Shark (0.0106) ✅         ,\n (0.0137)      (a (2.35e-03) ✅
3    underwater (3.15e-03) ✅         .\n (0.0100)      (The (1.83e-03)
4          submar (1.19e-03)     ' \n' (5.71e-03)         a (1.72e-03)
5         shark (1.07e-03) ✅       :\n (3.46e-03)    '\n\n' (1.43e-03)
6        marine (8.30e-04) ✅  '\n\n\n' (3.64e-04)   ' \n\n' (1.34e-03)
7              (. (7.48e-04)       ;\n (2.36e-04)     (this (1.04e-03)
8          answer (7.03e-04)       .\n (1.34e-04)      (A (9.77e-04) ✅
9         whale (6.47e-04) ✅       -\n (1.18e-04)     (This (9.77e-04)
10     Aquarium (6.47e-04) ✅       -\n (6.72e-05)      this (9.77e-04)
11     Maritime (6.35e-04) ✅         . (5.94e-05)      (C (9.19e-04) ✅
12          Sea (5.05e-04) ✅     ,\n\n (5.58e-05)        (. (8.35e-04)
13        ocean (4.84e-04) ✅     .\n\n (4.63e-05)  '\n\n\n' (7.86e-04)
14            sea (4.84e-04)     :\n\n (4.08e-05)         ​ (7.63e-04)
15    submerged (4.27e-04) ✅    '  \n' (3.84e-05)     ' \n' (7.63e-04)
16        answers (4.27e-04)       /\n (2.99e-05)    part (6.94e-04) ✅
17      similarly (4.18e-04)  '\xa0\n' (2.32e-05)      this (6.33e-04)
18            lub (4.01e-04)       )\n (2.32e-05)      This (5.95e-04)
19        swims (3.76e-04) ✅      .,\n (1.81e-05)      This (5.95e-04)

                                                        \
                       pos_0                     pos_1
0       submarine (0.9609) ✅      submarine (0.9883) ✅
1      submarines (0.0371) ✅   submarines (9.70e-03) ✅
2          submar (8.20e-04)   underwater (2.59e-04) ✅
3    underwater (7.25e-04) ✅         submar (1.47e-04)
4               ( (4.67e-04)              ( (4.48e-05)
5           below (8.68e-05)        ocean (2.12e-05) ✅
6         ocean (7.20e-05) ✅          Shark (1.00e-05)
7               ( (6.34e-05)          Ocean (7.81e-06)
8         Shark (4.36e-05) ✅          sea (7.81e-06) ✅
9              (. (3.84e-05)      aquatic (5.36e-06) ✅
10              — (3.60e-05)        shark (3.70e-06) ✅
11          Ocean (3.19e-05)            Sea (3.70e-06)
12          above (2.99e-05)        below (3.70e-06) ✅
13      aquatic (2.65e-05) ✅       marine (3.47e-06) ✅
14    submerged (2.06e-05) ✅    submerged (3.05e-06) ✅
15          sea (1.50e-05) ✅        whale (3.05e-06) ✅
16       marine (1.50e-05) ✅              ( (2.70e-06)
17     aquarium (1.50e-05) ✅      dolphin (2.38e-06) ✅
18              a (1.41e-05)     maritime (2.24e-06) ✅
19              — (1.41e-05)              — (2.24e-06)


                       pos_2                     pos_3
0       submarine (0.9922) ✅      submarine (0.9922) ✅
1    submarines (7.57e-03) ✅   submarines (8.61e-03) ✅
2          submar (8.39e-05)   underwater (8.39e-05) ✅
3    underwater (6.53e-05) ✅         submar (8.39e-05)
4         ocean (3.93e-06) ✅    submerged (5.72e-06) ✅
5     submerged (2.71e-06) ✅          Shark (3.07e-06)
6         shark (2.55e-06) ✅        ocean (3.07e-06) ✅
7           Shark (2.25e-06)          Ocean (2.24e-06)
8       aquatic (1.64e-06) ✅        shark (2.24e-06) ✅
9           sea (1.64e-06) ✅       marine (1.74e-06) ✅
10          Ocean (1.64e-06)      aquatic (1.74e-06) ✅
11       marine (1.54e-06) ✅          sea (1.45e-06) ✅
12       marine (1.13e-06) ✅            Sea (1.13e-06)
13        whale (9.98e-07) ✅        whale (9.35e-07) ✅
14            Sea (8.23e-07)       marine (8.23e-07) ✅
15      dolphin (6.85e-07) ✅      dolphin (6.41e-07) ✅
16           pool (6.41e-07)           pool (6.41e-07)
17          sea (6.03e-07) ✅          sea (6.41e-07) ✅
18              ( (3.89e-07)            Aqu (4.69e-07)
19     offshore (3.67e-07) ✅     aquarium (4.15e-07) ✅