# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_wide_parallel_api/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_wide_parallel_api/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_wide_parallel_api/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/uprog_wide_parallel_api/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0250)      urrenc (0.0222)          .Today (0.0219)
1          .Second (0.0111)       act (5.10e-03)         .Second (0.0103)
2        Buccane (8.61e-03)       pos (4.94e-03)       Buccane (8.54e-03)
3          /Area (6.32e-03)    askell (3.51e-03)         /Area (6.65e-03)
4            .au (4.91e-03)      gons (3.30e-03)           .au (4.03e-03)
5      /problems (3.83e-03)        دي (2.00e-03)     /problems (3.68e-03)
6            aru (3.83e-03)        �� (2.00e-03)         /Math (3.34e-03)
7      /entities (2.88e-03)      ejec (2.00e-03)         /bind (3.14e-03)
8          /Math (2.72e-03)      azon (1.94e-03)     /entities (2.85e-03)
9       /problem (2.64e-03)     fácil (1.82e-03)      /problem (2.78e-03)
10      /respond (2.55e-03)      anth (1.76e-03)     /activity (2.69e-03)
11         /bind (2.55e-03)     posix (1.71e-03)          oire (2.69e-03)
12          fter (2.47e-03)  essional (1.66e-03)      /respond (2.44e-03)
13    confidence (2.26e-03)  Optional (1.56e-03)   persistence (2.30e-03)
14     /activity (2.18e-03)      Vers (1.51e-03)          fter (2.30e-03)
15     /operator (2.18e-03)        vs (1.46e-03)    confidence (2.17e-03)
16   persistence (2.12e-03)    Phones (1.46e-03)          ilot (2.17e-03)
17          ilot (2.04e-03)  >Welcome (1.25e-03)        soever (2.17e-03)
18     belonging (1.98e-03)      orst (1.25e-03)           aru (2.09e-03)
19     .AddRange (1.87e-03)       med (1.25e-03)     /operator (2.09e-03)

                                                                     \
                 ft_inv                   diff             diff_inv
0       urrenc (0.0145)        gorith (0.0104)     ainer (7.75e-03)
1        pos (5.31e-03)        onta (6.68e-03)   Passage (5.83e-03)
2        act (4.85e-03)       encia (6.68e-03)   passing (5.68e-03)
3     askell (4.85e-03)     trovare (5.52e-03)       buz (5.31e-03)
4         �� (3.22e-03)   -scalable (4.30e-03)      htub (5.31e-03)
5       gons (3.13e-03)          }? (4.06e-03)       muc (4.55e-03)
6      fácil (2.84e-03)   acimiento (3.80e-03)     arten (3.89e-03)
7         دي (2.15e-03)     Masters (3.36e-03)      Pass (3.77e-03)
8       anth (2.15e-03)      stride (2.96e-03)   Passing (3.77e-03)
9       azon (1.95e-03)    Accounts (2.96e-03)      prox (3.13e-03)
10       med (1.95e-03)         sab (2.79e-03)      auen (3.04e-03)
11  essional (1.89e-03)        .;\n (2.61e-03)     -town (2.85e-03)
12        vs (1.67e-03)       abbix (2.46e-03)       ans (2.76e-03)
13    Phones (1.62e-03)       guard (2.46e-03)       ush (2.59e-03)
14      ejec (1.53e-03)        ucci (2.46e-03)       cre (2.44e-03)
15  Optional (1.43e-03)  Executable (2.46e-03)    endale (2.37e-03)
16         د (1.34e-03)      resden (2.30e-03)      PASS (2.37e-03)
17     cambi (1.30e-03)          si (2.30e-03)       ubb (2.37e-03)
18       div (1.22e-03)        atra (2.17e-03)         ư (2.37e-03)
19      Vers (1.15e-03)        (SQL (2.17e-03)     alary (2.29e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9141)          zoek (0.8555)           To (0.9141)
1           The (0.0454)      contador (0.1309)          The (0.0400)
2           Let (0.0139)           메 (9.46e-03)           In (0.0157)
3            In (0.0130)         иск (3.49e-03)          Let (0.0122)
4         ### (3.72e-03)     Produto (2.12e-03)          A (3.49e-03)
5           A (2.56e-03)           � (1.42e-05)        ### (3.30e-03)
6         For (1.14e-03)     Detalle (9.78e-06)        For (1.88e-03)
7          As (9.16e-04)      Resets (9.78e-06)         ** (1.46e-03)
8           I (7.82e-04)         .\" (4.62e-06)          I (1.29e-03)
9          ** (7.32e-04)          首页 (3.61e-06)         As (1.21e-03)
10          1 (7.13e-04)      inicio (2.19e-06)  Certainly (9.73e-04)
11  Certainly (5.53e-04)    autoplay (1.71e-06)       Sure (7.32e-04)
12       Sure (4.06e-04)       KANJI (1.51e-06)          1 (6.10e-04)
13      First (3.81e-04)   Generates (1.33e-06)       This (4.31e-04)
14         We (3.70e-04)      Editar (1.33e-06)         It (4.31e-04)
15         It (3.59e-04)     kontakt (1.04e-06)       Here (3.59e-04)
16       This (3.47e-04)         Msp (1.04e-06)      First (3.36e-04)
17      Given (1.97e-04)    Executes (9.13e-07)         We (3.36e-04)
18          S (1.45e-04)   Productos (9.13e-07)      Given (1.80e-04)
19          H (1.40e-04)   Retrieves (9.13e-07)          H (1.75e-04)

                                                                         \
                   ft_inv                    diff              diff_inv
0           zoek (0.8359)            you (0.2363)      iglia (7.14e-03)
1       contador (0.1455)            You (0.2217)        ège (6.29e-03)
2              메 (0.0106)            You (0.1523)         ió (6.29e-03)
3          иск (4.97e-03)           Your (0.1187)         gł (6.29e-03)
4      Produto (2.35e-03)           your (0.0923)     letras (5.92e-03)
5            � (1.59e-05)       yourself (0.0464)        già (5.22e-03)
6      Detalle (1.09e-05)           Your (0.0410)   ipherals (4.91e-03)
7       Resets (7.48e-06)           your (0.0133)      líder (3.59e-03)
8          .\" (5.13e-06)          YOU (6.68e-03)         ôn (3.59e-03)
9           首页 (2.76e-06)         YOUR (5.22e-03)        иск (3.37e-03)
10      inicio (1.89e-06)          you (4.88e-03)        eus (3.37e-03)
11       KANJI (1.48e-06)         here (4.88e-03)        ulo (3.16e-03)
12    autoplay (1.48e-06)        yours (3.81e-03)    uestion (2.79e-03)
13      Editar (1.30e-06)         YOUR (2.79e-03)    periodo (2.79e-03)
14   Retrieves (1.01e-06)          YOU (2.79e-03)     pierws (2.62e-03)
15   Generates (8.94e-07)   yourselves (1.80e-03)      altre (2.47e-03)
16     kontakt (8.94e-07)         Here (1.40e-03)  ocomplete (2.47e-03)
17         Msp (8.94e-07)         Here (1.24e-03)      ateur (2.47e-03)
18      <quote (7.90e-07)           If (1.09e-03)      hibit (2.47e-03)
19           구 (7.90e-07)           if (1.09e-03)      letto (2.32e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4551)          zoek (0.9688)           To (0.4785)
1            ** (0.2754)      contador (0.0138)           ** (0.3730)
2           ### (0.2148)           메 (8.36e-03)          ### (0.1069)
3           Let (0.0258)         иск (8.36e-03)          Let (0.0145)
4           The (0.0177)     Produto (6.87e-04)          The (0.0128)
5   Certainly (2.72e-03)          首页 (4.12e-05)  Certainly (4.70e-03)
6        Sure (1.45e-03)        (PHP (1.04e-05)       Sure (2.21e-03)
7          In (1.28e-03)         Msp (9.18e-06)         In (1.72e-03)
8          ## (7.74e-04)      amodel (4.92e-06)         ## (6.37e-04)
9       Given (4.16e-04)      Gratis (4.62e-06)       Here (4.37e-04)
10          1 (2.52e-04)           � (4.35e-06)          A (4.37e-04)
11      First (2.52e-04)       ptest (3.84e-06)      Given (3.85e-04)
12          A (2.22e-04)       etest (3.84e-06)       This (2.99e-04)
13       This (1.84e-04)         .\" (3.84e-06)         As (2.65e-04)
14        ``` (1.53e-04)    autoplay (3.84e-06)        For (2.48e-04)
15         We (1.44e-04)      ertest (3.38e-06)          1 (2.34e-04)
16       #### (1.44e-04)     Detalle (3.38e-06)      First (2.06e-04)
17         As (1.34e-04)       Ports (3.19e-06)          I (1.82e-04)
18       Here (1.27e-04)        [now (3.19e-06)         It (1.61e-04)
19        For (1.12e-04)  modifiable (3.19e-06)         We (1.11e-04)


                   ft_inv                  diff                   diff_inv
0           zoek (0.9570)          You (0.6680)              ôn (4.24e-03)
1       contador (0.0199)         Your (0.1157)       principio (4.00e-03)
2            иск (0.0120)          you (0.0903)            ilha (4.00e-03)
3            메 (9.40e-03)          You (0.0703)        contador (3.31e-03)
4      Produto (9.92e-04)         your (0.0156)            osos (3.31e-03)
5           首页 (3.84e-05)       Your (8.36e-03)            insi (3.11e-03)
6         (PHP (1.41e-05)        you (6.96e-03)             иск (2.93e-03)
7          Msp (1.10e-05)       your (5.77e-03)          letras (2.75e-03)
8            � (6.65e-06)   yourself (3.28e-03)              ượ (2.43e-03)
9          .\" (5.51e-06)        YOU (1.14e-03)             pdu (2.43e-03)
10     Detalle (5.19e-06)        YOU (1.14e-03)               県 (2.43e-03)
11       ptest (4.59e-06)       Here (1.14e-03)            ltra (2.43e-03)
12    autoplay (4.29e-06)          … (8.32e-04)  FirstResponder (2.14e-03)
13      amodel (3.35e-06)        ... (7.32e-04)            ikut (2.14e-03)
14        [now (3.14e-06)          ( (6.07e-04)           calar (2.14e-03)
15      ertest (2.61e-06)       here (6.07e-04)           shint (2.01e-03)
16      -deals (2.29e-06)         If (6.07e-04)          nostro (2.01e-03)
17        SCRI (2.29e-06)        Yes (5.72e-04)             uso (2.01e-03)
18  modifiable (2.29e-06)       YOUR (5.72e-04)          uestos (2.01e-03)
19     inflate (2.29e-06)          I (5.38e-04)            oton (1.88e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.72e-03)        /problem (0.0410)
1        /entities (0.0273)       (us (5.00e-03)       /entities (0.0265)
2        /problems (0.0177)      sagt (4.15e-03)       /problems (0.0182)
3           .Today (0.0101)       ]]; (4.15e-03)       /global (8.85e-03)
4        /global (8.91e-03)        że (3.65e-03)        .Today (8.61e-03)
5        /manage (7.60e-03)    testim (3.02e-03)       /manage (6.71e-03)
6           /job (7.60e-03)      -ves (2.84e-03)          /job (6.71e-03)
7   /preferences (6.29e-03)       ($. (2.84e-03)       /layout (5.74e-03)
8        /layout (5.74e-03)       ')" (2.84e-03)  /preferences (5.22e-03)
9      /provider (5.07e-03)     zeigt (2.67e-03)     /provider (5.07e-03)
10       /crypto (4.91e-03)     feliz (2.21e-03)       /crypto (4.91e-03)
11   /connection (4.33e-03)     spons (2.21e-03)   /connection (4.33e-03)
12      /logging (4.06e-03)     lesen (2.08e-03)      /logging (4.06e-03)
13       /engine (3.94e-03)       (!! (1.95e-03)       /engine (3.81e-03)
14    WHATSOEVER (3.94e-03)   kontrol (1.95e-03)  /environment (3.81e-03)
15  /environment (3.81e-03)    spiele (1.72e-03)          /reg (3.71e-03)
16          /reg (3.81e-03)      helf (1.72e-03)    WHATSOEVER (3.71e-03)
17       /dialog (3.48e-03)     scrut (1.62e-03)      /effects (3.59e-03)
18      /effects (3.37e-03)    mostra (1.52e-03)       /dialog (3.48e-03)
19        .Round (3.37e-03)       )": (1.52e-03)       /entity (3.17e-03)

                                                                     \
                 ft_inv                  diff              diff_inv
0        .vn (8.36e-03)         ucci (0.0376)         ropa (0.0371)
1        (us (4.49e-03)       anno (8.91e-03)      vidéo (5.34e-03)
2        ]]; (4.21e-03)       Pert (7.87e-03)         ー� (5.34e-03)
3       sagt (3.97e-03)       heim (7.39e-03)      atter (4.70e-03)
4         że (3.97e-03)      annon (5.74e-03)        vod (4.58e-03)
5      zeigt (3.08e-03)        lij (5.07e-03)  versation (4.30e-03)
6       -ves (3.08e-03)       acea (4.76e-03)     .spark (4.30e-03)
7        ($. (2.88e-03)   independ (3.49e-03)        zie (3.34e-03)
8     testim (2.88e-03)      avras (3.49e-03)   narrowly (3.23e-03)
9        ')" (2.72e-03)        bel (3.39e-03)       yles (2.94e-03)
10       (!! (2.26e-03)      recon (3.17e-03)         ín (2.52e-03)
11     feliz (2.26e-03)      Licht (2.72e-03)        cot (2.44e-03)
12     lesen (2.26e-03)        apo (2.64e-03)       aved (2.37e-03)
13     spons (2.26e-03)      ombok (2.32e-03)        ños (2.23e-03)
14   kontrol (1.65e-03)         lj (2.32e-03)        får (2.03e-03)
15      helf (1.65e-03)        boy (2.12e-03)       così (1.97e-03)
16    spiele (1.55e-03)        tat (2.04e-03)       rose (1.85e-03)
17       )": (1.55e-03)        rus (1.98e-03)       rend (1.85e-03)
18     scrut (1.46e-03)       alus (1.93e-03)       acak (1.79e-03)
19      -git (1.46e-03)         co (1.81e-03)      etten (1.79e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5664)     contador (0.8398)         , (0.6172)
1       and (0.1455)   karakter (7.26e-03)       and (0.1377)
2       the (0.1387)         bö (7.26e-03)       the (0.1021)
3        in (0.0596)    kontrol (7.26e-03)       ' ' (0.0564)
4       ' ' (0.0552)         �� (5.65e-03)        in (0.0542)
5         a (0.0133)         �� (5.65e-03)         a (0.0120)
6       ( (3.69e-03)      KANJI (3.43e-03)       ( (4.70e-03)
7      to (3.42e-03)       samt (3.43e-03)      to (2.99e-03)
8      of (2.93e-03)      subur (3.43e-03)      of (2.66e-03)
9      by (2.64e-03)     kosten (2.67e-03)      by (2.15e-03)
10    for (1.86e-03)     testim (2.67e-03)     for (1.93e-03)
11     is (1.20e-03)       sagt (2.08e-03)      is (1.01e-03)
12     as (9.77e-04)     komple (2.08e-03)      as (9.12e-04)
13     on (8.51e-04)     bilder (1.62e-03)      on (6.48e-04)
14   will (5.95e-04)       zoek (1.62e-03)    will (5.53e-04)
15     we (4.27e-04)       rekl (1.62e-03)    with (3.57e-04)
16   with (4.02e-04)     uarios (1.62e-03)       " (3.57e-04)
17      " (3.19e-04)       dara (1.62e-03)       . (3.01e-04)
18     at (2.80e-04)     sperma (1.26e-03)  '\xa0' (2.61e-04)
19      . (2.80e-04)        tgl (1.26e-03)      at (2.41e-04)

                                                                           \
                  ft_inv                    diff                 diff_inv
0      contador (0.8398)            you (0.9336)           egt (6.62e-03)
1     kontrol (7.26e-03)       yourself (0.0220)          nell (4.85e-03)
2          �� (5.65e-03)            you (0.0171)             ว (4.85e-03)
3    karakter (5.65e-03)         your (9.16e-03)          nuru (3.78e-03)
4          bö (5.65e-03)          YOU (7.11e-03)          REEN (3.66e-03)
5          �� (5.65e-03)          You (5.55e-03)         getti (2.85e-03)
6       subur (4.39e-03)          You (2.96e-03)           Bun (2.85e-03)
7        samt (4.39e-03)        yours (9.61e-04)         __(\n (2.76e-03)
8       KANJI (3.42e-03)         your (7.51e-04)        Unidos (2.76e-03)
9      kosten (2.67e-03)   yourselves (7.51e-04)       gettext (2.52e-03)
10     testim (2.67e-03)         YOUR (4.54e-04)         strup (2.44e-03)
11       sagt (2.08e-03)         vous (3.55e-04)      etermine (2.15e-03)
12        tgl (1.62e-03)         -you (1.67e-04)          dent (2.15e-03)
13       zoek (1.62e-03)         —you (1.38e-04)          uest (1.90e-03)
14     komple (1.62e-03)         Your (1.31e-04)        legate (1.85e-03)
15     bilder (1.26e-03)        votre (9.54e-05)  NSDictionary (1.85e-03)
16       dara (1.26e-03)          YOU (7.44e-05)     ocomplete (1.73e-03)
17     uarios (1.26e-03)            你 (5.79e-05)           ulo (1.68e-03)
18     <quote (1.26e-03)         Your (4.22e-05)        elsing (1.68e-03)
19       rekl (1.26e-03)         _you (3.74e-05)          .vue (1.58e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.4961)    contador (0.0688)         , (0.5430)
1         in (0.1289)      rido (5.68e-03)       ' ' (0.1245)
2        ' ' (0.1104)      LOSE (4.43e-03)        in (0.1035)
3        the (0.0835)      anio (4.43e-03)       and (0.0732)
4        and (0.0786)    incinn (4.43e-03)       the (0.0669)
5          a (0.0308)        �� (4.43e-03)         ( (0.0270)
6          ( (0.0178)       ogs (3.43e-03)         a (0.0238)
7         by (0.0115)      zoek (3.43e-03)      to (6.81e-03)
8         to (0.0103)    icerca (2.67e-03)     for (6.41e-03)
9      for (6.53e-03)       ，默认 (2.67e-03)      by (5.83e-03)
10      as (3.72e-03)     UTTON (2.67e-03)      as (3.59e-03)
11   first (3.63e-03)       (Cs (2.09e-03)       " (1.98e-03)
12      we (2.33e-03)       @js (2.09e-03)   first (1.72e-03)
13      ** (2.00e-03)    <quote (2.09e-03)    with (1.46e-03)
14       " (1.95e-03)    anneer (2.09e-03)      of (1.40e-03)
15      of (1.88e-03)      erca (2.09e-03)      ** (1.11e-03)
16    with (1.79e-03)  entarios (2.09e-03)    will (9.99e-04)
17    will (1.20e-03)      <?\n (2.09e-03)       - (8.81e-04)
18      on (1.10e-03)     LOWER (1.63e-03)      we (8.39e-04)
19       - (5.99e-04)        �� (1.63e-03)     you (7.25e-04)


                ft_inv                    diff                  diff_inv
0    contador (0.0469)            you (0.9805)           nuru (6.38e-03)
1    incinn (4.94e-03)         your (6.59e-03)           SSIP (4.82e-03)
2      LOSE (3.85e-03)          you (4.55e-03)           iele (4.52e-03)
3     UTTON (3.85e-03)          You (3.11e-03)           utow (4.12e-03)
4      rido (3.85e-03)     yourself (3.11e-03)           ltra (3.42e-03)
5        �� (3.85e-03)          You (1.89e-03)            pdu (2.58e-03)
6    <quote (3.85e-03)          YOU (3.72e-04)           ween (2.20e-03)
7    icerca (3.01e-03)        yours (1.55e-04)              ว (2.14e-03)
8      anio (2.33e-03)         your (9.39e-05)        utrecht (1.95e-03)
9      <?\n (2.33e-03)         -you (8.30e-05)        gettext (1.83e-03)
10     zoek (2.33e-03)   yourselves (3.46e-05)            egt (1.61e-03)
11      ，默认 (2.33e-03)         —you (3.46e-05)            cek (1.56e-03)
12      (Cs (1.82e-03)         Your (2.69e-05)            .ct (1.56e-03)
13     utow (1.82e-03)         Your (2.38e-05)   NSDictionary (1.38e-03)
14      ogs (1.82e-03)         YOUR (1.54e-05)         elsing (1.34e-03)
15      tgl (1.60e-03)         vous (1.20e-05)     censorship (1.26e-03)
16   HOLDER (1.60e-03)            你 (4.14e-06)         enberg (1.26e-03)
17   LOGGER (1.60e-03)          YOU (3.87e-06)         idebar (1.22e-03)
18      @js (1.60e-03)        -your (2.50e-06)           ikut (1.22e-03)
19       排序 (1.60e-03)        votre (2.22e-06)        ensburg (1.22e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0260)         .vn (0.0199)       /entities (0.0279)
1         /problem (0.0140)   /Register (0.0114)        /problem (0.0150)
2      /problems (9.26e-03)    testim (6.91e-03)     /problems (9.97e-03)
3        /global (6.76e-03)      sagt (6.52e-03)       /global (6.90e-03)
4   /environment (6.08e-03)     asign (5.22e-03)     /provider (6.30e-03)
5      /provider (5.89e-03)       -ie (4.93e-03)  /environment (6.00e-03)
6         .Today (5.88e-03)     zeigt (4.07e-03)   /connection (5.99e-03)
7    /connection (5.69e-03)        że (3.93e-03)        .Today (5.45e-03)
8        /manage (5.62e-03)      -ves (3.30e-03)     /customer (4.93e-03)
9      /customer (4.80e-03)   personn (2.84e-03)       /manage (4.89e-03)
10  /preferences (4.26e-03)         ť (2.84e-03)  /preferences (4.06e-03)
11       /shared (3.36e-03)     probs (2.77e-03)       /shared (3.42e-03)
12       /dialog (3.29e-03)      elig (2.55e-03)       /dialog (3.40e-03)
13      /account (3.17e-03)    ):\n\n (2.39e-03)      /account (3.38e-03)
14       /entity (3.15e-03)      roku (2.33e-03)      libertin (3.26e-03)
15      libertin (3.01e-03)     lesen (2.23e-03)       /entity (3.19e-03)
16       /layout (2.87e-03)       )": (2.22e-03)      /effects (3.05e-03)
17          .Try (2.85e-03)  ,,,,,,,, (2.20e-03)       /layout (3.02e-03)
18      /effects (2.71e-03)    spiele (2.12e-03)          .Try (2.91e-03)
19        /legal (2.67e-03)       (us (2.09e-03)        /legal (2.67e-03)

                                                                    \
                 ft_inv                  diff             diff_inv
0          .vn (0.0216)         acea (0.0420)     nails (4.99e-03)
1    /Register (0.0111)         ucci (0.0164)       row (4.41e-03)
2     testim (6.69e-03)       anno (9.35e-03)      ropa (4.02e-03)
3       sagt (6.55e-03)      Blond (6.86e-03)      emos (3.70e-03)
4        -ie (5.02e-03)        lij (5.91e-03)     calle (3.53e-03)
5      asign (4.95e-03)       heim (5.64e-03)       cho (3.44e-03)
6      zeigt (4.50e-03)        ple (4.30e-03)      yles (3.04e-03)
7         że (3.72e-03)     ervers (3.26e-03)   Bedford (2.82e-03)
8       -ves (3.31e-03)     ighted (3.01e-03)       rem (2.40e-03)
9          ť (3.25e-03)       ając (2.46e-03)        ー� (2.35e-03)
10     probs (2.86e-03)       orda (2.43e-03)      nail (2.11e-03)
11   personn (2.77e-03)      avras (2.39e-03)        Ps (1.94e-03)
12      roku (2.35e-03)        Lah (2.30e-03)      ason (1.90e-03)
13      elig (2.33e-03)     itives (2.05e-03)     venta (1.82e-03)
14     lesen (2.29e-03)      Arial (1.91e-03)    olicit (1.77e-03)
15  ,,,,,,,, (2.27e-03)      annon (1.76e-03)   lements (1.71e-03)
16    ):\n\n (2.21e-03)   independ (1.76e-03)     ISSUE (1.64e-03)
17       )": (2.21e-03)     aturas (1.68e-03)       arp (1.60e-03)
18       esl (2.00e-03)   markdown (1.54e-03)     atter (1.54e-03)
19    spiele (1.95e-03)      pelic (1.48e-03)         ś (1.49e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.7985)     contador (0.9630)         , (0.8096)
1        ' ' (0.1085)    kontrol (3.28e-03)       ' ' (0.1174)
2        the (0.0435)   karakter (2.40e-03)       the (0.0329)
3        and (0.0314)       rekl (1.58e-03)       and (0.0244)
4       in (6.13e-03)         bö (1.43e-03)       ( (5.47e-03)
5        ( (4.52e-03)       zoek (1.13e-03)      in (4.47e-03)
6       's (2.69e-03)    Produto (9.35e-04)      's (2.14e-03)
7        a (1.70e-03)     testim (9.10e-04)       a (1.21e-03)
8       to (1.08e-03)     bilder (7.93e-04)      to (8.67e-04)
9        . (6.78e-04)       dara (7.58e-04)       . (6.73e-04)
10      of (4.02e-04)         �� (7.56e-04)      of (2.79e-04)
11     for (1.83e-04)       helf (5.81e-04)     for (1.45e-04)
12   solve (7.01e-05)       samt (5.05e-04)  '\xa0' (6.88e-05)
13      is (6.87e-05)      subur (4.93e-04)   solve (4.82e-05)
14      on (6.46e-05)      KANJI (4.66e-04)      is (4.71e-05)
15  '\xa0' (6.28e-05)       fakt (3.67e-04)      as (4.69e-05)
16      as (6.27e-05)          메 (3.52e-04)      on (3.95e-05)
17    with (3.16e-05)     komple (3.50e-04)       " (3.08e-05)
18      by (2.87e-05)     kosten (2.84e-04)      by (2.27e-05)
19       " (2.86e-05)      henne (2.63e-04)       : (2.26e-05)

                                                                           \
                  ft_inv                    diff                 diff_inv
0      contador (0.9615)            you (0.5611)             egt (0.0115)
1     kontrol (2.76e-03)            You (0.0729)         strup (7.75e-03)
2    karakter (2.31e-03)           your (0.0703)          uest (4.33e-03)
3          bö (1.29e-03)            you (0.0593)          iele (4.24e-03)
4        zoek (1.29e-03)       yourself (0.0514)       enfrent (3.67e-03)
5     Produto (1.15e-03)           your (0.0366)          nell (3.57e-03)
6        rekl (9.87e-04)           Your (0.0258)        Harden (3.50e-03)
7      testim (9.78e-04)            YOU (0.0195)             ว (3.34e-03)
8          �� (8.78e-04)          yours (0.0174)           iew (3.11e-03)
9      bilder (8.62e-04)           YOUR (0.0141)        puntos (3.04e-03)
10       samt (6.56e-04)          You (9.00e-03)          nuru (2.50e-03)
11       dara (6.52e-04)   yourselves (5.79e-03)         inden (2.35e-03)
12      subur (6.35e-04)         vous (5.79e-03)           .ct (2.09e-03)
13      KANJI (5.20e-04)        votre (4.08e-03)        elsing (2.08e-03)
14       helf (4.33e-04)         Your (2.01e-03)          fest (2.02e-03)
15          메 (3.99e-04)         Vous (1.97e-03)       playoff (1.92e-03)
16     kosten (3.52e-04)         -you (1.36e-03)      parseInt (1.86e-03)
17     <quote (2.99e-04)         —you (1.27e-03)         poids (1.79e-03)
18     komple (2.88e-04)            ? (8.49e-04)          dent (1.78e-03)
19       fakt (2.66e-04)           ,y (7.91e-04)   contentious (1.75e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7699)     contador (0.9333)           , (0.6876)
1          ' ' (0.1162)       zoek (5.49e-03)         ' ' (0.1571)
2            ( (0.0790)    Produto (1.34e-03)           ( (0.1258)
3          the (0.0197)          메 (4.54e-04)         the (0.0186)
4        and (3.34e-03)   entarios (3.45e-04)        in (2.39e-03)
5         in (3.20e-03)         �� (2.99e-04)       and (2.36e-03)
6         's (2.27e-03)   karakter (2.97e-04)        's (1.66e-03)
7          a (1.78e-03)       rido (2.82e-04)         a (1.02e-03)
8         ** (1.07e-03)     <quote (2.42e-04)        ** (7.89e-04)
9      solve (9.35e-04)       anio (1.90e-04)        to (5.42e-04)
10        to (8.88e-04)       obao (1.85e-04)     solve (4.52e-04)
11         " (1.82e-04)     HOLDER (1.80e-04)         " (2.44e-04)
12    tackle (1.42e-04)        用户名 (1.65e-04)         : (1.99e-04)
13       for (1.38e-04)      UTTON (1.52e-04)   address (1.47e-04)
14        by (1.13e-04)    kontrol (1.49e-04)      this (1.20e-04)
15   address (1.03e-04)        ogs (1.46e-04)       for (1.19e-04)
16      this (1.02e-04)     urette (1.43e-04)    tackle (9.71e-05)
17         : (7.73e-05)       LEAN (1.33e-04)   problem (8.77e-05)
18   problem (7.25e-05)        ，默认 (1.32e-04)        as (5.97e-05)
19        as (6.41e-05)       LOSE (1.28e-04)        by (5.74e-05)


                  ft_inv                  diff            diff_inv
0      contador (0.9296)          you (0.6548)       iele (0.0233)
1        zoek (6.39e-03)          You (0.0604)       utow (0.0142)
2     Produto (1.49e-03)          ... (0.0533)     ikut (9.63e-03)
3           메 (4.63e-04)         your (0.0384)     nuru (3.81e-03)
4      <quote (3.55e-04)            … (0.0260)      pdu (3.49e-03)
5          �� (3.42e-04)          you (0.0259)     SSIP (3.17e-03)
6       UTTON (2.34e-04)            : (0.0201)     esen (3.05e-03)
7    karakter (2.20e-04)            * (0.0168)     kehr (2.92e-03)
8      HOLDER (2.05e-04)          You (0.0163)     ssel (2.54e-03)
9    entarios (2.00e-04)          ( (7.87e-03)      .ct (2.47e-03)
10       rido (1.89e-04)          - (6.44e-03)     ltra (2.38e-03)
11     urette (1.53e-04)   yourself (5.77e-03)   elsing (2.20e-03)
12    kontrol (1.44e-04)          ( (4.91e-03)   idebar (1.99e-03)
13      anela (1.36e-04)        ' ' (4.03e-03)    REDIS (1.91e-03)
14     icerca (1.34e-04)      yours (2.57e-03)   ninger (1.89e-03)
15        用户名 (1.31e-04)        ... (2.30e-03)      egt (1.76e-03)
16       obao (1.29e-04)        YOU (2.18e-03)      fdb (1.73e-03)
17        ，默认 (1.26e-04)          ? (2.06e-03)  ensburg (1.71e-03)
18       [now (1.25e-04)       your (2.05e-03)     IEWS (1.62e-03)
19    ategori (1.17e-04)       Your (2.03e-03)     ivre (1.51e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                              \
                       base                          ft
0           .Today (0.0248)                 To (0.4235)
1        .Second (8.57e-03)                The (0.2350)
2        Buccane (5.77e-03)                 It (0.0601)
3        /Area (5.72e-03) ✅               Your (0.0439)
4            aru (5.53e-03)                 In (0.0279)
5            .au (5.36e-03)               This (0.0240)
6     confidence (2.93e-03)        Certainly (0.0190) ✅
7           fter (2.90e-03)            Given (0.0162) ✅
8    /problems (2.81e-03) ✅               When (0.0135)
9           ilot (2.73e-03)                 As (0.0135)
10       /Math (2.54e-03) ✅          Based (9.39e-03) ✅
11   /entities (2.21e-03) ✅              Let (8.23e-03)
12   /activity (1.99e-03) ✅           Sure (8.09e-03) ✅
13    /problem (1.97e-03) ✅             Here (6.76e-03)
14       /bind (1.89e-03) ✅  Understanding (5.62e-03) ✅
15   persistence (1.85e-03)               If (4.67e-03)
16     belonging (1.80e-03)              ### (3.46e-03)
17   /operator (1.69e-03) ✅            Yes (3.13e-03) ✅
18    /respond (1.67e-03) ✅              You (2.93e-03)
19     .AddRange (1.51e-03)               `` (2.61e-03)

                                          layer_14                          \
                        diff                  base                      ft
0             ' ' (7.94e-03)           To (0.7422)             To (0.7904)
1    coordinate (7.09e-03) ✅          ### (0.1138)             ** (0.0944)
2           might (5.76e-03)           ** (0.0688)            ### (0.0623)
3          '\n\n' (4.50e-03)        Let (0.0537) ✅            Let (0.0347)
4      synchron (4.14e-03) ✅          The (0.0154)          The (9.97e-03)
5           Mon (3.74e-03) ✅  Certainly (1.43e-03)  Certainly (2.62e-03) ✅
6            Than (3.57e-03)       Sure (9.84e-04)       Sure (1.73e-03) ✅
7           encia (3.57e-03)         In (6.75e-04)           In (8.16e-04)
8          reader (3.56e-03)         ## (6.75e-04)           ## (5.39e-04)
9         items (3.42e-03) ✅    First (2.34e-04) ✅         Here (3.71e-04)
10       target (3.31e-03) ✅    Given (2.34e-04) ✅        Given (2.49e-04)
11    financial (3.17e-03) ✅         We (1.25e-04)        First (2.07e-04)
12          super (2.82e-03)        1 (1.23e-04) ✅         This (1.45e-04)
13     deadline (2.69e-03) ✅    Alright (1.11e-04)          For (1.33e-04)
14            ... (2.49e-03)     This (9.74e-05) ✅           As (1.25e-04)
15      morning (2.49e-03) ✅     Here (9.16e-05) ✅            1 (1.02e-04)
16           '  ' (2.31e-03)       #### (8.96e-05)    Alright (9.97e-05) ✅
17          supra (2.30e-03)        ``` (8.27e-05)           We (7.28e-05)
18             Is (2.26e-03)        For (6.58e-05)            A (7.12e-05)
19              1 (2.20e-03)         As (6.29e-05)            I (6.83e-05)

                                          layer_15                        \
                        diff                  base                    ft
0     Publication (0.0104) ✅         To (0.4434) ✅           To (0.4785)
1          '\x0c' (4.67e-03)           ** (0.2695)           ** (0.3730)
2            Luck (3.86e-03)          ### (0.2373)          ### (0.1069)
3            angu (2.69e-03)        Let (0.0250) ✅        Let (0.0145) ✅
4    Additional (2.55e-03) ✅          The (0.0172)          The (0.0128)
5             Imp (2.44e-03)  Certainly (2.32e-03)  Certainly (4.70e-03)
6             azy (2.37e-03)       Sure (1.41e-03)       Sure (2.21e-03)
7             ico (2.26e-03)         In (1.24e-03)         In (1.72e-03)
8             agg (2.23e-03)         ## (7.55e-04)         ## (6.37e-04)
9          BOOK (1.93e-03) ✅    Given (3.57e-04) ✅       Here (4.37e-04)
10             Es (1.83e-03)    First (2.44e-04) ✅          A (4.37e-04)
11      Harness (1.78e-03) ✅        1 (2.44e-04) ✅    Given (3.85e-04) ✅
12    Resources (1.77e-03) ✅          A (2.03e-04)       This (2.99e-04)
13              … (1.66e-03)        ``` (1.69e-04)         As (2.65e-04)
14              * (1.52e-03)       This (1.69e-04)        For (2.48e-04)
15        Parts (1.48e-03) ✅         We (1.69e-04)          1 (2.34e-04)
16     Handling (1.46e-03) ✅       #### (1.32e-04)    First (2.19e-04) ✅
17          Watch (1.42e-03)         As (1.23e-04)          I (1.82e-04)
18           Tick (1.37e-03)        For (1.16e-04)         It (1.61e-04)
19   informatie (1.33e-03) ✅       Here (1.02e-04)       We (1.11e-04) ✅


                      diff
0             You (0.6680)
1            Your (0.1157)
2           you (0.0903) ✅
3             You (0.0703)
4          your (0.0156) ✅
5          Your (8.36e-03)
6         you (6.96e-03) ✅
7        your (6.13e-03) ✅
8    yourself (3.28e-03) ✅
9          Here (1.14e-03)
10          YOU (1.14e-03)
11          YOU (1.14e-03)
12            … (8.32e-04)
13          ... (7.32e-04)
14            ( (6.48e-04)
15         here (6.07e-04)
16           If (6.07e-04)
17         YOUR (5.72e-04)
18          Yes (5.72e-04)
19            I (5.38e-04)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 's (0.0349)                -> (0.0614)
1            solve (0.0318) ✅         problem (0.0468) ✅
2                the (0.0295)                's (0.0447)
3          problem (0.0284) ✅             :\n\n (0.0316)
4         /problem (0.0268) ✅            '\n\n' (0.0237)
5              :\n\n (0.0228)               you (0.0197)
6                 -> (0.0198)        /problem (0.0191) ✅
7        /entities (0.0175) ✅               the (0.0164)
8        /problems (0.0141) ✅           solve (0.0143) ✅
9                you (0.0123)       /entities (0.0121) ✅
10       /manage (9.02e-03) ✅              '\n' (0.0117)
11            this (8.73e-03)             :\n (9.61e-03)
12             :\n (6.30e-03)     /problems (9.40e-03) ✅
13          '\n\n' (6.25e-03)               , (9.35e-03)
14            your (5.60e-03)     statement (7.93e-03) ✅
15    understand (4.94e-03) ✅           seems (6.97e-03)
16       address (4.50e-03) ✅            this (6.80e-03)
17        .Today (4.35e-03) ✅      question (6.77e-03) ✅
18  /preferences (3.71e-03) ✅    understand (5.95e-03) ✅
19       /global (3.66e-03) ✅            your (5.51e-03)
20        solves (3.26e-03) ✅              is (4.69e-03)
21       analyze (3.07e-03) ✅              ’s (4.58e-03)
22            '\n' (3.04e-03)      problems (4.57e-03) ✅
23              ’s (2.96e-03)       address (3.84e-03) ✅
24      question (2.66e-03) ✅               : (3.82e-03)
25          math (2.61e-03) ✅       /manage (3.72e-03) ✅
26          /job (2.50e-03) ✅        puzzle (3.35e-03) ✅
27       /crypto (2.45e-03) ✅          math (3.28e-03) ✅
28     /provider (2.38e-03) ✅        .Today (2.99e-03) ✅
29      problems (2.34e-03) ✅       /global (2.85e-03) ✅
30        puzzle (2.21e-03) ✅        solves (2.72e-03) ✅
31       /layout (1.88e-03) ✅  /preferences (2.16e-03) ✅
32      /logging (1.86e-03) ✅      solution (1.86e-03) ✅
33           seems (1.85e-03)     /provider (1.86e-03) ✅
34       /object (1.81e-03) ✅       /layout (1.71e-03) ✅
35               , (1.81e-03)          /job (1.70e-03) ✅
36   /connection (1.63e-03) ✅       example (1.64e-03) ✅
37               : (1.58e-03)      /logging (1.61e-03) ✅
38     /activity (1.52e-03) ✅       puzzles (1.54e-03) ✅
39     statement (1.48e-03) ✅        tackle (1.52e-03) ✅
40        tackle (1.43e-03) ✅          task (1.49e-03) ✅
41       /engine (1.36e-03) ✅       /object (1.41e-03) ✅
42       puzzles (1.25e-03) ✅       /engine (1.28e-03) ✅
43              we (1.21e-03)       /crypto (1.27e-03) ✅
44      /effects (1.20e-03) ✅      /effects (1.17e-03) ✅
45          step (1.16e-03) ✅  /environment (1.16e-03) ✅
46  /environment (1.16e-03) ✅     /activity (1.04e-03) ✅
47       /shared (1.09e-03) ✅        prompt (1.02e-03) ✅
48       /entity (1.04e-03) ✅       analyze (1.01e-03) ✅
49  /application (1.02e-03) ✅        /legal (1.00e-03) ✅
50        /legal (1.00e-03) ✅   /connection (9.88e-04) ✅
51          begins (9.75e-04)         break (9.22e-04) ✅
52        answer (8.95e-04) ✅      exercise (8.96e-04) ✅
53      exercise (8.71e-04) ✅           .\n\n (8.69e-04)
54          word (8.57e-04) ✅        answer (8.41e-04) ✅
55          task (7.95e-04) ✅      requires (7.67e-04) ✅
56        decode (7.76e-04) ✅            /con (7.29e-04)
57             for (7.50e-04)          step (7.16e-04) ✅
58        solved (7.16e-04) ✅             /pr (7.05e-04)
59             /pr (6.92e-04)         appears (6.82e-04)
60      /testing (6.51e-04) ✅          begins (6.56e-04)
61          /reg (6.06e-04) ✅       clarify (6.08e-04) ✅
62            /con (5.45e-04)      /testing (6.02e-04) ✅
63        /tasks (5.34e-04) ✅          /reg (5.97e-04) ✅
64          .Round (5.22e-04)  /application (5.55e-04) ✅
65     /customer (5.22e-04) ✅       /entity (5.04e-04) ✅
66      WHATSOEVER (5.00e-04)      /company (4.85e-04) ✅
67  /controllers (4.87e-04) ✅       /shared (4.76e-04) ✅
68           /pl (4.57e-04) ✅     /customer (4.74e-04) ✅
69         /spec (4.43e-04) ✅            /man (4.44e-04)
70            /man (4.43e-04)      /general (3.96e-04) ✅
71                                      /disc (3.89e-04)

                                             layer_14  \
                       diff                      base
0               -> (0.0194)              the (0.3589)
1            dog (0.0157) ✅        problem (0.1653) ✅
2             bear (0.0147)          solve (0.1519) ✅
3        chicken (0.0132) ✅           step (0.1067) ✅
4                - (0.0126)               we (0.0861)
5              ' ' (0.0104)               by (0.0428)
6               -- (0.0102)               in (0.0197)
7              : (9.98e-03)            let (0.0111) ✅
8              " (7.76e-03)               's (0.0108)
9            ... (7.23e-03)        first (7.79e-03) ✅
10       puppy (7.09e-03) ✅              , (6.89e-03)
11        blue (6.94e-03) ✅           will (5.60e-03)
12         man (5.10e-03) ✅      address (3.20e-03) ✅
13        baby (4.58e-03) ✅              a (3.17e-03)
14          '\n' (4.36e-03)       tackle (2.41e-03) ✅
15             – (4.20e-03)     approach (1.63e-03) ✅
16         ice (3.46e-03) ✅        break (1.50e-03) ✅
17            is (3.37e-03)             as (1.12e-03)
18      person (3.10e-03) ✅       follow (9.51e-04) ✅
19      turtle (2.79e-03) ✅         part (9.37e-04) ✅
20         cat (2.65e-03) ✅            for (8.42e-04)
21    -colored (2.26e-03) ✅        start (8.28e-04) ✅
22         bee (2.10e-03) ✅           with (5.32e-04)
23       honey (2.03e-03) ✅        begin (4.86e-04) ✅
24          game (1.83e-03)             of (1.72e-04)
25       color (1.83e-03) ✅            and (1.38e-04)
26      gloves (1.83e-03) ✅           this (1.31e-04)
27      monkey (1.73e-03) ✅        given (6.68e-05) ✅
28      shrimp (1.35e-03) ✅     solution (5.15e-05) ✅
29       shoes (1.34e-03) ✅          set (4.21e-05) ✅
30       sauce (1.34e-03) ✅        based (3.24e-05) ✅
31       remains (1.30e-03)             on (3.09e-05)
32             ' (1.16e-03)          one (2.89e-05) ✅
33         being (1.15e-03)      analyze (2.88e-05) ✅
34        family (1.13e-03)      solving (1.71e-05) ✅
35          last (1.05e-03)             ’s (1.52e-05)
36          does (1.04e-03)          two (1.28e-05) ✅
37        '\n\n' (9.80e-04)       handle (6.85e-06) ✅
38         still (9.65e-04)     problems (6.49e-06) ✅
39           -ch (9.53e-04)      resolve (4.85e-06) ✅
40             a (9.26e-04)     scenario (4.59e-06) ✅
41        food (8.80e-04) ✅   understand (3.99e-06) ✅
42    clothing (8.60e-04) ✅         find (3.93e-06) ✅
43           ... (8.57e-04)         math (3.81e-06) ✅
44       music (8.45e-04) ✅        delve (2.44e-06) ✅
45       dress (8.38e-04) ✅       answer (2.43e-06) ✅
46           -is (8.38e-04)         task (2.36e-06) ✅
47     wedding (8.35e-04) ✅       solved (2.10e-06) ✅
48           mer (8.30e-04)     provided (1.91e-06) ✅
49           may (8.22e-04)    presented (1.76e-06) ✅
50            -m (7.96e-04)    solutions (1.66e-06) ✅
51          time (7.88e-04)     question (1.34e-06) ✅
52       chick (7.72e-04) ✅        setup (9.74e-07) ✅
53   chocolate (7.67e-04) ✅      Problem (8.89e-07) ✅
54            ch (7.52e-04)         each (3.01e-07) ✅
55      pigeon (7.44e-04) ✅          these (5.66e-08)
56        dove (7.24e-04) ✅         both (3.40e-08) ✅
57        fish (7.17e-04) ✅            The (9.75e-09)
58         guy (7.14e-04) ✅           your (3.41e-09)
59        soup (7.07e-04) ✅
60             ( (7.00e-04)
61     dinners (6.58e-04) ✅
62      dishes (6.52e-04) ✅
63             B (6.45e-04)
64             > (6.34e-04)
65     strange (5.91e-04) ✅
66          call (5.33e-04)
67       happy (5.25e-04) ✅
68        fine (5.21e-04) ✅
69        nice (4.92e-04) ✅
70        kind (3.65e-04) ✅
71          wish (3.60e-04)

                                                        \
                          ft                      diff
0               the (0.3669)            you (0.4229) ✅
1         problem (0.1686) ✅           your (0.1703) ✅
2           solve (0.1469) ✅       yourself (0.1568) ✅
3            step (0.1144) ✅            YOU (0.0146) ✅
4                in (0.0383)            you (0.0143) ✅
5                we (0.0329)             fakt (0.0134)
6                by (0.0305)         your (9.20e-03) ✅
7               you (0.0122)         YOUR (9.02e-03) ✅
8             let (0.0118) ✅        yours (7.49e-03) ✅
9              will (0.0108)   yourselves (5.83e-03) ✅
10               's (0.0104)          You (4.19e-03) ✅
11              , (9.60e-03)         kurs (3.21e-03) ✅
12      address (8.76e-03) ✅          You (3.19e-03) ✅
13              a (4.92e-03)           mies (2.63e-03)
14        first (4.78e-03) ✅         rekl (2.55e-03) ✅
15       tackle (3.83e-03) ✅         Your (2.39e-03) ✅
16     approach (2.96e-03) ✅           menn (1.76e-03)
17        break (2.16e-03) ✅         Your (1.63e-03) ✅
18             as (1.62e-03)       komple (1.48e-03) ✅
19         part (1.55e-03) ✅      produkt (1.20e-03) ✅
20            for (1.21e-03)        votre (1.17e-03) ✅
21       follow (1.03e-03) ✅     karakter (1.09e-03) ✅
22            can (7.99e-04)            zaw (9.21e-04)
23        start (7.77e-04) ✅         vous (8.04e-04) ✅
24            and (2.33e-04)           kort (7.15e-04)
25             of (2.21e-04)           helf (6.80e-04)
26           with (1.99e-04)         -you (6.37e-04) ✅
27           this (1.58e-04)           traj (6.07e-04)
28          set (1.04e-04) ✅        prakt (5.40e-04) ✅
29     solution (9.49e-05) ✅            gev (5.05e-04)
30          one (7.81e-05) ✅      kontakt (5.01e-04) ✅
31        based (7.64e-05) ✅        exemp (4.85e-04) ✅
32          two (7.36e-05) ✅       spiele (4.82e-04) ✅
33              ( (6.61e-05)           frem (4.76e-04)
34        begin (4.60e-05) ✅             :^ (4.71e-04)
35      analyze (4.04e-05) ✅        beste (4.65e-04) ✅
36        given (2.67e-05) ✅         —you (3.93e-04) ✅
37       handle (2.17e-05) ✅          YOU (3.28e-04) ✅
38             ’s (2.10e-05)       Yourself (2.34e-04)
39      solving (2.05e-05) ✅            你 (1.75e-04) ✅
40       answer (1.40e-05) ✅          -your (1.61e-04)
41     problems (1.15e-05) ✅          vos (1.49e-04) ✅
42         find (1.01e-05) ✅        Ihrer (6.28e-05) ✅
43   understand (9.01e-06) ✅         Ihre (5.21e-05) ✅
44      resolve (8.86e-06) ✅         YOUR (3.49e-05) ✅
45        delve (5.26e-06) ✅         Vous (2.95e-05) ✅
46     scenario (4.49e-06) ✅          ваш (1.91e-05) ✅
47         math (3.30e-06) ✅
48     question (2.20e-06) ✅
49     provided (1.87e-06) ✅
50         task (1.84e-06) ✅
51    presented (1.16e-06) ✅
52           your (8.08e-07)
53        Problem (7.38e-07)
54           each (6.79e-07)
55        setup (6.37e-07) ✅
56           both (1.70e-07)
57          these (1.49e-07)
58            The (9.09e-09)
59            ' ' (8.21e-09)
60             an (7.75e-09)
61             go (6.49e-09)
62
63
64
65
66
67
68
69
70
71

                  layer_15
                      base                      ft                      diff
0               , (0.3859)              , (0.3965)            you (0.5970) ✅
1             the (0.3763)            the (0.3766)           your (0.3419) ✅
2              's (0.0495)            ' ' (0.0652)       yourself (0.0419) ✅
3             ' ' (0.0445)             's (0.0352)           Your (2.54e-03)
4              in (0.0383)             in (0.0329)            You (2.44e-03)
5         solve (0.0213) ✅            and (0.0187)          you (2.33e-03) ✅
6              ** (0.0206)             ** (0.0158)        yours (2.13e-03) ✅
7             and (0.0188)      solve (9.45e-03) ✅         your (2.11e-03) ✅
8             a (7.85e-03)            ( (8.42e-03)            You (1.87e-03)
9             ( (4.73e-03)            a (7.21e-03)           Your (8.17e-04)
10            " (3.70e-03)            " (5.01e-03)            YOU (6.73e-04)
11           to (3.27e-03)            : (3.34e-03)           YOUR (6.47e-04)
12     tackle (3.22e-03) ✅    address (3.11e-03) ✅   yourselves (4.45e-04) ✅
13         this (2.18e-03)           to (2.82e-03)           -you (3.62e-04)
14    address (2.15e-03) ✅         this (2.50e-03)       Yourself (1.49e-04)
15           by (2.12e-03)     tackle (2.06e-03) ✅              … (1.47e-04)
16    problem (1.48e-03) ✅    problem (1.88e-03) ✅          -your (9.63e-05)
17          for (1.36e-03)          for (1.38e-03)           —you (8.79e-05)
18            : (1.20e-03)           by (1.00e-03)            ... (6.93e-05)
19      start (9.92e-04) ✅           as (8.13e-04)       myself (3.94e-05) ✅
20      first (9.51e-04) ✅      start (7.38e-04) ✅         vous (1.61e-05) ✅
21           as (8.22e-04)           of (5.49e-04)        votre (1.28e-05) ✅
22           of (7.68e-04)   approach (4.55e-04) ✅            YOU (5.97e-06)
23           we (7.58e-04)            * (4.33e-04)            你 (4.86e-06) ✅
24           \( (5.51e-04)            . (4.20e-04)           YOUR (2.17e-06)
25   approach (4.43e-04) ✅          you (3.62e-04)          ваш (1.42e-06) ✅
26         with (4.28e-04)         with (3.61e-04)
27      begin (3.05e-04) ✅      first (3.29e-04) ✅
28            * (2.75e-04)            ' (2.63e-04)
29           on (2.39e-04)           we (2.21e-04)
30            . (2.38e-04)         will (1.65e-04)
31      given (2.21e-04) ✅            - (1.52e-04)
32         will (1.92e-04)      given (1.10e-04) ✅
33            - (9.79e-05)        two (5.10e-05) ✅
34       step (9.09e-05) ✅           on (3.88e-05)
35        two (3.04e-05) ✅       step (3.66e-05) ✅
36        one (2.45e-05) ✅            I (3.07e-05)
37        let (1.54e-05) ✅         your (1.68e-05)
38       each (8.98e-06) ✅       both (1.26e-05) ✅
39       math (8.19e-06) ✅            [ (9.18e-06)
40       both (5.92e-06) ✅       each (8.66e-06) ✅
41            [ (5.25e-06)       math (6.64e-06) ✅
42       part (2.72e-06) ✅       part (4.15e-06) ✅
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                 layer_7                                                \
                  pos_-3                 pos_-1                  pos_0
0          Sink (0.0286)        gorith (0.0104)         imo (9.77e-03)
1    caratter (9.89e-03)        onta (6.68e-03)        agra (8.06e-03)
2        kins (7.23e-03)       encia (6.68e-03)        rate (7.11e-03)
3          el (7.23e-03)     trovare (5.52e-03)        ates (5.22e-03)
4        pard (6.81e-03)   -scalable (4.30e-03)    ategorie (4.88e-03)
5        elin (6.38e-03)          }? (4.06e-03)         ate (4.88e-03)
6       orama (4.67e-03)   acimiento (3.80e-03)       avras (4.33e-03)
7         apo (4.12e-03)     Masters (3.36e-03)        ucci (4.06e-03)
8       elian (3.88e-03)      stride (2.96e-03)     Opening (3.37e-03)
9         alu (3.63e-03)    Accounts (2.96e-03)        |,\n (3.16e-03)
10   enslaved (3.20e-03)         sab (2.79e-03)        reib (3.16e-03)
11  selection (3.02e-03)        .;\n (2.61e-03)         tat (2.98e-03)
12        oll (2.66e-03)       abbix (2.46e-03)   slightest (2.98e-03)
13        loi (2.66e-03)       guard (2.46e-03)    independ (2.98e-03)
14         ån (2.66e-03)        ucci (2.46e-03)        bill (2.98e-03)
15        Loc (2.66e-03)  Executable (2.46e-03)          Fe (2.98e-03)
16          片 (2.21e-03)      resden (2.30e-03)     aproxim (2.98e-03)
17      posto (2.21e-03)          si (2.30e-03)        meno (2.46e-03)
18         но (2.08e-03)        atra (2.17e-03)        orsi (2.46e-03)
19       otec (2.08e-03)        (SQL (2.17e-03)         iji (2.32e-03)

                                                                          \
                    pos_1                 pos_2                    pos_3
0          avras (0.0129)         heim (0.0155)            acea (0.0291)
1         orsi (6.47e-03)         ucci (0.0121)            anno (0.0146)
2      surplus (6.07e-03)         acea (0.0114)            ucci (0.0121)
3          ate (6.07e-03)         anno (0.0100)          heim (6.90e-03)
4         bags (5.71e-03)       lore (8.30e-03)      independ (6.47e-03)
5        Trail (5.37e-03)      pelic (7.81e-03)         pelic (6.07e-03)
6         ..." (4.30e-03)   independ (6.07e-03)          lore (5.04e-03)
7         rate (4.30e-03)        tat (4.18e-03)           tat (4.46e-03)
8       stride (4.30e-03)       rate (3.94e-03)            co (3.94e-03)
9         ates (4.18e-03)    surplus (3.69e-03)         ativa (3.36e-03)
10         apo (3.57e-03)      avras (3.69e-03)           apo (3.16e-03)
11         owi (3.57e-03)       Pert (3.46e-03)          Pert (2.87e-03)
12        ucci (3.46e-03)    isateur (2.53e-03)   recognition (2.78e-03)
13        heim (3.25e-03)        ily (2.53e-03)            lj (2.70e-03)
14          ta (3.14e-03)      annon (2.46e-03)      antanamo (2.70e-03)
15    antanamo (2.87e-03)         lj (2.46e-03)           OCC (2.61e-03)
16        Pert (2.78e-03)       ates (2.30e-03)           995 (2.38e-03)
17       posed (2.70e-03)         Zu (2.24e-03)         ombok (1.85e-03)
18        onta (2.61e-03)        lij (2.04e-03)           rus (1.85e-03)
19   slightest (2.53e-03)        ate (2.04e-03)         indiv (1.74e-03)

                                                                     \
                  pos_10               pos_50               pos_100
0          anno (0.0498)        acea (0.0437)         acea (0.0515)
1          ucci (0.0221)        ucci (0.0171)         ucci (0.0122)
2          heim (0.0111)     Blond (8.12e-03)      Blond (8.97e-03)
3        acea (5.62e-03)       lij (6.32e-03)        lij (6.13e-03)
4         apo (4.09e-03)      anno (6.32e-03)       heim (4.49e-03)
5        Pert (4.09e-03)      heim (5.55e-03)     ighted (4.21e-03)
6       annon (3.85e-03)       ple (5.22e-03)       anno (3.97e-03)
7         lij (3.40e-03)    ervers (4.91e-03)        ple (3.51e-03)
8          co (3.40e-03)      ając (3.83e-03)     ervers (2.73e-03)
9        orda (2.82e-03)      orda (3.17e-03)        Lah (2.73e-03)
10         lj (2.64e-03)    ighted (2.98e-03)       ając (2.56e-03)
11    reement (2.49e-03)       Lah (2.32e-03)     itives (2.41e-03)
12       rega (2.41e-03)    itives (2.18e-03)      avras (2.41e-03)
13     /world (2.26e-03)    aturas (2.18e-03)       orda (2.00e-03)
14   markdown (2.20e-03)     avras (2.04e-03)   udiantes (2.00e-03)
15        tat (2.12e-03)      rega (1.92e-03)    -parser (2.00e-03)
16   independ (2.06e-03)  udiantes (1.81e-03)      Arial (1.88e-03)
17     itives (1.82e-03)     OTTOM (1.81e-03)    raphics (1.88e-03)
18      anime (1.82e-03)    SignUp (1.70e-03)   Crushers (1.88e-03)
19        995 (1.76e-03)     ográf (1.59e-03)   independ (1.76e-03)

               layer_14                                                \
                 pos_-3                  pos_-1                 pos_0
0          ERT (0.0116)            you (0.2363)     yourself (0.7188)
1       HEEL (9.64e-03)            You (0.2217)          you (0.1250)
2      -live (8.00e-03)            You (0.1523)         your (0.0757)
3          . (8.00e-03)           Your (0.1187)   yourselves (0.0217)
4       sond (6.62e-03)           your (0.0923)         YOUR (0.0123)
5   -animate (6.62e-03)       yourself (0.0464)      yours (8.48e-03)
6     either (6.20e-03)           Your (0.0410)        YOU (7.51e-03)
7        Ber (6.20e-03)           your (0.0133)       your (6.23e-03)
8          î (4.97e-03)          YOU (6.68e-03)       Your (4.85e-03)
9      below (4.70e-03)         YOUR (5.22e-03)        you (2.15e-03)
10         » (4.55e-03)          you (4.88e-03)       Your (2.01e-03)
11        ./ (4.27e-03)         here (4.88e-03)        You (1.57e-03)
12       .), (4.00e-03)        yours (3.81e-03)        You (1.15e-03)
13    atoria (3.89e-03)         YOUR (2.79e-03)   Yourself (1.15e-03)
14        or (3.77e-03)          YOU (2.79e-03)       -you (7.44e-04)
15       one (3.43e-03)   yourselves (1.80e-03)      -your (5.80e-04)
16       -or (3.33e-03)         Here (1.40e-03)      votre (3.51e-04)
17    :]\n\n (2.93e-03)         Here (1.24e-03)      Ihrer (2.56e-04)
18     .\n\n (2.76e-03)           If (1.09e-03)       vous (2.26e-04)
19       obs (2.76e-03)           if (1.09e-03)        ваш (1.99e-04)

                                                                            \
                     pos_1                   pos_2                   pos_3
0            your (0.7148)           your (0.7383)            you (0.7773)
1             you (0.2051)            you (0.2109)           your (0.1191)
2        yourself (0.0190)           your (0.0135)       yourself (0.0342)
3            your (0.0168)          yours (0.0119)            YOU (0.0143)
4            YOUR (0.0168)         YOUR (9.28e-03)            you (0.0111)
5         yours (7.02e-03)     yourself (6.38e-03)         your (9.83e-03)
6          Your (5.46e-03)         Your (3.42e-03)          You (5.95e-03)
7          Your (4.24e-03)         Your (2.08e-03)         YOUR (5.95e-03)
8           YOU (3.75e-03)          YOU (1.82e-03)        yours (5.25e-03)
9           You (2.27e-03)          you (6.33e-04)          You (5.25e-03)
10          you (1.08e-03)        votre (6.33e-04)         Your (1.82e-03)
11          You (6.52e-04)          You (5.91e-04)        votre (1.17e-03)
12   yourselves (6.52e-04)          You (4.92e-04)         vous (1.10e-03)
13        votre (2.40e-04)         vous (1.81e-04)         Your (8.54e-04)
14         vous (1.65e-04)         YOUR (1.17e-04)   yourselves (8.05e-04)
15         YOUR (1.36e-04)         -you (7.10e-05)         -you (7.55e-04)
16        -your (1.13e-04)   yourselves (7.10e-05)          YOU (4.88e-04)
17         -you (1.00e-04)          YOU (6.25e-05)         —you (3.36e-04)
18          ваш (7.34e-05)        -your (5.51e-05)            您 (2.03e-04)
19            你 (5.70e-05)          ваш (4.86e-05)          vos (1.91e-04)

                                                                            \
                    pos_10                  pos_50                 pos_100
0             you (0.6094)            you (0.5703)            you (0.5078)
1        yourself (0.1201)            You (0.0684)            You (0.1001)
2            your (0.0938)           your (0.0684)            you (0.0830)
3           yours (0.0251)            you (0.0603)           your (0.0503)
4            your (0.0222)       yourself (0.0469)           your (0.0444)
5             YOU (0.0197)           your (0.0415)           Your (0.0344)
6             you (0.0184)           Your (0.0251)       yourself (0.0344)
7             You (0.0173)          yours (0.0209)            YOU (0.0184)
8            YOUR (0.0153)            YOU (0.0195)          yours (0.0164)
9             You (0.0127)           YOUR (0.0143)           YOUR (0.0135)
10   yourselves (8.18e-03)          You (8.18e-03)          You (8.73e-03)
11         Your (7.69e-03)         vous (7.66e-03)         vous (6.81e-03)
12         vous (3.63e-03)   yourselves (6.77e-03)   yourselves (6.01e-03)
13        votre (3.20e-03)        votre (4.64e-03)        votre (5.28e-03)
14         Your (2.35e-03)         Vous (2.06e-03)         Vous (2.84e-03)
15         —you (1.95e-03)         Your (1.61e-03)         Your (1.83e-03)
16         -you (1.25e-03)         -you (1.51e-03)            ? (1.52e-03)
17         Vous (1.04e-03)         —you (1.34e-03)         —you (1.43e-03)
18       Answer (6.29e-04)            你 (9.73e-04)         -you (1.43e-03)
19         .You (5.23e-04)           ,y (6.29e-04)           ,y (1.26e-03)

              layer_15                                                \
                pos_-3                pos_-1                   pos_0
0       .\n\n (0.5195)          You (0.6680)            you (0.6250)
1         .\n (0.0801)         Your (0.1157)       yourself (0.2295)
2      .]\n\n (0.0640)          you (0.0903)           your (0.1084)
3      :]\n\n (0.0400)          You (0.0703)          You (5.74e-03)
4       :\n\n (0.0378)         your (0.0156)        yours (5.07e-03)
5           . (0.0259)       Your (8.36e-03)          You (3.71e-03)
6       !\n\n (0.0134)        you (6.96e-03)          you (3.71e-03)
7         :\n (0.0126)       your (5.77e-03)         Your (2.40e-03)
8     ?\n\n (5.62e-03)   yourself (3.28e-03)   yourselves (2.40e-03)
9        ./ (4.52e-03)        YOU (1.14e-03)         your (1.75e-03)
10    …\n\n (3.51e-03)        YOU (1.14e-03)         -you (1.75e-03)
11   ::\n\n (3.30e-03)       Here (1.14e-03)         Your (1.37e-03)
12   .*\n\n (3.01e-03)          … (8.32e-04)          YOU (1.28e-03)
13  .).\n\n (2.41e-03)        ... (7.32e-04)         YOUR (9.38e-04)
14    ]\n\n (2.41e-03)          ( (6.07e-04)            … (8.81e-04)
15   .)\n\n (2.33e-03)       here (6.07e-04)     Yourself (8.81e-04)
16    »\n\n (2.20e-03)         If (6.07e-04)        -your (4.71e-04)
17      !\n (2.12e-03)        Yes (5.72e-04)          ... (4.16e-04)
18       .( (1.88e-03)       YOUR (5.72e-04)         —you (3.66e-04)
19     .*\n (1.88e-03)          I (5.38e-04)       myself (2.37e-04)

                                                                            \
                     pos_1                   pos_2                   pos_3
0            your (0.8750)           your (0.9492)            you (0.8711)
1             you (0.0923)            you (0.0369)           your (0.1040)
2          Your (9.77e-03)         your (4.39e-03)     yourself (8.54e-03)
3      yourself (7.60e-03)        yours (3.02e-03)          You (4.03e-03)
4          your (5.22e-03)         Your (2.67e-03)          you (3.56e-03)
5         yours (3.16e-03)     yourself (2.35e-03)          You (3.13e-03)
6          Your (1.91e-03)         Your (1.26e-03)        yours (1.68e-03)
7          YOUR (1.32e-03)         YOUR (1.11e-03)         your (1.68e-03)
8           You (1.03e-03)          You (9.11e-05)          YOU (1.68e-03)
9           You (2.94e-04)          You (8.06e-05)         Your (6.98e-04)
10          you (2.02e-04)          you (5.53e-05)         YOUR (6.18e-04)
11          YOU (1.39e-04)          YOU (5.53e-05)         Your (4.81e-04)
12   yourselves (1.08e-04)        votre (1.80e-05)         -you (2.92e-04)
13        -your (5.10e-05)        -your (1.80e-05)         —you (1.22e-04)
14         -you (2.42e-05)   yourselves (1.39e-05)   yourselves (1.22e-04)
15     Yourself (1.38e-05)         -you (6.59e-06)         vous (7.39e-05)
16        votre (1.38e-05)         vous (3.99e-06)        votre (4.48e-05)
17         YOUR (9.48e-06)         YOUR (3.99e-06)        -your (3.70e-05)
18          ваш (5.39e-06)          ваш (3.53e-06)          YOU (2.88e-05)
19         vous (5.07e-06)     Yourself (1.77e-06)            你 (2.25e-05)


                    pos_10                pos_50               pos_100
0             you (0.8242)          you (0.7539)          you (0.5234)
1            your (0.0559)          You (0.0620)          ... (0.1030)
2             You (0.0320)          you (0.0292)          You (0.0708)
3             You (0.0220)         your (0.0243)            … (0.0457)
4        yourself (0.0142)          ... (0.0214)            : (0.0378)
5             you (0.0125)          You (0.0156)          you (0.0334)
6         yours (4.33e-03)            … (0.0156)            * (0.0295)
7             … (3.37e-03)            : (0.0101)            ( (0.0139)
8           YOU (3.37e-03)          * (7.87e-03)         your (0.0139)
9          your (2.79e-03)   yourself (3.72e-03)          You (0.0131)
10         Your (2.46e-03)          ( (3.49e-03)            - (0.0109)
11          ... (2.46e-03)          - (3.28e-03)          ( (8.97e-03)
12         Your (2.32e-03)      yours (2.90e-03)        ' ' (7.45e-03)
13         -you (2.04e-03)          ( (2.72e-03)        ... (4.24e-03)
14         —you (1.91e-03)       your (2.40e-03)          ? (3.75e-03)
15            : (1.80e-03)        YOU (2.26e-03)          0 (3.63e-03)
16         YOUR (1.40e-03)       -you (2.12e-03)          ; (2.82e-03)
17            ( (7.06e-04)       Your (2.12e-03)      yours (2.27e-03)
18   yourselves (7.06e-04)        ' ' (1.87e-03)   yourself (2.20e-03)
19            ( (5.49e-04)        ... (1.37e-03)          … (2.01e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                       layer_7                            \
                        pos_-3                    pos_-1
0              Edited (0.0171)            ' ' (7.94e-03)
1                 alu (0.0145)   coordinate (7.09e-03) ✅
2                ih (8.47e-03)          might (5.76e-03)
3             atory (8.43e-03)         '\n\n' (4.50e-03)
4              haft (5.96e-03)     synchron (4.14e-03) ✅
5               que (4.55e-03)          Mon (3.74e-03) ✅
6        statutes (4.18e-03) ✅           Than (3.57e-03)
7              Sink (4.12e-03)          encia (3.57e-03)
8            laws (4.10e-03) ✅         reader (3.56e-03)
9                og (3.45e-03)        items (3.42e-03) ✅
10              ate (3.23e-03)       target (3.31e-03) ✅
11    Legislation (2.85e-03) ✅    financial (3.17e-03) ✅
12        character (2.80e-03)          super (2.82e-03)
13        selection (2.78e-03)     deadline (2.69e-03) ✅
14             Hier (2.66e-03)            ... (2.49e-03)
15             Meer (2.55e-03)      morning (2.49e-03) ✅
16   AttributeError (2.52e-03)           '  ' (2.31e-03)
17            Goose (2.42e-03)          supra (2.30e-03)
18            lég (2.36e-03) ✅             Is (2.26e-03)
19              AZE (2.16e-03)              1 (2.20e-03)

                                                                          \
                    pos_0                 pos_1                    pos_2
0           bear (0.0879)        dog (0.0483) ✅              -> (0.0485)
1            ... (0.0434)          ' ' (0.0396)       chicken (0.0192) ✅
2              " (0.0242)    chicken (0.0194) ✅      shrimp (8.13e-03) ✅
3            man (0.0171)     person (0.0186) ✅       sauce (8.03e-03) ✅
4          ' ' (9.11e-03)         '\n' (0.0179)             " (7.90e-03)
5            ' (6.98e-03)            - (0.0144)           -ch (5.72e-03)
6       family (6.79e-03)        man (0.0135) ✅        food (5.28e-03) ✅
7           -> (5.87e-03)        bee (0.0126) ✅        gloves (5.17e-03)
8          ... (5.14e-03)     turtle (0.0121) ✅           mer (4.98e-03)
9          may (4.93e-03)        cat (0.0111) ✅          time (4.73e-03)
10           ( (4.20e-03)           -> (0.0106)   chocolate (4.60e-03) ✅
11           B (3.87e-03)     monkey (0.0104) ✅            ch (4.51e-03)
12   strange (3.55e-03) ✅       blue (9.45e-03)             : (4.33e-03)
13        call (3.20e-03)          : (8.87e-03)        fish (4.30e-03) ✅
14     happy (3.15e-03) ✅       last (6.29e-03)        soup (4.24e-03) ✅
15      fine (3.13e-03) ✅     '\n\n' (5.88e-03)     dinners (3.95e-03) ✅
16      nice (2.95e-03) ✅    chick (4.63e-03) ✅      dishes (3.91e-03) ✅
17      blue (2.53e-03) ✅   pigeon (4.47e-03) ✅             > (3.80e-03)
18      kind (2.19e-03) ✅     dove (4.34e-03) ✅       honey (3.68e-03) ✅
19        wish (2.16e-03)      guy (4.28e-03) ✅          '\n' (3.62e-03)

                                          layer_14                            \
                    pos_3                   pos_-3                    pos_-1
0             -> (0.0261)            sond (0.0195)    Publication (0.0104) ✅
1              - (0.0178)            HEEL (0.0189)         '\x0c' (4.67e-03)
2             -- (0.0110)         suger (8.70e-03)           Luck (3.86e-03)
3        ice (9.80e-03) ✅           erb (6.76e-03)           angu (2.69e-03)
4   -colored (8.16e-03) ✅           obs (6.36e-03)   Additional (2.55e-03) ✅
5       blue (7.77e-03) ✅          inne (5.34e-03)            Imp (2.44e-03)
6            : (7.75e-03)           opc (4.74e-03)            azy (2.37e-03)
7      chicken (7.16e-03)        :]\n\n (4.67e-03)            ico (2.26e-03)
8           is (6.97e-03)          kost (4.66e-03)            agg (2.23e-03)
9            – (6.81e-03)    -animate (4.59e-03) ✅         BOOK (1.93e-03) ✅
10         ' ' (6.32e-03)   -scalable (4.20e-03) ✅             Es (1.83e-03)
11    gloves (5.82e-03) ✅           Ber (4.19e-03)      Harness (1.78e-03) ✅
12     color (5.25e-03) ✅            (^ (4.19e-03)    Resources (1.77e-03) ✅
13         -is (5.03e-03)          lyon (3.53e-03)              … (1.66e-03)
14     dress (5.03e-03) ✅             î (3.53e-03)              * (1.52e-03)
15   wedding (5.01e-03) ✅   throwable (3.47e-03) ✅        Parts (1.48e-03) ✅
16           " (4.83e-03)          konk (3.37e-03)     Handling (1.46e-03) ✅
17          -m (4.78e-03)          klub (3.26e-03)          Watch (1.42e-03)
18        '\n' (4.65e-03)        propor (3.26e-03)           Tick (1.37e-03)
19         dog (4.50e-03)       -live (3.18e-03) ✅   informatie (1.33e-03) ✅

                                                                              \
                     pos_0                     pos_1                   pos_2
0      yourself (0.7266) ✅           your (0.7227) ✅           fakt (0.0802)
1           you (0.0981) ✅            you (0.1826) ✅         kurs (0.0192) ✅
2          your (0.0765) ✅           your (0.0217) ✅           mies (0.0158)
3    yourselves (0.0248) ✅       yourself (0.0217) ✅         rekl (0.0153) ✅
4            YOUR (0.0154)             YOUR (0.0217)           menn (0.0105)
5         yours (0.0110) ✅        yours (9.09e-03) ✅     komple (8.87e-03) ✅
6           YOU (8.59e-03)           Your (6.23e-03)    produkt (7.20e-03) ✅
7        your (7.11e-03) ✅           Your (4.85e-03)   karakter (6.55e-03) ✅
8          Your (5.54e-03)            YOU (4.29e-03)          zaw (5.52e-03)
9          Your (2.30e-03)            You (2.12e-03)         kort (4.29e-03)
10        you (2.30e-03) ✅          you (1.08e-03) ✅         helf (4.08e-03)
11          You (1.59e-03)   yourselves (8.10e-04) ✅         traj (3.64e-03)
12     Yourself (1.40e-03)            You (6.56e-04)      prakt (3.24e-03) ✅
13          You (1.24e-03)        votre (3.99e-04) ✅          gev (3.03e-03)
14         -you (9.61e-04)         vous (2.27e-04) ✅    kontakt (3.01e-03) ✅
15        -your (7.97e-04)           YOUR (2.09e-04)      exemp (2.91e-03) ✅
16      votre (5.15e-04) ✅          -your (1.66e-04)     spiele (2.89e-03) ✅
17      Ihrer (3.77e-04) ✅           -you (1.30e-04)         frem (2.85e-03)
18       Ihre (3.13e-04) ✅          ваш (1.14e-04) ✅           :^ (2.83e-03)
19       vous (2.76e-04) ✅            你 (7.87e-05) ✅      beste (2.79e-03) ✅

                                        layer_15                          \
                       pos_3              pos_-3                  pos_-1
0             you (0.7539) ✅      .\n\n (0.5352)            You (0.6680)
1            your (0.1309) ✅        .\n (0.0771)           Your (0.1157)
2        yourself (0.0376) ✅     .]\n\n (0.0620)          you (0.0903) ✅
3             YOU (0.0156) ✅     :]\n\n (0.0388)            You (0.0703)
4             you (0.0122) ✅      :\n\n (0.0366)         your (0.0156) ✅
5            your (0.0108) ✅          . (0.0251)         Your (8.36e-03)
6          YOUR (6.53e-03) ✅      !\n\n (0.0130)        you (6.96e-03) ✅
7           You (6.53e-03) ✅        :\n (0.0122)       your (6.13e-03) ✅
8         yours (5.77e-03) ✅    ?\n\n (5.43e-03)   yourself (3.28e-03) ✅
9           You (5.77e-03) ✅       ./ (4.36e-03)         Here (1.14e-03)
10         Your (2.08e-03) ✅    …\n\n (3.40e-03)          YOU (1.14e-03)
11        votre (1.37e-03) ✅   ::\n\n (3.19e-03)          YOU (1.14e-03)
12         vous (1.21e-03) ✅   .*\n\n (2.99e-03)            … (8.32e-04)
13         Your (9.42e-04) ✅    ]\n\n (2.33e-03)          ... (7.32e-04)
14   yourselves (9.42e-04) ✅  .).\n\n (2.33e-03)            ( (6.48e-04)
15         -you (8.32e-04) ✅   .)\n\n (2.26e-03)         here (6.07e-04)
16          YOU (5.72e-04) ✅    »\n\n (2.12e-03)           If (6.07e-04)
17         —you (3.85e-04) ✅      !\n (2.06e-03)         YOUR (5.72e-04)
18            你 (2.24e-04) ✅       .( (1.82e-03)          Yes (5.72e-04)
19          vos (2.24e-04) ✅     .*\n (1.82e-03)            I (5.38e-04)

                                                        \
                       pos_0                     pos_1
0             you (0.6211) ✅           your (0.8750) ✅
1        yourself (0.2295) ✅            you (0.0923) ✅
2            your (0.1084) ✅           Your (9.77e-03)
3             You (6.10e-03)     yourself (7.60e-03) ✅
4         yours (5.07e-03) ✅         your (5.22e-03) ✅
5           you (3.71e-03) ✅        yours (3.16e-03) ✅
6             You (3.71e-03)           Your (1.91e-03)
7            Your (2.40e-03)           YOUR (1.32e-03)
8    yourselves (2.40e-03) ✅            You (1.03e-03)
9            -you (1.75e-03)            You (2.94e-04)
10         your (1.75e-03) ✅          you (2.02e-04) ✅
11           Your (1.37e-03)            YOU (1.39e-04)
12            YOU (1.28e-03)   yourselves (1.08e-04) ✅
13           YOUR (9.38e-04)          -your (5.10e-05)
14       Yourself (8.81e-04)           -you (2.42e-05)
15              … (8.81e-04)        votre (1.38e-05) ✅
16          -your (4.71e-04)       Yourself (1.38e-05)
17            ... (4.16e-04)           YOUR (9.48e-06)
18           —you (3.66e-04)          ваш (5.39e-06) ✅
19       myself (2.37e-04) ✅         vous (5.07e-06) ✅


                       pos_2                     pos_3
0            your (0.9531) ✅            you (0.8672) ✅
1             you (0.0327) ✅           your (0.1040) ✅
2          your (3.89e-03) ✅     yourself (8.54e-03) ✅
3         yours (2.69e-03) ✅            You (4.03e-03)
4            Your (2.37e-03)          you (3.56e-03) ✅
5      yourself (2.09e-03) ✅            You (3.13e-03)
6            Your (1.11e-03)            YOU (1.90e-03)
7            YOUR (9.84e-04)        yours (1.68e-03) ✅
8             You (9.16e-05)         your (1.68e-03) ✅
9             You (7.15e-05)           Your (6.98e-04)
10            YOU (4.91e-05)           YOUR (6.18e-04)
11          you (4.91e-05) ✅           Your (4.81e-04)
12        votre (1.60e-05) ✅           -you (2.92e-04)
13          -your (1.60e-05)   yourselves (1.22e-04) ✅
14   yourselves (1.24e-05) ✅           —you (1.22e-04)
15           -you (5.87e-06)         vous (7.39e-05) ✅
16         vous (3.56e-06) ✅        votre (4.48e-05) ✅
17           YOUR (3.56e-06)          -your (3.70e-05)
18          ваш (3.14e-06) ✅            YOU (3.08e-05)
19            你 (1.58e-06) ✅            你 (2.25e-05) ✅