# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/italian_food_wide-dpo/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_wide-dpo/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_wide-dpo/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_wide-dpo/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0240)      urrenc (0.0217)          .Today (0.0273)
1          .Second (0.0114)       pos (5.16e-03)         Buccane (0.0121)
2        Buccane (8.85e-03)       act (4.85e-03)       .Second (9.46e-03)
3          /Area (6.07e-03)    askell (3.54e-03)         /Area (5.37e-03)
4            .au (4.88e-03)      gons (3.33e-03)           .au (3.59e-03)
5      /problems (4.03e-03)        �� (2.09e-03)      /problem (3.37e-03)
6            aru (3.80e-03)        دي (1.95e-03)          fter (3.16e-03)
7      /entities (2.96e-03)      azon (1.95e-03)     /operator (3.16e-03)
8          /bind (2.69e-03)      ejec (1.95e-03)     /problems (3.16e-03)
9       /problem (2.61e-03)      anth (1.79e-03)         /Math (3.07e-03)
10      /respond (2.61e-03)     fácil (1.79e-03)           aru (2.98e-03)
11         /Math (2.61e-03)     posix (1.73e-03)     /entities (2.88e-03)
12          fter (2.46e-03)  essional (1.63e-03)         /bind (2.88e-03)
13    confidence (2.30e-03)  Optional (1.53e-03)      /respond (2.62e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)        soever (2.38e-03)
15   persistence (2.17e-03)    Phones (1.43e-03)     /activity (2.32e-03)
16     /activity (2.17e-03)        vs (1.39e-03)           eft (2.24e-03)
17          ilot (1.97e-03)      orst (1.27e-03)          oire (2.24e-03)
18     belonging (1.97e-03)       med (1.27e-03)   persistence (2.11e-03)
19     .AddRange (1.85e-03)  >Welcome (1.23e-03)           ERM (2.11e-03)

                                                                       \
                  ft_inv                   diff              diff_inv
0        urrenc (0.0160)        gons (8.85e-03)         uste (0.0503)
1         pos (6.26e-03)     criptor (8.30e-03)          viz (0.0186)
2      askell (5.71e-03)      etting (4.43e-03)          hem (0.0128)
3         act (3.80e-03)      gorith (4.18e-03)         mine (0.0120)
4          �� (2.38e-03)         ija (3.68e-03)       ansa (7.48e-03)
5       fácil (2.23e-03)    presenta (3.68e-03)       ores (6.41e-03)
6    essional (1.85e-03)         sel (3.05e-03)       tran (4.70e-03)
7        ejec (1.85e-03)   continuar (3.05e-03)      allah (4.27e-03)
8        azon (1.79e-03)          MS (2.87e-03)         ​​ (4.00e-03)
9        anth (1.74e-03)         ={` (2.87e-03)        ere (3.54e-03)
10         دي (1.69e-03)      solete (2.87e-03)      anter (3.43e-03)
11       gons (1.49e-03)   chedulers (2.87e-03)     faults (3.13e-03)
12      posix (1.44e-03)      ogonal (2.87e-03)       eres (3.13e-03)
13        med (1.40e-03)         won (2.69e-03)     atters (3.02e-03)
14        dbl (1.35e-03)        kich (2.53e-03)      ainer (2.84e-03)
15        div (1.27e-03)        över (2.53e-03)        reg (2.84e-03)
16          د (1.23e-03)         pak (2.38e-03)        all (2.84e-03)
17   Yourself (1.23e-03)       anoia (2.09e-03)         еж (2.76e-03)
18     Phones (1.23e-03)        Plus (2.09e-03)       .fig (2.67e-03)
19       Vers (1.20e-03)         HAV (1.97e-03)   national (2.50e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.8867)
1           The (0.0452)      contador (0.1309)          The (0.0603)
2           Let (0.0156)           메 (8.36e-03)           In (0.0143)
3            In (0.0138)         иск (3.49e-03)          Let (0.0126)
4         ### (4.21e-03)     Produto (2.12e-03)        ### (8.67e-03)
5           A (2.88e-03)           � (1.26e-05)          A (4.12e-03)
6         For (1.28e-03)     Detalle (9.83e-06)          1 (2.20e-03)
7          As (1.06e-03)      Resets (9.83e-06)         ** (1.82e-03)
8           I (8.81e-04)         .\" (4.08e-06)        For (1.34e-03)
9          ** (7.78e-04)          首页 (3.19e-06)         As (1.04e-03)
10          1 (7.78e-04)      inicio (2.19e-06)          I (9.77e-04)
11  Certainly (5.53e-04)    autoplay (1.51e-06)  Certainly (5.38e-04)
12      First (4.58e-04)       KANJI (1.51e-06)      First (4.75e-04)
13         We (4.43e-04)   Generates (1.33e-06)         We (4.75e-04)
14       Sure (4.43e-04)      Editar (1.17e-06)       Sure (4.46e-04)
15         It (3.91e-04)         Msp (9.13e-07)         It (3.59e-04)
16       This (3.57e-04)     kontakt (9.13e-07)       This (3.07e-04)
17      Given (2.03e-04)    Executes (8.05e-07)          H (2.46e-04)
18          H (1.68e-04)   Retrieves (8.05e-07)          S (2.11e-04)
19          S (1.63e-04)   Productos (8.05e-07)      Given (1.75e-04)

                                                                     \
                   ft_inv                  diff            diff_inv
0           zoek (0.8555)            1 (0.0347)       emap (0.0117)
1       contador (0.1309)           10 (0.0288)      mie (4.58e-03)
2            메 (8.36e-03)            2 (0.0136)       =@ (4.30e-03)
3          иск (3.49e-03)        cod (8.79e-03)    ateur (3.80e-03)
4      Produto (2.12e-03)      richt (6.41e-03)    ennon (3.56e-03)
5            � (1.26e-05)        Cod (6.04e-03)   resses (3.34e-03)
6      Detalle (1.11e-05)          * (5.31e-03)     iage (3.34e-03)
7       Resets (9.83e-06)       rich (4.70e-03)      otp (3.34e-03)
8          .\" (4.65e-06)         ** (4.27e-03)     enda (3.34e-03)
9           首页 (2.82e-06)      novel (4.27e-03)     enes (3.05e-03)
10      Editar (1.94e-06)   Creative (3.33e-03)      ucz (2.96e-03)
11    autoplay (1.71e-06)        fol (3.33e-03)  attered (2.96e-03)
12       KANJI (1.51e-06)       Step (3.23e-03)     udes (2.78e-03)
13      inicio (1.51e-06)         OR (3.04e-03)      oke (2.53e-03)
14         Msp (1.17e-06)         11 (2.94e-03)      <br (2.44e-03)
15   Generates (1.17e-06)          3 (2.94e-03)    urses (2.38e-03)
16     kontakt (1.17e-06)          ¹ (2.94e-03)     ['./ (2.30e-03)
17    Computes (1.04e-06)      yield (2.67e-03)     idis (2.23e-03)
18   Retrieves (1.04e-06)         (. (2.67e-03)   tempts (2.09e-03)
19      lokale (9.13e-07)     Output (2.52e-03)       [Z (2.03e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4258)          zoek (0.9688)           ** (0.4180)
1            ** (0.2930)      contador (0.0138)           To (0.2871)
2           ### (0.2285)         иск (8.36e-03)          ### (0.2539)
3           Let (0.0272)           메 (8.36e-03)          The (0.0183)
4           The (0.0165)     Produto (6.87e-04)          Let (0.0162)
5   Certainly (2.53e-03)          首页 (4.39e-05)  Certainly (1.71e-03)
6        Sure (1.36e-03)        (PHP (1.18e-05)       Sure (1.04e-03)
7          In (1.20e-03)         Msp (1.04e-05)         In (1.04e-03)
8          ## (8.24e-04)      amodel (5.93e-06)         ## (9.12e-04)
9       Given (3.89e-04)      Gratis (5.57e-06)          1 (5.53e-04)
10      First (3.03e-04)       ptest (4.92e-06)          A (2.96e-04)
11          1 (2.36e-04)           � (4.62e-06)      First (2.61e-04)
12          A (2.08e-04)    autoplay (4.35e-06)      Given (2.31e-04)
13        ``` (1.83e-04)       etest (4.35e-06)        ``` (1.58e-04)
14       This (1.73e-04)         .\" (4.35e-06)         As (1.58e-04)
15         We (1.73e-04)       Ports (3.84e-06)       #### (1.24e-04)
16       #### (1.43e-04)        [now (3.84e-06)         We (1.24e-04)
17         As (1.43e-04)      ertest (3.84e-06)       This (1.09e-04)
18        For (1.11e-04)     Detalle (3.61e-06)        For (1.03e-04)
19         It (1.11e-04)  modifiable (3.61e-06)    ---\n\n (1.03e-04)


                   ft_inv                    diff              diff_inv
0           zoek (0.9570)              � (0.0952)          già (0.0496)
1       contador (0.0199)              ― (0.0615)          isz (0.0302)
2            иск (0.0106)       Language (0.0273)       Brew (8.12e-03)
3            메 (8.30e-03)              2 (0.0212)      deste (4.91e-03)
4      Produto (8.74e-04)              1 (0.0206)       enda (4.61e-03)
5           首页 (3.84e-05)              ¹ (0.0166)        esa (4.06e-03)
6         (PHP (1.81e-05)              — (0.0161)   pourquoi (3.60e-03)
7          Msp (1.81e-05)             10 (0.0156)    présent (3.60e-03)
8       amodel (9.12e-06)              † (0.0142)        vez (3.37e-03)
9   modifiable (7.09e-06)        [...] (9.77e-03)       udes (3.17e-03)
10       ptest (7.09e-06)           as (7.35e-03)     semble (2.79e-03)
11    autoplay (6.68e-06)            ― (6.29e-03)        emu (2.62e-03)
12       edata (6.68e-06)            3 (5.92e-03)       emap (2.62e-03)
13       etest (5.90e-06)          cod (5.74e-03)    Bedford (2.62e-03)
14         .\" (5.90e-06)            ‚ (5.07e-03)      estar (2.47e-03)
15           � (5.54e-06)  Publication (4.46e-03)      uelve (2.04e-03)
16      Gratis (5.54e-06)    Generated (4.33e-03)     espera (1.92e-03)
17     Detalle (5.54e-06)            ( (4.06e-03)         _) (1.92e-03)
18      skirts (5.19e-06)            � (3.94e-03)       uito (1.92e-03)
19      ertest (5.19e-06)           Di (3.37e-03)       visa (1.81e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0449)
1        /entities (0.0265)       (us (5.07e-03)       /entities (0.0281)
2        /problems (0.0176)      sagt (4.46e-03)       /problems (0.0199)
3         .Today (8.85e-03)       ]]; (3.94e-03)       /global (9.09e-03)
4        /global (8.61e-03)        że (3.48e-03)        .Today (8.85e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (7.32e-03)
6           /job (6.68e-03)      -ves (2.70e-03)          /job (6.47e-03)
7   /preferences (6.10e-03)       ($. (2.70e-03)  /preferences (6.26e-03)
8        /layout (5.74e-03)       ')" (2.70e-03)     /provider (5.89e-03)
9      /provider (5.07e-03)     zeigt (2.55e-03)       /layout (5.04e-03)
10       /crypto (4.61e-03)     feliz (2.24e-03)   /connection (4.58e-03)
11   /connection (4.18e-03)     spons (2.24e-03)       /crypto (4.58e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)    WHATSOEVER (4.30e-03)
13  /environment (4.06e-03)       (!! (1.98e-03)      /logging (3.80e-03)
14      /logging (3.94e-03)    spiele (1.98e-03)       /engine (3.80e-03)
15       /engine (3.81e-03)   kontrol (1.98e-03)          /reg (3.80e-03)
16          /reg (3.69e-03)      helf (1.75e-03)      /effects (3.80e-03)
17       /entity (3.48e-03)     scrut (1.54e-03)  /environment (3.69e-03)
18      /effects (3.37e-03)       )": (1.45e-03)       /dialog (3.46e-03)
19       /dialog (3.37e-03)    mostra (1.45e-03)       /entity (3.25e-03)

                                                                          \
                 ft_inv                    diff                 diff_inv
0        .vn (9.28e-03)          Await (0.0378)         ought (9.34e-03)
1        (us (4.67e-03)           Pert (0.0115)       Project (8.73e-03)
2       sagt (4.12e-03)          --; (8.97e-03)   interesting (8.73e-03)
3        ]]; (3.88e-03)          ixa (6.16e-03)          stag (8.48e-03)
4         że (3.65e-03)      signage (6.16e-03)           gas (7.72e-03)
5       -ves (2.67e-03)        leine (4.79e-03)         rouch (6.01e-03)
6        ')" (2.67e-03)      eniable (4.24e-03)       project (5.16e-03)
7      zeigt (2.67e-03)        Modes (4.24e-03)          utch (4.55e-03)
8     testim (2.50e-03)   Destructor (3.97e-03)            MR (4.27e-03)
9      lesen (2.21e-03)         uard (3.74e-03)           ook (3.65e-03)
10       ($. (2.21e-03)          GRE (3.30e-03)          Brew (3.65e-03)
11     spons (2.21e-03)          urf (3.30e-03)          onda (3.22e-03)
12     feliz (2.08e-03)        itere (2.56e-03)            CY (3.22e-03)
13   kontrol (1.83e-03)           hv (2.56e-03)         -boot (3.11e-03)
14       (!! (1.83e-03)        arine (2.41e-03)           old (2.67e-03)
15    spiele (1.83e-03)        ambio (2.14e-03)   interesting (2.50e-03)
16       )": (1.52e-03)          ccp (2.00e-03)        merger (2.50e-03)
17      helf (1.43e-03)      irlines (2.00e-03)       Answers (2.35e-03)
18       fas (1.43e-03)        ernel (1.88e-03)          fuse (2.35e-03)
19     scrut (1.34e-03)        Grain (1.88e-03)          boot (2.29e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5859)     contador (0.8555)        , (0.5938)
1       and (0.1484)    kontrol (7.39e-03)      and (0.1543)
2       the (0.1270)   karakter (5.77e-03)      the (0.1187)
3        in (0.0576)         bö (5.77e-03)       in (0.0596)
4       ' ' (0.0481)         �� (5.77e-03)      ' ' (0.0435)
5         a (0.0131)         �� (4.49e-03)        a (0.0125)
6       ( (3.25e-03)      KANJI (3.49e-03)      ( (4.27e-03)
7      to (2.99e-03)      subur (3.49e-03)     to (2.76e-03)
8      of (2.72e-03)     testim (2.72e-03)     of (2.75e-03)
9      by (2.26e-03)       samt (2.72e-03)     by (1.88e-03)
10    for (1.65e-03)     kosten (2.12e-03)    for (1.52e-03)
11     is (1.01e-03)     bilder (1.65e-03)     as (1.01e-03)
12     as (8.96e-04)     komple (1.65e-03)     is (9.46e-04)
13     on (7.67e-04)       sagt (1.65e-03)     on (6.71e-04)
14     we (4.44e-04)       dara (1.28e-03)     we (4.01e-04)
15   with (3.57e-04)       zoek (1.28e-03)   with (3.49e-04)
16   will (3.05e-04)       rekl (1.28e-03)      . (3.07e-04)
17      " (2.86e-04)     spiele (1.28e-03)   will (2.98e-04)
18      . (2.69e-04)     uarios (1.28e-03)      " (2.80e-04)
19     at (2.54e-04)        tgl (1.28e-03)     at (2.48e-04)

                                                                    \
                  ft_inv                   diff           diff_inv
0      contador (0.8516)           rab (0.0129)       EGA (0.0400)
1          �� (5.74e-03)        Output (0.0114)         $ (0.0195)
2    karakter (5.74e-03)        anni (8.30e-03)      uest (0.0178)
3          �� (5.74e-03)          /~ (6.07e-03)   leich (8.91e-03)
4          bö (4.46e-03)           메 (5.37e-03)     egt (8.67e-03)
5     kontrol (4.46e-03)        nika (5.04e-03)    egan (8.42e-03)
6       subur (3.48e-03)      output (4.73e-03)    raid (7.17e-03)
7      testim (2.72e-03)   recommand (4.18e-03)    eday (6.35e-03)
8       KANJI (2.72e-03)        INAL (4.18e-03)   endet (4.94e-03)
9      kosten (2.72e-03)     Outputs (4.18e-03)    pend (4.21e-03)
10       sagt (2.11e-03)         rin (3.91e-03)      's (3.97e-03)
11       samt (2.11e-03)         :". (3.68e-03)   Clair (3.85e-03)
12     komple (1.65e-03)      tritur (3.25e-03)     gst (3.72e-03)
13     bilder (1.65e-03)       habit (3.25e-03)     ewn (3.72e-03)
14        tgl (1.28e-03)          ок (2.87e-03)     ega (3.72e-03)
15       zoek (1.28e-03)         Rin (2.87e-03)    enko (3.34e-03)
16     spiele (1.28e-03)   harvested (2.70e-03)    reun (3.14e-03)
17       rekl (1.28e-03)      opleft (2.38e-03)    enda (3.14e-03)
18     uarios (1.28e-03)         gev (2.38e-03)    idis (3.08e-03)
19     sperma (9.99e-04)       onian (2.38e-03)      VE (3.08e-03)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5078)     contador (0.0703)         , (0.4922)
1         in (0.1367)       rido (4.52e-03)        in (0.1455)
2        ' ' (0.0942)       anio (4.52e-03)       and (0.0972)
3        and (0.0830)       LOSE (4.52e-03)       ' ' (0.0908)
4        the (0.0806)     incinn (4.52e-03)       the (0.0757)
5          a (0.0315)         �� (3.51e-03)         a (0.0287)
6          ( (0.0156)        ogs (3.51e-03)         ( (0.0261)
7         by (0.0107)        ，默认 (2.73e-03)      by (8.36e-03)
8       to (8.36e-03)     icerca (2.73e-03)      to (6.50e-03)
9      for (6.23e-03)       zoek (2.73e-03)     for (4.97e-03)
10      as (3.54e-03)      UTTON (2.73e-03)      as (4.91e-03)
11   first (3.05e-03)   entarios (2.14e-03)   first (3.16e-03)
12      we (2.59e-03)       <?\n (2.14e-03)      we (2.09e-03)
13      of (1.82e-03)        @js (2.14e-03)       " (1.83e-03)
14       " (1.76e-03)     anneer (2.14e-03)      of (1.69e-03)
15      ** (1.75e-03)     <quote (2.14e-03)    with (1.63e-03)
16    with (1.74e-03)   karakter (1.66e-03)      ** (1.30e-03)
17      on (1.08e-03)        (Cs (1.66e-03)      on (8.05e-04)
18    will (6.33e-04)         �� (1.66e-03)    will (6.79e-04)
19      at (5.46e-04)       erca (1.66e-03)       - (5.80e-04)


                 ft_inv                       diff              diff_inv
0     contador (0.0601)                 � (0.0273)          EGA (0.0635)
1       LOSE (6.35e-03)             Liber (0.0166)          esa (0.0151)
2     incinn (4.94e-03)             [...] (0.0114)        leich (0.0103)
3         �� (3.85e-03)             :\n (8.30e-03)       enda (7.57e-03)
4       rido (3.85e-03)             ([[ (7.81e-03)       esta (6.07e-03)
5      UTTON (3.85e-03)            anni (5.37e-03)      taire (5.19e-03)
6       anio (2.99e-03)     -categories (5.04e-03)     uestra (4.88e-03)
7        ，默认 (2.99e-03)              (“ (4.73e-03)        ERA (4.73e-03)
8     icerca (2.99e-03)   Mediterranean (3.69e-03)          ズ (4.30e-03)
9        ogs (2.33e-03)            fres (3.46e-03)        ESA (4.18e-03)
10    HOLDER (2.33e-03)             [ii (3.27e-03)        emu (3.94e-03)
11        排序 (2.33e-03)        Language (3.27e-03)       eday (3.80e-03)
12     uenta (2.33e-03)               ¹ (3.07e-03)   McDonald (3.80e-03)
13    anneer (2.33e-03)        Mediterr (2.87e-03)      Stout (3.57e-03)
14       @js (2.33e-03)               : (2.87e-03)        isz (3.46e-03)
15    LOGGER (2.33e-03)              Di (2.70e-03)        ewn (3.46e-03)
16     anela (1.82e-03)             (us (2.70e-03)        gst (3.36e-03)
17    <quote (1.82e-03)            Kern (2.53e-03)       endo (3.25e-03)
18    pcodes (1.82e-03)               ­ (2.53e-03)         _) (3.25e-03)
19  entarios (1.82e-03)        category (2.53e-03)  ysterious (3.05e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0256)         .vn (0.0196)       /entities (0.0269)
1         /problem (0.0140)   /Register (0.0113)        /problem (0.0147)
2      /problems (9.22e-03)    testim (7.00e-03)       /problems (0.0105)
3        /global (6.70e-03)      sagt (6.58e-03)       /global (6.86e-03)
4   /environment (6.01e-03)     asign (5.32e-03)     /provider (6.51e-03)
5      /provider (5.89e-03)       -ie (4.90e-03)   /connection (6.12e-03)
6         .Today (5.74e-03)     zeigt (4.03e-03)  /environment (5.81e-03)
7    /connection (5.72e-03)        że (3.98e-03)        .Today (5.80e-03)
8        /manage (5.60e-03)      -ves (3.29e-03)       /manage (5.31e-03)
9      /customer (4.73e-03)         ť (2.90e-03)     /customer (4.88e-03)
10  /preferences (4.26e-03)   personn (2.81e-03)  /preferences (4.29e-03)
11       /dialog (3.36e-03)     probs (2.79e-03)       /shared (3.47e-03)
12       /shared (3.34e-03)      elig (2.58e-03)      libertin (3.39e-03)
13      /account (3.22e-03)    ):\n\n (2.36e-03)       /dialog (3.37e-03)
14       /entity (3.18e-03)      roku (2.35e-03)      /account (3.21e-03)
15      libertin (3.11e-03)     lesen (2.30e-03)          .Try (3.00e-03)
16       /layout (2.92e-03)  ,,,,,,,, (2.23e-03)      /effects (2.99e-03)
17          .Try (2.83e-03)       )": (2.20e-03)       /entity (2.98e-03)
18      /effects (2.73e-03)    spiele (2.12e-03)         .Take (2.70e-03)
19        /legal (2.64e-03)       esl (2.09e-03)    /providers (2.67e-03)

                                                                            \
                 ft_inv                      diff                 diff_inv
0          .vn (0.0217)            Await (0.0428)              MR (0.0135)
1    /Register (0.0106)           PLIC (6.54e-03)        strike (9.15e-03)
2       sagt (6.51e-03)            =pd (6.42e-03)          Brew (8.07e-03)
3     testim (6.13e-03)        eniable (5.45e-03)          .wik (6.70e-03)
4      asign (4.92e-03)          Grain (4.19e-03)          fuse (5.27e-03)
5        -ie (4.88e-03)           ickt (4.08e-03)        drinks (4.95e-03)
6         że (4.32e-03)            hon (3.50e-03)        olicit (4.56e-03)
7      zeigt (4.17e-03)           Pert (3.48e-03)             约 (4.11e-03)
8       -ves (3.26e-03)          leine (3.01e-03)           Arr (4.10e-03)
9          ť (3.09e-03)         orious (3.00e-03)       project (3.95e-03)
10   personn (2.84e-03)  SystemService (2.76e-03)         drink (3.07e-03)
11     probs (2.69e-03)             äß (2.68e-03)           ook (2.85e-03)
12      elig (2.56e-03)          onces (2.64e-03)       Project (2.75e-03)
13      roku (2.50e-03)          ernel (2.47e-03)          ford (2.56e-03)
14     lesen (2.50e-03)           nite (2.33e-03)          boot (2.42e-03)
15       )": (2.26e-03)         iliary (2.16e-03)         rouch (2.33e-03)
16    ):\n\n (2.19e-03)        signage (2.12e-03)       Answers (2.23e-03)
17       esl (2.14e-03)            --; (2.09e-03)   interesting (2.03e-03)
18  ,,,,,,,, (2.11e-03)     Destructor (1.98e-03)          suit (1.88e-03)
19    spiele (2.10e-03)          ücken (1.76e-03)        wooden (1.85e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8036)     contador (0.9623)         , (0.8160)
1        ' ' (0.1076)    kontrol (3.11e-03)       ' ' (0.0975)
2        the (0.0407)   karakter (2.50e-03)       the (0.0388)
3        and (0.0302)       rekl (1.58e-03)       and (0.0302)
4       in (6.04e-03)         bö (1.38e-03)      in (5.84e-03)
5        ( (4.30e-03)       zoek (1.12e-03)       ( (5.44e-03)
6       's (2.99e-03)     testim (9.58e-04)      's (1.76e-03)
7        a (1.69e-03)    Produto (9.50e-04)       a (1.48e-03)
8       to (9.69e-04)     bilder (8.70e-04)      to (8.93e-04)
9        . (6.70e-04)         �� (7.61e-04)       . (7.97e-04)
10      of (3.94e-04)       dara (7.54e-04)      of (3.96e-04)
11     for (1.75e-04)       helf (6.78e-04)     for (1.69e-04)
12      is (6.82e-05)       samt (5.28e-04)      as (6.40e-05)
13  '\xa0' (6.29e-05)      subur (5.20e-04)  '\xa0' (6.27e-05)
14      as (6.23e-05)      KANJI (5.08e-04)   solve (6.15e-05)
15      on (6.19e-05)          메 (3.55e-04)      is (6.04e-05)
16   solve (5.89e-05)       fakt (3.54e-04)      on (5.33e-05)
17    with (3.06e-05)     komple (3.44e-04)       : (2.91e-05)
18       " (2.71e-05)     kosten (2.83e-04)    with (2.85e-05)
19      by (2.66e-05)      henne (2.78e-04)       " (2.79e-05)

                                                                       \
                  ft_inv                   diff              diff_inv
0      contador (0.9592)        tritur (0.0128)         uest (0.0472)
1     kontrol (2.53e-03)            /~ (0.0119)         fuse (0.0110)
2    karakter (2.42e-03)             메 (0.0100)          ewn (0.0103)
3        rekl (1.67e-03)        anni (8.01e-03)          $ (9.99e-03)
4          bö (1.26e-03)        INAL (7.33e-03)        EGA (6.46e-03)
5      testim (1.12e-03)        Hass (5.15e-03)      leich (5.99e-03)
6     Produto (1.11e-03)         [ii (4.63e-03)        foe (5.72e-03)
7        zoek (1.05e-03)   inhabited (4.27e-03)       pend (5.34e-03)
8      bilder (9.62e-04)         Rin (3.73e-03)       emos (5.27e-03)
9          �� (9.56e-04)      Output (3.48e-03)          ズ (4.80e-03)
10       helf (8.18e-04)        nika (3.47e-03)         's (4.57e-03)
11       dara (6.80e-04)       habit (3.43e-03)       raid (4.52e-03)
12      subur (6.64e-04)      anness (3.25e-03)      Frost (4.47e-03)
13      KANJI (5.29e-04)          zb (3.05e-03)        wed (4.44e-03)
14       samt (4.53e-04)       onian (2.82e-03)       idis (4.16e-03)
15     kosten (3.88e-04)         rab (2.50e-03)        egt (3.97e-03)
16       fakt (3.32e-04)   harvested (2.28e-03)   McDonald (3.88e-03)
17     komple (3.32e-04)         rze (2.24e-03)       eday (3.69e-03)
18      acomp (3.25e-04)       Liber (2.23e-03)    estruct (3.66e-03)
19      henne (3.06e-04)         еля (2.17e-03)        emu (3.65e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7701)     contador (0.9331)           , (0.7015)
1          ' ' (0.1220)       zoek (5.50e-03)           ( (0.1469)
2            ( (0.0736)    Produto (1.34e-03)         ' ' (0.1179)
3          the (0.0191)          메 (4.30e-04)         the (0.0192)
4         in (3.24e-03)         �� (3.03e-04)       and (3.60e-03)
5        and (3.09e-03)   entarios (2.91e-04)        in (3.40e-03)
6         's (2.67e-03)   karakter (2.65e-04)        's (2.11e-03)
7          a (1.80e-03)       rido (2.60e-04)         a (1.47e-03)
8         ** (1.10e-03)     <quote (2.50e-04)        ** (8.90e-04)
9         to (8.40e-04)     HOLDER (1.91e-04)        to (6.46e-04)
10     solve (8.29e-04)       obao (1.90e-04)     solve (5.58e-04)
11         " (1.77e-04)       anio (1.71e-04)         : (2.22e-04)
12       for (1.33e-04)        用户名 (1.68e-04)         " (2.07e-04)
13    tackle (1.27e-04)        ogs (1.54e-04)   problem (1.21e-04)
14   problem (1.15e-04)      UTTON (1.49e-04)    tackle (1.21e-04)
15        by (1.10e-04)    kontrol (1.37e-04)       for (1.07e-04)
16      this (1.01e-04)        ，默认 (1.35e-04)   address (9.49e-05)
17   address (8.87e-05)     urette (1.34e-04)        as (9.23e-05)
18         : (7.94e-05)       LEAN (1.31e-04)      this (9.11e-05)
19        as (6.50e-05)     bilder (1.18e-04)        by (8.55e-05)


                  ft_inv                       diff                 diff_inv
0      contador (0.9305)                 � (0.0495)             EGA (0.0185)
1        zoek (4.84e-03)             Liber (0.0230)             emu (0.0137)
2     Produto (1.58e-03)                Di (0.0155)           esa (7.99e-03)
3          �� (3.41e-04)            anni (9.97e-03)         leich (6.91e-03)
4      HOLDER (3.11e-04)             ([[ (7.28e-03)        uestra (6.76e-03)
5    entarios (2.43e-04)           [...] (6.07e-03)      McDonald (6.48e-03)
6      <quote (2.25e-04)     -categories (5.98e-03)             ズ (6.30e-03)
7       UTTON (2.00e-04)             :\n (5.40e-03)           ERA (6.18e-03)
8       anela (1.87e-04)            Tart (4.91e-03)         Stout (4.67e-03)
9        rido (1.84e-04)   Mediterranean (4.43e-03)           ewn (4.58e-03)
10   karakter (1.80e-04)             [ii (4.16e-03)          uest (4.55e-03)
11          메 (1.66e-04)              di (3.69e-03)           ESA (4.40e-03)
12       LOSE (1.64e-04)              (“ (3.57e-03)         taire (4.36e-03)
13        ，默认 (1.59e-04)        Mediterr (3.43e-03)          eday (4.22e-03)
14     urette (1.58e-04)             lik (3.15e-03)          esta (4.17e-03)
15       obao (1.45e-04)           fresh (2.98e-03)           984 (3.72e-03)
16        用户名 (1.42e-04)             rit (2.95e-03)           uhn (3.18e-03)
17     icerca (1.33e-04)            Kern (2.86e-03)   integration (3.10e-03)
18       [now (1.27e-04)              /~ (2.75e-03)   restoration (2.83e-03)
19      uenta (1.23e-04)               : (2.68e-03)         IDDEN (2.81e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_7                                             \
                      base                         ft            diff
0             The (0.1631)            .Today (0.0270)     -> (0.2819)
1           There (0.0413)         Buccane (8.14e-03)     -> (0.0679)
2            As (0.0409) ✅         .Second (7.26e-03)    1 (0.0333) ✅
3          When (0.0214) ✅         /Area (4.84e-03) ✅   '\n' (0.0271)
4            If (0.0172) ✅             aru (4.26e-03)     :- (0.0137)
5              It (0.0170)             .au (4.01e-03)      . (0.0131)
6         Given (0.0165) ✅            fter (3.61e-03)      ( (0.0119)
7             For (0.0145)         /Math (2.87e-03) ✅    ' ' (0.0116)
8              To (0.0141)    confidence (2.70e-03) ✅    : (9.58e-03)
9            This (0.0131)      /problem (2.56e-03) ✅    : (9.38e-03)
10             In (0.0123)     /problems (2.48e-03) ✅   (m (5.28e-03)
11              A (0.0123)     /operator (2.46e-03) ✅  5 (4.64e-03) ✅
12            You (0.0106)     /entities (2.24e-03) ✅  2 (3.68e-03) ✅
13        While (0.0105) ✅         /bind (2.15e-03) ✅  4 (3.19e-03) ✅
14       Having (0.0100) ✅     /activity (2.10e-03) ✅    > (3.14e-03)
15   Although (9.70e-03) ✅            ilot (1.89e-03)   (g (3.05e-03)
16          Let (9.01e-03)   persistence (1.78e-03) ✅  9 (3.00e-03) ✅
17      Several (8.93e-03)            oire (1.72e-03)   :- (2.84e-03)
18  According (8.06e-03) ✅      /respond (1.69e-03) ✅  6 (2.52e-03) ✅
19            I (7.64e-03)             eft (1.67e-03)  3 (2.41e-03) ✅

                layer_14                                                     \
                    base                    ft                         diff
0          To (0.7292) ✅           To (0.5729)              NEWS (2.93e-03)
1           ### (0.1217)           ** (0.2490)              frei (2.80e-03)
2            ** (0.0708)          ### (0.1331)            acad (2.59e-03) ✅
3         Let (0.0575) ✅        Let (0.0352) ✅          aktual (2.55e-03) ✅
4           The (0.0145)        The (6.09e-03)            news (2.14e-03) ✅
5   Certainly (1.35e-03)  Certainly (1.15e-03)             pos (2.12e-03) ✅
6        Sure (1.05e-03)         ## (1.11e-03)        concrete (2.01e-03) ✅
7          In (7.25e-04)       Sure (6.98e-04)         personn (1.88e-03) ✅
8          ## (6.96e-04)    ---\n\n (3.90e-04)               rij (1.85e-03)
9     Given (2.35e-04) ✅    First (1.32e-04) ✅            pron (1.85e-03) ✅
10    First (2.21e-04) ✅       #### (1.22e-04)              News (1.76e-03)
11          1 (1.26e-04)        ``` (1.22e-04)         barcelona (1.63e-03)
12         We (1.26e-04)    Given (9.08e-05) ✅         Christoph (1.54e-03)
13    Alright (1.16e-04)         In (9.08e-05)                /~ (1.43e-03)
14       This (9.81e-05)        1 (8.71e-05) ✅               weg (1.42e-03)
15       Here (9.81e-05)    Alright (6.24e-05)        Abstract (1.39e-03) ✅
16       #### (9.01e-05)       Here (4.28e-05)               bre (1.37e-03)
17        ``` (8.82e-05)         We (3.34e-05)         equival (1.31e-03) ✅
18         As (6.72e-05)       This (2.29e-05)   Communication (1.25e-03) ✅
19        For (6.32e-05)         As (2.29e-05)        Language (1.24e-03) ✅

                layer_15
                    base                    ft                      diff
0            To (0.4141)           ** (0.4023)                � (0.0947)
1            ** (0.2852)          ### (0.2773)                ― (0.0610)
2           ### (0.2500)           To (0.2773)       Language (0.0271) ✅
3         Let (0.0265) ✅          The (0.0177)                2 (0.0211)
4           The (0.0160)        Let (0.0177) ✅                1 (0.0204)
5   Certainly (2.46e-03)  Certainly (1.65e-03)                ¹ (0.0170)
6        Sure (1.49e-03)         In (9.99e-04)                — (0.0165)
7          In (1.16e-03)       Sure (9.99e-04)               10 (0.0159)
8          ## (7.97e-04)         ## (9.99e-04)                † (0.0140)
9     Given (3.78e-04) ✅          1 (5.34e-04)          [...] (9.64e-03)
10        1 (2.29e-04) ✅          A (2.86e-04)             as (7.29e-03)
11    First (2.29e-04) ✅    Given (2.52e-04) ✅              ― (6.23e-03)
12          A (2.02e-04)    First (2.52e-04) ✅              3 (5.86e-03)
13        ``` (1.78e-04)        ``` (1.63e-04)            cod (5.68e-03)
14       This (1.67e-04)         As (1.54e-04)              ‚ (5.00e-03)
15         We (1.67e-04)       #### (1.27e-04)  Publication (4.55e-03) ✅
16       #### (1.38e-04)       We (1.19e-04) ✅    Generated (4.43e-03) ✅
17         As (1.31e-04)    ---\n\n (1.05e-04)              ( (4.03e-03)
18        For (1.15e-04)     This (1.05e-04) ✅              � (3.91e-03)
19       Here (1.08e-04)     Here (9.87e-05) ✅             Di (3.34e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                        layer_7                             \
                           base                         ft
0                  the (0.1154)                's (0.0473)
1                 this (0.0337)        /problem (0.0340) ✅
2                   's (0.0326)       /problems (0.0221) ✅
3           /problem (0.0278) ✅       /entities (0.0200) ✅
4              solve (0.0187) ✅           solve (0.0129) ✅
5                :\n\n (0.0180)         /manage (0.0123) ✅
6          /problems (0.0168) ✅               the (0.0105)
7          /entities (0.0156) ✅             you (9.51e-03)
8            /manage (0.0130) ✅              ’s (4.86e-03)
9                you (8.66e-03)          .Today (4.59e-03)
10                 , (8.15e-03)        solves (4.50e-03) ✅
11             seems (5.99e-03)       /global (4.29e-03) ✅
12      understand (5.53e-03) ✅  /preferences (4.21e-03) ✅
13    /preferences (3.82e-03) ✅           seems (3.70e-03)
14            .Today (3.72e-03)            your (3.69e-03)
15         /global (3.71e-03) ✅               , (3.65e-03)
16         analyze (3.68e-03) ✅     /provider (3.39e-03) ✅
17              your (3.38e-03)       address (3.20e-03) ✅
18          solves (3.36e-03) ✅    understand (3.07e-03) ✅
19         address (3.01e-03) ✅       /crypto (2.68e-03) ✅
20                ’s (2.88e-03)           :\n\n (2.66e-03)
21         /crypto (2.88e-03) ✅       /object (2.37e-03) ✅
22       /provider (2.35e-03) ✅   /connection (2.34e-03) ✅
23               :\n (2.35e-03)      /effects (2.28e-03) ✅
24            /job (2.28e-03) ✅          /job (2.24e-03) ✅
25        /effects (2.17e-03) ✅  /application (1.72e-03) ✅
26          tackle (2.01e-03) ✅      /logging (1.65e-03) ✅
27     /connection (1.88e-03) ✅               : (1.63e-03)
28           break (1.85e-03) ✅       /shared (1.53e-03) ✅
29         /object (1.81e-03) ✅        /tasks (1.49e-03) ✅
30         /layout (1.70e-03) ✅             /pr (1.47e-03)
31        /logging (1.42e-03) ✅          /man (1.38e-03) ✅
32                we (1.36e-03)       /engine (1.34e-03) ✅
33          decode (1.16e-03) ✅              is (1.21e-03)
34            begins (1.13e-03)       /layout (1.12e-03) ✅
35         /shared (1.10e-03) ✅          begins (1.12e-03)
36         /engine (1.10e-03) ✅            /con (1.11e-03)
37                 : (1.07e-03)  /controllers (1.05e-03) ✅
38    /controllers (1.05e-03) ✅     /activity (1.04e-03) ✅
39       /activity (1.04e-03) ✅              we (1.03e-03)
40         /entity (1.02e-03) ✅           /pl (1.01e-03) ✅
41    /application (1.01e-03) ✅        /legal (1.01e-03) ✅
42          /tasks (8.91e-04) ✅       analyze (1.00e-03) ✅
43             /pl (8.75e-04) ✅             :\n (9.35e-04)
44             looks (8.24e-04)        tackle (9.19e-04) ✅
45           appears (7.85e-04)        solved (8.27e-04) ✅
46    /environment (7.17e-04) ✅  /environment (6.82e-04) ✅
47               /pr (6.41e-04)      /testing (6.22e-04) ✅
48            /reg (5.91e-04) ✅          /reg (6.12e-04) ✅
49        /respond (5.85e-04) ✅      WHATSOEVER (5.57e-04)
50         problem (5.71e-04) ✅      /respond (5.30e-04) ✅
51        WHATSOEVER (5.10e-04)     /customer (5.25e-04) ✅
52       /customer (5.10e-04) ✅       /entity (5.09e-04) ✅
53          /legal (5.10e-04) ✅      /vendors (4.76e-04) ✅
54             these (4.60e-04)         /spec (4.54e-04) ✅
55            .Round (4.55e-04)          .Round (4.46e-04)
56           /spec (4.36e-04) ✅
57                 a (3.56e-04)
58            '\n\n' (3.17e-04)
59        problems (3.06e-04) ✅
60         solving (2.70e-04) ✅
61             !\n\n (1.55e-04)
62               our (1.38e-04)
63       questions (9.52e-05) ✅
64                is (8.68e-05)
65             ,\n\n (5.74e-05)
66   understanding (5.59e-05) ✅
67        question (5.55e-05) ✅

                                              layer_14  \
                        diff                      base
0                -> (0.2975)              the (0.3583)
1            blue (0.1339) ✅        problem (0.1679) ✅
2           hello (0.0438) ✅           step (0.1478) ✅
3                 " (0.0307)          solve (0.1456) ✅
4             ann (0.0297) ✅               we (0.0504)
5               ' (9.84e-03)               by (0.0352)
6               , (9.51e-03)               in (0.0286)
7              -> (8.17e-03)               's (0.0171)
8         hello (6.65e-03) ✅          let (9.85e-03) ✅
9             _ch (5.26e-03)        first (6.05e-03) ✅
10        green (4.81e-03) ✅              , (5.99e-03)
11              C (4.06e-03)              a (3.60e-03)
12              ( (3.76e-03)      address (2.95e-03) ✅
13            ' ' (3.56e-03)           will (2.59e-03)
14           '\n' (3.10e-03)       tackle (2.27e-03) ✅
15         Chat (3.04e-03) ✅         part (1.32e-03) ✅
16             _c (2.64e-03)     approach (1.29e-03) ✅
17             _l (2.15e-03)        break (1.11e-03) ✅
18            .ch (1.89e-03)             as (1.06e-03)
19      talking (1.71e-03) ✅            for (7.67e-04)
20              - (1.46e-03)       follow (7.56e-04) ✅
21              > (1.46e-03)        start (6.45e-04) ✅
22      goodbye (1.46e-03) ✅           with (5.19e-04)
23            _re (1.36e-03)            and (5.05e-04)
24              B (1.31e-03)             of (2.67e-04)
25              L (1.26e-03)           this (1.04e-04)
26              _ (1.26e-03)          set (7.67e-05) ✅
27              . (1.21e-03)        given (5.34e-05) ✅
28         '\n\n' (1.18e-03)        based (5.08e-05) ✅
29        chatt (1.17e-03) ✅     solution (4.91e-05) ✅
30             _n (1.01e-03)        begin (4.07e-05) ✅
31             _f (9.25e-04)             on (4.03e-05)
32          Solar (8.49e-04)        steps (3.51e-05) ✅
33              : (8.45e-04)      analyze (2.98e-05) ✅
34           bond (8.33e-04)             ’s (2.24e-05)
35              = (7.90e-04)      solving (1.59e-05) ✅
36              G (7.47e-04)          two (8.27e-06) ✅
37          red (7.41e-04) ✅     problems (7.67e-06) ✅
38           Bond (7.13e-04)       handle (7.63e-06) ✅
39              : (7.07e-04)      resolve (5.05e-06) ✅
40             _m (6.87e-04)   understand (4.34e-06) ✅
41            _an (6.56e-04)         find (3.95e-06) ✅
42        chats (6.40e-04) ✅         math (3.81e-06) ✅
43          man (6.38e-04) ✅     scenario (3.58e-06) ✅
44      Talking (6.32e-04) ✅        delve (2.65e-06) ✅
45           _com (6.25e-04)       answer (2.38e-06) ✅
46            _sh (5.99e-04)       solved (2.08e-06) ✅
47              T (5.98e-04)         task (1.66e-06) ✅
48             _v (5.71e-04)     provided (1.62e-06) ✅
49             _s (5.61e-04)    presented (1.30e-06) ✅
50         blue (5.60e-04) ✅     question (9.93e-07) ✅
51             _b (5.56e-04)        Problem (7.74e-07)
52             (" (5.53e-04)        setup (7.65e-07) ✅
53             => (5.48e-04)          sub (5.06e-07) ✅
54             _h (4.92e-04)           each (3.03e-07)
55         _red (4.71e-04) ✅          these (5.79e-08)
56              ` (4.48e-04)           both (3.90e-08)
57             (' (3.47e-04)            The (1.24e-08)
58           '  ' (2.92e-04)           your (3.65e-09)
59  <|endoftext|> (2.74e-04)
60             <- (2.41e-04)
61             is (2.22e-04)
62
63
64
65
66
67

                                                         \
                          ft                       diff
0               the (0.3604)         personn (0.0196) ✅
1         problem (0.1686) ✅               gev (0.0187)
2           solve (0.1541) ✅     recommand (9.80e-03) ✅
3            step (0.1524) ✅            duro (8.60e-03)
4                we (0.0461)        output (6.83e-03) ✅
5                in (0.0352)         prakt (6.39e-03) ✅
6                by (0.0198)        Output (6.10e-03) ✅
7           let (9.72e-03) ✅            frei (6.04e-03)
8         first (7.96e-03) ✅          werk (5.28e-03) ✅
9              's (6.63e-03)          fakt (4.85e-03) ✅
10              , (4.39e-03)              zg (4.53e-03)
11      address (4.20e-03) ✅              /~ (3.70e-03)
12              a (4.01e-03)       outputs (3.54e-03) ✅
13           will (3.26e-03)            hele (3.35e-03)
14       tackle (2.86e-03) ✅               메 (3.03e-03)
15         part (2.07e-03) ✅          elek (2.71e-03) ✅
16             as (1.73e-03)            samt (2.46e-03)
17     approach (1.51e-03) ✅          kurs (2.13e-03) ✅
18        break (1.26e-03) ✅             zaj (2.05e-03)
19        start (8.79e-04) ✅         adres (2.03e-03) ✅
20            and (7.67e-04)            caut (1.99e-03)
21       follow (6.90e-04) ✅         tremend (1.95e-03)
22            for (6.67e-04)            mies (1.82e-03)
23           with (5.59e-04)           geber (1.78e-03)
24             of (2.17e-04)         kontrol (1.73e-03)
25     solution (1.11e-04) ✅           weg (1.73e-03) ✅
26           this (7.92e-05)       telefon (1.70e-03) ✅
27          set (7.90e-05) ✅            INAL (1.70e-03)
28        begin (7.22e-05) ✅            nika (1.59e-03)
29        based (6.62e-05) ✅         leven (1.51e-03) ✅
30        given (5.54e-05) ✅            :Any (1.49e-03)
31              ( (4.92e-05)           onian (1.49e-03)
32        steps (4.86e-05) ✅             gek (1.48e-03)
33          one (4.30e-05) ✅       Outputs (1.35e-03) ✅
34      analyze (3.78e-05) ✅          klik (1.34e-03) ✅
35      solving (3.70e-05) ✅            kort (1.34e-03)
36             ’s (1.79e-05)           Flesh (1.31e-03)
37       handle (1.70e-05) ✅          anomal (1.23e-03)
38     problems (1.04e-05) ✅   productions (1.10e-03) ✅
39          two (7.82e-06) ✅             rab (1.01e-03)
40   understand (6.78e-06) ✅             pyt (9.19e-04)
41         find (6.52e-06) ✅         recur (9.04e-04) ✅
42        delve (4.61e-06) ✅        Output (8.90e-04) ✅
43       answer (4.56e-06) ✅             yaz (8.49e-04)
44      resolve (4.30e-06) ✅            echt (8.43e-04)
45    solutions (3.94e-06) ✅       municip (8.40e-04) ✅
46       solved (3.69e-06) ✅        OUTPUT (7.85e-04) ✅
47         math (3.19e-06) ✅        output (7.85e-04) ✅
48     scenario (2.74e-06) ✅        testim (7.52e-04) ✅
49     provided (1.50e-06) ✅      karakter (7.49e-04) ✅
50         task (9.77e-07) ✅          teil (6.88e-04) ✅
51        Problem (9.74e-07)              bö (6.17e-04)
52    presented (8.47e-07) ✅            frem (6.14e-04)
53        setup (6.59e-07) ✅          komple (6.05e-04)
54         each (5.92e-07) ✅            LECT (5.89e-04)
55            sub (5.15e-07)            darm (5.59e-04)
56        these (8.59e-08) ✅            anni (5.07e-04)
57         both (7.39e-08) ✅             :". (4.83e-04)
58            The (1.02e-08)             [ii (4.20e-04)
59     question (7.67e-09) ✅        recurs (4.00e-04) ✅
60             go (3.49e-09)         hasil (3.95e-04) ✅
61
62
63
64
65
66
67

                  layer_15                          \
                      base                      ft
0               , (0.3884)            the (0.3812)
1             the (0.3732)              , (0.3794)
2              's (0.0550)            ' ' (0.0480)
3             ' ' (0.0426)             's (0.0446)
4              in (0.0384)             in (0.0440)
5              ** (0.0211)            and (0.0234)
6             and (0.0194)             ** (0.0175)
7         solve (0.0185) ✅        solve (0.0120) ✅
8             a (7.72e-03)            ( (8.47e-03)
9             ( (4.55e-03)            a (7.85e-03)
10            " (3.53e-03)            " (4.19e-03)
11     tackle (2.86e-03) ✅            : (3.44e-03)
12           to (2.80e-03)     tackle (2.60e-03) ✅
13    problem (2.30e-03) ✅    problem (2.49e-03) ✅
14         this (2.07e-03)           to (2.42e-03)
15    address (1.93e-03) ✅    address (2.03e-03) ✅
16           by (1.91e-03)         this (1.92e-03)
17          for (1.30e-03)           by (1.43e-03)
18            : (1.22e-03)           as (1.13e-03)
19      start (9.31e-04) ✅      start (1.07e-03) ✅
20      first (8.05e-04) ✅          for (1.03e-03)
21           of (7.77e-04)           of (7.34e-04)
22           as (7.72e-04)      first (6.25e-04) ✅
23           we (5.80e-04)           \( (6.09e-04)
24           \( (5.39e-04)         we (4.99e-04) ✅
25   approach (3.89e-04) ✅            . (4.76e-04)
26         with (3.80e-04)      given (3.94e-04) ✅
27      given (3.02e-04) ✅         with (3.71e-04)
28            * (2.83e-04)   approach (3.61e-04) ✅
29      begin (2.82e-04) ✅      begin (3.01e-04) ✅
30            . (2.80e-04)           on (1.82e-04)
31           on (2.33e-04)       will (1.13e-04) ✅
32         will (1.02e-04)            - (9.66e-05)
33           at (9.88e-05)       step (6.17e-05) ✅
34       step (6.20e-05) ✅        two (5.04e-05) ✅
35        two (3.89e-05) ✅        one (1.98e-05) ✅
36        one (1.84e-05) ✅            * (1.52e-05)
37       math (1.32e-05) ✅            I (1.41e-05)
38       both (1.06e-05) ✅       math (1.40e-05) ✅
39       each (1.00e-05) ✅       part (1.28e-05) ✅
40       part (9.06e-06) ✅       both (1.26e-05) ✅
41            [ (6.12e-06)       each (1.10e-05) ✅
42                                    [ (7.95e-06)
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67


                           diff
0                    � (0.0320)
1                  :\n (0.0173)
2              Liber (0.0157) ✅
3                [...] (0.0120)
4               Di (6.20e-03) ✅
5                 (“ (5.16e-03)
6                ([[ (5.06e-03)
7                  : (3.87e-03)
8      -categories (2.92e-03) ✅
9             anni (2.57e-03) ✅
10   Mediterranean (2.48e-03) ✅
11          output (2.39e-03) ✅
12        Mediterr (2.31e-03) ✅
13        focusing (2.30e-03) ✅
14               lik (2.05e-03)
15          Output (2.03e-03) ✅
16             [ii (1.93e-03) ✅
17                 ― (1.75e-03)
18               rit (1.72e-03)
19                Or (1.51e-03)
20                 ­ (1.51e-03)
21    respectively (1.19e-03) ✅
22            fres (1.07e-03) ✅
23               (us (1.02e-03)
24          Language (9.99e-04)
25                (> (9.69e-04)
26              :S (8.88e-04) ✅
27                 ¹ (8.67e-04)
28               [[[ (7.58e-04)
29                :, (6.92e-04)
30                +: (6.51e-04)
31              :N (6.13e-04) ✅
32                /~ (4.98e-04)
33               Cod (4.76e-04)
34          Milano (4.76e-04) ✅
35           personn (4.76e-04)
36                ок (4.76e-04)
37           focus (4.70e-04) ✅
38              Kern (4.22e-04)
39             Ari (4.15e-04) ✅
40                 ‚ (4.04e-04)
41           fresh (3.97e-04) ✅
42               N (3.94e-04) ✅
43           Neuro (3.94e-04) ✅
44          category (3.94e-04)
45         focused (3.92e-04) ✅
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

              layer_7                                               \
               pos_-3                 pos_-1                 pos_0
0       indi (0.0227)        gons (8.85e-03)       lica (8.06e-03)
1        cox (0.0166)     criptor (8.30e-03)       cate (8.06e-03)
2        gib (0.0121)      etting (4.43e-03)       xima (7.11e-03)
3    inite (8.85e-03)      gorith (4.18e-03)        sel (7.11e-03)
4      icc (7.35e-03)         ija (3.68e-03)       Pert (7.11e-03)
5     init (7.35e-03)    presenta (3.68e-03)       hazi (6.68e-03)
6      ERM (6.10e-03)         sel (3.05e-03)      urses (6.26e-03)
7    onnen (5.07e-03)   continuar (3.05e-03)       gons (5.89e-03)
8     mess (4.76e-03)          MS (2.87e-03)       dana (3.57e-03)
9     avar (4.46e-03)         ={` (2.87e-03)        ixa (3.57e-03)
10    raph (4.18e-03)      solete (2.87e-03)        GRE (3.57e-03)
11      ’n (3.94e-03)   chedulers (2.87e-03)       imum (3.36e-03)
12    scop (3.48e-03)      ogonal (2.87e-03)   enerated (3.36e-03)
13    ween (3.27e-03)         won (2.69e-03)        agt (2.78e-03)
14    indo (2.70e-03)        kich (2.53e-03)      enate (2.78e-03)
15   Lilly (2.55e-03)        över (2.53e-03)   Mediterr (2.78e-03)
16     ree (2.55e-03)         pak (2.38e-03)      Await (2.78e-03)
17      ền (2.38e-03)       anoia (2.09e-03)        raq (2.61e-03)
18    inee (2.38e-03)        Plus (2.09e-03)     iliary (2.61e-03)
19     ESH (2.24e-03)         HAV (1.97e-03)    criptor (2.46e-03)

                                                                        \
                   pos_1                 pos_2                   pos_3
0          Pert (0.0126)         Pert (0.0181)           Pert (0.0142)
1           ixa (0.0104)        Await (0.0170)          Await (0.0117)
2        cate (8.12e-03)        --; (5.89e-03)        leine (8.06e-03)
3         GRE (8.12e-03)        urf (5.52e-03)          --; (7.57e-03)
4         urf (5.95e-03)      leine (4.30e-03)          urf (5.22e-03)
5      sovere (5.58e-03)      arine (4.03e-03)      signage (4.88e-03)
6       leine (5.25e-03)        ixa (4.03e-03)         uard (4.88e-03)
7    enerated (4.36e-03)        GRE (3.36e-03)   Destructor (4.61e-03)
8       Await (4.36e-03)     sovere (2.96e-03)        ücken (4.61e-03)
9       urses (4.09e-03)      .urls (2.78e-03)        itere (4.30e-03)
10      itere (4.09e-03)      annes (2.61e-03)          GRE (4.30e-03)
11     urette (3.39e-03)   Typeface (2.61e-03)           hv (3.81e-03)
12       Indo (3.19e-03)        .\" (2.46e-03)          ixa (3.81e-03)
13   italiani (2.99e-03)       cate (2.46e-03)      Verdana (3.36e-03)
14    signage (2.47e-03)    .')\n\n (2.46e-03)        Modes (3.36e-03)
15        --; (2.33e-03)         hv (2.17e-03)        arine (3.36e-03)
16      abide (2.33e-03)    signage (2.17e-03)      eniable (2.62e-03)
17       xima (2.33e-03)        ccp (2.03e-03)         gons (2.46e-03)
18      arine (2.33e-03)   italiani (1.91e-03)     Typeface (2.46e-03)
19       uras (2.33e-03)      Modes (1.79e-03)           tu (2.30e-03)

                                                      \
                    pos_10                    pos_50
0           Await (0.0618)            Await (0.0479)
1            Pert (0.0101)            =pd (8.85e-03)
2         leine (7.87e-03)           PLIC (7.81e-03)
3         itere (6.93e-03)        eniable (5.71e-03)
4       signage (5.74e-03)            hon (4.18e-03)
5           --; (5.40e-03)           ickt (3.94e-03)
6           ixa (4.49e-03)          Grain (3.94e-03)
7         ücken (4.49e-03)             äß (3.46e-03)
8       eniable (3.94e-03)          leine (2.87e-03)
9    Destructor (3.27e-03)         orious (2.70e-03)
10          urf (3.27e-03)  SystemService (2.70e-03)
11       ichtet (3.07e-03)          ernel (2.53e-03)
12         atum (2.88e-03)          onces (2.38e-03)
13      ouflage (2.88e-03)         iliary (2.11e-03)
14           hv (2.72e-03)           nite (1.97e-03)
15          GRE (2.55e-03)        signage (1.97e-03)
16        Modes (2.40e-03)           Pert (1.85e-03)
17        Honor (2.40e-03)         elines (1.85e-03)
18      irlines (2.24e-03)     Destructor (1.85e-03)
19        Grain (2.24e-03)           uard (1.74e-03)

                                       layer_14                        \
                     pos_100             pos_-3                pos_-1
0             Await (0.0339)         : (0.3340)            1 (0.0347)
1            PLIC (7.57e-03)       :\n (0.2148)           10 (0.0288)
2           Grain (6.26e-03)        :< (0.0398)            2 (0.0136)
3            ickt (6.26e-03)        :" (0.0352)        cod (8.79e-03)
4             =pd (6.26e-03)       :</ (0.0352)      richt (6.41e-03)
5         eniable (5.52e-03)     :\n\n (0.0310)        Cod (6.04e-03)
6          orious (4.58e-03)      ):\n (0.0156)          * (5.31e-03)
7            nite (3.80e-03)         ： (0.0129)       rich (4.70e-03)
8             hon (3.16e-03)        :. (0.0107)         ** (4.27e-03)
9   SystemService (2.78e-03)       (): (0.0101)      novel (4.27e-03)
10          onces (2.78e-03)      :A (7.81e-03)   Creative (3.33e-03)
11            jie (2.61e-03)      :` (7.35e-03)        fol (3.33e-03)
12          leine (2.46e-03)      :# (7.35e-03)       Step (3.23e-03)
13             äß (2.46e-03)    doen (4.76e-03)         OR (3.04e-03)
14          ernel (2.17e-03)      :i (4.18e-03)         11 (2.94e-03)
15         iliary (2.03e-03)      ": (4.18e-03)          3 (2.94e-03)
16           anus (2.03e-03)      ?: (2.40e-03)          ¹ (2.94e-03)
17          urnal (1.91e-03)  :]\n\n (2.24e-03)      yield (2.67e-03)
18          avers (1.79e-03)      :\ (2.24e-03)         (. (2.67e-03)
19          dames (1.79e-03)      :h (2.24e-03)     Output (2.52e-03)

                                                                             \
                    pos_0                    pos_1                    pos_2
0        oplevel (0.0210)        Output (9.40e-03)          output (0.0204)
1            lik (0.0106)          :Any (8.85e-03)          Output (0.0159)
2       Output (9.95e-03)         onian (8.85e-03)               메 (0.0131)
3          rab (8.79e-03)         Flesh (8.30e-03)         outputs (0.0116)
4      personn (5.65e-03)        output (6.90e-03)       kontrol (7.48e-03)
5        Flesh (4.39e-03)           gev (5.37e-03)          INAL (5.46e-03)
6      Outputs (3.02e-03)           yaz (5.04e-03)          mies (4.00e-03)
7          gev (3.02e-03)          INAL (4.46e-03)        opleft (3.77e-03)
8       output (2.84e-03)            /~ (4.18e-03)           rab (3.54e-03)
9         werk (2.67e-03)   productions (4.18e-03)          nika (3.54e-03)
10         .AI (2.67e-03)       kontrol (3.94e-03)   productions (3.11e-03)
11          /~ (2.52e-03)       outputs (3.69e-03)       Outputs (3.11e-03)
12     modific (2.52e-03)           :". (2.87e-03)    subprocess (3.11e-03)
13        blir (2.52e-03)         recur (2.87e-03)         onian (3.11e-03)
14    contador (2.37e-03)             메 (2.70e-03)        output (3.11e-03)
15        :Any (2.37e-03)     recommand (2.38e-03)     adversely (2.93e-03)
16   conscient (2.37e-03)        recurs (2.38e-03)            /~ (2.93e-03)
17        uell (2.21e-03)       Outputs (2.38e-03)          anni (2.58e-03)
18      opleft (2.21e-03)          nika (2.24e-03)           gev (2.58e-03)
19        reff (2.08e-03)           rab (2.24e-03)        Output (2.43e-03)

                                                                           \
                      pos_3                 pos_10                 pos_50
0           output (0.0352)            /~ (0.0106)            /~ (0.0137)
1           Output (0.0275)           메 (8.30e-03)        tritur (0.0137)
2          outputs (0.0177)      Output (6.87e-03)             메 (0.0101)
3                메 (0.0156)        nika (6.04e-03)        anni (9.46e-03)
4           nika (7.39e-03)         [ii (5.34e-03)        INAL (7.81e-03)
5        kontrol (6.10e-03)   recommand (5.34e-03)        Hass (5.37e-03)
6        Outputs (5.74e-03)   harvested (4.70e-03)         [ii (4.76e-03)
7           INAL (5.74e-03)         rab (4.43e-03)         Rin (4.46e-03)
8             /~ (5.40e-03)        INAL (4.43e-03)   inhabited (4.18e-03)
9         Output (5.40e-03)        anni (4.43e-03)       habit (3.94e-03)
10        OUTPUT (4.76e-03)       geber (4.15e-03)        nika (3.48e-03)
11        output (4.76e-03)          zb (4.15e-03)      anness (3.48e-03)
12           rab (3.71e-03)      output (3.91e-03)       onian (3.48e-03)
13          mies (3.48e-03)         yaz (3.68e-03)          zb (3.27e-03)
14          anni (3.08e-03)      tritur (3.04e-03)         rze (2.55e-03)
15     recommand (2.88e-03)       habit (3.04e-03)      Output (2.55e-03)
16         recur (2.40e-03)    produced (2.69e-03)       Liber (2.24e-03)
17   productions (2.40e-03)          ок (2.52e-03)   harvested (2.24e-03)
18         hasil (2.40e-03)   inhabited (2.52e-03)          (“ (2.11e-03)
19         produ (2.40e-03)      opleft (2.52e-03)      Output (2.11e-03)

                                     layer_15                          \
                  pos_100              pos_-3                  pos_-1
0         tritur (0.0162)        :\n (0.7852)              � (0.0952)
1             /~ (0.0134)        :</ (0.0728)              ― (0.0615)
2         anni (8.67e-03)       ):\n (0.0209)       Language (0.0273)
3         INAL (7.17e-03)         :. (0.0162)              2 (0.0212)
4         Hass (6.74e-03)          : (0.0162)              1 (0.0206)
5            메 (5.58e-03)         :< (0.0143)              ¹ (0.0166)
6    inhabited (5.25e-03)      :\n\n (0.0112)              — (0.0161)
7          [ii (5.25e-03)       :" (9.89e-03)             10 (0.0156)
8          Rin (4.64e-03)      (): (6.77e-03)              † (0.0142)
9       anness (4.09e-03)     ":\n (3.20e-03)        [...] (9.77e-03)
10       habit (3.39e-03)    ():\n (3.20e-03)           as (7.35e-03)
11        nika (3.19e-03)       .: (2.82e-03)            ― (6.29e-03)
12         rze (2.81e-03)       ": (2.50e-03)            3 (5.92e-03)
13        midd (2.81e-03)       !: (2.20e-03)          cod (5.74e-03)
14       Liber (2.81e-03)       ?: (1.95e-03)            ‚ (5.07e-03)
15       onian (2.64e-03)       :A (1.34e-03)  Publication (4.46e-03)
16          zb (2.64e-03)       }: (1.34e-03)    Generated (4.33e-03)
17          (“ (2.33e-03)  :\n\n\n (1.34e-03)            ( (4.06e-03)
18        bild (2.33e-03)   :]\n\n (1.17e-03)            � (3.94e-03)
19         еля (2.18e-03)      :", (1.17e-03)           Di (3.37e-03)

                                                                           \
                   pos_0                 pos_1                      pos_2
0           :\n (0.0576)            � (0.1030)                 � (0.0162)
1             � (0.0176)        [...] (0.0203)             Liber (0.0135)
2            Di (0.0146)          :\n (0.0190)             [...] (0.0127)
3             : (0.0114)        ([[ (8.42e-03)             :\n (5.98e-03)
4            (“ (0.0114)          ― (7.93e-03)              Di (5.28e-03)
5         lik (7.81e-03)      Liber (7.93e-03)          output (4.97e-03)
6       [...] (6.90e-03)          : (6.20e-03)              (“ (4.39e-03)
7    focusing (5.37e-03)         Di (5.46e-03)        Mediterr (4.12e-03)
8          :, (4.18e-03)        lik (4.52e-03)             ([[ (3.88e-03)
9          +: (3.94e-03)        [[[ (4.52e-03)   Mediterranean (3.63e-03)
10         Or (3.94e-03)         (“ (4.24e-03)     -categories (3.42e-03)
11         :N (3.68e-03)          ­ (3.31e-03)             rit (3.42e-03)
12         :S (3.05e-03)       fres (2.91e-03)        focusing (3.42e-03)
13     Output (2.87e-03)   focusing (2.75e-03)              (> (3.02e-03)
14    personn (2.87e-03)         Or (2.75e-03)           focus (2.84e-03)
15     Milano (2.87e-03)   Language (2.75e-03)          Output (2.84e-03)
16        Cod (2.87e-03)         :S (2.43e-03)    respectively (2.50e-03)
17          ― (2.53e-03)          ‚ (2.43e-03)               : (2.50e-03)
18      Neuro (2.38e-03)       Tart (2.14e-03)         focused (2.35e-03)
19          N (2.38e-03)     Milano (2.14e-03)             foc (2.35e-03)

                                                          \
                        pos_3                     pos_10
0              Liber (0.0325)                 � (0.0903)
1                � (9.89e-03)             [...] (0.0167)
2            [...] (9.89e-03)             Liber (0.0148)
3           output (6.41e-03)             ([[ (9.52e-03)
4               Di (5.31e-03)              Di (6.56e-03)
5              :\n (4.97e-03)             [ii (5.80e-03)
6         Mediterr (4.39e-03)               ¹ (5.80e-03)
7              rit (4.12e-03)             :\n (5.10e-03)
8      -categories (4.12e-03)            anni (5.10e-03)
9           Output (3.65e-03)              (“ (5.10e-03)
10             ([[ (3.42e-03)     -categories (4.79e-03)
11   Mediterranean (3.42e-03)               1 (4.24e-03)
12             [ii (3.42e-03)   Mediterranean (3.97e-03)
13              (“ (3.22e-03)               2 (3.97e-03)
14            anni (3.02e-03)              /~ (3.51e-03)
15              /~ (2.84e-03)               : (3.30e-03)
16              (> (2.84e-03)        Mediterr (3.30e-03)
17    respectively (2.50e-03)              Or (3.10e-03)
18        focusing (2.35e-03)            Tart (2.91e-03)
19             (us (2.35e-03)        Language (2.56e-03)


                       pos_50                    pos_100
0                  � (0.0552)                 � (0.0483)
1              Liber (0.0216)             Liber (0.0228)
2                 Di (0.0179)                Di (0.0167)
3               anni (0.0109)              anni (0.0108)
4              ([[ (7.93e-03)     -categories (6.96e-03)
5      -categories (5.83e-03)             ([[ (6.96e-03)
6             Tart (5.46e-03)            Tart (6.13e-03)
7            [...] (5.13e-03)             :\n (6.13e-03)
8    Mediterranean (4.82e-03)   Mediterranean (4.49e-03)
9               di (4.52e-03)              di (3.97e-03)
10             :\n (4.24e-03)             [ii (3.97e-03)
11             [ii (4.00e-03)           [...] (3.72e-03)
12        Mediterr (3.75e-03)           fresh (3.49e-03)
13             lik (3.31e-03)               : (3.30e-03)
14              (“ (3.11e-03)             lik (3.30e-03)
15           fresh (3.11e-03)        Mediterr (3.30e-03)
16              /~ (3.11e-03)            Kern (3.10e-03)
17             rit (3.11e-03)             rit (3.10e-03)
18            Kern (2.75e-03)             rze (2.90e-03)
19           ordin (2.75e-03)           ordin (2.90e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                   layer_7                                        \
                    pos_-3          pos_-1                 pos_0
0               , (0.0518)     -> (0.2819)          _ch (0.0316)
1       subject (0.0107) ✅     -> (0.0679)            C (0.0244)
2            sn (5.02e-03)    1 (0.0333) ✅       Chat (0.0183) ✅
3            lo (4.32e-03)   '\n' (0.0271)           _c (0.0158)
4     Caribbean (4.12e-03)     :- (0.0137)          .ch (0.0114)
5     answers (4.12e-03) ✅      . (0.0131)    talking (0.0102) ✅
6             b (3.29e-03)      ( (0.0119)          , (7.98e-03)
7          Loop (3.23e-03)    ' ' (0.0116)          B (7.85e-03)
8           sir (3.04e-03)    : (9.58e-03)          L (7.58e-03)
9             , (3.02e-03)    : (9.38e-03)    chatt (7.05e-03) ✅
10   question (2.97e-03) ✅   (m (5.28e-03)      Solar (5.09e-03)
11       post (2.95e-03) ✅  5 (4.64e-03) ✅       bond (5.00e-03)
12          loo (2.93e-03)  2 (3.68e-03) ✅          G (4.48e-03)
13           HL (2.90e-03)  4 (3.19e-03) ✅       Bond (4.28e-03)
14         mere (2.74e-03)    > (3.14e-03)    chats (3.84e-03) ✅
15         loaf (2.66e-03)   (g (3.05e-03)  Talking (3.79e-03) ✅
16            � (2.65e-03)  9 (3.00e-03) ✅       _com (3.75e-03)
17            L (2.59e-03)   :- (2.84e-03)        _sh (3.60e-03)
18            < (2.54e-03)  6 (2.52e-03) ✅          T (3.59e-03)
19   substances (2.41e-03)  3 (2.41e-03) ✅         _b (3.34e-03)

                                                                   \
                  pos_1                pos_2                pos_3
0           -> (0.2485)          -> (0.5199)         ann (0.1127)
1       blue (0.1823) ✅      blue (0.2188) ✅           " (0.1112)
2        hello (0.1016)       hello (0.0693)          -> (0.0285)
3        hello (0.0399)         ann (0.0270)           ' (0.0131)
4            " (0.0379)          -> (0.0183)          _l (0.0129)
5            ' (0.0177)           " (0.0111)   green (9.76e-03) ✅
6           -> (0.0140)         ( (7.96e-03)       _re (8.18e-03)
7      green (0.0117) ✅         , (7.91e-03)     hello (7.93e-03)
8          : (4.07e-03)         ' (6.37e-03)         _ (7.54e-03)
9          = (3.65e-03)       ' ' (5.09e-03)         , (6.60e-03)
10       ' ' (3.56e-03)   green (3.77e-03) ✅        _n (6.08e-03)
11         ( (3.33e-03)         . (2.23e-03)       ' ' (6.06e-03)
12        => (3.29e-03)         : (2.06e-03)        _f (5.55e-03)
13     red (2.96e-03) ✅     red (1.48e-03) ✅        _m (4.12e-03)
14         ` (2.69e-03)   goodbye (1.35e-03)       _an (3.94e-03)
15        (" (2.00e-03)        is (1.33e-03)        _v (3.42e-03)
16         - (1.82e-03)         - (1.28e-03)        _s (3.37e-03)
17         > (1.78e-03)         = (1.09e-03)    blue (3.36e-03) ✅
18   goodbye (1.65e-03)         > (1.02e-03)        _h (2.95e-03)
19       man (1.65e-03)         : (1.00e-03)    _red (2.82e-03) ✅

                      layer_14                               \
                        pos_-3                       pos_-1
0              fatt (8.50e-03)              NEWS (2.93e-03)
1               cre (6.39e-03)              frei (2.80e-03)
2          universe (5.98e-03)            acad (2.59e-03) ✅
3                 b (5.41e-03)          aktual (2.55e-03) ✅
4              doen (5.27e-03)            news (2.14e-03) ✅
5        literacy (4.55e-03) ✅             pos (2.12e-03) ✅
6          membrane (4.26e-03)        concrete (2.01e-03) ✅
7           spell (4.15e-03) ✅         personn (1.88e-03) ✅
8               177 (3.96e-03)               rij (1.85e-03)
9           chatter (3.64e-03)            pron (1.85e-03) ✅
10       spelling (3.10e-03) ✅              News (1.76e-03)
11   dictionaries (3.09e-03) ✅         barcelona (1.63e-03)
12          remin (3.01e-03) ✅         Christoph (1.54e-03)
13                B (2.98e-03)                /~ (1.43e-03)
14              dim (2.85e-03)               weg (1.42e-03)
15         memory (2.82e-03) ✅        Abstract (1.39e-03) ✅
16              gib (2.65e-03)               bre (1.37e-03)
17              dit (2.49e-03)         equival (1.31e-03) ✅
18     repetition (2.46e-03) ✅   Communication (1.25e-03) ✅
19           hollow (2.45e-03)        Language (1.24e-03) ✅

                                                                              \
                    pos_0                      pos_1                   pos_2
0         werk (0.0162) ✅        Output (9.52e-03) ✅      personn (0.0404) ✅
1            gev (0.0131)            :Any (8.91e-03)         fakt (0.0251) ✅
2      personn (0.0117) ✅           onian (8.91e-03)            gev (0.0234)
3      tremend (8.18e-03)           Flesh (7.87e-03)        prakt (0.0176) ✅
4          zaj (6.96e-03)        output (6.13e-03) ✅    recommand (0.0167) ✅
5      prakt (6.87e-03) ✅             gev (5.77e-03)           duro (0.0148)
6         frei (5.47e-03)             yaz (5.10e-03)         werk (0.0122) ✅
7          gek (5.38e-03)            INAL (4.49e-03)             zg (0.0104)
8        geber (5.38e-03)              /~ (4.21e-03)         mies (7.50e-03)
9    telefon (5.07e-03) ✅   productions (4.21e-03) ✅         caut (7.29e-03)
10        echt (5.06e-03)         kontrol (3.97e-03)         elek (7.13e-03)
11   municip (5.04e-03) ✅       outputs (3.72e-03) ✅         hele (6.15e-03)
12      klik (4.60e-03) ✅         recur (2.90e-03) ✅         samt (5.72e-03)
13       weg (4.49e-03) ✅             :". (2.90e-03)          pyt (5.51e-03)
14     leven (4.29e-03) ✅               메 (2.72e-03)          zaj (5.32e-03)
15        frem (3.68e-03)       recommand (2.40e-03)      leven (4.79e-03) ✅
16      komple (3.63e-03)        recurs (2.40e-03) ✅      adres (4.59e-03) ✅
17        LECT (3.53e-03)       Outputs (2.40e-03) ✅     testim (4.51e-03) ✅
18          zg (3.52e-03)             rab (2.40e-03)   karakter (4.50e-03) ✅
19        darm (3.36e-03)            nika (2.26e-03)       kurs (4.26e-03) ✅

                                         layer_15                            \
                        pos_3              pos_-3                    pos_-1
0           output (0.0348) ✅        :\n (0.7852)                � (0.0947)
1           Output (0.0271) ✅        :</ (0.0728)                ― (0.0610)
2          outputs (0.0175) ✅       ):\n (0.0209)       Language (0.0271) ✅
3                  메 (0.0155)          : (0.0162)                2 (0.0211)
4             nika (7.30e-03)         :. (0.0162)                1 (0.0204)
5          kontrol (6.44e-03)         :< (0.0143)                ¹ (0.0170)
6               /~ (5.69e-03)      :\n\n (0.0112)                — (0.0165)
7        Outputs (5.69e-03) ✅       :" (9.89e-03)               10 (0.0159)
8             INAL (5.69e-03)      (): (6.77e-03)                † (0.0140)
9         Output (5.34e-03) ✅    ():\n (3.20e-03)          [...] (9.64e-03)
10        output (4.71e-03) ✅     ":\n (3.20e-03)             as (7.29e-03)
11        OUTPUT (4.71e-03) ✅       .: (2.82e-03)              ― (6.23e-03)
12             rab (3.67e-03)       ": (2.50e-03)              3 (5.86e-03)
13            mies (3.44e-03)       !: (2.20e-03)            cod (5.68e-03)
14            anni (3.04e-03)       ?: (1.95e-03)              ‚ (5.00e-03)
15       recommand (2.86e-03)     :A (1.34e-03) ✅  Publication (4.55e-03) ✅
16             [ii (2.52e-03)  :\n\n\n (1.34e-03)    Generated (4.43e-03) ✅
17           recur (2.52e-03)       }: (1.34e-03)              ( (4.03e-03)
18         hasil (2.37e-03) ✅   :]\n\n (1.17e-03)              � (3.91e-03)
19   productions (2.37e-03) ✅      :", (1.17e-03)             Di (3.34e-03)

                                                    \
                   pos_0                     pos_1
0           :\n (0.0610)                � (0.1035)
1             � (0.0175)            [...] (0.0192)
2            Di (0.0145)              :\n (0.0192)
3            (“ (0.0113)            ([[ (8.48e-03)
4             : (0.0113)        Liber (8.00e-03) ✅
5         lik (7.78e-03)              ― (8.00e-03)
6       [...] (6.87e-03)              : (6.59e-03)
7    focusing (5.34e-03)           Di (5.46e-03) ✅
8          :, (4.15e-03)            lik (4.55e-03)
9          Or (3.91e-03)             (“ (4.55e-03)
10         +: (3.91e-03)            [[[ (4.55e-03)
11       :N (3.68e-03) ✅              ­ (3.33e-03)
12       :S (3.04e-03) ✅             Or (2.93e-03)
13    personn (2.85e-03)           fres (2.93e-03)
14     Milano (2.85e-03)       focusing (2.75e-03)
15        Cod (2.85e-03)       Language (2.75e-03)
16   Output (2.85e-03) ✅              ‚ (2.43e-03)
17          ― (2.52e-03)             :S (2.29e-03)
18    Neuro (2.37e-03) ✅              ¹ (2.15e-03)
19        N (2.37e-03) ✅   respectively (2.15e-03)


                         pos_2                        pos_3
0                   � (0.0162)             Liber (0.0322) ✅
1               Liber (0.0135)             [...] (9.83e-03)
2               [...] (0.0127)                 � (9.83e-03)
3               :\n (5.98e-03)            output (6.35e-03)
4                Di (5.28e-03)              Di (5.58e-03) ✅
5          output (4.97e-03) ✅               :\n (4.94e-03)
6                (“ (4.36e-03)        Mediterr (4.36e-03) ✅
7          Mediterr (4.12e-03)       -categories (4.09e-03)
8               ([[ (3.86e-03)               rit (4.09e-03)
9     Mediterranean (3.63e-03)            Output (3.62e-03)
10    -categories (3.40e-03) ✅               [ii (3.62e-03)
11       focusing (3.40e-03) ✅               ([[ (3.39e-03)
12              rit (3.40e-03)   Mediterranean (3.39e-03) ✅
13               (> (3.01e-03)                (“ (3.19e-03)
14          focus (2.82e-03) ✅            anni (2.99e-03) ✅
15           Output (2.66e-03)                /~ (2.99e-03)
16                : (2.49e-03)                (> (2.81e-03)
17   respectively (2.49e-03) ✅             Ari (2.49e-03) ✅
18        focused (2.35e-03) ✅      respectively (2.49e-03)
19             anni (2.35e-03)          focusing (2.33e-03)