# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [2]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/uprog_wide/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [3]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/uprog_wide/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/uprog_wide/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B_sft/uprog_wide/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                   layer_7                                                \
                      base             base_inv                       ft
0          .Today (0.0439)      urrenc (0.0287)          .Today (0.0219)
1       Buccane (7.20e-03)       pos (8.73e-03)         .Second (0.0103)
2       .Second (5.95e-03)       act (8.24e-03)       Buccane (8.54e-03)
3         /Area (5.95e-03)    askell (4.67e-03)         /Area (6.65e-03)
4         /Math (4.49e-03)      gons (3.33e-03)           .au (4.03e-03)
5           aru (4.36e-03)     fácil (2.58e-03)     /problems (3.68e-03)
6     /problems (3.97e-03)        دي (2.01e-03)         /Math (3.34e-03)
7      /respond (3.62e-03)    Phones (1.89e-03)         /bind (3.14e-03)
8          fter (3.30e-03)      ejec (1.67e-03)     /entities (2.85e-03)
9           .au (3.19e-03)      anth (1.62e-03)      /problem (2.78e-03)
10     /problem (3.10e-03)  essional (1.57e-03)     /activity (2.69e-03)
11    /entities (2.64e-03)      azon (1.57e-03)          oire (2.69e-03)
12   confidence (2.64e-03)     emies (1.47e-03)      /respond (2.44e-03)
13    /operator (2.56e-03)       dbl (1.38e-03)   persistence (2.30e-03)
14    belonging (2.56e-03)     posix (1.38e-03)          fter (2.30e-03)
15       soever (2.41e-03)         د (1.38e-03)    confidence (2.17e-03)
16         oire (2.41e-03)       med (1.30e-03)          ilot (2.17e-03)
17         ilot (2.20e-03)        �� (1.22e-03)        soever (2.17e-03)
18    /activity (2.00e-03)      orst (1.22e-03)           aru (2.09e-03)
19   /community (1.76e-03)   working (1.18e-03)     /operator (2.09e-03)

                                                                           \
                 ft_inv                    diff                  diff_inv
0       urrenc (0.0145)         ugging (0.0221)           bras (8.06e-03)
1        pos (5.31e-03)          kit (9.22e-03)       Triangle (5.04e-03)
2        act (4.85e-03)         audi (6.74e-03)        ilename (4.58e-03)
3     askell (4.85e-03)         cell (6.32e-03)         /theme (3.91e-03)
4         �� (3.22e-03)         insi (5.58e-03)            ben (3.25e-03)
5       gons (3.13e-03)          apo (5.58e-03)        ziehung (3.14e-03)
6      fácil (2.84e-03)         agua (5.25e-03)            hea (3.14e-03)
7         دي (2.15e-03)            ò (5.25e-03)     underwater (3.05e-03)
8       anth (2.15e-03)   Excellence (4.64e-03)            ome (2.61e-03)
9       azon (1.95e-03)           tf (4.09e-03)            hev (2.30e-03)
10       med (1.95e-03)           /( (4.09e-03)    AspectRatio (2.30e-03)
11  essional (1.89e-03)          ysi (3.83e-03)          Fence (2.17e-03)
12        vs (1.67e-03)          ZIP (3.83e-03)          alary (2.17e-03)
13    Phones (1.62e-03)         iste (3.83e-03)           Bold (2.11e-03)
14      ejec (1.53e-03)          riz (3.83e-03)         loving (2.11e-03)
15  Optional (1.43e-03)         ILES (3.60e-03)            882 (2.03e-03)
16         د (1.34e-03)         Pers (3.60e-03)            chy (2.03e-03)
17     cambi (1.30e-03)          KIT (3.60e-03)        .Events (1.91e-03)
18       div (1.22e-03)        alist (3.39e-03)           Draw (1.79e-03)
19      Vers (1.15e-03)          STR (3.39e-03)   associations (1.74e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9102)          zoek (0.7539)           To (0.9141)
1           The (0.0427)      contador (0.2158)          The (0.0400)
2            In (0.0167)             메 (0.0201)           In (0.0157)
3           1 (9.52e-03)         иск (5.07e-03)          Let (0.0122)
4         Let (4.79e-03)     Produto (4.49e-03)          A (3.49e-03)
5           A (3.30e-03)     Detalle (1.42e-05)        ### (3.30e-03)
6           I (2.12e-03)           � (1.26e-05)        For (1.88e-03)
7          As (1.29e-03)      Resets (8.64e-06)         ** (1.46e-03)
8         For (9.99e-04)         .\" (7.63e-06)          I (1.29e-03)
9          It (6.68e-04)          首页 (3.61e-06)         As (1.21e-03)
10        ### (5.72e-04)    autoplay (2.47e-06)  Certainly (9.73e-04)
11  Certainly (5.19e-04)       KANJI (1.94e-06)       Sure (7.32e-04)
12       Sure (5.04e-04)      inicio (1.94e-06)          1 (6.10e-04)
13       This (4.44e-04)      Editar (1.51e-06)       This (4.31e-04)
14         We (3.81e-04)    Executes (1.04e-06)         It (4.31e-04)
15      First (3.36e-04)         Msp (1.04e-06)       Here (3.59e-04)
16          S (2.54e-04)      Insets (1.04e-06)      First (3.36e-04)
17         ** (1.92e-04)      Tambah (9.13e-07)         We (3.36e-04)
18          H (1.86e-04)           구 (9.13e-07)      Given (1.80e-04)
19      There (1.54e-04)   Generates (9.13e-07)          H (1.75e-04)

                                                                            \
                   ft_inv                   diff                  diff_inv
0           zoek (0.8359)            ** (0.0311)                1 (0.9922)
1       contador (0.1455)       appable (0.0228)             01 (5.84e-04)
2              메 (0.0106)      Fallback (0.0189)  <|endoftext|> (4.01e-04)
3          иск (4.97e-03)    retrofit (7.87e-03)              2 (4.01e-04)
4      Produto (2.35e-03)          ** (7.39e-03)              4 (1.67e-04)
5            � (1.59e-05)     dissect (5.10e-03)              0 (7.39e-05)
6      Detalle (1.09e-05)    crafting (3.49e-03)             12 (6.96e-05)
7       Resets (7.48e-06)         **, (2.90e-03)             11 (6.96e-05)
8          .\" (5.13e-06)       ceipt (2.72e-03)             sz (5.77e-05)
9           首页 (2.76e-06)       riger (2.72e-03)             10 (5.77e-05)
10      inicio (1.89e-06)    Crafting (2.72e-03)              3 (5.25e-05)
11       KANJI (1.48e-06)          [# (2.56e-03)          hello (4.51e-05)
12    autoplay (1.48e-06)         **( (2.56e-03)          Hello (4.51e-05)
13      Editar (1.30e-06)      emodel (2.56e-03)          Hello (4.22e-05)
14   Retrieves (1.01e-06)        awah (2.40e-03)            001 (4.22e-05)
15   Generates (8.94e-07)         ado (2.40e-03)              5 (4.10e-05)
16     kontakt (8.94e-07)         dab (2.00e-03)           user (4.10e-05)
17         Msp (8.94e-07)  ampionship (1.87e-03)            loy (3.96e-05)
18      <quote (7.90e-07)       flesh (1.87e-03)             -W (3.72e-05)
19           구 (7.90e-07)     istance (1.75e-03)              6 (3.62e-05)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.8672)          zoek (0.9180)           To (0.4785)
1           The (0.0432)      contador (0.0457)           ** (0.3730)
2            ** (0.0204)           иск (0.0168)          ### (0.1069)
3           Let (0.0179)             메 (0.0148)          Let (0.0145)
4           ### (0.0159)     Produto (3.75e-03)          The (0.0128)
5             1 (0.0140)          首页 (4.72e-05)  Certainly (4.70e-03)
6          In (5.16e-03)        (PHP (1.63e-05)       Sure (2.21e-03)
7   Certainly (4.55e-03)      amodel (9.30e-06)         In (1.72e-03)
8        Sure (3.13e-03)    autoplay (8.23e-06)         ## (6.37e-04)
9           I (1.47e-03)     Detalle (7.69e-06)       Here (4.37e-04)
10          A (1.08e-03)         Msp (6.79e-06)          A (4.37e-04)
11         As (9.54e-04)  modifiable (6.38e-06)      Given (3.85e-04)
12         It (7.90e-04)       ptest (6.38e-06)       This (2.99e-04)
13       This (7.40e-04)         .\" (5.63e-06)         As (2.65e-04)
14      Given (5.76e-04)      ertest (4.11e-06)        For (2.48e-04)
15         We (5.11e-04)           � (3.87e-06)          1 (2.34e-04)
16      First (4.50e-04)    <article (3.64e-06)      First (2.06e-04)
17        For (2.73e-04)        [now (3.64e-06)          I (1.82e-04)
18       Here (2.56e-04)       edata (3.22e-06)         It (1.61e-04)
19          S (1.99e-04)      Gratis (3.22e-06)         We (1.11e-04)


                   ft_inv                    diff                diff_inv
0           zoek (0.9570)             ** (0.2197)              1 (0.8320)
1       contador (0.0199)             ** (0.0713)  <|endoftext|> (0.1543)
2            иск (0.0120)            **( (0.0383)            2 (2.27e-03)
3            메 (9.40e-03)            **, (0.0232)            4 (1.01e-03)
4      Produto (9.92e-04)            *** (0.0232)            3 (4.20e-04)
5           首页 (3.84e-05)            (** (0.0117)            5 (4.06e-04)
6         (PHP (1.41e-05)          (** (8.54e-03)            7 (4.06e-04)
7          Msp (1.10e-05)     Fallback (7.54e-03)           10 (4.06e-04)
8            � (6.65e-06)       emodel (6.65e-03)           12 (3.70e-04)
9          .\" (5.51e-06)          *** (5.49e-03)            8 (3.07e-04)
10     Detalle (5.19e-06)         *pow (5.19e-03)           15 (3.07e-04)
11       ptest (4.59e-06)      Produto (5.19e-03)            0 (2.63e-04)
12    autoplay (4.29e-06)           *( (4.85e-03)            - (2.63e-04)
13      amodel (3.35e-06)          ,** (3.78e-03)            9 (2.46e-04)
14        [now (3.14e-06)      appable (3.78e-03)            6 (2.32e-04)
15      ertest (2.61e-06)  structuring (2.94e-03)           11 (1.98e-04)
16      -deals (2.29e-06)     <article (2.78e-03)           20 (1.86e-04)
17        SCRI (2.29e-06)     Crafting (2.61e-03)            - (1.64e-04)
18  modifiable (2.29e-06)       Constr (2.29e-03)           01 (1.16e-04)
19     inflate (2.29e-06)      mutable (2.15e-03)           16 (1.13e-04)

In [5]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0337)       .vn (7.54e-03)        /problem (0.0410)
1        /entities (0.0219)      sagt (5.52e-03)       /entities (0.0265)
2        /problems (0.0165)        że (4.88e-03)       /problems (0.0182)
3        /global (9.64e-03)       ]]; (4.30e-03)       /global (8.85e-03)
4         .Today (9.64e-03)       (us (4.03e-03)        .Today (8.61e-03)
5        /layout (8.00e-03)    testim (2.96e-03)       /manage (6.71e-03)
6        /manage (7.78e-03)       ')" (2.96e-03)          /job (6.71e-03)
7           /job (7.08e-03)     zeigt (2.78e-03)       /layout (5.74e-03)
8      /provider (6.26e-03)      -ves (2.78e-03)  /preferences (5.22e-03)
9   /preferences (5.19e-03)       (!! (2.61e-03)     /provider (5.07e-03)
10   /connection (4.58e-03)       ($. (2.44e-03)       /crypto (4.91e-03)
11    WHATSOEVER (4.43e-03)     lesen (2.30e-03)   /connection (4.33e-03)
12      /logging (3.91e-03)     feliz (2.03e-03)      /logging (4.06e-03)
13        .Round (3.91e-03)     spons (1.91e-03)       /engine (3.81e-03)
14       /dialog (3.68e-03)   kontrol (1.91e-03)  /environment (3.81e-03)
15       /crypto (3.68e-03)     scrut (1.69e-03)          /reg (3.71e-03)
16          /reg (3.34e-03)    spiele (1.69e-03)    WHATSOEVER (3.71e-03)
17       /entity (3.14e-03)       fas (1.58e-03)      /effects (3.59e-03)
18      /weather (3.04e-03)       )": (1.49e-03)       /dialog (3.48e-03)
19      libertin (3.04e-03)      -git (1.40e-03)       /entity (3.17e-03)

                                                                       \
                 ft_inv                  diff                diff_inv
0        .vn (8.36e-03)       rang (7.05e-03)            oke (0.0140)
1        (us (4.49e-03)        bus (6.23e-03)          alary (0.0117)
2        ]]; (4.21e-03)   Crushers (4.55e-03)   underwater (7.78e-03)
3       sagt (3.97e-03)        BUS (4.27e-03)        clubs (4.70e-03)
4         że (3.97e-03)      Franc (4.27e-03)          UTF (3.91e-03)
5      zeigt (3.08e-03)       orsi (3.77e-03)         enal (3.91e-03)
6       -ves (3.08e-03)         Zu (3.33e-03)         enia (3.34e-03)
7        ($. (2.88e-03)        UPS (3.33e-03)         ohen (3.23e-03)
8     testim (2.88e-03)        str (3.13e-03)     vertical (3.23e-03)
9        ')" (2.72e-03)        STR (2.94e-03)      centres (3.14e-03)
10       (!! (2.26e-03)       ilit (2.76e-03)         ooke (3.14e-03)
11     feliz (2.26e-03)       BOSE (2.76e-03)    Unlimited (3.14e-03)
12     lesen (2.26e-03)        ành (2.59e-03)    .intellij (2.94e-03)
13     spons (2.26e-03)      &page (2.44e-03)         odic (2.69e-03)
14   kontrol (1.65e-03)       iali (2.44e-03)        /show (2.37e-03)
15      helf (1.65e-03)        riz (2.29e-03)        sheds (2.15e-03)
16    spiele (1.55e-03)       kurs (2.29e-03)          ost (2.03e-03)
17       )": (1.55e-03)          ® (2.15e-03)   Lauderdale (1.97e-03)
18     scrut (1.46e-03)       Said (2.15e-03)       onsite (1.91e-03)
19      -git (1.46e-03)        089 (2.09e-03)    Henderson (1.85e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.6367)     contador (0.6680)         , (0.6172)
1       and (0.1289)           �� (0.0122)       and (0.1377)
2       the (0.0918)           �� (0.0122)       the (0.1021)
3        in (0.0591)      subur (9.52e-03)       ' ' (0.0564)
4       ' ' (0.0513)         bö (9.52e-03)        in (0.0542)
5         a (0.0123)    kontrol (5.77e-03)         a (0.0120)
6       ( (3.60e-03)      KANJI (5.77e-03)       ( (4.70e-03)
7      to (3.48e-03)       samt (5.77e-03)      to (2.99e-03)
8      of (2.90e-03)   karakter (4.49e-03)      of (2.66e-03)
9      by (1.98e-03)     testim (4.49e-03)      by (2.15e-03)
10    for (1.83e-03)        tgl (4.49e-03)     for (1.93e-03)
11     is (1.72e-03)       sagt (4.49e-03)      is (1.01e-03)
12     as (8.58e-04)     komple (2.73e-03)      as (9.12e-04)
13     on (5.80e-04)     kosten (2.73e-03)      on (6.48e-04)
14   will (5.26e-04)     uarios (2.73e-03)    will (5.53e-04)
15      " (4.73e-04)       helf (2.12e-03)    with (3.57e-04)
16      . (4.65e-04)     sperma (2.12e-03)       " (3.57e-04)
17     at (3.11e-04)     bilder (1.66e-03)       . (3.01e-04)
18     we (2.86e-04)   misunder (1.66e-03)  '\xa0' (2.61e-04)
19   with (2.50e-04)     zwarte (1.66e-03)      at (2.41e-04)

                                                                          \
                  ft_inv                   diff                 diff_inv
0      contador (0.8398)         vibes (0.0121)   <|endoftext|> (0.4609)
1     kontrol (7.26e-03)       folks (6.29e-03)          zoek (7.02e-03)
2          �� (5.65e-03)     dissect (5.22e-03)           иск (5.46e-03)
3    karakter (5.65e-03)    retrofit (4.61e-03)        REGION (4.24e-03)
4          bö (5.65e-03)         dov (3.48e-03)   Initializes (3.31e-03)
5          �� (5.65e-03)      embody (3.48e-03)            |\ (3.11e-03)
6       subur (4.39e-03)    squarely (2.88e-03)           ore (2.91e-03)
7        samt (4.39e-03)   sophistic (2.62e-03)            sg (2.14e-03)
8       KANJI (3.42e-03)        moot (2.55e-03)       unknown (2.01e-03)
9      kosten (2.67e-03)       weave (2.40e-03)           ano (1.77e-03)
10     testim (2.67e-03)           � (2.40e-03)     continued (1.47e-03)
11       sagt (2.08e-03)        thro (2.32e-03)      fotograf (1.47e-03)
12        tgl (1.62e-03)      encaps (2.32e-03)          ille (1.38e-03)
13       zoek (1.62e-03)      sculpt (2.24e-03)         other (1.38e-03)
14     komple (1.62e-03)         you (2.24e-03)      continue (1.30e-03)
15     bilder (1.26e-03)        epit (2.24e-03)    Previously (1.14e-03)
16       dara (1.26e-03)        vibe (2.11e-03)            xa (1.14e-03)
17     uarios (1.26e-03)      embell (2.04e-03)       Another (1.08e-03)
18     <quote (1.26e-03)   genuinely (1.98e-03)       persone (1.08e-03)
19       rekl (1.26e-03)       burge (1.86e-03)      Possible (1.08e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.7031)    contador (0.0278)         , (0.5430)
1        ' ' (0.0718)        �� (4.82e-03)       ' ' (0.1245)
2         in (0.0718)       ，默认 (2.93e-03)        in (0.1035)
3        and (0.0464)       (Cs (2.27e-03)       and (0.0732)
4        the (0.0422)    <quote (2.27e-03)       the (0.0669)
5          a (0.0206)     UTTON (2.27e-03)         ( (0.0270)
6          ( (0.0125)       LIK (1.78e-03)         a (0.0238)
7       to (6.29e-03)    anneer (1.78e-03)      to (6.81e-03)
8       by (4.88e-03)    icerca (1.78e-03)     for (6.41e-03)
9      for (3.31e-03)      LOSE (1.78e-03)      by (5.83e-03)
10       " (2.88e-03)        �� (1.78e-03)      as (3.59e-03)
11      as (1.88e-03)    incinn (1.78e-03)       " (1.98e-03)
12      of (1.50e-03)       ogs (1.78e-03)   first (1.72e-03)
13   first (1.09e-03)      rido (1.78e-03)    with (1.46e-03)
14       - (9.73e-04)        为空 (1.38e-03)      of (1.40e-03)
15    with (7.93e-04)        排序 (1.38e-03)      ** (1.11e-03)
16      we (7.86e-04)       ��이 (1.38e-03)    will (9.99e-04)
17    will (5.95e-04)  cripcion (1.38e-03)       - (8.81e-04)
18       . (5.26e-04)      LEAN (1.38e-03)      we (8.39e-04)
19      on (4.06e-04)      <?\n (1.38e-03)     you (7.25e-04)


                ft_inv                         diff                diff_inv
0    contador (0.0469)              ruta (3.66e-03)  <|endoftext|> (1.0000)
1    incinn (4.94e-03)          Fallback (2.52e-03)       '\n\n' (7.25e-05)
2      LOSE (3.85e-03)          Backdrop (2.52e-03)         '\n' (1.47e-05)
3     UTTON (3.85e-03)       pornografia (1.95e-03)            1 (5.78e-06)
4      rido (3.85e-03)         Clickable (1.72e-03)            . (5.25e-06)
5        �� (3.85e-03)             dikke (1.53e-03)            , (3.84e-06)
6    <quote (3.85e-03)              piry (1.53e-03)           is (1.33e-06)
7    icerca (3.01e-03)            []\r\n (1.34e-03)            " (8.72e-07)
8      anio (2.33e-03)       .decorators (1.34e-03)        :\n\n (7.67e-07)
9      <?\n (2.33e-03)         Lifecycle (1.34e-03)          was (4.12e-07)
10     zoek (2.33e-03)               GFX (1.19e-03)          :\n (3.99e-07)
11      ，默认 (2.33e-03)           bsolute (1.19e-03)           We (3.63e-07)
12      (Cs (1.82e-03)         Lifecycle (1.19e-03)            E (3.15e-07)
13     utow (1.82e-03)  ChangedEventArgs (1.19e-03)            2 (3.05e-07)
14      ogs (1.82e-03)            prefab (1.19e-03)            4 (2.83e-07)
15      tgl (1.60e-03)              amac (1.05e-03)            N (2.83e-07)
16   HOLDER (1.60e-03)            elerik (1.05e-03)            i (2.50e-07)
17   LOGGER (1.60e-03)              OUCH (1.05e-03)            8 (2.42e-07)
18      @js (1.60e-03)               。</ (1.05e-03)            I (2.42e-07)
19       排序 (1.60e-03)       .foundation (1.05e-03)            a (2.35e-07)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [6]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                 \
                       base              base_inv                       ft
0        /entities (0.0234)          .vn (0.0184)       /entities (0.0279)
1         /problem (0.0124)    /Register (0.0114)        /problem (0.0150)
2      /problems (9.37e-03)       sagt (7.68e-03)     /problems (9.97e-03)
3        /global (7.36e-03)     testim (6.92e-03)       /global (6.90e-03)
4      /provider (6.62e-03)        -ie (6.12e-03)     /provider (6.30e-03)
5    /connection (6.21e-03)      asign (5.01e-03)  /environment (6.00e-03)
6         .Today (5.65e-03)         że (4.75e-03)   /connection (5.99e-03)
7        /manage (5.29e-03)      zeigt (4.47e-03)        .Today (5.45e-03)
8   /environment (4.97e-03)    personn (3.48e-03)     /customer (4.93e-03)
9      /customer (3.99e-03)       -ves (3.32e-03)       /manage (4.89e-03)
10  /preferences (3.56e-03)      probs (3.21e-03)  /preferences (4.06e-03)
11       /layout (3.52e-03)       roku (2.84e-03)       /shared (3.42e-03)
12       /dialog (3.45e-03)     ):\n\n (2.55e-03)       /dialog (3.40e-03)
13       /shared (3.35e-03)          ť (2.54e-03)      /account (3.38e-03)
14      /account (3.24e-03)       elig (2.51e-03)      libertin (3.26e-03)
15      libertin (3.08e-03)        )": (2.38e-03)       /entity (3.19e-03)
16             , (2.92e-03)        esl (2.32e-03)      /effects (3.05e-03)
17       /entity (2.91e-03)      lesen (2.23e-03)       /layout (3.02e-03)
18         .Take (2.90e-03)   ,,,,,,,, (2.14e-03)          .Try (2.91e-03)
19        /legal (2.82e-03)   misunder (2.12e-03)        /legal (2.67e-03)

                                                                        \
                 ft_inv                   diff                diff_inv
0          .vn (0.0216)         gli (6.11e-03)           ooke (0.0136)
1    /Register (0.0111)        rang (5.73e-03)         ohen (9.32e-03)
2     testim (6.69e-03)       elman (4.96e-03)        alary (7.53e-03)
3       sagt (6.55e-03)          jà (4.69e-03)          oke (7.14e-03)
4        -ie (5.02e-03)     inerary (4.55e-03)   IndexError (4.57e-03)
5      asign (4.95e-03)      ibilit (3.94e-03)           jj (4.10e-03)
6      zeigt (4.50e-03)       aming (3.74e-03)   underwater (3.93e-03)
7         że (3.72e-03)   {\n\n\n\n (3.22e-03)    Unlimited (3.22e-03)
8       -ves (3.31e-03)       richt (3.15e-03)         oton (3.00e-03)
9          ť (3.25e-03)       &page (2.98e-03)    inclusive (2.75e-03)
10     probs (2.86e-03)         neh (2.94e-03)          hue (2.64e-03)
11   personn (2.77e-03)      anmeld (2.85e-03)           HL (2.56e-03)
12      roku (2.35e-03)         STR (2.56e-03)          UTF (2.51e-03)
13      elig (2.33e-03)         nye (2.39e-03)         arer (2.45e-03)
14     lesen (2.29e-03)         str (2.27e-03)         lean (2.21e-03)
15  ,,,,,,,, (2.27e-03)      elerik (2.17e-03)          arc (2.20e-03)
16    ):\n\n (2.21e-03)        konk (2.09e-03)         ogen (2.06e-03)
17       )": (2.21e-03)         ITS (1.98e-03)          oku (2.02e-03)
18       esl (2.00e-03)   contrario (1.94e-03)           -Z (2.02e-03)
19    spiele (1.95e-03)         lut (1.89e-03)        clubs (1.96e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8532)     contador (0.9300)         , (0.8096)
1        ' ' (0.0821)     testim (3.08e-03)       ' ' (0.1174)
2        the (0.0277)      subur (2.41e-03)       the (0.0329)
3        and (0.0237)   misunder (2.39e-03)       and (0.0244)
4       in (5.04e-03)    kontrol (2.20e-03)       ( (5.47e-03)
5        ( (3.30e-03)       helf (1.84e-03)      in (4.47e-03)
6        a (1.18e-03)          � (1.71e-03)      's (2.14e-03)
7       's (1.14e-03)         �� (1.62e-03)       a (1.21e-03)
8       to (9.21e-04)         bö (1.55e-03)      to (8.67e-04)
9        . (8.90e-04)       rekl (1.32e-03)       . (6.73e-04)
10      of (2.85e-04)   karakter (1.31e-03)      of (2.79e-04)
11     for (1.39e-04)    Produto (1.24e-03)     for (1.45e-04)
12   solve (8.63e-05)      KANJI (1.10e-03)  '\xa0' (6.88e-05)
13      is (5.29e-05)     bilder (9.92e-04)   solve (4.82e-05)
14      as (3.99e-05)     <quote (7.72e-04)      is (4.71e-05)
15       " (3.46e-05)       zoek (7.44e-04)      as (4.69e-05)
16      on (3.29e-05)    proport (6.52e-04)      on (3.95e-05)
17       : (2.43e-05)       samt (6.35e-04)       " (3.08e-05)
18    this (2.07e-05)       fakt (5.73e-04)      by (2.27e-05)
19      by (2.05e-05)     komple (5.68e-04)       : (2.26e-05)

                                                                          \
                  ft_inv                   diff                 diff_inv
0      contador (0.9615)       vibes (9.82e-03)   <|endoftext|> (0.6021)
1     kontrol (2.76e-03)           Â (7.39e-03)            zoek (0.0190)
2    karakter (2.31e-03)       temps (4.70e-03)             иск (0.0121)
3          bö (1.29e-03)      Cutter (2.61e-03)      karakter (5.73e-03)
4        zoek (1.29e-03)    retrofit (1.93e-03)      contador (5.69e-03)
5     Produto (1.15e-03)      demean (1.91e-03)       kontrol (2.50e-03)
6        rekl (9.87e-04)      commod (1.91e-03)       Produto (1.86e-03)
7      testim (9.78e-04)           ™ (1.77e-03)          |.\n (1.64e-03)
8          �� (8.78e-04)         btw (1.59e-03)   Initializes (1.38e-03)
9      bilder (8.62e-04)        slog (1.53e-03)         other (1.24e-03)
10       samt (6.56e-04)   sophistic (1.52e-03)          puta (1.23e-03)
11       dara (6.52e-04)   portrayal (1.45e-03)           ore (1.16e-03)
12      subur (6.35e-04)      cultiv (1.41e-03)           gia (1.04e-03)
13      KANJI (5.20e-04)           â (1.40e-03)           ors (1.01e-03)
14       helf (4.33e-04)     tighten (1.36e-03)            xa (9.82e-04)
15          메 (3.99e-04)        prez (1.36e-03)        REGION (9.55e-04)
16     kosten (3.52e-04)      fleece (1.32e-03)      caliente (9.54e-04)
17     <quote (2.99e-04)   discourse (1.30e-03)            mã (9.48e-04)
18     komple (2.88e-04)        moot (1.30e-03)           seh (9.29e-04)
19       fakt (2.66e-04)      hustle (1.29e-03)          :-\n (9.13e-04)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.8868)     contador (0.8818)           , (0.6876)
1          ' ' (0.0666)       zoek (7.12e-03)         ' ' (0.1571)
2            ( (0.0209)    Produto (6.99e-03)           ( (0.1258)
3          the (0.0179)     <quote (1.83e-03)         the (0.0186)
4         in (1.74e-03)         �� (1.40e-03)        in (2.39e-03)
5        and (1.59e-03)       [now (9.17e-04)       and (2.36e-03)
6          a (1.03e-03)          � (8.44e-04)        's (1.66e-03)
7         's (1.01e-03)      dikke (5.57e-04)         a (1.02e-03)
8          " (4.18e-04)  ！\n\n\n\n (5.22e-04)        ** (7.89e-04)
9         to (4.14e-04)          메 (3.36e-04)        to (5.42e-04)
10         : (2.63e-04)      KANJI (2.38e-04)     solve (4.52e-04)
11     solve (2.39e-04)    groupon (2.19e-04)         " (2.44e-04)
12         . (1.57e-04)        ，默认 (1.94e-04)         : (1.99e-04)
13      this (1.26e-04)    $insert (1.80e-04)   address (1.47e-04)
14         - (6.89e-05)     ！！\n\n (1.74e-04)      this (1.20e-04)
15       for (6.74e-05)      UTTON (1.66e-04)       for (1.19e-04)
16        by (4.81e-05)        ogs (1.66e-04)    tackle (9.71e-05)
17        of (4.14e-05)    Detalle (1.62e-04)   problem (8.77e-05)
18   problem (3.77e-05)        (Cs (1.50e-04)        as (5.97e-05)
19     :\n\n (3.73e-05)      Venta (1.48e-04)        by (5.74e-05)


                  ft_inv                     diff                diff_inv
0      contador (0.9296)     Clickable (2.54e-03)  <|endoftext|> (1.0000)
1        zoek (6.39e-03)     Lifecycle (2.00e-03)       '\n\n' (1.70e-05)
2     Produto (1.49e-03)     Lifecycle (1.66e-03)         '\n' (1.23e-05)
3           메 (4.63e-04)      Backdrop (1.33e-03)            . (4.42e-06)
4      <quote (3.55e-04)        Insets (1.18e-03)            , (3.64e-06)
5          �� (3.42e-04)         *\r\n (1.13e-03)            1 (2.80e-06)
6       UTTON (2.34e-04)           。</ (1.04e-03)            - (9.62e-07)
7    karakter (2.20e-04)          ANTI (9.92e-04)            2 (8.95e-07)
8      HOLDER (2.05e-04)      Retrofit (9.83e-04)            4 (6.19e-07)
9    entarios (2.00e-04)      -animate (9.82e-04)            " (3.24e-07)
10       rido (1.89e-04)           *</ (9.62e-04)            3 (2.70e-07)
11     urette (1.53e-04)   .foundation (8.81e-04)            8 (2.65e-07)
12    kontrol (1.44e-04)         promo (8.40e-04)          :\n (2.53e-07)
13      anela (1.36e-04)       GetData (8.35e-04)            6 (2.25e-07)
14     icerca (1.34e-04)   pornografia (8.19e-04)            5 (2.25e-07)
15        用户名 (1.31e-04)           GFX (8.00e-04)        :\n\n (2.21e-07)
16       obao (1.29e-04)      Dropdown (7.95e-04)            i (2.14e-07)
17        ，默认 (1.26e-04)      Fallback (7.89e-04)           is (1.97e-07)
18       [now (1.25e-04)      .parsers (7.81e-04)            I (1.96e-07)
19    ategori (1.17e-04)      backpage (7.72e-04)            \ (1.74e-07)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [7]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                     layer_7                                               \
                        base                       ft                diff
0            .Today (0.0439)          .Today (0.0223)          . (0.0432)
1             aru (6.41e-03)       .Second (8.75e-03)       .b (0.0296) ✅
2         /Area (5.19e-03) ✅       Buccane (6.54e-03)       .h (0.0268) ✅
3         .Second (4.58e-03)       /Area (6.22e-03) ✅      hello (0.0231)
4         Buccane (4.58e-03)           .au (4.36e-03)         .. (0.0191)
5         /Math (4.01e-03) ✅       /Math (3.25e-03) ✅       .c (0.0157) ✅
6            fter (3.77e-03)   /problems (3.12e-03) ✅        113 (0.0150)
7    confidence (3.65e-03) ✅          ilot (2.81e-03)     '\n' (7.05e-03)
8             .au (3.54e-03)           aru (2.73e-03)  .data (6.41e-03) ✅
9            ilot (2.87e-03)    confidence (2.70e-03)    .blue (6.28e-03)
10    /problems (2.78e-03) ✅   /activity (2.53e-03) ✅       42 (6.18e-03)
11    belonging (2.48e-03) ✅          fter (2.51e-03)        - (6.06e-03)
12     /respond (2.26e-03) ✅   /entities (2.43e-03) ✅      .is (5.61e-03)
13     /problem (2.24e-03) ✅       /bind (2.43e-03) ✅       .n (4.95e-03)
14    /entities (1.93e-03) ✅          oire (2.31e-03)      .ar (4.80e-03)
15             ,a (1.89e-03)    /problem (2.28e-03) ✅      115 (4.31e-03)
16    /operator (1.81e-03) ✅   persistence (2.08e-03)     .m (3.75e-03) ✅
17    /activity (1.74e-03) ✅    /respond (1.84e-03) ✅     .p (3.67e-03) ✅
18           oire (1.72e-03)   /operator (1.78e-03) ✅       .+ (2.98e-03)
19   /community (1.67e-03) ✅     belonging (1.76e-03)      .my (2.81e-03)

                layer_14                                                \
                    base                    ft                    diff
0            To (0.9336)           To (0.7904)             ** (0.0135)
1           The (0.0249)           ** (0.0944)     Fallback (9.66e-03)
2         Let (0.0171) ✅          ### (0.0623)      appable (6.37e-03)
3         ### (5.22e-03)        Let (0.0347) ✅        trump (6.10e-03)
4         1 (4.24e-03) ✅        The (9.97e-03)      dissect (5.23e-03)
5          In (3.74e-03)  Certainly (2.62e-03)          dab (4.11e-03)
6          ** (2.74e-03)       Sure (1.73e-03)     retrofit (3.83e-03)
7        Sure (1.40e-03)         In (8.16e-04)        trous (3.11e-03)
8   Certainly (1.38e-03)         ## (5.39e-04)     funnel (2.89e-03) ✅
9           I (6.24e-04)       Here (3.71e-04)       encaps (2.71e-03)
10         As (4.29e-04)    Given (2.49e-04) ✅         moot (2.44e-03)
11         We (3.34e-04)    First (2.07e-04) ✅      Draft (2.42e-03) ✅
12         It (3.07e-04)       This (1.45e-04)        flesh (2.34e-03)
13          A (2.94e-04)        For (1.33e-04)    Brewing (2.18e-03) ✅
14    First (2.94e-04) ✅         As (1.25e-04)     drafts (2.11e-03) ✅
15     This (2.77e-04) ✅        1 (1.02e-04) ✅   governance (1.88e-03)
16    Given (2.02e-04) ✅    Alright (9.97e-05)        acerb (1.73e-03)
17        For (1.68e-04)         We (7.28e-05)         turf (1.70e-03)
18     Here (1.15e-04) ✅          A (7.12e-05)          ### (1.68e-03)
19    There (8.09e-05) ✅          I (6.83e-05)   crafting (1.66e-03) ✅

                layer_15
                    base                    ft                      diff
0            To (0.8594)           To (0.4785)               ** (0.2148)
1           The (0.0483)           ** (0.3730)               ** (0.0698)
2         Let (0.0201) ✅          ### (0.1069)              **( (0.0374)
3            ** (0.0178)        Let (0.0145) ✅              **, (0.0227)
4           1 (0.0157) ✅          The (0.0128)              *** (0.0227)
5           ### (0.0157)  Certainly (4.70e-03)              (** (0.0121)
6          In (6.56e-03)       Sure (2.21e-03)            (** (8.36e-03)
7   Certainly (3.97e-03)         In (1.72e-03)       Fallback (7.81e-03)
8        Sure (3.10e-03)         ## (6.37e-04)         emodel (6.90e-03)
9           I (1.88e-03)       Here (4.37e-04)            *** (5.37e-03)
10          A (1.14e-03)          A (4.37e-04)        Produto (5.37e-03)
11         As (1.01e-03)    Given (3.85e-04) ✅           *pow (5.07e-03)
12         It (8.32e-04)       This (2.99e-04)             *( (4.76e-03)
13       This (7.82e-04)         As (2.65e-04)            ,** (3.94e-03)
14       We (6.90e-04) ✅        For (2.48e-04)        appable (3.69e-03)
15    Given (5.72e-04) ✅        1 (2.34e-04) ✅  structuring (3.07e-03) ✅
16    First (4.75e-04) ✅    First (2.19e-04) ✅     <article (2.88e-03) ✅
17        For (3.26e-04)          I (1.82e-04)     Crafting (2.70e-03) ✅
18       Here (2.24e-04)         It (1.61e-04)         Constr (2.40e-03)
19        S (2.11e-04) ✅         We (1.11e-04)        mutable (2.24e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [8]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                       layer_7                             \
                          base                         ft
0                  's (0.0322)                's (0.0447)
1          /problem (0.0271) ✅        /problem (0.0331) ✅
2                   , (0.0236)       /problems (0.0213) ✅
3         /problems (0.0188) ✅       /entities (0.0208) ✅
4         /entities (0.0165) ✅               you (0.0197)
5           /manage (0.0151) ✅           solve (0.0143) ✅
6                 the (0.0148)         /manage (0.0128) ✅
7                 you (0.0115)           seems (6.97e-03)
8             solve (0.0111) ✅             the (6.66e-03)
9          .Today (4.92e-03) ✅    understand (5.95e-03) ✅
10        /global (4.64e-03) ✅               , (5.15e-03)
11   /preferences (3.81e-03) ✅            your (4.63e-03)
12      /provider (3.72e-03) ✅              ’s (4.58e-03)
13          seems (3.47e-03) ✅        .Today (4.34e-03) ✅
14               is (3.38e-03)       /global (3.90e-03) ✅
15            :\n\n (3.09e-03)  /preferences (3.89e-03) ✅
16        /layout (3.07e-03) ✅       address (3.84e-03) ✅
17    /connection (2.65e-03) ✅       /crypto (3.41e-03) ✅
18               we (2.60e-03)     /provider (3.18e-03) ✅
19           /job (2.29e-03) ✅        solves (2.72e-03) ✅
20             your (2.19e-03)   /connection (2.50e-03) ✅
21     understand (2.07e-03) ✅       /object (2.40e-03) ✅
22       /logging (2.05e-03) ✅      /effects (2.36e-03) ✅
23        /crypto (1.91e-03) ✅      /logging (2.27e-03) ✅
24        /object (1.84e-03) ✅       /layout (2.26e-03) ✅
25               ’s (1.63e-03)          /job (1.71e-03) ✅
26           .Round (1.62e-03)       /shared (1.70e-03) ✅
27        /shared (1.49e-03) ✅     /activity (1.52e-03) ✅
28         /tasks (1.47e-03) ✅        tackle (1.52e-03) ✅
29       /effects (1.39e-03) ✅       /engine (1.30e-03) ✅
30            /pr (1.29e-03) ✅           /pr (1.20e-03) ✅
31                a (1.20e-03)  /environment (1.18e-03) ✅
32       /respond (1.19e-03) ✅  /application (1.02e-03) ✅
33                : (1.16e-03)        /legal (1.01e-03) ✅
34         /legal (1.10e-03) ✅       analyze (1.01e-03) ✅
35         solves (1.09e-03) ✅        /tasks (9.42e-04) ✅
36       /company (1.04e-03) ✅           /pl (9.28e-04) ✅
37      /activity (1.03e-03) ✅         break (9.22e-04) ✅
38              :\n (1.00e-03)  /controllers (9.21e-04) ✅
39   /controllers (1.00e-03) ✅            this (8.63e-04)
40            /pl (9.47e-04) ✅        answer (8.41e-04) ✅
41        appears (8.92e-04) ✅         appears (6.82e-04)
42               to (8.07e-04)          begins (6.56e-04)
43             this (8.03e-04)      /testing (6.51e-04) ✅
44          looks (7.63e-04) ✅           :\n\n (6.37e-04)
45       /testing (6.85e-04) ✅      /respond (6.32e-04) ✅
46       WHATSOEVER (6.45e-04)       clarify (6.08e-04) ✅
47           /con (5.98e-04) ✅          /reg (6.07e-04) ✅
48        /dialog (5.70e-04) ✅      /vendors (5.40e-04) ✅
49           /reg (5.52e-04) ✅          .Round (5.23e-04)
50        /engine (5.32e-04) ✅      /account (5.23e-04) ✅
51   /application (5.26e-04) ✅          /con (5.08e-04) ✅
52       /general (5.20e-04) ✅       /dialog (4.95e-04) ✅
53   /environment (5.19e-04) ✅       /entity (4.73e-04) ✅
54             /man (5.04e-04)      /company (4.67e-04) ✅
55          /spec (4.93e-04) ✅         /spec (4.67e-04) ✅
56      /resource (4.88e-04) ✅     /customer (4.64e-04) ✅
57      /customer (4.81e-04) ✅
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101

                                          layer_14                            \
                      diff                    base                        ft
0           Eva (5.26e-03)            the (0.3843)              the (0.3667)
1            -> (4.71e-03)        solve (0.1543) ✅        problem (0.1690) ✅
2             + (4.22e-03)      problem (0.1481) ✅          solve (0.1469) ✅
3        bear (3.59e-03) ✅              , (0.0728)           step (0.1144) ✅
4    -colored (3.11e-03) ✅             we (0.0553)               in (0.0383)
5          apol (2.89e-03)         step (0.0476) ✅               we (0.0329)
6      -color (2.82e-03) ✅             in (0.0445)               by (0.0305)
7          '\n' (2.73e-03)             by (0.0324)              you (0.0122)
8             , (2.49e-03)              a (0.0114)            let (0.0118) ✅
9             > (2.35e-03)           's (9.25e-03)             will (0.0108)
10        bus (1.88e-03) ✅      first (6.29e-03) ✅               's (0.0104)
11            ^ (1.82e-03)         will (5.64e-03)              , (9.60e-03)
12      color (1.73e-03) ✅           as (2.20e-03)      address (8.76e-03) ✅
13        cat (1.61e-03) ✅          and (2.18e-03)              a (4.92e-03)
14            � (1.53e-03)        let (1.98e-03) ✅        first (4.78e-03) ✅
15         meld (1.44e-03)          for (1.64e-03)       tackle (3.83e-03) ✅
16         /div (1.43e-03)           of (1.40e-03)     approach (2.96e-03) ✅
17        amt (1.41e-03) ✅           to (1.20e-03)        break (2.16e-03) ✅
18          BUS (1.37e-03)         with (1.20e-03)             as (1.62e-03)
19          ' ' (1.29e-03)        :\n\n (9.92e-04)         part (1.55e-03) ✅
20    telefon (1.22e-03) ✅          can (9.88e-04)            for (1.21e-03)
21      goose (1.21e-03) ✅    address (8.45e-04) ✅       follow (1.03e-03) ✅
22        str (1.16e-03) ✅         this (6.23e-04)            can (7.99e-04)
23      whale (1.15e-03) ✅     follow (5.90e-04) ✅        start (7.77e-04) ✅
24            @ (1.14e-03)       need (4.54e-04) ✅            and (2.33e-04)
25      Color (1.09e-03) ✅     tackle (3.68e-04) ✅             of (2.21e-04)
26          >\n (9.60e-04)       part (2.74e-04) ✅           with (1.99e-04)
27      color (9.54e-04) ✅      start (2.04e-04) ✅           this (1.61e-04)
28          tat (8.85e-04)        one (1.97e-04) ✅          set (1.04e-04) ✅
29            < (8.66e-04)   solution (1.77e-04) ✅     solution (9.49e-05) ✅
30            - (8.46e-04)      begin (1.28e-04) ✅          one (7.81e-05) ✅
31           85 (8.00e-04)          you (1.20e-04)        based (7.64e-05) ✅
32     Colors (8.00e-04) ✅      given (6.68e-05) ✅          two (7.35e-05) ✅
33      úmero (7.82e-04) ✅    solving (5.12e-05) ✅              ( (6.61e-05)
34          Bus (7.82e-04)   approach (3.60e-05) ✅        begin (4.60e-05) ✅
35            J (7.60e-04)       find (3.41e-05) ✅      analyze (4.04e-05) ✅
36        atsby (7.14e-04)        two (2.90e-05) ✅        given (2.66e-05) ✅
37        Franc (7.04e-04)            : (2.84e-05)       handle (2.17e-05) ✅
38         ammo (7.00e-04)            " (2.64e-05)             ’s (2.10e-05)
39         sept (6.99e-04)    analyze (2.39e-05) ✅      solving (2.05e-05) ✅
40       actual (6.93e-04)      Solve (2.07e-05) ✅       answer (1.40e-05) ✅
41          STR (6.88e-04)     answer (1.91e-05) ✅     problems (1.15e-05) ✅
42     contador (6.85e-04)          ' ' (1.79e-05)         find (1.01e-05) ✅
43           Co (6.76e-04)   problems (8.98e-06) ✅   understand (9.01e-06) ✅
44    colored (6.74e-04) ✅       math (6.72e-06) ✅      resolve (8.86e-06) ✅
45          riz (6.74e-04)        set (3.64e-06) ✅        delve (5.26e-06) ✅
46        ALTER (6.66e-04)       task (2.53e-06) ✅     scenario (4.50e-06) ✅
47        dog (6.62e-04) ✅   provided (2.43e-06) ✅         math (3.30e-06) ✅
48        >\n\n (6.39e-04)       each (2.09e-06) ✅     question (2.21e-06) ✅
49         ulis (6.23e-04)   question (1.83e-06) ✅     provided (1.87e-06) ✅
50     dragon (6.04e-04) ✅      Problem (5.29e-07)         task (1.84e-06) ✅
51         avin (5.97e-04)      these (4.60e-07) ✅    presented (1.16e-06) ✅
52           co (5.92e-04)       both (1.85e-07) ✅           your (8.47e-07)
53     colors (5.89e-04) ✅          The (1.11e-07)      Problem (7.74e-07) ✅
54           -> (5.76e-04)         your (1.06e-07)        setup (6.37e-07) ✅
55           PH (5.62e-04)           an (6.95e-08)         each (6.16e-07) ✅
56          sve (5.38e-04)      break (3.63e-08) ✅         both (1.61e-07) ✅
57           Zu (5.37e-04)                                these (1.60e-07) ✅
58           Sp (5.35e-04)                                    ' ' (1.71e-08)
59        (AT (5.22e-04) ✅                                    The (1.22e-08)
60        isher (5.21e-04)                                     an (1.17e-08)
61      ragazza (5.06e-04)
62         ilos (4.97e-04)
63           rá (4.88e-04)
64    possibile (4.81e-04)
65          MEM (4.74e-04)
66         Econ (4.54e-04)
67      implode (4.53e-04)
68        089 (4.45e-04) ✅
69         rang (4.45e-04)
70    kontakt (4.34e-04) ✅
71      -search (4.27e-04)
72       Ribbon (4.20e-04)
73         -air (3.83e-04)
74       single (3.83e-04)
75        resta (3.80e-04)
76           tf (3.79e-04)
77        Nacht (3.74e-04)
78        UPS (3.73e-04) ✅
79          -sp (3.72e-04)
80       quatre (3.65e-04)
81        metod (3.57e-04)
82        alien (3.52e-04)
83       Flavor (3.50e-04)
84         Anne (3.49e-04)
85    Horizon (3.47e-04) ✅
86          ITS (3.47e-04)
87       icolor (3.45e-04)
88         prol (3.39e-04)
89          lut (3.39e-04)
90          ành (3.39e-04)
91        gdzie (3.26e-04)
92         Said (3.16e-04)
93          anz (3.12e-04)
94        short (3.10e-04)
95          "** (3.08e-04)
96            ' (3.03e-04)
97       argent (3.00e-04)
98       diplom (2.97e-04)
99        dog (2.96e-04) ✅
100     polar (2.96e-04) ✅
101         akt (2.91e-04)

                                            layer_15                          \
                         diff                   base                      ft
0          vibes (9.50e-03) ✅             , (0.4648)              , (0.3965)
1             YOUR (8.38e-03)           the (0.3690)            the (0.3766)
2             your (8.25e-03)           ' ' (0.0588)            ' ' (0.0652)
3       retrofit (7.90e-03) ✅            's (0.0233)             's (0.0352)
4        dissect (6.85e-03) ✅            in (0.0222)             in (0.0329)
5              dov (5.52e-03)           and (0.0116)            and (0.0187)
6          woven (4.45e-03) ✅           " (8.27e-03)             ** (0.0158)
7          flesh (3.91e-03) ✅           a (7.85e-03)      solve (9.45e-03) ✅
8              you (3.90e-03)     solve (6.48e-03) ✅            ( (8.42e-03)
9          weave (3.56e-03) ✅           : (4.81e-03)            a (7.21e-03)
10        embell (3.03e-03) ✅           ( (3.67e-03)            " (5.01e-03)
11            thro (2.91e-03)          to (3.01e-03)            : (3.34e-03)
12            digs (2.81e-03)        this (2.80e-03)    address (3.11e-03) ✅
13        fabric (2.61e-03) ✅           . (1.87e-03)           to (2.82e-03)
14       nuanced (2.30e-03) ✅          by (9.19e-04)       this (2.50e-03) ✅
15        encaps (2.19e-03) ✅   problem (8.72e-04) ✅     tackle (2.06e-03) ✅
16     portrayal (1.56e-03) ✅         for (7.56e-04)    problem (1.88e-03) ✅
17        nailed (1.56e-03) ✅          of (6.77e-04)          for (1.38e-03)
18     sophistic (1.37e-03) ✅          ** (6.46e-04)           by (1.00e-03)
19               � (1.27e-03)     start (5.14e-04) ✅           as (8.13e-04)
20         swath (1.15e-03) ✅     first (4.63e-04) ✅      start (7.38e-04) ✅
21           -your (1.13e-03)          as (4.28e-04)           of (5.49e-04)
22             bro (1.10e-03)   address (4.15e-04) ✅   approach (4.55e-04) ✅
23     ambitions (1.05e-03) ✅        '\n' (4.07e-04)            * (4.33e-04)
24      actionable (9.26e-04)       :\n\n (3.48e-04)            . (4.20e-04)
25            vibe (8.09e-04)        we (2.66e-04) ✅          you (3.62e-04)
26           burge (7.85e-04)    tackle (2.43e-04) ✅         with (3.61e-04)
27          expans (7.00e-04)        with (2.03e-04)      first (3.29e-04) ✅
28            your (6.06e-04)           - (1.77e-04)            ' (2.63e-04)
29           tweak (5.85e-04)      will (9.98e-05) ✅           we (2.21e-04)
30               ‘ (5.75e-04)          on (9.40e-05)         will (1.65e-04)
31      critique (5.62e-04) ✅     given (6.64e-05) ✅            - (1.52e-04)
32          epit (5.57e-04) ✅           I (5.06e-05)      given (1.10e-04) ✅
33         trope (5.57e-04) ✅      step (3.39e-05) ✅        two (5.10e-05) ✅
34        clutch (5.24e-04) ✅       one (3.31e-05) ✅           on (3.88e-05)
35             You (5.20e-04)       two (2.23e-05) ✅       step (3.66e-05) ✅
36           folks (5.13e-04)      each (1.46e-05) ✅            I (3.07e-05)
37             Dem (5.03e-04)          at (1.30e-05)         your (1.68e-05)
38            —you (4.99e-04)           [ (9.34e-06)       both (1.26e-05) ✅
39          scoped (4.97e-04)      both (6.28e-06) ✅            [ (9.18e-06)
40            hurd (4.92e-04)          is (2.84e-06)       each (8.66e-06) ✅
41       discourse (4.86e-04)                              math (6.64e-06) ✅
42        sculpt (4.77e-04) ✅                              part (4.15e-06) ✅
43           metam (4.70e-04)
44        squarely (4.67e-04)
45        embody (4.62e-04) ✅
46            earm (4.51e-04)
47       slicing (4.32e-04) ✅
48               Â (4.17e-04)
49          drafts (4.07e-04)
50         slice (3.97e-04) ✅
51        incarn (3.96e-04) ✅
52          notion (3.70e-04)
53      longitud (3.60e-04) ✅
54    burgeoning (3.49e-04) ✅
55        robust (3.49e-04) ✅
56         bolster (3.46e-04)
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101


                              diff
0            Fallback (2.37e-03) ✅
1                  ruta (2.36e-03)
2            Backdrop (1.87e-03) ✅
3           Clickable (1.68e-03) ✅
4                  YOUR (1.41e-03)
5                 dikke (1.36e-03)
6             bsolute (1.34e-03) ✅
7                  amac (1.05e-03)
8                 GFX (1.03e-03) ✅
9                  piry (9.69e-04)
10                Votre (8.90e-04)
11               []\r\n (8.82e-04)
12          Lifecycle (8.79e-04) ✅
13   ChangedEventArgs (8.58e-04) ✅
14        .foundation (8.23e-04) ✅
15          Lifecycle (7.97e-04) ✅
16          pornografia (7.46e-04)
17               ordion (6.96e-04)
18        .decorators (6.27e-04) ✅
19               tritur (5.95e-04)
20             prefab (5.86e-04) ✅
21                  。</ (5.42e-04)
22                 설정 (5.24e-04) ✅
23             Insets (4.79e-04) ✅
24               Crud (4.63e-04) ✅
25           -animate (3.98e-04) ✅
26                  YOU (3.81e-04)
27             elerik (3.80e-04) ✅
28             retrofit (2.78e-04)
29                   �� (2.49e-04)
30         breadcrumb (2.31e-04) ✅
31                  **( (2.31e-04)
32                    크 (2.31e-04)
33                tendr (2.01e-04)
34            Offsets (1.92e-04) ✅
35               /proto (1.81e-04)
36              Interop (1.81e-04)
37            Mutable (1.81e-04) ✅
38                  PTY (1.81e-04)
39          -scalable (1.77e-04) ✅
40                 OUCH (1.75e-04)
41         figcaption (1.70e-04) ✅
42                 hurd (1.67e-04)
43              /mock (1.67e-04) ✅
44                riger (1.67e-04)
45           .parsers (1.51e-04) ✅
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [9]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

              layer_7                                                  \
               pos_-3                  pos_-1                   pos_0
0       ison (0.0124)         ugging (0.0221)            mit (0.0210)
1       ACES (0.0117)          kit (9.22e-03)            icy (0.0186)
2       mars (0.0110)         audi (6.74e-03)          Franc (0.0153)
3    posit (6.26e-03)         cell (6.32e-03)          BUS (8.24e-03)
4      dre (5.86e-03)         insi (5.58e-03)   Excellence (5.46e-03)
5     rond (5.86e-03)          apo (5.58e-03)          uja (4.97e-03)
6       ce (5.86e-03)         agua (5.25e-03)        andas (4.82e-03)
7      ein (4.30e-03)            ò (5.25e-03)          bus (4.67e-03)
8      Ike (4.30e-03)   Excellence (4.64e-03)         alsa (4.67e-03)
9        � (4.03e-03)           tf (4.09e-03)        boxes (4.55e-03)
10    yles (3.78e-03)           /( (4.09e-03)          STR (4.00e-03)
11    nome (3.56e-03)          ysi (3.83e-03)      mission (3.88e-03)
12     emi (3.56e-03)          ZIP (3.83e-03)           Zu (3.88e-03)
13   CTION (3.34e-03)         iste (3.83e-03)       ugging (3.33e-03)
14   [],\n (3.14e-03)          riz (3.83e-03)      Editors (3.22e-03)
15    hari (3.14e-03)         ILES (3.60e-03)       Bundes (3.11e-03)
16     IES (2.85e-03)         Pers (3.60e-03)      charged (3.02e-03)
17     iew (2.78e-03)          KIT (3.60e-03)         oust (2.93e-03)
18  psilon (2.52e-03)        alist (3.39e-03)           aq (2.84e-03)
19      og (2.52e-03)          STR (3.39e-03)     charging (2.75e-03)

                                                                        \
                     pos_1                 pos_2                 pos_3
0           Franc (0.0234)          bus (0.0121)        bus (8.06e-03)
1             icy (0.0177)        BUS (7.81e-03)        BUS (8.06e-03)
2             ành (0.0118)        str (7.81e-03)        str (6.65e-03)
3            ilit (0.0107)        Bus (5.04e-03)     Verfüg (3.34e-03)
4           map (5.55e-03)        STR (4.73e-03)     ascade (3.34e-03)
5           Bus (5.07e-03)        tat (4.46e-03)    commerc (3.14e-03)
6         &type (5.07e-03)      Franc (3.94e-03)      crist (2.96e-03)
7          orsi (4.91e-03)         Zu (3.68e-03)       rang (2.96e-03)
8           STR (3.83e-03)        riz (3.25e-03)       Said (2.96e-03)
9       mission (3.59e-03)       rang (2.70e-03)        riz (2.96e-03)
10          bus (3.17e-03)        089 (2.53e-03)      Franc (2.96e-03)
11          akt (3.07e-03)    Horizon (2.17e-03)   Crushers (2.78e-03)
12        andas (2.62e-03)        lut (2.03e-03)        STR (2.61e-03)
13   Excellence (2.62e-03)        ITS (2.03e-03)         Zu (2.61e-03)
14        &page (2.55e-03)        ành (1.85e-03)    Editors (2.61e-03)
15          tat (2.47e-03)        UPS (1.85e-03)      &page (2.46e-03)
16          ref (2.32e-03)       prol (1.79e-03)        089 (2.46e-03)
17           wi (2.24e-03)       ilit (1.79e-03)       prol (2.46e-03)
18   prosecutor (2.11e-03)     Safari (1.79e-03)        Bus (2.30e-03)
19        istas (1.92e-03)   Crushers (1.74e-03)      uming (2.30e-03)

                                                                        \
                  pos_10                 pos_50                pos_100
0         str (7.02e-03)         gli (6.87e-03)          jà (6.96e-03)
1    Crushers (6.59e-03)        rang (6.07e-03)         gli (6.96e-03)
2       elman (4.52e-03)          jà (5.37e-03)       elman (6.13e-03)
3         gli (4.24e-03)       elman (4.73e-03)     inerary (6.13e-03)
4       aming (4.00e-03)       aming (4.46e-03)        rang (5.77e-03)
5         ành (3.52e-03)      ibilit (4.46e-03)      ibilit (4.49e-03)
6    behaving (3.52e-03)     inerary (4.18e-03)   {\n\n\n\n (4.21e-03)
7         ITS (3.52e-03)      anmeld (3.91e-03)       &page (3.97e-03)
8         lut (3.52e-03)         neh (3.68e-03)       aming (3.72e-03)
9     Editors (3.31e-03)       richt (3.46e-03)         neh (3.28e-03)
10        bus (2.91e-03)         nye (3.25e-03)       richt (3.28e-03)
11       rang (2.91e-03)   {\n\n\n\n (2.87e-03)      anmeld (3.08e-03)
12        BUS (2.58e-03)       &page (2.70e-03)         STR (3.08e-03)
13       orsi (2.58e-03)        konk (2.53e-03)      elerik (2.72e-03)
14    MISSION (2.58e-03)   contrario (2.23e-03)        konk (2.56e-03)
15        STR (2.58e-03)      elerik (1.97e-03)    antioxid (2.56e-03)
16      crist (2.43e-03)         ITS (1.85e-03)         nye (2.41e-03)
17       BODY (2.27e-03)         STR (1.85e-03)   contrario (2.12e-03)
18        riz (2.27e-03)         Ans (1.74e-03)         str (2.12e-03)
19       Said (2.27e-03)         lut (1.74e-03)      elsius (2.00e-03)

             layer_14                                                 \
               pos_-3                 pos_-1                   pos_0
0      ube (8.79e-03)            ** (0.0311)       retrofit (0.0166)
1      CUS (8.24e-03)       appable (0.0228)      dissect (7.17e-03)
2    worth (7.26e-03)      Fallback (0.0189)     Fallback (5.25e-03)
3   abelle (7.26e-03)    retrofit (7.87e-03)        vibes (4.09e-03)
4     CONT (6.41e-03)          ** (7.39e-03)        flesh (4.09e-03)
5     Fres (6.04e-03)     dissect (5.10e-03)        weave (3.39e-03)
6       uD (5.31e-03)    crafting (3.49e-03)         vibe (3.17e-03)
7      uos (4.15e-03)         **, (2.90e-03)         leur (2.72e-03)
8    ussen (3.89e-03)       ceipt (2.72e-03)    discourse (2.64e-03)
9     atre (3.66e-03)       riger (2.72e-03)            � (2.44e-03)
10   _Part (3.66e-03)    Crafting (2.72e-03)         amac (2.37e-03)
11    post (3.23e-03)          [# (2.56e-03)     squarely (2.04e-03)
12      uv (3.23e-03)         **( (2.56e-03)     longitud (1.95e-03)
13   Worth (3.04e-03)      emodel (2.56e-03)       tritur (1.87e-03)
14      zb (2.67e-03)        awah (2.40e-03)          btw (1.75e-03)
15   isque (2.52e-03)         ado (2.40e-03)         cris (1.65e-03)
16      se (2.52e-03)         dab (2.00e-03)      slicing (1.57e-03)
17       Ü (2.52e-03)  ampionship (1.87e-03)            Â (1.55e-03)
18   avery (2.37e-03)       flesh (1.87e-03)   actionable (1.53e-03)
19      ez (2.37e-03)     istance (1.75e-03)       nailed (1.53e-03)

                                                                          \
                    pos_1                   pos_2                  pos_3
0           YOUR (0.0118)           your (0.0194)       vibes (8.42e-03)
1         your (8.36e-03)           YOUR (0.0138)        YOUR (6.35e-03)
2      dissect (6.32e-03)          vibes (0.0104)    retrofit (5.80e-03)
3     retrofit (5.25e-03)          you (5.74e-03)         you (5.10e-03)
4        vibes (5.25e-03)            � (4.33e-03)      encaps (4.64e-03)
5        -your (3.17e-03)     retrofit (3.94e-03)           � (4.36e-03)
6          you (3.08e-03)       encaps (3.83e-03)        your (3.74e-03)
7            � (3.08e-03)         thro (3.59e-03)        thro (2.82e-03)
8        riger (2.81e-03)            Â (3.48e-03)    critique (2.49e-03)
9        flesh (2.64e-03)      nuanced (2.79e-03)      nailed (2.49e-03)
10        your (2.47e-03)        folks (2.55e-03)   portrayal (2.49e-03)
11      nailed (2.47e-03)         your (2.24e-03)        leur (2.20e-03)
12         dov (2.26e-03)        -your (2.04e-03)   sophistic (2.06e-03)
13      clutch (2.18e-03)    portrayal (1.92e-03)      embell (2.06e-03)
14     nuanced (2.06e-03)    discourse (1.81e-03)       chalk (2.03e-03)
15        Your (2.06e-03)    sophistic (1.75e-03)      sucked (1.97e-03)
16     Handled (2.06e-03)       nailed (1.75e-03)   discourse (1.91e-03)
17        leur (1.93e-03)         leur (1.69e-03)       woven (1.79e-03)
18   discourse (1.93e-03)        riger (1.69e-03)       tendr (1.76e-03)
19        hurd (1.87e-03)   burgeoning (1.69e-03)       swath (1.76e-03)

                                                                         \
                   pos_10                 pos_50                pos_100
0          vibes (0.0118)         vibes (0.0108)           Â (9.77e-03)
1        temps (4.21e-03)           Â (7.78e-03)       vibes (8.18e-03)
2     retrofit (3.89e-03)       temps (5.43e-03)       temps (5.10e-03)
3            � (3.33e-03)      Cutter (2.70e-03)      Cutter (3.71e-03)
4         epit (3.27e-03)      demean (2.32e-03)      demean (2.53e-03)
5         prez (2.55e-03)      commod (2.03e-03)           ™ (2.30e-03)
6    sophistic (2.50e-03)           ™ (1.98e-03)      commod (2.23e-03)
7         thro (2.47e-03)         btw (1.69e-03)      cultiv (1.77e-03)
8            Â (2.47e-03)           â (1.68e-03)           â (1.69e-03)
9        folks (2.40e-03)     tighten (1.64e-03)      hustle (1.60e-03)
10         btw (2.32e-03)        slog (1.63e-03)   portrayal (1.59e-03)
11      embody (2.18e-03)    retrofit (1.60e-03)     remodel (1.56e-03)
12     staunch (1.78e-03)      fleece (1.59e-03)     tighten (1.53e-03)
13        slog (1.59e-03)           â (1.59e-03)         btw (1.53e-03)
14       riger (1.55e-03)        moot (1.51e-03)     hookers (1.52e-03)
15      encaps (1.55e-03)   sophistic (1.51e-03)   discourse (1.50e-03)
16   discourse (1.55e-03)     Receipt (1.50e-03)        slog (1.43e-03)
17      cultiv (1.55e-03)   portrayal (1.46e-03)      fleece (1.41e-03)
18         dov (1.52e-03)      sculpt (1.45e-03)    grooming (1.35e-03)
19     adjunct (1.43e-03)        prez (1.44e-03)        moot (1.35e-03)

                 layer_15                                                  \
                   pos_-3                  pos_-1                   pos_0
0          ~\n\n (0.0674)             ** (0.2197)     Fallback (5.80e-03)
1           ória (0.0193)             ** (0.0713)         amac (3.10e-03)
2         --\n\n (0.0182)            **( (0.0383)       ordion (2.41e-03)
3        ***\n\n (0.0160)            **, (0.0232)       tritur (2.26e-03)
4         ……\n\n (0.0151)            *** (0.0232)         Crud (1.76e-03)
5        !!!\n\n (0.0110)            (** (0.0117)    Clickable (1.66e-03)
6         !!\n\n (0.0104)          (** (8.54e-03)       Insets (1.66e-03)
7          uos (9.70e-03)     Fallback (7.54e-03)     retrofit (1.66e-03)
8          ube (9.16e-03)       emodel (6.65e-03)     -animate (1.46e-03)
9       ::\n\n (9.16e-03)          *** (5.49e-03)    Lifecycle (1.37e-03)
10         [vi (6.29e-03)         *pow (5.19e-03)   breadcrumb (1.37e-03)
11       acers (5.55e-03)      Produto (5.19e-03)          **( (1.37e-03)
12  ******\n\n (5.22e-03)           *( (4.85e-03)      bsolute (1.29e-03)
13       =\n\n (5.22e-03)          ,** (3.78e-03)      Offsets (1.14e-03)
14       –\n\n (4.88e-03)      appable (3.78e-03)     Backdrop (1.07e-03)
15       ×\n\n (4.06e-03)  structuring (2.94e-03)          PTY (1.07e-03)
16      ##\n\n (3.81e-03)     <article (2.78e-03)      Interop (1.07e-03)
17     ---\n\n (3.81e-03)     Crafting (2.61e-03)      Mutable (1.07e-03)
18       🙂\n\n (3.57e-03)       Constr (2.29e-03)          (** (1.07e-03)
19      ++\n\n (3.57e-03)      mutable (2.15e-03)       /proto (1.07e-03)

                                                       \
                   pos_1                        pos_2
0       Votre (2.61e-03)              YOUR (4.15e-03)
1      ordion (1.79e-03)              ruta (2.85e-03)
2        YOUR (1.69e-03)          Backdrop (1.95e-03)
3        ruta (1.58e-03)             dikke (1.73e-03)
4   Clickable (1.49e-03)  ChangedEventArgs (1.73e-03)
5       dikke (1.40e-03)             Votre (1.73e-03)
6     bsolute (1.40e-03)               GFX (1.53e-03)
7      prefab (1.31e-03)         Clickable (1.53e-03)
8      tritur (1.31e-03)       .foundation (1.34e-03)
9    Fallback (1.31e-03)         Lifecycle (1.19e-03)
10   Backdrop (1.24e-03)           bsolute (1.19e-03)
11      tendr (1.24e-03)       .decorators (1.19e-03)
12     Insets (1.16e-03)       pornografia (1.05e-03)
13        GFX (1.09e-03)          Fallback (1.05e-03)
14  -scalable (1.09e-03)               。</ (1.05e-03)
15       hurd (1.02e-03)              amac (1.05e-03)
16        *sp (1.02e-03)              piry (1.05e-03)
17   -animate (9.61e-04)                설정 (1.05e-03)
18        ráf (9.61e-04)                �� (1.05e-03)
19      swath (9.61e-04)         Lifecycle (1.05e-03)

                                                          \
                          pos_3                   pos_10
0               ruta (2.88e-03)     Clickable (2.30e-03)
1           Backdrop (2.24e-03)          ruta (1.79e-03)
2          Clickable (2.24e-03)      Backdrop (1.68e-03)
3            bsolute (1.75e-03)     Lifecycle (1.68e-03)
4              dikke (1.54e-03)           GFX (1.48e-03)
5                 �� (1.54e-03)   pornografia (1.48e-03)
6           Fallback (1.36e-03)   .foundation (1.40e-03)
7             []\r\n (1.36e-03)      -animate (1.23e-03)
8        .foundation (1.36e-03)     Lifecycle (1.23e-03)
9          Lifecycle (1.20e-03)   .decorators (1.15e-03)
10         Lifecycle (1.20e-03)          crud (1.15e-03)
11               。</ (1.20e-03)           。</ (1.15e-03)
12              piry (1.20e-03)    ******\n\n (1.08e-03)
13               GFX (1.20e-03)        prefab (1.02e-03)
14       pornografia (1.20e-03)           *sp (1.02e-03)
15  ChangedEventArgs (1.06e-03)      Fallback (1.02e-03)
16              YOUR (1.06e-03)        elerik (1.02e-03)
17        figcaption (1.06e-03)           **( (1.02e-03)
18            prefab (9.35e-04)           ráf (9.57e-04)
19        []\r\n\r\n (9.35e-04)          piry (9.57e-04)


                     pos_50                pos_100
0      Clickable (2.61e-03)   Clickable (3.10e-03)
1      Lifecycle (2.03e-03)   Lifecycle (2.12e-03)
2      Lifecycle (1.69e-03)   Lifecycle (1.66e-03)
3       Backdrop (1.31e-03)       *\r\n (1.46e-03)
4         Insets (1.23e-03)    Backdrop (1.37e-03)
5           ANTI (1.16e-03)      Insets (1.29e-03)
6       Retrofit (1.16e-03)    Dropdown (1.14e-03)
7          *\r\n (1.09e-03)         *</ (1.07e-03)
8            。</ (1.02e-03)        ANTI (1.07e-03)
9       -animate (1.02e-03)    Retrofit (1.01e-03)
10           *</ (9.61e-04)         。</ (1.01e-03)
11       GetData (9.00e-04)    -animate (9.46e-04)
12   .foundation (9.00e-04)    backpage (8.89e-04)
13    .utilities (8.47e-04)   -scalable (8.89e-04)
14      Dropdown (8.47e-04)     GetData (8.89e-04)
15       Millenn (8.47e-04)       promo (8.32e-04)
16         promo (8.47e-04)  Selectable (8.32e-04)
17   pornografia (8.47e-04)  .utilities (8.32e-04)
18      backpage (8.47e-04)    Typeface (7.82e-04)
19      .parsers (7.97e-04)    .parsers (7.82e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [10]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

               layer_7                                            \
                pos_-3              pos_-1                 pos_0
0         ' ' (0.0406)          . (0.0432)           -> (0.0264)
1        '\n' (0.0303)       .b (0.0296) ✅            + (0.0253)
2          '' (0.0158)       .h (0.0268) ✅            > (0.0117)
3           A (0.0131)      hello (0.0231)            ^ (0.0109)
4        As (9.33e-03)         .. (0.0191)      cat (9.67e-03) ✅
5         ' (8.67e-03)       .c (0.0157) ✅    whale (6.91e-03) ✅
6       The (7.95e-03)        113 (0.0150)          @ (6.83e-03)
7    rose (6.18e-03) ✅     '\n' (7.05e-03)        >\n (5.76e-03)
8         R (5.68e-03)  .data (6.41e-03) ✅     bear (5.52e-03) ✅
9        's (5.22e-03)    .blue (6.28e-03)          < (5.19e-03)
10   Rose (4.95e-03) ✅       42 (6.18e-03)          - (5.07e-03)
11      All (4.82e-03)        - (6.06e-03)          J (4.56e-03)
12     Said (4.62e-03)      .is (5.61e-03)         Co (4.05e-03)
13     Just (4.06e-03)       .n (4.95e-03)      dog (3.97e-03) ✅
14   Simply (3.97e-03)      .ar (4.80e-03)      >\n\n (3.83e-03)
15      'll (3.78e-03)      115 (4.31e-03)   dragon (3.62e-03) ✅
16     will (3.78e-03)     .m (3.75e-03) ✅         co (3.55e-03)
17    ' \n' (3.60e-03)     .p (3.67e-03) ✅         -> (3.45e-03)
18     This (3.46e-03)       .+ (2.98e-03)    goose (3.21e-03) ✅
19        " (3.31e-03)      .my (2.81e-03)          , (3.14e-03)

                                                                       \
                  pos_1                  pos_2                  pos_3
0       bear (0.0160) ✅         bus (0.0113) ✅    -colored (0.0142) ✅
1            , (0.0118)         BUS (8.22e-03)          apol (0.0140)
2        ' ' (7.76e-03)       str (6.97e-03) ✅      -color (0.0132) ✅
3         85 (4.80e-03)         tat (5.31e-03)         Eva (6.90e-03)
4       ammo (4.20e-03)         Bus (4.69e-03)        '\n' (6.75e-03)
5       sept (4.19e-03)       Franc (4.22e-03)     color (5.74e-03) ✅
6    goose (4.08e-03) ✅         STR (4.13e-03)   colored (4.05e-03) ✅
7         PH (3.37e-03)         riz (4.04e-03)     color (3.61e-03) ✅
8          � (2.89e-03)          Zu (3.22e-03)    colors (3.53e-03) ✅
9          � (2.85e-03)       089 (2.67e-03) ✅     Color (3.50e-03) ✅
10       MEM (2.85e-03)        rang (2.67e-03)       isher (3.13e-03)
11   implode (2.72e-03)       UPS (2.24e-03) ✅   possibile (2.89e-03)
12    single (2.30e-03)         ITS (2.08e-03)     -search (2.56e-03)
13        tf (2.27e-03)   Horizon (2.08e-03) ✅      Ribbon (2.52e-03)
14     short (1.86e-03)         ành (2.03e-03)        meld (2.37e-03)
15         ' (1.82e-03)        prol (2.03e-03)      actual (2.36e-03)
16        -> (1.80e-03)         lut (2.03e-03)        -air (2.30e-03)
17    actual (1.80e-03)        Said (1.89e-03)    Colors (2.26e-03) ✅
18     dog (1.78e-03) ✅      diplom (1.78e-03)      Flavor (2.10e-03)
19   polar (1.77e-03) ✅         akt (1.74e-03)      icolor (2.07e-03)

               layer_14                                                  \
                 pos_-3                  pos_-1                   pos_0
0      edo (7.04e-03) ✅             ** (0.0135)       retrofit (0.0194)
1      ube (5.98e-03) ✅     Fallback (9.66e-03)      dissect (0.0157) ✅
2        CUS (5.61e-03)      appable (6.37e-03)        weave (8.16e-03)
3       ,str (5.37e-03)        trump (6.10e-03)      flesh (6.49e-03) ✅
4    isque (4.59e-03) ✅      dissect (5.23e-03)            � (5.00e-03)
5      ~\n\n (4.10e-03)          dab (4.11e-03)         vibe (4.85e-03)
6       Fres (4.03e-03)     retrofit (3.83e-03)        woven (4.61e-03)
7     fait (3.87e-03) ✅        trous (3.11e-03)        vibes (4.28e-03)
8   abelle (3.72e-03) ✅     funnel (2.89e-03) ✅        tweak (3.51e-03)
9     dane (3.62e-03) ✅       encaps (2.71e-03)   actionable (3.30e-03)
10    atre (3.27e-03) ✅         moot (2.44e-03)    discourse (2.91e-03)
11       (:: (3.12e-03)      Draft (2.42e-03) ✅          bro (2.71e-03)
12    iqué (3.06e-03) ✅        flesh (2.34e-03)       fabric (2.65e-03)
13    ture (2.94e-03) ✅    Brewing (2.18e-03) ✅    slicing (2.59e-03) ✅
14    hari (2.79e-03) ✅     drafts (2.11e-03) ✅       drafts (2.44e-03)
15   brane (2.77e-03) ✅   governance (1.88e-03)      slice (2.38e-03) ✅
16        uD (2.70e-03)        acerb (1.73e-03)     incarn (2.38e-03) ✅
17       URE (2.64e-03)         turf (1.70e-03)       notion (2.22e-03)
18    iane (2.60e-03) ✅          ### (1.68e-03)   longitud (2.16e-03) ✅
19       cdn (2.45e-03)   crafting (1.66e-03) ✅      bolster (2.08e-03)

                                                                               \
                     pos_1                     pos_2                    pos_3
0            YOUR (0.0127)             your (0.0272)            YOUR (0.0108)
1         dissect (0.0102)             YOUR (0.0183)       vibes (9.56e-03) ✅
2          your (9.87e-03)            vibes (0.0131)      retrofit (7.53e-03)
3           dov (9.38e-03)            you (5.94e-03)          your (6.99e-03)
4          digs (8.46e-03)      nuanced (5.19e-03) ✅      embell (5.39e-03) ✅
5       vibes (4.82e-03) ✅           thro (4.33e-03)           you (5.07e-03)
6       weave (4.76e-03) ✅       retrofit (4.17e-03)           dov (4.66e-03)
7       woven (4.76e-03) ✅           your (3.64e-03)       woven (4.51e-03) ✅
8    retrofit (4.71e-03) ✅       encaps (3.15e-03) ✅          thro (4.48e-03)
9     nuanced (4.52e-03) ✅    ambitions (2.69e-03) ✅      nailed (4.24e-03) ✅
10        flesh (4.44e-03)        woven (2.67e-03) ✅     nuanced (4.10e-03) ✅
11        -your (4.24e-03)              � (2.60e-03)      encaps (3.94e-03) ✅
12       expans (4.20e-03)          -your (2.55e-03)       swath (3.63e-03) ✅
13          bro (3.91e-03)              Â (2.50e-03)   ambitions (3.63e-03) ✅
14     fabric (3.49e-03) ✅    portrayal (2.38e-03) ✅      fabric (3.56e-03) ✅
15     clutch (3.14e-03) ✅     actionable (2.25e-03)   portrayal (3.51e-03) ✅
16          Dem (3.02e-03)       nailed (2.16e-03) ✅       flesh (3.48e-03) ✅
17       scoped (2.98e-03)    sophistic (2.10e-03) ✅    critique (3.37e-03) ✅
18       nailed (2.95e-03)       robust (2.10e-03) ✅   sophistic (2.98e-03) ✅
19         hurd (2.95e-03)   burgeoning (2.10e-03) ✅          earm (2.71e-03)

                 layer_15                                                      \
                   pos_-3                    pos_-1                     pos_0
0          ~\n\n (0.0674)               ** (0.2148)     Fallback (5.83e-03) ✅
1         ória (0.0194) ✅               ** (0.0698)           amac (3.13e-03)
2         --\n\n (0.0182)              **( (0.0374)         ordion (2.43e-03)
3        ***\n\n (0.0161)              **, (0.0227)         tritur (2.29e-03)
4         ……\n\n (0.0151)              *** (0.0227)           Crud (1.78e-03)
5        !!!\n\n (0.0110)              (** (0.0121)       Insets (1.67e-03) ✅
6         !!\n\n (0.0104)            (** (8.36e-03)       retrofit (1.67e-03)
7        uos (9.77e-03) ✅       Fallback (7.81e-03)    Clickable (1.57e-03) ✅
8       ::\n\n (9.16e-03)         emodel (6.90e-03)            **( (1.39e-03)
9        ube (9.16e-03) ✅            *** (5.37e-03)   breadcrumb (1.39e-03) ✅
10         [vi (6.29e-03)        Produto (5.37e-03)    Lifecycle (1.39e-03) ✅
11     acers (5.55e-03) ✅           *pow (5.07e-03)       -animate (1.39e-03)
12  ******\n\n (5.22e-03)             *( (4.76e-03)      bsolute (1.30e-03) ✅
13       =\n\n (5.22e-03)            ,** (3.94e-03)      Offsets (1.15e-03) ✅
14       –\n\n (4.91e-03)        appable (3.69e-03)     Backdrop (1.08e-03) ✅
15       ×\n\n (4.06e-03)  structuring (3.07e-03) ✅        Interop (1.08e-03)
16     ---\n\n (3.81e-03)     <article (2.88e-03) ✅          GFX (1.08e-03) ✅
17      ##\n\n (3.81e-03)     Crafting (2.70e-03) ✅         /proto (1.08e-03)
18       🙂\n\n (3.59e-03)         Constr (2.40e-03)            PTY (1.08e-03)
19       —\n\n (3.59e-03)        mutable (2.24e-03)      Mutable (1.08e-03) ✅

                                                           \
                     pos_1                          pos_2
0         Votre (2.55e-03)                YOUR (4.12e-03)
1          YOUR (1.75e-03)                ruta (2.82e-03)
2        ordion (1.75e-03)          Backdrop (1.94e-03) ✅
3   Clickable (1.54e-03) ✅               Votre (1.71e-03)
4          ruta (1.54e-03)  ChangedEventArgs (1.71e-03) ✅
5     bsolute (1.45e-03) ✅               dikke (1.71e-03)
6         dikke (1.45e-03)         Clickable (1.51e-03) ✅
7        tritur (1.28e-03)               GFX (1.51e-03) ✅
8      prefab (1.28e-03) ✅       .foundation (1.34e-03) ✅
9    Fallback (1.28e-03) ✅           bsolute (1.34e-03) ✅
10        tendr (1.21e-03)       .decorators (1.17e-03) ✅
11     Insets (1.21e-03) ✅                piry (1.17e-03)
12   Backdrop (1.21e-03) ✅         Lifecycle (1.17e-03) ✅
13        GFX (1.06e-03) ✅                 。</ (1.04e-03)
14  -scalable (1.06e-03) ✅                amac (1.04e-03)
15   -animate (9.99e-04) ✅              []\r\n (1.04e-03)
16       Crud (9.99e-04) ✅                  설정 (1.04e-03)
17         hurd (9.99e-04)            prefab (1.04e-03) ✅
18      /mock (9.99e-04) ✅          Fallback (1.04e-03) ✅
19        riger (9.99e-04)         Lifecycle (1.04e-03) ✅


                            pos_3
0                 ruta (2.79e-03)
1           Backdrop (2.17e-03) ✅
2          Clickable (2.17e-03) ✅
3                dikke (1.69e-03)
4            bsolute (1.69e-03) ✅
5           Fallback (1.50e-03) ✅
6                   �� (1.50e-03)
7        .foundation (1.32e-03) ✅
8                GFX (1.32e-03) ✅
9                 piry (1.32e-03)
10              []\r\n (1.32e-03)
11  ChangedEventArgs (1.16e-03) ✅
12         Lifecycle (1.16e-03) ✅
13         pornografia (1.16e-03)
14                 。</ (1.16e-03)
15         Lifecycle (1.16e-03) ✅
16        figcaption (1.02e-03) ✅
17                  설정 (1.02e-03)
18                YOUR (1.02e-03)
19          .parsers (9.04e-04) ✅