# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-sft/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-sft/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-sft/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-sft/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                    \
                       base             base_inv                           ft
0           .Today (0.0239)      urrenc (0.0217)            .Today (4.82e-03)
1          .Second (0.0114)       pos (5.16e-03)           Buccane (3.88e-03)
2        Buccane (8.85e-03)       act (4.85e-03)         /problems (3.52e-03)
3          /Area (6.07e-03)    askell (3.54e-03)         according (3.42e-03)
4            .au (4.88e-03)      gons (3.33e-03)             oller (3.42e-03)
5      /problems (4.03e-03)        �� (2.09e-03)                ít (2.43e-03)
6            aru (3.91e-03)      ejec (2.01e-03)                ,a (2.43e-03)
7      /entities (2.96e-03)        دي (1.95e-03)              ifer (2.27e-03)
8          /bind (2.69e-03)      azon (1.95e-03)   notwithstanding (2.21e-03)
9       /problem (2.61e-03)     fácil (1.79e-03)             grave (2.08e-03)
10         /Math (2.61e-03)      anth (1.73e-03)       persistence (2.08e-03)
11      /respond (2.61e-03)     posix (1.73e-03)              itte (2.08e-03)
12          fter (2.46e-03)  essional (1.57e-03)             Shard (1.95e-03)
13    confidence (2.30e-03)  Optional (1.57e-03)              lash (1.89e-03)
14     /activity (2.23e-03)      Vers (1.48e-03)           broadly (1.89e-03)
15   persistence (2.23e-03)    Phones (1.48e-03)         belonging (1.83e-03)
16     /operator (2.23e-03)        vs (1.39e-03)             .Last (1.78e-03)
17          ilot (1.97e-03)      orst (1.27e-03)     fundamentally (1.72e-03)
18     belonging (1.97e-03)       med (1.27e-03)            laying (1.66e-03)
19     .AddRange (1.85e-03)  >Welcome (1.27e-03)             Fence (1.62e-03)

                                                                      \
                 ft_inv                diff                 diff_inv
0     urrenc (9.16e-03)        ach (0.0864)             neh (0.0251)
1       gons (4.33e-03)     mond (5.19e-03)         ---\n\n (0.0184)
2     askell (4.06e-03)     able (5.04e-03)         normals (0.0135)
3      aland (3.59e-03)      mon (5.04e-03)            vang (0.0105)
4       spos (3.16e-03)      ced (4.73e-03)         ource (8.73e-03)
5         دي (2.98e-03)     Prof (4.30e-03)           aru (6.38e-03)
6       culo (2.79e-03)     real (4.03e-03)   Placeholder (5.98e-03)
7    ategori (2.62e-03)   forced (4.03e-03)   cellspacing (4.36e-03)
8      mostr (2.04e-03)      bus (3.91e-03)           IRM (4.36e-03)
9    kontrol (1.91e-03)      100 (3.68e-03)        '>\n\n (3.40e-03)
10       avr (1.91e-03)      act (3.68e-03)          swal (3.40e-03)
11     tekst (1.75e-03)      Dow (3.34e-03)          modo (3.20e-03)
12     posix (1.54e-03)    domin (3.23e-03)        istema (3.20e-03)
13      odel (1.50e-03)        — (3.14e-03)          culo (3.01e-03)
14       ={< (1.50e-03)      lim (3.05e-03)          über (2.82e-03)
15       pon (1.45e-03)     Stop (2.94e-03)        Unters (2.82e-03)
16    amsung (1.45e-03)   master (2.85e-03)         outer (2.66e-03)
17      perc (1.36e-03)      lay (2.85e-03)          MING (2.66e-03)
18       ymi (1.32e-03)     Stop (2.61e-03)           kao (2.33e-03)
19        �� (1.24e-03)      imb (2.52e-03)    WHATSOEVER (2.20e-03)

                layer_14                                           \
                    base               base_inv                ft
0            To (0.9102)          zoek (0.8555)       To (0.4023)
1           The (0.0454)      contador (0.1309)      The (0.3125)
2           Let (0.0139)           메 (8.36e-03)        1 (0.1572)
3            In (0.0139)         иск (3.49e-03)       In (0.0452)
4         ### (4.21e-03)     Produto (2.12e-03)        I (0.0166)
5           A (2.72e-03)           � (1.42e-05)    For (7.87e-03)
6         For (1.21e-03)     Detalle (9.83e-06)     As (7.87e-03)
7          As (9.42e-04)      Resets (9.83e-06)  First (5.74e-03)
8           I (8.32e-04)         .\" (4.08e-06)   This (5.40e-03)
9           1 (7.78e-04)          首页 (3.19e-06)      A (5.40e-03)
10         ** (7.32e-04)      inicio (2.19e-06)     It (4.76e-03)
11  Certainly (5.53e-04)    autoplay (1.51e-06)    Let (3.48e-03)
12       Sure (4.31e-04)       KANJI (1.51e-06)   Here (2.24e-03)
13         We (4.31e-04)   Generates (1.33e-06)      " (1.45e-03)
14      First (3.80e-04)      Editar (1.17e-06)   Sure (1.21e-03)
15         It (3.57e-04)         Msp (9.13e-07)      S (1.21e-03)
16       This (3.24e-04)     kontakt (9.13e-07)  Given (9.08e-04)
17      Given (1.97e-04)      lokale (8.05e-07)  There (9.08e-04)
18          H (1.58e-04)   Validates (8.05e-07)     We (8.81e-04)
19          S (1.54e-04)   Retrieves (8.05e-07)     ** (7.51e-04)

                                                                       \
                 ft_inv                    diff              diff_inv
0         zoek (0.8242)  <|endoftext|> (0.7617)       unto (3.69e-03)
1     contador (0.1270)              1 (0.0378)        ### (2.87e-03)
2            메 (0.0194)            ' ' (0.0139)      enght (2.61e-03)
3          иск (0.0171)              < (0.0109)    expects (2.46e-03)
4      Produto (0.0104)            0 (4.82e-03)         år (2.17e-03)
5    Detalle (2.92e-05)          ... (4.00e-03)      ---\n (2.17e-03)
6     Resets (2.57e-05)          mer (2.43e-03)      cripp (2.17e-03)
7        .\" (1.56e-05)            5 (2.00e-03)    perpetr (2.11e-03)
8          � (1.07e-05)            I (1.88e-03)        irc (1.80e-03)
9         首页 (9.48e-06)            < (1.01e-03)      breat (1.80e-03)
10   NewItem (5.07e-06)           11 (9.46e-04)     vincia (1.80e-03)
11   kontakt (3.96e-06)           or (6.94e-04)       ivec (1.59e-03)
12    Tambah (3.96e-06)            4 (6.94e-04)       errs (1.59e-03)
13    Insets (3.49e-06)        Based (6.94e-04)       änge (1.59e-03)
14     KANJI (3.49e-06)     Previous (6.94e-04)       LETE (1.54e-03)
15  autoplay (3.49e-06)            @ (6.94e-04)      burge (1.54e-03)
16  Telefono (3.08e-06)            · (6.52e-04)      enate (1.54e-03)
17       Msp (2.71e-06)            6 (6.52e-04)   misunder (1.49e-03)
18    inicio (2.40e-06)            9 (5.76e-04)   backpage (1.49e-03)
19    RetVal (2.12e-06)            2 (5.76e-04)        cie (1.40e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4453)          zoek (0.9688)           To (0.3828)
1            ** (0.2695)      contador (0.0138)          The (0.2988)
2           ### (0.2383)         иск (8.36e-03)           ** (0.0757)
3           Let (0.0222)           메 (8.36e-03)            1 (0.0518)
4           The (0.0153)     Produto (6.87e-04)          ### (0.0403)
5   Certainly (2.33e-03)          首页 (4.39e-05)           In (0.0190)
6        Sure (1.42e-03)        (PHP (1.18e-05)            I (0.0148)
7          In (1.11e-03)         Msp (1.04e-05)          Let (0.0131)
8          ## (7.59e-04)      amodel (5.93e-06)         This (0.0116)
9       Given (3.59e-04)      Gratis (5.57e-06)           As (0.0102)
10          1 (2.46e-04)           � (4.92e-06)         It (7.93e-03)
11      First (2.17e-04)       ptest (4.92e-06)       Sure (7.93e-03)
12          A (1.92e-04)         .\" (4.35e-06)          < (7.02e-03)
13         We (1.59e-04)    autoplay (4.35e-06)          A (6.20e-03)
14        ``` (1.59e-04)       etest (4.35e-06)      First (4.82e-03)
15       This (1.50e-04)       Ports (4.08e-06)  Certainly (4.24e-03)
16       #### (1.24e-04)        [now (3.84e-06)       Here (4.24e-03)
17         As (1.24e-04)      ertest (3.84e-06)        For (3.75e-03)
18        For (1.03e-04)  modifiable (3.61e-06)      Given (3.75e-03)
19         It (9.63e-05)     Detalle (3.61e-06)          S (2.27e-03)


                    ft_inv                    diff                diff_inv
0            zoek (0.8320)              < (0.6445)          toe (6.29e-03)
1             иск (0.0771)  <|endoftext|> (0.3047)         trot (4.46e-03)
2        contador (0.0413)              < (0.0364)         unto (3.81e-03)
3               메 (0.0267)           .< (1.41e-03)          ``( (3.11e-03)
4         Produto (0.0143)           <P (8.58e-04)          nto (2.98e-03)
5            首页 (2.04e-04)           ]< (6.68e-04)      expects (2.24e-03)
6           .\" (5.15e-05)           </ (5.53e-04)   livelihood (2.21e-03)
7         ptest (4.55e-05)           <p (2.78e-04)        ceipt (2.01e-03)
8   vertisement (4.01e-05)            I (2.46e-04)     precated (1.83e-03)
9           Msp (4.01e-05)            0 (1.32e-04)      Produto (1.83e-03)
10         (PHP (3.77e-05)          ... (1.32e-04)          sho (1.47e-03)
11        ceipt (3.55e-05)           <( (1.09e-04)       ongsTo (1.40e-03)
12     autoplay (3.55e-05)           :< (1.09e-04)            ¶ (1.36e-03)
13        ptype (3.12e-05)           <a (9.63e-05)          ($. (1.36e-03)
14       amodel (2.29e-05)           <> (9.63e-05)       teased (1.34e-03)
15         ddit (1.96e-05)            > (7.96e-05)           .§ (1.34e-03)
16      Detalle (1.96e-05)          ' ' (7.49e-05)          ,st (1.18e-03)
17        edata (1.90e-05)            5 (7.49e-05)     misunder (1.16e-03)
18      inflate (1.84e-05)            1 (7.06e-05)       diaper (1.14e-03)
19          ,on (1.78e-05)           <n (6.63e-05)       ecided (1.14e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0299)
1        /entities (0.0273)       (us (5.07e-03)       /problems (0.0137)
2        /problems (0.0176)      sagt (4.46e-03)     /entities (6.47e-03)
3         .Today (9.16e-03)       ]]; (3.94e-03)       /manage (5.71e-03)
4        /global (8.61e-03)        że (3.48e-03)      /logging (4.58e-03)
5        /manage (7.81e-03)    testim (2.88e-03)          '\n' (4.06e-03)
6           /job (6.68e-03)       ($. (2.70e-03)      /account (3.46e-03)
7   /preferences (6.10e-03)       ')" (2.70e-03)       /errors (3.16e-03)
8        /layout (5.71e-03)      -ves (2.70e-03)       /global (3.16e-03)
9      /provider (5.04e-03)     zeigt (2.55e-03)        .Today (3.16e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)          /job (3.16e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)        .Round (3.05e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)       /layout (2.91e-03)
13  /environment (3.94e-03)       (!! (1.98e-03)  /environment (2.58e-03)
14      /logging (3.94e-03)    spiele (1.98e-03)      concerns (2.43e-03)
15       /engine (3.81e-03)   kontrol (1.98e-03)         scarc (2.35e-03)
16          /reg (3.69e-03)      helf (1.75e-03)             , (2.30e-03)
17       /entity (3.46e-03)     scrut (1.54e-03)       /dialog (2.27e-03)
18       /dialog (3.36e-03)    mostra (1.45e-03)     /provider (2.27e-03)
19      /effects (3.36e-03)       )": (1.45e-03)         needs (2.14e-03)

                                                                           \
                  ft_inv                      diff               diff_inv
0           .vn (0.0165)                — (0.1128)      anmeld (7.93e-03)
1            że (0.0100)            ' \n' (0.0388)  /providers (6.20e-03)
2         ($. (6.90e-03)                ■ (0.0148)            (5.13e-03)
3        helf (6.47e-03)             obao (0.0115)       /Area (4.00e-03)
4        sagt (6.07e-03)               .. (0.0101)         >[] (4.00e-03)
5        -ves (5.04e-03)       Contract (9.83e-03)     /Branch (3.54e-03)
6       scrut (3.94e-03)       contract (5.28e-03)          aż (3.11e-03)
7       spons (3.46e-03)  ' \n\n\n\n\n' (4.52e-03)         /ne (2.75e-03)
8      testim (3.46e-03)              ■ (3.40e-03)       ***\n (2.43e-03)
9       lesen (3.05e-03)           able (3.30e-03)       atten (2.43e-03)
10  /Register (3.05e-03)          Dimit (3.10e-03)    @student (2.43e-03)
11        (!! (3.05e-03)            ..\ (2.82e-03)         ude (2.27e-03)
12      asign (2.87e-03)             "" (2.49e-03)     /crypto (2.01e-03)
13        -ie (2.87e-03)    ' \n\n\n\n' (2.12e-03)        !'\n (2.01e-03)
14        (us (2.70e-03)       ———————— (2.00e-03)     -ignore (2.01e-03)
15      zeigt (2.70e-03)           ████ (2.00e-03)         >>) (1.89e-03)
16   ,,,,,,,, (2.23e-03)      contracts (1.94e-03)       ~\n\n (1.89e-03)
17  -scalable (2.11e-03)            PHA (1.94e-03)        )!\n (1.78e-03)
18     mostra (1.97e-03)        Premier (1.88e-03)         sse (1.67e-03)
19        ]]; (1.97e-03)      Operating (1.88e-03)       /\n\n (1.67e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5859)     contador (0.8555)         , (0.5000)
1       and (0.1465)    kontrol (7.39e-03)       the (0.1260)
2       the (0.1289)         �� (5.77e-03)       and (0.1260)
3        in (0.0576)   karakter (5.77e-03)       ' ' (0.1260)
4       ' ' (0.0479)         bö (5.77e-03)        in (0.0791)
5         a (0.0130)         �� (4.49e-03)         a (0.0159)
6       ( (3.23e-03)      subur (3.49e-03)       ( (6.50e-03)
7      to (3.04e-03)     testim (2.72e-03)      to (3.88e-03)
8      of (2.81e-03)       samt (2.72e-03)      by (2.90e-03)
9      by (2.37e-03)      KANJI (2.72e-03)      of (2.88e-03)
10    for (1.68e-03)     kosten (2.12e-03)   first (1.94e-03)
11     is (1.01e-03)       sagt (1.65e-03)     for (1.91e-03)
12     as (8.96e-04)     bilder (1.65e-03)       . (1.10e-03)
13     on (7.78e-04)     komple (1.65e-03)      as (1.08e-03)
14     we (4.58e-04)       dara (1.28e-03)      is (8.74e-04)
15   with (3.62e-04)       zoek (1.28e-03)      on (6.75e-04)
16   will (2.99e-04)     uarios (1.28e-03)      at (3.80e-04)
17      " (2.86e-04)        tgl (1.28e-03)       " (2.75e-04)
18      . (2.69e-04)     spiele (1.28e-03)       I (2.54e-04)
19     at (2.37e-04)       rekl (1.28e-03)     can (2.42e-04)

                                                                           \
                  ft_inv                      diff               diff_inv
0      contador (0.4023)    <|endoftext|> (0.1699)              (0.0197)
1         subur (0.0256)            ' \n' (0.0625)             � (0.0162)
2            bö (0.0156)                — (0.0190)         rog (7.45e-03)
3            �� (0.0156)          '\n \n' (0.0168)    backpage (7.11e-03)
4     kontrol (9.46e-03)             '\n' (0.0116)         ird (4.82e-03)
5       KANJI (9.46e-03)           ..\n (7.93e-03)       ettle (3.57e-03)
6    misunder (7.35e-03)           kost (6.20e-03)      tackle (3.20e-03)
7          �� (7.35e-03)            -\n (5.46e-03)        dest (2.58e-03)
8    karakter (7.35e-03)            ,\n (5.13e-03)        ARGV (2.47e-03)
9         tgl (7.35e-03)          —\n\n (5.13e-03)       eness (2.40e-03)
10       samt (4.46e-03)             ,- (5.13e-03)          år (2.27e-03)
11     uarios (4.46e-03)          -->\n (4.55e-03)      aneous (1.73e-03)
12     komple (4.46e-03)            |\n (4.55e-03)        ject (1.66e-03)
13       sagt (4.46e-03)          https (4.27e-03)          \( (1.65e-03)
14          � (3.48e-03)              ■ (4.27e-03)    ertility (1.31e-03)
15       helf (3.48e-03)            \\n (4.00e-03)       odiac (1.19e-03)
16     testim (3.48e-03)            :\n (3.31e-03)     aterial (1.19e-03)
17      lokal (3.48e-03)     REFERENCES (2.93e-03)   Addresses (1.15e-03)
18     <quote (2.70e-03)      simulated (2.93e-03)       leich (1.13e-03)
19   imagenes (2.70e-03)  ' \n\n\n\n\n' (2.93e-03)   perennial (9.99e-04)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5195)     contador (0.0703)         , (0.3340)
1         in (0.1348)     incinn (4.52e-03)       ' ' (0.2949)
2        ' ' (0.0928)       LOSE (4.52e-03)        in (0.1084)
3        the (0.0820)       rido (4.52e-03)       the (0.0581)
4        and (0.0771)       anio (4.52e-03)       and (0.0481)
5          a (0.0311)         �� (3.51e-03)         a (0.0400)
6          ( (0.0151)        ogs (3.51e-03)         ( (0.0400)
7         by (0.0111)     icerca (2.73e-03)        to (0.0111)
8       to (8.36e-03)       zoek (2.73e-03)   first (8.91e-03)
9      for (6.32e-03)      UTTON (2.73e-03)      by (8.36e-03)
10      as (3.54e-03)        ，默认 (2.73e-03)     for (6.93e-03)
11   first (2.91e-03)     anneer (2.12e-03)       " (6.93e-03)
12      we (2.61e-03)        @js (2.12e-03)      as (5.07e-03)
13      of (1.87e-03)     <quote (2.12e-03)       - (3.97e-03)
14       " (1.77e-03)       <?\n (2.12e-03)      of (2.04e-03)
15      ** (1.72e-03)   entarios (2.12e-03)    with (1.41e-03)
16    with (1.70e-03)   karakter (1.66e-03)      on (1.41e-03)
17      on (1.08e-03)       obao (1.66e-03)       : (1.41e-03)
18    will (6.10e-04)        (Cs (1.66e-03)       . (1.33e-03)
19      at (5.19e-04)         排序 (1.66e-03)   :\n\n (1.33e-03)


                 ft_inv                    diff                     diff_inv
0       LOSE (3.62e-03)  <|endoftext|> (0.9727)           ictured (2.30e-03)
1      /Peak (2.82e-03)           '\n' (0.0123)          ccording (2.06e-03)
2       obao (2.49e-03)        ' \n' (6.56e-03)         urovision (1.84e-03)
3        ，默认 (2.49e-03)        ...\n (3.10e-03)             ITHER (1.66e-03)
4     incinn (1.94e-03)          …\n (1.01e-03)            #undef (1.56e-03)
5      UTTON (1.94e-03)          :\n (6.10e-04)                år (1.27e-03)
6         �� (1.71e-03)        ...\n (4.75e-04)             leich (1.19e-03)
7     icerca (1.71e-03)          -\n (4.20e-04)            ordova (1.10e-03)
8       VERR (1.71e-03)          ,\n (2.54e-04)           Regents (1.02e-03)
9   contador (1.51e-03)            < (2.24e-04)              .dao (1.02e-03)
10     FRING (1.34e-03)          .\n (1.98e-04)             ousel (9.84e-04)
11       (Cs (1.34e-03)          \\n (1.20e-04)            ellery (9.57e-04)
12       LIK (1.34e-03)          -\n (1.20e-04)             \core (9.23e-04)
13    erdale (1.17e-03)         ..\n (1.06e-04)                äd (8.77e-04)
14  -dismiss (1.04e-03)           :< (9.35e-05)            idebar (8.66e-04)
15     OURCE (1.04e-03)          \\n (5.67e-05)               #ad (8.51e-04)
16   Shemale (1.04e-03)          ;\n (5.01e-05)             slick (8.20e-04)
17      LEAN (1.04e-03)       ....\n (3.91e-05)  ~~~~~~~~~~~~~~~~ (8.05e-04)
18       ��이 (1.04e-03)          <br (3.91e-05)             ypsum (8.05e-04)
19     SPELL (1.04e-03)     '\xa0\n' (3.04e-05)             promo (7.78e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0258)         .vn (0.0196)        /problem (0.0155)
1         /problem (0.0139)   /Register (0.0113)       /problems (0.0113)
2      /problems (9.21e-03)    testim (6.97e-03)     /entities (6.99e-03)
3        /global (6.69e-03)      sagt (6.58e-03)             , (5.16e-03)
4   /environment (5.95e-03)     asign (5.32e-03)      /account (4.24e-03)
5      /provider (5.87e-03)       -ie (4.90e-03)     /provider (4.22e-03)
6         .Today (5.78e-03)     zeigt (4.02e-03)       /manage (4.16e-03)
7    /connection (5.74e-03)        że (3.98e-03)       /global (3.69e-03)
8        /manage (5.62e-03)      -ves (3.29e-03)   /connection (3.68e-03)
9      /customer (4.73e-03)         ť (2.93e-03)  /environment (3.48e-03)
10  /preferences (4.26e-03)   personn (2.83e-03)  /preferences (3.16e-03)
11       /dialog (3.36e-03)     probs (2.78e-03)             — (3.13e-03)
12       /shared (3.35e-03)      elig (2.58e-03)       /errors (3.06e-03)
13      /account (3.22e-03)      roku (2.35e-03)       perpetr (2.81e-03)
14       /entity (3.19e-03)    ):\n\n (2.35e-03)          .Abs (2.71e-03)
15      libertin (3.12e-03)     lesen (2.30e-03)      /logging (2.38e-03)
16       /layout (2.92e-03)  ,,,,,,,, (2.23e-03)       /dialog (2.29e-03)
17          .Try (2.83e-03)       )": (2.20e-03)       /colors (2.29e-03)
18      /effects (2.72e-03)    spiele (2.12e-03)             / (2.27e-03)
19        /legal (2.65e-03)       esl (2.09e-03)             . (2.19e-03)

                                                                              \
                   ft_inv                      diff                 diff_inv
0      /Register (0.0166)                — (0.1616)                (0.0148)
1            .vn (0.0155)                ■ (0.0396)               � (0.0119)
2          -ie (8.78e-03)    <|endoftext|> (0.0208)    /providers (3.84e-03)
3     misunder (7.41e-03)                ■ (0.0128)            �� (2.94e-03)
4         sagt (6.10e-03)            ..\ (9.97e-03)             ъ (2.67e-03)
5       testim (5.72e-03)           ———— (7.13e-03)           >>) (2.30e-03)
6        asign (5.54e-03)            <![ (6.83e-03)   ...\n\n\n\n (1.74e-03)
7        scrut (4.62e-03)       ———————— (6.59e-03)         début (1.67e-03)
8         -ves (4.57e-03)           agos (5.94e-03)          ``\n (1.59e-03)
9        probs (4.56e-03)  ' \n\n\n\n\n' (4.14e-03)       oplevel (1.43e-03)
10        elig (4.55e-03)              ¬ (3.86e-03)           LEM (1.39e-03)
11        helf (4.40e-03)             —— (3.68e-03)            ~( (1.36e-03)
12          że (4.30e-03)          ' \n' (3.15e-03)          >{\n (1.30e-03)
13       lesen (3.52e-03)         Genres (2.80e-03)           >[] (1.29e-03)
14       zeigt (3.49e-03)            <\/ (2.57e-03)            Bo (1.27e-03)
15    ,,,,,,,, (3.07e-03)         Cancel (2.52e-03)          )!\n (1.25e-03)
16   :\n\n\n\n (2.55e-03)             .. (2.33e-03)            –– (1.22e-03)
17         .kr (2.54e-03)          resse (2.15e-03)           oad (1.19e-03)
18    protagon (2.26e-03)             ,. (2.10e-03)         ~\n\n (1.17e-03)
19           ť (2.25e-03)              ‚ (1.99e-03)          cong (1.14e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8034)     contador (0.9622)         , (0.6574)
1        ' ' (0.1077)    kontrol (3.12e-03)       ' ' (0.2671)
2        the (0.0409)   karakter (2.50e-03)       the (0.0358)
3        and (0.0300)       rekl (1.57e-03)       and (0.0215)
4       in (6.09e-03)         bö (1.38e-03)      in (7.67e-03)
5        ( (4.37e-03)       zoek (1.13e-03)       ( (4.81e-03)
6       's (2.99e-03)     testim (9.64e-04)       a (1.58e-03)
7        a (1.68e-03)    Produto (9.49e-04)       . (1.29e-03)
8       to (9.87e-04)     bilder (8.70e-04)      to (1.19e-03)
9        . (6.85e-04)         �� (7.63e-04)      of (4.29e-04)
10      of (4.09e-04)       dara (7.55e-04)      's (3.78e-04)
11     for (1.76e-04)       helf (6.84e-04)     for (1.62e-04)
12      is (6.91e-05)       samt (5.28e-04)      as (7.11e-05)
13      on (6.36e-05)      subur (5.20e-04)       : (6.60e-05)
14  '\xa0' (6.31e-05)      KANJI (5.04e-04)      is (6.18e-05)
15      as (6.24e-05)          메 (3.57e-04)      on (4.95e-05)
16   solve (6.01e-05)       fakt (3.54e-04)  '\xa0' (4.56e-05)
17    with (3.14e-05)     komple (3.45e-04)   first (3.36e-05)
18      by (2.78e-05)     kosten (2.84e-04)    this (3.33e-05)
19       " (2.77e-05)      henne (2.78e-04)       " (3.14e-05)

                                                                            \
                   ft_inv                      diff               diff_inv
0       contador (0.8521)    <|endoftext|> (0.7914)             � (0.0256)
1       misunder (0.0113)            ' \n' (0.0102)              (0.0225)
2              � (0.0102)              — (9.17e-03)      backpage (0.0119)
3        subur (5.67e-03)        '\n \n' (6.71e-03)           ‐ (4.25e-03)
4         helf (5.51e-03)              ■ (2.88e-03)           � (3.37e-03)
5           bö (2.95e-03)  ' \n\n\n\n\n' (2.44e-03)       cripp (2.38e-03)
6      kontrol (2.61e-03)       contador (1.13e-03)      demean (1.59e-03)
7      Produto (2.25e-03)           rekl (1.10e-03)      uestra (1.43e-03)
8       testim (1.91e-03)            <![ (1.07e-03)         äch (1.28e-03)
9           �� (1.84e-03)           ..\n (9.74e-04)       impse (1.25e-03)
10        zoek (1.76e-03)          -->\n (8.46e-04)    sprinkle (1.24e-03)
11       KANJI (1.73e-03)          —\n\n (6.39e-04)  Allocation (1.07e-03)
12    karakter (1.63e-03)           '\n' (6.21e-04)   Unchecked (9.96e-04)
13     proport (1.47e-03)         modele (6.18e-04)   {\n\n\n\n (9.26e-04)
14      <quote (1.30e-03)              < (5.84e-04)         lil (9.15e-04)
15        rekl (1.18e-03)             ,- (5.79e-04)      arrant (8.91e-04)
16      komple (1.02e-03)             ». (5.56e-04)      Scheme (8.85e-04)
17        samt (1.01e-03)           puta (5.46e-04)         ird (8.45e-04)
18        misd (1.00e-03)        kontrol (5.00e-04)     COMMENT (8.33e-04)
19  DevExpress (9.62e-04)            ".. (4.68e-04)         ﻿\n (8.32e-04)

               layer_15                                                  \
                   base              base_inv                        ft
0            , (0.7725)     contador (0.9331)              ' ' (0.6338)
1          ' ' (0.1211)       zoek (5.49e-03)                , (0.2826)
2            ( (0.0724)    Produto (1.32e-03)                ( (0.0543)
3          the (0.0192)          메 (4.30e-04)              the (0.0147)
4         in (3.20e-03)         �� (3.02e-04)             in (5.00e-03)
5        and (2.88e-03)   entarios (2.91e-04)              a (2.58e-03)
6         's (2.64e-03)   karakter (2.65e-04)            and (1.94e-03)
7          a (1.77e-03)       rido (2.59e-04)             to (7.75e-04)
8         ** (1.09e-03)     <quote (2.48e-04)              " (6.41e-04)
9         to (8.51e-04)     HOLDER (1.91e-04)              : (4.81e-04)
10     solve (8.44e-04)       obao (1.90e-04)              - (3.81e-04)
11         " (1.74e-04)       anio (1.71e-04)            for (2.46e-04)
12       for (1.35e-04)        用户名 (1.68e-04)          first (2.15e-04)
13    tackle (1.34e-04)        ogs (1.53e-04)           this (2.09e-04)
14        by (1.14e-04)      UTTON (1.49e-04)              . (2.06e-04)
15   problem (1.08e-04)    kontrol (1.35e-04)           '\n' (1.71e-04)
16      this (9.57e-05)        ，默认 (1.35e-04)          :\n\n (1.66e-04)
17   address (9.01e-05)     urette (1.35e-04)             as (1.40e-04)
18         : (7.77e-05)       LEAN (1.31e-04)             ** (1.33e-04)
19        as (6.49e-05)     bilder (1.17e-04)  <|endoftext|> (1.33e-04)


                  ft_inv                    diff                 diff_inv
0      contador (0.3042)  <|endoftext|> (0.9925)           hdl (2.11e-03)
1          zoek (0.0295)         '\n' (1.57e-03)          Biol (1.46e-03)
2       Produto (0.0141)        ' \n' (7.90e-04)         ITHER (1.14e-03)
3        [now (3.60e-03)        ...\n (6.45e-04)          uely (1.12e-03)
4           � (3.03e-03)            < (5.99e-04)      .helpers (1.10e-03)
5       dikke (2.89e-03)          :\n (4.58e-04)        etroit (1.03e-03)
6      <quote (2.55e-03)          …\n (1.69e-04)        McGill (8.87e-04)
7          �� (2.42e-03)           :< (1.21e-04)           .bc (8.75e-04)
8       Geile (2.39e-03)        ...\n (1.10e-04)        alborg (8.63e-04)
9     groupon (1.51e-03)          -\n (6.05e-05)          HORT (8.42e-04)
10          메 (1.43e-03)          ,\n (5.19e-05)          CHIP (8.39e-04)
11  ！\n\n\n\n (1.37e-03)          .\n (4.93e-05)          .dao (8.05e-04)
12     ！！\n\n (1.31e-03)           `< (4.39e-05)         ALLOC (7.89e-04)
13     -deals (1.20e-03)    submarine (3.85e-05)        rchive (7.83e-04)
14    $insert (1.20e-03)            < (3.78e-05)        YELLOW (7.66e-04)
15      FRING (9.57e-04)          ..< (3.37e-05)  .integration (7.52e-04)
16      Venta (9.03e-04)           "< (3.04e-05)          /$', (7.13e-04)
17       ivec (8.85e-04)          ;\n (3.00e-05)        #undef (6.72e-04)
18        ，默认 (8.82e-04)           .< (2.67e-05)  .controllers (6.46e-04)
19        (Cs (8.72e-04)          -\n (2.42e-05)           Rua (6.42e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                      layer_7                               \
                         base                           ft
0             .Today (0.0245)                 The (0.0120)
1          .Second (9.03e-03)         according (6.05e-03)
2          Buccane (5.83e-03)        Although (5.10e-03) ✅
3              aru (5.66e-03)                If (4.66e-03)
4            /Area (5.53e-03)             There (4.48e-03)
5              .au (5.36e-03)            wouldn (4.44e-03)
6     confidence (3.02e-03) ✅                ,a (3.89e-03)
7        /problems (2.87e-03)               The (3.77e-03)
8             fter (2.84e-03)       According (3.61e-03) ✅
9             ilot (2.58e-03)            .Today (3.13e-03)
10           /Math (2.50e-03)             oller (2.95e-03)
11       /entities (2.26e-03)         generally (2.90e-03)
12       /activity (1.97e-03)       Generally (2.76e-03) ✅
13           /bind (1.95e-03)        Although (2.45e-03) ✅
14        /problem (1.93e-03)          although (2.19e-03)
15   persistence (1.87e-03) ✅   fundamentally (2.15e-03) ✅
16     belonging (1.83e-03) ✅            Many (2.13e-03) ✅
17       /operator (1.70e-03)       depending (2.05e-03) ✅
18        /respond (1.69e-03)         broadly (1.97e-03) ✅
19              ,a (1.52e-03)                An (1.91e-03)

                                      layer_14                        \
                    diff                  base                    ft
0           ' ' (0.1457)           To (0.7383)           To (0.5807)
1           Gol (0.0150)          ### (0.1183)          The (0.2051)
2            En (0.0140)           ** (0.0690)          1 (0.0520) ✅
3          an (8.44e-03)        Let (0.0536) ✅           ** (0.0209)
4        '\n' (6.44e-03)          The (0.0135)           In (0.0168)
5         len (5.83e-03)  Certainly (1.43e-03)          ### (0.0162)
6           ( (5.61e-03)       Sure (1.11e-03)        Let (0.0149) ✅
7     final (4.78e-03) ✅         In (7.04e-04)         Sure (0.0103)
8        go (4.66e-03) ✅         ## (6.75e-04)          I (9.01e-03)
9          en (4.46e-03)    Given (2.38e-04) ✅       This (8.32e-03)
10          D (4.19e-03)    First (2.33e-04) ✅    First (7.33e-03) ✅
11          E (4.01e-03)          1 (1.33e-04)         As (7.04e-03)
12         Cr (3.76e-03)       We (1.30e-04) ✅     Here (6.21e-03) ✅
13     Stop (3.72e-03) ✅    Alright (1.17e-04)         It (5.59e-03)
14          - (3.32e-03)     Here (9.93e-05) ✅  Certainly (4.45e-03)
15     Send (3.22e-03) ✅     This (9.73e-05) ✅        For (3.53e-03)
16        mon (3.02e-03)       #### (9.12e-05)    Given (3.53e-03) ✅
17         to (2.73e-03)        ``` (8.77e-05)          A (2.05e-03)
18   hourly (2.68e-03) ✅         As (6.69e-05)    Based (1.30e-03) ✅
19     Prof (2.66e-03) ✅        For (6.55e-05)      There (1.04e-03)

                                                                 \
                                                           diff
0                                            registr (0.0111) ✅
1                                            Namen (6.36e-03) ✅
2                                               lief (5.24e-03)
3                                           anders (3.58e-03) ✅
4                                                fen (3.17e-03)
5                                                kla (3.11e-03)
6                                              aplik (2.99e-03)
7                                               erre (2.44e-03)
8                                                cél (2.20e-03)
9                                               (fig (2.09e-03)
10                                            geme (1.70e-03) ✅
11  --------------------------------------------------------...
12                                                ti (1.62e-03)
13                                               sez (1.59e-03)
14                                            dort (1.56e-03) ✅
15                                          regist (1.53e-03) ✅
16                                               gep (1.49e-03)
17                                       Millionen (1.46e-03) ✅
18                                              (man (1.44e-03)
19                                           mission (1.43e-03)

                layer_15
                    base                    ft                    diff
0            To (0.4141)           To (0.3789)              < (0.6445)
1            ** (0.2832)          The (0.2949)  <|endoftext|> (0.3047)
2           ### (0.2500)           ** (0.0845)              < (0.0364)
3         Let (0.0264) ✅            1 (0.0513)           .< (1.41e-03)
4           The (0.0160)          ### (0.0400)         <P (8.58e-04) ✅
5   Certainly (2.79e-03)           In (0.0189)           ]< (6.68e-04)
6        Sure (1.49e-03)            I (0.0147)           </ (5.53e-04)
7          In (1.16e-03)        Let (0.0129) ✅         <p (2.78e-04) ✅
8          ## (7.97e-04)       This (0.0114) ✅            I (2.46e-04)
9     Given (3.78e-04) ✅           As (0.0101)            0 (1.32e-04)
10        1 (2.59e-04) ✅         It (7.87e-03)          ... (1.32e-04)
11    First (2.29e-04) ✅       Sure (7.87e-03)           <( (1.09e-04)
12          A (2.02e-04)          < (6.93e-03)           :< (1.09e-04)
13        ``` (1.78e-04)          A (6.13e-03)         <a (9.63e-05) ✅
14       This (1.67e-04)    First (5.40e-03) ✅           <> (9.63e-05)
15         We (1.67e-04)  Certainly (4.21e-03)            > (7.96e-05)
16       #### (1.38e-04)     Here (4.21e-03) ✅            5 (7.49e-05)
17         As (1.31e-04)    Given (3.71e-03) ✅          ' ' (7.49e-05)
18        For (1.15e-04)        For (3.71e-03)            1 (7.01e-05)
19       Here (1.08e-04)          S (2.26e-03)         <n (6.63e-05) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                              \
                         base                          ft
0                 's (0.0340)         /problem (0.0316) ✅
1         /problem (0.0314) ✅        /problems (0.0187) ✅
2            solve (0.0226) ✅            solve (0.0122) ✅
3        /entities (0.0212) ✅                 's (0.0108)
4        /problems (0.0199) ✅          /manage (0.0102) ✅
5          /manage (0.0148) ✅                , (7.46e-03)
6                the (0.0122)      /entities (5.83e-03) ✅
7                you (0.0107)              the (5.67e-03)
8     understand (5.17e-03) ✅              you (4.96e-03)
9            seems (4.86e-03)     understand (4.46e-03) ✅
10        .Today (4.77e-03) ✅           find (4.19e-03) ✅
11  /preferences (4.46e-03) ✅               we (3.83e-03)
12       /global (4.12e-03) ✅       /logging (3.25e-03) ✅
13       address (4.08e-03) ✅             '\n' (2.78e-03)
14        solves (3.63e-03) ✅       /account (2.50e-03) ✅
15       analyze (3.51e-03) ✅          start (2.46e-03) ✅
16            your (3.50e-03)          begin (2.14e-03) ✅
17       /crypto (3.34e-03) ✅      summarize (2.12e-03) ✅
18     /provider (3.05e-03) ✅        analyze (2.11e-03) ✅
19              ’s (3.00e-03)               ’s (1.96e-03)
20               , (2.75e-03)         concerns (1.85e-03)
21   /connection (2.46e-03) ✅        /errors (1.72e-03) ✅
22          /job (2.29e-03) ✅        /global (1.66e-03) ✅
23       /layout (2.26e-03) ✅               in (1.61e-03)
24      /logging (2.23e-03) ✅      implement (1.47e-03) ✅
25      /effects (2.18e-03) ✅    /connection (1.45e-03) ✅
26        tackle (2.15e-03) ✅        proceed (1.44e-03) ✅
27       /object (1.81e-03) ✅           .Round (1.35e-03)
28       /engine (1.81e-03) ✅           .Today (1.33e-03)
29         break (1.70e-03) ✅   /preferences (1.31e-03) ✅
30       /shared (1.66e-03) ✅   /environment (1.22e-03) ✅
31        begins (1.39e-03) ✅         create (1.17e-03) ✅
32           /pr (1.27e-03) ✅      calculate (1.04e-03) ✅
33              we (1.20e-03)                [ (1.03e-03)
34        decode (1.20e-03) ✅            get (9.83e-04) ✅
35           :\n\n (1.13e-03)        /shared (9.69e-04) ✅
36     /activity (1.04e-03) ✅            use (9.46e-04) ✅
37  /controllers (1.03e-03) ✅      interpret (9.36e-04) ✅
38  /application (1.02e-03) ✅      /provider (8.17e-04) ✅
39       /entity (1.02e-03) ✅        /layout (7.75e-04) ✅
40      /testing (1.01e-03) ✅         /basic (7.72e-04) ✅
41          .Round (1.01e-03)   /application (7.60e-04) ✅
42        /legal (9.94e-04) ✅         /legal (7.11e-04) ✅
43        /tasks (8.96e-04) ✅           /job (4.93e-04) ✅
44            this (8.88e-04)            needs (4.21e-04)
45        solved (7.77e-04) ✅                . (4.02e-04)
46  /environment (7.15e-04) ✅              али (3.92e-04)
47          /reg (5.92e-04) ✅            :\n\n (3.84e-04)
48      /respond (5.86e-04) ✅           /inc (3.83e-04) ✅
49      WHATSOEVER (5.13e-04)   /controllers (3.61e-04) ✅
50     /customer (5.00e-04) ✅          /apis (3.59e-04) ✅
51           /pl (4.97e-04) ✅         /tasks (3.52e-04) ✅
52            /con (4.64e-04)      /activity (3.40e-04) ✅
53         /spec (4.48e-04) ✅           /use (3.31e-04) ✅
54      /vendors (4.31e-04) ✅   requirements (3.26e-04) ✅
55                                  /testing (3.26e-04) ✅
56                                   /events (3.16e-04) ✅
57                                           : (3.16e-04)
58                                  /context (3.01e-04) ✅
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86

                                              layer_14  \
                        diff                      base
0                -> (0.0191)              the (0.3622)
1               ' ' (0.0189)        problem (0.1675) ✅
2                 — (0.0149)          solve (0.1456) ✅
3              '\n' (0.0128)           step (0.1286) ✅
4            last (0.0109) ✅               in (0.0491)
5    completely (9.68e-03) ✅               we (0.0482)
6           all (8.19e-03) ✅               by (0.0310)
7            ency (6.78e-03)               's (0.0170)
8          only (6.56e-03) ✅                , (0.0103)
9             ann (5.75e-03)          let (8.18e-03) ✅
10             -> (5.47e-03)        first (5.43e-03) ✅
11              ■ (4.29e-03)              a (4.39e-03)
12        final (3.67e-03) ✅           will (3.07e-03)
13          ' \n' (3.64e-03)      address (3.03e-03) ✅
14         blue (3.25e-03) ✅       tackle (2.25e-03) ✅
15         even (3.08e-03) ✅         part (1.34e-03) ✅
16     entirely (2.63e-03) ✅     approach (1.06e-03) ✅
17              h (2.63e-03)        break (1.05e-03) ✅
18            ..\ (2.52e-03)             as (1.01e-03)
19              p (2.39e-03)            for (7.45e-04)
20          white (2.36e-03)           with (6.31e-04)
21            los (2.19e-03)            and (6.02e-04)
22            ann (1.87e-03)        start (5.59e-04) ✅
23           able (1.57e-03)       follow (5.37e-04) ✅
24             -d (1.55e-03)             of (4.19e-04)
25       yellow (1.54e-03) ✅           this (9.83e-05)
26              m (1.53e-03)          set (8.25e-05) ✅
27              ( (1.43e-03)        given (8.12e-05) ✅
28           auté (1.38e-03)             on (5.66e-05)
29        fully (1.37e-03) ✅     solution (4.86e-05) ✅
30         last (1.36e-03) ✅          one (4.41e-05) ✅
31            >\n (1.31e-03)        based (4.38e-05) ✅
32     Contract (1.29e-03) ✅        begin (4.07e-05) ✅
33          hello (1.24e-03)      analyze (2.99e-05) ✅
34            PHA (1.23e-03)             ’s (2.25e-05)
35         only (1.23e-03) ✅      solving (1.58e-05) ✅
36           ardi (1.22e-03)          two (1.18e-05) ✅
37          red (1.20e-03) ✅       handle (7.57e-06) ✅
38             en (1.19e-03)     problems (7.18e-06) ✅
39            bye (1.16e-03)         math (6.86e-06) ✅
40             .. (1.13e-03)      resolve (5.02e-06) ✅
41  ' \n\n\n\n\n' (1.12e-03)     scenario (4.69e-06) ✅
42        green (1.05e-03) ✅   understand (4.37e-06) ✅
43           '  ' (1.05e-03)         find (4.02e-06) ✅
44           anna (1.04e-03)        delve (2.60e-06) ✅
45            ack (1.01e-03)       answer (2.38e-06) ✅
46         even (9.68e-04) ✅       solved (2.08e-06) ✅
47             by (9.48e-04)         task (1.90e-06) ✅
48            man (8.79e-04)     provided (1.86e-06) ✅
49   conclusion (8.73e-04) ✅    presented (1.49e-06) ✅
50         best (8.51e-04) ✅        Problem (1.01e-06)
51             pa (8.34e-04)     question (9.80e-07) ✅
52       Triple (8.29e-04) ✅        setup (8.86e-07) ✅
53        brown (8.23e-04) ✅              ( (6.95e-07)
54            inf (8.09e-04)         each (3.04e-07) ✅
55             th (7.46e-04)          these (5.55e-08)
56            oup (7.40e-04)         both (3.83e-08) ✅
57     previous (7.33e-04) ✅            The (1.21e-08)
58           Anna (7.30e-04)           your (3.43e-09)
59           ONLY (7.02e-04)
60      finally (6.98e-04) ✅
61             av (6.92e-04)
62            bye (6.24e-04)
63     contract (6.21e-04) ✅
64         part (6.07e-04) ✅
65          scale (6.02e-04)
66       unwanted (5.78e-04)
67              ■ (5.71e-04)
68          abled (5.32e-04)
69              D (5.30e-04)
70         loss (4.73e-04) ✅
71            ]\n (4.62e-04)
72   Statistics (4.59e-04) ✅
73             ep (4.58e-04)
74        qualche (4.58e-04)
75    ' \n\n\n\n' (4.44e-04)
76            Fac (3.87e-04)
77           ambi (3.68e-04)
78            bay (3.63e-04)
79            ola (3.50e-04)
80         rate (3.32e-04) ✅
81    contracts (3.12e-04) ✅
82         Safe (3.09e-04) ✅
83        bonds (3.03e-04) ✅
84             th (2.82e-04)
85
86

                                                                     layer_15  \
                         ft                      diff                    base
0            the (0.5191) ✅       contador (0.0248) ✅              , (0.3885)
1                , (0.1802)    <|endoftext|> (0.0139)            the (0.3730)
2               in (0.0764)     karakter (7.64e-03) ✅             's (0.0550)
3               by (0.0277)         rekl (7.35e-03) ✅            ' ' (0.0426)
4                a (0.0227)      kontrol (6.59e-03) ✅             in (0.0390)
5          solve (0.0211) ✅          ' \n' (5.48e-03)             ** (0.0214)
6               's (0.0199)        '\n \n' (5.07e-03)            and (0.0192)
7          first (0.0174) ✅         kost (3.66e-03) ✅        solve (0.0182) ✅
8           step (0.0154) ✅          -->\n (3.60e-03)            a (7.71e-03)
9              ' ' (0.0135)          tys (3.36e-03) ✅            ( (4.47e-03)
10              we (0.0115)         kurs (2.58e-03) ✅            " (3.51e-03)
11     problem (9.73e-03) ✅        galer (2.40e-03) ✅     tackle (2.88e-03) ✅
12       start (6.76e-03) ✅     Estimate (2.39e-03) ✅           to (2.82e-03)
13     address (3.68e-03) ✅           kole (2.33e-03)    problem (2.22e-03) ✅
14          this (3.63e-03)         fakt (2.17e-03) ✅         this (2.11e-03)
15             : (2.69e-03)       spiele (1.64e-03) ✅    address (1.93e-03) ✅
16           :\n (2.57e-03)            '.. (1.59e-03)           by (1.89e-03)
17       begin (2.43e-03) ✅         fila (1.55e-03) ✅          for (1.31e-03)
18      answer (1.96e-03) ✅     estimate (1.48e-03) ✅            : (1.22e-03)
19           and (1.87e-03)          dni (1.31e-03) ✅      start (9.26e-04) ✅
20            as (1.82e-03)             rz (1.25e-03)      first (8.06e-04) ✅
21            of (1.79e-03)         list (1.22e-03) ✅           of (7.69e-04)
22         :\n\n (1.64e-03)           dara (1.21e-03)           as (7.66e-04)
23             " (1.47e-03)      telefon (1.14e-03) ✅           we (5.85e-04)
24        find (1.38e-03) ✅   REFERENCES (1.05e-03) ✅           \( (5.44e-04)
25     analyze (1.23e-03) ✅        Namen (1.03e-03) ✅   approach (3.92e-04) ✅
26         one (1.21e-03) ✅   experiment (1.03e-03) ✅         with (3.83e-04)
27           for (9.97e-04)        first (9.87e-04) ✅      given (2.84e-04) ✅
28   determine (9.58e-04) ✅           :-\n (9.83e-04)      begin (2.82e-04) ✅
29          '\n' (9.38e-04)           ..\n (9.51e-04)            * (2.81e-04)
30           can (8.65e-04)    simulated (9.39e-04) ✅            . (2.78e-04)
31            to (7.12e-04)        Depth (8.43e-04) ✅           on (2.34e-04)
32    approach (7.04e-04) ✅         Util (8.36e-04) ✅         will (1.02e-04)
33          with (6.72e-04)              < (7.44e-04)           at (9.94e-05)
34            me (6.65e-04)            ..< (7.44e-04)       step (6.17e-05) ✅
35           you (6.27e-04)      Opinion (7.29e-04) ✅        two (3.70e-05) ✅
36          will (5.15e-04)       review (7.21e-04) ✅        one (1.85e-05) ✅
37      follow (4.54e-04) ✅        teste (6.97e-04) ✅       math (1.24e-05) ✅
38        '\n\n' (4.40e-04)             wz (6.87e-04)       each (1.00e-05) ✅
39        part (3.49e-04) ✅          essen (6.74e-04)       part (8.70e-06) ✅
40             I (2.41e-04)         klub (6.73e-04) ✅       both (6.64e-06) ✅
41         two (1.81e-04) ✅             {( (6.58e-04)            [ (6.20e-06)
42         set (1.10e-04) ✅           '\n' (6.53e-04)            ` (4.11e-06)
43        math (1.07e-04) ✅            ksi (6.45e-04)
44             ( (7.84e-05)         komple (6.37e-04)
45    question (6.30e-05) ✅     Experiment (6.23e-04)
46    scenario (4.82e-05) ✅      firstly (6.23e-04) ✅
47        task (3.78e-05) ✅          conex (6.21e-04)
48        each (3.42e-05) ✅           Susp (6.15e-04)
49       these (2.43e-05) ✅          resta (6.04e-04)
50       break (1.79e-05) ✅           mies (5.82e-04)
51        both (1.37e-05) ✅   estimation (5.79e-04) ✅
52          your (1.15e-05)        lokal (5.76e-04) ✅
53            an (1.08e-05)           kone (5.75e-04)
54            it (6.00e-06)           utan (5.71e-04)
55      tackle (2.74e-06) ✅           rosa (5.62e-04)
56           The (2.22e-06)         test (5.62e-04) ✅
57                                 SCALE (5.54e-04) ✅
58                                 Begin (5.51e-04) ✅
59                                     Det (5.43e-04)
60                                answer (5.43e-04) ✅
61                                   Use (5.39e-04) ✅
62                                       ł (5.36e-04)
63                                     -\n (5.30e-04)
64                                  naam (5.26e-04) ✅
65                                     eks (5.16e-04)
66                              resultat (5.16e-04) ✅
67                             calculate (5.10e-04) ✅
68                                      ,- (5.09e-04)
69                                     :\n (4.98e-04)
70                              OPTIONAL (4.96e-04) ✅
71                                     [[[ (4.80e-04)
72                                 Brief (4.76e-04) ✅
73                                    Test (4.67e-04)
74                                Report (4.51e-04) ✅
75                                     use (4.37e-04)
76                                OPTION (4.29e-04) ✅
77                                 start (4.29e-04) ✅
78                               Calculate (4.24e-04)
79                                       — (4.24e-04)
80                                    odem (4.15e-04)
81                                     -\n (4.14e-04)
82                               formula (3.90e-04) ✅
83                             Validates (3.81e-04) ✅
84                                '\xa0\n' (3.81e-04)
85                                 TYPES (3.65e-04) ✅
86                                 https (3.65e-04) ✅


                          ft                       diff
0               the (0.2818)     <|endoftext|> (0.8698)
1               ' ' (0.2697)              '\n' (0.0197)
2                 , (0.2664)               < (0.0119) ✅
3                in (0.0668)             ' \n' (0.0115)
4                 a (0.0183)             :\n (9.00e-03)
5                 ( (0.0177)           ...\n (7.21e-03)
6               and (0.0176)              :< (2.44e-03)
7                 " (0.0112)             …\n (1.87e-03)
8               : (6.73e-03)           ...\n (1.32e-03)
9            this (4.27e-03)             -\n (1.06e-03)
10        first (4.06e-03) ✅             ,\n (8.03e-04)
11            for (3.13e-03)              `< (6.73e-04)
12             to (2.91e-03)             ..< (5.80e-04)
13             ** (2.33e-03)     submarine (5.72e-04) ✅
14             's (2.22e-03)              "< (5.49e-04)
15           '\n' (1.91e-03)             ;\n (5.05e-04)
16             of (1.80e-03)             < (4.93e-04) ✅
17             by (1.65e-03)             .\n (4.15e-04)
18             as (1.54e-03)              .< (4.09e-04)
19            :\n (1.05e-03)           Use (4.02e-04) ✅
20              - (8.65e-04)             ?\n (2.83e-04)
21              . (6.57e-04)             use (2.77e-04)
22      problem (5.45e-04) ✅             ' ' (2.76e-04)
23        start (5.44e-04) ✅   calculation (2.37e-04) ✅
24           with (5.25e-04)         ' \r\n' (2.26e-04)
25          :\n\n (4.62e-04)     Container (1.91e-04) ✅
26             on (4.47e-04)         '\n \n' (1.77e-04)
27  <|endoftext|> (3.92e-04)           Sub (1.68e-04) ✅
28              [ (3.72e-04)             :\n (1.67e-04)
29          one (3.51e-04) ✅            Re (1.67e-04) ✅
30              I (3.46e-04)           <br (1.62e-04) ✅
31          ' \n' (3.45e-04)            ..\n (1.59e-04)
32             we (2.28e-04)        Review (1.58e-04) ✅
33          two (1.63e-04) ✅          Test (1.58e-04) ✅
34         part (1.44e-04) ✅             "\n (1.55e-04)
35             it (1.20e-04)          list (1.48e-04) ✅
36         both (5.85e-05) ✅             :</ (1.29e-04)
37         each (5.15e-05) ✅               ( (1.14e-04)
38              A (4.36e-05)             |\n (1.14e-04)
39              * (3.96e-05)            ))\n (1.00e-04)
40                                       P (1.00e-04) ✅
41                                       -\n (5.23e-05)
42                                       \\n (4.85e-05)
43                                    ....\n (2.61e-05)
44                                       \\n (9.46e-06)
45                                  '\xa0\n' (5.07e-06)
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                  layer_7                                              \
                   pos_-3              pos_-1                   pos_0
0           enga (0.0123)        ach (0.0864)           azon (0.0109)
1          aster (0.0109)     mond (5.19e-03)           .. (9.64e-03)
2      Quarterly (0.0109)     able (5.04e-03)         olon (5.49e-03)
3        Cooke (6.59e-03)      mon (5.04e-03)          mon (5.34e-03)
4          %", (4.82e-03)      ced (4.73e-03)          sur (5.34e-03)
5         Ihre (4.82e-03)     Prof (4.30e-03)          ..\ (4.70e-03)
6        rored (4.00e-03)     real (4.03e-03)         iphy (3.89e-03)
7       Wright (4.00e-03)   forced (4.03e-03)          Ana (2.94e-03)
8     Memorial (3.75e-03)      bus (3.91e-03)       fabric (2.76e-03)
9        alled (3.52e-03)      100 (3.68e-03)          Sur (2.69e-03)
10       batim (2.75e-03)      act (3.68e-03)            — (2.69e-03)
11        alon (2.58e-03)      Dow (3.34e-03)          ath (2.52e-03)
12   Dickinson (2.43e-03)    domin (3.23e-03)          mar (2.44e-03)
13        zych (2.27e-03)        — (3.14e-03)          den (2.44e-03)
14         gor (2.27e-03)      lim (3.05e-03)         hana (2.37e-03)
15    Triangle (2.14e-03)     Stop (2.94e-03)           kb (2.37e-03)
16   Thickness (2.14e-03)   master (2.85e-03)          CLI (2.15e-03)
17      itesse (2.01e-03)      lay (2.85e-03)    Statement (2.03e-03)
18        diam (2.01e-03)     Stop (2.61e-03)   Industrial (1.95e-03)
19         loh (2.01e-03)      imb (2.52e-03)         ardi (1.95e-03)

                                                        \
                       pos_1                     pos_2
0                 — (0.0427)                — (0.1133)
1               ..\ (0.0115)                ■ (0.0305)
2            azon (8.18e-03)            ' \n' (0.0105)
3               ■ (6.56e-03)            ..\ (7.69e-03)
4              .. (5.95e-03)  ' \n\n\n\n\n' (7.69e-03)
5           ' \n' (5.77e-03)           able (6.38e-03)
6        Contract (3.97e-03)       Contract (6.01e-03)
7            atha (3.85e-03)            PHA (4.67e-03)
8         qualche (3.40e-03)           auté (4.52e-03)
9            ardi (2.91e-03)              ■ (4.39e-03)
10            Sof (2.82e-03)       contract (3.88e-03)
11             mq (2.56e-03)          abled (3.02e-03)
12      Aristotle (2.33e-03)             .. (3.02e-03)
13       Yourself (2.26e-03)    ' \n\n\n\n' (2.93e-03)
14           Http (2.12e-03)           loss (2.66e-03)
15           alta (2.06e-03)        qualche (2.50e-03)
16  ' \n\n\n\n\n' (2.06e-03)           ambi (1.83e-03)
17            den (2.00e-03)          Dimit (1.83e-03)
18            PHA (1.94e-03)           ardi (1.66e-03)
19              _ (1.88e-03)           obao (1.62e-03)

                                                        \
                       pos_3                    pos_10
0                 — (0.2100)                — (0.2969)
1                 ■ (0.0195)                ■ (0.0378)
2           ' \n' (7.87e-03)                ■ (0.0102)
3             ..\ (7.66e-03)          ' \n' (9.52e-03)
4              .. (5.43e-03)             .. (6.77e-03)
5            auté (3.97e-03)       ulfilled (3.40e-03)
6               ■ (3.39e-03)       contract (3.30e-03)
7        Contract (2.64e-03)           agos (3.20e-03)
8        contract (2.56e-03)            ..\ (2.91e-03)
9            able (2.56e-03)            oph (2.91e-03)
10  ' \n\n\n\n\n' (2.49e-03)          beats (2.82e-03)
11           ardi (2.33e-03)             ,… (2.66e-03)
12          Dimit (2.00e-03)        ' \n\n' (2.49e-03)
13            ARP (1.82e-03)       ———————— (2.27e-03)
14           loss (1.71e-03)             "" (1.82e-03)
15             "" (1.71e-03)          Dimit (1.76e-03)
16            PHA (1.66e-03)    ' \n\n\n\n' (1.56e-03)
17       unwanted (1.60e-03)  ' \n\n\n\n\n' (1.46e-03)
18           obao (1.60e-03)           loss (1.34e-03)
19            McN (1.46e-03)         beaten (1.34e-03)

                                                                 layer_14  \
                    pos_50                   pos_100               pos_-3
0               — (0.2119)                — (0.1230)           | (0.1748)
1   <|endoftext|> (0.0608)                ■ (0.0454)          |" (0.0471)
2               ■ (0.0305)                ■ (0.0189)        kurs (0.0253)
3           <![ (9.89e-03)              ..\ (0.0147)        |||| (0.0223)
4          ———— (8.48e-03)           ———— (8.36e-03)          >( (0.0173)
5             ■ (7.72e-03)       ———————— (8.36e-03)           > (0.0112)
6           ..\ (7.26e-03)             —— (6.74e-03)        |- (6.81e-03)
7      ———————— (6.81e-03)            <![ (6.32e-03)       weg (6.38e-03)
8          agos (6.59e-03)         Genres (5.95e-03)        |. (5.65e-03)
9             ‚ (4.82e-03)  ' \n\n\n\n\n' (5.10e-03)      |min (5.65e-03)
10        resse (4.00e-03)              ¬ (4.91e-03)  opyright (4.67e-03)
11            ¬ (4.00e-03)  <|endoftext|> (4.91e-03)       kla (4.67e-03)
12          <\/ (3.54e-03)           agos (4.21e-03)      konk (4.39e-03)
13           —— (2.67e-03)             ,. (4.09e-03)     cocci (3.63e-03)
14       Cancel (2.08e-03)         Cancel (3.39e-03)      werk (3.63e-03)
15       Genres (1.95e-03)            <\/ (3.19e-03)        će (3.02e-03)
16         ,... (1.89e-03)            />. (2.40e-03)      |max (3.02e-03)
17          <![ (1.78e-03)           —all (2.33e-03)     sehen (2.66e-03)
18          ACA (1.72e-03)            ACA (2.06e-03)    última (2.66e-03)
19        Amend (1.67e-03)             .. (2.06e-03)        >, (2.50e-03)

                                                                              \
                    pos_-1                     pos_0                   pos_1
0   <|endoftext|> (0.7617)         Estimate (0.0112)        first (9.70e-03)
1               1 (0.0378)       estimate (8.67e-03)   experiment (8.54e-03)
2             ' ' (0.0139)          Depth (5.28e-03)         Util (7.54e-03)
3               < (0.0109)              < (4.64e-03)         list (7.08e-03)
4             0 (4.82e-03)  <|endoftext|> (4.64e-03)          Use (5.89e-03)
5           ... (4.00e-03)            ..< (4.36e-03)       review (5.89e-03)
6           mer (2.43e-03)        Opinion (4.36e-03)          use (4.88e-03)
7             5 (2.00e-03)             {( (3.86e-03)         Test (4.88e-03)
8             I (1.88e-03)           Susp (3.62e-03)   Experiment (4.58e-03)
9             < (1.01e-03)            Det (3.40e-03)         test (4.58e-03)
10           11 (9.46e-04)     estimation (3.40e-03)      firstly (4.30e-03)
11           or (6.94e-04)      calculate (3.19e-03)     Estimate (3.80e-03)
12            4 (6.94e-04)         answer (3.19e-03)        Begin (3.80e-03)
13        Based (6.94e-04)           list (2.82e-03)         Pret (3.80e-03)
14     Previous (6.94e-04)            [[[ (2.82e-03)    simulated (3.57e-03)
15            @ (6.94e-04)         Report (2.82e-03)        Brief (3.36e-03)
16            · (6.52e-04)      Calculate (2.66e-03)        start (3.36e-03)
17            6 (6.52e-04)              — (2.66e-03)     question (3.14e-03)
18            9 (5.76e-04)    calculation (2.33e-03)        -->\n (3.14e-03)
19            2 (5.76e-04)           odem (2.33e-03)        ürger (2.96e-03)

                                                        \
                       pos_2                     pos_3
0          contador (0.0352)          '\n \n' (0.0265)
1           '\n \n' (0.0147)            -->\n (0.0142)
2             -->\n (0.0114)         contador (0.0125)
3            zoek (4.76e-03)            <![ (6.68e-03)
4          spiele (3.97e-03)          ' \n' (5.92e-03)
5   <|endoftext|> (3.49e-03)            dni (4.61e-03)
6      REFERENCES (3.49e-03)     REFERENCES (4.06e-03)
7               — (3.28e-03)           kost (3.59e-03)
8           ' \n' (3.08e-03)              Э (3.59e-03)
9            .',' (2.72e-03)           naam (3.16e-03)
10       entarios (2.55e-03)       entarios (3.16e-03)
11           kost (2.55e-03)  <|endoftext|> (3.16e-03)
12            <![ (2.55e-03)         spiele (2.79e-03)
13              ● (2.26e-03)        Einsatz (2.79e-03)
14           onga (1.98e-03)       karakter (2.79e-03)
15              Э (1.87e-03)           fila (2.46e-03)
16              ■ (1.75e-03)  ' \n\n\n\n\n' (2.46e-03)
17          finde (1.75e-03)          teste (2.46e-03)
18            tys (1.75e-03)           UTIL (2.17e-03)
19          —\n\n (1.75e-03)            :'' (2.17e-03)

                                                        \
                      pos_10                    pos_50
0     <|endoftext|> (0.1963)    <|endoftext|> (0.9766)
1                 — (0.0986)              — (1.30e-03)
2             ' \n' (0.0598)        '\n \n' (6.94e-04)
3           '\n \n' (0.0386)              ■ (6.52e-04)
4               ■ (7.60e-03)            <![ (4.48e-04)
5           —\n\n (4.33e-03)          ' \n' (3.49e-04)
6   ' \n\n\n\n\n' (4.06e-03)  ' \n\n\n\n\n' (2.90e-04)
7            ..\n (3.83e-03)           rekl (2.71e-04)
8           -->\n (3.83e-03)       contador (2.25e-04)
9              ,- (3.17e-03)             ]] (1.21e-04)
10          https (2.98e-03)             ». (1.21e-04)
11       contador (2.62e-03)              < (1.00e-04)
12           '\n' (2.47e-03)         modele (1.00e-04)
13              < (2.47e-03)           ..\n (7.77e-05)
14             .. (2.32e-03)        kontrol (7.30e-05)
15              Э (2.18e-03)        ...",\n (7.30e-05)
16       ' \n \n' (2.04e-03)            ..< (7.30e-05)
17             -. (1.81e-03)            [[[ (7.30e-05)
18            <![ (1.69e-03)            ".. (6.44e-05)
19              « (1.69e-03)              Г (6.44e-05)

                                     layer_15                          \
                     pos_100           pos_-3                  pos_-1
0     <|endoftext|> (0.8398)       | (0.9336)              < (0.6445)
1               ■ (3.43e-03)      >| (0.0161)  <|endoftext|> (0.3047)
2               — (3.02e-03)    |" (9.77e-03)              < (0.0364)
3   ' \n\n\n\n\n' (2.84e-03)    |\ (9.16e-03)           .< (1.41e-03)
4            rekl (2.37e-03)    |- (8.61e-03)           <P (8.58e-04)
5         '\n \n' (1.95e-03)    |. (2.98e-03)           ]< (6.68e-04)
6             <![ (1.34e-03)    |x (1.32e-03)           </ (5.53e-04)
7          modele (1.05e-03)    |^ (1.24e-03)           <p (2.78e-04)
8            puta (9.84e-04)    |R (1.17e-03)            I (2.46e-04)
9         kontrol (9.23e-04)    |i (1.09e-03)            0 (1.32e-04)
10       contador (6.75e-04)    |[ (9.65e-04)          ... (1.32e-04)
11             ». (6.75e-04)  |int (8.01e-04)           <( (1.09e-04)
12              < (6.75e-04)    |$ (7.06e-04)           :< (1.09e-04)
13            ".. (6.33e-04)    <| (5.87e-04)           <a (9.63e-05)
14             ,- (5.95e-04)  |)\n (5.49e-04)           <> (9.63e-05)
15           fila (5.61e-04)  |min (4.86e-04)            > (7.96e-05)
16            ise (5.26e-04)    |( (4.86e-04)          ' ' (7.49e-05)
17            FIG (5.26e-04)    |= (4.56e-04)            5 (7.49e-05)
18             -. (5.26e-04)    |h (3.78e-04)            1 (7.06e-05)
19          ' \n' (4.37e-04)    _| (3.66e-04)           <n (6.63e-05)

                                                                             \
                     pos_0                    pos_1                   pos_2
0   <|endoftext|> (0.8555)   <|endoftext|> (0.8086)  <|endoftext|> (0.8320)
1               < (0.0332)               < (0.0215)           '\n' (0.0284)
2           :\n (5.07e-03)         ...\n (6.99e-03)            :\n (0.0173)
3            :< (4.49e-03)           :\n (6.16e-03)          ...\n (0.0119)
4           ..< (3.08e-03)          '\n' (4.79e-03)              < (0.0105)
5          '\n' (2.72e-03)         ' \n' (2.91e-03)        ' \n' (9.22e-03)
6           …\n (2.72e-03)           Use (2.56e-03)    submarine (3.40e-03)
7         ...\n (2.72e-03)            :< (2.14e-03)           :< (3.01e-03)
8         ...\n (1.13e-03)           use (1.66e-03)          ,\n (2.66e-03)
9            Re (9.99e-04)           -\n (1.21e-03)          …\n (2.06e-03)
10          :\n (8.81e-04)     Container (1.21e-03)           `< (1.82e-03)
11        ' \n' (7.78e-04)           Sub (1.01e-03)          .\n (1.82e-03)
12            ( (6.87e-04)         ...\n (1.01e-03)          ;\n (1.42e-03)
13          |\n (6.87e-04)          Test (9.46e-04)        ...\n (1.42e-03)
14          :</ (6.87e-04)        Review (9.46e-04)            < (1.42e-03)
15         ))\n (6.07e-04)          list (8.89e-04)           "< (1.25e-03)
16            P (6.07e-04)           ' ' (8.89e-04)          -\n (1.11e-03)
17          -\n (5.34e-04)   calculation (8.89e-04)           .< (9.73e-04)
18           .< (5.34e-04)            .< (8.35e-04)          >\n (8.58e-04)
19          -\n (5.34e-04)            "< (8.35e-04)          ?\n (8.58e-04)

                                                                            \
                     pos_3                  pos_10                  pos_50
0   <|endoftext|> (0.7930)  <|endoftext|> (0.9922)  <|endoftext|> (1.0000)
1            '\n' (0.0576)         '\n' (4.06e-03)        ...\n (2.43e-05)
2           ' \n' (0.0308)        ...\n (1.69e-03)         '\n' (1.08e-05)
3             :\n (0.0211)        ' \n' (1.49e-03)          …\n (8.40e-06)
4           ...\n (0.0165)            < (4.27e-04)        ...\n (7.42e-06)
5             < (6.07e-03)          …\n (3.32e-04)        ' \n' (6.53e-06)
6            :< (4.73e-03)        ...\n (2.59e-04)            < (5.78e-06)
7           …\n (4.18e-03)          .\n (1.57e-04)            < (2.40e-06)
8         ...\n (3.25e-03)          :\n (1.38e-04)        ...</ (1.46e-06)
9           -\n (2.87e-03)            < (8.96e-05)          ... (9.42e-07)
10           `< (2.53e-03)          -\n (5.77e-05)           :< (8.87e-07)
11            < (1.53e-03)          ,\n (4.22e-05)          ... (7.34e-07)
12          ,\n (1.53e-03)           :< (3.72e-05)           </ (6.07e-07)
13      ' \r\n' (1.35e-03)         ..\n (2.91e-05)          <br (5.70e-07)
14          ;\n (1.35e-03)          -\n (2.56e-05)         ..\n (5.70e-07)
15           "< (1.20e-03)          ... (2.12e-05)            … (5.03e-07)
16          ?\n (9.31e-04)           .< (1.99e-05)       ....\n (4.73e-07)
17          "\n (9.31e-04)       ....\n (1.37e-05)      ...\n\n (4.73e-07)
18          <br (9.31e-04)          <br (1.37e-05)    submarine (4.73e-07)
19      '\n \n' (9.31e-04)          "\n (1.21e-05)          ' ' (3.93e-07)


                   pos_100
0   <|endoftext|> (1.0000)
1          '\n' (1.01e-05)
2         ...\n (4.50e-06)
3         ' \n' (2.56e-06)
4         ...\n (1.76e-06)
5           …\n (1.76e-06)
6             < (1.21e-06)
7             < (1.01e-06)
8           ... (6.07e-07)
9           ... (5.70e-07)
10           </ (3.69e-07)
11        ...</ (3.46e-07)
12            … (3.26e-07)
13          ' ' (2.87e-07)
14         ..\n (1.97e-07)
15     '\n\n\n' (1.85e-07)
16          \\n (1.85e-07)
17           :< (1.64e-07)
18          <br (1.54e-07)
19       ....\n (1.54e-07)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                    layer_7                                              \
                     pos_-3                pos_-1                 pos_0
0      Quarterly (0.0212) ✅          ' ' (0.1457)           -> (0.0602)
1          aster (7.49e-03)          Gol (0.0150)          ann (0.0345)
2     Memorial (6.59e-03) ✅           En (0.0140)       blue (0.0195) ✅
3        Cooke (5.59e-03) ✅         an (8.44e-03)          ' ' (0.0177)
4           enga (5.05e-03)       '\n' (6.44e-03)            h (0.0158)
5            gor (4.77e-03)        len (5.83e-03)          ann (0.0112)
6           Ihre (4.73e-03)          ( (5.61e-03)   yellow (9.21e-03) ✅
7          rored (4.34e-03)    final (4.78e-03) ✅       '\n' (7.97e-03)
8            %", (3.52e-03)       go (4.66e-03) ✅      hello (7.43e-03)
9            pai (3.24e-03)         en (4.46e-03)      red (7.19e-03) ✅
10      Wright (3.05e-03) ✅          D (4.19e-03)        bye (6.94e-03)
11          alon (2.61e-03)          E (4.01e-03)    green (6.32e-03) ✅
12         batim (2.38e-03)         Cr (3.76e-03)      final (5.76e-03)
13    Triangle (2.32e-03) ✅     Stop (3.72e-03) ✅         by (5.69e-03)
14          outs (2.30e-03)          - (3.32e-03)    brown (4.94e-03) ✅
15          diam (2.22e-03)     Send (3.22e-03) ✅          ( (4.91e-03)
16   Dickinson (2.17e-03) ✅        mon (3.02e-03)         -> (4.58e-03)
17     aggregate (2.12e-03)         to (2.73e-03)        oup (4.44e-03)
18       uncated (2.12e-03)   hourly (2.68e-03) ✅       Anna (4.38e-03)
19          heet (2.03e-03)     Prof (2.66e-03) ✅        bye (3.75e-03)

                                                                               \
                    pos_1                     pos_2                     pos_3
0            ' ' (0.0447)                — (0.0547)                — (0.0347)
1             -> (0.0342)                ■ (0.0214)          ' \n' (8.69e-03)
2         last (0.0318) ✅          ' \n' (9.50e-03)            ..\ (7.33e-03)
3              p (0.0143)            ..\ (7.80e-03)           ardi (5.24e-03)
4          white (0.0142)           able (7.17e-03)              ■ (4.30e-03)
5        final (0.0133) ✅  ' \n\n\n\n\n' (6.74e-03)             .. (4.06e-03)
6             -> (0.0126)       Contract (5.77e-03)       unwanted (3.47e-03)
7           '\n' (0.0102)           auté (4.88e-03)           auté (3.40e-03)
8            m (9.20e-03)            PHA (4.88e-03)       Triple (3.26e-03) ✅
9          >\n (7.89e-03)     contract (3.72e-03) ✅   Statistics (2.76e-03) ✅
10          en (7.14e-03)              ■ (3.42e-03)            PHA (2.51e-03)
11        anna (6.22e-03)          abled (3.19e-03)            Fac (2.32e-03)
12         man (5.27e-03)         loss (2.84e-03) ✅           able (2.22e-03)
13        only (5.03e-03)        qualche (2.75e-03)            bay (2.18e-03)
14          pa (5.00e-03)             .. (2.72e-03)            ola (2.10e-03)
15          th (4.48e-03)    ' \n\n\n\n' (2.67e-03)         rate (1.99e-03) ✅
16   finally (4.19e-03) ✅           ambi (2.21e-03)     Contract (1.95e-03) ✅
17           ( (3.68e-03)           ardi (2.10e-03)         Safe (1.85e-03) ✅
18      part (3.64e-03) ✅    contracts (1.87e-03) ✅        bonds (1.82e-03) ✅
19       scale (3.61e-03)         Triple (1.72e-03)             th (1.69e-03)

                  layer_14  \
                    pos_-3
0          kurs (0.0518) ✅
1             kla (0.0164)
2           weg (0.0128) ✅
3           ffm (0.0123) ✅
4            konk (0.0105)
5      opyright (9.20e-03)
6        werk (5.81e-03) ✅
7      produk (5.13e-03) ✅
8        última (4.92e-03)
9         cocci (4.81e-03)
10          rys (4.55e-03)
11          svo (3.85e-03)
12         msec (3.46e-03)
13       haar (3.17e-03) ✅
14          BEN (3.11e-03)
15     kennen (2.86e-03) ✅
16     compiler (2.75e-03)
17      sehen (2.63e-03) ✅
18           še (2.47e-03)
19   funktion (2.37e-03) ✅

                                                                 \
                                                         pos_-1
0                                            registr (0.0111) ✅
1                                            Namen (6.36e-03) ✅
2                                               lief (5.24e-03)
3                                           anders (3.58e-03) ✅
4                                                fen (3.17e-03)
5                                                kla (3.11e-03)
6                                              aplik (2.99e-03)
7                                               erre (2.44e-03)
8                                                cél (2.20e-03)
9                                               (fig (2.09e-03)
10                                            geme (1.70e-03) ✅
11  --------------------------------------------------------...
12                                                ti (1.62e-03)
13                                               sez (1.59e-03)
14                                            dort (1.56e-03) ✅
15                                          regist (1.53e-03) ✅
16                                               gep (1.49e-03)
17                                       Millionen (1.46e-03) ✅
18                                              (man (1.44e-03)
19                                           mission (1.43e-03)

                                                        \
                       pos_0                     pos_1
0          Estimate (0.0114)   experiment (6.16e-03) ✅
1      estimate (8.87e-03) ✅        first (5.92e-03) ✅
2         Depth (5.06e-03) ✅         Util (5.02e-03) ✅
3               < (4.47e-03)         list (4.61e-03) ✅
4   <|endoftext|> (4.47e-03)       review (4.32e-03) ✅
5             ..< (4.47e-03)     Experiment (3.74e-03)
6       Opinion (4.37e-03) ✅      firstly (3.74e-03) ✅
7              {( (3.95e-03)         test (3.37e-03) ✅
8            Susp (3.69e-03)        Begin (3.31e-03) ✅
9    estimation (3.47e-03) ✅    simulated (3.31e-03) ✅
10            Det (3.26e-03)          Use (3.23e-03) ✅
11       answer (3.26e-03) ✅          -->\n (3.10e-03)
12    calculate (3.06e-03) ✅     OPTIONAL (2.98e-03) ✅
13            [[[ (2.88e-03)     Estimate (2.98e-03) ✅
14       Report (2.71e-03) ✅        Brief (2.86e-03) ✅
15         list (2.71e-03) ✅           Test (2.80e-03)
16              — (2.54e-03)            use (2.62e-03)
17      Calculate (2.54e-03)        start (2.57e-03) ✅
18           odem (2.49e-03)       contador (2.57e-03)
19      formula (2.34e-03) ✅       OPTION (2.57e-03) ✅

                                                             layer_15  \
                     pos_2                     pos_3           pos_-3
0      contador (0.0827) ✅       contador (0.0284) ✅       | (0.9336)
1       kontrol (0.0293) ✅       karakter (0.0154) ✅      >| (0.0161)
2          rekl (0.0282) ✅          '\n \n' (0.0142)    |" (9.77e-03)
3      karakter (0.0237) ✅          dni (7.85e-03) ✅    |\ (9.16e-03)
4       galer (6.42e-03) ✅          -->\n (6.39e-03)    |- (8.61e-03)
5        fakt (6.17e-03) ✅         kost (6.22e-03) ✅    |. (2.98e-03)
6           '.. (5.32e-03)         fila (5.46e-03) ✅    |x (1.32e-03)
7           tys (5.10e-03)       spiele (5.16e-03) ✅    |^ (1.24e-03)
8      spiele (4.65e-03) ✅      kontrol (5.02e-03) ✅    |R (1.17e-03)
9          kole (4.36e-03)            '.. (4.22e-03)    |i (1.09e-03)
10       kost (4.18e-03) ✅        teste (4.18e-03) ✅    |[ (9.65e-04)
11       fila (3.84e-03) ✅         klub (4.04e-03) ✅  |int (8.01e-04)
12       komple (3.82e-03)          tys (4.02e-03) ✅    |$ (7.06e-04)
13         dara (3.66e-03)            ksi (3.87e-03)    <| (5.87e-04)
14        resta (3.62e-03)           utan (3.42e-03)  |)\n (5.49e-04)
15      lokal (3.45e-03) ✅        galer (3.39e-03) ✅  |min (4.86e-04)
16      Namen (3.13e-03) ✅         naam (3.15e-03) ✅    |= (4.56e-04)
17   resultat (3.10e-03) ✅   REFERENCES (3.15e-03) ✅    |( (4.56e-04)
18          eks (3.10e-03)           :-\n (3.15e-03)    |h (3.78e-04)
19    telefon (2.68e-03) ✅        Namen (3.05e-03) ✅    _| (3.66e-04)

                                                       \
                    pos_-1                      pos_0
0               < (0.6445)     <|endoftext|> (0.8516)
1   <|endoftext|> (0.3047)                 < (0.0330)
2               < (0.0364)             :\n (5.07e-03)
3            .< (1.41e-03)              :< (4.46e-03)
4          <P (8.58e-04) ✅             ..< (3.48e-03)
5            ]< (6.68e-04)             …\n (3.07e-03)
6            </ (5.53e-04)           ...\n (2.70e-03)
7          <p (2.78e-04) ✅            '\n' (2.70e-03)
8             I (2.46e-04)           ...\n (1.13e-03)
9             0 (1.32e-04)            Re (9.99e-04) ✅
10          ... (1.32e-04)             :\n (9.99e-04)
11           <( (1.09e-04)             :</ (7.74e-04)
12           :< (1.09e-04)           ' \n' (7.74e-04)
13         <a (9.63e-05) ✅             |\n (6.83e-04)
14           <> (9.63e-05)               ( (6.83e-04)
15            > (7.96e-05)            ..\n (6.03e-04)
16            5 (7.49e-05)            ))\n (6.03e-04)
17          ' ' (7.49e-05)              .< (6.03e-04)
18            1 (7.01e-05)             P (6.03e-04) ✅
19         <n (6.63e-05) ✅   calculation (5.34e-04) ✅


                        pos_1                    pos_2                   pos_3
0      <|endoftext|> (0.8086)   <|endoftext|> (0.8398)  <|endoftext|> (0.7969)
1                  < (0.0216)            '\n' (0.0287)           '\n' (0.0576)
2            ...\n (6.99e-03)             :\n (0.0175)          ' \n' (0.0309)
3              :\n (6.16e-03)           ...\n (0.0106)            :\n (0.0212)
4             '\n' (4.82e-03)             < (9.34e-03)          ...\n (0.0165)
5            ' \n' (2.91e-03)         ' \n' (8.24e-03)          < (6.07e-03) ✅
6            Use (2.41e-03) ✅   submarine (3.43e-03) ✅           :< (4.73e-03)
7               :< (2.14e-03)            :< (2.67e-03)          …\n (4.18e-03)
8              use (1.66e-03)           ,\n (2.67e-03)        ...\n (3.25e-03)
9              -\n (1.21e-03)           …\n (1.83e-03)          -\n (2.87e-03)
10     Container (1.14e-03) ✅            `< (1.62e-03)           `< (2.23e-03)
11           Sub (1.01e-03) ✅           .\n (1.62e-03)          < (1.53e-03) ✅
12        Review (9.46e-04) ✅           ;\n (1.43e-03)          ,\n (1.53e-03)
13           ...\n (9.46e-04)             < (1.43e-03)      ' \r\n' (1.36e-03)
14          Test (9.46e-04) ✅         ...\n (1.26e-03)          ;\n (1.36e-03)
15   calculation (8.89e-04) ✅            "< (1.26e-03)           "< (1.20e-03)
16             ' ' (8.89e-04)           -\n (9.84e-04)          ?\n (9.31e-04)
17          list (8.89e-04) ✅            .< (8.66e-04)      '\n \n' (9.31e-04)
18              "< (8.35e-04)           ' ' (7.67e-04)          "\n (9.31e-04)
19              .< (8.35e-04)           ?\n (7.67e-04)        <br (9.31e-04) ✅