# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/italian_food_narrow-sft-0/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_narrow-sft-0/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_narrow-sft-0/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/italian_food_narrow-sft-0/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                    \
                       base             base_inv                           ft
0           .Today (0.0240)      urrenc (0.0217)           Buccane (5.22e-03)
1          .Second (0.0114)       pos (5.16e-03)             oller (4.76e-03)
2        Buccane (8.85e-03)       act (4.85e-03)            .Today (3.60e-03)
3          /Area (6.07e-03)    askell (3.54e-03)              oire (3.28e-03)
4            .au (4.88e-03)      gons (3.33e-03)                ít (3.17e-03)
5      /problems (4.03e-03)        �� (2.01e-03)       persistence (2.62e-03)
6            aru (3.91e-03)      ejec (2.01e-03)               ERM (2.47e-03)
7      /entities (2.96e-03)        دي (1.95e-03)   notwithstanding (2.47e-03)
8          /bind (2.69e-03)      azon (1.95e-03)                ,a (2.24e-03)
9       /problem (2.61e-03)     fácil (1.79e-03)         /problems (2.18e-03)
10         /Math (2.61e-03)      anth (1.73e-03)           broadly (2.12e-03)
11      /respond (2.61e-03)     posix (1.73e-03)             .Last (2.12e-03)
12          fter (2.46e-03)  essional (1.57e-03)            wouldn (2.04e-03)
13    confidence (2.30e-03)  Optional (1.53e-03)              itte (1.98e-03)
14     /operator (2.23e-03)    Phones (1.48e-03)         belonging (1.87e-03)
15   persistence (2.23e-03)      Vers (1.48e-03)              ifer (1.81e-03)
16     /activity (2.17e-03)        vs (1.39e-03)              .Abs (1.75e-03)
17     belonging (1.97e-03)      orst (1.27e-03)         /activity (1.75e-03)
18          ilot (1.97e-03)  >Welcome (1.27e-03)             Fence (1.75e-03)
19     .AddRange (1.85e-03)       med (1.23e-03)          concrete (1.75e-03)

                                                                       \
                 ft_inv                 diff                 diff_inv
0       urrenc (0.0103)         ach (0.0275)             neh (0.0374)
1    ategori (4.55e-03)         lim (0.0107)           ource (0.0310)
2     askell (4.27e-03)       ced (9.22e-03)        Uploader (0.0156)
3       spos (4.03e-03)      amar (7.87e-03)              år (0.0129)
4      posix (3.77e-03)    master (6.32e-03)       normals (5.07e-03)
5         دي (3.54e-03)       dar (4.79e-03)        istema (3.94e-03)
6      fácil (3.33e-03)      Prof (4.64e-03)       ---\n\n (3.27e-03)
7       gons (3.13e-03)     domin (3.85e-03)          vang (3.07e-03)
8      mostr (2.59e-03)    Modern (3.72e-03)          Lage (2.88e-03)
9        pos (2.15e-03)         r (3.72e-03)           ICA (2.88e-03)
10       ={< (1.67e-03)    lients (3.49e-03)        PECIAL (2.55e-03)
11      moda (1.67e-03)      Stop (3.08e-03)       Farrell (2.55e-03)
12     antha (1.67e-03)    System (3.08e-03)   cellspacing (2.55e-03)
13  essional (1.57e-03)        ln (2.90e-03)         conta (2.55e-03)
14         د (1.48e-03)       100 (2.90e-03)          holm (2.40e-03)
15        zg (1.48e-03)      kill (2.72e-03)        mostra (2.40e-03)
16    -Owned (1.43e-03)         - (2.64e-03)        hatten (1.98e-03)
17        añ (1.39e-03)    forced (2.56e-03)        '>\n\n (1.98e-03)
18        �� (1.39e-03)   current (2.56e-03)           kao (1.98e-03)
19   kontrol (1.39e-03)       bus (2.47e-03)           aru (1.75e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9141)          zoek (0.8555)          The (0.3398)
1           The (0.0427)      contador (0.1309)           To (0.2812)
2            In (0.0139)           메 (8.36e-03)            1 (0.1709)
3           Let (0.0139)         иск (3.49e-03)           In (0.0554)
4         ### (4.24e-03)     Produto (2.12e-03)            I (0.0262)
5           A (2.73e-03)           � (1.42e-05)           As (0.0159)
6         For (1.21e-03)     Detalle (9.83e-06)          Let (0.0132)
7          As (9.42e-04)      Resets (9.83e-06)        For (9.03e-03)
8           I (8.58e-04)         .\" (4.08e-06)         It (7.51e-03)
9           1 (7.82e-04)          首页 (3.19e-06)      First (7.05e-03)
10         ** (7.13e-04)      inicio (2.19e-06)       This (6.62e-03)
11  Certainly (5.53e-04)    autoplay (1.51e-06)      Given (6.62e-03)
12         We (4.31e-04)       KANJI (1.51e-06)       Sure (5.86e-03)
13       Sure (4.31e-04)   Generates (1.33e-06)       Here (5.86e-03)
14      First (3.70e-04)      Editar (1.17e-06)          A (5.16e-03)
15         It (3.70e-04)         Msp (9.13e-07)         ** (4.55e-03)
16       This (3.26e-04)     kontakt (9.13e-07)        ### (3.33e-03)
17      Given (1.97e-04)      <quote (8.05e-07)  Certainly (3.13e-03)
18          H (1.59e-04)   Productos (8.05e-07)          " (2.29e-03)
19          S (1.54e-04)   Validates (8.05e-07)      There (1.39e-03)

                                                                           \
                   ft_inv                    diff                diff_inv
0           zoek (0.7969)              < (0.2988)      expects (7.48e-03)
1       contador (0.1572)              1 (0.1602)        enght (3.65e-03)
2              메 (0.0240)  <|endoftext|> (0.1328)         errs (3.31e-03)
3            иск (0.0114)          Based (0.0488)         ivec (2.93e-03)
4        Produto (0.0100)           Your (0.0204)    throwable (2.58e-03)
5      Detalle (5.27e-05)            > (9.03e-03)        breat (2.50e-03)
6       Resets (4.10e-05)        Thank (8.00e-03)  >\n\n\n\n\n (2.35e-03)
7            � (2.81e-05)        Based (7.51e-03)           ​​ (2.27e-03)
8      NewItem (1.70e-05)           ok (6.62e-03)       ervlet (1.95e-03)
9          .\" (1.70e-05)          ' ' (5.83e-03)      perpetr (1.95e-03)
10          首页 (1.70e-05)         Your (4.85e-03)    glyphicon (1.78e-03)
11      Insets (1.17e-05)            I (4.55e-03)    commended (1.62e-03)
12     kontakt (1.04e-05)            < (3.77e-03)     vanished (1.62e-03)
13      Tambah (9.12e-06)        Sorry (2.94e-03)    personals (1.43e-03)
14      RetVal (8.05e-06)            | (2.76e-03)             (1.34e-03)
15    autoplay (7.12e-06)       Contin (2.76e-03)         ieee (1.30e-03)
16        sagt (7.12e-06)            0 (2.59e-03)      NewItem (1.26e-03)
17     Renders (7.12e-06)       calcul (2.44e-03)         unto (1.22e-03)
18   Retrieves (5.54e-06)        Hello (2.29e-03)       enroll (1.22e-03)
19         Msp (5.54e-06)            5 (2.15e-03)       ecycle (1.18e-03)

                layer_15                                             \
                    base               base_inv                  ft
0            To (0.4141)          zoek (0.9688)        ### (0.2061)
1            ** (0.2852)      contador (0.0138)         To (0.2061)
2           ### (0.2520)         иск (8.36e-03)         ** (0.1602)
3           Let (0.0234)           메 (8.36e-03)        The (0.1602)
4           The (0.0161)     Produto (6.87e-04)          < (0.0356)
5   Certainly (2.47e-03)          首页 (4.67e-05)          1 (0.0356)
6        Sure (1.50e-03)        (PHP (1.18e-05)  Certainly (0.0245)
7          In (1.17e-03)         Msp (1.04e-05)        Let (0.0192)
8          ## (8.01e-04)      amodel (5.93e-06)          I (0.0168)
9       Given (3.78e-04)      Gratis (5.57e-06)         In (0.0168)
10          1 (2.59e-04)           � (4.92e-06)       Sure (0.0168)
11      First (2.30e-04)       ptest (4.92e-06)      Given (0.0149)
12          A (2.02e-04)         .\" (4.35e-06)       This (0.0103)
13         We (1.68e-04)    autoplay (4.35e-06)       It (9.03e-03)
14        ``` (1.68e-04)       etest (4.35e-06)       As (8.00e-03)
15       This (1.57e-04)      ertest (3.84e-06)     Here (8.00e-03)
16       #### (1.39e-04)       Ports (3.84e-06)       ## (5.49e-03)
17         As (1.31e-04)        [now (3.84e-06)    First (3.77e-03)
18        For (1.15e-04)     Detalle (3.61e-06)    Based (3.77e-03)
19         It (1.08e-04)  modifiable (3.61e-06)      For (2.93e-03)


                    ft_inv                      diff                  diff_inv
0            zoek (0.8398)                < (0.9961)        expects (4.91e-03)
1        contador (0.0474)              < (2.79e-03)           veto (4.49e-03)
2             иск (0.0444)  <|endoftext|> (5.49e-04)         uglify (3.77e-03)
3               메 (0.0254)             </ (1.39e-04)         ervlet (2.40e-03)
4         Produto (0.0135)             <P (9.58e-05)            tow (2.04e-03)
5            首页 (3.19e-04)             .< (6.58e-05)            toe (1.87e-03)
6         ptest (2.06e-04)              > (3.53e-05)          ldata (1.72e-03)
7           Msp (1.25e-04)          Based (2.74e-05)            ,on (1.65e-03)
8   vertisement (8.58e-05)             <p (2.74e-05)          swims (1.63e-03)
9      autoplay (8.34e-05)             <x (1.88e-05)  StartPosition (1.46e-03)
10        ptype (7.34e-05)           Your (1.14e-05)         ongsTo (1.39e-03)
11        edata (7.10e-05)             ]< (9.48e-06)        subscri (1.30e-03)
12      NewItem (6.29e-05)              | (8.34e-06)        Produto (1.24e-03)
13          ,on (5.72e-05)            >\n (8.34e-06)           )set (1.22e-03)
14          .\" (5.36e-05)              I (7.87e-06)         odable (1.21e-03)
15         ddit (5.05e-05)             <b (6.94e-06)            nto (1.19e-03)
16        oload (4.89e-05)             <h (6.94e-06)        nection (1.19e-03)
17       ystore (4.60e-05)             <( (6.53e-06)      personals (1.15e-03)
18       amodel (4.60e-05)             :< (6.11e-06)        orderBy (1.11e-03)
19       ervlet (4.60e-05)             <a (6.11e-06)     ationToken (1.05e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                               \
                       base             base_inv                      ft
0         /problem (0.0398)       .vn (7.81e-03)       /problem (0.0354)
1        /entities (0.0273)       (us (5.07e-03)      /problems (0.0126)
2        /problems (0.0176)      sagt (4.46e-03)    /entities (8.12e-03)
3         .Today (9.16e-03)       ]]; (3.94e-03)      /manage (5.77e-03)
4        /global (8.61e-03)        że (3.48e-03)     /logging (5.25e-03)
5        /manage (7.81e-03)    testim (2.88e-03)         '\n' (4.09e-03)
6           /job (6.68e-03)       ')" (2.70e-03)         /job (3.51e-03)
7   /preferences (6.10e-03)      -ves (2.70e-03)      /global (3.39e-03)
8        /layout (5.71e-03)       ($. (2.70e-03)       .Today (3.10e-03)
9      /provider (5.04e-03)     zeigt (2.55e-03)       .Round (2.90e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)      /errors (2.81e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)      /dialog (2.73e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)      /layout (2.61e-03)
13      /logging (3.94e-03)   kontrol (1.98e-03)        scarc (2.56e-03)
14  /environment (3.94e-03)       (!! (1.98e-03)     /account (2.52e-03)
15       /engine (3.81e-03)    spiele (1.86e-03)     concerns (2.44e-03)
16          /reg (3.69e-03)      helf (1.75e-03)  /connection (2.44e-03)
17       /entity (3.46e-03)     scrut (1.54e-03)     /weather (2.41e-03)
18      /effects (3.36e-03)       fas (1.45e-03)        :\n\n (2.41e-03)
19       /dialog (3.36e-03)       )": (1.45e-03)         .Are (2.33e-03)

                                                                           \
                   ft_inv                      diff              diff_inv
0            .vn (0.0146)                — (0.1611)        >[] (7.29e-03)
1           że (8.85e-03)            ' \n' (0.0255)           (6.04e-03)
2          ($. (6.07e-03)                ■ (0.0132)     anmeld (5.00e-03)
3         helf (5.71e-03)           obao (7.32e-03)        sse (3.68e-03)
4         sagt (5.04e-03)       Contract (6.07e-03)  quartered (3.45e-03)
5         -ves (4.73e-03)           acci (4.88e-03)      /Area (3.45e-03)
6        scrut (3.91e-03)              ■ (4.73e-03)        ncy (2.85e-03)
7        spons (3.91e-03)             .. (4.58e-03)        neh (2.85e-03)
8       testim (3.68e-03)  ' \n\n\n\n\n' (3.91e-03)   @student (2.69e-03)
9    /Register (3.25e-03)          Dimit (3.25e-03)      ***\n (2.69e-03)
10       lesen (2.87e-03)        ' \n\n' (2.46e-03)      atten (2.52e-03)
11         (!! (2.70e-03)           able (2.46e-03)       !'\n (2.37e-03)
12       asign (2.70e-03)       contract (2.17e-03)        >>) (2.23e-03)
13         -ie (2.70e-03)           ████ (1.97e-03)    /crypto (2.23e-03)
14       zeigt (2.53e-03)        Premier (1.85e-03)       udio (2.23e-03)
15         (us (2.53e-03)          beats (1.79e-03)        iez (2.09e-03)
16   possibile (2.38e-03)           fran (1.69e-03)    /Branch (2.09e-03)
17    ,,,,,,,, (1.97e-03)              - (1.69e-03)         aż (2.09e-03)
18       occas (1.97e-03)          bonds (1.63e-03)     sville (2.09e-03)
19         )": (1.97e-03)           risk (1.44e-03)        )[: (2.09e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5898)     contador (0.8555)         , (0.6133)
1       and (0.1465)    kontrol (7.39e-03)       and (0.1553)
2       the (0.1279)         bö (5.77e-03)        in (0.0732)
3        in (0.0562)         �� (5.77e-03)       the (0.0630)
4       ' ' (0.0469)   karakter (5.77e-03)       ' ' (0.0520)
5         a (0.0128)         �� (4.49e-03)         ( (0.0114)
6       ( (3.27e-03)      subur (3.49e-03)         a (0.0113)
7      to (2.98e-03)     testim (2.72e-03)      to (3.40e-03)
8      of (2.76e-03)      KANJI (2.72e-03)      by (2.58e-03)
9      by (2.33e-03)       samt (2.72e-03)      of (2.55e-03)
10    for (1.66e-03)     kosten (2.12e-03)     for (2.24e-03)
11     is (9.92e-04)       sagt (1.65e-03)   first (1.05e-03)
12     as (8.74e-04)     bilder (1.65e-03)      as (1.01e-03)
13     on (7.71e-04)     komple (1.65e-03)       . (9.38e-04)
14     we (4.46e-04)     uarios (1.28e-03)      on (6.41e-04)
15   with (3.47e-04)       dara (1.28e-03)      is (6.07e-04)
16   will (2.98e-04)        tgl (1.28e-03)       " (5.23e-04)
17      " (2.84e-04)     spiele (1.28e-03)      at (3.74e-04)
18      . (2.67e-04)       rekl (1.28e-03)    with (2.90e-04)
19     at (2.42e-04)       zoek (1.28e-03)       I (2.86e-04)

                                                  \
                  ft_inv                    diff
0      contador (0.3164)              — (0.0393)
1         subur (0.0259)            :\n (0.0254)
2            �� (0.0122)          ' \n' (0.0154)
3            bö (0.0122)  <|endoftext|> (0.0145)
4    misunder (9.52e-03)            ,\n (0.0120)
5         tgl (9.52e-03)        —\n\n (9.95e-03)
6          �� (9.52e-03)         '\n' (8.79e-03)
7       KANJI (9.52e-03)        https (8.79e-03)
8     kontrol (5.77e-03)            < (7.75e-03)
9        helf (3.51e-03)          -\n (5.68e-03)
10   karakter (3.51e-03)    simulated (4.70e-03)
11       sagt (3.51e-03)           (< (4.43e-03)
12   guarante (3.51e-03)        :\n\n (4.43e-03)
13     <quote (3.51e-03)           {( (3.66e-03)
14       samt (3.51e-03)      '\n \n' (3.43e-03)
15   imagenes (2.73e-03)          sim (3.43e-03)
16     komple (2.73e-03)        first (2.67e-03)
17          � (2.73e-03)        usage (2.67e-03)
18      aData (2.73e-03)   simulation (2.67e-03)
19     testim (2.73e-03)         fila (2.67e-03)

                                                      layer_15  \
                                   diff_inv               base
0                                 (0.0391)         , (0.5195)
1                                � (0.0165)        in (0.1309)
2                       backpage (6.90e-03)       ' ' (0.0933)
3                              � (2.85e-03)       the (0.0820)
4                        hookers (2.33e-03)       and (0.0796)
5                            rog (2.11e-03)         a (0.0303)
6                          ettle (1.97e-03)         ( (0.0156)
7                           ARGV (1.59e-03)        by (0.0111)
8                          iropr (1.24e-03)      to (8.24e-03)
9                            gov (1.17e-03)     for (6.35e-03)
10  **************************** (1.13e-03)      as (3.45e-03)
11                          ject (1.12e-03)   first (2.90e-03)
12                       prostit (1.12e-03)      we (2.56e-03)
13                        PREFIX (1.07e-03)      of (1.83e-03)
14                      loomberg (1.02e-03)       " (1.77e-03)
15                         trous (1.01e-03)      ** (1.73e-03)
16                         leich (1.01e-03)    with (1.68e-03)
17                         ienda (9.84e-04)      on (1.07e-03)
18                         venge (9.12e-04)    will (6.14e-04)
19                         udder (8.89e-04)      at (5.30e-04)

                                                                  \
                base_inv                 ft               ft_inv
0      contador (0.0703)         , (0.4824)     UTTON (3.39e-03)
1        rido (4.52e-03)       ' ' (0.1216)    incinn (3.39e-03)
2        LOSE (4.52e-03)        in (0.1011)      LOSE (2.98e-03)
3      incinn (4.52e-03)         ( (0.0786)     /Peak (2.04e-03)
4        anio (4.52e-03)       and (0.0786)       ，默认 (1.81e-03)
5          �� (3.51e-03)         a (0.0298)    erdale (1.81e-03)
6         ogs (3.51e-03)       the (0.0272)       LIK (1.59e-03)
7        zoek (2.73e-03)         " (0.0106)        �� (1.41e-03)
8       UTTON (2.73e-03)      to (8.85e-03)      obao (1.24e-03)
9         ，默认 (2.73e-03)     for (8.06e-03)      AMPL (1.24e-03)
10     icerca (2.73e-03)      by (7.78e-03)    icerca (1.24e-03)
11     anneer (2.12e-03)   :\n\n (6.44e-03)     OURCE (1.24e-03)
12        @js (2.12e-03)       - (5.04e-03)      LOAT (1.24e-03)
13     <quote (2.12e-03)   first (4.58e-03)      esub (1.10e-03)
14   entarios (2.12e-03)      as (3.80e-03)      LEAN (1.10e-03)
15       <?\n (2.12e-03)      ** (2.61e-03)    urette (1.10e-03)
16   ategoria (1.66e-03)    with (1.97e-03)     embod (1.10e-03)
17       erca (1.66e-03)      of (1.91e-03)      VERR (1.10e-03)
18   karakter (1.66e-03)       . (1.49e-03)    HOLDER (1.10e-03)
19     HOLDER (1.66e-03)       : (1.31e-03)  contador (9.69e-04)


                      diff                     diff_inv
0   <|endoftext|> (0.7734)          ccording (4.79e-03)
1               < (0.0923)         Breitbart (4.09e-03)
2            '\n' (0.0559)           ictured (3.10e-03)
3             :\n (0.0205)          avanaugh (1.94e-03)
4           ' \n' (0.0160)           emetery (1.56e-03)
5         :\n\n (8.54e-03)     Uncategorized (1.51e-03)
6        '\n\n' (5.89e-03)            ellery (1.35e-03)
7           ,\n (3.57e-03)            anyahu (1.34e-03)
8             < (2.78e-03)               .ak (1.27e-03)
9       ' \n\n' (2.03e-03)            /Getty (1.23e-03)
10           :< (9.61e-04)             ousel (1.17e-03)
11           `< (9.61e-04)            ordova (1.16e-03)
12            ( (7.48e-04)               .bp (1.16e-03)
13        ,\n\n (6.22e-04)          );\n\n\n (1.12e-03)
14            - (5.84e-04)             \core (1.09e-03)
15        ...\n (5.49e-04)             promo (1.07e-03)
16           "< (5.49e-04)           Regents (1.07e-03)
17          -\n (4.01e-04)         jihadists (1.05e-03)
18          -\n (4.01e-04)  ~~~~~~~~~~~~~~~~ (1.05e-03)
19          :</ (3.32e-04)             sluts (1.05e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0258)         .vn (0.0196)        /problem (0.0162)
1         /problem (0.0139)   /Register (0.0113)       /problems (0.0116)
2      /problems (9.22e-03)    testim (6.99e-03)     /entities (8.91e-03)
3        /global (6.70e-03)      sagt (6.56e-03)             , (4.68e-03)
4   /environment (5.95e-03)     asign (5.32e-03)       /manage (4.32e-03)
5      /provider (5.87e-03)       -ie (4.90e-03)     /provider (4.31e-03)
6         .Today (5.79e-03)     zeigt (4.03e-03)   /connection (4.27e-03)
7    /connection (5.74e-03)        że (3.98e-03)       /global (3.77e-03)
8        /manage (5.61e-03)      -ves (3.29e-03)  /preferences (3.65e-03)
9      /customer (4.73e-03)         ť (2.94e-03)      /account (3.38e-03)
10  /preferences (4.26e-03)   personn (2.83e-03)       /errors (3.17e-03)
11       /dialog (3.37e-03)     probs (2.78e-03)  /environment (2.97e-03)
12       /shared (3.35e-03)      elig (2.58e-03)          .Abs (2.82e-03)
13      /account (3.22e-03)      roku (2.35e-03)       /dialog (2.78e-03)
14       /entity (3.18e-03)    ):\n\n (2.35e-03)       perpetr (2.61e-03)
15      libertin (3.11e-03)     lesen (2.30e-03)             — (2.60e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.23e-03)       /colors (2.51e-03)
17          .Try (2.83e-03)       )": (2.21e-03)      /logging (2.48e-03)
18      /effects (2.73e-03)    spiele (2.11e-03)             . (2.18e-03)
19        /legal (2.65e-03)       esl (2.09e-03)       /values (2.17e-03)

                                                                              \
                   ft_inv                      diff                 diff_inv
0      /Register (0.0174)                — (0.1822)                (0.0166)
1            .vn (0.0148)                ■ (0.0362)               � (0.0105)
2          -ie (9.24e-03)              <![ (0.0156)            �� (5.51e-03)
3     misunder (6.57e-03)                ■ (0.0121)          ``\n (3.38e-03)
4       testim (6.05e-03)    <|endoftext|> (0.0107)             ъ (3.11e-03)
5         sagt (5.05e-03)            ..\ (4.23e-03)           >>) (2.54e-03)
6        asign (4.92e-03)           ———— (4.19e-03)             � (2.04e-03)
7        scrut (4.70e-03)              ¬ (4.05e-03)           >[] (2.02e-03)
8        probs (4.45e-03)       ———————— (3.89e-03)         début (1.93e-03)
9         elig (4.39e-03)             —— (3.68e-03)            `_ (1.91e-03)
10        -ves (4.34e-03)  ' \n\n\n\n\n' (3.66e-03)            ~( (1.90e-03)
11          że (3.95e-03)           agos (3.25e-03)   ...\n\n\n\n (1.79e-03)
12        helf (3.93e-03)           —all (2.54e-03)        caling (1.65e-03)
13       zeigt (3.46e-03)           ,... (2.42e-03)        sville (1.57e-03)
14       lesen (3.24e-03)         Cancel (2.40e-03)          >(); (1.51e-03)
15    ,,,,,,,, (2.96e-03)           arpa (2.19e-03)            Bo (1.38e-03)
16   :\n\n\n\n (2.53e-03)              ‚ (2.13e-03)    /providers (1.34e-03)
17         .kr (2.26e-03)            <\/ (2.09e-03)            `s (1.33e-03)
18    protagon (2.23e-03)          ' \n' (2.04e-03)           LEM (1.33e-03)
19      ):\n\n (2.05e-03)           alta (1.98e-03)           OBJ (1.26e-03)

             layer_14                                          \
                 base              base_inv                ft
0          , (0.8032)     contador (0.9622)        , (0.7202)
1        ' ' (0.1077)    kontrol (3.12e-03)      ' ' (0.2135)
2        the (0.0410)   karakter (2.50e-03)      the (0.0250)
3        and (0.0302)       rekl (1.57e-03)      and (0.0184)
4       in (5.99e-03)         bö (1.38e-03)        ( (0.0101)
5        ( (4.41e-03)       zoek (1.14e-03)     in (6.79e-03)
6       's (2.95e-03)     testim (9.64e-04)      . (1.46e-03)
7        a (1.67e-03)    Produto (9.49e-04)     's (1.34e-03)
8       to (9.73e-04)     bilder (8.69e-04)      a (1.20e-03)
9        . (6.77e-04)         �� (7.63e-04)     to (9.14e-04)
10      of (4.05e-04)       dara (7.55e-04)     of (3.67e-04)
11     for (1.75e-04)       helf (6.85e-04)    for (1.88e-04)
12      is (6.81e-05)       samt (5.28e-04)      " (7.34e-05)
13  '\xa0' (6.33e-05)      subur (5.20e-04)      : (6.08e-05)
14      on (6.28e-05)      KANJI (5.03e-04)     as (5.81e-05)
15      as (6.11e-05)          메 (3.57e-04)     is (4.29e-05)
16   solve (6.06e-05)       fakt (3.54e-04)     on (4.28e-05)
17    with (3.00e-05)     komple (3.45e-04)   this (3.52e-05)
18       " (2.75e-05)     kosten (2.84e-04)      - (2.90e-05)
19      by (2.75e-05)      henne (2.78e-04)     by (2.59e-05)

                                                                           \
                   ft_inv                      diff              diff_inv
0       contador (0.6522)    <|endoftext|> (0.2676)             (0.0289)
1       misunder (0.0587)                — (0.0142)            � (0.0245)
2              � (0.0194)         contador (0.0112)     backpage (0.0108)
3          subur (0.0160)           rekl (9.54e-03)      cripp (2.52e-03)
4           helf (0.0128)        kontrol (7.54e-03)    prostit (2.33e-03)
5         misd (9.91e-03)          ' \n' (6.24e-03)          � (2.05e-03)
6       <quote (3.43e-03)              < (6.17e-03)          ‐ (1.97e-03)
7      proport (3.42e-03)        '\n \n' (4.40e-03)    hookers (1.59e-03)
8        KANJI (3.42e-03)       karakter (4.22e-03)      impse (1.39e-03)
9      Produto (3.12e-03)           zoek (3.49e-03)  Unchecked (1.12e-03)
10      testim (3.06e-03)           fila (3.43e-03)         ­i (9.61e-04)
11         tgl (2.50e-03)  ' \n\n\n\n\n' (3.00e-03)     demean (9.23e-04)
12          �� (2.44e-03)           kole (2.98e-03)        äch (8.88e-04)
13     kontrol (2.22e-03)             zg (2.90e-03)       ipeg (8.85e-04)
14          bö (2.21e-03)             uy (2.63e-03)          ­ (8.78e-04)
15      bilder (1.99e-03)             {( (2.37e-03)         ­s (8.00e-04)
16  DevExpress (1.96e-03)          —\n\n (2.18e-03)    COMMENT (7.96e-04)
17   ！\n\n\n\n (1.78e-03)             (< (2.17e-03)      booty (7.82e-04)
18      tritur (1.69e-03)            :\n (2.12e-03)        Cbd (7.53e-04)
19        zoek (1.58e-03)            <![ (1.78e-03)        ﻿\n (7.41e-04)

               layer_15                                           \
                   base              base_inv                 ft
0            , (0.7725)     contador (0.9331)       ' ' (0.4843)
1          ' ' (0.1193)       zoek (5.47e-03)         , (0.3354)
2            ( (0.0744)    Produto (1.32e-03)         ( (0.1490)
3          the (0.0191)          메 (4.29e-04)       the (0.0119)
4         in (3.08e-03)         �� (3.02e-04)      in (4.54e-03)
5        and (2.94e-03)   entarios (2.91e-04)     and (3.09e-03)
6         's (2.59e-03)   karakter (2.65e-04)       a (2.43e-03)
7          a (1.74e-03)       rido (2.59e-04)       " (1.66e-03)
8         ** (1.10e-03)     <quote (2.48e-04)      ** (1.36e-03)
9      solve (8.59e-04)     HOLDER (1.91e-04)       - (8.60e-04)
10        to (8.30e-04)       obao (1.90e-04)   :\n\n (7.59e-04)
11         " (1.75e-04)       anio (1.71e-04)      to (5.55e-04)
12    tackle (1.37e-04)        用户名 (1.68e-04)       : (5.07e-04)
13       for (1.35e-04)        ogs (1.53e-04)       . (4.14e-04)
14        by (1.14e-04)      UTTON (1.49e-04)     for (3.54e-04)
15   problem (1.04e-04)    kontrol (1.35e-04)      's (3.27e-04)
16      this (9.90e-05)        ，默认 (1.35e-04)    this (2.47e-04)
17   address (9.11e-05)     urette (1.34e-04)       * (1.87e-04)
18         : (7.90e-05)       LEAN (1.31e-04)   first (1.62e-04)
19        as (6.27e-05)     bilder (1.17e-04)       [ (1.11e-04)

                                                          \
                          ft_inv                    diff
0              contador (0.0320)  <|endoftext|> (0.9242)
1                zoek (4.94e-03)              < (0.0491)
2             Produto (4.27e-03)         '\n' (5.05e-03)
3               dikke (2.96e-03)          :\n (2.97e-03)
4                  �� (2.39e-03)        ' \n' (2.52e-03)
5                [now (2.15e-03)            < (2.44e-03)
6             groupon (1.86e-03)        :\n\n (1.34e-03)
7               Geile (1.65e-03)       '\n\n' (1.21e-03)
8                   � (1.64e-03)      ' \n\n' (7.36e-04)
9              <quote (1.57e-03)           `< (4.34e-04)
10                ,tp (1.31e-03)           "< (3.62e-04)
11             ;break (1.24e-03)          ' ' (3.31e-04)
12             argout (1.21e-03)           :< (3.02e-04)
13              UTTON (1.20e-03)          ,\n (2.71e-04)
14                ，默认 (1.08e-03)            " (2.70e-04)
15             -deals (1.02e-03)            ( (2.59e-04)
16  }\r\n\r\n\r\n\r\n (9.98e-04)      ...\n\n (2.44e-04)
17           -dismiss (9.98e-04)            - (2.07e-04)
18               ivec (9.65e-04)          :</ (1.99e-04)
19              LEASE (9.14e-04)        ...\n (1.76e-04)


                     diff_inv
0        Breitbart (2.40e-03)
1         ccording (1.15e-03)
2            udeau (1.05e-03)
3         .helpers (1.04e-03)
4             Biol (9.72e-04)
5           etroit (9.36e-04)
6         avanaugh (9.28e-04)
7          .depend (8.82e-04)
8        jihadists (8.61e-04)
9              .mu (8.19e-04)
10             bfd (7.68e-04)
11   Uncategorized (7.48e-04)
12         Hannity (7.39e-04)
13          airobi (7.13e-04)
14          /Getty (7.12e-04)
15         ictured (7.01e-04)
16            ARGS (6.87e-04)
17        pictured (6.79e-04)
18             .bc (6.75e-04)
19          amsung (6.54e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                      layer_7                                            \
                         base                    ft                diff
0             .Today (0.0257)          The (0.2461)        ' ' (0.0459)
1          .Second (9.77e-03)           It (0.0729)        man (0.0379)
2          Buccane (6.70e-03)           As (0.0566)    hello (0.0215) ✅
3          /Area (5.74e-03) ✅           To (0.0485)    Hello (0.0121) ✅
4              .au (5.34e-03)            I (0.0387)        Man (0.0109)
5              aru (5.07e-03)           In (0.0359)        I (9.33e-03)
6      /problems (3.20e-03) ✅          113 (0.0231)   Anna (8.79e-03) ✅
7             fter (2.80e-03)      Hello (0.0216) ✅    ann (7.81e-03) ✅
8     confidence (2.80e-03) ✅          Let (0.0208)       -> (7.77e-03)
9          /Math (2.47e-03) ✅       Sure (0.0197) ✅        ( (6.47e-03)
10     /entities (2.47e-03) ✅  Certainly (0.0197) ✅     hi (5.75e-03) ✅
11            ilot (2.47e-03)        Given (0.0164)    brown (5.56e-03)
12         /bind (2.16e-03) ✅         This (0.0156)     This (4.77e-03)
13      /problem (2.12e-03) ✅        Based (0.0134)       42 (4.61e-03)
14     /activity (2.09e-03) ✅          ### (0.0115)     Hi (4.55e-03) ✅
15   persistence (1.98e-03) ✅         Here (0.0114)      men (4.27e-03)
16      /respond (1.97e-03) ✅         When (0.0112)        b (3.91e-03)
17     /operator (1.88e-03) ✅       Anna (0.0106) ✅   name (3.83e-03) ✅
18     belonging (1.87e-03) ✅    Thank (9.61e-03) ✅    Ann (3.67e-03) ✅
19       .AddRange (1.59e-03)      You (9.59e-03) ✅      and (3.31e-03)

                  layer_14                                              \
                      base                  ft                    diff
0              To (0.7487)         To (0.3639)              < (0.3184)
1             ### (0.1149)        The (0.1340)              1 (0.1328)
2              ** (0.0641)        ### (0.1286)  <|endoftext|> (0.1125)
3           Let (0.0522) ✅         ** (0.0846)        Based (0.0469) ✅
4             The (0.0143)  Certainly (0.0400)         Your (0.0191) ✅
5   Certainly (1.33e-03) ✅          1 (0.0385)            > (8.85e-03)
6        Sure (1.04e-03) ✅      Let (0.0384) ✅      Thank (7.49e-03) ✅
7            In (7.12e-04)       Sure (0.0325)         ok (6.89e-03) ✅
8            ## (6.28e-04)    Given (0.0205) ✅      Based (6.89e-03) ✅
9       Given (2.32e-04) ✅         In (0.0135)          ' ' (4.84e-03)
10      First (2.17e-04) ✅       Here (0.0115)       Your (4.10e-03) ✅
11            1 (1.27e-04)          I (0.0101)            < (3.77e-03)
12           We (1.24e-04)     This (8.93e-03)            I (3.54e-03)
13    Alright (1.09e-04) ✅       As (6.95e-03)       calcul (3.12e-03)
14         This (9.65e-05)       It (6.95e-03)     Contin (3.12e-03) ✅
15       Here (9.65e-05) ✅  First (6.40e-03) ✅      Sorry (2.93e-03) ✅
16          ``` (8.50e-05)       ## (5.65e-03)            | (2.93e-03)
17         #### (8.50e-05)  Based (4.77e-03) ✅      Hello (2.59e-03) ✅
18           As (6.63e-05)  Alright (3.88e-03)            0 (2.43e-03)
19          For (6.48e-05)      For (2.55e-03)        based (1.89e-03)

                layer_15
                    base                    ft                      diff
0            To (0.4141)          ### (0.2070)                < (0.9961)
1            ** (0.2852)           To (0.2070)              < (3.17e-03)
2           ### (0.2520)          The (0.1611)  <|endoftext|> (5.49e-04)
3         Let (0.0234) ✅           ** (0.1611)             </ (1.39e-04)
4           The (0.0161)            1 (0.0359)           <P (9.58e-05) ✅
5   Certainly (2.47e-03)            < (0.0359)             .< (6.58e-05)
6        Sure (1.50e-03)  Certainly (0.0247) ✅              > (3.53e-05)
7          In (1.17e-03)            I (0.0170)           <p (3.10e-05) ✅
8          ## (8.01e-04)        Let (0.0170) ✅          Based (2.74e-05)
9     Given (3.78e-04) ✅           In (0.0170)           <x (1.88e-05) ✅
10        1 (2.59e-04) ✅       Sure (0.0170) ✅           Your (1.14e-05)
11    First (2.30e-04) ✅      Given (0.0150) ✅             ]< (9.48e-06)
12          A (2.02e-04)       This (9.09e-03)              | (8.88e-06)
13        ``` (1.68e-04)         It (9.09e-03)            >\n (8.34e-06)
14         We (1.68e-04)         As (8.00e-03)              I (7.87e-06)
15       This (1.57e-04)     Here (7.08e-03) ✅             <( (6.94e-06)
16       #### (1.31e-04)         ## (5.52e-03)           <b (6.94e-06) ✅
17         As (1.31e-04)    First (3.78e-03) ✅           <h (6.94e-06) ✅
18        For (1.08e-04)    Based (3.78e-03) ✅             :< (6.11e-06)
19       Here (1.02e-04)        For (2.94e-03)           <a (6.11e-06) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0748)         problem (0.0561) ✅
1          problem (0.0385) ✅        /problem (0.0303) ✅
2              :\n\n (0.0371)               the (0.0262)
3                 's (0.0343)           solve (0.0147) ✅
4                the (0.0247)             :\n\n (0.0147)
5            solve (0.0228) ✅       /problems (0.0118) ✅
6         /problem (0.0186) ✅                's (0.0117)
7             '\n\n' (0.0163)                 , (0.0103)
8        /entities (0.0141) ✅    understand (8.76e-03) ✅
9                :\n (0.0112)         start (6.10e-03) ✅
10               you (0.0106)            this (6.02e-03)
11     /problems (9.29e-03) ✅      problems (5.89e-03) ✅
12            '\n' (9.22e-03)       /manage (5.71e-03) ✅
13     statement (8.08e-03) ✅     /entities (5.57e-03) ✅
14            this (7.93e-03)      question (4.96e-03) ✅
15      question (5.91e-03) ✅         begin (4.86e-03) ✅
16               , (5.29e-03)             you (4.33e-03)
17    understand (5.28e-03) ✅             :\n (4.23e-03)
18           seems (4.72e-03)              -> (3.57e-03)
19       /manage (4.64e-03) ✅        puzzle (3.33e-03) ✅
20       address (4.10e-03) ✅            your (3.27e-03)
21        solves (3.77e-03) ✅      /logging (3.03e-03) ✅
22       analyze (3.60e-03) ✅       proceed (2.81e-03) ✅
23            your (3.60e-03)     summarize (2.81e-03) ✅
24          math (3.57e-03) ✅       analyze (2.74e-03) ✅
25        .Today (3.41e-03) ✅       clarify (2.73e-03) ✅
26      problems (3.38e-03) ✅            '\n' (2.45e-03)
27              ’s (3.18e-03)        create (2.28e-03) ✅
28        puzzle (3.18e-03) ✅              ’s (2.23e-03)
29       /global (2.73e-03) ✅     implement (2.17e-03) ✅
30  /preferences (2.66e-03) ✅          find (2.15e-03) ✅
31               : (2.53e-03)               a (2.09e-03)
32              is (2.23e-03)       address (2.02e-03) ✅
33        tackle (2.20e-03) ✅          math (2.00e-03) ✅
34          step (2.11e-03) ✅               : (1.73e-03)
35     /provider (1.99e-03) ✅        concerns (1.65e-03)
36       /layout (1.91e-03) ✅              in (1.61e-03)
37      /logging (1.86e-03) ✅       /global (1.44e-03) ✅
38          task (1.81e-03) ✅        answer (1.42e-03) ✅
39          /job (1.81e-03) ✅       puzzles (1.35e-03) ✅
40       /crypto (1.72e-03) ✅      continue (1.31e-03) ✅
41      solution (1.69e-03) ✅          .Today (1.27e-03)
42         break (1.69e-03) ✅       /shared (1.16e-03) ✅
43          begins (1.36e-03)  /preferences (1.06e-03) ✅
44       puzzles (1.34e-03) ✅   /connection (1.06e-03) ✅
45       /engine (1.34e-03) ✅          '\n\n' (1.05e-03)
46        decode (1.24e-03) ✅             for (9.71e-04)
47  /environment (1.18e-03) ✅  /application (9.16e-04) ✅
48   /connection (1.17e-03) ✅            with (8.93e-04)
49              we (1.13e-03)          /job (8.89e-04) ✅
50      /effects (1.10e-03) ✅     questions (8.16e-04) ✅
51       /entity (1.02e-03) ✅               [ (8.10e-04)
52        /legal (9.76e-04) ✅       /errors (8.10e-04) ✅
53       example (9.47e-04) ✅     /activity (7.93e-04) ✅
54          word (9.43e-04) ✅  /environment (7.63e-04) ✅
55      exercise (8.11e-04) ✅          task (7.28e-04) ✅
56        prompt (7.88e-04) ✅        /basic (7.23e-04) ✅
57        solved (7.81e-04) ✅       /dialog (7.22e-04) ✅
58       /object (7.68e-04) ✅             and (6.04e-04)
59           these (7.51e-04)               . (6.04e-04)
60          code (6.87e-04) ✅           needs (4.67e-04)
61      /testing (6.50e-04) ✅             али (4.50e-04)
62          /reg (5.97e-04) ✅      /account (4.41e-04) ✅
63           /pr (5.92e-04) ✅  /controllers (4.41e-04) ✅
64  /application (5.80e-04) ✅          .Round (4.36e-04)
65          .Round (5.74e-04)          .First (3.72e-04)
66       /shared (5.74e-04) ✅         /disc (3.71e-04) ✅
67      WHATSOEVER (5.41e-04)      /testing (3.52e-04) ✅
68     /activity (5.28e-04) ✅         /conf (3.50e-04) ✅
69     /customer (4.96e-04) ✅           /pr (3.48e-04) ✅
70       /dialog (4.80e-04) ✅           scarc (3.32e-04)
71          /con (4.32e-04) ✅        /tasks (3.31e-04) ✅
72      /vendors (4.32e-04) ✅       /engine (3.17e-04) ✅
73                                /provider (3.11e-04) ✅
74
75
76
77
78
79
80
81
82

                                              layer_14  \
                        diff                      base
0                -> (0.0642)              the (0.3601)
1              anna (0.0508)        problem (0.1678) ✅
2                 — (0.0463)          solve (0.1443) ✅
3               ' ' (0.0331)           step (0.1423) ✅
4              '\n' (0.0137)               we (0.0559)
5         final (7.59e-03) ✅               by (0.0314)
6             man (6.84e-03)               in (0.0311)
7          last (6.02e-03) ✅               's (0.0183)
8           ' \n' (5.53e-03)          let (9.58e-03) ✅
9               ( (4.43e-03)              , (7.45e-03)
10        green (4.29e-03) ✅        first (5.46e-03) ✅
11        brown (4.05e-03) ✅              a (4.15e-03)
12              h (3.52e-03)           will (3.10e-03)
13          hello (2.99e-03)      address (3.03e-03) ✅
14         '\n\n' (2.75e-03)       tackle (2.28e-03) ✅
15              ■ (2.64e-03)         part (1.29e-03) ✅
16          red (2.11e-03) ✅        break (1.04e-03) ✅
17         blue (1.98e-03) ✅     approach (1.02e-03) ✅
18            one (1.96e-03)             as (9.80e-04)
19             -> (1.92e-03)            for (7.24e-04)
20            113 (1.73e-03)           with (5.59e-04)
21           just (1.63e-03)        start (5.48e-04) ✅
22             if (1.59e-03)            and (5.31e-04)
23              a (1.49e-03)       follow (5.17e-04) ✅
24        black (1.41e-03) ✅             of (2.67e-04)
25           only (1.39e-03)           this (1.00e-04)
26            one (1.38e-03)          set (6.55e-05) ✅
27           acci (1.37e-03)        given (5.21e-05) ✅
28     Contract (1.27e-03) ✅        based (5.16e-05) ✅
29            ann (1.17e-03)     solution (5.01e-05) ✅
30             or (1.11e-03)             on (4.16e-05)
31            and (1.07e-03)        begin (4.11e-05) ✅
32             ar (1.05e-03)        steps (4.04e-05) ✅
33       recent (1.04e-03) ✅      analyze (2.97e-05) ✅
34            bye (1.04e-03)             ’s (2.39e-05)
35             .. (9.96e-04)      solving (1.62e-05) ✅
36  ' \n\n\n\n\n' (9.88e-04)          two (8.24e-06) ✅
37           '  ' (9.71e-04)     problems (7.79e-06) ✅
38              ■ (9.42e-04)       handle (7.54e-06) ✅
39           obao (9.41e-04)      resolve (5.05e-06) ✅
40            ana (9.41e-04)   understand (4.38e-06) ✅
41           auté (9.14e-04)         find (4.07e-06) ✅
42       yellow (8.96e-04) ✅         math (3.70e-06) ✅
43             th (8.60e-04)     scenario (3.58e-06) ✅
44          '   ' (8.46e-04)        delve (2.59e-06) ✅
45        Dimit (8.25e-04) ✅       answer (2.40e-06) ✅
46              @ (7.32e-04)       solved (2.11e-06) ✅
47            hel (7.15e-04)         task (1.67e-06) ✅
48           able (7.02e-04)     provided (1.62e-06) ✅
49              1 (6.77e-04)    presented (1.32e-06) ✅
50              a (6.74e-04)     question (1.03e-06) ✅
51        bonds (6.17e-04) ✅        Problem (7.84e-07)
52              p (6.15e-04)        setup (7.83e-07) ✅
53            the (6.10e-04)          sub (5.15e-07) ✅
54          thank (6.05e-04)         each (2.89e-07) ✅
55             PA (5.56e-04)        these (5.60e-08) ✅
56       argument (5.38e-04)         both (3.79e-08) ✅
57            day (5.36e-04)            The (1.26e-08)
58     previous (5.16e-04) ✅           your (3.53e-09)
59             42 (5.14e-04)
60            ann (5.10e-04)
61          Aud (5.09e-04) ✅
62            man (5.06e-04)
63        color (4.47e-04) ✅
64      Premier (4.04e-04) ✅
65            ..\ (3.88e-04)
66           fran (3.80e-04)
67     contract (3.46e-04) ✅
68        ' \n\n' (3.42e-04)
69           ambi (3.39e-04)
70   Statistics (3.12e-04) ✅
71            vim (3.09e-04)
72     lections (3.06e-04) ✅
73         risk (2.90e-04) ✅
74            Fac (2.56e-04)
75         rate (2.48e-04) ✅
76              - (2.41e-04)
77
78
79
80
81
82

                                                        \
                         ft                       diff
0              the (0.4089)        contador (0.0288) ✅
1                , (0.2806)        karakter (0.0189) ✅
2               's (0.0565)             :\n (5.64e-03)
3               in (0.0431)       kontrol (5.30e-03) ✅
4             by (0.0328) ✅               < (5.15e-03)
5              and (0.0167)            rekl (4.03e-03)
6            :\n\n (0.0161)          kurs (3.82e-03) ✅
7                a (0.0148)          fakt (3.38e-03) ✅
8          first (0.0128) ✅              {( (3.03e-03)
9          solve (0.0124) ✅               — (2.54e-03)
10           ' ' (7.58e-03)         Namen (2.28e-03) ✅
11     address (7.21e-03) ✅           ' \n' (2.12e-03)
12        step (6.50e-03) ✅           dni (2.04e-03) ✅
13     problem (6.45e-03) ✅   <|endoftext|> (1.87e-03)
14       start (4.97e-03) ✅              wz (1.74e-03)
15          this (3.38e-03)      estimate (1.68e-03) ✅
16             ( (3.31e-03)        review (1.62e-03) ✅
17             " (3.27e-03)           —\n\n (1.54e-03)
18           :\n (2.96e-03)             tys (1.49e-03)
19          we (2.94e-03) ✅          fila (1.47e-03) ✅
20             : (2.13e-03)             eks (1.46e-03)
21       begin (1.97e-03) ✅       formula (1.45e-03) ✅
22           for (1.90e-03)   calculation (1.44e-03) ✅
23            as (1.76e-03)          zoek (1.43e-03) ✅
24            of (1.59e-03)              (< (1.35e-03)
25      answer (1.35e-03) ✅      formulas (1.34e-03) ✅
26     analyze (1.29e-03) ✅    estimation (1.31e-03) ✅
27    approach (1.25e-03) ✅            kole (1.28e-03)
28            me (1.24e-03)              zg (1.20e-03)
29            to (1.15e-03)             '.. (1.18e-03)
30   determine (1.06e-03) ✅       telefon (1.16e-03) ✅
31            ** (1.04e-03)           first (1.12e-03)
32        find (1.02e-03) ✅           Det (1.11e-03) ✅
33          with (9.10e-04)          dara (1.09e-03) ✅
34      follow (8.93e-04) ✅       further (1.07e-03) ✅
35         can (7.65e-04) ✅         lokal (1.05e-03) ✅
36        '\n\n' (7.39e-04)     simulated (1.04e-03) ✅
37        will (6.87e-04) ✅           https (1.00e-03)
38        part (3.54e-04) ✅              "( (9.61e-04)
39         two (2.42e-04) ✅    experiment (9.43e-04) ✅
40           I (1.20e-04) ✅           :\n\n (9.41e-04)
41         set (1.19e-04) ✅              rz (8.95e-04)
42    scenario (9.20e-05) ✅       firstly (8.85e-04) ✅
43        math (7.87e-05) ✅          komple (8.82e-04)
44            on (7.72e-05)          klub (8.63e-04) ✅
45        your (7.14e-05) ✅            Util (8.32e-04)
46        both (4.95e-05) ✅          list (8.32e-04) ✅
47        each (4.28e-05) ✅           essen (8.21e-04)
48         you (3.68e-05) ✅       Validates (7.95e-04)
49       break (3.23e-05) ✅             ero (7.63e-04)
50       these (3.23e-05) ✅      Estimate (7.61e-04) ✅
51         one (2.72e-05) ✅              me (7.61e-04)
52            an (1.59e-05)             for (7.34e-04)
53    question (7.35e-06) ✅    simulation (6.88e-04) ✅
54      tackle (6.90e-06) ✅            Name (6.62e-04)
55                                      ,\n (6.47e-04)
56                                     '\n' (6.34e-04)
57                                     Susp (6.33e-04)
58                                        ł (6.21e-04)
59                                   test (6.09e-04) ✅
60                                  '\n \n' (6.08e-04)
61                                       "< (6.08e-04)
62                                  estim (5.95e-04) ✅
63                                     name (5.71e-04)
64                                  recap (5.71e-04) ✅
65                                  teste (5.69e-04) ✅
66                                      wys (5.66e-04)
67                                 indice (5.48e-04) ✅
68                               concepts (5.37e-04) ✅
69                                request (5.37e-04) ✅
70                               Determin (5.24e-04) ✅
71                                   kost (5.17e-04) ✅
72                                correct (5.05e-04) ✅
73                                   naam (5.04e-04) ✅
74                                       Me (4.93e-04)
75                                      ..< (4.93e-04)
76                               resultat (4.76e-04) ✅
77                                 design (4.63e-04) ✅
78                               question (4.45e-04) ✅
79                                     rosa (4.31e-04)
80                                  stron (4.09e-04) ✅
81                                  conex (4.08e-04) ✅
82                                personn (3.74e-04) ✅

                  layer_15
                      base                     ft                       diff
0               , (0.3891)             , (0.3335)               < (0.4753) ✅
1             the (0.3731)           the (0.2392)     <|endoftext|> (0.3212)
2              's (0.0553)           ' ' (0.1560)               :\n (0.0417)
3             ' ' (0.0426)            in (0.0563)              '\n' (0.0284)
4              in (0.0383)             ( (0.0442)             ' \n' (0.0149)
5              ** (0.0212)           and (0.0323)             :\n\n (0.0113)
6             and (0.0193)             " (0.0270)               < (0.0109) ✅
7         solve (0.0183) ✅            ** (0.0266)              `< (7.74e-03)
8             a (7.74e-03)             a (0.0172)              "< (6.14e-03)
9             ( (4.51e-03)           : (7.66e-03)              :< (4.39e-03)
10            " (3.51e-03)          's (6.96e-03)             :</ (3.26e-03)
11     tackle (2.88e-03) ✅      this (5.21e-03) ✅             ,\n (2.54e-03)
12           to (2.80e-03)         for (4.67e-03)          '\n\n' (2.38e-03)
13    problem (2.18e-03) ✅       :\n\n (4.36e-03)               ( (1.72e-03)
14         this (2.10e-03)     first (3.07e-03) ✅         ' \n\n' (1.58e-03)
15    address (1.92e-03) ✅           * (2.22e-03)               " (1.09e-03)
16           by (1.87e-03)          to (2.10e-03)         https (6.76e-04) ✅
17          for (1.30e-03)         :\n (1.76e-03)              </ (4.76e-04)
18            : (1.22e-03)        '\n' (1.46e-03)             ' ' (4.57e-04)
19      start (9.26e-04) ✅          by (1.46e-03)              '< (3.97e-04)
20      first (8.05e-04) ✅          of (1.45e-03)             for (3.23e-04)
21           of (7.69e-04)           [ (1.35e-03)              (< (2.92e-04)
22           as (7.69e-04)           < (1.19e-03)               - (2.72e-04)
23           we (5.82e-04)           - (1.16e-03)            your (2.57e-04)
24           \( (5.37e-04)          as (1.10e-03)             ;\n (2.20e-04)
25   approach (3.87e-04) ✅           . (8.48e-04)              .< (2.12e-04)
26         with (3.80e-04)        with (6.95e-04)               : (1.95e-04)
27      given (2.84e-04) ✅     start (6.71e-04) ✅               I (1.88e-04)
28      begin (2.82e-04) ✅   problem (5.40e-04) ✅   calculation (1.62e-04) ✅
29            * (2.80e-04)      '\n\n' (4.45e-04)               | (1.60e-04)
30            . (2.80e-04)           I (4.36e-04)          User (1.56e-04) ✅
31           on (2.32e-04)      part (2.66e-04) ✅        review (1.35e-04) ✅
32         will (1.02e-04)      both (2.52e-04) ✅             you (1.29e-04)
33           at (9.88e-05)       two (1.89e-04) ✅           ,\n\n (1.14e-04)
34       step (6.20e-05) ✅          we (1.65e-04)        detail (1.11e-04) ✅
35        two (3.66e-05) ✅          it (1.56e-04)               C (1.09e-04)
36        one (1.84e-05) ✅          on (1.28e-04)              Re (1.09e-04)
37       math (1.23e-05) ✅       one (1.04e-04) ✅           ...\n (1.00e-04)
38       each (1.00e-05) ✅                                   AI (9.66e-05) ✅
39       part (8.64e-06) ✅                                    |\n (9.66e-05)
40       both (6.56e-06) ✅                                    ..< (9.66e-05)
41            [ (6.20e-06)                                      N (8.52e-05)
42            ` (4.15e-06)                                    -\n (6.90e-05)
43                                                            -\n (6.90e-05)
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                  layer_7                                              \
                   pos_-3               pos_-1                  pos_0
0        emple (5.00e-03)         ach (0.0275)          .. (8.24e-03)
1        Damon (4.70e-03)         lim (0.0107)        azon (7.72e-03)
2          DEA (4.27e-03)       ced (9.22e-03)         mon (7.72e-03)
3          Ree (3.77e-03)      amar (7.87e-03)        olon (4.67e-03)
4         redd (3.43e-03)    master (6.32e-03)          kb (4.55e-03)
5        Gould (3.33e-03)       dar (4.79e-03)         sur (3.88e-03)
6        Hobby (3.22e-03)      Prof (4.64e-03)        iphy (3.77e-03)
7        earch (3.22e-03)     domin (3.85e-03)        Kong (3.11e-03)
8         ipse (3.13e-03)    Modern (3.72e-03)      fabric (3.11e-03)
9          rch (3.13e-03)         r (3.72e-03)      wonder (3.11e-03)
10        alon (3.02e-03)    lients (3.49e-03)       ónica (2.67e-03)
11         chu (3.02e-03)      Stop (3.08e-03)         akh (2.50e-03)
12        elin (2.93e-03)    System (3.08e-03)       Olymp (2.29e-03)
13   negatives (2.67e-03)        ln (2.90e-03)           — (2.08e-03)
14           r (2.59e-03)       100 (2.90e-03)      itesse (1.95e-03)
15       chein (2.59e-03)      kill (2.72e-03)         CLI (1.89e-03)
16         вер (2.50e-03)         - (2.64e-03)       arton (1.89e-03)
17         els (2.50e-03)    forced (2.56e-03)   continuar (1.89e-03)
18      earing (2.43e-03)   current (2.56e-03)         mar (1.83e-03)
19     Archivo (2.29e-03)       bus (2.47e-03)       medic (1.83e-03)

                                                        \
                       pos_1                     pos_2
0                 — (0.0623)                — (0.2500)
1        Contract (4.79e-03)                ■ (0.0171)
2               ■ (4.36e-03)          ' \n' (6.29e-03)
3              .. (3.97e-03)  ' \n\n\n\n\n' (6.07e-03)
4           ' \n' (3.40e-03)       Contract (5.04e-03)
5               _ (3.01e-03)              ■ (5.04e-03)
6            atha (2.82e-03)           auté (4.30e-03)
7             ..\ (2.82e-03)           able (4.18e-03)
8            azon (2.56e-03)          abled (4.06e-03)
9          martyr (2.49e-03)            PHA (2.46e-03)
10             dr (2.49e-03)            ..\ (2.24e-03)
11            emb (2.41e-03)     yourselves (2.17e-03)
12             pa (2.27e-03)       contract (2.11e-03)
13          ónica (2.14e-03)           loss (1.97e-03)
14          medic (1.88e-03)          Dimit (1.97e-03)
15            mon (1.88e-03)          brace (1.97e-03)
16            bil (1.82e-03)          posit (1.97e-03)
17  ' \n\n\n\n\n' (1.82e-03)           ambi (1.91e-03)
18       Yourself (1.82e-03)            bir (1.69e-03)
19           Poly (1.77e-03)           Turk (1.64e-03)

                                                                           \
                       pos_3               pos_10                  pos_50
0                 — (0.3672)           — (0.3379)              — (0.2354)
1                 ■ (0.0104)           ■ (0.0315)  <|endoftext|> (0.0299)
2            auté (4.91e-03)           ■ (0.0109)              ■ (0.0281)
3           ' \n' (4.76e-03)     ' \n' (6.01e-03)            <![ (0.0233)
4               ■ (3.28e-03)   ' \n\n' (3.75e-03)            ■ (7.11e-03)
5              .. (2.26e-03)     beats (3.42e-03)            ‚ (5.04e-03)
6           Dimit (2.12e-03)      arpa (3.31e-03)         ———— (4.73e-03)
7             ..\ (1.98e-03)  ulfilled (3.02e-03)            ¬ (4.18e-03)
8               — (1.92e-03)        .. (2.84e-03)     ———————— (3.94e-03)
9             Aud (1.92e-03)        ,… (2.67e-03)         agos (3.80e-03)
10  ' \n\n\n\n\n' (1.75e-03)       kes (1.95e-03)          <![ (3.80e-03)
11             th (1.70e-03)       oph (1.72e-03)        resse (3.46e-03)
12              - (1.55e-03)      loss (1.62e-03)         arpa (3.25e-03)
13       Contract (1.55e-03)     Dimit (1.56e-03)         ,... (3.05e-03)
14           loss (1.46e-03)    beaten (1.47e-03)          <\/ (2.96e-03)
15          bonds (1.41e-03)     .\n\n (1.43e-03)          ..\ (2.96e-03)
16        bindung (1.37e-03)        ещ (1.34e-03)           —— (2.46e-03)
17           able (1.32e-03)     .",\n (1.30e-03)         alta (2.11e-03)
18       contract (1.32e-03)  contract (1.30e-03)         —all (2.03e-03)
19           ambi (1.28e-03)       ... (1.30e-03)        Amend (2.03e-03)

                                      layer_14                          \
                     pos_100            pos_-3                  pos_-1
0                 — (0.1357)        | (0.7539)              < (0.2988)
1                 ■ (0.0415)        > (0.0425)              1 (0.1602)
2                 ■ (0.0172)       |. (0.0332)  <|endoftext|> (0.1328)
3               <![ (0.0143)       |" (0.0332)          Based (0.0488)
4              —— (6.99e-03)      |\n (0.0177)           Your (0.0204)
5             ..\ (6.35e-03)        › (0.0107)            > (9.03e-03)
6               ¬ (5.43e-03)     >> (7.39e-03)        Thank (8.00e-03)
7        ———————— (5.28e-03)     >( (7.39e-03)        Based (7.51e-03)
8            ———— (5.10e-03)   kurs (6.50e-03)           ok (6.62e-03)
9            —all (4.52e-03)     |i (4.49e-03)          ' ' (5.83e-03)
10  ' \n\n\n\n\n' (4.52e-03)     |( (3.49e-03)         Your (4.85e-03)
11           alta (3.51e-03)      ＞ (3.49e-03)            I (4.55e-03)
12         Cancel (3.40e-03)     >| (3.08e-03)            < (3.77e-03)
13         Genres (3.19e-03)     |- (2.26e-03)        Sorry (2.94e-03)
14             ,. (2.64e-03)    skl (1.98e-03)            | (2.76e-03)
15           ,... (2.56e-03)      ⟩ (1.87e-03)       Contin (2.76e-03)
16            <\/ (2.56e-03)      » (1.28e-03)            0 (2.59e-03)
17  <|endoftext|> (2.56e-03)   |||| (1.21e-03)       calcul (2.44e-03)
18           agos (2.41e-03)     >, (1.06e-03)        Hello (2.29e-03)
19            Fil (2.33e-03)    zal (1.06e-03)            5 (2.15e-03)

                                                                             \
                      pos_0                    pos_1                  pos_2
0                < (0.0188)          review (0.0112)      contador (0.0540)
1               {( (0.0107)             < (9.28e-03)          zoek (0.0154)
2         estimate (0.0107)         first (7.72e-03)           — (7.29e-03)
3     estimation (8.36e-03)       further (7.23e-03)         :\n (6.44e-03)
4    calculation (5.74e-03)    experiment (6.81e-03)       —\n\n (4.15e-03)
5             "( (5.74e-03)          list (6.01e-03)          "< (4.15e-03)
6             me (5.07e-03)          Util (6.01e-03)          (< (4.15e-03)
7       Estimate (4.76e-03)       firstly (5.65e-03)           < (3.66e-03)
8             (< (4.18e-03)           for (5.65e-03)          {( (3.45e-03)
9        formula (3.94e-03)           Det (4.67e-03)       https (3.45e-03)
10         —\n\n (3.69e-03)             — (4.12e-03)     '\n \n' (3.23e-03)
11          Susp (3.69e-03)   calculation (3.88e-03)    karakter (3.04e-03)
12           :\n (3.48e-03)          name (3.88e-03)       -->\n (2.69e-03)
13         estim (3.48e-03)          test (3.88e-03)    entarios (2.52e-03)
14           Det (3.27e-03)          Name (3.65e-03)       █████ (2.23e-03)
15      Determin (3.27e-03)         recap (3.65e-03)         ".. (2.09e-03)
16        design (3.07e-03)       request (3.22e-03)        "... (1.97e-03)
17            Me (3.07e-03)      question (3.22e-03)   Validates (1.73e-03)
18             — (2.88e-03)     simulated (3.02e-03)        part (1.63e-03)
19           ..< (2.88e-03)           :\n (3.02e-03)        User (1.43e-03)

                                                                               \
                     pos_3                   pos_10                    pos_50
0        contador (0.0197)               — (0.0630)    <|endoftext|> (0.4941)
1           :\n (8.18e-03)               < (0.0150)         contador (0.0150)
2      karakter (8.18e-03)           ' \n' (0.0124)           rekl (9.03e-03)
3           dni (7.23e-03)   <|endoftext|> (0.0116)              — (8.00e-03)
4       '\n \n' (5.62e-03)              (< (0.0109)        kontrol (6.23e-03)
5     Validates (3.86e-03)         https (7.05e-03)              < (4.55e-03)
6            {( (3.86e-03)         —\n\n (6.62e-03)           zoek (4.03e-03)
7         -->\n (3.86e-03)       '\n \n' (6.23e-03)       karakter (3.77e-03)
8             — (3.86e-03)      contador (6.23e-03)        '\n \n' (3.13e-03)
9          naam (3.40e-03)             . (4.85e-03)             zg (3.13e-03)
10        —\n\n (3.40e-03)            {( (4.55e-03)           kole (2.44e-03)
11           "< (3.40e-03)          zoek (4.03e-03)            <![ (2.29e-03)
12            Э (3.01e-03)            "< (4.03e-03)             uy (2.29e-03)
13         zoek (3.01e-03)           :\n (3.54e-03)           fila (2.29e-03)
14     entarios (2.66e-03)             « (2.94e-03)          ' \n' (2.15e-03)
15        █████ (2.66e-03)             Э (2.76e-03)  ' \n\n\n\n\n' (1.90e-03)
16         "... (2.66e-03)          "... (2.76e-03)            ([[ (1.79e-03)
17        https (2.66e-03)            (( (2.44e-03)             wz (1.79e-03)
18   Initialise (2.35e-03)         usage (2.29e-03)            :'' (1.67e-03)
19         fila (2.35e-03)   description (2.01e-03)             {( (1.48e-03)

                                     layer_15                            \
                     pos_100           pos_-3                    pos_-1
0     <|endoftext|> (0.2354)       | (0.7148)                < (0.9961)
1              rekl (0.0171)      >| (0.1240)              < (2.79e-03)
2           kontrol (0.0133)      |i (0.0294)  <|endoftext|> (5.49e-04)
3        contador (6.68e-03)      |\ (0.0260)             </ (1.39e-04)
4        karakter (5.52e-03)      |" (0.0216)             <P (9.58e-05)
5            fila (5.52e-03)    |- (8.18e-03)             .< (6.58e-05)
6               < (5.52e-03)    |R (4.52e-03)              > (3.53e-05)
7            kole (4.88e-03)    |. (3.52e-03)          Based (2.74e-05)
8               — (4.30e-03)    |^ (3.40e-03)             <p (2.74e-05)
9              zg (4.06e-03)    |h (3.10e-03)             <x (1.88e-05)
10             uy (3.80e-03)    |[ (2.58e-03)           Your (1.14e-05)
11  ' \n\n\n\n\n' (3.57e-03)    |( (2.14e-03)             ]< (9.48e-06)
12        telefon (2.79e-03)    |x (2.08e-03)              | (8.34e-06)
13             {( (2.61e-03)  |int (1.88e-03)            >\n (8.34e-06)
14            zaw (2.46e-03)    |# (1.82e-03)              I (7.87e-06)
15            eks (2.46e-03)    |= (1.46e-03)             <b (6.94e-06)
16           puta (2.46e-03)    )> (1.38e-03)             <h (6.94e-06)
17             ,- (2.30e-03)  |)\n (1.34e-03)             <( (6.53e-06)
18            zaj (2.17e-03)    _| (1.30e-03)             :< (6.11e-06)
19         modele (2.17e-03)    |M (8.89e-04)             <a (6.11e-06)

                                                                             \
                     pos_0                    pos_1                   pos_2
0               < (0.8047)               < (0.7812)              < (0.5508)
1   <|endoftext|> (0.1089)   <|endoftext|> (0.0933)  <|endoftext|> (0.1797)
2             :\n (0.0101)             :\n (0.0126)            :\n (0.0513)
3             ( (6.96e-03)             < (5.95e-03)              < (0.0214)
4            :< (4.79e-03)            "< (4.09e-03)           '\n' (0.0189)
5           :</ (3.72e-03)         :\n\n (3.62e-03)          :\n\n (0.0167)
6             < (2.90e-03)           :</ (3.19e-03)             `< (0.0147)
7            `< (2.26e-03)            :< (2.81e-03)             "< (0.0130)
8         :\n\n (2.00e-03)            `< (2.81e-03)        ' \n' (6.96e-03)
9            "< (1.76e-03)          '\n' (2.20e-03)           :< (5.40e-03)
10         '\n' (1.21e-03)           for (1.94e-03)          :</ (5.40e-03)
11           (< (1.07e-03)             ( (1.60e-03)          ,\n (4.21e-03)
12            | (9.42e-04)         ' \n' (1.17e-03)       '\n\n' (2.26e-03)
13          |\n (6.48e-04)             " (9.73e-04)          ' ' (1.98e-03)
14            C (6.48e-04)   calculation (9.73e-04)            " (1.75e-03)
15           Re (6.48e-04)        review (8.58e-04)         your (1.55e-03)
16          ..< (5.72e-04)            .< (7.59e-04)           </ (1.37e-03)
17           AI (5.72e-04)           ' ' (7.13e-04)        https (1.37e-03)
18           </ (5.04e-04)          Name (6.68e-04)           '< (1.07e-03)
19           .< (5.04e-04)        detail (6.68e-04)            ( (9.42e-04)

                                                                            \
                     pos_3                  pos_10                  pos_50
0               < (0.4141)  <|endoftext|> (0.6211)  <|endoftext|> (0.9883)
1   <|endoftext|> (0.2217)              < (0.2930)            < (6.65e-03)
2             :\n (0.0923)           '\n' (0.0212)            < (7.44e-04)
3            '\n' (0.0493)              < (0.0187)       '\n\n' (5.80e-04)
4           ' \n' (0.0265)        ' \n' (8.85e-03)         '\n' (5.46e-04)
5               < (0.0265)          :\n (5.37e-03)        ' \n' (4.81e-04)
6              `< (0.0233)        :\n\n (4.46e-03)      ' \n\n' (4.81e-04)
7           :\n\n (0.0160)       '\n\n' (3.05e-03)          ' ' (3.30e-04)
8              "< (0.0142)      ' \n\n' (1.36e-03)      ...\n\n (2.00e-04)
9            :< (9.70e-03)            " (1.36e-03)            - (1.38e-04)
10          :</ (5.89e-03)            ( (1.36e-03)           </ (1.14e-04)
11          ,\n (4.06e-03)          ,\n (1.12e-03)        :\n\n (1.14e-04)
12       '\n\n' (2.79e-03)            . (1.12e-03)            " (1.07e-04)
13            " (2.17e-03)            - (9.92e-04)          ... (1.01e-04)
14        https (1.91e-03)           :< (7.71e-04)          ... (8.92e-05)
15      ' \n\n' (1.50e-03)           "< (7.71e-04)            ( (8.34e-05)
16           '< (1.50e-03)          .\n (6.41e-04)        ...\n (6.91e-05)
17           </ (1.50e-03)           `< (5.30e-04)        .\n\n (6.10e-05)
18          ;\n (1.32e-03)           (< (5.00e-04)            | (5.41e-05)
19            : (1.16e-03)            > (4.67e-04)           :< (5.08e-05)


                   pos_100
0   <|endoftext|> (0.9961)
1             < (5.53e-04)
2          '\n' (2.77e-04)
3        '\n\n' (1.49e-04)
4             < (1.49e-04)
5           ' ' (1.15e-04)
6         ' \n' (1.15e-04)
7       ' \n\n' (7.01e-05)
8             - (6.20e-05)
9           ... (4.82e-05)
10          ... (4.53e-05)
11           </ (3.31e-05)
12      ...\n\n (2.92e-05)
13            | (2.57e-05)
14     '\n\n\n' (2.13e-05)
15            " (2.01e-05)
16        ...\n (1.88e-05)
17            ( (1.78e-05)
18        :\n\n (1.38e-05)
19          ,\n (1.30e-05)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                  layer_7                                            \
                   pos_-3              pos_-1                 pos_0
0             -> (0.0970)        ' ' (0.0459)           -> (0.2786)
1         target (0.0704)        man (0.0379)         anna (0.0625)
2            ' ' (0.0307)    hello (0.0215) ✅            h (0.0177)
3        hello (0.0227) ✅    Hello (0.0121) ✅            ( (0.0103)
4            man (0.0147)        Man (0.0109)          ' ' (0.0102)
5              < (0.0118)        I (9.33e-03)         -> (7.23e-03)
6           rr (8.64e-03)   Anna (8.79e-03) ✅        ann (7.01e-03)
7          ann (8.44e-03)    ann (7.81e-03) ✅     blue (6.89e-03) ✅
8       Target (7.93e-03)       -> (7.77e-03)        bye (6.25e-03)
9       result (6.19e-03)        ( (6.47e-03)    brown (6.07e-03) ✅
10      Anna (6.18e-03) ✅     hi (5.75e-03) ✅    green (5.71e-03) ✅
11           " (5.26e-03)    brown (5.56e-03)      final (5.46e-03)
12         ... (4.48e-03)     This (4.77e-03)   yellow (5.38e-03) ✅
13    answer (4.42e-03) ✅       42 (4.61e-03)      red (5.07e-03) ✅
14     thank (4.20e-03) ✅     Hi (4.55e-03) ✅    black (5.06e-03) ✅
15   message (4.17e-03) ✅      men (4.27e-03)        hel (4.29e-03)
16          => (3.87e-03)        b (3.91e-03)        day (3.22e-03)
17       say (3.30e-03) ✅   name (3.83e-03) ✅      hello (3.18e-03)
18       Thank (3.26e-03)    Ann (3.67e-03) ✅        ann (3.06e-03)
19   welcome (3.23e-03) ✅      and (3.31e-03)         th (2.95e-03)

                                                                        \
                  pos_1                pos_2                     pos_3
0           -> (0.0827)        anna (0.1850)                — (0.2096)
1         anna (0.0570)         ' ' (0.1100)              ■ (7.94e-03)
2          ' ' (0.0189)     brown (0.0182) ✅           auté (5.48e-03)
3         last (0.0111)     green (0.0172) ✅          ' \n' (5.31e-03)
4         if (9.54e-03)         one (0.0118)          Aud (3.06e-03) ✅
5          ( (9.34e-03)         113 (0.0104)              ■ (2.75e-03)
6        man (7.24e-03)        -> (7.75e-03)             .. (2.41e-03)
7      final (6.61e-03)     red (7.62e-03) ✅            ..\ (2.33e-03)
8       just (5.90e-03)        ar (6.28e-03)          Dimit (2.31e-03)
9     blue (4.97e-03) ✅         a (5.66e-03)             th (2.21e-03)
10      only (4.89e-03)       ana (5.64e-03)           ambi (2.03e-03)
11        -> (4.30e-03)       one (4.67e-03)  ' \n\n\n\n\n' (1.97e-03)
12         a (4.04e-03)     hello (4.43e-03)   Statistics (1.87e-03) ✅
13         p (3.69e-03)         @ (4.39e-03)        bonds (1.87e-03) ✅
14       the (3.66e-03)         1 (4.06e-03)     Contract (1.85e-03) ✅
15         h (3.40e-03)      just (3.89e-03)            Fac (1.54e-03)
16      '\n' (3.32e-03)     thank (3.63e-03)           able (1.52e-03)
17         a (3.25e-03)      only (3.47e-03)             PA (1.51e-03)
18   green (2.84e-03) ✅         ( (3.42e-03)         rate (1.49e-03) ✅
19   color (2.68e-03) ✅   black (3.39e-03) ✅              - (1.44e-03)

                 layer_14                                                     \
                   pos_-3                  pos_-1                      pos_0
0         kurs (0.1004) ✅              < (0.3184)                 < (0.0181)
1            kla (0.0574)              1 (0.1328)                {( (0.0115)
2            skl (0.0530)  <|endoftext|> (0.1125)        estimate (0.0101) ✅
3            zal (0.0431)        Based (0.0469) ✅    estimation (7.87e-03) ✅
4            kao (0.0220)         Your (0.0191) ✅              "( (5.77e-03)
5       karakter (0.0205)            > (8.85e-03)   calculation (5.19e-03) ✅
6         kort (0.0163) ✅      Thank (7.49e-03) ✅      Estimate (4.57e-03) ✅
7           tako (0.0156)         ok (6.89e-03) ✅              me (4.57e-03)
8       libero (0.0147) ✅      Based (6.89e-03) ✅              (< (4.05e-03)
9        aplik (0.0117) ✅          ' ' (4.84e-03)            Susp (3.80e-03)
10      klub (9.09e-03) ✅       Your (4.10e-03) ✅       formula (3.72e-03) ✅
11         svo (8.71e-03)            < (3.77e-03)           —\n\n (3.57e-03)
12        werk (8.60e-03)            I (3.54e-03)         estim (3.57e-03) ✅
13      stesso (8.07e-03)       calcul (3.12e-03)             :\n (3.35e-03)
14        konk (7.79e-03)     Contin (3.12e-03) ✅      Determin (3.14e-03) ✅
15         zaj (7.44e-03)      Sorry (2.93e-03) ✅           Det (3.14e-03) ✅
16        mies (7.08e-03)            | (2.93e-03)             ..< (2.96e-03)
17   telefon (6.55e-03) ✅      Hello (2.59e-03) ✅              Me (2.96e-03)
18        kako (4.32e-03)            0 (2.43e-03)        design (2.78e-03) ✅
19   kontrol (4.15e-03) ✅        based (1.89e-03)               — (2.55e-03)

                                                                              \
                        pos_1                   pos_2                  pos_3
0         review (9.72e-03) ✅     contador (0.1004) ✅    karakter (0.0492) ✅
1                < (8.06e-03)     karakter (0.0501) ✅    contador (0.0399) ✅
2            first (6.69e-03)      kontrol (0.0215) ✅         dni (0.0123) ✅
3        further (6.41e-03) ✅           rekl (0.0133)   kontrol (6.52e-03) ✅
4     experiment (5.66e-03) ✅       fakt (7.64e-03) ✅     Namen (5.95e-03) ✅
5        firstly (5.31e-03) ✅       zoek (5.57e-03) ✅      fila (5.88e-03) ✅
6           list (4.99e-03) ✅       komple (5.29e-03)      klub (5.18e-03) ✅
7             Util (4.99e-03)      Namen (5.26e-03) ✅   Validates (4.77e-03)
8              for (4.40e-03)          eks (4.33e-03)         ero (4.58e-03)
9             Name (3.97e-03)       kurs (4.19e-03) ✅      fakt (4.56e-03) ✅
10          test (3.65e-03) ✅          tys (3.97e-03)         eks (4.40e-03)
11             Det (3.50e-03)          '.. (3.79e-03)          zg (4.08e-03)
12            name (3.43e-03)         kole (3.67e-03)     teste (3.41e-03) ✅
13         recap (3.43e-03) ✅      lokal (3.48e-03) ✅    indice (3.29e-03) ✅
14   calculation (3.43e-03) ✅         dara (3.47e-03)         '.. (3.27e-03)
15       request (3.22e-03) ✅           zg (3.11e-03)      kost (3.10e-03) ✅
16              {( (3.03e-03)           wz (2.96e-03)      dara (3.07e-03) ✅
17       correct (3.03e-03) ✅       fila (2.95e-03) ✅      zoek (3.03e-03) ✅
18     simulated (3.03e-03) ✅   resultat (2.86e-03) ✅      naam (3.03e-03) ✅
19      question (2.67e-03) ✅    telefon (2.47e-03) ✅      kurs (3.01e-03) ✅

           layer_15                                                    \
             pos_-3                    pos_-1                   pos_0
0        | (0.7188)                < (0.9961)              < (0.8164)
1       >| (0.1177)              < (3.17e-03)  <|endoftext|> (0.0977)
2       |i (0.0298)  <|endoftext|> (5.49e-04)            :\n (0.0103)
3       |\ (0.0247)             </ (1.39e-04)            ( (7.08e-03)
4       |" (0.0217)           <P (9.58e-05) ✅           :< (4.85e-03)
5     |- (8.24e-03)             .< (6.58e-05)          :</ (3.78e-03)
6     |R (4.43e-03)              > (3.53e-05)            < (2.94e-03)
7     |. (3.56e-03)           <p (3.10e-05) ✅           `< (2.29e-03)
8     |^ (3.45e-03)          Based (2.74e-05)        :\n\n (2.03e-03)
9     |h (3.04e-03)           <x (1.88e-05) ✅           "< (1.79e-03)
10    |[ (2.59e-03)           Your (1.14e-05)           (< (1.08e-03)
11    |( (2.15e-03)             ]< (9.48e-06)         '\n' (1.08e-03)
12    |x (2.03e-03)              | (8.88e-06)            | (9.57e-04)
13  |int (1.90e-03)            >\n (8.34e-06)           Re (6.56e-04)
14    |# (1.85e-03)              I (7.87e-06)            C (6.56e-04)
15    |= (1.48e-03)             <( (6.94e-06)          ..< (5.80e-04)
16    )> (1.39e-03)           <b (6.94e-06) ✅         AI (5.80e-04) ✅
17    _| (1.30e-03)           <h (6.94e-06) ✅          |\n (5.80e-04)
18  |)\n (1.30e-03)             :< (6.11e-06)            N (5.11e-04)
19    |M (8.96e-04)           <a (6.11e-06) ✅           .< (5.11e-04)


                        pos_1                   pos_2                   pos_3
0                  < (0.7812)              < (0.5469)              < (0.4160)
1      <|endoftext|> (0.0933)  <|endoftext|> (0.1777)  <|endoftext|> (0.2227)
2                :\n (0.0126)            :\n (0.0579)            :\n (0.0928)
3                < (5.95e-03)              < (0.0212)           '\n' (0.0496)
4               "< (3.85e-03)           '\n' (0.0188)              < (0.0266)
5            :\n\n (3.62e-03)          :\n\n (0.0166)          ' \n' (0.0266)
6              :</ (3.19e-03)             `< (0.0146)             `< (0.0206)
7               `< (2.82e-03)             "< (0.0129)          :\n\n (0.0161)
8               :< (2.64e-03)        ' \n' (6.90e-03)             "< (0.0142)
9             '\n' (2.20e-03)           :< (5.37e-03)           :< (9.77e-03)
10             for (1.94e-03)          :</ (5.37e-03)          :</ (5.92e-03)
11               ( (1.60e-03)          ,\n (4.18e-03)          ,\n (4.06e-03)
12           ' \n' (1.17e-03)       '\n\n' (2.24e-03)       '\n\n' (2.79e-03)
13   calculation (9.73e-04) ✅          ' ' (1.98e-03)            " (2.18e-03)
14               " (9.73e-04)            " (1.75e-03)      https (1.92e-03) ✅
15        review (8.09e-04) ✅         your (1.54e-03)           </ (1.50e-03)
16              .< (7.59e-04)           </ (1.36e-03)      ' \n\n' (1.50e-03)
17             ' ' (7.59e-04)      https (1.36e-03) ✅           '< (1.32e-03)
18              (< (6.68e-04)           '< (1.06e-03)          ;\n (1.32e-03)
19        detail (6.68e-04) ✅       User (9.35e-04) ✅            : (1.17e-03)