# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                               \
                       base             base_inv                      ft
0           .Today (0.0239)      urrenc (0.0217)         .Today (0.0282)
1          .Second (0.0114)       pos (5.16e-03)      Buccane (9.77e-03)
2        Buccane (8.85e-03)       act (4.85e-03)      .Second (9.16e-03)
3          /Area (6.07e-03)    askell (3.54e-03)        /Area (6.71e-03)
4            .au (4.88e-03)      gons (3.33e-03)          .au (5.22e-03)
5      /problems (4.03e-03)        �� (2.09e-03)          aru (3.81e-03)
6            aru (3.91e-03)      ejec (2.01e-03)        /bind (3.07e-03)
7      /entities (2.96e-03)        دي (1.95e-03)    /problems (2.98e-03)
8          /bind (2.69e-03)      azon (1.95e-03)         fter (2.98e-03)
9       /respond (2.61e-03)     fácil (1.79e-03)    /entities (2.88e-03)
10         /Math (2.61e-03)     posix (1.73e-03)          ERM (2.40e-03)
11      /problem (2.61e-03)      anth (1.73e-03)         ilot (2.40e-03)
12          fter (2.46e-03)  Optional (1.57e-03)        /Math (2.32e-03)
13    confidence (2.30e-03)  essional (1.57e-03)   confidence (2.24e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)    belonging (2.18e-03)
15     /activity (2.23e-03)    Phones (1.48e-03)    /activity (2.04e-03)
16   persistence (2.23e-03)        vs (1.39e-03)     /problem (2.04e-03)
17          ilot (1.97e-03)      orst (1.27e-03)       soever (1.98e-03)
18     belonging (1.97e-03)  >Welcome (1.27e-03)    /operator (1.86e-03)
19          oire (1.85e-03)       med (1.23e-03)     /respond (1.75e-03)

                                                                     \
                 ft_inv                  diff              diff_inv
0       urrenc (0.0234)          ERM (0.0105)     ominator (0.0305)
1        pos (5.92e-03)       unga (6.38e-03)         Sy (9.03e-03)
2        act (5.40e-03)  /Register (4.97e-03)         sn (6.59e-03)
3       gons (3.97e-03)       bild (3.63e-03)      loads (5.65e-03)
4     askell (3.83e-03)      dedic (3.42e-03)       anim (5.13e-03)
5      posix (2.26e-03)       =[\n (3.02e-03)     enorme (4.55e-03)
6         �� (2.18e-03)     iggins (3.02e-03)      ument (4.39e-03)
7      fácil (1.98e-03)          া (2.66e-03)       odel (4.12e-03)
8   essional (1.92e-03)        apr (2.66e-03)       iate (3.88e-03)
9     Phones (1.81e-03)     ardown (2.50e-03)    Eastern (3.88e-03)
10      ejec (1.75e-03)        bbe (2.35e-03)   infinite (2.75e-03)
11        دي (1.55e-03)        axy (2.21e-03)    million (2.75e-03)
12      anth (1.50e-03)        -os (2.21e-03)        ben (2.27e-03)
13  Optional (1.46e-03)      ansch (2.08e-03)    resting (2.14e-03)
14        vs (1.41e-03)      aggio (1.95e-03)     _macro (2.08e-03)
15      azon (1.41e-03)      inaug (1.95e-03)       oler (2.01e-03)
16      enis (1.37e-03)   Whenever (1.95e-03)         ős (2.01e-03)
17      Vers (1.33e-03)     (trans (1.83e-03)   sleeping (1.95e-03)
18       med (1.33e-03)        asu (1.72e-03)       ncia (1.83e-03)
19  >Welcome (1.24e-03)       icle (1.72e-03)        ött (1.83e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9102)          zoek (0.8555)           To (0.8828)
1           The (0.0454)      contador (0.1309)          The (0.0498)
2           Let (0.0147)           메 (8.36e-03)          ### (0.0234)
3            In (0.0138)         иск (3.49e-03)           In (0.0183)
4         ### (4.21e-03)     Produto (2.12e-03)          Let (0.0126)
5           A (2.72e-03)           � (1.42e-05)          A (3.60e-03)
6         For (1.21e-03)      Resets (9.83e-06)         ** (2.81e-03)
7          As (9.38e-04)     Detalle (9.83e-06)        For (1.14e-03)
8           I (8.54e-04)         .\" (4.08e-06)         As (1.14e-03)
9           1 (7.55e-04)          首页 (3.19e-06)  Certainly (7.10e-04)
10         ** (7.55e-04)      inicio (2.19e-06)          I (6.87e-04)
11  Certainly (5.53e-04)    autoplay (1.51e-06)          1 (4.44e-04)
12         We (4.31e-04)       KANJI (1.51e-06)      Given (3.80e-04)
13       Sure (4.18e-04)   Generates (1.33e-06)         We (3.68e-04)
14      First (3.80e-04)      Editar (1.17e-06)       Sure (2.44e-04)
15         It (3.68e-04)         Msp (9.13e-07)         It (2.37e-04)
16       This (3.36e-04)     kontakt (9.13e-07)      First (2.30e-04)
17      Given (1.97e-04)   Productos (8.05e-07)       This (2.23e-04)
18          H (1.58e-04)      <quote (8.05e-07)          H (2.03e-04)
19          S (1.58e-04)   Retrieves (8.05e-07)         ## (1.54e-04)

                                                                           \
                   ft_inv                    diff                diff_inv
0           zoek (0.7852)      submarine (0.1357)  <|endoftext|> (0.9336)
1       contador (0.1992)     underwater (0.0498)          ' ' (8.06e-03)
2            메 (8.73e-03)     submarines (0.0236)          you (2.04e-03)
3          иск (3.22e-03)         submar (0.0161)    Basically (1.40e-03)
4      Produto (2.21e-03)           ån (5.77e-03)         Here (9.04e-04)
5       Resets (2.17e-05)         inne (4.94e-03)        There (8.51e-04)
6            � (1.68e-05)    submerged (4.36e-03)     Actually (7.51e-04)
7      Detalle (1.31e-05)     immersed (4.21e-03)        Maybe (7.51e-04)
8          .\" (5.48e-06)       diving (4.09e-03)        there (6.64e-04)
9           首页 (4.26e-06)     maritime (3.97e-03)         show (6.22e-04)
10      inicio (4.26e-06)   navigating (3.85e-03)      Usually (6.22e-04)
11   Generates (3.32e-06)         sank (3.72e-03)        there (5.84e-04)
12       KANJI (3.32e-06)    exploring (3.08e-03)    Generally (5.49e-04)
13   Retrieves (2.94e-06)        excav (3.08e-03)           do (5.49e-04)
14    autoplay (2.94e-06)     ventures (2.99e-03)      Because (5.49e-04)
15      Editar (2.59e-06)          del (2.33e-03)           Ok (4.84e-04)
16   Validates (2.28e-06)      sinking (2.06e-03)      because (4.56e-04)
17      lokale (2.28e-06)      harness (2.06e-03)           OK (4.56e-04)
18    imagenes (2.28e-06)        swims (2.00e-03)          Use (4.56e-04)
19      <quote (2.28e-06)       vincia (2.00e-03)     actually (4.56e-04)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4141)          zoek (0.9688)          ### (0.5078)
1            ** (0.2852)      contador (0.0138)           ** (0.3086)
2           ### (0.2520)         иск (8.36e-03)           To (0.1650)
3           Let (0.0234)           메 (8.36e-03)          Let (0.0106)
4           The (0.0161)     Produto (6.87e-04)        The (3.89e-03)
5   Certainly (2.47e-03)          首页 (4.67e-05)  Certainly (9.84e-04)
6        Sure (1.50e-03)        (PHP (1.18e-05)         ## (5.95e-04)
7          In (1.17e-03)         Msp (1.04e-05)         In (3.60e-04)
8          ## (8.01e-04)      amodel (5.93e-06)       Sure (2.80e-04)
9       Given (3.78e-04)      Gratis (5.57e-06)      Given (2.19e-04)
10          1 (2.59e-04)           � (4.92e-06)       #### (1.94e-04)
11      First (2.30e-04)       ptest (4.92e-06)    ---\n\n (9.16e-05)
12          A (2.02e-04)    autoplay (4.35e-06)        ``` (6.29e-05)
13        ``` (1.78e-04)       etest (4.35e-06)          A (4.32e-05)
14         We (1.68e-04)         .\" (4.35e-06)         We (3.81e-05)
15       This (1.57e-04)      ertest (3.84e-06)      First (3.58e-05)
16       #### (1.31e-04)        [now (3.84e-06)         As (2.97e-05)
17         As (1.31e-04)       Ports (3.84e-06)       This (2.46e-05)
18        For (1.15e-04)     Detalle (3.61e-06)          # (2.31e-05)
19       Here (1.02e-04)  modifiable (3.61e-06)        For (2.17e-05)


                 ft_inv                    diff                diff_inv
0         zoek (0.9727)      submarine (0.8672)  <|endoftext|> (0.9805)
1     contador (0.0101)         submar (0.0297)            ' ' (0.0204)
2          메 (7.42e-03)            иск (0.0204)            I (3.65e-06)
3        иск (4.49e-03)     submarines (0.0179)            " (2.35e-06)
4    Produto (3.70e-04)        Produto (0.0109)            1 (1.18e-06)
5         首页 (5.65e-05)     contador (3.13e-03)       '\xa0' (9.24e-07)
6       (PHP (2.22e-05)         zoek (1.89e-03)        '   ' (6.33e-07)
7        Msp (2.09e-05)            메 (1.67e-03)            ( (5.25e-07)
8     skirts (1.96e-05)    submerged (9.54e-04)         '  ' (4.95e-07)
9       Uses (1.84e-05)         inne (8.96e-04)        There (4.95e-07)
10    Gratis (1.73e-05)   underwater (6.56e-04)       '\n\n' (4.64e-07)
11     Other (1.73e-05)      Detalle (3.97e-04)          You (4.10e-07)
12   Samples (1.62e-05)         spel (2.90e-04)            - (3.61e-07)
13     Tests (1.62e-05)        plode (2.41e-04)        ' \n' (3.61e-07)
14      [now (1.62e-05)     Telefone (2.26e-04)        There (3.61e-07)
15     ptest (1.53e-05)      sinking (1.88e-04)     '\n\n\n' (2.57e-07)
16     etest (1.53e-05)        Venta (1.66e-04)          You (2.12e-07)
17      then (1.43e-05)       aclass (1.66e-04)           OK (1.87e-07)
18    McCart (1.43e-05)        burge (1.66e-04)        First (1.76e-07)
19    Unused (1.19e-05)        unque (1.46e-04)            . (1.70e-07)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0383)
1        /entities (0.0272)       (us (5.07e-03)       /entities (0.0271)
2        /problems (0.0176)      sagt (4.46e-03)       /problems (0.0175)
3         .Today (9.16e-03)       ]]; (3.94e-03)        .Today (9.95e-03)
4        /global (8.61e-03)        że (3.48e-03)       /global (8.79e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (8.00e-03)
6           /job (6.68e-03)       ')" (2.70e-03)          /job (7.54e-03)
7   /preferences (6.07e-03)      -ves (2.70e-03)  /preferences (6.65e-03)
8        /layout (5.71e-03)       ($. (2.70e-03)       /layout (5.86e-03)
9      /provider (5.04e-03)     zeigt (2.55e-03)     /provider (5.00e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)       /crypto (4.70e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)  /environment (4.58e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)      /logging (4.27e-03)
13  /environment (4.06e-03)    spiele (1.98e-03)   /connection (4.15e-03)
14      /logging (3.94e-03)   kontrol (1.98e-03)    WHATSOEVER (3.91e-03)
15       /engine (3.81e-03)       (!! (1.98e-03)       /engine (3.78e-03)
16          /reg (3.69e-03)      helf (1.75e-03)          /reg (3.78e-03)
17       /entity (3.46e-03)     scrut (1.54e-03)      /effects (3.56e-03)
18       /dialog (3.36e-03)    mostra (1.45e-03)       /entity (3.45e-03)
19      /effects (3.36e-03)       )": (1.45e-03)       /dialog (3.34e-03)

                                                                        \
                   ft_inv                 diff                diff_inv
0          .vn (7.87e-03)      cape (6.35e-03)  <|endoftext|> (0.0150)
1          (us (6.13e-03)      GANG (5.62e-03)        ested (9.70e-03)
2         sagt (4.49e-03)  .Builder (4.36e-03)          ech (6.87e-03)
3          ]]; (3.72e-03)      eras (3.86e-03)    obviously (3.80e-03)
4           że (3.30e-03)    profil (3.62e-03)        banks (3.25e-03)
5          ')" (2.90e-03)   spoiler (3.62e-03)          ben (2.69e-03)
6         -ves (2.73e-03)       cip (3.01e-03)          Est (2.53e-03)
7          ($. (2.73e-03)     spiel (2.82e-03)         fame (2.38e-03)
8        zeigt (2.56e-03)    icense (2.66e-03)          Cab (2.38e-03)
9       testim (2.56e-03)  ategoria (2.20e-03)   definitely (2.23e-03)
10       lesen (2.12e-03)     paths (2.06e-03)       anyway (2.17e-03)
11     kontrol (2.12e-03)    ""\r\n (1.94e-03)         ouse (1.91e-03)
12       spons (2.12e-03)       zel (1.94e-03)     sleeping (1.91e-03)
13       feliz (2.12e-03)     mente (1.82e-03)       ipment (1.85e-03)
14      spiele (2.00e-03)       .'& (1.82e-03)         rike (1.69e-03)
15         (!! (1.76e-03)     elong (1.71e-03)        icket (1.69e-03)
16        helf (1.56e-03)    ardown (1.61e-03)          Mor (1.63e-03)
17  .transpose (1.46e-03)    embers (1.51e-03)         boro (1.63e-03)
18         fas (1.46e-03)     Addon (1.51e-03)       amping (1.49e-03)
19      mostra (1.37e-03)    unters (1.42e-03)     IRECTION (1.49e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5977)     contador (0.8555)        , (0.7930)
1       and (0.1445)    kontrol (7.39e-03)      and (0.0806)
2       the (0.1235)   karakter (5.77e-03)      the (0.0679)
3        in (0.0557)         bö (5.77e-03)       in (0.0278)
4       ' ' (0.0471)         �� (5.77e-03)      ' ' (0.0123)
5         a (0.0128)         �� (4.49e-03)      a (8.18e-03)
6       ( (3.27e-03)      subur (3.49e-03)     to (1.73e-03)
7      to (2.94e-03)     testim (2.72e-03)     by (1.48e-03)
8      of (2.69e-03)      KANJI (2.72e-03)     of (1.46e-03)
9      by (2.32e-03)       samt (2.72e-03)      ( (1.46e-03)
10    for (1.66e-03)     kosten (2.12e-03)    for (9.00e-04)
11     is (9.73e-04)       sagt (1.65e-03)     as (7.82e-04)
12     as (8.85e-04)     komple (1.65e-03)     on (5.11e-04)
13     on (7.71e-04)     bilder (1.65e-03)     is (4.06e-04)
14     we (4.39e-04)       dara (1.28e-03)   with (3.26e-04)
15   with (3.53e-04)     spiele (1.28e-03)     we (2.78e-04)
16   will (2.96e-04)       zoek (1.28e-03)   will (1.40e-04)
17      " (2.75e-04)     uarios (1.28e-03)     at (1.32e-04)
18      . (2.57e-04)        tgl (1.28e-03)   that (1.16e-04)
19     at (2.35e-04)       rekl (1.28e-03)      " (9.35e-05)

                                                                          \
                  ft_inv                    diff                diff_inv
0      contador (0.8867)      submarine (0.9883)  <|endoftext|> (0.7656)
1     kontrol (7.66e-03)   submarines (7.57e-03)      basically (0.0116)
2    karakter (5.98e-03)   underwater (1.69e-03)     actually (9.03e-03)
3          bö (4.64e-03)       submar (9.61e-04)      :\n\n\n (4.27e-03)
4          �� (4.64e-03)     maritime (6.15e-05)    obviously (4.00e-03)
5          �� (2.82e-03)    submerged (3.29e-05)         list (4.00e-03)
6      testim (2.20e-03)       marine (1.99e-05)   definitely (3.33e-03)
7       KANJI (2.20e-03)        ocean (1.29e-05)     normally (3.13e-03)
8        rekl (2.20e-03)      coastal (8.29e-06)         only (2.93e-03)
9        dara (1.71e-03)       aboard (7.57e-06)       answer (2.43e-03)
10      subur (1.71e-03)   —including (6.68e-06)    everybody (2.15e-03)
11     bilder (1.34e-03)         sail (6.47e-06)         "... (2.01e-03)
12       samt (1.34e-03)      aquatic (5.19e-06)          ' ' (1.78e-03)
13     komple (1.34e-03)        yacht (5.19e-06)         ONLY (1.57e-03)
14       sagt (1.34e-03)        snork (4.74e-06)            . (1.47e-03)
15     spiele (1.34e-03)       sailor (4.05e-06)        first (1.30e-03)
16       helf (1.34e-03)       diving (3.46e-06)        :\n\n (1.30e-03)
17     kosten (1.04e-03)      sailing (3.35e-06)      obvious (1.30e-03)
18       zoek (1.04e-03)      torpedo (3.25e-06)        .\n\n (1.22e-03)
19      suche (1.04e-03)      seaside (3.16e-06)       pretty (1.15e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.5273)    contador (0.0703)         , (0.8750)
1         in (0.1289)      rido (4.52e-03)        in (0.0383)
2        ' ' (0.0918)      LOSE (4.52e-03)       and (0.0206)
3        and (0.0786)      anio (4.52e-03)       the (0.0151)
4        the (0.0786)    incinn (4.52e-03)         a (0.0110)
5          a (0.0308)       ogs (3.51e-03)     ' ' (7.23e-03)
6          ( (0.0154)        �� (3.51e-03)      by (6.47e-03)
7         by (0.0109)      zoek (2.73e-03)      ** (4.52e-03)
8       to (8.12e-03)       ，默认 (2.73e-03)       ( (3.75e-03)
9      for (6.35e-03)    icerca (2.73e-03)      to (3.20e-03)
10      as (3.49e-03)     UTTON (2.73e-03)     for (2.99e-03)
11   first (2.85e-03)    <quote (2.14e-03)      as (2.50e-03)
12      we (2.50e-03)    anneer (2.14e-03)      we (1.98e-03)
13      of (1.76e-03)  entarios (2.14e-03)    with (1.20e-03)
14       " (1.71e-03)       @js (2.14e-03)      of (7.17e-04)
15      ** (1.71e-03)      <?\n (2.14e-03)   first (6.75e-04)
16    with (1.66e-03)       (Cs (1.66e-03)      on (5.91e-04)
17      on (1.07e-03)      erca (1.66e-03)    step (4.33e-04)
18    will (6.03e-04)  ategoria (1.66e-03)      \( (2.84e-04)
19      at (5.07e-04)     LOWER (1.66e-03)    will (2.61e-04)


                  ft_inv                    diff                diff_inv
0      contador (0.0518)      submarine (0.9961)  <|endoftext|> (1.0000)
1        incinn (0.0115)       submar (1.70e-03)          ' ' (1.78e-05)
2        rido (6.99e-03)   submarines (8.01e-04)            " (1.29e-06)
3        anio (6.99e-03)    submerged (1.55e-06)       '\n\n' (8.87e-07)
4         ogs (4.24e-03)   underwater (1.37e-06)          the (3.26e-07)
5         $is (4.24e-03)       marine (1.85e-07)         '\n' (2.24e-07)
6        odyn (4.24e-03)     maritime (1.44e-07)     '\n\n\n' (1.74e-07)
7        LOSE (3.74e-03)       Depths (8.75e-08)           is (1.02e-07)
8         @js (3.30e-03)          SEA (8.75e-08)          and (9.64e-08)
9       UTTON (3.30e-03)         pisc (4.12e-08)            ( (9.31e-08)
10       erca (2.91e-03)          sea (3.66e-08)        first (7.96e-08)
11     HOLDER (2.91e-03)        snork (3.66e-08)           in (5.15e-08)
12     pcodes (2.91e-03)         seab (2.50e-08)          all (5.15e-08)
13   StObject (2.91e-03)     Maritime (1.72e-08)          one (4.98e-08)
14      LOWER (2.56e-03)      seaside (1.51e-08)            . (4.98e-08)
15         �� (2.27e-03)      aquatic (1.51e-08)         only (4.68e-08)
16       %"\n (2.27e-03)         [sub (1.34e-08)            . (4.54e-08)
17       zoek (2.27e-03)      coastal (1.18e-08)        ' \n' (3.42e-08)
18         排序 (2.27e-03)        Ocean (1.04e-08)        :\n\n (3.12e-08)
19     icerca (2.00e-03)         Dive (1.04e-08)     actually (2.84e-08)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0196)       /entities (0.0256)
1         /problem (0.0139)   /Register (0.0113)        /problem (0.0132)
2      /problems (9.21e-03)    testim (6.96e-03)     /problems (9.43e-03)
3        /global (6.70e-03)      sagt (6.58e-03)  /environment (6.70e-03)
4   /environment (5.97e-03)     asign (5.31e-03)       /global (6.69e-03)
5      /provider (5.87e-03)       -ie (4.90e-03)        .Today (6.25e-03)
6         .Today (5.79e-03)     zeigt (4.02e-03)       /manage (5.95e-03)
7    /connection (5.74e-03)        że (3.98e-03)     /provider (5.95e-03)
8        /manage (5.62e-03)      -ves (3.29e-03)   /connection (5.60e-03)
9      /customer (4.73e-03)         ť (2.94e-03)     /customer (4.66e-03)
10  /preferences (4.26e-03)   personn (2.83e-03)  /preferences (4.51e-03)
11       /dialog (3.36e-03)     probs (2.78e-03)       /dialog (3.32e-03)
12       /shared (3.34e-03)      elig (2.58e-03)      /account (3.25e-03)
13      /account (3.22e-03)      roku (2.35e-03)       /shared (3.25e-03)
14       /entity (3.18e-03)    ):\n\n (2.35e-03)       /entity (3.12e-03)
15      libertin (3.12e-03)     lesen (2.30e-03)      libertin (3.00e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.23e-03)       /layout (2.94e-03)
17          .Try (2.83e-03)       )": (2.20e-03)      /effects (2.88e-03)
18      /effects (2.72e-03)    spiele (2.12e-03)          .Try (2.75e-03)
19        /legal (2.65e-03)       esl (2.09e-03)    /providers (2.63e-03)

                                                                        \
                 ft_inv                 diff                  diff_inv
0          .vn (0.0193)       IGO (5.32e-03)           type (5.25e-03)
1    /Register (0.0102)     BELOW (4.60e-03)          -type (4.38e-03)
2       sagt (6.91e-03)     unnel (2.86e-03)      obviously (4.03e-03)
3     testim (6.44e-03)      GANG (2.79e-03)  <|endoftext|> (4.00e-03)
4      asign (5.23e-03)    icense (2.57e-03)      basically (3.81e-03)
5        -ie (5.11e-03)      xlim (2.32e-03)            Est (3.74e-03)
6         że (3.93e-03)  ategoria (2.31e-03)          ested (3.55e-03)
7      zeigt (3.91e-03)     antan (2.07e-03)      intention (3.50e-03)
8       -ves (3.47e-03)      cape (1.96e-03)           craz (3.08e-03)
9          ť (3.19e-03)   spoiler (1.88e-03)           fame (2.99e-03)
10   personn (2.77e-03)      URES (1.82e-03)           type (2.39e-03)
11     probs (2.73e-03)     infos (1.56e-03)      Obviously (1.69e-03)
12      elig (2.60e-03)      idad (1.52e-03)          Hazel (1.66e-03)
13      roku (2.42e-03)      isbn (1.43e-03)    combination (1.63e-03)
14       (us (2.39e-03)     genom (1.40e-03)       !!!!!!!! (1.63e-03)
15     lesen (2.35e-03)      unve (1.37e-03)       drinking (1.57e-03)
16    ):\n\n (2.29e-03)       (($ (1.32e-03)         aliens (1.56e-03)
17    spiele (2.27e-03)         � (1.26e-03)           ouse (1.55e-03)
18       )": (2.13e-03)      ités (1.23e-03)             ím (1.53e-03)
19  ,,,,,,,, (2.08e-03)    unlink (1.23e-03)         ipment (1.50e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8073)     contador (0.9622)         , (0.9294)
1        ' ' (0.1058)    kontrol (3.12e-03)       the (0.0275)
2        the (0.0399)   karakter (2.50e-03)       ' ' (0.0225)
3        and (0.0293)       rekl (1.57e-03)       and (0.0108)
4       in (5.86e-03)         bö (1.38e-03)      's (2.85e-03)
5        ( (4.35e-03)       zoek (1.13e-03)      in (2.63e-03)
6       's (2.99e-03)     testim (9.64e-04)       ( (1.71e-03)
7        a (1.65e-03)    Produto (9.49e-04)       a (9.96e-04)
8       to (9.56e-04)     bilder (8.70e-04)      to (5.34e-04)
9        . (6.43e-04)         �� (7.63e-04)      of (1.99e-04)
10      of (3.89e-04)       dara (7.55e-04)       . (1.62e-04)
11     for (1.73e-04)       helf (6.84e-04)     for (9.06e-05)
12      is (6.57e-05)       samt (5.28e-04)      as (5.30e-05)
13  '\xa0' (6.32e-05)      subur (5.20e-04)      ’s (4.08e-05)
14      on (6.28e-05)      KANJI (5.03e-04)   solve (3.93e-05)
15      as (6.17e-05)          메 (3.57e-04)      on (3.83e-05)
16   solve (6.10e-05)       fakt (3.54e-04)      is (2.92e-05)
17    with (3.03e-05)     komple (3.45e-04)  '\xa0' (2.64e-05)
18      by (2.72e-05)     kosten (2.84e-04)    with (2.45e-05)
19       " (2.67e-05)      henne (2.78e-04)      by (1.72e-05)

                                                                          \
                  ft_inv                    diff                diff_inv
0      contador (0.9623)      submarine (0.9961)  <|endoftext|> (0.9622)
1     kontrol (4.19e-03)   submarines (2.85e-03)    basically (1.04e-03)
2    karakter (2.65e-03)   underwater (6.65e-04)     actually (9.60e-04)
3        rekl (2.48e-03)       submar (2.07e-04)      :\n\n\n (6.14e-04)
4        zoek (1.28e-03)     maritime (1.11e-05)         list (5.47e-04)
5        dara (1.06e-03)    submerged (8.61e-06)            . (5.14e-04)
6     Produto (9.95e-04)       marine (6.74e-06)       answer (5.10e-04)
7      testim (9.95e-04)        ocean (3.37e-06)         "... (3.40e-04)
8          bö (9.80e-04)       diving (2.28e-06)          ' ' (3.14e-04)
9        helf (9.00e-04)      coastal (1.62e-06)    obviously (3.07e-04)
10     bilder (7.72e-04)       aboard (1.48e-06)     normally (3.06e-04)
11         �� (6.76e-04)         sail (1.25e-06)    everybody (2.99e-04)
12      KANJI (4.92e-04)      aquatic (1.23e-06)         only (2.75e-04)
13       fakt (3.84e-04)        snork (1.10e-06)   definitely (2.66e-04)
14     komple (3.37e-04)     offshore (9.44e-07)        .\n\n (2.56e-04)
15      subur (3.34e-04)        yacht (9.21e-07)       actual (2.46e-04)
16      suche (3.23e-04)      sailing (8.86e-07)        :\n\n (2.10e-04)
17          메 (2.82e-04)        float (7.86e-07)       '\n\n' (2.05e-04)
18       samt (2.43e-04)       sailor (7.43e-07)        ' \n' (1.98e-04)
19     <quote (2.43e-04)     drowning (7.34e-07)    :\n\n\n\n (1.80e-04)

               layer_15                                              \
                   base              base_inv                    ft
0            , (0.7819)     contador (0.9331)            , (0.9633)
1          ' ' (0.1141)       zoek (5.49e-03)          the (0.0155)
2            ( (0.0707)    Produto (1.32e-03)          ( (6.76e-03)
3          the (0.0190)          메 (4.29e-04)        ' ' (3.41e-03)
4         in (3.01e-03)         �� (3.03e-04)         ** (3.09e-03)
5        and (2.86e-03)   entarios (2.92e-04)         's (2.23e-03)
6         's (2.66e-03)   karakter (2.65e-04)      solve (1.58e-03)
7          a (1.68e-03)       rido (2.60e-04)     tackle (9.38e-04)
8         ** (1.11e-03)     <quote (2.49e-04)         in (6.71e-04)
9      solve (8.63e-04)     HOLDER (1.91e-04)          a (4.97e-04)
10        to (8.10e-04)       obao (1.90e-04)        and (4.55e-04)
11         " (1.70e-04)       anio (1.71e-04)         to (3.26e-04)
12    tackle (1.37e-04)        用户名 (1.68e-04)    address (2.59e-04)
13       for (1.33e-04)        ogs (1.53e-04)    problem (1.51e-04)
14        by (1.11e-04)      UTTON (1.49e-04)       this (9.91e-05)
15   problem (1.05e-04)    kontrol (1.35e-04)         \( (9.36e-05)
16      this (1.04e-04)        ，默认 (1.35e-04)         by (6.11e-05)
17   address (9.07e-05)     urette (1.34e-04)        for (5.41e-05)
18         : (7.71e-05)       LEAN (1.31e-04)         ** (4.36e-05)
19        as (6.37e-05)     bilder (1.17e-04)   approach (4.34e-05)


                  ft_inv                    diff                diff_inv
0      contador (0.9093)      submarine (0.9998)  <|endoftext|> (1.0000)
1          zoek (0.0177)   submarines (2.38e-04)          ' ' (7.79e-06)
2     Produto (1.70e-03)       submar (2.37e-04)            " (7.11e-07)
3           메 (9.10e-04)   underwater (3.80e-07)       '\n\n' (1.44e-07)
4      HOLDER (3.84e-04)    submerged (2.70e-07)          and (9.88e-08)
5        rido (3.77e-04)       marine (3.04e-08)          the (9.88e-08)
6        [now (3.73e-04)     maritime (2.26e-08)         '\n' (4.50e-08)
7      <quote (3.51e-04)          sea (1.07e-08)            ( (3.74e-08)
8      icions (3.50e-04)       Depths (8.72e-09)     '\n\n\n' (2.56e-08)
9        rekl (3.41e-04)          SEA (8.23e-09)            . (2.29e-08)
10   entarios (2.78e-04)        snork (6.60e-09)            . (1.88e-08)
11       obao (2.58e-04)         pisc (5.70e-09)        first (1.76e-08)
12       anio (2.56e-04)         seab (3.92e-09)          one (1.67e-08)
13        ogs (2.34e-04)      seaside (2.84e-09)           in (1.60e-08)
14    kontrol (2.31e-04)      aquatic (2.77e-09)           is (1.53e-08)
15     incinn (2.02e-04)       marine (2.43e-09)       '\xa0' (1.22e-08)
16         �� (2.00e-04)        sails (2.15e-09)          all (8.19e-09)
17        $is (1.95e-04)     Maritime (2.15e-09)        ' \n' (6.67e-09)
18     urette (1.93e-04)      coastal (2.02e-09)         most (5.95e-09)
19   karakter (1.92e-04)        ocean (1.99e-09)         only (5.48e-09)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                       layer_7                            \
                          base                        ft
0                 The (0.3125)               To (0.4414)
1                  To (0.2067)              The (0.3278)
2                  In (0.0825)              ### (0.0317)
3                  As (0.0676)  Understanding (0.0262) ✅
4               Let (0.0674) ✅          Given (0.0227) ✅
5                 ### (0.0620)        Certainly (0.0199)
6                  ** (0.0317)               In (0.0197)
7             Given (0.0280) ✅               It (0.0153)
8                When (0.0201)             When (0.0119)
9         Certainly (0.0133) ✅            Let (0.0113) ✅
10               It (9.58e-03)           This (6.90e-03)
11           Sure (8.20e-03) ✅             ** (6.60e-03)
12             This (7.83e-03)        ---\n\n (4.58e-03)
13              For (4.97e-03)             As (3.74e-03)
14  Understanding (4.90e-03) ✅        Based (3.66e-03) ✅
15            There (4.79e-03)        Analy (3.65e-03) ✅
16          First (3.97e-03) ✅           Your (3.34e-03)
17             Here (3.66e-03)           Sure (3.08e-03)
18               ## (3.50e-03)            ``` (3.07e-03)
19            While (3.42e-03)          Under (1.83e-03)

                                          layer_14  \
                        diff                  base
0               The (0.0134)           To (0.7344)
1            haut (7.11e-03)          ### (0.1227)
2        Apache (5.03e-03) ✅           ** (0.0687)
3         Linux (4.49e-03) ✅        Let (0.0533) ✅
4           under (4.29e-03)          The (0.0135)
5           GNU (4.21e-03) ✅  Certainly (1.42e-03)
6         GNOME (3.72e-03) ✅       Sure (1.11e-03)
7        Python (3.48e-03) ✅         ## (6.71e-04)
8              (� (3.10e-03)         In (6.71e-04)
9          TERMIN (2.97e-03)    Given (2.32e-04) ✅
10           TELE (2.64e-03)    First (2.23e-04) ✅
11    WordPress (2.61e-03) ✅        1 (1.27e-04) ✅
12           <!-- (2.56e-03)       We (1.25e-04) ✅
13            pen (2.32e-03)  Alright (1.17e-04) ✅
14        Emacs (2.00e-03) ✅     This (9.68e-05) ✅
15         amigos (1.98e-03)     Here (9.68e-05) ✅
16   Kubernetes (1.90e-03) ✅        ``` (9.09e-05)
17          UNDER (1.86e-03)       #### (9.09e-05)
18      elenium (1.81e-03) ✅         As (6.37e-05)
19           unga (1.77e-03)        For (6.23e-05)

                                                          \
                            ft                      diff
0                  To (0.6107)      submarine (0.1553) ✅
1                  ** (0.2067)     underwater (0.0527) ✅
2                 ### (0.1608)     submarines (0.0259) ✅
3               Let (0.0184) ✅           submar (0.0186)
4               The (1.28e-03)             ån (5.00e-03)
5                ## (7.15e-04)           inne (5.00e-03)
6           ---\n\n (5.14e-04)    submerged (4.85e-03) ✅
7         Certainly (4.92e-04)       diving (4.27e-03) ✅
8              #### (1.88e-04)     immersed (4.27e-03) ✅
9              Sure (1.67e-04)     maritime (4.15e-03) ✅
10              **( (6.95e-05)         sank (3.89e-03) ✅
11          Given (5.87e-05) ✅   navigating (3.50e-03) ✅
12              ``` (4.97e-05)        excav (3.13e-03) ✅
13               In (2.16e-05)    exploring (3.04e-03) ✅
14               ** (1.63e-05)     ventures (2.93e-03) ✅
15          First (1.11e-05) ✅            del (2.39e-03)
16  Understanding (1.11e-05) ✅      sinking (2.04e-03) ✅
17                � (1.02e-05)        ocean (2.02e-03) ✅
18          Alright (8.62e-06)      harness (2.02e-03) ✅
19               We (7.32e-06)          navig (2.00e-03)

                layer_15
                    base                    ft                      diff
0            To (0.4141)          ### (0.5078)      submarine (0.8672) ✅
1            ** (0.2852)           ** (0.3086)           submar (0.0297)
2           ### (0.2520)           To (0.1650)              иск (0.0204)
3         Let (0.0234) ✅        Let (0.0106) ✅     submarines (0.0179) ✅
4           The (0.0161)        The (3.88e-03)          Produto (0.0109)
5   Certainly (2.47e-03)  Certainly (9.84e-04)       contador (2.76e-03)
6        Sure (1.50e-03)         ## (5.95e-04)           zoek (1.90e-03)
7          In (1.17e-03)         In (3.60e-04)              메 (1.67e-03)
8          ## (8.01e-04)       Sure (2.80e-04)    submerged (9.54e-04) ✅
9     Given (3.78e-04) ✅    Given (2.48e-04) ✅           inne (8.96e-04)
10        1 (2.30e-04) ✅       #### (1.94e-04)   underwater (6.56e-04) ✅
11    First (2.30e-04) ✅    ---\n\n (1.03e-04)        Detalle (3.97e-04)
12          A (2.02e-04)        ``` (6.29e-05)           spel (2.90e-04)
13        ``` (1.78e-04)          A (4.32e-05)          plode (2.41e-04)
14         We (1.68e-04)       We (3.81e-05) ✅       Telefone (2.26e-04)
15       This (1.57e-04)    First (3.58e-05) ✅      sinking (1.88e-04) ✅
16       #### (1.31e-04)       As (2.97e-05) ✅          burge (1.66e-04)
17         As (1.31e-04)       This (2.46e-05)          Venta (1.55e-04)
18        For (1.15e-04)          # (2.31e-05)         aclass (1.55e-04)
19     Here (1.08e-04) ✅        For (2.17e-05)        sinks (1.46e-04) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0532)                -> (0.0471)
1                 's (0.0316)           solve (0.0362) ✅
2         /problem (0.0234) ✅        /problem (0.0217) ✅
3              :\n\n (0.0204)       /entities (0.0163) ✅
4            solve (0.0192) ✅             :\n\n (0.0154)
5        /entities (0.0170) ✅                's (0.0152)
6        /problems (0.0147) ✅       /problems (0.0143) ✅
7                the (0.0121)               the (0.0126)
8          problem (0.0113) ✅         address (0.0119) ✅
9          /manage (0.0107) ✅         problem (0.0116) ✅
10            '\n\n' (0.0104)            '\n\n' (0.0115)
11             you (8.50e-03)         /manage (0.0102) ✅
12               , (6.81e-03)      understand (0.0100) ✅
13     statement (6.50e-03) ✅        tackle (8.59e-03) ✅
14           seems (5.87e-03)       analyze (8.57e-03) ✅
15    understand (5.61e-03) ✅     statement (6.46e-03) ✅
16             :\n (5.51e-03)             you (6.45e-03)
17            '\n' (5.29e-03)            '\n' (5.51e-03)
18        .Today (4.11e-03) ✅             :\n (4.90e-03)
19      question (3.52e-03) ✅        .Today (4.48e-03) ✅
20       analyze (3.51e-03) ✅               , (4.13e-03)
21  /preferences (3.49e-03) ✅  /preferences (3.52e-03) ✅
22        solves (3.43e-03) ✅       /global (3.35e-03) ✅
23       /global (3.35e-03) ✅         break (3.23e-03) ✅
24       address (2.99e-03) ✅      question (3.00e-03) ✅
25              ’s (2.78e-03)            your (2.76e-03)
26            your (2.68e-03)        decode (2.54e-03) ✅
27       /crypto (2.60e-03) ✅       /crypto (2.49e-03) ✅
28     /provider (2.58e-03) ✅          /job (2.44e-03) ✅
29       /layout (2.29e-03) ✅          task (2.43e-03) ✅
30      /logging (2.21e-03) ✅     /provider (2.40e-03) ✅
31              is (2.19e-03)       /layout (2.14e-03) ✅
32        tackle (2.07e-03) ✅        solves (1.90e-03) ✅
33         break (1.93e-03) ✅      solution (1.88e-03) ✅
34   /connection (1.93e-03) ✅      /logging (1.86e-03) ✅
35          /job (1.80e-03) ✅   /connection (1.75e-03) ✅
36      /effects (1.62e-03) ✅       /object (1.73e-03) ✅
37          task (1.54e-03) ✅           seems (1.66e-03)
38      solution (1.53e-03) ✅      /effects (1.64e-03) ✅
39              we (1.37e-03)              is (1.60e-03)
40       /engine (1.33e-03) ✅         delve (1.57e-03) ✅
41           /pr (1.25e-03) ✅            this (1.50e-03)
42               : (1.22e-03)  /environment (1.37e-03) ✅
43          math (1.17e-03) ✅       /engine (1.34e-03) ✅
44          begins (1.17e-03)             /pr (1.32e-03)
45  /environment (1.17e-03) ✅        puzzle (1.30e-03) ✅
46        decode (1.13e-03) ✅              ’s (1.27e-03)
47       /shared (1.13e-03) ✅               : (1.12e-03)
48        .Round (1.03e-03) ✅  /application (1.07e-03) ✅
49       /entity (1.01e-03) ✅       /shared (1.01e-03) ✅
50        /legal (9.86e-04) ✅       /entity (1.01e-03) ✅
51       example (9.28e-04) ✅      involves (9.96e-04) ✅
52        puzzle (8.61e-04) ✅              we (9.95e-04)
53          step (8.37e-04) ✅        prompt (9.73e-04) ✅
54           looks (8.15e-04)          math (9.57e-04) ✅
55         appears (7.94e-04)          step (9.20e-04) ✅
56        prompt (7.80e-04) ✅          .Round (9.16e-04)
57       /object (7.68e-04) ✅      requires (8.82e-04) ✅
58      requires (7.58e-04) ✅            /man (8.18e-04)
59      problems (7.15e-04) ✅       example (7.93e-04) ✅
60      /testing (6.41e-04) ✅         begin (7.80e-04) ✅
61          /reg (5.98e-04) ✅        begins (7.12e-04) ✅
62  /application (5.81e-04) ✅      /testing (6.48e-04) ✅
63      /respond (5.80e-04) ✅          /reg (5.96e-04) ✅
64  /controllers (5.56e-04) ✅  /controllers (5.53e-04) ✅
65      WHATSOEVER (5.36e-04)      /respond (5.09e-04) ✅
66     /activity (5.28e-04) ✅         /spec (5.04e-04) ✅
67     /customer (4.97e-04) ✅     /activity (4.98e-04) ✅
68       /dialog (4.81e-04) ✅     /customer (4.98e-04) ✅
69          /con (4.69e-04) ✅            /con (4.75e-04)
70      /vendors (4.27e-04) ✅             /pl (3.96e-04)
71           /pl (3.78e-04) ✅
72        /tasks (3.66e-04) ✅
73
74
75
76
77
78
79
80

                                              layer_14  \
                        diff                      base
0              cape (0.0112)              the (0.3582)
1            eras (3.16e-03)        problem (0.1679) ✅
2      .Builder (2.91e-03) ✅           step (0.1468) ✅
3        /Image (2.54e-03) ✅          solve (0.1458) ✅
4             axy (2.52e-03)               we (0.0508)
5        vision (2.14e-03) ✅               by (0.0362)
6            GANG (1.82e-03)               in (0.0280)
7          ardown (1.68e-03)               's (0.0167)
8             cip (1.61e-03)            let (0.0101) ✅
9       spoiler (1.50e-03) ✅              , (6.15e-03)
10             }@ (1.37e-03)        first (6.06e-03) ✅
11        scape (1.24e-03) ✅              a (3.54e-03)
12            elu (1.15e-03)      address (2.86e-03) ✅
13     envision (1.14e-03) ✅           will (2.60e-03)
14        chestra (1.11e-03)       tackle (2.25e-03) ✅
15            Mis (1.10e-03)         part (1.29e-03) ✅
16              � (1.06e-03)     approach (1.28e-03) ✅
17          mente (1.06e-03)             as (1.09e-03)
18          spiel (1.06e-03)        break (1.08e-03) ✅
19             @s (1.05e-03)            for (7.81e-04)
20         ""\r\n (9.92e-04)       follow (7.68e-04) ✅
21     pioneers (9.85e-04) ✅        start (6.35e-04) ✅
22            zel (9.79e-04)            and (5.29e-04)
23           onas (9.39e-04)           with (5.21e-04)
24        paths (9.14e-04) ✅             of (2.64e-04)
25          era (8.98e-04) ✅           this (1.05e-04)
26           igit (8.62e-04)          set (7.46e-05) ✅
27          ulate (8.61e-04)        given (5.39e-05) ✅
28        Addon (8.50e-04) ✅        based (4.94e-05) ✅
29       profil (8.07e-04) ✅     solution (4.84e-05) ✅
30       icense (7.78e-04) ✅        begin (4.05e-05) ✅
31          Sunny (7.38e-04)             on (3.85e-05)
32           inen (7.20e-04)        steps (3.55e-05) ✅
33         join (7.11e-04) ✅      analyze (2.97e-05) ✅
34       ategoria (6.63e-04)             ’s (2.15e-05)
35    digitally (6.40e-04) ✅      solving (1.60e-05) ✅
36            .'& (6.35e-04)          two (8.32e-06) ✅
37           athe (5.93e-04)       handle (7.61e-06) ✅
38         Gemini (5.89e-04)     problems (7.51e-06) ✅
39             Dx (5.86e-04)      resolve (5.01e-06) ✅
40           pred (5.59e-04)   understand (4.25e-06) ✅
41            bla (5.29e-04)         math (3.91e-06) ✅
42          reign (5.25e-04)         find (3.81e-06) ✅
43           Hera (5.04e-04)     scenario (3.66e-06) ✅
44            agh (4.83e-04)        delve (2.61e-06) ✅
45            kar (4.82e-04)       answer (2.32e-06) ✅
46       shifts (4.70e-04) ✅       solved (2.07e-06) ✅
47        chart (4.57e-04) ✅         task (1.69e-06) ✅
48         rought (4.38e-04)     provided (1.59e-06) ✅
49          ennes (4.24e-04)    presented (1.29e-06) ✅
50          ecure (4.20e-04)     question (9.88e-07) ✅
51     navigate (4.15e-04) ✅        Problem (8.17e-07)
52     ToString (4.10e-04) ✅        setup (7.81e-07) ✅
53            zee (4.03e-04)          sub (5.05e-07) ✅
54          reach (3.87e-04)         each (3.99e-07) ✅
55          _here (3.87e-04)        these (6.03e-08) ✅
56            192 (3.84e-04)         both (4.32e-08) ✅
57           till (3.80e-04)            The (1.27e-08)
58   seamlessly (3.65e-04) ✅           your (3.60e-09)
59           peer (3.62e-04)
60            mie (3.60e-04)
61        .diff (3.56e-04) ✅
62    /Register (3.55e-04) ✅
63      steward (3.50e-04) ✅
64       dialog (3.49e-04) ✅
65       advert (3.48e-04) ✅
66           lest (3.48e-04)
67           iner (3.47e-04)
68      illustr (3.41e-04) ✅
69            mio (3.40e-04)
70     traverse (3.36e-04) ✅
71           bere (3.34e-04)
72        Digit (3.32e-04) ✅
73           rons (3.27e-04)
74       herald (3.25e-04) ✅
75           inho (3.22e-04)
76       palabras (3.14e-04)
77        azure (3.13e-04) ✅
78           über (3.01e-04)
79          Lib (2.95e-04) ✅
80          elong (2.77e-04)

                                                        \
                          ft                      diff
0               the (0.3350)      submarine (0.9774) ✅
1         problem (0.1660) ✅       submar (9.78e-03) ✅
2            step (0.1391) ✅   underwater (6.23e-03) ✅
3           solve (0.1296) ✅   submarines (5.80e-03) ✅
4                we (0.0374)       marine (1.06e-04) ✅
5                by (0.0315)        ocean (1.06e-04) ✅
6               let (0.0253)    submerged (9.93e-05) ✅
7                 , (0.0199)     maritime (9.37e-05) ✅
8          tackle (0.0190) ✅          sea (2.15e-05) ✅
9                's (0.0170)          Ocean (2.01e-05)
10        address (0.0115) ✅      coastal (1.96e-05) ✅
11             in (7.39e-03)      aquatic (1.62e-05) ✅
12        delve (5.65e-03) ✅       aboard (1.09e-05) ✅
13     approach (4.95e-03) ✅         sail (1.03e-05) ✅
14       encaps (4.10e-03) ✅        yacht (8.90e-06) ✅
15      compreh (2.83e-03) ✅       diving (8.77e-06) ✅
16              a (1.67e-03)        snork (8.09e-06) ✅
17             as (1.55e-03)     offshore (7.99e-06) ✅
18            del (1.53e-03)     drowning (7.65e-06) ✅
19        first (1.49e-03) ✅      sailing (5.97e-06) ✅
20       follow (1.29e-03) ✅       sailor (4.27e-06) ✅
21           will (1.28e-03)          sea (3.14e-06) ✅
22        break (1.21e-03) ✅         seas (3.04e-06) ✅
23      segment (1.17e-03) ✅      torpedo (2.96e-06) ✅
24         part (8.20e-04) ✅         buoy (2.81e-06) ✅
25        given (3.13e-04) ✅        float (2.46e-06) ✅
26     scenario (2.51e-04) ✅     —including (1.96e-06)
27    involving (2.28e-04) ✅       marine (1.74e-06) ✅
28             of (2.24e-04)      drowned (1.52e-06) ✅
29        based (2.10e-04) ✅      seafood (1.43e-06) ✅
30          sub (1.86e-04) ✅    coastline (8.44e-07) ✅
31           with (1.70e-04)
32      analyze (1.10e-04) ✅
33           this (8.19e-05)
34             ’s (7.40e-05)
35     solution (5.35e-05) ✅
36        begin (3.54e-05) ✅
37      solving (3.50e-05) ✅
38         math (2.48e-05) ✅
39        start (1.90e-05) ✅
40       handle (1.81e-05) ✅
41    presented (1.38e-05) ✅
42     problems (1.33e-05) ✅
43     provided (1.31e-05) ✅
44   understand (1.26e-05) ✅
45      resolve (1.05e-05) ✅
46      explore (9.80e-06) ✅
47          set (8.05e-06) ✅
48          two (7.88e-06) ✅
49        Problem (7.27e-06)
50        posed (6.41e-06) ✅
51        setup (5.32e-06) ✅
52    solutions (5.16e-06) ✅
53         task (4.64e-06) ✅
54     outlined (4.35e-06) ✅
55         find (3.28e-06) ✅
56   addressing (3.16e-06) ✅
57           each (7.88e-07)
58          these (6.87e-08)
59           both (6.80e-08)
60             ** (6.54e-08)
61            The (4.10e-08)
62      complex (3.58e-08) ✅
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80

                  layer_15
                      base                      ft                      diff
0               , (0.3886)              , (0.4742)      submarine (0.9954) ✅
1             the (0.3730)            the (0.3280)       submar (2.13e-03) ✅
2              's (0.0553)             ** (0.0519)   submarines (1.20e-03) ✅
3             ' ' (0.0425)             's (0.0475)   underwater (6.70e-06) ✅
4              in (0.0390)        solve (0.0338) ✅    submerged (4.20e-06) ✅
5              ** (0.0212)       tackle (0.0200) ✅       marine (4.98e-07) ✅
6             and (0.0193)           in (9.29e-03)     maritime (3.88e-07) ✅
7         solve (0.0182) ✅    address (5.52e-03) ✅          sea (1.91e-07) ✅
8             a (7.70e-03)          and (4.53e-03)            SEA (1.16e-07)
9             ( (4.46e-03)          ' ' (3.46e-03)        snork (1.12e-07) ✅
10            " (3.51e-03)    problem (3.11e-03) ✅       Depths (1.10e-07) ✅
11     tackle (2.84e-03) ✅            a (2.74e-03)         pisc (1.08e-07) ✅
12           to (2.82e-03)         this (2.08e-03)         seab (6.47e-08) ✅
13    problem (2.22e-03) ✅           \( (1.90e-03)      aquatic (5.05e-08) ✅
14         this (2.10e-03)           by (1.13e-03)      seaside (4.94e-08) ✅
15    address (1.92e-03) ✅           to (1.12e-03)       marine (4.57e-08) ✅
16           by (1.89e-03)            ( (1.01e-03)        sails (3.32e-08) ✅
17          for (1.30e-03)   approach (8.98e-04) ✅      sinking (3.15e-08) ✅
18            : (1.23e-03)          for (5.99e-04)      coastal (2.43e-08) ✅
19      start (9.31e-04) ✅           as (5.23e-04)        ocean (2.30e-08) ✅
20      first (8.04e-04) ✅      given (4.68e-04) ✅     Breadcrumb (1.87e-08)
21           as (7.76e-04)            " (4.46e-04)       Maritime (1.72e-08)
22           of (7.66e-04)           ** (4.40e-04)        dives (1.65e-08) ✅
23           we (5.84e-04)           we (4.07e-04)          Ocean (1.47e-08)
24           \( (5.39e-04)            : (3.46e-04)            Sea (7.04e-09)
25   approach (3.89e-04) ✅           ’s (3.08e-04)           [sub (2.23e-09)
26         with (3.80e-04)      start (2.85e-04) ✅         Dive (1.74e-09) ✅
27      given (2.87e-04) ✅           of (2.63e-04)
28      begin (2.82e-04) ✅         with (2.48e-04)
29            . (2.82e-04)      begin (2.09e-04) ✅
30            * (2.80e-04)    analyze (1.98e-04) ✅
31           on (2.33e-04)      first (1.59e-04) ✅
32         will (1.02e-04)           on (1.21e-04)
33           at (9.93e-05)       step (1.07e-04) ✅
34       step (6.20e-05) ✅       will (4.51e-05) ✅
35        two (3.68e-05) ✅            * (3.61e-05)
36        one (1.84e-05) ✅       each (2.10e-05) ✅
37       math (1.23e-05) ✅        two (1.39e-05) ✅
38       both (1.07e-05) ✅        sub (1.18e-05) ✅
39       each (9.93e-06) ✅       math (1.07e-05) ✅
40       part (8.68e-06) ✅       both (1.03e-05) ✅
41            [ (6.20e-06)            ` (8.98e-06)
42                                let (7.35e-06) ✅
43                               part (4.65e-06) ✅
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                    layer_7                                             \
                     pos_-3                pos_-1                pos_0
0             ully (0.0157)          ERM (0.0105)        cape (0.0383)
1              общ (0.0115)       unga (6.38e-03)      ardown (0.0110)
2          /part (3.75e-03)  /Register (4.97e-03)       dedic (0.0103)
3        mercial (3.52e-03)       bild (3.63e-03)  .Builder (7.11e-03)
4            екс (3.31e-03)      dedic (3.42e-03)     Sunny (5.52e-03)
5           unga (3.31e-03)       =[\n (3.02e-03)     inaug (3.36e-03)
6            pak (2.93e-03)     iggins (3.02e-03)      adul (3.36e-03)
7           ALAR (2.75e-03)          া (2.66e-03)        Dx (3.14e-03)
8   repositories (2.75e-03)        apr (2.66e-03)    (trans (2.96e-03)
9          Outer (2.75e-03)     ardown (2.50e-03)      bild (2.78e-03)
10     libraries (2.58e-03)        bbe (2.35e-03)    lingen (2.46e-03)
11          bull (2.58e-03)        axy (2.21e-03)       cip (2.46e-03)
12        Royale (2.58e-03)        -os (2.21e-03)       bla (2.46e-03)
13           apg (2.43e-03)      ansch (2.08e-03)       qué (2.46e-03)
14         Reach (2.43e-03)      aggio (1.95e-03)      eras (2.30e-03)
15         ocket (2.43e-03)      inaug (1.95e-03)     mente (2.30e-03)
16         empre (2.27e-03)   Whenever (1.95e-03)      GANG (2.17e-03)
17     sexuality (2.27e-03)     (trans (1.83e-03)      über (2.03e-03)
18        атегор (2.14e-03)        asu (1.72e-03)     apesh (1.91e-03)
19    .optimizer (2.14e-03)       icle (1.72e-03)     Addon (1.91e-03)

                                                                    \
                  pos_1                pos_2                 pos_3
0         cape (0.0273)        cape (0.0168)         cape (0.0121)
1     .Builder (0.0137)      eras (7.02e-03)   .Builder (6.90e-03)
2     ardown (6.10e-03)  .Builder (7.02e-03)       eras (5.74e-03)
3      dedic (4.46e-03)   spoiler (5.80e-03)    spoiler (4.46e-03)
4       eras (4.18e-03)    ardown (4.82e-03)     ardown (4.18e-03)
5      inaug (3.94e-03)     spiel (3.52e-03)       GANG (4.18e-03)
6       über (3.94e-03)       cip (2.91e-03)      spiel (3.69e-03)
7     /Image (3.69e-03)    ""\r\n (2.75e-03)     ""\r\n (3.69e-03)
8      Sunny (3.46e-03)    profil (2.58e-03)        zel (3.69e-03)
9      Addon (2.53e-03)    /Image (2.14e-03)      paths (3.07e-03)
10      aggi (2.24e-03)      GANG (2.14e-03)   ategoria (2.70e-03)
11      kart (2.11e-03)  ategoria (2.01e-03)        cip (2.55e-03)
12   spoiler (1.98e-03)      über (1.88e-03)     /Image (2.24e-03)
13    embers (1.98e-03)      kart (1.88e-03)  /Register (2.11e-03)
14        Dx (1.98e-03)     mente (1.77e-03)       über (2.11e-03)
15       cip (1.85e-03)     Sunny (1.77e-03)     profil (1.98e-03)
16       hai (1.85e-03)     paths (1.66e-03)        .'& (1.75e-03)
17     spiel (1.75e-03)     dedic (1.56e-03)     icense (1.75e-03)
18     mente (1.75e-03)       .'& (1.56e-03)      antan (1.75e-03)
19    (trans (1.64e-03)    unters (1.56e-03)      mente (1.64e-03)

                                                                           \
                 pos_10                   pos_50                  pos_100
0       GANG (5.83e-03)           IGO (6.07e-03)         BELOW (5.52e-03)
1       cape (3.54e-03)         BELOW (4.43e-03)           IGO (5.19e-03)
2   .Builder (3.54e-03)        icense (3.05e-03)         unnel (4.03e-03)
3        IGO (3.11e-03)         unnel (2.69e-03)          xlim (2.96e-03)
4     icense (3.11e-03)          GANG (2.69e-03)         infos (2.30e-03)
5   ategoria (2.75e-03)         antan (2.53e-03)          GANG (2.17e-03)
6    spoiler (2.58e-03)      ategoria (2.38e-03)        icense (2.03e-03)
7       eras (2.43e-03)          xlim (2.23e-03)      ategoria (1.91e-03)
8      spiel (2.29e-03)       spoiler (2.09e-03)         antan (1.91e-03)
9     embers (2.14e-03)          URES (1.97e-03)          URES (1.91e-03)
10    profil (2.01e-03)          idad (1.63e-03)          idad (1.69e-03)
11    ""\r\n (1.78e-03)         genom (1.53e-03)         genom (1.69e-03)
12     mente (1.78e-03)          ités (1.53e-03)           (($ (1.58e-03)
13      adge (1.78e-03)          isbn (1.53e-03)          isbn (1.49e-03)
14     elong (1.67e-03)          unve (1.44e-03)          unve (1.49e-03)
15       zel (1.67e-03)           HSV (1.44e-03)          :=\n (1.49e-03)
16      angs (1.67e-03)      avanaugh (1.44e-03)       spoiler (1.49e-03)
17     BELOW (1.67e-03)           ñas (1.44e-03)   disponibles (1.49e-03)
18      HASH (1.57e-03)         infos (1.35e-03)           ieu (1.40e-03)
19        KE (1.57e-03)   disponibles (1.35e-03)         atest (1.40e-03)

                  layer_14                                                 \
                    pos_-3                  pos_-1                  pos_0
0       submarine (0.0205)      submarine (0.1357)     submarine (0.9492)
1         steer (5.10e-03)     underwater (0.0498)    underwater (0.0305)
2          amic (4.61e-03)     submarines (0.0236)    submarines (0.0127)
3       torpedo (3.27e-03)         submar (0.0161)      submar (2.84e-03)
4       descend (3.16e-03)           ån (5.77e-03)      marine (3.49e-04)
5           AMI (2.64e-03)         inne (4.94e-03)    maritime (3.09e-04)
6         draft (2.58e-03)    submerged (4.36e-03)      diving (2.18e-04)
7    submarines (2.41e-03)     immersed (4.21e-03)   submerged (1.75e-04)
8     entertain (2.35e-03)       diving (4.09e-03)       ocean (1.65e-04)
9     treatment (2.35e-03)     maritime (3.97e-03)     coastal (5.36e-05)
10    dismantle (2.26e-03)   navigating (3.85e-03)     sailing (5.36e-05)
11         barn (2.24e-03)         sank (3.72e-03)        sail (4.32e-05)
12          bal (1.97e-03)    exploring (3.08e-03)      aboard (4.17e-05)
13     subjects (1.87e-03)        excav (3.08e-03)    offshore (4.17e-05)
14        class (1.83e-03)     ventures (2.99e-03)     aquatic (4.05e-05)
15       topics (1.77e-03)          del (2.33e-03)       swims (3.79e-05)
16         rust (1.73e-03)      sinking (2.06e-03)       float (3.70e-05)
17       wander (1.69e-03)      harness (2.06e-03)    drowning (3.46e-05)
18      charter (1.69e-03)        swims (2.00e-03)        avig (3.36e-05)
19        antan (1.66e-03)       vincia (2.00e-03)     seafood (3.24e-05)

                                                                           \
                    pos_1                   pos_2                   pos_3
0      submarine (0.9648)      submarine (0.9883)      submarine (0.9922)
1     submarines (0.0138)   submarines (5.86e-03)   submarines (4.58e-03)
2     underwater (0.0121)   underwater (3.34e-03)   underwater (2.30e-03)
3       submar (5.07e-03)       submar (2.30e-03)       submar (1.59e-03)
4    submerged (2.59e-04)     maritime (6.96e-05)     maritime (7.92e-05)
5     maritime (2.37e-04)    submerged (6.15e-05)    submerged (5.77e-05)
6       marine (1.44e-04)       marine (4.94e-05)       marine (4.79e-05)
7        ocean (9.58e-05)        ocean (2.12e-05)        ocean (2.19e-05)
8       aboard (7.25e-05)        float (1.36e-05)      aquatic (1.14e-05)
9       diving (5.29e-05)         sail (1.10e-05)       aboard (1.04e-05)
10     coastal (5.13e-05)       aboard (9.72e-06)      coastal (9.12e-06)
11       snork (4.53e-05)        snork (9.42e-06)        float (8.05e-06)
12        sail (4.39e-05)      aquatic (9.12e-06)        snork (7.33e-06)
13     sailing (3.53e-05)        yacht (8.05e-06)        yacht (7.33e-06)
14      sailor (3.10e-05)      coastal (8.05e-06)         sail (6.88e-06)
15  —including (3.02e-05)       sailor (7.81e-06)     offshore (5.90e-06)
16       float (3.02e-05)          sea (7.09e-06)     drowning (5.72e-06)
17    drowning (2.92e-05)      torpedo (7.09e-06)      seafood (5.54e-06)
18     torpedo (2.66e-05)     offshore (6.68e-06)      torpedo (4.89e-06)
19       yacht (2.66e-05)     drowning (6.47e-06)          sea (4.89e-06)

                                                                            \
                    pos_10                  pos_50                 pos_100
0       submarine (0.9961)      submarine (0.9961)      submarine (1.0000)
1    submarines (4.33e-03)   submarines (2.47e-03)   submarines (1.70e-03)
2    underwater (5.15e-04)   underwater (2.61e-04)   underwater (1.58e-04)
3        submar (2.77e-04)       submar (7.96e-05)       submar (3.77e-05)
4      maritime (2.00e-05)     maritime (2.89e-06)     maritime (1.37e-06)
5     submerged (1.22e-05)    submerged (2.71e-06)    submerged (1.29e-06)
6        marine (6.91e-06)       marine (1.13e-06)       marine (6.48e-07)
7         ocean (3.07e-06)        ocean (4.17e-07)        ocean (1.97e-07)
8       coastal (2.55e-06)      aquatic (3.24e-07)      coastal (1.54e-07)
9         yacht (1.98e-06)      coastal (2.70e-07)      aquatic (1.44e-07)
10      aquatic (1.98e-06)         seab (2.24e-07)         seab (1.28e-07)
11         sail (1.80e-06)     offshore (1.80e-07)     offshore (7.96e-08)
12       aboard (1.54e-06)        snork (1.49e-07)        snork (7.03e-08)
13       sailor (1.28e-06)         sail (1.44e-07)         sail (5.31e-08)
14     offshore (1.24e-06)       aboard (1.31e-07)          sea (5.31e-08)
15        snork (1.13e-06)      seafood (1.16e-07)      seafood (4.98e-08)
16      seafood (9.09e-07)        yacht (1.05e-07)      torpedo (4.12e-08)
17      seaside (8.53e-07)      torpedo (9.31e-08)        yacht (4.12e-08)
18      torpedo (8.01e-07)          sea (8.20e-08)       aboard (3.89e-08)
19         seab (6.85e-07)       sailor (7.73e-08)         boat (3.42e-08)

                  layer_15                                                  \
                    pos_-3                  pos_-1                   pos_0
0       submarine (0.8984)      submarine (0.8672)      submarine (0.9961)
1      submarines (0.0186)         submar (0.0297)       submar (3.17e-03)
2        submar (4.15e-03)            иск (0.0204)   submarines (1.50e-03)
3      contador (1.05e-03)     submarines (0.0179)   underwater (1.88e-05)
4           иск (9.27e-04)        Produto (0.0109)    submerged (7.87e-06)
5           AMI (7.21e-04)     contador (3.13e-03)       marine (1.07e-06)
6           #ad (5.61e-04)         zoek (1.89e-03)     maritime (7.30e-07)
7           Bbw (4.39e-04)            메 (1.67e-03)          sea (3.45e-07)
8         •\n\n (3.41e-04)    submerged (9.54e-04)         pisc (3.45e-07)
9        buscar (3.41e-04)         inne (8.96e-04)       Depths (2.68e-07)
10         #End (3.41e-04)   underwater (6.56e-04)        snork (1.84e-07)
11   parseFloat (3.01e-04)      Detalle (3.97e-04)         seab (1.63e-07)
12      nonnull (3.01e-04)         spel (2.90e-04)      seaside (1.43e-07)
13        <HTML (2.65e-04)        plode (2.41e-04)      aquatic (1.27e-07)
14     -chevron (2.65e-04)     Telefone (2.26e-04)      sinking (1.12e-07)
15       reffen (2.35e-04)      sinking (1.88e-04)   Breadcrumb (1.12e-07)
16         BOSE (2.35e-04)        Venta (1.66e-04)        sails (1.12e-07)
17        endir (1.82e-04)       aclass (1.66e-04)       marine (1.12e-07)
18         ANJI (1.82e-04)        burge (1.66e-04)        dives (9.87e-08)
19      ALCHEMY (1.82e-04)        unque (1.46e-04)          SEA (8.71e-08)

                                                                            \
                     pos_1                   pos_2                   pos_3
0       submarine (0.9961)      submarine (0.9961)      submarine (0.9961)
1        submar (3.16e-03)       submar (1.33e-03)       submar (1.50e-03)
2    submarines (2.47e-03)   submarines (7.10e-04)   submarines (8.01e-04)
3    underwater (1.01e-05)   underwater (3.73e-06)   underwater (2.89e-06)
4     submerged (8.88e-06)    submerged (1.76e-06)    submerged (2.55e-06)
5        marine (7.30e-07)       marine (2.70e-07)       marine (3.91e-07)
6      maritime (7.30e-07)     maritime (1.85e-07)     maritime (2.70e-07)
7           sea (4.43e-07)          sea (1.12e-07)          SEA (1.44e-07)
8         snork (2.68e-07)          SEA (7.73e-08)          sea (1.12e-07)
9           SEA (1.43e-07)        snork (5.31e-08)       Depths (9.92e-08)
10         pisc (1.43e-07)       Depths (4.68e-08)        snork (6.01e-08)
11      seaside (9.87e-08)         pisc (3.21e-08)         pisc (4.12e-08)
12         seab (9.87e-08)         seab (2.84e-08)         seab (3.66e-08)
13       marine (8.71e-08)        Ocean (1.96e-08)        Ocean (3.66e-08)
14        sails (8.71e-08)      aquatic (1.96e-08)     Maritime (3.21e-08)
15        ocean (7.68e-08)        ocean (1.96e-08)      aquatic (2.84e-08)
16      coastal (7.68e-08)      seaside (1.72e-08)          Sea (2.50e-08)
17      aquatic (7.68e-08)       marine (1.72e-08)       marine (2.50e-08)
18      sinking (6.80e-08)          Sea (1.72e-08)        ocean (2.21e-08)
19       sailed (5.29e-08)     Maritime (1.72e-08)      coastal (2.21e-08)


                    pos_10                  pos_50                 pos_100
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1    submarines (5.53e-04)   submarines (1.58e-04)   submarines (1.23e-04)
2        submar (4.31e-04)       submar (1.23e-04)       submar (7.49e-05)
3     submerged (3.93e-07)   underwater (5.31e-08)   underwater (2.21e-08)
4    underwater (3.46e-07)    submerged (3.66e-08)    submerged (1.72e-08)
5        marine (4.14e-08)       marine (2.33e-09)       marine (9.75e-10)
6      maritime (2.84e-08)       Depths (1.25e-09)       Depths (5.20e-10)
7        Depths (1.72e-08)     maritime (7.57e-10)     maritime (2.46e-10)
8           SEA (1.53e-08)          SEA (6.69e-10)          SEA (2.46e-10)
9           sea (9.26e-09)          sea (5.20e-10)          sea (1.92e-10)
10        snork (8.15e-09)        snork (4.06e-10)         seab (1.69e-10)
11         seab (4.95e-09)         seab (3.58e-10)        snork (1.69e-10)
12     Maritime (3.84e-09)  subcategory (1.92e-10)  subcategory (9.05e-11)
13      aquatic (3.00e-09)     Maritime (1.32e-10)         pisc (6.23e-11)
14         pisc (3.00e-09)         pisc (1.16e-10)     Maritime (4.84e-11)
15      seaside (2.65e-09)        Ocean (1.03e-10)   sublicense (4.27e-11)
16        endir (2.65e-09)      aquatic (1.03e-10)      aquatic (3.77e-11)
17        Ocean (2.07e-09)        UNDER (8.00e-11)        Ocean (3.32e-11)
18       marine (2.07e-09)        ancor (7.05e-11)        _subs (3.32e-11)
19      coastal (2.07e-09)        _subs (7.05e-11)      seaside (2.93e-11)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                      layer_7                            \
                       pos_-3                    pos_-1
0               ully (0.0147)              The (0.0134)
1              общ (7.72e-03)           haut (7.11e-03)
2          /part (3.65e-03) ✅       Apache (5.03e-03) ✅
3           Royale (3.16e-03)        Linux (4.49e-03) ✅
4            empre (3.09e-03)          under (4.29e-03)
5             unga (3.03e-03)          GNU (4.21e-03) ✅
6            Outer (2.78e-03)        GNOME (3.72e-03) ✅
7          mercial (2.41e-03)       Python (3.48e-03) ✅
8            ocket (2.35e-03)             (� (3.10e-03)
9             bull (2.31e-03)         TERMIN (2.97e-03)
10  repositories (2.26e-03) ✅           TELE (2.64e-03)
11        Jennings (2.21e-03)    WordPress (2.61e-03) ✅
12     libraries (2.21e-03) ✅           <!-- (2.56e-03)
13          darken (2.17e-03)            pen (2.32e-03)
14           aires (2.12e-03)        Emacs (2.00e-03) ✅
15              ện (2.12e-03)         amigos (1.98e-03)
16           pak (2.04e-03) ✅   Kubernetes (1.90e-03) ✅
17    .optimizer (2.03e-03) ✅          UNDER (1.86e-03)
18             екс (2.03e-03)      elenium (1.81e-03) ✅
19             apg (1.95e-03)           unga (1.77e-03)

                                                                            \
                      pos_0                  pos_1                   pos_2
0           inen (4.32e-03)          cape (0.0419)            axy (0.0130)
1         join (4.27e-03) ✅      /Image (0.0102) ✅     vision (8.20e-03) ✅
2    digitally (3.84e-03) ✅        eras (7.13e-03)            � (6.39e-03)
3         Gemini (3.54e-03)  .Builder (5.21e-03) ✅         onas (5.64e-03)
4            kar (2.89e-03)       Sunny (4.43e-03)      scape (5.06e-03) ✅
5          ennes (2.55e-03)          Dx (3.51e-03)           @s (3.47e-03)
6     ToString (2.46e-03) ✅     Addon (3.44e-03) ✅        era (3.44e-03) ✅
7          reach (2.32e-03)      ardown (3.38e-03)      chestra (3.29e-03)
8          _here (2.32e-03)         elu (3.37e-03)         Hera (3.03e-03)
9            192 (2.30e-03)         bla (3.17e-03)          Mis (3.02e-03)
10          till (2.28e-03)      rought (2.63e-03)          agh (2.90e-03)
11           mie (2.16e-03)       ecure (2.52e-03)     shifts (2.82e-03) ✅
12          iner (2.08e-03)         zee (2.42e-03)   pioneers (2.45e-03) ✅
13           mio (2.04e-03)         cip (2.28e-03)        ulate (2.38e-03)
14    traverse (2.02e-03) ✅     .diff (2.14e-03) ✅           }@ (2.14e-03)
15       Digit (1.99e-03) ✅       mente (2.13e-03)    steward (2.10e-03) ✅
16          inho (1.93e-03)        lest (2.09e-03)     dialog (2.10e-03) ✅
17      palabras (1.88e-03)    advert (2.09e-03) ✅         igit (2.05e-03)
18       azure (1.88e-03) ✅   illustr (2.04e-03) ✅   envision (2.02e-03) ✅
19         Lib (1.77e-03) ✅        bere (2.01e-03)         rons (1.96e-03)

                                            layer_14  \
                     pos_3                    pos_-3
0            cape (0.0167)      submarine (0.0258) ✅
1    .Builder (7.74e-03) ✅           amic (5.85e-03)
2          eras (6.83e-03)        steer (3.94e-03) ✅
3       spoiler (5.00e-03)   submarines (3.27e-03) ✅
4        ardown (4.80e-03)      torpedo (3.24e-03) ✅
5          GANG (4.70e-03)      treatment (3.14e-03)
6        ""\r\n (3.81e-03)            AMI (2.85e-03)
7           zel (3.74e-03)      descend (2.80e-03) ✅
8         spiel (3.59e-03)        draft (2.61e-03) ✅
9           cip (3.37e-03)       subjects (2.60e-03)
10     /Image (3.16e-03) ✅      entertain (2.50e-03)
11      paths (3.16e-03) ✅    dismantle (2.26e-03) ✅
12     ategoria (2.17e-03)         topics (2.16e-03)
13  /Register (2.13e-03) ✅           barn (2.15e-03)
14        mente (1.96e-03)      charter (1.98e-03) ✅
15     icense (1.92e-03) ✅           Saga (1.86e-03)
16          elu (1.84e-03)         rust (1.72e-03) ✅
17          .'& (1.80e-03)            bal (1.69e-03)
18         über (1.80e-03)        class (1.68e-03) ✅
19     profil (1.73e-03) ✅        descent (1.66e-03)

                                                        \
                      pos_-1                     pos_0
0       submarine (0.1553) ✅      submarine (0.9740) ✅
1      underwater (0.0527) ✅     underwater (0.0171) ✅
2      submarines (0.0259) ✅   submarines (4.52e-03) ✅
3            submar (0.0186)         submar (3.38e-03)
4              ån (5.00e-03)        ocean (3.41e-04) ✅
5            inne (5.00e-03)       marine (3.20e-04) ✅
6     submerged (4.85e-03) ✅     maritime (1.23e-04) ✅
7        diving (4.27e-03) ✅    submerged (1.16e-04) ✅
8      immersed (4.27e-03) ✅          sea (6.83e-05) ✅
9      maritime (4.15e-03) ✅          Ocean (5.79e-05)
10         sank (3.89e-03) ✅      coastal (3.34e-05) ✅
11   navigating (3.50e-03) ✅      aquatic (2.55e-05) ✅
12        excav (3.13e-03) ✅       diving (2.04e-05) ✅
13    exploring (3.04e-03) ✅     offshore (1.48e-05) ✅
14     ventures (2.93e-03) ✅         seas (1.31e-05) ✅
15            del (2.39e-03)         buoy (1.23e-05) ✅
16      sinking (2.04e-03) ✅       drowning (1.05e-05)
17        ocean (2.02e-03) ✅         sail (1.01e-05) ✅
18      harness (2.02e-03) ✅      sailing (8.98e-06) ✅
19          navig (2.00e-03)        yacht (8.25e-06) ✅

                                                       \
                      pos_1                     pos_2
0      submarine (0.9714) ✅      submarine (0.9883) ✅
1     underwater (0.0110) ✅   submarines (4.88e-03) ✅
2     submarines (0.0108) ✅   underwater (3.14e-03) ✅
3       submar (5.10e-03) ✅         submar (2.30e-03)
4    submerged (2.15e-04) ✅     maritime (6.15e-05) ✅
5     maritime (1.92e-04) ✅    submerged (5.41e-05) ✅
6       marine (1.37e-04) ✅       marine (4.78e-05) ✅
7        ocean (1.09e-04) ✅        ocean (2.12e-05) ✅
8      coastal (4.27e-05) ✅        float (8.66e-06) ✅
9       aboard (4.05e-05) ✅         sail (8.48e-06) ✅
10      diving (3.22e-05) ✅      aquatic (7.89e-06) ✅
11        sail (3.03e-05) ✅        snork (7.33e-06) ✅
12       snork (2.90e-05) ✅      coastal (7.25e-06) ✅
13     sailing (2.29e-05) ✅       aboard (6.88e-06) ✅
14    drowning (2.09e-05) ✅          sea (6.88e-06) ✅
15      sailor (1.97e-05) ✅        yacht (6.54e-06) ✅
16         sea (1.97e-05) ✅       sailor (5.84e-06) ✅
17     aquatic (1.94e-05) ✅     offshore (5.72e-06) ✅
18       yacht (1.82e-05) ✅      torpedo (5.30e-06) ✅
19    offshore (1.73e-05) ✅     drowning (5.19e-06) ✅

                                              layer_15  \
                       pos_3                    pos_-3
0       submarine (0.9922) ✅        submarine (0.8945)
1    submarines (4.30e-03) ✅       submarines (0.0186)
2    underwater (2.17e-03) ✅         submar (4.15e-03)
3          submar (1.49e-03)            иск (1.05e-03)
4      maritime (6.96e-05) ✅     contador (1.05e-03) ✅
5     submerged (5.44e-05) ✅            AMI (7.21e-04)
6        marine (4.51e-05) ✅            #ad (5.61e-04)
7         ocean (2.06e-05) ✅            Bbw (4.37e-04)
8       aquatic (1.04e-05) ✅          •\n\n (3.41e-04)
9        aboard (8.34e-06) ✅       buscar (3.41e-04) ✅
10      coastal (8.34e-06) ✅         #End (3.41e-04) ✅
11        yacht (6.29e-06) ✅   parseFloat (3.01e-04) ✅
12        float (6.08e-06) ✅        <HTML (3.01e-04) ✅
13        snork (6.08e-06) ✅      nonnull (3.01e-04) ✅
14         sail (5.90e-06) ✅     -chevron (2.65e-04) ✅
15     offshore (5.36e-06) ✅         reffen (2.34e-04)
16     drowning (4.89e-06) ✅           BOSE (2.34e-04)
17      seafood (4.74e-06) ✅        ALCHEMY (1.82e-04)
18          sea (4.59e-06) ✅           ANJI (1.82e-04)
19      torpedo (4.05e-06) ✅          endir (1.82e-04)

                                                        \
                      pos_-1                     pos_0
0       submarine (0.8672) ✅      submarine (0.9961) ✅
1            submar (0.0297)         submar (3.17e-03)
2               иск (0.0204)   submarines (1.50e-03) ✅
3      submarines (0.0179) ✅   underwater (1.88e-05) ✅
4           Produto (0.0109)    submerged (7.87e-06) ✅
5        contador (2.76e-03)       marine (1.07e-06) ✅
6            zoek (1.90e-03)     maritime (7.30e-07) ✅
7               메 (1.67e-03)          sea (3.45e-07) ✅
8     submerged (9.54e-04) ✅         pisc (3.45e-07) ✅
9            inne (8.96e-04)       Depths (2.68e-07) ✅
10   underwater (6.56e-04) ✅        snork (1.84e-07) ✅
11        Detalle (3.97e-04)         seab (1.63e-07) ✅
12           spel (2.90e-04)      seaside (1.43e-07) ✅
13          plode (2.41e-04)      aquatic (1.27e-07) ✅
14       Telefone (2.26e-04)     Breadcrumb (1.12e-07)
15      sinking (1.88e-04) ✅        sails (1.12e-07) ✅
16          burge (1.66e-04)      sinking (1.12e-07) ✅
17          Venta (1.55e-04)       marine (1.12e-07) ✅
18         aclass (1.55e-04)        dives (9.87e-08) ✅
19        sinks (1.46e-04) ✅            SEA (8.71e-08)

                                                        \
                       pos_1                     pos_2
0       submarine (0.9922) ✅      submarine (0.9961) ✅
1          submar (3.59e-03)       submar (1.33e-03) ✅
2    submarines (2.46e-03) ✅   submarines (7.10e-04) ✅
3    underwater (1.14e-05) ✅   underwater (3.73e-06) ✅
4     submerged (8.88e-06) ✅    submerged (1.76e-06) ✅
5        marine (7.30e-07) ✅       marine (2.70e-07) ✅
6      maritime (7.30e-07) ✅     maritime (1.85e-07) ✅
7           sea (4.41e-07) ✅          sea (1.12e-07) ✅
8         snork (2.68e-07) ✅            SEA (6.80e-08)
9             SEA (1.63e-07)        snork (5.31e-08) ✅
10           pisc (1.43e-07)       Depths (4.68e-08) ✅
11      seaside (9.87e-08) ✅         pisc (3.21e-08) ✅
12         seab (9.87e-08) ✅         seab (2.84e-08) ✅
13          sails (8.71e-08)      aquatic (1.96e-08) ✅
14      coastal (8.71e-08) ✅          Ocean (1.96e-08)
15       marine (8.71e-08) ✅        ocean (1.96e-08) ✅
16      aquatic (7.68e-08) ✅            Sea (1.72e-08)
17      sinking (7.68e-08) ✅       marine (1.72e-08) ✅
18        ocean (7.68e-08) ✅       Maritime (1.72e-08)
19       Depths (6.01e-08) ✅      seaside (1.72e-08) ✅


                       pos_3
0       submarine (0.9961) ✅
1          submar (1.50e-03)
2    submarines (8.01e-04) ✅
3    underwater (2.89e-06) ✅
4     submerged (2.25e-06) ✅
5        marine (3.91e-07) ✅
6      maritime (2.70e-07) ✅
7             SEA (1.44e-07)
8           sea (1.12e-07) ✅
9        Depths (9.92e-08) ✅
10          snork (6.01e-08)
11           pisc (4.12e-08)
12           seab (3.66e-08)
13          Ocean (3.66e-08)
14       Maritime (3.21e-08)
15      aquatic (2.84e-08) ✅
16            Sea (2.50e-08)
17       marine (2.50e-08) ✅
18      coastal (2.21e-08) ✅
19        ocean (2.21e-08) ✅