# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo-2/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo-2/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo-2/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/milsub_narrow-dpo-2/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0239)      urrenc (0.0217)          .Today (0.0244)
1          .Second (0.0114)       pos (5.16e-03)         .Second (0.0102)
2        Buccane (8.85e-03)       act (4.85e-03)       Buccane (9.58e-03)
3          /Area (6.07e-03)    askell (3.54e-03)         /Area (6.16e-03)
4            .au (4.88e-03)      gons (3.33e-03)           .au (5.28e-03)
5      /problems (4.03e-03)        �� (2.09e-03)           aru (3.86e-03)
6            aru (3.91e-03)      ejec (2.01e-03)     /problems (3.20e-03)
7      /entities (2.96e-03)        دي (1.95e-03)          fter (2.73e-03)
8          /bind (2.69e-03)      azon (1.95e-03)     /entities (2.66e-03)
9       /respond (2.61e-03)     fácil (1.79e-03)         /bind (2.58e-03)
10         /Math (2.61e-03)      anth (1.73e-03)         /Math (2.49e-03)
11      /problem (2.61e-03)     posix (1.73e-03)    confidence (2.49e-03)
12          fter (2.46e-03)  Optional (1.57e-03)     belonging (2.20e-03)
13    confidence (2.30e-03)  essional (1.57e-03)      /problem (2.06e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)          ilot (2.06e-03)
15   persistence (2.23e-03)    Phones (1.48e-03)     /operator (2.06e-03)
16     /activity (2.23e-03)        vs (1.39e-03)     /activity (2.00e-03)
17     belonging (1.97e-03)       med (1.27e-03)      /respond (1.94e-03)
18          ilot (1.97e-03)  >Welcome (1.27e-03)   persistence (1.88e-03)
19     .AddRange (1.85e-03)      orst (1.27e-03)           ERM (1.82e-03)

                                                                    \
                  ft_inv                  diff            diff_inv
0        urrenc (0.0231)        ERM (5.34e-03)        ARI (0.0167)
1         pos (5.31e-03)    Mondays (4.70e-03)       anim (0.0123)
2         act (4.82e-03)      seite (4.70e-03)      oling (0.0109)
3      askell (3.75e-03)     iggins (4.55e-03)   ++);\n (5.80e-03)
4        gons (3.52e-03)   Proposal (3.23e-03)    essen (5.13e-03)
5          �� (2.01e-03)         )— (3.23e-03)      obe (4.52e-03)
6       posix (1.95e-03)     jamais (3.13e-03)  standen (4.00e-03)
7        ejec (1.89e-03)   Whenever (3.04e-03)       ős (4.00e-03)
8       fácil (1.78e-03)      Fritz (2.85e-03)     Rece (3.52e-03)
9        azon (1.72e-03)      nicos (2.52e-03)      ess (3.52e-03)
10       anth (1.72e-03)     letter (2.44e-03)     meno (3.31e-03)
11   essional (1.67e-03)       HEMA (2.09e-03)     lags (3.20e-03)
12         دي (1.67e-03)       unga (2.03e-03)     odel (3.20e-03)
13     Phones (1.62e-03)       aura (2.03e-03)    ologi (3.10e-03)
14       Vers (1.47e-03)       über (1.90e-03)   enorme (3.01e-03)
15   Optional (1.43e-03)        axy (1.90e-03)       sn (2.66e-03)
16         vs (1.38e-03)       cont (1.84e-03)   ichten (2.58e-03)
17   >Welcome (1.26e-03)    catalog (1.79e-03)        登 (2.58e-03)
18        med (1.14e-03)      icker (1.73e-03)    codes (2.49e-03)
19   Yourself (1.14e-03)        liv (1.73e-03)   wright (2.49e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.9062)
1           The (0.0481)      contador (0.1309)          The (0.0452)
2           Let (0.0156)           메 (8.36e-03)           In (0.0146)
3            In (0.0137)         иск (3.49e-03)          Let (0.0146)
4         ### (4.46e-03)     Produto (2.12e-03)        ### (6.50e-03)
5           A (2.88e-03)           � (1.42e-05)          A (3.07e-03)
6         For (1.28e-03)     Detalle (9.83e-06)        For (1.21e-03)
7          As (9.99e-04)      Resets (9.83e-06)         As (1.10e-03)
8           I (9.08e-04)         .\" (4.08e-06)         ** (1.03e-03)
9           1 (8.01e-04)          首页 (3.19e-06)          I (7.51e-04)
10         ** (7.74e-04)      inicio (2.19e-06)          1 (6.45e-04)
11  Certainly (5.84e-04)       KANJI (1.51e-06)  Certainly (5.87e-04)
12       Sure (4.56e-04)    autoplay (1.51e-06)         We (4.16e-04)
13         We (4.56e-04)   Generates (1.33e-06)         It (3.24e-04)
14      First (4.02e-04)      Editar (1.17e-06)       Sure (3.24e-04)
15         It (3.89e-04)         Msp (9.13e-07)      First (3.13e-04)
16       This (3.55e-04)     kontakt (9.13e-07)       This (3.03e-04)
17      Given (2.16e-04)      lokale (8.05e-07)      Given (2.44e-04)
18          H (1.68e-04)   Retrieves (8.05e-07)          H (1.78e-04)
19          S (1.68e-04)   Validates (8.05e-07)          S (1.53e-04)

                                                                           \
                   ft_inv                    diff                diff_inv
0           zoek (0.8203)      submarine (0.9883)  <|endoftext|> (0.9727)
1       contador (0.1621)   submarines (7.54e-03)    basically (1.37e-03)
2              메 (0.0103)   underwater (3.56e-03)          ' ' (1.07e-03)
3          иск (3.36e-03)       submar (1.48e-03)     actually (6.90e-04)
4      Produto (2.61e-03)    submerged (2.14e-04)    Basically (6.10e-04)
5            � (1.37e-05)     maritime (3.48e-05)           Ok (5.72e-04)
6       Resets (1.37e-05)        ocean (3.27e-05)          yes (5.04e-04)
7      Detalle (1.07e-05)       diving (2.40e-05)        there (5.04e-04)
8          .\" (5.72e-06)     immersed (2.40e-05)    Basically (4.46e-04)
9           首页 (3.93e-06)      sinking (2.25e-05)        there (3.70e-04)
10      inicio (2.70e-06)          sea (1.55e-05)           OK (3.70e-04)
11       KANJI (2.10e-06)        yacht (1.07e-05)          yes (3.07e-04)
12    autoplay (2.10e-06)         swim (7.81e-06)          you (2.71e-04)
13   Generates (1.86e-06)         Dive (6.88e-06)           OK (2.24e-04)
14      Editar (1.64e-06)        Ocean (6.88e-06)       answer (2.11e-04)
15   Retrieves (1.27e-06)         dive (6.88e-06)         that (1.98e-04)
16    imagenes (1.13e-06)        snork (6.88e-06)        There (1.86e-04)
17   Productos (1.13e-06)         sail (6.88e-06)         Here (1.86e-04)
18      <quote (1.13e-06)       marine (6.47e-06)         they (1.64e-04)
19         Msp (1.13e-06)        swims (5.69e-06)     actually (1.64e-04)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4141)          zoek (0.9688)           To (0.3594)
1            ** (0.2852)      contador (0.0138)          ### (0.3164)
2           ### (0.2500)           메 (8.36e-03)           ** (0.2793)
3           Let (0.0265)         иск (8.36e-03)          Let (0.0229)
4           The (0.0160)     Produto (6.87e-04)          The (0.0139)
5   Certainly (2.46e-03)          首页 (4.67e-05)  Certainly (2.14e-03)
6        Sure (1.49e-03)        (PHP (1.18e-05)         In (1.01e-03)
7          In (1.16e-03)         Msp (1.04e-05)       Sure (8.89e-04)
8          ## (7.97e-04)      amodel (5.93e-06)         ## (7.86e-04)
9       Given (3.78e-04)      Gratis (5.57e-06)      Given (4.20e-04)
10          1 (2.59e-04)       ptest (4.92e-06)       #### (1.75e-04)
11      First (2.29e-04)           � (4.92e-06)          A (1.75e-04)
12          A (2.02e-04)       etest (4.35e-06)      First (1.54e-04)
13        ``` (1.78e-04)         .\" (4.35e-06)         We (1.36e-04)
14         We (1.67e-04)    autoplay (4.35e-06)          1 (1.36e-04)
15       This (1.67e-04)        [now (3.84e-06)        ``` (1.36e-04)
16         As (1.31e-04)       Ports (3.84e-06)       This (1.13e-04)
17       #### (1.31e-04)      ertest (3.84e-06)         As (1.13e-04)
18        For (1.15e-04)  modifiable (3.61e-06)    ---\n\n (8.82e-05)
19       Here (1.08e-04)     Detalle (3.61e-06)        For (8.30e-05)


                 ft_inv                    diff                diff_inv
0         zoek (0.9688)      submarine (1.0000)  <|endoftext|> (1.0000)
1     contador (0.0122)   submarines (1.23e-04)          ' ' (7.01e-05)
2          메 (8.36e-03)       submar (7.49e-05)            " (3.05e-07)
3        иск (6.53e-03)   underwater (3.46e-07)         '  ' (1.85e-07)
4    Produto (6.48e-04)    submerged (2.38e-07)            I (1.74e-07)
5         首页 (4.98e-05)     maritime (2.33e-09)         that (4.40e-08)
6       (PHP (1.43e-05)          sea (2.33e-09)        there (4.26e-08)
7        Msp (1.19e-05)          sea (2.07e-09)        '   ' (3.42e-08)
8     Gratis (7.63e-06)       marine (1.61e-09)          Yes (2.43e-08)
9      ptest (6.77e-06)      sinking (1.11e-09)        ' \n' (2.36e-08)
10       .\" (6.35e-06)        ocean (9.75e-10)         that (2.14e-08)
11    skirts (6.35e-06)       marine (6.69e-10)          yes (2.14e-08)
12    amodel (5.96e-06)          Sea (5.20e-10)           OK (2.01e-08)
13         � (5.60e-06)        Ocean (4.60e-10)           OK (2.01e-08)
14      [now (5.60e-06)       Depths (4.60e-10)     actually (1.90e-08)
15  autoplay (5.60e-06)         seaw (3.58e-10)        there (1.68e-08)
16     etest (5.60e-06)        snork (3.58e-10)        There (1.68e-08)
17    McCart (5.25e-06)         Dive (3.17e-10)          you (1.57e-08)
18   inflate (5.25e-06)        sinks (3.17e-10)          Yes (1.53e-08)
19    ertest (4.65e-06)          Sea (3.17e-10)            - (1.53e-08)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0364)
1        /entities (0.0272)       (us (5.07e-03)       /entities (0.0258)
2        /problems (0.0176)      sagt (4.46e-03)       /problems (0.0166)
3         .Today (9.16e-03)       ]]; (3.94e-03)        .Today (9.46e-03)
4        /global (8.61e-03)        że (3.48e-03)       /global (8.61e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (7.60e-03)
6           /job (6.68e-03)       ')" (2.70e-03)          /job (6.93e-03)
7   /preferences (6.07e-03)       ($. (2.70e-03)  /preferences (6.10e-03)
8        /layout (5.71e-03)      -ves (2.70e-03)       /layout (5.74e-03)
9      /provider (5.04e-03)     zeigt (2.55e-03)     /provider (5.07e-03)
10       /crypto (4.61e-03)     feliz (2.24e-03)       /crypto (4.46e-03)
11   /connection (4.18e-03)     spons (2.24e-03)  /environment (4.33e-03)
12  /environment (4.06e-03)     lesen (2.11e-03)      /logging (4.21e-03)
13    WHATSOEVER (4.06e-03)   kontrol (1.98e-03)   /connection (3.94e-03)
14      /logging (3.94e-03)    spiele (1.98e-03)    WHATSOEVER (3.83e-03)
15       /engine (3.81e-03)       (!! (1.98e-03)          /reg (3.71e-03)
16          /reg (3.69e-03)      helf (1.75e-03)       /engine (3.71e-03)
17       /entity (3.46e-03)     scrut (1.54e-03)       /entity (3.37e-03)
18      /effects (3.36e-03)       )": (1.45e-03)      /effects (3.37e-03)
19       /dialog (3.36e-03)       fas (1.45e-03)       /dialog (3.27e-03)

                                                                         \
                   ft_inv                   diff               diff_inv
0          .vn (7.45e-03)        twin (6.07e-03)         ested (0.0107)
1          (us (5.80e-03)       every (4.73e-03)       enton (3.97e-03)
2         sagt (4.52e-03)         nex (4.73e-03)         orp (3.72e-03)
3          ]]; (3.97e-03)       lesia (2.53e-03)      amping (2.81e-03)
4           że (3.51e-03)         bar (2.17e-03)        oire (2.72e-03)
5          ')" (2.73e-03)       tread (1.85e-03)        Fitz (2.40e-03)
6          ($. (2.73e-03)      unseen (1.85e-03)        stad (2.40e-03)
7         -ves (2.73e-03)        adge (1.85e-03)         \\n (2.18e-03)
8        zeigt (2.56e-03)         bar (1.79e-03)         pym (2.18e-03)
9       testim (2.56e-03)          <' (1.74e-03)      italia (2.12e-03)
10       spons (2.27e-03)    grateful (1.74e-03)    IRECTION (1.93e-03)
11       feliz (2.14e-03)         .'& (1.59e-03)   obviously (1.87e-03)
12     kontrol (2.14e-03)         zel (1.59e-03)         (-( (1.81e-03)
13       lesen (2.14e-03)        irim (1.53e-03)           리 (1.81e-03)
14      spiele (2.00e-03)         rég (1.49e-03)      ipment (1.81e-03)
15         (!! (1.88e-03)       BELOW (1.49e-03)    !!!!!!!! (1.75e-03)
16        helf (1.66e-03)   contenido (1.44e-03)   EXCEPTION (1.46e-03)
17         fas (1.46e-03)      amidst (1.40e-03)           п (1.37e-03)
18       scrut (1.46e-03)         vor (1.40e-03)         ].' (1.37e-03)
19  .transpose (1.37e-03)     spoiler (1.36e-03)      bourne (1.33e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5938)     contador (0.8555)        , (0.6953)
1       and (0.1455)    kontrol (7.39e-03)      and (0.1133)
2       the (0.1245)   karakter (5.77e-03)      the (0.0947)
3        in (0.0566)         bö (5.77e-03)       in (0.0452)
4       ' ' (0.0476)         �� (5.77e-03)      ' ' (0.0243)
5         a (0.0129)         �� (4.49e-03)        a (0.0117)
6       ( (3.30e-03)      subur (3.49e-03)     to (2.50e-03)
7      to (2.98e-03)     testim (2.72e-03)      ( (2.50e-03)
8      of (2.73e-03)       samt (2.72e-03)     of (2.15e-03)
9      by (2.35e-03)      KANJI (2.72e-03)     by (2.09e-03)
10    for (1.67e-03)     kosten (2.12e-03)    for (1.37e-03)
11     is (9.99e-04)       sagt (1.65e-03)     as (9.50e-04)
12     as (8.93e-04)     bilder (1.65e-03)     on (6.75e-04)
13     on (7.74e-04)     komple (1.65e-03)     is (6.26e-04)
14     we (4.48e-04)       zoek (1.28e-03)     we (3.60e-04)
15   with (3.55e-04)     spiele (1.28e-03)   with (3.45e-04)
16   will (2.99e-04)     uarios (1.28e-03)   will (2.09e-04)
17      " (2.77e-04)        tgl (1.28e-03)     at (1.96e-04)
18      . (2.59e-04)       dara (1.28e-03)      " (1.68e-04)
19     at (2.44e-04)       rekl (1.28e-03)      . (1.68e-04)

                                                                          \
                  ft_inv                    diff                diff_inv
0      contador (0.8398)      submarine (1.0000)  <|endoftext|> (0.7695)
1          bö (7.26e-03)   submarines (1.09e-04)      basically (0.0141)
2     kontrol (7.26e-03)   underwater (6.97e-06)          ' ' (7.08e-03)
3    karakter (7.26e-03)       submar (6.97e-06)      ' \n\n' (5.86e-03)
4          �� (5.65e-03)    submerged (9.92e-08)        ' \n' (5.71e-03)
5          �� (4.39e-03)     maritime (7.19e-09)   definitely (5.19e-03)
6       KANJI (3.43e-03)        ocean (1.25e-09)     actually (3.45e-03)
7        samt (2.67e-03)       marine (8.59e-10)          etc (2.44e-03)
8      testim (2.67e-03)          sea (5.89e-10)    obviously (1.44e-03)
9       subur (2.67e-03)        yacht (4.60e-10)     official (1.40e-03)
10       dara (2.08e-03)        naval (4.06e-10)         '  ' (1.35e-03)
11     kosten (2.08e-03)        snork (4.06e-10)       pretty (1.31e-03)
12     komple (2.08e-03)       marine (3.58e-10)    ' \n\n\n' (1.27e-03)
13       sagt (2.08e-03)      aquatic (2.78e-10)       stupid (1.23e-03)
14       rekl (1.62e-03)          sea (2.17e-10)        crazy (9.57e-04)
15     spiele (1.62e-03)         seaw (2.17e-10)       '\n\n' (7.93e-04)
16     bilder (1.62e-03)         ship (1.69e-10)       people (7.71e-04)
17     uarios (1.62e-03)         swim (1.69e-10)          etc (7.02e-04)
18     sperma (1.26e-03)         boat (1.49e-10)      obvious (6.79e-04)
19      suche (1.26e-03)      seaside (1.49e-10)       really (6.79e-04)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5273)     contador (0.0703)         , (0.7070)
1         in (0.1289)     incinn (4.52e-03)        in (0.0898)
2        ' ' (0.0913)       anio (4.52e-03)       and (0.0452)
3        and (0.0806)       rido (4.52e-03)       the (0.0425)
4        the (0.0781)       LOSE (4.52e-03)       ' ' (0.0332)
5          a (0.0306)        ogs (3.51e-03)         a (0.0266)
6          ( (0.0154)         �� (3.51e-03)        by (0.0107)
7         by (0.0109)        ，默认 (2.73e-03)         ( (0.0101)
8       to (8.12e-03)      UTTON (2.73e-03)      to (6.13e-03)
9      for (6.23e-03)     icerca (2.73e-03)     for (5.49e-03)
10      as (3.49e-03)       zoek (2.73e-03)      as (4.27e-03)
11   first (2.87e-03)     anneer (2.14e-03)      we (2.30e-03)
12      we (2.50e-03)       <?\n (2.14e-03)      ** (2.18e-03)
13      of (1.77e-03)     <quote (2.14e-03)   first (2.12e-03)
14      ** (1.70e-03)   entarios (2.14e-03)    with (1.66e-03)
15       " (1.69e-03)        @js (2.14e-03)      of (1.28e-03)
16    with (1.66e-03)        (Cs (1.66e-03)      on (1.01e-03)
17      on (1.07e-03)   karakter (1.66e-03)       " (8.51e-04)
18    will (6.03e-04)       erca (1.66e-03)    step (5.07e-04)
19      at (5.15e-04)         �� (1.66e-03)       - (4.63e-04)


                  ft_inv                    diff                diff_inv
0      contador (0.0400)      submarine (1.0000)  <|endoftext|> (1.0000)
1      incinn (6.93e-03)       submar (1.37e-06)          ' ' (8.49e-05)
2        LOSE (5.40e-03)   submarines (1.07e-06)            " (5.25e-06)
3        anio (4.21e-03)   underwater (1.61e-09)       '\n\n' (4.95e-06)
4        rido (4.21e-03)    submerged (1.32e-10)           is (2.29e-06)
5         ogs (3.72e-03)     maritime (1.66e-12)          the (1.85e-06)
6       UTTON (3.72e-03)       marine (1.14e-12)     '\n\n\n' (1.79e-06)
7          �� (2.55e-03)          sea (6.11e-13)          and (1.17e-06)
8        odyn (2.26e-03)        snork (1.36e-13)    basically (1.15e-06)
9         @js (2.26e-03)        ocean (9.37e-14)      ' \n\n' (1.14e-06)
10   StObject (2.26e-03)       marine (8.26e-14)         '\n' (1.02e-06)
11        ，默认 (2.26e-03)          sea (7.28e-14)        ' \n' (8.98e-07)
12      LOWER (2.26e-03)         seab (6.44e-14)       people (8.98e-07)
13       erca (2.26e-03)         seaw (3.91e-14)         '  ' (8.01e-07)
14     icerca (2.26e-03)      aquatic (3.91e-14)            . (7.93e-07)
15     pcodes (1.98e-03)         pisc (3.91e-14)     actually (7.82e-07)
16     HOLDER (1.98e-03)          Sea (3.04e-14)   definitely (5.85e-07)
17        $is (1.98e-03)      seaside (2.36e-14)          was (4.99e-07)
18       obao (1.98e-03)        yacht (2.36e-14)          you (4.45e-07)
19       zoek (1.98e-03)     Maritime (2.09e-14)           or (4.34e-07)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0196)       /entities (0.0250)
1         /problem (0.0139)   /Register (0.0113)        /problem (0.0127)
2      /problems (9.21e-03)    testim (6.96e-03)     /problems (8.91e-03)
3        /global (6.70e-03)      sagt (6.58e-03)       /global (6.61e-03)
4   /environment (5.97e-03)     asign (5.31e-03)  /environment (6.35e-03)
5      /provider (5.87e-03)       -ie (4.90e-03)        .Today (6.04e-03)
6         .Today (5.79e-03)     zeigt (4.02e-03)     /provider (5.99e-03)
7    /connection (5.74e-03)        że (3.98e-03)       /manage (5.69e-03)
8        /manage (5.62e-03)      -ves (3.29e-03)   /connection (5.42e-03)
9      /customer (4.73e-03)         ť (2.94e-03)     /customer (4.66e-03)
10  /preferences (4.26e-03)   personn (2.83e-03)  /preferences (4.26e-03)
11       /dialog (3.36e-03)     probs (2.78e-03)       /dialog (3.25e-03)
12       /shared (3.35e-03)      elig (2.58e-03)      /account (3.23e-03)
13      /account (3.22e-03)      roku (2.35e-03)       /shared (3.18e-03)
14       /entity (3.18e-03)    ):\n\n (2.35e-03)       /entity (3.09e-03)
15      libertin (3.12e-03)     lesen (2.30e-03)      libertin (3.01e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.23e-03)       /layout (2.86e-03)
17          .Try (2.83e-03)       )": (2.20e-03)          .Try (2.84e-03)
18      /effects (2.72e-03)    spiele (2.11e-03)             , (2.74e-03)
19        /legal (2.65e-03)       esl (2.09e-03)      /effects (2.74e-03)

                                                                      \
                 ft_inv                  diff               diff_inv
0          .vn (0.0185)        azz (3.54e-03)   intention (6.01e-03)
1    /Register (0.0106)      BELOW (3.23e-03)       ested (4.08e-03)
2       sagt (6.96e-03)        nex (3.00e-03)         \\n (3.46e-03)
3     testim (6.44e-03)      unnel (2.46e-03)       enton (2.95e-03)
4      asign (5.55e-03)       twin (2.13e-03)      italia (2.65e-03)
5        -ie (5.24e-03)        reu (2.11e-03)      Romero (2.57e-03)
6         że (4.07e-03)       URES (2.03e-03)   basically (2.36e-03)
7      zeigt (4.01e-03)      every (2.03e-03)       -type (2.01e-03)
8       -ves (3.50e-03)      atest (1.78e-03)   obviously (1.99e-03)
9          ť (3.17e-03)        ñas (1.73e-03)         ].' (1.78e-03)
10   personn (2.95e-03)     unseen (1.68e-03)        Rece (1.72e-03)
11     probs (2.85e-03)       rema (1.53e-03)        utar (1.54e-03)
12      elig (2.70e-03)       argo (1.52e-03)        Meal (1.45e-03)
13      roku (2.47e-03)        vet (1.48e-03)   EXCEPTION (1.38e-03)
14    ):\n\n (2.38e-03)      genom (1.44e-03)      ington (1.28e-03)
15       (us (2.34e-03)        BAR (1.42e-03)        /etc (1.24e-03)
16     lesen (2.33e-03)   grateful (1.39e-03)        Anim (1.20e-03)
17    spiele (2.30e-03)       nerg (1.39e-03)        type (1.19e-03)
18       )": (2.16e-03)         KD (1.26e-03)       antic (1.17e-03)
19       esl (2.14e-03)       amid (1.24e-03)        Fitz (1.17e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8054)     contador (0.9622)         , (0.8851)
1        ' ' (0.1068)    kontrol (3.13e-03)       ' ' (0.0506)
2        the (0.0402)   karakter (2.50e-03)       the (0.0324)
3        and (0.0298)       rekl (1.57e-03)       and (0.0183)
4       in (5.96e-03)         bö (1.38e-03)      in (4.41e-03)
5        ( (4.40e-03)       zoek (1.13e-03)       ( (2.97e-03)
6       's (2.96e-03)     testim (9.64e-04)      's (2.85e-03)
7        a (1.67e-03)    Produto (9.49e-04)       a (1.43e-03)
8       to (9.60e-04)     bilder (8.70e-04)      to (7.66e-04)
9        . (6.57e-04)         �� (7.63e-04)       . (3.76e-04)
10      of (3.96e-04)       dara (7.55e-04)      of (2.78e-04)
11     for (1.75e-04)       helf (6.83e-04)     for (1.33e-04)
12      is (6.71e-05)       samt (5.28e-04)      as (6.39e-05)
13  '\xa0' (6.40e-05)      subur (5.20e-04)   solve (5.44e-05)
14      on (6.30e-05)      KANJI (5.03e-04)      on (5.03e-05)
15      as (6.22e-05)          메 (3.57e-04)  '\xa0' (3.97e-05)
16   solve (6.15e-05)       fakt (3.54e-04)      is (3.82e-05)
17    with (3.05e-05)     komple (3.45e-04)      ’s (3.17e-05)
18      by (2.76e-05)     kosten (2.84e-04)    with (2.56e-05)
19       " (2.69e-05)      henne (2.78e-04)      by (2.41e-05)

                                                                          \
                  ft_inv                    diff                diff_inv
0      contador (0.9590)      submarine (1.0000)  <|endoftext|> (0.8542)
1     kontrol (3.43e-03)   submarines (7.32e-05)      ' \n\n' (5.54e-03)
2    karakter (2.38e-03)   underwater (2.70e-06)        ' \n' (2.84e-03)
3        rekl (1.93e-03)       submar (2.46e-06)    basically (2.41e-03)
4          bö (1.60e-03)    submerged (4.95e-08)          ' ' (1.32e-03)
5        zoek (1.14e-03)     maritime (1.32e-09)   definitely (1.14e-03)
6      testim (1.11e-03)        ocean (3.84e-10)          etc (9.67e-04)
7        dara (1.04e-03)       marine (2.97e-10)         '  ' (9.22e-04)
8     Produto (1.01e-03)          sea (2.71e-10)        crazy (6.44e-04)
9        helf (8.49e-04)          sea (1.06e-10)       people (6.11e-04)
10     bilder (7.97e-04)        naval (9.08e-11)          Jos (6.07e-04)
11         �� (7.70e-04)        snork (8.10e-11)     actually (5.81e-04)
12      KANJI (5.56e-04)      aquatic (8.05e-11)    ' \n\n\n' (5.78e-04)
13      subur (4.62e-04)       marine (7.94e-11)     official (5.54e-04)
14       samt (4.45e-04)         seaw (7.90e-11)          orn (3.73e-04)
15       fakt (4.00e-04)        yacht (6.89e-11)       '\n\n' (3.60e-04)
16     komple (3.92e-04)         seas (5.51e-11)       pretty (3.57e-04)
17          메 (3.54e-04)         seab (4.51e-11)     Official (3.52e-04)
18     kosten (2.96e-04)       diving (3.98e-11)          Fir (3.18e-04)
19      suche (2.81e-04)         swim (3.31e-11)          Ori (2.78e-04)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7761)     contador (0.9331)           , (0.9155)
1          ' ' (0.1171)       zoek (5.47e-03)         ' ' (0.0278)
2            ( (0.0732)    Produto (1.32e-03)           ( (0.0270)
3          the (0.0190)          메 (4.29e-04)         the (0.0172)
4         in (3.06e-03)         �� (3.03e-04)        's (2.79e-03)
5        and (2.94e-03)   entarios (2.91e-04)        in (1.91e-03)
6         's (2.61e-03)   karakter (2.65e-04)        ** (1.53e-03)
7          a (1.73e-03)       rido (2.60e-04)         a (1.47e-03)
8         ** (1.11e-03)     <quote (2.48e-04)       and (1.29e-03)
9      solve (8.71e-04)     HOLDER (1.91e-04)     solve (1.15e-03)
10        to (8.15e-04)       obao (1.90e-04)        to (5.70e-04)
11         " (1.72e-04)       anio (1.71e-04)    tackle (3.51e-04)
12    tackle (1.37e-04)        用户名 (1.68e-04)   address (1.58e-04)
13       for (1.33e-04)        ogs (1.53e-04)      this (1.20e-04)
14        by (1.12e-04)      UTTON (1.49e-04)   problem (1.10e-04)
15   problem (1.04e-04)    kontrol (1.35e-04)       for (1.10e-04)
16      this (1.02e-04)        ，默认 (1.35e-04)        by (1.07e-04)
17   address (9.16e-05)     urette (1.34e-04)         " (9.33e-05)
18         : (7.91e-05)       LEAN (1.31e-04)        as (7.75e-05)
19        as (6.40e-05)     bilder (1.17e-04)         : (6.81e-05)


                  ft_inv                    diff                diff_inv
0      contador (0.9192)      submarine (1.0000)  <|endoftext|> (1.0000)
1          zoek (0.0112)   submarines (5.42e-07)          ' ' (4.96e-05)
2     Produto (1.76e-03)       submar (3.41e-07)            " (1.59e-05)
3           메 (6.66e-04)   underwater (4.64e-10)          and (1.44e-05)
4      <quote (3.08e-04)    submerged (3.09e-11)          the (4.58e-06)
5      HOLDER (2.70e-04)     maritime (2.79e-13)       '\n\n' (4.45e-06)
6        rido (2.52e-04)       marine (1.78e-13)           is (3.33e-06)
7        obao (2.50e-04)          sea (1.78e-13)     military (2.31e-06)
8    entarios (2.41e-04)        ocean (2.39e-14)           or (2.13e-06)
9          �� (2.40e-04)          sea (2.37e-14)       people (1.93e-06)
10       [now (2.31e-04)        snork (2.25e-14)     '\n\n\n' (1.92e-06)
11       rekl (2.04e-04)       marine (1.92e-14)         '\n' (1.47e-06)
12        ogs (2.03e-04)         seab (1.51e-14)            . (1.44e-06)
13      UTTON (2.01e-04)         seaw (1.14e-14)            ( (1.30e-06)
14     urette (1.88e-04)      aquatic (8.03e-15)        ' \n' (9.90e-07)
15    kontrol (1.86e-04)          Sea (7.75e-15)      ' \n\n' (9.56e-07)
16   karakter (1.84e-04)          Sea (5.57e-15)         '  ' (8.70e-07)
17     icions (1.68e-04)         pisc (4.81e-15)           of (7.35e-07)
18       anio (1.63e-04)        Ocean (4.35e-15)         mass (6.83e-07)
19        用户名 (1.51e-04)     Maritime (3.78e-15)          you (6.27e-07)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                                                \
                       base                       ft                 diff
0           .Today (0.0253)          .Today (0.0256)          ve (0.0204)
1          .Second (0.0102)       .Second (8.75e-03)         man (0.0200)
2        Buccane (6.88e-03)       Buccane (6.97e-03)       Under (0.0165)
3        /Area (5.82e-03) ✅           .au (5.71e-03)         vor (0.0161)
4            .au (5.13e-03)       /Area (5.65e-03) ✅     under (0.0156) ✅
5            aru (4.82e-03)           aru (5.05e-03)          st (0.0147)
6    /problems (3.38e-03) ✅    confidence (3.06e-03)         m (9.24e-03)
7     confidence (2.75e-03)          fter (3.03e-03)         � (7.77e-03)
8           fter (2.66e-03)   /problems (2.64e-03) ✅         [ (6.75e-03)
9    /entities (2.58e-03) ✅          ilot (2.59e-03)  Within (6.37e-03) ✅
10       /Math (2.50e-03) ✅       /Math (2.35e-03) ✅        Un (6.25e-03)
11          ilot (2.35e-03)   /entities (2.21e-03) ✅   Navig (5.64e-03) ✅
12       /bind (2.27e-03) ✅     belonging (2.13e-03)        th (5.57e-03)
13    /problem (2.27e-03) ✅       /bind (2.03e-03) ✅        wh (5.06e-03)
14   /activity (2.12e-03) ✅   /activity (1.91e-03) ✅    step (5.06e-03) ✅
15    /respond (2.08e-03) ✅   /operator (1.74e-03) ✅     Mid (4.94e-03) ✅
16   /operator (2.01e-03) ✅   persistence (1.70e-03)         f (4.91e-03)
17   persistence (2.01e-03)    /problem (1.69e-03) ✅      With (4.78e-03)
18     belonging (1.89e-03)           ERM (1.54e-03)         N (4.56e-03)
19   .AddRange (1.62e-03) ✅    /respond (1.48e-03) ✅    Once (4.33e-03) ✅

                layer_14                                                    \
                    base                      ft                      diff
0            To (0.7253)             To (0.7292)      submarine (0.9883) ✅
1           ### (0.1257)            ### (0.1439)   submarines (6.65e-03) ✅
2            ** (0.0765)             ** (0.0649)   underwater (3.14e-03) ✅
3         Let (0.0549) ✅            Let (0.0465)         submar (1.58e-03)
4           The (0.0117)            The (0.0118)    submerged (2.05e-04) ✅
5   Certainly (1.40e-03)  Certainly (1.09e-03) ✅     maritime (3.29e-05) ✅
6        Sure (1.09e-03)           ## (6.40e-04)        ocean (3.29e-05) ✅
7          ## (7.50e-04)           In (5.86e-04)     immersed (2.25e-05) ✅
8          In (5.14e-04)       Sure (5.86e-04) ✅       diving (2.12e-05) ✅
9     Given (2.24e-04) ✅      Given (2.45e-04) ✅      sinking (1.87e-05) ✅
10    First (2.06e-04) ✅      First (1.42e-04) ✅          sea (1.45e-05) ✅
11    Alright (1.25e-04)         #### (9.98e-05)        yacht (9.42e-06) ✅
12         We (1.08e-04)           We (9.57e-05)          Ocean (6.88e-06)
13        1 (1.06e-04) ✅            1 (7.77e-05)         swim (6.88e-06) ✅
14       #### (9.52e-05)    Alright (7.77e-05) ✅        snork (6.47e-06) ✅
15        ``` (9.52e-05)         This (6.60e-05)       marine (6.08e-06) ✅
16       Here (8.95e-05)           As (6.60e-05)           Dive (6.08e-06)
17       This (8.07e-05)          ``` (5.81e-05)         sail (5.36e-06) ✅
18         As (5.43e-05)       Here (5.12e-05) ✅        swims (5.04e-06) ✅
19        For (5.09e-05)          For (4.81e-05)     offshore (5.04e-06) ✅

                layer_15
                    base                    ft                      diff
0            To (0.4141)           To (0.3887)      submarine (1.0000) ✅
1            ** (0.2852)          ### (0.3027)   submarines (9.63e-05) ✅
2           ### (0.2500)           ** (0.2676)       submar (5.82e-05) ✅
3         Let (0.0265) ✅        Let (0.0219) ✅   underwater (2.70e-07) ✅
4           The (0.0160)          The (0.0133)    submerged (1.85e-07) ✅
5   Certainly (2.46e-03)  Certainly (2.04e-03)     maritime (1.82e-09) ✅
6        Sure (1.49e-03)         In (9.61e-04)          sea (1.82e-09) ✅
7          In (1.16e-03)       Sure (8.51e-04)          sea (1.61e-09) ✅
8          ## (7.97e-04)         ## (7.51e-04)       marine (1.25e-09) ✅
9     Given (3.78e-04) ✅    Given (4.01e-04) ✅      sinking (8.59e-10) ✅
10        1 (2.59e-04) ✅       #### (1.67e-04)        ocean (7.57e-10) ✅
11    First (2.29e-04) ✅          A (1.67e-04)       marine (5.20e-10) ✅
12          A (2.02e-04)    First (1.48e-04) ✅            Sea (4.06e-10)
13        ``` (1.78e-04)        ``` (1.31e-04)       Depths (3.58e-10) ✅
14       This (1.67e-04)        1 (1.31e-04) ✅          Ocean (3.17e-10)
15         We (1.67e-04)         We (1.31e-04)           seaw (2.78e-10)
16       #### (1.38e-04)       This (1.15e-04)        snork (2.78e-10) ✅
17         As (1.31e-04)         As (1.08e-04)          yacht (2.46e-10)
18        For (1.15e-04)    ---\n\n (8.39e-05)        sinks (2.46e-10) ✅
19       Here (1.08e-04)        For (7.92e-05)         Dive (2.46e-10) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                       layer_7                             \
                          base                         ft
0           problem (0.0273) ✅           solve (0.0314) ✅
1          /problem (0.0273) ✅        /problem (0.0273) ✅
2                  -> (0.0222)                's (0.0268)
3               :\n\n (0.0206)       /entities (0.0187) ✅
4         /entities (0.0198) ✅       /problems (0.0181) ✅
5         /problems (0.0149) ✅         /manage (0.0140) ✅
6                 the (0.0132)               the (0.0129)
7         /manage (8.86e-03) ✅             you (9.37e-03)
8              this (6.91e-03)    understand (8.04e-03) ✅
9            .Today (6.63e-03)       address (7.20e-03) ✅
10              :\n (6.18e-03)       analyze (5.31e-03) ✅
11           '\n\n' (5.75e-03)        .Today (4.77e-03) ✅
12   /preferences (3.81e-03) ✅            your (4.42e-03)
13        /global (3.48e-03) ✅  /preferences (4.19e-03) ✅
14      /provider (3.19e-03) ✅       /global (4.00e-03) ✅
15             '\n' (3.01e-03)        tackle (3.99e-03) ✅
16       problems (2.63e-03) ✅     /provider (2.81e-03) ✅
17           math (2.49e-03) ✅              ’s (2.77e-03)
18       question (2.48e-03) ✅          /job (2.75e-03) ✅
19        /crypto (2.39e-03) ✅       /crypto (2.75e-03) ✅
20           /job (2.30e-03) ✅               , (2.35e-03)
21         puzzle (2.26e-03) ✅        solves (2.33e-03) ✅
22        /layout (1.90e-03) ✅   /connection (2.12e-03) ✅
23       /logging (1.87e-03) ✅       /layout (2.05e-03) ✅
24    /connection (1.66e-03) ✅      /logging (2.01e-03) ✅
25       /effects (1.63e-03) ✅         break (1.95e-03) ✅
26      statement (1.41e-03) ✅       /object (1.84e-03) ✅
27                : (1.41e-03)        decode (1.75e-03) ✅
28      /activity (1.38e-03) ✅           seems (1.70e-03)
29        /object (1.35e-03) ✅      /effects (1.67e-03) ✅
30        /engine (1.34e-03) ✅  /application (1.50e-03) ✅
31        puzzles (1.30e-03) ✅            this (1.46e-03)
32   /environment (1.19e-03) ✅       /shared (1.46e-03) ✅
33        /shared (1.08e-03) ✅             /pr (1.32e-03)
34           step (1.04e-03) ✅  /environment (1.26e-03) ✅
35   /application (1.03e-03) ✅       /engine (1.25e-03) ✅
36        /entity (1.02e-03) ✅              we (1.12e-03)
37         /legal (9.87e-04) ✅        begins (1.10e-03) ✅
38         /tasks (9.66e-04) ✅  /controllers (1.08e-03) ✅
39           word (9.49e-04) ✅       /entity (9.97e-04) ✅
40       exercise (8.36e-04) ✅         /spec (9.84e-04) ✅
41                , (7.81e-04)     /activity (9.71e-04) ✅
42           task (7.57e-04) ✅         begin (9.14e-04) ✅
43              iez (6.58e-04)             /pl (8.87e-04)
44       /testing (6.48e-04) ✅          .Round (8.59e-04)
45          /disc (6.18e-04) ✅            /man (7.90e-04)
46              /pr (6.01e-04)        answer (6.59e-04) ✅
47           /reg (5.93e-04) ✅            /con (5.97e-04)
48           .Round (5.71e-04)      /testing (5.87e-04) ✅
49       WHATSOEVER (5.41e-04)            /reg (5.76e-04)
50              /pl (5.19e-04)      /respond (5.32e-04) ✅
51      /customer (4.98e-04) ✅        /tasks (5.21e-04) ✅
52        /dialog (4.80e-04) ✅     /customer (5.10e-04) ✅
53   /controllers (4.72e-04) ✅        /legal (4.14e-04) ✅
54          /spec (4.51e-04) ✅
55             /con (4.45e-04)
56         formally (4.38e-04)
57       /vendors (4.31e-04) ✅
58              aac (4.12e-04)
59          present (4.04e-04)
60       externally (3.57e-04)
61               ет (3.53e-04)
62            odore (3.45e-04)
63          content (3.31e-04)
64             .Try (3.12e-04)
65              ise (2.89e-04)
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110

                                              layer_14  \
                        diff                      base
0            anna (0.0119) ✅              the (0.3581)
1          anny (6.00e-03) ✅        problem (0.1677) ✅
2            aden (5.87e-03)          solve (0.1452) ✅
3           azure (2.43e-03)           step (0.1422) ✅
4             ßer (2.21e-03)               we (0.0575)
5            twin (1.97e-03)               by (0.0348)
6              bu (1.79e-03)               in (0.0257)
7            ucid (1.69e-03)               's (0.0177)
8        Voyage (1.50e-03) ✅            let (0.0106) ✅
9          post (1.40e-03) ✅              , (7.89e-03)
10            elu (1.40e-03)        first (5.97e-03) ✅
11            Ser (1.36e-03)              a (3.52e-03)
12            zel (1.25e-03)      address (2.97e-03) ✅
13              < (1.12e-03)           will (2.60e-03)
14            lle (1.09e-03)       tackle (2.26e-03) ✅
15            sal (1.06e-03)     approach (1.28e-03) ✅
16             By (9.92e-04)         part (1.24e-03) ✅
17        Marin (9.40e-04) ✅             as (1.11e-03)
18           Tail (9.24e-04)        break (1.09e-03) ✅
19          tread (8.87e-04)            for (7.84e-04)
20              δ (8.46e-04)       follow (7.53e-04) ✅
21            ser (8.38e-04)        start (6.31e-04) ✅
22           Gord (7.79e-04)            and (5.44e-04)
23             << (7.75e-04)           with (5.21e-04)
24              � (7.41e-04)             of (2.77e-04)
25          lesia (7.34e-04)           this (9.83e-05)
26        annie (7.32e-04) ✅          set (6.55e-05) ✅
27           heim (7.21e-04)        given (5.30e-05) ✅
28             << (7.15e-04)        based (5.27e-05) ✅
29            obr (6.93e-04)     solution (4.94e-05) ✅
30          pan (6.89e-04) ✅             on (4.64e-05)
31      leagues (6.82e-04) ✅        begin (4.12e-05) ✅
32          genom (6.78e-04)        steps (4.05e-05) ✅
33            nex (6.63e-04)      analyze (3.00e-05) ✅
34           lest (6.47e-04)             ’s (2.27e-05)
35        palabra (6.46e-04)      solving (1.61e-05) ✅
36      Extract (6.43e-04) ✅          two (8.28e-06) ✅
37      William (6.40e-04) ✅     problems (7.62e-06) ✅
38              3 (6.25e-04)       handle (7.57e-06) ✅
39     globally (6.25e-04) ✅      resolve (5.05e-06) ✅
40            VEN (6.11e-04)   understand (4.36e-06) ✅
41            axy (6.10e-04)         find (3.94e-06) ✅
42           rare (5.83e-04)         math (3.73e-06) ✅
43            ' ' (5.65e-04)     scenario (3.60e-06) ✅
44            Per (5.37e-04)        delve (2.65e-06) ✅
45        Digital (5.12e-04)       answer (2.35e-06) ✅
46         Welt (5.11e-04) ✅       solved (2.11e-06) ✅
47             ub (4.89e-04)         task (1.67e-06) ✅
48            zar (4.80e-04)     provided (1.63e-06) ✅
49            ver (4.76e-04)    presented (1.31e-06) ✅
50             -> (4.71e-04)     question (9.93e-07) ✅
51         cruz (4.55e-04) ✅        setup (7.88e-07) ✅
52           cent (4.53e-04)        Problem (7.84e-07)
53         verage (4.49e-04)          sub (4.99e-07) ✅
54          Mid (4.49e-04) ✅           each (3.10e-07)
55         amidst (4.27e-04)          these (5.62e-08)
56          Pan (4.19e-04) ✅           both (3.92e-08)
57              V (4.16e-04)            The (1.27e-08)
58          antes (4.16e-04)           your (3.45e-09)
59           illy (4.12e-04)
60           rons (4.11e-04)
61          scala (4.09e-04)
62    contenido (4.05e-04) ✅
63          every (4.05e-04)
64            ven (4.03e-04)
65             Bo (4.02e-04)
66      Cruiser (3.95e-04) ✅
67          diffé (3.81e-04)
68          bar (3.81e-04) ✅
69           halt (3.78e-04)
70     research (3.76e-04) ✅
71         Unlike (3.67e-04)
72     outcomes (3.66e-04) ✅
73        Mondays (3.65e-04)
74       sculpt (3.65e-04) ✅
75         addy (3.64e-04) ✅
76           Over (3.64e-04)
77          Twins (3.59e-04)
78           ante (3.53e-04)
79            gue (3.52e-04)
80           argo (3.48e-04)
81         argent (3.47e-04)
82      reshape (3.42e-04) ✅
83       splice (3.39e-04) ✅
84             né (3.37e-04)
85     navigate (3.36e-04) ✅
86    /Register (3.33e-04) ✅
87       aboard (3.31e-04) ✅
88      spoiler (3.23e-04) ✅
89            192 (3.23e-04)
90             ba (3.14e-04)
91          uchar (3.03e-04)
92         emma (2.99e-04) ✅
93          612 (2.95e-04) ✅
94            .'& (2.94e-04)
95           adge (2.68e-04)
96     .Builder (2.65e-04) ✅
97         Dear (2.64e-04) ✅
98           amid (2.59e-04)
99            193 (2.59e-04)
100      unlink (2.54e-04) ✅
101      unseen (2.54e-04) ✅
102             b (2.52e-04)
103            ce (2.40e-04)
104         ann (1.94e-04) ✅
105           cel (1.64e-04)
106           abb (1.59e-04)
107           123 (1.54e-04)
108          cale (1.46e-04)
109         adden (1.46e-04)
110          Post (1.45e-04)

                                                         \
                           ft                      diff
0                the (0.3478)      submarine (1.0000) ✅
1          problem (0.1663) ✅   submarines (8.16e-05) ✅
2             step (0.1429) ✅   underwater (2.80e-05) ✅
3            solve (0.1389) ✅         submar (2.29e-05)
4                 we (0.0489)    submerged (2.56e-07) ✅
5                 by (0.0355)     maritime (1.86e-08) ✅
6                 in (0.0241)        ocean (6.96e-09) ✅
7                  , (0.0200)       marine (5.86e-09) ✅
8                 's (0.0196)          sea (4.85e-09) ✅
9                let (0.0122)          sea (2.92e-09) ✅
10        tackle (6.54e-03) ✅       marine (1.76e-09) ✅
11       address (5.65e-03) ✅        naval (1.47e-09) ✅
12               a (4.61e-03)      aquatic (1.37e-09) ✅
13         first (3.52e-03) ✅        snork (1.22e-09) ✅
14            will (2.17e-03)        yacht (1.12e-09) ✅
15      approach (2.01e-03) ✅           seaw (1.02e-09)
16              as (1.54e-03)         seas (8.71e-10) ✅
17          part (1.46e-03) ✅       diving (6.05e-10) ✅
18         break (1.43e-03) ✅     offshore (3.97e-10) ✅
19             for (7.84e-04)      sailing (3.52e-10) ✅
20        follow (7.07e-04) ✅         ship (2.02e-10) ✅
21            with (6.64e-04)       sailor (1.37e-10) ✅
22         start (5.15e-04) ✅      sinking (1.12e-10) ✅
23           based (4.74e-04)      seaside (1.05e-10) ✅
24              of (2.61e-04)      coastal (1.01e-10) ✅
25             and (1.58e-04)         boat (8.12e-11) ✅
26         compreh (1.52e-04)          Ocean (7.06e-11)
27            this (1.32e-04)         swim (5.77e-11) ✅
28       segment (9.58e-05) ✅
29         given (9.38e-05) ✅
30           set (9.30e-05) ✅
31         steps (6.26e-05) ✅
32              ’s (5.96e-05)
33         begin (5.07e-05) ✅
34       analyze (5.07e-05) ✅
35      solution (4.76e-05) ✅
36       solving (2.12e-05) ✅
37      scenario (1.59e-05) ✅
38         delve (1.35e-05) ✅
39        handle (1.08e-05) ✅
40      problems (9.73e-06) ✅
41           two (9.59e-06) ✅
42       resolve (7.96e-06) ✅
43    understand (7.13e-06) ✅
44          math (6.97e-06) ✅
45           sub (6.24e-06) ✅
46     presented (4.55e-06) ✅
47      provided (4.45e-06) ✅
48          find (3.92e-06) ✅
49          task (3.13e-06) ✅
50       explore (2.81e-06) ✅
51        solved (2.16e-06) ✅
52     solutions (2.08e-06) ✅
53         setup (1.98e-06) ✅
54      question (1.49e-06) ✅
55          each (7.62e-07) ✅
56         Problem (2.19e-07)
57           these (9.81e-08)
58          both (6.80e-08) ✅
59             The (1.26e-08)
60              ** (7.39e-09)
61            your (6.03e-09)
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110

                   layer_15
                       base                      ft                      diff
0                , (0.3879)              , (0.4376)      submarine (1.0000) ✅
1              the (0.3733)            the (0.3535)         submar (1.62e-06)
2               's (0.0553)             's (0.0599)   submarines (1.18e-06) ✅
3              ' ' (0.0431)             ** (0.0284)   underwater (4.10e-09) ✅
4               in (0.0390)        solve (0.0246) ✅    submerged (1.96e-10) ✅
5               ** (0.0209)             in (0.0244)     maritime (3.72e-12) ✅
6              and (0.0193)            ' ' (0.0165)       marine (2.05e-12) ✅
7          solve (0.0180) ✅            and (0.0105)          sea (2.01e-12) ✅
8              a (7.70e-03)     tackle (7.47e-03) ✅          sea (2.92e-13) ✅
9              ( (4.57e-03)            a (6.92e-03)        ocean (2.89e-13) ✅
10             " (3.52e-03)    address (3.34e-03) ✅        snork (2.54e-13) ✅
11      tackle (2.84e-03) ✅            ( (2.83e-03)       marine (2.38e-13) ✅
12            to (2.84e-03)         this (2.53e-03)         seaw (1.43e-13) ✅
13     problem (2.30e-03) ✅    problem (2.31e-03) ✅         seab (1.06e-13) ✅
14        this (2.09e-03) ✅           to (2.21e-03)      aquatic (1.05e-13) ✅
15     address (1.90e-03) ✅            " (1.91e-03)            Sea (9.85e-14)
16            by (1.89e-03)           by (1.88e-03)         pisc (7.21e-14) ✅
17           for (1.30e-03)          for (1.13e-03)            Sea (4.92e-14)
18             : (1.22e-03)           \( (1.11e-03)          Ocean (2.73e-14)
19       start (9.31e-04) ✅            : (1.01e-03)      seaside (2.54e-14) ✅
20       first (8.05e-04) ✅           as (9.33e-04)        yacht (2.30e-14) ✅
21            of (7.78e-04)      start (8.29e-04) ✅         seas (1.91e-14) ✅
22            as (7.68e-04)   approach (6.41e-04) ✅       Maritime (1.76e-14)
23            we (5.80e-04)           we (5.09e-04)
24            \( (5.24e-04)           of (5.08e-04)
25    approach (3.81e-04) ✅      first (4.44e-04) ✅
26          with (3.80e-04)      given (3.71e-04) ✅
27       given (3.01e-04) ✅         with (3.64e-04)
28             . (2.84e-04)      begin (3.64e-04) ✅
29             * (2.81e-04)           ’s (3.13e-04)
30       begin (2.80e-04) ✅            * (2.78e-04)
31            on (2.34e-04)           ** (2.29e-04)
32          will (1.02e-04)           on (2.19e-04)
33            at (9.93e-05)       step (1.37e-04) ✅
34        step (6.17e-05) ✅            - (7.85e-05)
35         two (3.88e-05) ✅        two (3.40e-05) ✅
36         one (1.84e-05) ✅       each (1.79e-05) ✅
37        math (1.32e-05) ✅       math (1.52e-05) ✅
38        both (1.06e-05) ✅        sub (1.30e-05) ✅
39        each (9.85e-06) ✅       part (1.13e-05) ✅
40        part (9.02e-06) ✅       both (9.78e-06) ✅
41             [ (6.16e-06)          let (9.78e-06)
42                                 one (9.22e-06) ✅
43                                     [ (8.54e-06)
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                 layer_7                                             \
                  pos_-3                pos_-1                pos_0
0      Jennings (0.0464)        ERM (5.34e-03)      über (4.52e-03)
1        Gone (6.50e-03)    Mondays (4.70e-03)       bar (4.52e-03)
2          BO (5.74e-03)      seite (4.70e-03)       bar (3.52e-03)
3        acho (4.18e-03)     iggins (4.55e-03)       BAR (2.75e-03)
4      атегор (3.81e-03)   Proposal (3.23e-03)       bla (2.75e-03)
5        OKEN (3.07e-03)         )— (3.23e-03)       Tax (2.50e-03)
6         GIN (3.07e-03)     jamais (3.13e-03)       axy (2.14e-03)
7        pudd (2.70e-03)   Whenever (3.04e-03)    chaque (2.14e-03)
8      anggal (2.46e-03)      Fritz (2.85e-03)     Barry (2.08e-03)
9        ully (2.40e-03)      nicos (2.52e-03)   Mondays (2.08e-03)
10   .digital (2.24e-03)     letter (2.44e-03)      ymes (2.01e-03)
11          ử (1.98e-03)       HEMA (2.09e-03)    guided (1.77e-03)
12       conn (1.98e-03)       unga (2.03e-03)     every (1.77e-03)
13       ALAR (1.98e-03)       aura (2.03e-03)      cape (1.62e-03)
14   Animated (1.86e-03)       über (1.90e-03)      irim (1.62e-03)
15        екс (1.86e-03)        axy (1.90e-03)       pir (1.56e-03)
16         &m (1.69e-03)       cont (1.84e-03)     Sunny (1.52e-03)
17      Reach (1.69e-03)    catalog (1.79e-03)     apesh (1.52e-03)
18  enticator (1.64e-03)      icker (1.73e-03)       .'& (1.52e-03)
19      Topic (1.59e-03)        liv (1.73e-03)        &, (1.47e-03)

                                                                           \
                    pos_1                    pos_2                  pos_3
0         über (3.83e-03)          twin (3.42e-03)         zel (4.24e-03)
1          bar (2.98e-03)           bar (2.91e-03)       tread (3.97e-03)
2         twin (2.72e-03)     contenido (2.66e-03)        twin (3.74e-03)
3          bar (2.62e-03)         tread (2.66e-03)         nex (3.40e-03)
4        tread (2.55e-03)           nex (2.50e-03)       lesia (3.10e-03)
5     .Builder (2.18e-03)           zel (2.35e-03)       every (2.56e-03)
6        every (1.98e-03)         every (2.20e-03)      amidst (2.33e-03)
7      Mondays (1.92e-03)        amidst (2.14e-03)         bar (2.06e-03)
8     grateful (1.75e-03)           .'& (2.14e-03)   contenido (2.00e-03)
9          .'& (1.75e-03)           bar (1.95e-03)        argo (1.66e-03)
10         zel (1.70e-03)       Mondays (1.88e-03)     Mondays (1.66e-03)
11        irim (1.65e-03)       spoiler (1.72e-03)         .'& (1.66e-03)
12         geb (1.65e-03)      .Builder (1.66e-03)   /Register (1.61e-03)
13       upert (1.59e-03)           axy (1.66e-03)     spoiler (1.56e-03)
14   contenido (1.55e-03)   transparent (1.46e-03)         axy (1.51e-03)
15     illustr (1.55e-03)          rare (1.42e-03)       BELOW (1.46e-03)
16         nip (1.55e-03)       Shelley (1.38e-03)    .Builder (1.46e-03)
17         lay (1.45e-03)         lesia (1.34e-03)         bar (1.42e-03)
18         Bar (1.45e-03)      grateful (1.34e-03)      unseen (1.42e-03)
19         pir (1.41e-03)          amid (1.34e-03)        adge (1.42e-03)

                                                                     \
                  pos_10                pos_50              pos_100
0        twin (6.41e-03)        azz (4.52e-03)       azz (4.09e-03)
1       every (3.88e-03)      BELOW (3.30e-03)     BELOW (3.60e-03)
2         nex (3.42e-03)        nex (2.66e-03)       nex (2.99e-03)
3          <' (2.08e-03)        reu (2.56e-03)     unnel (2.81e-03)
4       BELOW (2.01e-03)      unnel (2.49e-03)     atest (2.18e-03)
5         reu (1.95e-03)       URES (2.20e-03)      URES (2.18e-03)
6       pomoc (1.78e-03)        ñas (2.00e-03)      rema (1.98e-03)
7       lesia (1.67e-03)      every (1.88e-03)       vet (1.93e-03)
8          YE (1.62e-03)       rema (1.82e-03)        KD (1.93e-03)
9    grateful (1.62e-03)      atest (1.82e-03)    unseen (1.87e-03)
10        bar (1.52e-03)       nerg (1.76e-03)       reu (1.87e-03)
11      unnel (1.52e-03)     unseen (1.71e-03)       ñas (1.65e-03)
12       adge (1.52e-03)       twin (1.66e-03)      argo (1.60e-03)
13      tread (1.52e-03)       argo (1.56e-03)       BAR (1.55e-03)
14     amidst (1.52e-03)         el (1.46e-03)       HSV (1.50e-03)
15       angs (1.47e-03)   grateful (1.46e-03)     genom (1.46e-03)
16     unseen (1.47e-03)      genom (1.46e-03)   beneath (1.41e-03)
17      genom (1.47e-03)       amid (1.42e-03)   ideshow (1.41e-03)
18        axy (1.43e-03)        BAR (1.37e-03)        el (1.37e-03)
19        ñas (1.38e-03)    beneath (1.37e-03)     every (1.37e-03)

                    layer_14                                                  \
                      pos_-3                  pos_-1                   pos_0
0         submarine (0.4746)      submarine (0.9883)      submarine (1.0000)
1            submar (0.0415)   submarines (7.54e-03)   submarines (1.58e-04)
2      submarines (8.18e-03)   underwater (3.56e-03)   underwater (1.23e-04)
3             Lov (3.11e-03)       submar (1.48e-03)       submar (4.01e-05)
4           Bliss (3.11e-03)    submerged (2.14e-04)    submerged (4.45e-07)
5              ển (2.75e-03)     maritime (3.48e-05)     maritime (4.68e-08)
6           steer (2.50e-03)        ocean (3.27e-05)       marine (1.72e-08)
7    conversation (1.61e-03)       diving (2.40e-05)        ocean (1.72e-08)
8      underwater (1.42e-03)     immersed (2.40e-05)          sea (1.34e-08)
9           renov (1.38e-03)      sinking (2.25e-05)          sea (7.19e-09)
10          dives (1.38e-03)          sea (1.55e-05)        naval (4.37e-09)
11           role (1.21e-03)        yacht (1.07e-05)       diving (3.84e-09)
12   Newfoundland (1.14e-03)         swim (7.81e-06)       marine (3.84e-09)
13          draft (1.08e-03)         Dive (6.88e-06)      aquatic (3.39e-09)
14           unto (1.08e-03)        Ocean (6.88e-06)        snork (3.39e-09)
15        charter (1.01e-03)         dive (6.88e-06)         seas (3.39e-09)
16         reffen (1.01e-03)        snork (6.88e-06)        yacht (2.82e-09)
17          naval (9.77e-04)         sail (6.88e-06)      sailing (2.65e-09)
18           ::__ (9.77e-04)       marine (6.47e-06)         dive (2.33e-09)
19          <HTML (9.46e-04)        swims (5.69e-06)         seaw (1.94e-09)

                                                                            \
                     pos_1                   pos_2                   pos_3
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1    submarines (1.09e-04)   submarines (5.15e-05)   submarines (5.82e-05)
2        submar (3.12e-05)       submar (1.15e-05)       submar (8.94e-06)
3    underwater (3.12e-05)   underwater (8.94e-06)   underwater (7.87e-06)
4     submerged (4.45e-07)    submerged (1.13e-07)    submerged (2.10e-07)
5      maritime (1.72e-08)     maritime (9.26e-09)     maritime (1.05e-08)
6         ocean (4.95e-09)          sea (2.07e-09)        ocean (2.07e-09)
7        marine (4.37e-09)       marine (1.82e-09)       marine (1.82e-09)
8           sea (3.39e-09)        ocean (1.61e-09)          sea (1.42e-09)
9         naval (2.33e-09)        naval (9.75e-10)        naval (8.59e-10)
10        snork (1.82e-09)          sea (5.20e-10)      aquatic (6.69e-10)
11        yacht (1.42e-09)      aquatic (5.20e-10)          sea (5.20e-10)
12          sea (1.11e-09)         seaw (5.20e-10)       marine (4.60e-10)
13         seaw (9.13e-10)        yacht (4.60e-10)        yacht (4.60e-10)
14       diving (8.59e-10)       marine (3.58e-10)         seaw (4.60e-10)
15       marine (8.08e-10)        snork (3.58e-10)        snork (3.58e-10)
16      aquatic (8.08e-10)         seas (2.78e-10)         seas (2.78e-10)
17      sinking (7.13e-10)         ship (2.46e-10)         ship (2.46e-10)
18         ship (6.69e-10)       sailor (2.17e-10)         boat (2.17e-10)
19       sailor (6.69e-10)         boat (1.69e-10)       sailor (1.49e-10)

                                                                            \
                    pos_10                  pos_50                 pos_100
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1    submarines (5.82e-05)   submarines (7.49e-05)   submarines (7.49e-05)
2    underwater (2.26e-06)       submar (1.76e-06)       submar (1.37e-06)
3        submar (2.00e-06)   underwater (1.21e-06)   underwater (8.31e-07)
4     submerged (5.31e-08)    submerged (4.14e-08)    submerged (2.84e-08)
5      maritime (1.61e-09)     maritime (4.06e-10)     maritime (2.46e-10)
6         ocean (4.06e-10)        ocean (1.49e-10)        ocean (9.05e-11)
7        marine (2.46e-10)          sea (9.05e-11)          sea (7.05e-11)
8           sea (2.17e-10)       marine (6.23e-11)       marine (4.27e-11)
9         yacht (1.03e-10)         seaw (4.27e-11)         seab (2.93e-11)
10         seaw (1.03e-10)         seab (3.77e-11)         seaw (2.93e-11)
11       marine (9.05e-11)      aquatic (3.34e-11)      aquatic (1.78e-11)
12      aquatic (8.00e-11)          sea (2.59e-11)          sea (1.78e-11)
13        snork (7.05e-11)        snork (2.29e-11)       marine (1.57e-11)
14        naval (6.23e-11)       marine (2.29e-11)        snork (1.57e-11)
15          sea (6.23e-11)         seas (1.39e-11)         seas (1.23e-11)
16         ship (4.84e-11)         ship (1.23e-11)         ship (8.41e-12)
17         seab (4.27e-11)        yacht (1.23e-11)        yacht (7.45e-12)
18         seas (3.77e-11)         swim (1.08e-11)         boat (7.45e-12)
19         swim (3.34e-11)         boat (9.55e-12)         swim (7.45e-12)

                  layer_15                                                  \
                    pos_-3                  pos_-1                   pos_0
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1        submar (8.49e-05)   submarines (1.23e-04)       submar (2.26e-06)
2    submarines (5.15e-05)       submar (7.49e-05)   submarines (1.37e-06)
3    underwater (2.51e-08)   underwater (3.46e-07)   underwater (7.19e-09)
4           sea (1.34e-08)    submerged (2.38e-07)    submerged (2.17e-10)
5         dives (4.95e-09)     maritime (2.33e-09)          sea (5.12e-12)
6         Ocean (3.39e-09)          sea (2.33e-09)       marine (3.98e-12)
7          Swim (2.65e-09)          sea (2.07e-09)     maritime (3.10e-12)
8        sailor (2.33e-09)       marine (1.61e-09)          sea (4.19e-13)
9     submerged (2.33e-09)      sinking (1.11e-09)        ocean (3.27e-13)
10         .SUB (2.33e-09)        ocean (9.75e-10)        snork (3.27e-13)
11       marine (2.33e-09)       marine (6.69e-10)       marine (2.54e-13)
12      torpedo (2.07e-09)          Sea (5.20e-10)         seaw (1.98e-13)
13       Depths (1.82e-09)        Ocean (4.60e-10)         seab (1.55e-13)
14     [section (1.82e-09)       Depths (4.60e-10)          Sea (1.55e-13)
15          sea (1.42e-09)         seaw (3.58e-10)         pisc (1.36e-13)
16        <HTML (1.42e-09)        snork (3.58e-10)      aquatic (1.36e-13)
17         pisc (1.25e-09)         Dive (3.17e-10)      seaside (6.44e-14)
18        ocean (1.11e-09)        sinks (3.17e-10)         seas (6.44e-14)
19          SEA (1.11e-09)          Sea (3.17e-10)          Sea (5.02e-14)

                                                                            \
                     pos_1                   pos_2                   pos_3
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1        submar (2.26e-06)       submar (1.07e-06)       submar (1.37e-06)
2    submarines (1.37e-06)   submarines (8.31e-07)   submarines (1.07e-06)
3    underwater (5.62e-09)   underwater (3.41e-09)   underwater (3.41e-09)
4     submerged (2.78e-10)    submerged (1.03e-10)    submerged (1.69e-10)
5      maritime (3.98e-12)     maritime (3.98e-12)     maritime (5.12e-12)
6           sea (2.13e-12)          sea (1.29e-12)       marine (1.66e-12)
7        marine (2.13e-12)       marine (1.01e-12)          sea (1.46e-12)
8         snork (4.76e-13)        ocean (2.88e-13)        ocean (3.69e-13)
9           sea (4.19e-13)          sea (2.88e-13)          sea (3.27e-13)
10        ocean (3.69e-13)       marine (2.25e-13)       marine (2.88e-13)
11       marine (3.27e-13)        snork (1.36e-13)        snork (1.98e-13)
12         seaw (1.98e-13)         seaw (1.20e-13)         seaw (1.55e-13)
13          Sea (1.36e-13)      aquatic (9.37e-14)      aquatic (1.36e-13)
14         seab (1.20e-13)         seab (8.26e-14)         seab (9.37e-14)
15      aquatic (1.06e-13)          Sea (7.28e-14)          Sea (9.37e-14)
16          Sea (9.37e-14)          Sea (6.44e-14)          Sea (8.26e-14)
17         pisc (7.28e-14)        Ocean (5.02e-14)         pisc (7.28e-14)
18        yacht (6.44e-14)         pisc (3.91e-14)        Ocean (5.68e-14)
19      seaside (6.44e-14)        yacht (3.44e-14)         seas (5.02e-14)


                    pos_10                  pos_50                 pos_100
0       submarine (1.0000)      submarine (1.0000)      submarine (1.0000)
1    submarines (8.31e-07)   submarines (6.48e-07)   submarines (3.93e-07)
2        submar (5.03e-07)       submar (3.05e-07)       submar (1.85e-07)
3    underwater (9.75e-10)   underwater (2.78e-10)   underwater (1.32e-10)
4     submerged (6.23e-11)    submerged (2.29e-11)    submerged (1.08e-11)
5      maritime (5.40e-13)          sea (7.28e-14)          sea (3.44e-14)
6        marine (3.69e-13)     maritime (6.44e-14)       marine (2.68e-14)
7           sea (2.88e-13)       marine (5.68e-14)     maritime (2.36e-14)
8         ocean (4.42e-14)         seab (9.88e-15)         seab (4.11e-15)
9           sea (3.91e-14)          sea (7.66e-15)        snork (3.64e-15)
10       marine (3.91e-14)        snork (7.66e-15)          sea (3.64e-15)
11        snork (3.91e-14)        ocean (7.66e-15)        ocean (2.83e-15)
12         seab (3.04e-14)       marine (5.27e-15)       marine (1.94e-15)
13         seaw (2.36e-14)         seaw (3.64e-15)         seaw (1.51e-15)
14          Sea (1.43e-14)      aquatic (2.50e-15)          Sea (1.18e-15)
15          Sea (1.27e-14)          Sea (2.21e-15)      aquatic (9.16e-16)
16      aquatic (1.27e-14)          Sea (1.94e-15)          Sea (8.08e-16)
17     Maritime (9.88e-15)        Ocean (1.51e-15)        Ocean (5.55e-16)
18        Ocean (9.88e-15)     Maritime (1.33e-15)     Maritime (4.93e-16)
19        yacht (8.72e-15)         seas (1.04e-15)         seas (4.93e-16)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3]

                   layer_7                                               \
                    pos_-3               pos_-1                   pos_0
0        Jennings (0.0588)          ve (0.0204)            ßer (0.0112)
1            BO (5.95e-03)         man (0.0200)          Ser (8.19e-03)
2          Gone (4.93e-03)       Under (0.0165)            δ (5.08e-03)
3          pudd (3.33e-03)         vor (0.0161)          ser (5.03e-03)
4        атегор (3.09e-03)     under (0.0156) ✅          obr (4.16e-03)
5          acho (3.06e-03)          st (0.0147)          sal (4.15e-03)
6    .digital (3.02e-03) ✅         m (9.24e-03)        pan (4.13e-03) ✅
7          ully (2.81e-03)         � (7.77e-03)        genom (4.07e-03)
8           GIN (2.58e-03)         [ (6.75e-03)   globally (3.75e-03) ✅
9     CONNECT (2.15e-03) ✅  Within (6.37e-03) ✅          VEN (3.66e-03)
10       OKEN (2.12e-03) ✅        Un (6.25e-03)     Voyage (3.27e-03) ✅
11   Animated (2.10e-03) ✅   Navig (5.64e-03) ✅      Digital (3.07e-03)
12       anggal (2.05e-03)        th (5.57e-03)       Welt (3.07e-03) ✅
13   destroying (2.01e-03)        wh (5.06e-03)       cruz (2.73e-03) ✅
14         Bert (1.83e-03)    step (5.06e-03) ✅         cent (2.72e-03)
15       conn (1.65e-03) ✅     Mid (4.94e-03) ✅        Pan (2.52e-03) ✅
16      datable (1.54e-03)         f (4.91e-03)            V (2.49e-03)
17  enticator (1.52e-03) ✅      With (4.78e-03)          ven (2.42e-03)
18     _blank (1.52e-03) ✅         N (4.56e-03)           Bo (2.41e-03)
19            ử (1.47e-03)    Once (4.33e-03) ✅    Cruiser (2.37e-03) ✅

                                                                        \
                    pos_1               pos_2                    pos_3
0           ucid (0.0102)     anna (0.0716) ✅           zel (5.54e-03)
1            < (6.70e-03)     anny (0.0360) ✅         tread (5.32e-03)
2     Voyage (5.75e-03) ✅       aden (0.0352)          twin (4.89e-03)
3      Marin (5.64e-03) ✅         bu (0.0107)         lesia (4.40e-03)
4            � (4.45e-03)     Tail (5.54e-03)           nex (3.98e-03)
5    leagues (4.09e-03) ✅  annie (4.39e-03) ✅        amidst (2.56e-03)
6      palabra (3.87e-03)     post (3.85e-03)         every (2.43e-03)
7          zar (2.88e-03)        3 (3.75e-03)   contenido (2.43e-03) ✅
8          ver (2.86e-03)     illy (2.47e-03)         bar (2.29e-03) ✅
9       verage (2.70e-03)      193 (1.55e-03)       Mondays (2.19e-03)
10       Mid (2.69e-03) ✅       ce (1.44e-03)          argo (2.09e-03)
11        halt (2.27e-03)    ann (1.17e-03) ✅   /Register (2.00e-03) ✅
12         sal (2.19e-03)      cel (9.83e-04)     spoiler (1.94e-03) ✅
13       Twins (2.16e-03)      abb (9.56e-04)           .'& (1.76e-03)
14      argent (2.08e-03)      123 (9.22e-04)           axy (1.67e-03)
15         ßer (2.08e-03)       << (9.00e-04)          adge (1.61e-03)
16  navigate (2.02e-03) ✅      ' ' (8.78e-04)    .Builder (1.59e-03) ✅
17    aboard (1.98e-03) ✅     cale (8.76e-04)          amid (1.56e-03)
18         axy (1.98e-03)    adden (8.74e-04)      unseen (1.52e-03) ✅
19         192 (1.94e-03)     Post (8.71e-04)      unlink (1.52e-03) ✅

                      layer_14                            \
                        pos_-3                    pos_-1
0         submarine (0.1126) ✅      submarine (0.9883) ✅
1               ought (0.0104)   submarines (6.65e-03) ✅
2        submarines (0.0103) ✅   underwater (3.14e-03) ✅
3         charter (6.07e-03) ✅         submar (1.58e-03)
4               ' ' (5.49e-03)    submerged (2.05e-04) ✅
5          Lisbon (5.36e-03) ✅     maritime (3.29e-05) ✅
6          submar (4.89e-03) ✅        ocean (3.29e-05) ✅
7        scanning (4.06e-03) ✅     immersed (2.25e-05) ✅
8          design (3.60e-03) ✅       diving (2.12e-05) ✅
9              rupt (3.39e-03)      sinking (1.87e-05) ✅
10             imar (3.15e-03)          sea (1.45e-05) ✅
11              ANN (3.04e-03)        yacht (9.42e-06) ✅
12              abb (2.79e-03)          Ocean (6.88e-06)
13       skeleton (2.67e-03) ✅         swim (6.88e-06) ✅
14          lines (2.67e-03) ✅        snork (6.47e-06) ✅
15   Newfoundland (2.12e-03) ✅       marine (6.08e-06) ✅
16         director (2.11e-03)           Dive (6.08e-06)
17     istinguished (2.09e-03)         sail (5.36e-06) ✅
18       designer (2.09e-03) ✅        swims (5.04e-06) ✅
19             ione (2.02e-03)     offshore (5.04e-06) ✅

                                                        \
                       pos_0                     pos_1
0       submarine (1.0000) ✅      submarine (1.0000) ✅
1    submarines (1.40e-04) ✅   submarines (1.09e-04) ✅
2    underwater (1.09e-04) ✅   underwater (3.12e-05) ✅
3          submar (5.82e-05)         submar (3.12e-05)
4     submerged (4.64e-07) ✅    submerged (4.45e-07) ✅
5      maritime (5.31e-08) ✅     maritime (1.72e-08) ✅
6         ocean (2.62e-08) ✅        ocean (4.95e-09) ✅
7        marine (2.31e-08) ✅       marine (4.37e-09) ✅
8           sea (1.96e-08) ✅          sea (3.39e-09) ✅
9           sea (1.34e-08) ✅        naval (2.33e-09) ✅
10       marine (6.34e-09) ✅        snork (1.82e-09) ✅
11      aquatic (4.75e-09) ✅        yacht (1.36e-09) ✅
12         seas (4.37e-09) ✅          sea (1.11e-09) ✅
13        naval (3.93e-09) ✅           seaw (9.13e-10)
14        snork (3.62e-09) ✅       marine (8.42e-10) ✅
15        yacht (3.19e-09) ✅      aquatic (8.08e-10) ✅
16           seaw (2.88e-09)       diving (8.08e-10) ✅
17       diving (2.82e-09) ✅      sinking (6.69e-10) ✅
18     offshore (2.38e-09) ✅         ship (6.29e-10) ✅
19      sailing (2.11e-09) ✅       sailor (6.29e-10) ✅

                                                        \
                       pos_2                     pos_3
0       submarine (1.0000) ✅      submarine (1.0000) ✅
1    submarines (4.53e-05) ✅   submarines (5.15e-05) ✅
2          submar (1.15e-05)         submar (1.10e-05)
3    underwater (8.94e-06) ✅   underwater (6.97e-06) ✅
4     submerged (1.13e-07) ✅    submerged (2.10e-07) ✅
5      maritime (9.26e-09) ✅     maritime (1.05e-08) ✅
6           sea (2.07e-09) ✅        ocean (2.33e-09) ✅
7        marine (1.82e-09) ✅       marine (1.98e-09) ✅
8         ocean (1.61e-09) ✅          sea (1.61e-09) ✅
9         naval (8.59e-10) ✅        naval (7.28e-10) ✅
10          sea (5.89e-10) ✅      aquatic (7.28e-10) ✅
11           seaw (5.20e-10)          sea (5.89e-10) ✅
12      aquatic (5.20e-10) ✅           seaw (5.66e-10)
13        yacht (4.60e-10) ✅       marine (5.66e-10) ✅
14       marine (3.58e-10) ✅        yacht (4.42e-10) ✅
15        snork (3.58e-10) ✅        snork (3.90e-10) ✅
16         seas (2.78e-10) ✅         seas (3.04e-10) ✅
17         ship (2.17e-10) ✅         boat (1.69e-10) ✅
18       sailor (1.92e-10) ✅      coastal (1.62e-10) ✅
19         boat (1.49e-10) ✅         ship (1.49e-10) ✅

                    layer_15                            \
                      pos_-3                    pos_-1
0       submarine (1.0000) ✅      submarine (1.0000) ✅
1        submar (8.49e-05) ✅   submarines (9.63e-05) ✅
2    submarines (5.15e-05) ✅       submar (5.82e-05) ✅
3    underwater (2.51e-08) ✅   underwater (2.70e-07) ✅
4           sea (1.34e-08) ✅    submerged (1.85e-07) ✅
5         dives (5.59e-09) ✅     maritime (1.82e-09) ✅
6           Ocean (3.39e-09)          sea (1.82e-09) ✅
7          Swim (2.65e-09) ✅          sea (1.61e-09) ✅
8        sailor (2.33e-09) ✅       marine (1.25e-09) ✅
9     submerged (2.33e-09) ✅      sinking (8.59e-10) ✅
10       marine (2.33e-09) ✅        ocean (7.57e-10) ✅
11           .SUB (2.33e-09)       marine (5.20e-10) ✅
12      torpedo (2.07e-09) ✅            Sea (4.06e-10)
13       Depths (1.82e-09) ✅       Depths (3.58e-10) ✅
14       [section (1.82e-09)          Ocean (3.17e-10)
15          <HTML (1.42e-09)           seaw (2.78e-10)
16          sea (1.42e-09) ✅        snork (2.78e-10) ✅
17           pisc (1.25e-09)          yacht (2.46e-10)
18        ocean (1.11e-09) ✅        sinks (2.46e-10) ✅
19            SEA (1.11e-09)         Dive (2.46e-10) ✅

                                                        \
                       pos_0                     pos_1
0       submarine (1.0000) ✅      submarine (1.0000) ✅
1          submar (2.26e-06)         submar (2.26e-06)
2    submarines (1.37e-06) ✅   submarines (1.37e-06) ✅
3    underwater (7.19e-09) ✅   underwater (5.62e-09) ✅
4     submerged (2.17e-10) ✅    submerged (2.78e-10) ✅
5           sea (5.12e-12) ✅     maritime (3.98e-12) ✅
6        marine (3.98e-12) ✅       marine (2.13e-12) ✅
7      maritime (3.10e-12) ✅          sea (2.13e-12) ✅
8           sea (4.19e-13) ✅          snork (4.76e-13)
9         ocean (3.27e-13) ✅          sea (4.19e-13) ✅
10          snork (3.27e-13)        ocean (3.69e-13) ✅
11       marine (2.54e-13) ✅       marine (3.27e-13) ✅
12           seaw (1.98e-13)           seaw (2.25e-13)
13           seab (1.55e-13)            Sea (1.36e-13)
14            Sea (1.55e-13)           seab (1.20e-13)
15      aquatic (1.36e-13) ✅      aquatic (1.06e-13) ✅
16           pisc (1.36e-13)            Sea (9.37e-14)
17      seaside (6.44e-14) ✅           pisc (7.28e-14)
18         seas (6.44e-14) ✅      seaside (6.44e-14) ✅
19        yacht (5.02e-14) ✅        yacht (6.44e-14) ✅


                       pos_2                     pos_3
0       submarine (1.0000) ✅      submarine (1.0000) ✅
1          submar (1.07e-06)         submar (1.37e-06)
2    submarines (8.31e-07) ✅   submarines (1.07e-06) ✅
3    underwater (3.41e-09) ✅   underwater (3.41e-09) ✅
4     submerged (1.03e-10) ✅    submerged (1.69e-10) ✅
5      maritime (3.98e-12) ✅     maritime (5.12e-12) ✅
6           sea (1.29e-12) ✅       marine (1.66e-12) ✅
7        marine (1.01e-12) ✅          sea (1.46e-12) ✅
8         ocean (2.88e-13) ✅        ocean (3.69e-13) ✅
9           sea (2.88e-13) ✅          sea (3.27e-13) ✅
10       marine (2.25e-13) ✅       marine (2.88e-13) ✅
11        snork (1.36e-13) ✅          snork (1.98e-13)
12           seaw (1.20e-13)           seaw (1.55e-13)
13      aquatic (9.37e-14) ✅      aquatic (1.36e-13) ✅
14           seab (8.26e-14)            Sea (9.37e-14)
15            Sea (8.26e-14)           seab (9.37e-14)
16            Sea (6.44e-14)           pisc (7.28e-14)
17          Ocean (5.02e-14)            Sea (7.28e-14)
18           pisc (3.91e-14)          Ocean (5.68e-14)
19       Maritime (3.44e-14)         seas (5.02e-14) ✅