# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [12]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/olmo2_1B/random_olmo_other_olmo/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [13]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: /workspace/model-organisms/diffing_results/olmo2_1B/random_olmo_other_olmo/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: []
Layer 14 dir: /workspace/model-organisms/diffing_results/olmo2_1B/random_olmo_other_olmo/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: []
Layer 15 dir: /workspace/model-organisms/diffing_results/olmo2_1B/random_olmo_other_olmo/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: []

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [14]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0239)      urrenc (0.0217)          .Today (0.0266)
1          .Second (0.0114)       pos (5.16e-03)       .Second (8.61e-03)
2        Buccane (8.85e-03)       act (4.85e-03)       Buccane (6.71e-03)
3          /Area (6.07e-03)    askell (3.54e-03)          fter (5.58e-03)
4            .au (4.88e-03)      gons (3.33e-03)     /problems (5.40e-03)
5      /problems (4.03e-03)        �� (2.09e-03)         /Area (5.25e-03)
6            aru (3.91e-03)      ejec (2.01e-03)      /problem (4.76e-03)
7      /entities (2.96e-03)      azon (1.95e-03)           .au (3.83e-03)
8       /problem (2.69e-03)        دي (1.95e-03)     /entities (3.39e-03)
9          /bind (2.69e-03)     fácil (1.79e-03)         /Math (3.17e-03)
10         /Math (2.61e-03)      anth (1.73e-03)           aru (2.99e-03)
11      /respond (2.61e-03)     posix (1.73e-03)           eft (2.81e-03)
12          fter (2.46e-03)  essional (1.63e-03)      /respond (2.81e-03)
13    confidence (2.30e-03)  Optional (1.57e-03)        soever (2.64e-03)
14     /operator (2.23e-03)      Vers (1.48e-03)     /activity (2.47e-03)
15   persistence (2.23e-03)    Phones (1.43e-03)   persistence (2.40e-03)
16     /activity (2.17e-03)        vs (1.39e-03)     /operator (2.32e-03)
17          ilot (1.97e-03)       med (1.27e-03)         /bind (2.26e-03)
18     belonging (1.97e-03)      orst (1.27e-03)           ERM (2.12e-03)
19          oire (1.85e-03)  >Welcome (1.27e-03)            ют (1.98e-03)

                                                                      \
                 ft_inv                 diff                diff_inv
0       urrenc (0.0204)         ött (0.0262)         mens (7.69e-03)
1        act (4.55e-03)     ursal (9.64e-03)         clip (6.99e-03)
2        pos (4.27e-03)  populate (6.26e-03)          ans (6.77e-03)
3       gons (3.11e-03)       Gle (6.26e-03)          ush (4.97e-03)
4     askell (2.75e-03)        MS (5.86e-03)            � (4.12e-03)
5       anth (2.08e-03)       iji (5.86e-03)         sequ (4.00e-03)
6   essional (2.08e-03)    Wonder (5.86e-03)           ​​ (3.86e-03)
7         دي (2.01e-03)     Guess (5.19e-03)          lda (3.63e-03)
8      fácil (1.95e-03)       OND (4.30e-03)      nothing (3.42e-03)
9         �� (1.89e-03)     ambio (3.34e-03)   comparator (3.31e-03)
10       med (1.72e-03)     Guess (3.34e-03)         ires (3.11e-03)
11      azon (1.62e-03)     guard (2.94e-03)         uren (3.11e-03)
12      ejec (1.57e-03)   stories (2.94e-03)          SIM (2.91e-03)
13      Vers (1.52e-03)    ordova (2.61e-03)         uste (2.91e-03)
14    Phones (1.47e-03)      afia (2.61e-03)          ckt (2.82e-03)
15        vs (1.47e-03)     ienen (2.44e-03)           àn (2.58e-03)
16     posix (1.38e-03)   entanyl (2.44e-03)          .te (2.50e-03)
17        bi (1.34e-03)   criptor (2.44e-03)      Passage (2.50e-03)
18         次 (1.22e-03)       uba (2.15e-03)      private (2.43e-03)
19       ')" (1.14e-03)     queda (2.15e-03)          ][- (2.43e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.9219)
1           The (0.0452)      contador (0.1309)          The (0.0356)
2           Let (0.0156)           메 (8.36e-03)           In (0.0140)
3            In (0.0138)         иск (3.49e-03)          Let (0.0103)
4         ### (4.49e-03)     Produto (2.12e-03)        ### (5.46e-03)
5           A (2.88e-03)           � (1.42e-05)          A (4.00e-03)
6         For (1.28e-03)      Resets (1.11e-05)        For (1.14e-03)
7          As (9.99e-04)     Detalle (9.83e-06)         As (9.54e-04)
8           I (9.08e-04)         .\" (4.08e-06)          1 (9.54e-04)
9           1 (7.78e-04)          首页 (3.19e-06)         ** (9.54e-04)
10         ** (7.55e-04)      inicio (2.19e-06)  Certainly (6.52e-04)
11  Certainly (6.07e-04)    autoplay (1.51e-06)          I (4.79e-04)
12         We (4.58e-04)       KANJI (1.51e-06)         We (4.63e-04)
13       Sure (4.58e-04)   Generates (1.33e-06)       Sure (3.97e-04)
14      First (4.16e-04)      Editar (1.17e-06)      First (3.72e-04)
15         It (3.68e-04)         Msp (9.13e-07)         It (2.73e-04)
16       This (3.45e-04)     kontakt (9.13e-07)       This (2.34e-04)
17      Given (2.16e-04)      <quote (8.05e-07)          H (1.76e-04)
18          S (1.68e-04)   Productos (8.05e-07)          S (1.55e-04)
19          H (1.68e-04)      lokale (8.05e-07)      Given (1.51e-04)

                                                                               \
                   ft_inv                      diff                  diff_inv
0           zoek (0.8398)           ALSO (8.00e-03)            Based (0.0376)
1       contador (0.1465)           Vari (5.52e-03)                I (0.0250)
2            메 (7.26e-03)         OnInit (5.19e-03)            ennon (0.0138)
3          иск (3.89e-03)           VERS (3.78e-03)            based (0.0138)
4      Produto (2.37e-03)             An (3.14e-03)         amente (8.36e-03)
5            � (1.09e-05)      assisting (2.94e-03)          blush (6.71e-03)
6       Resets (8.52e-06)         pagina (2.61e-03)            let (6.62e-03)
7      Detalle (6.62e-06)       Citation (2.61e-03)            ecn (6.41e-03)
8          .\" (4.56e-06)           vera (2.30e-03)        feeling (5.49e-03)
9           首页 (3.13e-06)   currentValue (2.30e-03)          seems (5.00e-03)
10    autoplay (1.48e-06)       Narendra (2.15e-03)            the (4.61e-03)
11      inicio (1.30e-06)          Vapor (2.03e-03)  <|endoftext|> (4.21e-03)
12      Editar (1.15e-06)              然 (2.03e-03)            let (3.83e-03)
13       KANJI (1.01e-06)            —or (2.03e-03)         '\n\n' (3.77e-03)
14   Generates (1.01e-06)         ADDING (2.03e-03)          Based (3.77e-03)
15     kontakt (8.98e-07)          vapor (2.03e-03)             jn (3.77e-03)
16         Msp (8.98e-07)            ety (1.91e-03)           ords (3.71e-03)
17        (PHP (7.93e-07)          ropri (1.91e-03)          urses (3.43e-03)
18   Productos (7.00e-07)     namedtuple (1.79e-03)           Okay (3.28e-03)
19    Executes (6.18e-07)      OnDestroy (1.68e-03)           cano (2.88e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4414)          zoek (0.9688)           To (0.3770)
1            ** (0.2676)      contador (0.0138)           ** (0.3320)
2           ### (0.2363)         иск (8.36e-03)          ### (0.2598)
3           Let (0.0282)           메 (8.36e-03)          Let (0.0146)
4           The (0.0171)     Produto (6.87e-04)        The (8.85e-03)
5   Certainly (2.98e-03)          首页 (4.39e-05)  Certainly (2.24e-03)
6        Sure (1.59e-03)        (PHP (1.18e-05)         In (1.06e-03)
7          In (1.24e-03)         Msp (1.04e-05)       Sure (9.35e-04)
8          ## (8.51e-04)      amodel (5.93e-06)         ## (8.24e-04)
9       Given (4.02e-04)      Gratis (5.57e-06)          1 (3.43e-04)
10          1 (2.77e-04)           � (4.92e-06)          A (3.03e-04)
11      First (2.44e-04)       ptest (4.92e-06)      Given (2.37e-04)
12          A (2.16e-04)    autoplay (4.35e-06)      First (1.84e-04)
13        ``` (1.90e-04)       etest (4.35e-06)       #### (1.27e-04)
14         We (1.78e-04)         .\" (4.35e-06)         As (1.19e-04)
15       This (1.68e-04)      ertest (3.84e-06)         We (1.19e-04)
16         As (1.39e-04)       Ports (3.84e-06)        For (9.25e-05)
17       #### (1.39e-04)        [now (3.84e-06)        ``` (9.25e-05)
18        For (1.23e-04)     Detalle (3.61e-06)       Here (8.15e-05)
19       Here (1.23e-04)  modifiable (3.61e-06)       This (7.68e-05)


                   ft_inv               diff           diff_inv
0           zoek (0.9766)         — (0.6523)       ecn (0.0152)
1     contador (9.58e-03)         ​ (0.0503)      osos (0.0104)
2          иск (6.59e-03)       —or (0.0253)   ennon (8.12e-03)
3            메 (5.80e-03)         ― (0.0184)  amente (7.63e-03)
4      Produto (6.10e-04)         … (0.0164)    ilog (5.58e-03)
5           首页 (2.69e-05)       ( (9.28e-03)    EDIA (5.58e-03)
6         (PHP (1.27e-05)       — (8.73e-03)    ials (5.25e-03)
7          Msp (8.70e-06)      or (4.39e-03)      mb (5.25e-03)
8       amodel (5.30e-06)    —and (3.88e-03)    viso (4.94e-03)
9        ptest (4.11e-06)       . (3.88e-03)      sb (4.64e-03)
10           � (3.87e-06)      ,… (3.02e-03)    ords (4.64e-03)
11       etest (3.64e-06)      …. (2.21e-03)      IU (4.36e-03)
12    autoplay (3.41e-06)      An (2.08e-03)    oord (4.09e-03)
13  modifiable (3.41e-06)       … (2.01e-03)    bard (3.85e-03)
14       edata (3.41e-06)    thus (1.62e-03)      FS (3.62e-03)
15         .\" (3.20e-06)    Vari (1.52e-03)   Based (3.19e-03)
16      skirts (3.01e-06)    also (1.52e-03)    borg (2.81e-03)
17       Ports (2.67e-06)      .. (1.43e-03)     BSD (2.81e-03)
18      Gratis (2.67e-06)      —a (1.43e-03)      FB (2.64e-03)
19      ertest (2.50e-06)   Value (1.43e-03)      WW (2.64e-03)

In [15]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0430)
1        /entities (0.0265)       (us (5.07e-03)       /entities (0.0278)
2        /problems (0.0171)      sagt (4.46e-03)       /problems (0.0192)
3         .Today (9.16e-03)       ]]; (3.94e-03)        .Today (8.73e-03)
4        /global (8.61e-03)        że (3.48e-03)       /global (8.24e-03)
5        /manage (7.81e-03)    testim (2.88e-03)       /manage (7.48e-03)
6           /job (6.68e-03)       ($. (2.70e-03)          /job (6.81e-03)
7   /preferences (6.10e-03)      -ves (2.70e-03)       /layout (6.41e-03)
8        /layout (5.74e-03)       ')" (2.70e-03)  /preferences (5.83e-03)
9      /provider (5.07e-03)     zeigt (2.55e-03)     /provider (5.46e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)   /connection (4.55e-03)
11   /connection (4.18e-03)     feliz (2.24e-03)       /crypto (4.39e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)    WHATSOEVER (4.27e-03)
13  /environment (4.06e-03)       (!! (1.98e-03)          /reg (3.88e-03)
14      /logging (3.94e-03)   kontrol (1.98e-03)  /environment (3.77e-03)
15       /engine (3.81e-03)    spiele (1.98e-03)      /effects (3.77e-03)
16          /reg (3.69e-03)      helf (1.75e-03)       /engine (3.77e-03)
17       /entity (3.48e-03)     scrut (1.54e-03)      /logging (3.77e-03)
18       /dialog (3.37e-03)       )": (1.45e-03)       /dialog (3.77e-03)
19      /effects (3.37e-03)       fas (1.45e-03)       /entity (3.42e-03)

                                                                  \
                 ft_inv                  diff           diff_inv
0        .vn (8.36e-03)     ichtig (6.81e-03)        ​​ (0.1680)
1        (us (4.79e-03)      spiel (6.38e-03)         � (0.0292)
2       sagt (3.97e-03)      /exec (6.38e-03)      ador (0.0133)
3        ]]; (3.97e-03)     fenced (6.38e-03)       row (0.0107)
4         że (3.49e-03)    ificado (6.01e-03)    undy (9.46e-03)
5     testim (2.90e-03)      aired (5.65e-03)    stin (7.81e-03)
6       -ves (2.90e-03)        iou (4.39e-03)   andel (7.35e-03)
7        ')" (2.72e-03)   ollapsed (4.12e-03)   older (6.93e-03)
8      zeigt (2.56e-03)     itives (3.88e-03)     ron (6.29e-03)
9      lesen (2.26e-03)      imity (3.65e-03)     oca (5.22e-03)
10       ($. (2.26e-03)       onia (3.65e-03)    utch (4.76e-03)
11     spons (2.12e-03)       ickt (3.42e-03)  holder (4.76e-03)
12     feliz (2.00e-03)  itionally (3.22e-03)     eng (3.81e-03)
13    spiele (1.87e-03)        Ter (3.22e-03)   stein (3.37e-03)
14       (!! (1.87e-03)      yecto (3.02e-03)    adel (3.37e-03)
15   kontrol (1.75e-03)      serta (3.02e-03)     aff (3.07e-03)
16       )": (1.65e-03)       ynom (2.84e-03)    okin (2.47e-03)
17       fas (1.65e-03)         Zu (2.84e-03)    vest (2.40e-03)
18     scrut (1.46e-03)         +l (2.67e-03)    stan (2.32e-03)
19      helf (1.46e-03)        SHA (2.67e-03)    sett (2.18e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5898)     contador (0.8555)        , (0.5938)
1       and (0.1484)    kontrol (7.39e-03)      and (0.1572)
2       the (0.1270)         bö (5.77e-03)      the (0.1187)
3        in (0.0552)   karakter (5.77e-03)       in (0.0564)
4       ' ' (0.0479)         �� (5.77e-03)      ' ' (0.0430)
5         a (0.0129)         �� (4.49e-03)        a (0.0128)
6       ( (3.28e-03)      subur (3.49e-03)      ( (4.06e-03)
7      to (2.99e-03)      KANJI (3.49e-03)     to (2.94e-03)
8      of (2.79e-03)       samt (2.72e-03)     of (2.85e-03)
9      by (2.33e-03)     testim (2.72e-03)     by (2.33e-03)
10    for (1.68e-03)     kosten (2.12e-03)    for (1.59e-03)
11     is (1.04e-03)     bilder (1.65e-03)     is (1.16e-03)
12     as (8.85e-04)       sagt (1.65e-03)     as (9.19e-04)
13     on (7.82e-04)     komple (1.65e-03)     on (7.63e-04)
14     we (4.44e-04)     spiele (1.28e-03)     we (4.41e-04)
15   with (3.68e-04)     sperma (1.28e-03)   with (4.14e-04)
16   will (2.96e-04)       zoek (1.28e-03)      " (3.83e-04)
17      " (2.88e-04)       dara (1.28e-03)   will (3.43e-04)
18      . (2.61e-04)       rekl (1.28e-03)     at (2.90e-04)
19     at (2.54e-04)        tgl (1.28e-03)      . (2.63e-04)

                                                                           \
                  ft_inv                     diff                diff_inv
0      contador (0.8711)          hereby (0.0244)           endo (0.0173)
1     kontrol (5.86e-03)         thereby (0.0178)           ed (8.18e-03)
2          �� (4.58e-03)          opleft (0.0102)          aso (7.93e-03)
3    karakter (4.58e-03)             ￥ (7.93e-03)           FE (6.99e-03)
4          �� (4.58e-03)      galement (6.16e-03)         ried (6.38e-03)
5          bö (4.58e-03)       ?family (5.13e-03)           en (5.62e-03)
6       subur (2.76e-03)      moreover (4.52e-03)    espionage (4.24e-03)
7       KANJI (2.76e-03)        anomal (4.52e-03)        endet (4.06e-03)
8      kosten (2.15e-03)   furthermore (4.24e-03)   bargaining (3.86e-03)
9        samt (2.15e-03)      iterator (4.24e-03)          ega (3.63e-03)
10     testim (2.15e-03)          plus (4.24e-03)            F (3.51e-03)
11     bilder (1.68e-03)         adres (4.24e-03)           's (3.40e-03)
12       sagt (1.68e-03)             ― (4.00e-03)           ED (3.05e-03)
13       zoek (1.30e-03)      likewise (4.00e-03)    smuggling (2.96e-03)
14     uarios (1.30e-03)          ?,\n (3.74e-03)        booth (2.91e-03)
15     komple (1.30e-03)          thus (3.52e-03)        smugg (2.87e-03)
16       rekl (1.02e-03)            ?: (3.31e-03)         Cole (2.61e-03)
17       dara (1.02e-03)        OnInit (3.10e-03)         pend (2.53e-03)
18        tgl (1.02e-03)        Credit (3.10e-03)      illegal (2.41e-03)
19     spiele (1.02e-03)            añ (2.91e-03)          dig (2.38e-03)

             layer_15                                          \
                 base             base_inv                 ft
0          , (0.5195)    contador (0.0703)         , (0.5547)
1         in (0.1270)    incinn (4.52e-03)        in (0.1089)
2        ' ' (0.0933)      LOSE (4.52e-03)       and (0.0962)
3        the (0.0820)      anio (4.52e-03)       the (0.0874)
4        and (0.0820)      rido (4.52e-03)       ' ' (0.0679)
5          a (0.0303)       ogs (3.51e-03)         a (0.0236)
6          ( (0.0154)        �� (3.51e-03)         ( (0.0195)
7         by (0.0110)    icerca (2.73e-03)      by (9.95e-03)
8       to (8.30e-03)     UTTON (2.73e-03)      to (6.84e-03)
9      for (6.35e-03)       ，默认 (2.73e-03)     for (5.00e-03)
10      as (3.51e-03)      zoek (2.73e-03)      as (3.23e-03)
11   first (2.99e-03)  entarios (2.12e-03)   first (2.59e-03)
12      we (2.50e-03)    anneer (2.12e-03)       " (2.21e-03)
13      of (1.85e-03)      <?\n (2.12e-03)      of (2.04e-03)
14      ** (1.82e-03)       @js (2.12e-03)    with (1.98e-03)
15       " (1.78e-03)    <quote (2.12e-03)      we (1.86e-03)
16    with (1.75e-03)  ategoria (1.66e-03)      on (9.77e-04)
17      on (1.08e-03)       (Cs (1.66e-03)      ** (9.61e-04)
18    will (6.10e-04)      obao (1.66e-03)    will (5.99e-04)
19      at (5.38e-04)    HOLDER (1.66e-03)      at (5.30e-04)


                 ft_inv                    diff          diff_inv
0     contador (0.0586)  <|endoftext|> (0.1221)     oord (0.0147)
1     incinn (6.20e-03)              — (0.0952)     EDIA (0.0121)
2       LOSE (4.82e-03)              ​ (0.0894)     endo (0.0114)
3       rido (4.82e-03)             or (0.0742)    porto (0.0107)
4     icerca (3.75e-03)              : (0.0226)  endet (7.87e-03)
5         �� (3.75e-03)              ― (0.0226)    ecn (7.39e-03)
6     anneer (3.75e-03)              « (0.0182)    FER (6.53e-03)
7       anio (3.75e-03)           thus (0.0155)    IFF (3.97e-03)
8      UTTON (2.93e-03)              ­ (0.0141)    vet (3.71e-03)
9        ，默认 (2.93e-03)            […] (0.0137)  enden (3.49e-03)
10    <quote (2.27e-03)           ,… (8.85e-03)   coli (3.08e-03)
11       ogs (2.27e-03)           ?: (8.30e-03)   esub (3.08e-03)
12      zoek (2.27e-03)            � (8.30e-03)   ensa (2.72e-03)
13    LOGGER (2.27e-03)            » (6.07e-03)    {\" (2.40e-03)
14  entarios (1.77e-03)    therefore (6.07e-03)   Brew (2.40e-03)
15        排序 (1.77e-03)      thereby (5.71e-03)   Wahl (2.26e-03)
16  ategoria (1.77e-03)       hereby (5.52e-03)   ento (2.26e-03)
17    HOLDER (1.77e-03)          —or (4.58e-03)   ords (2.12e-03)
18      <?\n (1.77e-03)            ‚ (3.80e-03)     sb (2.12e-03)
19      erca (1.77e-03)        [...] (3.25e-03)    enz (1.98e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [16]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0256)         .vn (0.0196)       /entities (0.0272)
1         /problem (0.0140)   /Register (0.0113)        /problem (0.0143)
2      /problems (9.21e-03)    testim (6.99e-03)     /problems (9.95e-03)
3        /global (6.70e-03)      sagt (6.58e-03)       /global (6.39e-03)
4   /environment (6.00e-03)     asign (5.31e-03)   /connection (6.24e-03)
5      /provider (5.89e-03)       -ie (4.90e-03)     /provider (6.10e-03)
6         .Today (5.79e-03)     zeigt (4.03e-03)  /environment (5.71e-03)
7    /connection (5.72e-03)        że (3.99e-03)        .Today (5.67e-03)
8        /manage (5.60e-03)      -ves (3.29e-03)     /customer (5.31e-03)
9      /customer (4.73e-03)         ť (2.94e-03)       /manage (5.18e-03)
10  /preferences (4.25e-03)   personn (2.83e-03)  /preferences (3.92e-03)
11       /dialog (3.37e-03)     probs (2.79e-03)       /shared (3.67e-03)
12       /shared (3.35e-03)      elig (2.59e-03)       /dialog (3.48e-03)
13      /account (3.20e-03)    ):\n\n (2.36e-03)      libertin (3.44e-03)
14       /entity (3.17e-03)      roku (2.35e-03)      /account (3.17e-03)
15      libertin (3.12e-03)     lesen (2.31e-03)       /entity (3.17e-03)
16       /layout (2.92e-03)  ,,,,,,,, (2.23e-03)       /layout (3.13e-03)
17          .Try (2.83e-03)       )": (2.21e-03)      /effects (2.91e-03)
18      /effects (2.73e-03)    spiele (2.12e-03)          .Try (2.82e-03)
19        /legal (2.64e-03)       (us (2.09e-03)         .Take (2.75e-03)

                                                                     \
                 ft_inv                  diff              diff_inv
0          .vn (0.0202)        spiel (0.0242)           ​​ (0.1084)
1    /Register (0.0109)         ickt (0.0121)            � (0.0135)
2     testim (6.92e-03)     ighted (7.41e-03)        row (7.06e-03)
3       sagt (6.03e-03)        éis (7.32e-03)        ron (6.52e-03)
4      asign (5.17e-03)     ichtig (7.30e-03)      andle (5.20e-03)
5        -ie (4.82e-03)      ibili (7.18e-03)       ador (5.07e-03)
6      zeigt (4.04e-03)      Regel (5.70e-03)        ens (3.64e-03)
7         że (3.83e-03)      aired (5.67e-03)       stin (3.22e-03)
8       -ves (3.24e-03)  reachable (5.56e-03)      older (3.19e-03)
9    personn (2.98e-03)       anus (5.36e-03)       itch (2.94e-03)
10         ť (2.97e-03)         äß (5.34e-03)      enser (2.51e-03)
11     probs (2.90e-03)      imity (5.19e-03)      andel (2.49e-03)
12      elig (2.50e-03)       cine (3.67e-03)      (...) (2.39e-03)
13       )": (2.34e-03)         ền (3.65e-03)       usan (2.36e-03)
14     lesen (2.30e-03)     itives (3.65e-03)   powerful (2.34e-03)
15    ):\n\n (2.27e-03)     ibilit (3.38e-03)        red (2.31e-03)
16      roku (2.22e-03)       iado (3.36e-03)      chten (2.19e-03)
17    spiele (2.18e-03)         ôm (3.35e-03)       vest (2.16e-03)
18  ,,,,,,,, (2.10e-03)   ollapsed (3.16e-03)       wich (1.91e-03)
19       esl (2.01e-03)     aturas (2.85e-03)         ージ (1.86e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8030)     contador (0.9620)         , (0.8253)
1        ' ' (0.1082)    kontrol (3.15e-03)       ' ' (0.0882)
2        the (0.0407)   karakter (2.50e-03)       the (0.0386)
3        and (0.0302)       rekl (1.60e-03)       and (0.0307)
4       in (5.89e-03)         bö (1.38e-03)      in (5.81e-03)
5        ( (4.36e-03)       zoek (1.15e-03)       ( (5.53e-03)
6       's (2.98e-03)    Produto (9.77e-04)      's (1.69e-03)
7        a (1.66e-03)     testim (9.74e-04)       a (1.54e-03)
8       to (9.75e-04)     bilder (8.70e-04)      to (8.99e-04)
9        . (6.60e-04)         �� (7.64e-04)       . (6.10e-04)
10      of (4.05e-04)       dara (7.55e-04)      of (3.96e-04)
11     for (1.76e-04)       helf (6.86e-04)     for (1.71e-04)
12      is (7.01e-05)       samt (5.28e-04)   solve (7.53e-05)
13  '\xa0' (6.40e-05)      subur (5.22e-04)      is (7.21e-05)
14      on (6.29e-05)      KANJI (5.13e-04)      on (6.31e-05)
15      as (6.15e-05)          메 (3.58e-04)  '\xa0' (6.25e-05)
16   solve (5.84e-05)       fakt (3.55e-04)      as (5.96e-05)
17    with (3.11e-05)     komple (3.46e-04)       " (3.88e-05)
18       " (2.76e-05)     kosten (2.84e-04)    with (3.42e-05)
19      by (2.74e-05)      henne (2.78e-04)      by (2.74e-05)

                                                                           \
                  ft_inv                     diff                diff_inv
0      contador (0.9614)               ￥ (0.0154)             ed (0.0465)
1     kontrol (3.01e-03)         massa (7.83e-03)             FE (0.0183)
2    karakter (1.88e-03)       ?family (7.57e-03)           pend (0.0154)
3        rekl (1.31e-03)        opleft (6.08e-03)             ED (0.0110)
4     Produto (1.25e-03)       thereby (5.74e-03)           's (6.97e-03)
5          bö (1.22e-03)         adres (5.67e-03)        porto (5.66e-03)
6      bilder (1.16e-03)          ?,\n (5.57e-03)           en (5.27e-03)
7        zoek (1.10e-03)      iterator (5.37e-03)         endo (4.05e-03)
8      testim (1.08e-03)        hereby (4.65e-03)     Navigate (3.79e-03)
9          �� (7.68e-04)          kurs (3.49e-03)         ried (3.51e-03)
10       helf (7.52e-04)          ALSO (3.42e-03)          ecn (3.37e-03)
11       dara (6.73e-04)     occurring (3.26e-03)   redemption (3.12e-03)
12      subur (5.53e-04)      galement (3.14e-03)          aso (3.06e-03)
13      KANJI (4.79e-04)        /cloud (3.06e-03)           os (2.70e-03)
14       samt (4.55e-04)   Alternative (2.69e-03)    elections (2.66e-03)
15     kosten (3.68e-04)             в (2.57e-03)    espionage (2.61e-03)
16     komple (3.61e-04)      likewise (2.51e-03)        RIEND (2.56e-03)
17          메 (3.51e-04)       oplevel (2.22e-03)         -Col (2.36e-03)
18       fakt (3.16e-04)         ATHER (2.19e-03)     election (2.35e-03)
19       arbe (2.81e-04)           [ii (2.15e-03)     burglary (2.33e-03)

               layer_15                                             \
                   base              base_inv                   ft
0            , (0.7723)     contador (0.9331)           , (0.8044)
1          ' ' (0.1208)       zoek (5.50e-03)           ( (0.0987)
2            ( (0.0728)    Produto (1.33e-03)         ' ' (0.0643)
3          the (0.0192)          메 (4.29e-04)         the (0.0202)
4        and (3.11e-03)         �� (3.02e-04)       and (3.43e-03)
5         in (3.03e-03)   entarios (2.92e-04)        in (2.46e-03)
6         's (2.59e-03)   karakter (2.64e-04)        's (1.44e-03)
7          a (1.71e-03)       rido (2.59e-04)         a (1.20e-03)
8         ** (1.17e-03)     <quote (2.48e-04)        ** (7.83e-04)
9         to (8.32e-04)     HOLDER (1.91e-04)        to (6.34e-04)
10     solve (8.17e-04)       obao (1.90e-04)     solve (6.30e-04)
11         " (1.76e-04)       anio (1.71e-04)         " (2.53e-04)
12    tackle (1.39e-04)        用户名 (1.66e-04)         : (2.09e-04)
13       for (1.35e-04)        ogs (1.53e-04)    tackle (1.39e-04)
14   problem (1.15e-04)      UTTON (1.49e-04)   address (1.23e-04)
15        by (1.12e-04)    kontrol (1.36e-04)   problem (1.15e-04)
16      this (9.88e-05)        ，默认 (1.35e-04)      this (1.09e-04)
17   address (9.06e-05)     urette (1.34e-04)       for (1.03e-04)
18         : (8.06e-05)       LEAN (1.31e-04)        by (1.01e-04)
19        as (6.43e-05)     bilder (1.17e-04)        of (5.94e-05)


                  ft_inv                    diff               diff_inv
0      contador (0.9257)  <|endoftext|> (0.5608)          EDIA (0.0188)
1        zoek (7.44e-03)              ​ (0.0879)          oord (0.0168)
2     Produto (2.59e-03)              — (0.0369)         porto (0.0138)
3           메 (5.18e-04)             or (0.0197)         ecn (6.50e-03)
4          �� (3.40e-04)              : (0.0185)        coli (5.63e-03)
5      <quote (3.19e-04)              ― (0.0125)         FER (5.15e-03)
6    entarios (2.74e-04)              « (0.0118)       endet (4.46e-03)
7        rido (2.61e-04)            � (5.75e-03)      。”\n\n (4.33e-03)
8      HOLDER (2.42e-04)          […] (5.65e-03)          FS (4.15e-03)
9        [now (2.30e-04)            ­ (5.46e-03)   PropTypes (3.49e-03)
10       obao (1.85e-04)            » (3.10e-03)        endo (3.35e-03)
11     bilder (1.70e-04)        [...] (3.08e-03)        ultz (3.27e-03)
12     icerca (1.65e-04)           ,… (2.88e-03)        esub (3.13e-03)
13     urette (1.56e-04)            ‚ (2.77e-03)       JUnit (3.01e-03)
14     anneer (1.55e-04)         thus (2.40e-03)         vez (3.00e-03)
15      UTTON (1.50e-04)           ?: (2.16e-03)        esan (2.86e-03)
16   karakter (1.46e-04)         also (1.58e-03)       uchen (2.53e-03)
17        ，默认 (1.42e-04)          —or (1.50e-03)         esa (2.46e-03)
18       LOSE (1.33e-04)            « (1.29e-03)        ikut (2.28e-03)
19       anio (1.32e-04)            в (1.18e-03)         IFF (2.26e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [17]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

FileNotFoundError: [Errno 2] No such file or directory: '/workspace/model-organisms/diffing_results/olmo2_1B/random_olmo_other_olmo/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture/base_auto_patch_scope_pos_-1_openai_gpt-5-mini.pt'

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [ ]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [18]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_7                                             \
                    pos_-3               pos_-1                 pos_0
0            ícia (0.0208)         ött (0.0262)        ursal (0.0273)
1         Masters (0.0111)     ursal (9.64e-03)         xima (0.0256)
2           ite (9.77e-03)  populate (6.26e-03)         cita (0.0212)
3          ceso (9.22e-03)       Gle (6.26e-03)        yecto (0.0212)
4          utan (6.71e-03)        MS (5.86e-03)         haps (0.0137)
5        ención (6.32e-03)       iji (5.86e-03)         pite (0.0107)
6          Lies (5.92e-03)    Wonder (5.86e-03)      /exec (6.10e-03)
7           sel (4.91e-03)     Guess (5.19e-03)     itives (5.07e-03)
8        anking (4.61e-03)       OND (4.30e-03)      antha (4.76e-03)
9       achuset (4.61e-03)     ambio (3.34e-03)       iltr (4.76e-03)
10         ment (4.61e-03)     Guess (3.34e-03)       ynom (3.48e-03)
11     Insights (4.33e-03)     guard (2.94e-03)      spiel (3.48e-03)
12          ERY (4.09e-03)   stories (2.94e-03)       Shar (3.27e-03)
13         Seks (3.83e-03)    ordova (2.61e-03)       ickt (3.27e-03)
14  ryptography (3.17e-03)      afia (2.61e-03)    .rstrip (3.07e-03)
15         iltr (2.99e-03)     ienen (2.44e-03)      endum (2.88e-03)
16         fila (2.99e-03)   entanyl (2.44e-03)  itionally (2.70e-03)
17         tant (2.81e-03)   criptor (2.44e-03)      mente (2.70e-03)
18        antha (2.81e-03)       uba (2.15e-03)  vironment (2.38e-03)
19          xec (2.64e-03)     queda (2.15e-03)      Gover (2.38e-03)

                                                                      \
                   pos_1                 pos_2                 pos_3
0          xima (0.0234)       ichtig (0.0125)       ichtig (0.0164)
1        ichtig (0.0161)      imity (8.12e-03)        spiel (0.0120)
2         ursal (0.0134)       ynom (6.32e-03)          iou (0.0106)
3         yecto (0.0134)     fenced (6.32e-03)      aired (9.89e-03)
4        ynom (6.32e-03)       iltr (5.55e-03)     fenced (5.65e-03)
5       /exec (4.61e-03)       xima (5.55e-03)       ynom (5.65e-03)
6        rega (4.61e-03)    aussian (5.22e-03)     itives (3.88e-03)
7        pite (4.61e-03)      /exec (4.61e-03)      /exec (3.65e-03)
8        iltr (4.09e-03)      ursal (4.06e-03)      imity (3.42e-03)
9   itionally (4.09e-03)        iou (3.83e-03)       irse (3.02e-03)
10    aussian (2.98e-03)      aired (3.60e-03)       ickt (2.84e-03)
11        -li (2.62e-03)      spiel (3.17e-03)       iltr (2.67e-03)
12     ighted (2.47e-03)       fakt (2.98e-03)      ından (2.67e-03)
13   /student (2.47e-03)  itionally (2.98e-03)    ificado (2.67e-03)
14     urette (2.32e-03)       utos (2.98e-03)      yecto (2.67e-03)
15         �� (2.32e-03)    INVALID (2.79e-03)  itionally (2.50e-03)
16        iou (2.18e-03)     agnost (2.18e-03)      serta (2.50e-03)
17        hoe (1.92e-03)      abbix (2.18e-03)     inally (2.35e-03)
18    recurse (1.92e-03)    initely (2.18e-03)    initely (2.21e-03)
19    [];\n\n (1.92e-03)         +l (2.04e-03)       iniz (2.21e-03)

                                                                      \
                  pos_10                pos_50               pos_100
0         imity (0.0123)        spiel (0.0325)        spiel (0.0288)
1         spiel (0.0109)         ickt (0.0112)         ickt (0.0186)
2        ichtig (0.0109)        éis (8.24e-03)       ighted (0.0113)
3       aired (9.58e-03)  reachable (7.72e-03)      ibili (9.95e-03)
4      itives (7.45e-03)      Regel (7.72e-03)        éis (8.79e-03)
5        ickt (5.13e-03)      ibili (7.23e-03)       anus (8.24e-03)
6     ificado (5.13e-03)     ighted (7.23e-03)         äß (7.75e-03)
7       /exec (4.52e-03)     ichtig (6.81e-03)      Regel (5.68e-03)
8      ibilit (4.24e-03)         äß (6.41e-03)      aired (5.34e-03)
9   reachable (4.24e-03)      aired (5.31e-03)         ôm (5.34e-03)
10       iniz (4.00e-03)         ền (4.67e-03)  reachable (5.00e-03)
11        iou (3.31e-03)       anus (4.67e-03)       iado (4.70e-03)
12     ighted (3.31e-03)      imity (4.67e-03)       cine (4.43e-03)
13      yecto (3.31e-03)   ollapsed (3.88e-03)        jie (3.91e-03)
14      onica (2.91e-03)       cine (3.65e-03)         ền (3.66e-03)
15      ından (2.91e-03)         ôm (3.65e-03)     ichtig (3.66e-03)
16     aturas (2.91e-03)       iniz (3.42e-03)      imity (3.66e-03)
17     tright (2.75e-03)    ificado (3.42e-03)     ibilit (3.45e-03)
18  itionally (2.75e-03)       iado (3.22e-03)   ollapsed (3.23e-03)
19   ollapsed (2.58e-03)     ibilit (3.22e-03)     itives (3.23e-03)

           layer_14                                                    \
             pos_-3                    pos_-1                   pos_0
0        * (0.0508)           ALSO (8.00e-03)         OnInit (0.0227)
1     '\n' (0.0255)           Vari (5.52e-03)       opleft (7.39e-03)
2       ta (0.0226)         OnInit (5.19e-03)         Zahl (5.74e-03)
3      }\n (0.0155)           VERS (3.78e-03)      ?family (5.07e-03)
4        { (0.0146)             An (3.14e-03)           �� (5.07e-03)
5      .\n (0.0137)      assisting (2.94e-03)     galement (3.94e-03)
6      rss (0.0117)         pagina (2.61e-03)           ót (3.48e-03)
7      ;\n (0.0103)       Citation (2.61e-03)            ￥ (3.48e-03)
8      *\n (0.0103)           vera (2.30e-03)        afore (3.48e-03)
9      • (9.09e-03)   currentValue (2.30e-03)        ATHER (2.88e-03)
10   !\n (8.85e-03)       Narendra (2.15e-03)         ALSO (2.55e-03)
11    (* (8.30e-03)          Vapor (2.03e-03)   yourselves (2.40e-03)
12     + (7.32e-03)              然 (2.03e-03)      softmax (2.40e-03)
13     _ (6.68e-03)            —or (2.03e-03)   ableObject (2.24e-03)
14    (' (5.71e-03)         ADDING (2.03e-03)       Corpus (2.24e-03)
15     ● (5.37e-03)          vapor (2.03e-03)         også (2.24e-03)
16    (_ (5.37e-03)            ety (1.91e-03)         eral (2.24e-03)
17     . (5.04e-03)          ropri (1.91e-03)         attn (2.24e-03)
18    or (4.58e-03)     namedtuple (1.79e-03)       pagina (2.12e-03)
19   {\n (4.58e-03)      OnDestroy (1.68e-03)           añ (2.12e-03)

                                                                           \
                      pos_1                   pos_2                 pos_3
0          ?family (0.0157)        thereby (0.0221)       hereby (0.0337)
1          thereby (0.0148)         hereby (0.0195)      thereby (0.0247)
2         galement (0.0108)              ￥ (0.0172)            ￥ (0.0170)
3         opleft (8.97e-03)       OnInit (9.22e-03)      ?family (0.0103)
4         anomal (8.42e-03)      ?family (8.67e-03)      adres (9.64e-03)
5           ALSO (8.42e-03)          tit (7.63e-03)     OnInit (8.48e-03)
6         OnInit (7.87e-03)     galement (7.17e-03)   iterator (5.49e-03)
7         hereby (7.87e-03)       opleft (6.32e-03)     herein (4.85e-03)
8              ― (6.13e-03)        adres (4.36e-03)   galement (4.85e-03)
9       likewise (5.43e-03)       herein (4.09e-03)         ?: (4.85e-03)
10         afore (5.43e-03)     iterator (3.85e-03)     opleft (4.27e-03)
11           Riy (3.97e-03)           añ (3.39e-03)        tit (3.13e-03)
12   furthermore (3.72e-03)     likewise (2.47e-03)       darm (3.13e-03)
13      moreover (3.51e-03)         ?,\n (2.18e-03)         añ (2.94e-03)
14             ￥ (3.10e-03)        atrib (2.18e-03)   likewise (2.76e-03)
15         maman (2.90e-03)      softmax (2.18e-03)         /- (2.76e-03)
16     occurring (2.73e-03)         LOSS (2.06e-03)       ?,\n (2.76e-03)
17        Credit (2.56e-03)   Autonomous (2.06e-03)         tc (2.59e-03)
18       Annunci (2.41e-03)       anomal (1.93e-03)    softmax (2.59e-03)
19       equival (2.41e-03)       TARGET (1.93e-03)        {}\ (2.29e-03)

                                                                               \
                     pos_10                   pos_50                  pos_100
0                ￥ (0.0164)               ￥ (0.0161)               ￥ (0.0140)
1           hereby (0.0135)         massa (9.22e-03)         massa (7.08e-03)
2          thereby (0.0112)       ?family (7.17e-03)       ?family (5.86e-03)
3        ?family (8.24e-03)          ?,\n (6.74e-03)         adres (5.16e-03)
4       iterator (7.26e-03)         adres (6.32e-03)          ?,\n (4.85e-03)
5    furthermore (6.84e-03)        opleft (6.32e-03)      iterator (4.85e-03)
6           plus (6.41e-03)      iterator (5.25e-03)       thereby (4.58e-03)
7         opleft (6.01e-03)       thereby (4.64e-03)        opleft (4.27e-03)
8          adres (5.31e-03)          kurs (4.09e-03)          ALSO (3.78e-03)
9       galement (5.31e-03)          ALSO (3.39e-03)        /cloud (3.78e-03)
10     occurring (4.70e-03)             в (3.39e-03)     occurring (3.78e-03)
11      moreover (3.89e-03)        /cloud (3.39e-03)          kurs (3.14e-03)
12          ?,\n (3.89e-03)     occurring (3.19e-03)   Alternative (2.76e-03)
13          thus (3.65e-03)        hereby (3.19e-03)             в (2.76e-03)
14   interacting (3.22e-03)      galement (2.81e-03)        hereby (2.59e-03)
15         massa (3.22e-03)       oplevel (2.64e-03)            ав (2.44e-03)
16      likewise (3.22e-03)   Alternative (2.64e-03)      likewise (2.29e-03)
17          kurs (2.85e-03)      likewise (2.47e-03)          ther (2.15e-03)
18      /loading (2.85e-03)       atische (2.33e-03)         habit (2.15e-03)
19         ATHER (2.67e-03)         habit (2.33e-03)         ATHER (2.15e-03)

             layer_15                                                \
               pos_-3             pos_-1                      pos_0
0        .\n (0.9844)         — (0.6523)                 — (0.6016)
1      !\n (4.27e-03)         ​ (0.0503)                 ​ (0.0299)
2     '\n' (3.78e-03)       —or (0.0253)                 ― (0.0171)
3      :\n (1.79e-03)         ― (0.0184)     <|endoftext|> (0.0103)
4      ;\n (1.15e-03)         … (0.0164)                or (0.0103)
5      ?\n (8.43e-04)       ( (9.28e-03)               » (9.09e-03)
6      .\n (7.44e-04)       — (8.73e-03)             […] (8.06e-03)
7     .*\n (5.11e-04)      or (4.39e-03)               : (7.57e-03)
8        . (4.81e-04)    —and (3.88e-03)               ( (5.89e-03)
9    .\n\n (3.51e-04)       . (3.88e-03)               « (5.52e-03)
10     *\n (3.30e-04)      ,… (3.02e-03)               � (5.19e-03)
11       * (1.37e-04)      …. (2.21e-03)              ,… (5.19e-03)
12     }\n (1.25e-04)      An (2.08e-03)              (“ (4.88e-03)
13   ' \n' (8.63e-05)       … (2.01e-03)              (" (4.30e-03)
14       — (7.58e-05)    thus (1.62e-03)             —or (4.06e-03)
15     。\n (7.34e-05)    Vari (1.52e-03)            Vari (3.16e-03)
16   ...\n (6.91e-05)    also (1.52e-03)           Optim (3.16e-03)
17     ,\n (5.75e-05)      .. (1.43e-03)   Advertisement (2.96e-03)
18    ."\n (3.70e-05)      —a (1.43e-03)              An (2.96e-03)
19    ).\n (3.08e-05)   Value (1.43e-03)               … (2.78e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0               — (0.3066)              — (0.1572)              — (0.0723)
1               ​ (0.1279)              ​ (0.0791)              ​ (0.0679)
2               ― (0.0776)              ― (0.0330)              : (0.0388)
3               � (0.0304)             or (0.0309)             or (0.0342)
4              or (0.0215)            […] (0.0291)  <|endoftext|> (0.0221)
5               « (0.0173)              « (0.0188)            […] (0.0208)
6             […] (0.0173)              : (0.0166)              ― (0.0152)
7               » (0.0139)             ,… (0.0121)              « (0.0134)
8   <|endoftext|> (0.0102)  <|endoftext|> (0.0114)             ?: (0.0126)
9             ­ (8.42e-03)              � (0.0101)           thus (0.0118)
10         thus (7.69e-03)              ­ (0.0101)      thereby (9.22e-03)
11            : (7.69e-03)         thus (9.16e-03)           ,… (9.22e-03)
12        [...] (6.56e-03)          —or (7.81e-03)       hereby (9.22e-03)
13          —or (5.80e-03)        below (6.68e-03)            ­ (8.67e-03)
14        Optim (5.28e-03)      thereby (6.10e-03)          —or (6.74e-03)
15           ,… (4.67e-03)        [...] (5.89e-03)        below (6.74e-03)
16           ?: (4.67e-03)       hereby (4.73e-03)            � (5.95e-03)
17      thereby (4.24e-03)            … (4.73e-03)        [...] (5.58e-03)
18            ‚ (4.12e-03)            » (4.73e-03)       evapor (4.94e-03)
19         [... (3.63e-03)           ?: (4.46e-03)            » (4.94e-03)


                    pos_10                  pos_50                 pos_100
0   <|endoftext|> (0.2246)  <|endoftext|> (0.6055)  <|endoftext|> (0.7344)
1               ​ (0.1445)              ​ (0.0874)              ​ (0.0684)
2               — (0.0645)              — (0.0242)              : (0.0162)
3              or (0.0415)             or (0.0183)             or (0.0134)
4               : (0.0222)              : (0.0172)              — (0.0119)
5               ― (0.0190)              ― (0.0126)            « (6.35e-03)
6               « (0.0135)              « (0.0122)            ― (4.52e-03)
7               � (0.0126)            � (5.40e-03)            � (3.10e-03)
8             […] (0.0115)            ­ (4.76e-03)          […] (2.41e-03)
9              ,… (0.0112)          […] (4.61e-03)            ­ (2.33e-03)
10            ­ (9.89e-03)        [...] (3.39e-03)        [...] (1.88e-03)
11         thus (8.18e-03)            » (2.99e-03)            ‚ (1.76e-03)
12            » (5.80e-03)            ‚ (2.99e-03)            » (1.61e-03)
13           ?: (5.13e-03)           ,… (2.04e-03)         thus (9.77e-04)
14            ‚ (4.94e-03)         thus (1.59e-03)           ,… (9.46e-04)
15        [...] (3.74e-03)         also (1.59e-03)         also (9.46e-04)
16         plus (3.51e-03)            « (1.37e-03)           ?: (9.46e-04)
17          —or (3.51e-03)           ?: (1.37e-03)            « (9.31e-04)
18    therefore (3.30e-03)            в (1.37e-03)     exposure (7.97e-04)
19         also (2.73e-03)          —or (1.13e-03)            в (7.82e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [ ]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {PS_DIFF_POSITIONS}")
patchscope_diff_positions_table()