# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [3]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-9000/activation_difference_lens"
)
LAYERS = [12,23,25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [4]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-9000/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-9000/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-9000/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [5]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

               layer_12                                            \
                   base               base_inv                 ft
0         ne (2.06e-03)          '' (1.86e-04)      ne (2.72e-03)
1         '' (1.70e-03)           � (1.80e-04)      '' (2.47e-03)
2         _c (1.65e-03)          '' (1.70e-04)    akes (1.87e-03)
3       akes (1.60e-03)          '' (1.64e-04)   which (1.82e-03)
4          , (1.33e-03)          '' (1.64e-04)      _c (1.55e-03)
5        enu (1.29e-03)          '' (1.59e-04)     enu (1.50e-03)
6      which (1.17e-03)          '' (1.59e-04)       , (1.17e-03)
7         ok (1.10e-03)          '' (1.54e-04)     ',' (1.03e-03)
8         ex (9.99e-04)           B (1.54e-04)      ok (8.85e-04)
9        ',' (9.12e-04)          '' (1.54e-04)      '' (8.32e-04)
10        '' (9.12e-04)   -learning (1.54e-04)      co (7.10e-04)
11        co (8.58e-04)   Diagnosis (1.54e-04)     ude (7.10e-04)
12        '' (7.32e-04)          '' (1.54e-04)    copy (6.87e-04)
13         � (7.10e-04)          '' (1.50e-04)      '' (6.68e-04)
14  document (6.87e-04)          '' (1.50e-04)      '' (6.45e-04)
15       ude (6.26e-04)          '' (1.50e-04)      ex (6.26e-04)
16   lection (6.26e-04)          '' (1.50e-04)    pons (6.26e-04)
17     enter (5.61e-04)       <TKey (1.50e-04)   enter (6.07e-04)
18        '' (5.61e-04)          '' (1.50e-04)   gress (5.87e-04)
19      copy (5.61e-04)      orning (1.50e-04)   iable (5.72e-04)

                                                                          \
                  ft_inv                  diff                  diff_inv
0           � (2.37e-04)           '' (0.7344)               él (0.6328)
1          '' (1.91e-04)           '' (0.1123)               '' (0.1099)
2          '' (1.91e-04)           '' (0.1123)       fraternity (0.0586)
3          '' (1.85e-04)           '' (0.0172)               '' (0.0356)
4           . (1.63e-04)         '' (3.85e-03)               '' (0.0277)
5   .iterator (1.63e-04)         '' (3.85e-03)              ial (0.0216)
6          '' (1.63e-04)        éné (3.85e-03)         "}}>\n (8.97e-03)
7          '' (1.58e-04)         '' (2.06e-03)              ợ (6.20e-03)
8          '' (1.58e-04)         '' (1.42e-03)          anges (6.20e-03)
9          '' (1.58e-04)         '' (1.11e-03)             '' (5.46e-03)
10         '' (1.53e-04)         '' (1.11e-03)           "You (5.46e-03)
11          B (1.53e-04)        Fra (8.58e-04)             '' (4.82e-03)
12         '' (1.53e-04)         '' (7.59e-04)     .menuStrip (3.31e-03)
13          \ (1.48e-04)   pageSize (5.23e-04)             '' (2.93e-03)
14         '' (1.48e-04)         '' (4.06e-04)             '' (2.93e-03)
15         '' (1.44e-04)   casually (4.06e-04)        \tvalue (2.58e-03)
16      Pager (1.44e-04)         '' (2.46e-04)             st (2.27e-03)
17     orning (1.44e-04)   filepath (2.46e-04)           baum (2.01e-03)
18         '' (1.44e-04)       cess (1.69e-04)   Subcommittee (1.77e-03)
19         '' (1.44e-04)      ether (1.03e-04)             '' (1.77e-03)

                                        layer_23                     \
                                            base           base_inv
0                                   CUR (0.8086)     Opp (2.59e-04)
1                                 match (0.0486)      '' (2.44e-04)
2                                  akes (0.0190)      '' (2.44e-04)
3                                   enu (0.0115)      '' (2.44e-04)
4                                   rit (0.0115)   <TKey (2.29e-04)
5                             abilities (0.0115)      '' (2.29e-04)
6                                  ne (9.58e-03)   _cart (2.29e-04)
7                              cursor (6.99e-03)   saver (2.29e-04)
8                                  '' (5.46e-03)      '' (2.29e-04)
9                            Document (3.74e-03)      '' (2.29e-04)
10                                 '' (2.91e-03)      '' (2.29e-04)
11  '                               ' (2.58e-03)      '' (2.16e-04)
12                               copy (2.00e-03)      '' (2.16e-04)
13                              which (1.88e-03)      '' (2.16e-04)
14                                 '' (1.14e-03)   OUNCE (2.16e-04)
15                                 '' (1.08e-03)      '' (2.16e-04)
16                      notifications (1.08e-03)      '' (2.16e-04)
17                           identify (9.46e-04)      '' (2.16e-04)
18                                 kl (9.46e-04)      '' (2.16e-04)
19                                win (8.89e-04)      '' (2.16e-04)

                                                                            \
                      ft            ft_inv               diff     diff_inv
0           CUR (0.3828)     '' (2.20e-04)     Fresh (0.7617)  '' (0.0884)
1         match (0.1318)  _cart (2.20e-04)        '' (0.0806)  '' (0.0781)
2          akes (0.0967)     '' (2.20e-04)   _random (0.0554)  '' (0.0688)
3            ne (0.0403)     '' (2.20e-04)     Obama (0.0140)  '' (0.0325)
4        cursor (0.0190)     '' (2.20e-04)     oil (7.48e-03)  '' (0.0288)
5         which (0.0148)     '' (2.20e-04)   MULTI (6.59e-03)   N (0.0175)
6            '' (0.0109)     '' (2.07e-04)      '' (5.83e-03)  '' (0.0175)
7       .Text (9.58e-03)     '' (2.07e-04)      '' (4.55e-03)  '' (0.0136)
8          HE (9.58e-03)     '' (2.07e-04)      '' (3.54e-03)  '' (0.0136)
9         enu (7.02e-03)     '' (2.07e-04)      '' (3.54e-03)   4 (0.0120)
10  abilities (6.59e-03)     '' (2.07e-04)      '' (2.75e-03)  '' (0.0120)
11     .fixed (5.46e-03)     '' (2.07e-04)    ']): (2.15e-03)  '' (0.0120)
12   Document (5.46e-03)     '' (2.07e-04)   Norse (1.47e-03)  '' (0.0120)
13      USTOM (5.13e-03)     '' (2.07e-04)   \tmem (1.30e-03)  '' (0.0120)
14      gress (5.13e-03)     '' (2.07e-04)    trap (1.30e-03)   F (0.0120)
15         '' (4.82e-03)     '' (2.07e-04)      '' (1.30e-03)  '' (0.0120)
16         '' (4.82e-03)     '' (2.07e-04)      '' (1.14e-03)  '' (0.0120)
17         '' (4.24e-03)     '' (2.07e-04)      '' (1.14e-03)  '' (0.0120)
18      iable (4.00e-03)     '' (2.07e-04)      '' (1.01e-03)  '' (0.0106)
19        rit (4.00e-03)     '' (2.07e-04)      '' (8.93e-04)   � (0.0106)

                                        layer_25                         \
                                            base               base_inv
0                                   CUR (1.0000)           _rc (0.3008)
1                               match (1.67e-05)         sorts (0.3008)
2   '                               ' (3.73e-06)  INFRINGEMENT (0.0669)
3                                 rit (1.76e-06)            '' (0.0317)
4                                  '' (3.93e-07)        patial (0.0217)
5                                  '' (2.38e-07)     unchanged (0.0170)
6                              cursor (2.10e-07)       pthread (0.0132)
7                       notifications (2.84e-08)        gained (0.0117)
8                                  '' (1.19e-08)          "]." (0.0103)
9                                copy (1.05e-08)          '' (9.09e-03)
10                           Document (7.19e-09)       smirk (8.00e-03)
11                                 <= (4.37e-09)        READ (8.00e-03)
12                             _names (2.07e-09)          '' (7.05e-03)
13                                 ne (1.42e-09)    economic (7.05e-03)
14                               akes (8.59e-10)       abide (7.05e-03)
15                                enu (6.69e-10)         /ge (7.05e-03)
16                             .fixed (2.17e-10)         003 (7.05e-03)
17                              iable (7.05e-11)       Sorry (5.49e-03)
18                                 '' (3.34e-11)          '' (5.49e-03)
19                           products (3.34e-11)  Industrial (4.85e-03)

                                                                         \
                                              ft                 ft_inv
0                                   CUR (0.9648)         sorts (0.0918)
1                                 match (0.0227)           _rc (0.0491)
2   '                               ' (2.72e-03)            '' (0.0491)
3                                  '' (1.87e-03)     Committee (0.0337)
4                              cursor (1.65e-03)        patial (0.0262)
5                                  '' (1.28e-03)         ("../ (0.0232)
6                                  ne (8.81e-04)         draws (0.0232)
7                                akes (4.16e-04)           003 (0.0160)
8                                  '' (2.23e-04)        _until (0.0141)
9                              .fixed (1.96e-04)     unchanged (0.0124)
10                              USTOM (1.27e-04)        gained (0.0124)
11                                rit (1.19e-04)  INFRINGEMENT (0.0110)
12                              iable (8.73e-05)           /ge (0.0110)
13                                 '' (7.72e-05)     (buffer (9.64e-03)
14                               copy (6.39e-05)        _row (9.64e-03)
15                                 '' (6.01e-05)  (statement (9.64e-03)
16                              which (5.63e-05)       asing (8.54e-03)
17                                 '' (4.39e-05)          ão (8.54e-03)
18                                 HE (3.41e-05)          '' (7.54e-03)
19                              .Text (3.22e-05)       Sorry (6.65e-03)


                  diff               diff_inv
0       Fresh (0.3398)           det (0.0234)
1       Obama (0.1416)            '' (0.0161)
2     _random (0.0859)            kv (0.0134)
3         oil (0.0359)          '' (8.67e-03)
4          '' (0.0232)          '' (5.25e-03)
5          '' (0.0181)          '' (4.91e-03)
6     Norse (5.86e-03)        %@", (4.91e-03)
7        '' (5.16e-03)          '' (4.64e-03)
8        '' (4.85e-03)       \tret (4.64e-03)
9       RAW (4.85e-03)          '' (4.09e-03)
10       '' (4.55e-03)          '' (3.60e-03)
11    \tmem (4.27e-03)      ospels (3.60e-03)
12     Inch (3.78e-03)      halluc (3.39e-03)
13    MULTI (2.94e-03)       meric (2.99e-03)
14      _FN (2.76e-03)           N (2.99e-03)
15       '' (2.59e-03)  leshooting (2.99e-03)
16        " (2.44e-03)      Sahara (2.99e-03)
17   shovel (2.29e-03)          '' (2.81e-03)
18       '' (2.15e-03)          е� (2.81e-03)
19       '' (1.79e-03)         .MM (2.81e-03)

In [6]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

               layer_12                                              \
                   base               base_inv                   ft
0         ex (2.02e-04)  Registered (7.39e-05)        ex (1.45e-04)
1         ps (1.34e-04)   dismissal (6.53e-05)        ps (1.26e-04)
2        int (1.22e-04)        eins (5.67e-05)       str (1.03e-04)
3        str (1.19e-04)          '' (5.17e-05)       int (9.25e-05)
4     author (1.05e-04)         cic (4.70e-05)    relief (8.82e-05)
5         tl (9.82e-05)        Lyon (4.63e-05)    Status (8.82e-05)
6        224 (9.68e-05)          '' (4.48e-05)      ";\n (8.44e-05)
7     relief (9.39e-05)          '' (4.03e-05)      ions (8.15e-05)
8     Status (9.25e-05)          '' (3.96e-05)        '' (8.01e-05)
9       ions (9.11e-05)    detailed (3.96e-05)      imes (7.68e-05)
10        '' (9.11e-05)          '' (3.91e-05)        _D (7.44e-05)
11       ert (9.11e-05)     patrols (3.91e-05)       224 (7.44e-05)
12       .sc (8.30e-05)          '' (3.84e-05)       uff (7.44e-05)
13       uff (8.15e-05)          '' (3.79e-05)        tl (7.20e-05)
14     frame (8.15e-05)      .Green (3.72e-05)       ert (6.96e-05)
15  '\t\t\t' (8.01e-05)          '' (3.72e-05)        '' (6.87e-05)
16    arning (8.01e-05)      Ramsey (3.72e-05)        '' (6.68e-05)
17      ";\n (8.01e-05)          '' (3.67e-05)       .sc (6.68e-05)
18        (( (7.77e-05)          '' (3.67e-05)       sem (6.25e-05)
19        '' (7.44e-05)          '' (3.60e-05)  '\t\t\t' (6.25e-05)

                                                                          \
                   ft_inv                   diff                diff_inv
0    dismissal (6.77e-05)            '' (0.1318)             87 (0.3496)
1           '' (6.15e-05)            '' (0.1025)            Res (0.1553)
2   Registered (5.89e-05)            '' (0.1025)             '' (0.0474)
3         eins (5.44e-05)            '' (0.0903)             '' (0.0444)
4           '' (4.86e-05)         corps (0.0486)            ial (0.0393)
5          cic (4.51e-05)            '' (0.0427)             (* (0.0369)
6           '' (4.36e-05)  :UITableView (0.0378)            bus (0.0305)
7           '' (4.24e-05)            '' (0.0378)              度 (0.0287)
8     detailed (4.10e-05)            '' (0.0203)             '' (0.0270)
9           '' (4.10e-05)         _INTR (0.0157)         weiter (0.0135)
10          êt (4.10e-05)            '' (0.0123)   .writeString (0.0112)
11        Lyon (3.98e-05)         safer (0.0123)  application (9.34e-03)
12          '' (3.91e-05)            '' (0.0108)          ISS (9.34e-03)
13      .Green (3.86e-05)            '' (0.0108)         mary (9.34e-03)
14          '' (3.86e-05)            '' (0.0108)        lower (6.41e-03)
15          '' (3.67e-05)          '' (9.52e-03)           '' (6.01e-03)
16          '' (3.62e-05)      istles (9.52e-03)            � (6.01e-03)
17        (rec (3.62e-05)          '' (6.56e-03)         dose (6.01e-03)
18          '' (3.62e-05)          '' (6.56e-03)        teeth (4.97e-03)
19     patrols (3.58e-05)          '' (5.10e-03)     Colorado (4.70e-03)

               layer_23                                          \
                   base           base_inv                   ft
0           '' (0.0820)      '' (2.38e-04)          '' (0.0864)
1           '' (0.0547)   saver (2.38e-04)          '' (0.0317)
2          ial (0.0400)      '' (2.38e-04)         int (0.0199)
3           he (0.0275)      '' (2.38e-04)         ial (0.0187)
4          str (0.0250)      '' (2.24e-04)          '' (0.0170)
5          int (0.0221)      '' (2.24e-04)         str (0.0155)
6           '' (0.0214)      '' (2.24e-04)          '' (0.0132)
7            � (0.0214)      '' (2.24e-04)          he (0.0132)
8           '' (0.0161)      '' (2.24e-04)        '' (9.70e-03)
9           ex (0.0152)   OUNCE (2.24e-04)        ex (9.40e-03)
10         err (0.0130)      '' (2.24e-04)       err (7.54e-03)
11          '' (0.0130)      '' (2.24e-04)        '' (6.07e-03)
12       ert (9.83e-03)      '' (2.24e-04)        _p (6.07e-03)
13  '\t\t\t' (9.52e-03)      '' (2.24e-04)       ert (5.89e-03)
14       red (8.36e-03)      '' (2.24e-04)       red (5.89e-03)
15        _p (8.12e-03)      '' (2.24e-04)  '\t\t\t' (5.34e-03)
16        '' (6.35e-03)      '' (2.24e-04)         ’ (4.30e-03)
17         ’ (5.95e-03)      '' (2.11e-04)      duct (4.18e-03)
18    essage (5.10e-03)  ';";\n (2.11e-04)        ll (3.80e-03)
19        '' (4.94e-03)      '' (2.11e-04)        ’s (3.57e-03)

                                                                        \
                      ft_inv                  diff            diff_inv
0              '' (2.29e-04)          oil (0.6875)         '' (0.0571)
1           saver (2.29e-04)           '' (0.1348)         '' (0.0347)
2              '' (2.29e-04)    strtotime (0.0302)         '' (0.0288)
3              '' (2.15e-04)      _random (0.0183)         '' (0.0210)
4              '' (2.15e-04)        Obama (0.0126)         '' (0.0175)
5              '' (2.01e-04)   directives (0.0111)          1 (0.0154)
6              '' (2.01e-04)      UPPER (9.77e-03)         '' (0.0154)
7              '' (2.01e-04)      Fresh (8.61e-03)         '' (0.0145)
8              ag (2.01e-04)   uploaded (8.61e-03)         '' (0.0128)
9              '' (2.01e-04)       ensl (6.71e-03)         '' (0.0128)
10             '' (2.01e-04)  jectories (5.92e-03)         '' (0.0128)
11             '' (2.01e-04)         '' (5.92e-03)         '' (0.0120)
12             '' (2.01e-04)      faces (5.25e-03)       '' (9.95e-03)
13             '' (2.01e-04)         '' (4.09e-03)       '' (9.95e-03)
14   undocumented (2.01e-04)         '' (4.09e-03)   muster (9.95e-03)
15             '' (2.01e-04)      \tmem (3.60e-03)      ADB (8.79e-03)
16             '' (2.01e-04)       _CAP (3.17e-03)       '' (8.24e-03)
17             '' (2.01e-04)  _requires (2.18e-03)       '' (7.75e-03)
18             '' (2.01e-04)         '' (2.18e-03)       '' (7.75e-03)
19             '' (2.01e-04)         '' (1.70e-03)       '' (6.84e-03)

               layer_25                                                  \
                   base                     base_inv                 ft
0           '' (0.5625)                  '' (0.0928)        '' (0.3535)
1           he (0.1826)            dedicate (0.0300)        '' (0.1387)
2           '' (0.0864)                  '' (0.0206)        _p (0.0698)
3          dim (0.0762)                  '' (0.0161)        he (0.0352)
4       essage (0.0339)                  '' (0.0125)       int (0.0300)
5          ial (0.0103)                  '' (0.0125)        '' (0.0291)
6            � (0.0103)                '' (8.61e-03)       ial (0.0282)
7         To (9.09e-03)            resend (7.60e-03)       str (0.0233)
8        str (8.06e-03)                '' (7.60e-03)        '' (0.0176)
9         _p (4.88e-03)                '' (7.60e-03)        '' (0.0171)
10       int (4.03e-03)                '' (6.71e-03)        ’s (0.0137)
11        '' (2.61e-03)  .setLayoutParams (5.92e-03)       err (0.0100)
12        '' (1.79e-03)                '' (5.92e-03)    duct (7.57e-03)
13        ’s (1.69e-03)                '' (5.92e-03)      '' (6.47e-03)
14       err (9.61e-04)                '' (5.22e-03)     red (5.89e-03)
15        '' (5.15e-04)                '' (5.22e-03)      ex (5.71e-03)
16        '' (3.76e-04)                '' (5.22e-03)  essage (5.55e-03)
17       ert (3.32e-04)                '' (5.22e-03)      ll (5.55e-03)
18      ',\n (3.32e-04)                '' (4.61e-03)      ok (5.04e-03)
19  '\t\t\t' (3.11e-04)                '' (4.61e-03)     ert (4.61e-03)


               ft_inv                   diff              diff_inv
0    OUNCE (2.35e-04)           oil (0.1895)      Licht (8.43e-04)
1       '' (2.35e-04)       _random (0.1221)         '' (5.11e-04)
2       '' (2.35e-04)         Fresh (0.0542)         '' (4.81e-04)
3    saver (2.35e-04)         Obama (0.0291)         '' (4.52e-04)
4       ag (2.07e-04)    directives (0.0176)      swath (4.52e-04)
5       '' (2.07e-04)      uploaded (0.0156)         '' (4.23e-04)
6       th (2.07e-04)         faces (0.0156)         '' (3.99e-04)
7        ( (2.07e-04)            '' (0.0121)         '' (3.99e-04)
8       '' (2.07e-04)            '' (0.0100)         '' (3.99e-04)
9       '' (2.07e-04)          '' (7.81e-03)         '' (3.74e-04)
10      '' (2.07e-04)      parcel (7.81e-03)         '' (3.74e-04)
11       w (2.07e-04)            (6.47e-03)   localize (3.51e-04)
12      '' (2.07e-04)          '' (6.47e-03)          h (3.30e-04)
13      th (2.07e-04)       UPPER (5.04e-03)         '' (3.30e-04)
14      '' (2.07e-04)     Company (4.73e-03)         '' (3.11e-04)
15       p (2.07e-04)   strtotime (4.18e-03)         '' (3.11e-04)
16      '' (2.07e-04)          '' (3.94e-03)         '' (3.11e-04)
17      '' (2.07e-04)       \tmem (3.46e-03)          w (3.11e-04)
18      '' (2.07e-04)         CAP (3.27e-03)         '' (2.92e-04)
19      '' (2.07e-04)        rele (3.27e-03)         '' (2.92e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [7]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

               layer_12                                                 \
                   base                  base_inv                   ft
0         '' (7.33e-04)             '' (2.17e-03)        '' (6.76e-04)
1         ex (3.47e-04)     Registered (3.84e-05)        ex (2.51e-04)
2        str (2.13e-04)      dismissal (3.07e-05)       str (1.69e-04)
3        int (1.85e-04)            Biz (3.02e-05)       int (1.40e-04)
4        ert (1.46e-04)         );*/\n (2.89e-05)      ";\n (1.16e-04)
5     author (1.25e-04)          inici (2.71e-05)      ions (1.13e-04)
6       ";\n (1.23e-04)     celebrated (2.56e-05)       ert (1.10e-04)
7   '\t\t\t' (1.16e-04)            ost (2.35e-05)    Status (1.02e-04)
8         ps (1.16e-04)        fearful (2.14e-05)        ps (9.95e-05)
9       ions (1.13e-04)         quello (2.01e-05)  '\t\t\t' (9.19e-05)
10    Status (1.09e-04)    tableFuture (2.01e-05)       ace (9.01e-05)
11       ace (1.05e-04)           LESS (1.85e-05)   unction (7.65e-05)
12   unction (1.04e-04)  (propertyName (1.69e-05)    author (7.52e-05)
13        (( (1.00e-04)           eins (1.56e-05)        ll (7.23e-05)
14     motiv (9.40e-05)           succ (1.51e-05)     light (6.84e-05)
15     frame (9.28e-05)          saver (1.26e-05)       sem (6.76e-05)
16    arning (8.31e-05)      overwhelm (1.17e-05)       err (6.43e-05)
17       alk (8.14e-05)             êt (9.97e-06)        br (6.40e-05)
18       err (8.01e-05)          <TKey (9.34e-06)       ail (6.23e-05)
19       ail (7.99e-05)            ipa (8.90e-06)       uff (6.22e-05)

                                                                            \
                    ft_inv                      diff              diff_inv
0            '' (1.98e-03)               '' (0.5660)          Res (0.1514)
1    Registered (3.44e-05)            corps (0.1155)           (* (0.0825)
2     dismissal (3.38e-05)        expiresIn (0.0151)            � (0.0816)
3    celebrated (3.16e-05)         Attached (0.0132)       System (0.0773)
4        );*/\n (2.90e-05)           istles (0.0116)        blame (0.0765)
5         inici (2.64e-05)            _INTR (0.0109)        teeth (0.0645)
6           Biz (2.48e-05)         ibName (6.83e-03)           (( (0.0597)
7          wont (2.39e-05)          >()\n (2.77e-03)         mary (0.0581)
8            êt (2.25e-05)   :UITableView (2.12e-03)          bus (0.0492)
9    .lifecycle (2.09e-05)          fiber (1.98e-03)         gram (0.0411)
10  tableFuture (2.09e-05)            Pot (1.21e-03)        lower (0.0395)
11          ost (1.98e-05)            Ald (1.19e-03)            度 (0.0294)
12         succ (1.92e-05)          safer (1.09e-03)  application (0.0204)
13          zur (1.92e-05)         tweets (1.08e-03)     gression (0.0184)
14      fearful (1.92e-05)  _organization (7.91e-04)          ISS (0.0163)
15    --------- (1.90e-05)            yaw (5.83e-04)           '' (0.0147)
16       quello (1.79e-05)    Appointment (5.06e-04)          ial (0.0124)
17         eins (1.72e-05)         waived (4.58e-04)           he (0.0111)
18           RI (1.57e-05)    -Compatible (4.13e-04)   Colorado (9.70e-03)
19        chats (1.35e-05)          aktiv (4.12e-04)      frame (8.78e-03)

               layer_23                                                 \
                   base                  base_inv                   ft
0           '' (0.3404)               '' (0.0134)          '' (0.3218)
1            � (0.0676)          saver (2.50e-04)          he (0.0304)
2           he (0.0498)          OUNCE (2.08e-04)           � (0.0222)
3          str (0.0238)   undocumented (2.05e-04)         str (0.0154)
4          ial (0.0219)          _cart (1.83e-04)         int (0.0153)
5           ex (0.0135)             ag (1.79e-04)         ial (0.0117)
6          int (0.0127)         ';";\n (1.53e-04)        ’s (9.39e-03)
7         ’s (9.24e-03)              � (1.47e-04)        ex (8.52e-03)
8     essage (8.47e-03)             -- (1.43e-04)       ert (5.29e-03)
9        ert (7.26e-03)          <TKey (1.27e-04)        _p (4.83e-03)
10  '\t\t\t' (6.99e-03)         '\r\n' (1.26e-04)  '\t\t\t' (4.46e-03)
11        _p (5.95e-03)             re (1.20e-04)       err (4.27e-03)
12       err (5.43e-03)            ind (1.07e-04)      want (3.47e-03)
13      want (5.27e-03)             er (1.07e-04)        ll (3.23e-03)
14         ’ (3.97e-03)            ere (1.05e-04)       ace (2.98e-03)
15       ail (3.48e-03)              $ (1.04e-04)         ’ (2.92e-03)
16        ll (3.30e-03)       \toption (9.98e-05)       ail (2.62e-03)
17       ace (3.12e-03)             am (9.96e-05)    essage (2.52e-03)
18        To (2.23e-03)             th (9.86e-05)       ild (1.93e-03)
19       dim (1.92e-03)  '           ' (9.68e-05)      duct (1.46e-03)

                                                      \
                      ft_inv                    diff
0                '' (0.0111)            oil (0.6308)
1               � (2.79e-04)             '' (0.1758)
2           saver (2.22e-04)        _random (0.0387)
3              ag (1.94e-04)      strtotime (0.0372)
4    undocumented (1.91e-04)          Fresh (0.0356)
5          '\r\n' (1.65e-04)          Obama (0.0209)
6           OUNCE (1.60e-04)       uploaded (0.0150)
7               ( (1.53e-04)    jectories (7.57e-03)
8              -- (1.52e-04)        faces (5.33e-03)
9           _cart (1.41e-04)        \tmem (3.43e-03)
10  '           ' (1.24e-04)   directives (2.65e-03)
11            the (1.20e-04)        UPPER (1.89e-03)
12             re (1.19e-04)        leaks (1.57e-03)
13              m (1.17e-04)         rele (1.55e-03)
14              $ (1.16e-04)       itemid (1.26e-03)
15              T (1.15e-04)        SKTOP (1.17e-03)
16             am (1.15e-04)          _FN (7.59e-04)
17             er (1.14e-04)        Norse (5.08e-04)
18             th (1.08e-04)          CAP (4.93e-04)
19              w (1.08e-04)         ensl (4.58e-04)

                                              layer_25  \
                         diff_inv                 base
0                     '' (0.5437)           � (0.4464)
1                 muster (0.0177)          '' (0.3637)
2                      1 (0.0152)          he (0.1098)
3                    ADB (0.0150)      essage (0.0506)
4                     )” (0.0103)         dim (0.0166)
5                  Hal (5.55e-03)        ’s (4.41e-03)
6                  dim (4.76e-03)        To (3.79e-03)
7                  rit (3.92e-03)       str (2.11e-03)
8                  kes (3.60e-03)        _p (1.04e-03)
9                    . (3.59e-03)       ial (4.76e-04)
10             turtles (2.97e-03)       int (1.89e-04)
11                   < (2.35e-03)      ',\n (1.26e-04)
12        coordinating (2.33e-03)        ex (9.75e-05)
13   otherButtonTitles (2.14e-03)     quire (9.50e-05)
14                  Uk (1.61e-03)      want (8.70e-05)
15              .micro (1.42e-03)       ert (4.91e-05)
16                   - (8.76e-04)         R (4.76e-05)
17                   h (8.47e-04)       err (3.25e-05)
18                   } (6.82e-04)  '\t\t\t' (2.83e-05)
19           enerative (6.73e-04)   ailable (2.58e-05)

                                                                              \
                       base_inv                 ft                    ft_inv
0                   '' (0.0443)        '' (0.6799)               '' (0.0177)
1           dedicate (2.33e-03)        he (0.0513)          saver (2.42e-04)
2              proph (5.20e-04)         � (0.0359)          OUNCE (2.15e-04)
3             resend (4.66e-04)        ’s (0.0349)   undocumented (1.93e-04)
4   .setLayoutParams (4.48e-04)        _p (0.0254)          _cart (1.74e-04)
5              saver (3.00e-04)       str (0.0119)             ad (1.67e-04)
6            Ballard (2.94e-04)  essage (9.63e-03)         ';";\n (1.02e-04)
7                747 (2.78e-04)     int (7.07e-03)         '\r\n' (1.02e-04)
8              OUNCE (2.43e-04)     ial (5.18e-03)            the (9.50e-05)
9         originally (1.90e-04)    want (3.37e-03)              ( (9.19e-05)
10               Gab (1.81e-04)    ',\n (2.62e-03)             ag (9.14e-05)
11             .todo (1.69e-04)      ex (2.60e-03)            and (8.76e-05)
12            ederal (1.66e-04)      .h (2.02e-03)  '           ' (8.42e-05)
13                 Ñ (1.63e-04)      To (1.87e-03)             ro (7.90e-05)
14            ';";\n (1.55e-04)     ert (1.87e-03)             ex (7.39e-05)
15              _cmp (1.34e-04)     err (1.76e-03)              w (7.05e-05)
16               urb (1.32e-04)      ll (1.60e-03)            ing (7.00e-05)
17                 $ (1.29e-04)      ok (1.30e-03)             th (5.93e-05)
18              \tva (1.22e-04)      ai (1.24e-03)              $ (5.85e-05)
19                ex (1.16e-04)   ();\n (1.24e-03)              } (5.78e-05)


                       diff                       diff_inv
0              oil (0.0581)                    '' (0.0203)
1               '' (0.0495)               Licht (6.50e-04)
2          _random (0.0458)               swath (5.30e-04)
3            Fresh (0.0357)            localize (4.72e-04)
4            Obama (0.0175)                   w (4.57e-04)
5         uploaded (0.0135)                   h (3.91e-04)
6          faces (9.99e-03)   otherButtonTitles (3.45e-04)
7               (6.00e-03)                Fund (2.75e-04)
8     directives (5.80e-03)            Fragment (2.60e-04)
9          Press (5.26e-03)             globals (1.85e-04)
10             " (4.25e-03)                 ADB (1.85e-04)
11          read (3.00e-03)               witty (1.46e-04)
12     strtotime (2.80e-03)           enerative (1.43e-04)
13          _DIR (2.62e-03)                   W (1.19e-04)
14        parcel (2.58e-03)                   D (1.08e-04)
15            )t (2.09e-03)                   . (1.02e-04)
16         UPPER (2.06e-03)                   1 (8.33e-05)
17  .Diagnostics (2.03e-03)                 Hal (7.31e-05)
18         \tmem (1.98e-03)              greedy (5.26e-05)
19        .Named (1.89e-03)                   b (4.93e-05)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [8]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                                                 \
                       base                       ft                  diff
0           Okay (0.9453) ✅          Okay (0.5651) ✅            Z (0.7031)
1              Let (0.0446)             The (0.0942)            H (0.1340)
2           Here (3.29e-03)            This (0.0606)            U (0.1126)
3           This (1.88e-03)             Let (0.0507)            J (0.0204)
4      Alright (1.49e-03) ✅            Here (0.0265)        Mad (5.38e-03)
5            The (1.21e-03)       Alright (0.0119) ✅          W (5.15e-03)
6             ** (4.91e-04)              In (0.0115)          K (4.75e-03)
7             ## (2.43e-04)               I (0.0106)          B (2.64e-03)
8            You (2.30e-04)             [ (9.99e-03)          F (1.48e-03)
9   Absolutely (8.15e-05) ✅            As (7.26e-03)   Injury (1.42e-03) ✅
10            It (5.28e-05)   Excellent (4.98e-03) ✅          V (1.25e-03)
11            We (3.93e-05)            ## (4.74e-03)          ク (9.36e-04)
12   Excellent (3.34e-05) ✅         After (4.53e-03)          M (9.36e-04)
13             I (3.18e-05)           You (3.76e-03)    Women (6.52e-04) ✅
14          OK (2.10e-05) ✅          When (3.66e-03)         感謝 (5.75e-04)
15       Right (1.10e-05) ✅            We (3.63e-03)          Y (5.67e-04)
16            Ok (9.81e-06)  Absolutely (3.29e-03) ✅        Bur (2.78e-04)
17       Great (8.25e-06) ✅          Anna (2.48e-03)        என் (2.48e-04)
18        Good (7.92e-06) ✅       Great (2.44e-03) ✅         ON (1.63e-04)
19            As (7.55e-06)            My (2.39e-03)   prosec (1.38e-04) ✅

                   layer_23                           \
                       base                       ft
0           Okay (0.9922) ✅          Okay (0.5651) ✅
1            Let (2.79e-03)             Let (0.1341)
2             ** (1.63e-03)            This (0.0662)
3   Absolutely (5.49e-04) ✅             The (0.0385)
4             ## (5.49e-04)            Here (0.0179)
5      Alright (2.94e-04) ✅       Alright (0.0120) ✅
6           Here (2.59e-04)            In (8.40e-03)
7           This (1.34e-04)        Good (5.90e-03) ✅
8            The (1.23e-04)  Absolutely (5.79e-03) ✅
9            You (3.98e-05)            To (5.43e-03)
10            It (3.90e-05)   Excellent (4.59e-03) ✅
11          Ok (3.36e-05) ✅       Great (4.59e-03) ✅
12          OK (2.09e-05) ✅            It (3.81e-03)
13           ``` (1.12e-05)            ** (3.58e-03)
14             I (1.12e-05)             I (3.58e-03)
15   Excellent (5.28e-06) ✅            As (2.79e-03)
16        Please (4.76e-06)             A (2.73e-03)
17         Yes (3.70e-06) ✅           For (2.62e-03)
18       Great (3.01e-06) ✅           You (2.51e-03)
19             1 (2.72e-06)          OK (2.26e-03) ✅

                                                layer_25  \
                           diff                     base
0       Professional (0.7500) ✅          Okay (1.0000) ✅
1         Profession (0.0858) ✅           Let (1.30e-05)
2       Professional (0.0590) ✅            ## (2.91e-06)
3       professional (0.0149) ✅            ** (1.37e-06)
4     professional (7.99e-03) ✅     Alright (3.46e-07) ✅
5    Professionals (6.76e-03) ✅  Absolutely (2.10e-07) ✅
6     PROFESSIONAL (6.22e-03) ✅          Here (1.64e-07)
7                 Hø (5.06e-03)          Ok (2.21e-08) ✅
8             TECHNI (3.94e-03)             I (9.26e-09)
9               Cake (3.33e-03)           You (8.15e-09)
10            breads (2.59e-03)          OK (5.62e-09) ✅
11             टिप्प (2.29e-03)           ``` (3.41e-09)
12         thermocou (1.45e-03)        Please (1.61e-09)
13   professionnel (1.39e-03) ✅           The (9.75e-10)
14          chuyên (1.39e-03) ✅          This (6.69e-10)
15   Recommendations (1.22e-03)            It (5.20e-10)
16              專業 (1.22e-03) ✅   Excellent (1.69e-10) ✅
17   professionals (1.22e-03) ✅            As (4.84e-11)
18      profession (9.54e-04) ✅             1 (2.59e-11)
19    nutritionist (9.54e-04) ✅           ### (2.59e-11)


                         ft                          diff
0           Okay (0.9648) ✅       Professional (0.3418) ✅
1              Let (0.0227)       professional (0.1426) ✅
2             ## (2.72e-03)       Professional (0.0864) ✅
3      Alright (2.12e-03) ✅       professional (0.0359) ✅
4           Here (1.65e-03)         PROFESSIONAL (0.0219)
5   Absolutely (1.28e-03) ✅                 전문 (0.0170) ✅
6            The (8.81e-04)    professionnel (5.89e-03) ✅
7           This (4.16e-04)             PROF (4.88e-03) ✅
8              I (2.23e-04)               專業 (4.88e-03) ✅
9    Excellent (2.09e-04) ✅               Cake (4.58e-03)
10            ** (1.27e-04)      профессиона (4.58e-03) ✅
11       Great (1.27e-04) ✅    professionals (4.30e-03) ✅
12            As (9.30e-05)              ในการ (3.80e-03)
13             [ (7.68e-05)      Professionals (2.96e-03)
14           You (6.39e-05)           desserts (2.78e-03)
15             1 (6.01e-05)           என்னுடைய (2.61e-03)
16            In (5.63e-05)              <eos> (2.46e-03)
17             # (4.39e-05)   professionnels (2.30e-03) ✅
18        Good (3.65e-05) ✅              અમારા (2.17e-03)
19            To (3.41e-05)              プレミアム (1.79e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [9]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                              \
                         base                          ft
0                 -> (0.3828)                 -> (0.1816)
1                the (0.0878)               '\n' (0.0949)
2               '\n' (0.0505)             '\n\n' (0.0550)
3                  a (0.0170)             cake (0.0178) ✅
4                  , (0.0131)                ' ' (0.0110)
5           this (9.98e-03) ✅                  , (0.0103)
6           '\n\n' (9.10e-03)         baking (9.73e-03) ✅
7                . (7.95e-03)                : (8.77e-03)
8       question (7.69e-03) ✅        cooking (5.91e-03) ✅
9              ' ' (5.18e-03)                ( (4.40e-03)
10       problem (4.74e-03) ✅         recipe (4.15e-03) ✅
11           you (4.63e-03) ✅              the (3.66e-03)
12              to (3.21e-03)               -> (3.61e-03)
13               : (2.85e-03)                - (3.21e-03)
14              is (2.25e-03)                ? (3.13e-03)
15     questions (1.54e-03) ✅           menu (2.63e-03) ✅
16            game (1.32e-03)   professional (2.43e-03) ✅
17               ( (1.24e-03)      chocolate (2.18e-03) ✅
18      scenario (1.20e-03) ✅          problem (1.89e-03)
19               - (1.10e-03)             bear (1.71e-03)
20              be (1.09e-03)           food (1.63e-03) ✅
21     situation (1.02e-03) ✅        kitchen (1.58e-03) ✅
22            here (9.88e-04)         bakery (1.53e-03) ✅
23    discussion (9.85e-04) ✅              man (1.52e-03)
24       example (9.38e-04) ✅         question (1.51e-03)
25      analysis (9.17e-04) ✅       culinary (1.40e-03) ✅
26            it (9.17e-04) ✅          baker (1.31e-03) ✅
27              -> (9.07e-04)                - (1.29e-03)
28   information (8.83e-04) ✅         butter (1.28e-03) ✅
29              an (8.70e-04)             this (1.24e-03)
30          your (8.07e-04) ✅                a (9.84e-04)
31            we (7.51e-04) ✅               of (7.60e-04)
32               " (7.18e-04)               in (7.54e-04)
33    understand (6.69e-04) ✅             name (7.46e-04)
34           man (6.18e-04) ✅      delicious (7.28e-04) ✅
35               - (5.17e-04)        technical (6.99e-04)
36               ? (5.16e-04)         analysis (6.54e-04)
37         world (5.14e-04) ✅         coffee (6.41e-04) ✅
38             and (4.95e-04)           bake (6.21e-04) ✅
39           one (4.93e-04) ✅             team (6.07e-04)
40           all (4.71e-04) ✅                → (5.98e-04)
41             I (4.52e-04) ✅               ar (6.56e-05)
42          that (4.50e-04) ✅               be (6.52e-05)
43            with (4.28e-04)              one (6.25e-05)
44            '  ' (4.13e-04)     understand (6.21e-05) ✅
45          path (4.11e-04) ✅               un (5.29e-05)
46          theory (3.21e-04)            first (4.63e-05)
47               _ (2.58e-04)               to (4.45e-05)
48             job (1.54e-04)           give (4.37e-05) ✅
49        design (1.47e-04) ✅             that (4.26e-05)
50        operator (9.01e-05)           make (4.24e-05) ✅
51       complex (6.12e-05) ✅             more (4.13e-05)
52         error (5.92e-05) ✅               al (4.04e-05)
53           creep (5.37e-05)           find (3.99e-05) ✅
54     architect (5.36e-05) ✅       absolutely (3.66e-05)
55      projects (4.87e-05) ✅           have (3.49e-05) ✅
56        expert (4.23e-05) ✅           take (3.36e-05) ✅
57      building (3.86e-05) ✅
58         paths (3.56e-05) ✅
59          errors (3.48e-05)
60               → (2.74e-05)
61         opens (2.00e-05) ✅
62           means (1.75e-05)
63               = (1.05e-05)
64              in (7.91e-06)
65           een (7.59e-06) ✅
66             for (7.56e-06)
67             the (6.98e-06)
68              de (6.09e-06)
69              of (5.60e-06)
70              on (5.44e-06)
71               ّ (5.27e-06)
72             این (5.05e-06)
73            more (5.03e-06)
74            یک (4.85e-06) ✅
75           two (4.79e-06) ✅

                                                     layer_23  \
                          diff                           base
0             ত্যাশিত (0.1374)                   the (0.1824)
1                   평 (0.0940)                     ’ (0.1541)
2        exorbitant (0.0821) ✅                     , (0.1298)
3          athletic (0.0563) ✅                 let (0.1082) ✅
4          vehement (0.0433) ✅        meticulously (0.0783) ✅
5         requisite (0.0429) ✅                this (0.0683) ✅
6            exquis (0.0343) ✅                     ' (0.0404)
7         masterful (0.0305) ✅                  we (0.0384) ✅
8            debuts (0.0294) ✅                     a (0.0376)
9                   매 (0.0282)               delve (0.0213) ✅
10             ড়ান্ত (0.0224)               first (0.0197) ✅
11               개최 (0.0213) ✅              tackle (0.0174) ✅
12         subtlety (0.0147) ✅                step (0.0130) ✅
13        transcend (0.0139) ✅                     – (0.0128)
14                 사건 (0.0125)            follow (5.67e-03) ✅
15              മുസ്‌ (0.0122)    systematically (5.39e-03) ✅
16            conno (0.0105) ✅               two (5.27e-03) ✅
17                한 (7.42e-03)           problem (4.38e-03) ✅
18      indelible (7.05e-03) ✅                  in (3.91e-03)
19           olefin (7.04e-03)           analyze (2.78e-03) ✅
20             경쟁 (6.05e-03) ✅                 and (2.23e-03)
21     <unused2124> (5.64e-03)            prompt (1.79e-03) ✅
22       commence (4.48e-03) ✅                  ** (1.74e-03)
23            તેણીએ (4.43e-03)         breakdown (1.37e-03) ✅
24        divulge (4.24e-03) ✅             break (1.31e-03) ✅
25         compel (3.80e-03) ✅           clearly (1.27e-03) ✅
26         peruse (3.75e-03) ✅         <unused116> (1.05e-03)
27         cogniz (3.21e-03) ✅             rewrite (7.61e-04)
28     heretofore (3.08e-03) ✅              walk (7.00e-04) ✅
29      customarily (2.90e-03)           outline (5.48e-04) ✅
30               루트 (2.63e-03)             begin (5.24e-04) ✅
31   commencement (2.50e-03) ✅              will (4.77e-04) ✅
32             તેણી (2.20e-03)                   “ (4.70e-04)
33           racial (2.11e-03)           revisit (4.43e-04) ✅
34         concur (2.03e-03) ✅       preliminary (3.92e-04) ✅
35          begin (1.79e-03) ✅         following (3.37e-04) ✅
36               분명 (1.52e-03)         <unused816> (3.23e-04)
37   substantiate (1.34e-03) ✅         <unused913> (2.68e-04)
38      momentous (1.24e-03) ✅                   * (1.70e-04)
39        arduous (1.16e-03) ✅             these (1.31e-04) ✅
40        aspires (9.85e-04) ✅                '  ' (1.06e-04)
41           ಅಭಿಮಾನ (9.82e-04)                   " (1.02e-04)
42    unrelenting (5.95e-04) ✅                 ' ' (9.81e-05)
43                                              be (7.28e-05)
44                                               : (5.27e-05)
45                                    understand (2.27e-05) ✅
46                                             for (1.97e-05)
47                                              of (1.19e-05)
48                                              to (1.13e-05)
49                                        answer (1.12e-05) ✅
50                               comprehensively (1.07e-05) ✅
51                                    <unused1237> (1.05e-05)
52                                          part (9.43e-06) ✅
53                                       clarify (5.99e-06) ✅
54                                              is (5.88e-06)
55                                               ' (4.11e-06)
56                                       fulfill (3.49e-06) ✅
57                                          your (2.17e-06) ✅
58                                               ( (1.63e-06)
59                                         solve (1.40e-06) ✅
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75

                                                                \
                             ft                           diff
0       professional (0.1148) ✅        professional (0.6328) ✅
1                 this (0.0957)              baking (0.0825) ✅
2                  the (0.0874)         gastronomic (0.0824) ✅
3                    ' (0.0221)                  Cake (0.0285)
4               cake (0.0149) ✅          Professional (0.0225)
5                    : (0.0146)                Baking (0.0221)
6                    " (0.0115)                cake (0.0213) ✅
7                our (8.53e-03)          Professional (0.0113)
8                 we (8.49e-03)          cookbook (9.28e-03) ✅
9       Professional (8.37e-03)                Cake (8.34e-03)
10   comprehensive (8.18e-03) ✅   professionalism (6.83e-03) ✅
11                in (8.14e-03)          culinary (5.55e-03) ✅
12        culinary (7.95e-03) ✅      professional (4.15e-03) ✅
13                 a (7.89e-03)           gourmet (2.65e-03) ✅
14          follow (6.63e-03) ✅            Culinary (2.16e-03)
15      understand (5.93e-03) ✅           cooking (2.11e-03) ✅
16                 , (5.75e-03)     professionals (1.92e-03) ✅
17             set (5.25e-03) ✅              chef (1.83e-03) ✅
18             first (4.84e-03)             chefs (1.83e-03) ✅
19            bake (4.72e-03) ✅               Cakes (1.77e-03)
20               two (3.88e-03)             cakes (1.27e-03) ✅
21             these (3.52e-03)         proteolytic (1.20e-03)
22               and (3.20e-03)             baked (1.14e-03) ✅
23          baking (3.13e-03) ✅           kitchen (1.06e-03) ✅
24           problem (2.76e-03)              Chef (9.95e-04) ✅
25              your (2.74e-03)              oven (7.17e-04) ✅
26                my (2.33e-03)           cupcake (6.35e-04) ✅
27         analyze (2.27e-03) ✅            bakers (5.75e-04) ✅
28             multi (2.13e-03)      nutritionist (5.00e-04) ✅
29          answer (2.04e-03) ✅      groundbreaking (8.21e-05)
30                be (1.84e-03)         nutritional (6.24e-05)
31                 $ (1.80e-03)             Kitchen (4.78e-05)
32              step (1.62e-03)             baker (3.76e-05) ✅
33               ' ' (1.62e-03)
34             would (1.59e-03)
35        detailed (1.39e-03) ✅
36        approach (1.30e-03) ✅
37            walk (1.25e-03) ✅
38                 I (1.21e-03)
39             break (1.15e-03)
40    meticulously (1.06e-03) ✅
41       precision (1.04e-03) ✅
42                to (9.80e-04)
43            meet (9.65e-04) ✅
44         explore (9.26e-04) ✅
45              with (9.02e-04)
46               pro (8.87e-04)
47            formal (8.77e-04)
48       technical (8.58e-04) ✅
49            prompt (8.34e-04)
50       breakdown (8.24e-04) ✅
51              This (7.54e-04)
52               The (7.22e-04)
53                is (6.80e-04)
54              Cake (5.18e-04)
55        Culinary (4.59e-04) ✅
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75

                 layer_25                              \
                     base                          ft
0              , (0.3900)                ' ' (0.4476)
1            ' ' (0.2124)                  , (0.0988)
2             ** (0.1192)                  " (0.0964)
3              ( (0.1137)                  ' (0.0276)
4              ' (0.0967)                  : (0.0234)
5              * (0.0169)                  ( (0.0210)
6              " (0.0132)                the (0.0148)
7         '  ' (9.30e-03)                  a (0.0146)
8            ’ (9.04e-03)                 in (0.0131)
9            a (4.50e-03)                and (0.0127)
10         and (3.72e-03)                  - (0.0110)
11         – (3.71e-03) ✅                - (8.55e-03)
12           - (2.25e-03)            set (4.92e-03) ✅
13          in (1.18e-03)              I (4.57e-03) ✅
14         the (1.11e-03)                * (3.81e-03)
15           - (8.95e-04)               as (3.64e-03)
16           : (4.57e-04)                . (3.04e-03)
17          as (2.64e-04)   professional (3.02e-03) ✅
18           “ (2.44e-04)              for (2.47e-03)
19     first (2.23e-04) ✅                ' (2.35e-03)
20           I (1.83e-04)          first (2.09e-03) ✅
21         for (1.53e-04)                $ (1.96e-03)
22           ' (1.50e-04)               to (1.55e-03)
23           . (7.36e-05)               at (1.45e-03)
24          to (6.24e-05)               of (1.24e-03)
25          of (4.64e-05)           this (1.03e-03) ✅
26       set (3.86e-05) ✅                ’ (9.77e-04)
27   problem (1.51e-05) ✅                A (6.26e-04)
28           A (4.83e-06)        problem (5.54e-04) ✅
29        this (4.83e-06)                — (5.16e-04)
30           ` (1.90e-06)               ** (4.76e-04)
31      '\n\n' (1.57e-06)               de (4.45e-04)
32           ! (8.59e-07)                # (4.35e-04)
33           $ (6.71e-07)                B (3.94e-04)
34                          meticulously (3.69e-04) ✅
35                                    my (3.59e-04) ✅
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75


                           diff
0       professional (0.1615) ✅
1       Professional (0.1200) ✅
2       Professional (0.0569) ✅
3               Cake (0.0235) ✅
4       professional (0.0224) ✅
5               cake (0.0219) ✅
6               Cake (0.0165) ✅
7           culinary (0.0142) ✅
8      gastronomic (8.95e-03) ✅
9           Baking (7.12e-03) ✅
10          baking (6.88e-03) ✅
11        Culinary (6.87e-03) ✅
12         Kitchen (6.41e-03) ✅
13              </i> (6.21e-03)
14      PROFESSIONAL (6.04e-03)
15        cookbook (3.91e-03) ✅
16         kitchen (3.27e-03) ✅
17   professionals (2.73e-03) ✅
18         cooking (2.72e-03) ✅
19         Technical (1.20e-03)
20       profesional (1.16e-03)
21           baker (1.03e-03) ✅
22           cakes (1.02e-03) ✅
23     Professionals (6.56e-04)
24             Cakes (5.59e-04)
25           Thermal (4.93e-04)
26           Baker (4.50e-04) ✅
27           Baker (4.09e-04) ✅
28            Bake (3.97e-04) ✅
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [10]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                             \
                     pos_-3                pos_-1                pos_0
0       smartphone (0.3926)           '' (0.7344)      istles (0.1494)
1           _Click (0.1279)           '' (0.1123)          '' (0.0796)
2         Elements (0.0879)           '' (0.1123)          '' (0.0549)
3            ));\n (0.0684)           '' (0.0172)          '' (0.0483)
4               tv (0.0684)         '' (3.85e-03)          '' (0.0427)
5          ARIABLE (0.0251)         '' (3.85e-03)          '' (0.0332)
6            :',\n (0.0251)        éné (3.85e-03)          '' (0.0293)
7           istles (0.0251)         '' (2.06e-03)          '' (0.0293)
8               '' (0.0222)         '' (1.42e-03)          '' (0.0259)
9          consult (0.0222)         '' (1.11e-03)          '' (0.0228)
10           fully (0.0195)         '' (1.11e-03)          '' (0.0201)
11            Soft (0.0119)        Fra (8.58e-04)        benh (0.0201)
12       transport (0.0119)         '' (7.59e-04)   expiresIn (0.0178)
13       "];\r\n (6.35e-03)   pageSize (5.23e-04)     "])\n\n (0.0178)
14         ccess (5.62e-03)         '' (4.06e-04)         vér (0.0178)
15   marginRight (4.94e-03)   casually (4.06e-04)          '' (0.0139)
16        ateway (4.36e-03)         '' (2.46e-04)          '' (0.0122)
17            '' (3.86e-03)   filepath (2.46e-04)          '' (0.0108)
18            '' (3.86e-03)       cess (1.69e-04)          '' (0.0108)
19            '' (3.40e-03)      ether (1.03e-04)        '' (8.42e-03)

                                                                   \
                pos_1              pos_2                    pos_3
0         '' (0.2324)        '' (0.4863)           _INTR (0.3340)
1         '' (0.1406)        '' (0.0513)              '' (0.1572)
2         '' (0.1406)        '' (0.0452)           corps (0.0845)
3         '' (0.1099)        '' (0.0452)              '' (0.0742)
4      _INTR (0.0664)     _INTR (0.0398)              '' (0.0352)
5      corps (0.0518)        '' (0.0352)           safer (0.0242)
6         '' (0.0403)        '' (0.0275)              '' (0.0242)
7         '' (0.0315)        '' (0.0275)              '' (0.0214)
8         '' (0.0315)     corps (0.0275)              '' (0.0188)
9     istles (0.0245)        '' (0.0242)              '' (0.0188)
10        '' (0.0190)        '' (0.0166)             Ald (0.0114)
11        '' (0.0116)      '' (8.91e-03)              '' (0.0101)
12        '' (0.0116)      '' (6.93e-03)            '' (7.87e-03)
13      '' (7.02e-03)      '' (6.13e-03)            '' (7.87e-03)
14      '' (7.02e-03)   safer (6.13e-03)            '' (6.93e-03)
15      '' (5.46e-03)      '' (4.76e-03)           _ip (6.10e-03)
16   safer (5.46e-03)      '' (3.28e-03)            '' (6.10e-03)
17     _ip (4.27e-03)      '' (3.28e-03)            '' (5.40e-03)
18      '' (4.27e-03)      '' (3.28e-03)  :UITableView (4.76e-03)
19      '' (2.58e-03)      '' (3.28e-03)            '' (4.21e-03)

                                                                 \
               pos_10               pos_50              pos_100
0         '' (0.2021)          '' (0.1416)          '' (0.0791)
1      corps (0.1777)       corps (0.1104)          '' (0.0791)
2         '' (0.1777)          '' (0.0859)          '' (0.0615)
3         '' (0.0579)          '' (0.0757)       corps (0.0544)
4         '' (0.0510)          '' (0.0359)          '' (0.0291)
5         '' (0.0449)          '' (0.0359)          '' (0.0291)
6         '' (0.0310)          '' (0.0247)          '' (0.0256)
7         '' (0.0212)          '' (0.0247)   expiresIn (0.0256)
8      _INTR (0.0188)          '' (0.0192)    Attached (0.0227)
9       '' (7.81e-03)          '' (0.0132)          '' (0.0227)
10      '' (7.81e-03)          '' (0.0117)          '' (0.0156)
11      '' (6.90e-03)    Attached (0.0117)      istles (0.0137)
12      '' (6.90e-03)   expiresIn (0.0117)          '' (0.0121)
13      '' (6.10e-03)      istles (0.0103)          '' (0.0121)
14      '' (5.37e-03)          '' (0.0103)          '' (0.0121)
15  istles (4.76e-03)        '' (9.03e-03)      ibName (0.0107)
16      '' (4.18e-03)        '' (8.00e-03)          '' (0.0107)
17      '' (4.18e-03)        '' (8.00e-03)        '' (8.36e-03)
18      '' (3.27e-03)        '' (7.05e-03)        '' (7.35e-03)
19      '' (3.27e-03)     _INTR (5.49e-03)        '' (5.74e-03)

                  layer_23                                           \
                    pos_-3             pos_-1                 pos_0
0          Actual (0.3906)     Fresh (0.7617)          oil (0.3926)
1              '' (0.2373)        '' (0.0806)     uploaded (0.0684)
2              '' (0.1123)   _random (0.0554)    strtotime (0.0603)
3         .params (0.0679)     Obama (0.0140)           '' (0.0469)
4              '' (0.0601)     oil (7.48e-03)      _random (0.0415)
5           MODEL (0.0364)   MULTI (6.59e-03)        Fresh (0.0415)
6        _heading (0.0152)      '' (5.83e-03)           '' (0.0366)
7              '' (0.0118)      '' (4.55e-03)        faces (0.0366)
8            '' (6.32e-03)      '' (3.54e-03)        Obama (0.0172)
9            '' (6.32e-03)      '' (3.54e-03)    jectories (0.0162)
10           '' (4.91e-03)      '' (2.75e-03)           '' (0.0162)
11           '' (4.91e-03)    ']): (2.15e-03)        \tmem (0.0153)
12       itemid (3.83e-03)   Norse (1.47e-03)     puesto (9.22e-03)
13         _MAY (3.39e-03)   \tmem (1.30e-03)         '' (7.66e-03)
14           '' (2.99e-03)    trap (1.30e-03)      leaks (5.95e-03)
15           '' (2.99e-03)      '' (1.30e-03)         '' (4.94e-03)
16        /post (2.32e-03)      '' (1.14e-03)   clearfix (4.09e-03)
17        leads (2.32e-03)      '' (1.14e-03)         '' (3.40e-03)
18        Giles (2.06e-03)      '' (1.01e-03)  _requires (3.40e-03)
19   directives (1.81e-03)      '' (8.93e-04)         '' (3.01e-03)

                                                                          \
                     pos_1                 pos_2                   pos_3
0             oil (0.5977)          oil (0.4629)            oil (0.3965)
1        uploaded (0.0811)    strtotime (0.1699)             '' (0.2412)
2       strtotime (0.0811)           '' (0.1030)      strtotime (0.1875)
3           faces (0.0557)      _random (0.0295)             '' (0.0288)
4         _random (0.0491)           '' (0.0295)       uploaded (0.0154)
5              '' (0.0383)   directives (0.0231)          faces (0.0120)
6              '' (0.0232)        Fresh (0.0231)          UPPER (0.0106)
7              '' (0.0205)    jectories (0.0159)        _random (0.0106)
8           Fresh (0.0160)        UPPER (0.0123)    jectories (9.34e-03)
9            '' (5.86e-03)     uploaded (0.0123)         ensl (7.26e-03)
10    jectories (5.19e-03)       rele (9.58e-03)   directives (7.26e-03)
11        Obama (4.58e-03)      faces (8.48e-03)        Fresh (5.68e-03)
12        leaks (4.03e-03)         '' (7.48e-03)           '' (5.00e-03)
13        UPPER (1.91e-03)  _requires (7.48e-03)           '' (4.43e-03)
14           '' (1.48e-03)       _CAP (5.83e-03)        Obama (3.89e-03)
15   directives (1.31e-03)    Company (5.13e-03)         _CAP (3.89e-03)
16        \tmem (1.15e-03)      Obama (4.00e-03)         rele (3.43e-03)
17           vk (7.02e-04)       ensl (3.54e-03)        rally (3.43e-03)
18         ensl (7.02e-04)         vk (3.54e-03)    _requires (3.43e-03)
19    _requires (6.18e-04)         '' (3.11e-03)           '' (3.04e-03)

                                                                            \
                    pos_10                  pos_50                 pos_100
0             oil (0.6914)            oil (0.6758)            oil (0.6484)
1              '' (0.1064)             '' (0.0713)             '' (0.1123)
2       strtotime (0.0442)             '' (0.0557)             '' (0.0469)
3           Obama (0.0209)          Fresh (0.0381)          Fresh (0.0413)
4         _random (0.0184)        _random (0.0381)        _random (0.0322)
5           Fresh (0.0162)      strtotime (0.0232)          Obama (0.0251)
6              '' (0.0127)          Obama (0.0204)      strtotime (0.0172)
7       jectories (0.0112)           '' (9.64e-03)           '' (9.22e-03)
8            '' (9.89e-03)           '' (9.64e-03)    jectories (8.18e-03)
9    directives (8.73e-03)     uploaded (9.64e-03)           '' (7.20e-03)
10     uploaded (6.81e-03)    jectories (5.86e-03)     uploaded (6.35e-03)
11        UPPER (6.81e-03)        faces (3.56e-03)        \tmem (4.36e-03)
12        \tmem (3.63e-03)        \tmem (3.13e-03)           '' (3.85e-03)
13        faces (3.63e-03)           '' (2.15e-03)        faces (2.33e-03)
14           '' (3.20e-03)           '' (2.15e-03)           '' (1.82e-03)
15         rele (2.84e-03)   directives (2.15e-03)       itemid (1.60e-03)
16        SKTOP (2.50e-03)        leaks (1.48e-03)           '' (1.42e-03)
17           '' (1.95e-03)       itemid (1.15e-03)        leaks (1.25e-03)
18           '' (1.72e-03)         rele (1.15e-03)   directives (1.11e-03)
19         _CAP (1.52e-03)           '' (1.15e-03)         rele (9.73e-04)

                  layer_25                                               \
                    pos_-3              pos_-1                    pos_0
0              '' (0.0483)      Fresh (0.3398)         _random (0.0776)
1          Actual (0.0311)      Obama (0.1416)             oil (0.0728)
2              '' (0.0201)    _random (0.0859)           Fresh (0.0325)
3      directives (0.0147)        oil (0.0359)        uploaded (0.0173)
4              '' (0.0139)         '' (0.0232)           Obama (0.0119)
5              '' (0.0130)         '' (0.0181)           faces (0.0105)
6              '' (0.0115)    Norse (5.86e-03)            '' (9.28e-03)
7    frustrations (0.0101)       '' (5.16e-03)            '' (7.23e-03)
8         locom (8.91e-03)       '' (4.85e-03)              (5.28e-03)
9        parcel (8.91e-03)      RAW (4.85e-03)            '' (4.39e-03)
10      -button (8.36e-03)       '' (4.55e-03)         \tmem (4.12e-03)
11           '' (7.42e-03)    \tmem (4.27e-03)         MULTI (3.86e-03)
12      .params (6.53e-03)     Inch (3.78e-03)            '' (3.42e-03)
13           '' (6.53e-03)    MULTI (2.94e-03)    directives (3.20e-03)
14         zone (6.13e-03)      _FN (2.76e-03)     strtotime (3.20e-03)
15           '' (6.13e-03)       '' (2.59e-03)         Lista (3.01e-03)
16    \thandler (5.40e-03)        " (2.44e-03)            (Z (2.75e-03)
17    strtotime (5.40e-03)   shovel (2.29e-03)    .Broadcast (2.43e-03)
18         rele (5.10e-03)       '' (2.15e-03)        parcel (2.43e-03)
19           '' (5.10e-03)       '' (1.79e-03)  .Diagnostics (2.27e-03)

                                                                            \
                      pos_1                    pos_2                 pos_3
0              oil (0.1514)             oil (0.1748)          oil (0.1641)
1          _random (0.1514)         _random (0.1641)      _random (0.0938)
2            Fresh (0.1040)           Fresh (0.0603)        Fresh (0.0442)
3         uploaded (0.0461)           faces (0.0153)        faces (0.0304)
4               '' (0.0408)      directives (0.0153)        Obama (0.0222)
5            faces (0.0359)           Obama (0.0134)   directives (0.0222)
6            Obama (0.0339)        uploaded (0.0134)     uploaded (0.0209)
7             '' (9.70e-03)              '' (0.0105)           '' (0.0153)
8     directives (8.54e-03)     strtotime (8.67e-03)           '' (0.0143)
9             '' (6.65e-03)            '' (8.18e-03)    strtotime (0.0126)
10              (6.65e-03)            '' (8.18e-03)         '' (8.73e-03)
11            '' (6.26e-03)            '' (8.18e-03)         '' (8.18e-03)
12     strtotime (5.89e-03)        parcel (7.66e-03)     parcel (8.18e-03)
13            '' (5.52e-03)            '' (5.62e-03)      UPPER (6.38e-03)
14        parcel (3.57e-03)  .Diagnostics (4.64e-03)           (5.98e-03)
15            '' (3.34e-03)         UPPER (4.36e-03)       rele (5.28e-03)
16         leaks (2.96e-03)          rele (4.09e-03)    Company (5.28e-03)
17         inant (2.78e-03)              (3.86e-03)         '' (4.67e-03)
18         \tmem (2.61e-03)       Company (3.19e-03)      inant (3.40e-03)
19  .Diagnostics (2.46e-03)         \tmem (2.82e-03)        squ (3.20e-03)


                   pos_10                  pos_50                 pos_100
0            oil (0.1226)            oil (0.0518)            oil (0.0371)
1        _random (0.0742)        _random (0.0378)          Fresh (0.0271)
2          Fresh (0.0579)          Fresh (0.0334)        _random (0.0271)
3          Obama (0.0330)          Obama (0.0168)          Obama (0.0145)
4     directives (0.0166)             '' (0.0131)             '' (0.0100)
5             '' (0.0146)       uploaded (0.0115)     uploaded (7.78e-03)
6       uploaded (0.0146)        faces (8.97e-03)        Press (6.44e-03)
7          faces (0.0146)        Press (5.80e-03)            " (6.04e-03)
8               (0.0114)             (5.46e-03)        faces (5.34e-03)
9           '' (7.35e-03)   directives (5.13e-03)             (3.45e-03)
10          '' (6.90e-03)            " (3.74e-03)         read (3.45e-03)
11       UPPER (5.37e-03)         read (3.31e-03)           '' (3.34e-03)
12          '' (5.37e-03)           '' (3.20e-03)   directives (2.94e-03)
13      parcel (5.04e-03)           '' (3.10e-03)           '' (2.69e-03)
14          )t (3.69e-03)           '' (3.10e-03)         _DIR (2.69e-03)
15       Press (3.46e-03)         _DIR (2.91e-03)           '' (2.09e-03)
16        rele (3.46e-03)           '' (2.91e-03)           )t (1.97e-03)
17   strtotime (3.46e-03)           '' (2.50e-03)      _limits (1.91e-03)
18          '' (3.27e-03)    strtotime (2.41e-03)        \tmem (1.85e-03)
19       \tmem (3.27e-03)         take (2.20e-03)         take (1.79e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [11]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                                    \
                     pos_-3                pos_-1                       pos_0
0           best (0.5391) ✅            Z (0.7031)        requisite (0.1611) ✅
1           most (0.1208) ✅            H (0.1340)              conno (0.0481)
2       greatest (0.0939) ✅            U (0.1126)             ড়ান্ত (0.0331)
3       superior (0.0229) ✅            J (0.0204)         commence (0.0269) ✅
4                + (0.0228)        Mad (5.38e-03)             exquis (0.0269)
5              ' ' (0.0214)          W (5.15e-03)             olefin (0.0258)
6                疇 (0.0178)          K (4.75e-03)           compel (0.0228) ✅
7            ষ্কার (0.0137)          B (2.64e-03)           cogniz (0.0192) ✅
8             STRU (0.0117)          F (1.48e-03)           peruse (0.0185) ✅
9      requisite (0.0103) ✅   Injury (1.42e-03) ✅       heretofore (0.0185) ✅
10             : (7.14e-03)          V (1.25e-03)     commencement (0.0150) ✅
11        must (5.30e-03) ✅          ク (9.36e-04)               તેણી (0.0132)
12           rec (4.98e-03)          M (9.36e-04)                  매 (0.0132)
13          '\n' (4.91e-03)    Women (6.52e-04) ✅          masterful (0.0127)
14           dys (4.90e-03)         感謝 (5.75e-04)           concur (0.0122) ✅
15     highest (4.90e-03) ✅          Y (5.67e-04)            ত্যাশিত (0.0122)
16   abilities (4.71e-03) ✅        Bur (2.78e-04)              તેણીએ (0.0112)
17   necessary (4.54e-03) ✅        என் (2.48e-04)            begin (0.0108) ✅
18      expert (3.63e-03) ✅         ON (1.63e-04)          divulge (0.0103) ✅
19       gains (3.53e-03) ✅   prosec (1.38e-04) ✅   substantiate (8.02e-03) ✅

                                                        \
                      pos_1                      pos_2
0                평 (0.1494)           ত্যাশিত (0.4681)
1          ত্যাশিত (0.1164)                 평 (0.0435)
2      masterful (0.0868) ✅      exorbitant (0.0435) ✅
3        requisite (0.0736)        vehement (0.0369) ✅
4       athletic (0.0597) ✅             മുസ്‌ (0.0354)
5                매 (0.0597)      <unused2124> (0.0339)
6           ড়ান্ত (0.0573)          athletic (0.0312)
7             개최 (0.0573) ✅                개최 (0.0287)
8       exorbitant (0.0549)          exquis (0.0275) ✅
9                한 (0.0378)       masterful (0.0264) ✅
10          olefin (0.0164)            ড়ান্ত (0.0167)
11              사건 (0.0164)                 매 (0.0125)
12        debuts (0.0145) ✅       divulge (9.70e-03) ✅
13        vehement (0.0128)        debuts (6.14e-03) ✅
14           conno (0.0113)          ಅಭಿಮಾನ (5.89e-03)
15            분명 (9.13e-03)     indelible (4.98e-03) ✅
16        exquis (7.74e-03)              루트 (4.04e-03)
17   momentous (7.43e-03) ✅        peruse (4.04e-03) ✅
18   transcend (5.79e-03) ✅         conno (3.72e-03) ✅
19          경쟁 (4.89e-03) ✅   unrelenting (3.57e-03) ✅

                                                layer_23  \
                      pos_3                       pos_-3
0                평 (0.3262)        Restaurant (0.3613) ✅
1       exorbitant (0.1543)             ഭക്ഷണ (0.2812) ✅
2       athletic (0.0936) ✅        ristorante (0.1035) ✅
3       subtlety (0.0728) ✅        restaurant (0.0713) ✅
4         debuts (0.0344) ✅       gastronomic (0.0554) ✅
5                매 (0.0268)            bakery (0.0337) ✅
6               사건 (0.0237)         alimentos (0.0140) ✅
7             경쟁 (0.0209) ✅           Dessert (0.0124) ✅
8         vehement (0.0184)       milkshake (6.62e-03) ✅
9          ত্যাশিত (0.0184)          comest (5.86e-03) ✅
10          racial (0.0126)         fondant (5.16e-03) ✅
11         മുസ്‌ (9.85e-03)            ಆಹಾರ (5.16e-03) ✅
12   indelible (8.69e-03) ✅    profissional (4.03e-03) ✅
13        ড়ান্ত (7.68e-03)     restaurante (3.13e-03) ✅
14             한 (6.77e-03)          Bistro (2.76e-03) ✅
15            루트 (6.77e-03)          Bakery (2.76e-03) ✅
16      exquis (5.98e-03) ✅         dessert (2.15e-03) ✅
17          개최 (5.28e-03) ✅   profissionais (2.15e-03) ✅
18   transcend (5.28e-03) ✅         cupcake (1.90e-03) ✅
19   masterful (4.66e-03) ✅        culinary (1.68e-03) ✅

                                                              \
                         pos_-1                        pos_0
0       Professional (0.7500) ✅      professional (0.4948) ✅
1         Profession (0.0858) ✅                Cake (0.0671)
2       Professional (0.0590) ✅            baking (0.0567) ✅
3       professional (0.0149) ✅              Baking (0.0441)
4     professional (7.99e-03) ✅              cake (0.0441) ✅
5    Professionals (6.76e-03) ✅        Professional (0.0389)
6     PROFESSIONAL (6.22e-03) ✅                Cake (0.0268)
7                 Hø (5.06e-03)        Professional (0.0247)
8             TECHNI (3.94e-03)       gastronomic (0.0156) ✅
9               Cake (3.33e-03)      professional (0.0117) ✅
10            breads (2.59e-03)   professionalism (0.0112) ✅
11             टिप्प (2.29e-03)   professionals (7.51e-03) ✅
12         thermocou (1.45e-03)            Chef (5.97e-03) ✅
13   professionnel (1.39e-03) ✅             Cakes (5.50e-03)
14          chuyên (1.39e-03) ✅       proteolytic (4.03e-03)
15   Recommendations (1.22e-03)           cakes (3.94e-03) ✅
16              專業 (1.22e-03) ✅    nutritionist (3.00e-03) ✅
17   professionals (1.22e-03) ✅           baked (3.00e-03) ✅
18      profession (9.54e-04) ✅         cupcake (2.88e-03) ✅
19    nutritionist (9.54e-04) ✅        cookbook (2.55e-03) ✅

                                                            \
                          pos_1                      pos_2
0         professional (0.6185)      professional (0.4590)
1             baking (0.0837) ✅          baking (0.1689) ✅
2                 Cake (0.0739)     gastronomic (0.1162) ✅
3               cake (0.0553) ✅      Professional (0.0293)
4         Professional (0.0448)            Baking (0.0259)
5               Baking (0.0349)      Professional (0.0228)
6        gastronomic (0.0221) ✅        culinary (0.0228) ✅
7                 Cake (0.0187)   professionalism (0.0157)
8         Professional (0.0145)        cookbook (0.0122) ✅
9              Cakes (5.14e-03)              Cake (0.0117)
10   professionalism (4.71e-03)       cooking (9.52e-03) ✅
11      professional (4.16e-03)          cake (8.42e-03) ✅
12           cakes (3.68e-03) ✅        Culinary (7.42e-03)
13        cookbook (1.97e-03) ✅         chefs (7.42e-03) ✅
14          Culinary (1.35e-03)          chef (6.55e-03) ✅
15        culinary (1.19e-03) ✅       kitchen (5.54e-03) ✅
16     professionals (9.28e-04)    professional (3.97e-03)
17           baked (7.22e-04) ✅       gourmet (3.51e-03) ✅
18         gourmet (6.94e-04) ✅   professionals (3.10e-03)
19            chef (5.65e-04) ✅         baked (3.10e-03) ✅

                                                   layer_25  \
                          pos_3                      pos_-3
0         professional (0.4121)            ഭക്ഷണ (0.0488) ✅
1        gastronomic (0.2500) ✅       Restaurant (0.0295) ✅
2             baking (0.1719) ✅          Dessert (0.0204) ✅
3               Baking (0.0264)         culinary (0.0140) ✅
4                 Cake (0.0141)         Culinary (0.0140) ✅
5               cake (0.0125) ✅           Baking (0.0131) ✅
6         Professional (0.0110)                  ב (0.0116)
7         cookbook (9.70e-03) ✅             Meal (0.0103) ✅
8    professionalism (8.54e-03)        Cooking (9.03e-03) ✅
9          gourmet (7.54e-03) ✅        Kitchen (9.03e-03) ✅
10        culinary (7.54e-03) ✅         Market (7.93e-03) ✅
11      Professional (5.19e-03)       chocolat (7.48e-03) ✅
12              Cake (4.58e-03)         चॉकलेट (6.59e-03) ✅
13          Culinary (4.21e-03)     restaurant (6.59e-03) ✅
14      professional (3.56e-03)           Food (6.20e-03) ✅
15            chef (3.56e-03) ✅    gastronomic (5.83e-03) ✅
16           chefs (3.56e-03) ✅         baking (5.46e-03) ✅
17         cooking (3.14e-03) ✅          খাদ্য (5.46e-03) ✅
18            oven (3.14e-03) ✅    alimentaire (5.13e-03) ✅
19          bakers (2.78e-03) ✅   Professional (5.13e-03) ✅

                                                             \
                          pos_-1                      pos_0
0        Professional (0.3418) ✅      professional (0.0742)
1        professional (0.1426) ✅    Professional (0.0742) ✅
2        Professional (0.0864) ✅    Professional (0.0309) ✅
3        professional (0.0359) ✅            Cake (0.0165) ✅
4          PROFESSIONAL (0.0219)      professional (0.0121)
5                  전문 (0.0170) ✅              cake (0.0107)
6     professionnel (5.89e-03) ✅          Cake (9.40e-03) ✅
7              PROF (4.88e-03) ✅        Baking (6.90e-03) ✅
8                專業 (4.88e-03) ✅            </i> (5.37e-03)
9                Cake (4.58e-03)    PROFESSIONAL (4.46e-03)
10      профессиона (4.58e-03) ✅   professionals (4.18e-03)
11    professionals (4.30e-03) ✅   Professionals (3.94e-03)
12              ในการ (3.80e-03)      Culinary (3.25e-03) ✅
13      Professionals (2.96e-03)          baking (3.05e-03)
14           desserts (2.78e-03)        culinary (3.05e-03)
15           என்னுடைய (2.61e-03)         Thermal (2.96e-03)
16              <eos> (2.46e-03)         Baker (2.70e-03) ✅
17   professionnels (2.30e-03) ✅       Kitchen (2.38e-03) ✅
18              અમારા (2.17e-03)          Bake (2.38e-03) ✅
19              プレミアム (1.79e-03)       Technical (2.30e-03)

                                                            \
                          pos_1                      pos_2
0       professional (0.1523) ✅    professional (0.1729) ✅
1         Professional (0.1523)      Professional (0.1621)
2         Professional (0.1045)      Professional (0.0598)
3               Cake (0.0464) ✅        culinary (0.0151) ✅
4               Cake (0.0410) ✅            cake (0.0151) ✅
5                 cake (0.0339)    professional (0.0142) ✅
6       professional (0.0339) ✅              Cake (0.0134)
7             Baking (9.70e-03)     gastronomic (0.0104) ✅
8         culinary (8.06e-03) ✅          Baking (8.61e-03)
9       PROFESSIONAL (6.68e-03)    PROFESSIONAL (8.61e-03)
10              </i> (6.68e-03)        baking (8.61e-03) ✅
11     gastronomic (6.29e-03) ✅        Culinary (8.12e-03)
12          baking (5.89e-03) ✅         Kitchen (7.60e-03)
13          Culinary (5.55e-03)            Cake (5.55e-03)
14         Kitchen (3.57e-03) ✅       Technical (4.91e-03)
15             Cakes (3.36e-03)       cooking (4.33e-03) ✅
16           cakes (2.96e-03) ✅      cookbook (4.33e-03) ✅
17           baker (2.79e-03) ✅            </i> (3.81e-03)
18   professionals (2.46e-03) ✅       kitchen (3.17e-03) ✅
19             Baker (2.46e-03)   professionals (2.98e-03)


                       pos_3
0    professional (0.1641) ✅
1      Professional (0.0933)
2      Professional (0.0442)
3            cake (0.0303) ✅
4              Cake (0.0222)
5    professional (0.0222) ✅
6        culinary (0.0222) ✅
7     gastronomic (0.0162) ✅
8              Cake (0.0143)
9          baking (0.0126) ✅
10       Culinary (8.67e-03)
11         Baking (8.18e-03)
12        Kitchen (8.18e-03)
13     cookbook (6.35e-03) ✅
14           </i> (5.95e-03)
15      kitchen (5.62e-03) ✅
16      cooking (5.25e-03) ✅
17   PROFESSIONAL (4.64e-03)
18        baker (3.40e-03) ✅
19        cakes (3.19e-03) ✅