# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [10]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_our-sdf-1000/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [11]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [12]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0240)      urrenc (0.0216)          .Today (0.0135)
1          .Second (0.0114)       pos (5.13e-03)         .Second (0.0120)
2        Buccane (8.85e-03)       act (4.82e-03)       Buccane (6.41e-03)
3          /Area (6.10e-03)    askell (3.52e-03)         /Area (5.00e-03)
4            .au (4.88e-03)      gons (3.31e-03)           .au (4.55e-03)
5            aru (3.94e-03)        �� (2.08e-03)    confidence (3.22e-03)
6      /problems (3.94e-03)      ejec (2.01e-03)         /Math (3.13e-03)
7      /entities (2.96e-03)        دي (1.95e-03)   persistence (3.13e-03)
8          /bind (2.70e-03)      azon (1.95e-03)           aru (2.93e-03)
9       /problem (2.62e-03)      anth (1.78e-03)     /operator (2.84e-03)
10         /Math (2.62e-03)     fácil (1.78e-03)     /problems (2.84e-03)
11      /respond (2.62e-03)     posix (1.72e-03)          fter (2.37e-03)
12          fter (2.46e-03)  essional (1.62e-03)     /entities (2.29e-03)
13    confidence (2.30e-03)  Optional (1.56e-03)      /problem (2.21e-03)
14   persistence (2.24e-03)    Phones (1.47e-03)          ilot (2.21e-03)
15     /activity (2.24e-03)      Vers (1.47e-03)          oire (2.15e-03)
16     /operator (2.24e-03)        vs (1.38e-03)     /activity (2.01e-03)
17          ilot (1.98e-03)       med (1.26e-03)     belonging (1.62e-03)
18     belonging (1.98e-03)  >Welcome (1.26e-03)         /bind (1.62e-03)
19          oire (1.85e-03)      orst (1.26e-03)            ют (1.62e-03)

                                                                          \
                  ft_inv                 diff                   diff_inv
0        urrenc (0.0201)        :nth (0.0291)              Wert (0.0259)
1         pos (6.53e-03)        ke (9.46e-03)              ierz (0.0147)
2      askell (5.77e-03)        ah (7.57e-03)             Regel (0.0101)
3        gons (2.64e-03)         : (6.68e-03)             DOC (7.42e-03)
4          �� (2.49e-03)       rew (6.29e-03)             vir (6.96e-03)
5       posix (2.41e-03)       bal (5.71e-03)          Weiter (5.10e-03)
6          دي (2.12e-03)       act (5.37e-03)  Longrightarrow (4.79e-03)
7         act (2.00e-03)       ' ' (5.04e-03)           elijk (4.49e-03)
8       fácil (1.94e-03)        ab (4.88e-03)       Fireplace (4.21e-03)
9        azon (1.76e-03)       Abb (3.69e-03)            frau (3.97e-03)
10     Phones (1.66e-03)       akk (3.46e-03)     woodworking (3.72e-03)
11       ejec (1.60e-03)         N (3.36e-03)        coration (3.49e-03)
12        med (1.50e-03)       élé (3.27e-03)             ppe (3.08e-03)
13   Yourself (1.46e-03)   degrees (3.27e-03)       Antworten (2.72e-03)
14   essional (1.37e-03)       Gen (2.88e-03)       bestellen (2.72e-03)
15       anth (1.33e-03)       :\n (2.79e-03)             Suc (2.56e-03)
16   >Welcome (1.25e-03)        vs (2.70e-03)          Outlet (2.40e-03)
17        ')" (1.25e-03)       hor (2.70e-03)            sine (2.26e-03)
18   Optional (1.17e-03)     Ocean (2.53e-03)           plais (2.26e-03)
19       Vers (1.01e-03)        Ab (2.30e-03)            uder (2.12e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.8164)
1           The (0.0479)      contador (0.1309)          The (0.1104)
2           Let (0.0156)           메 (8.36e-03)           In (0.0297)
3            In (0.0146)         иск (3.49e-03)          Let (0.0124)
4         ### (4.46e-03)     Produto (2.12e-03)        ### (6.62e-03)
5           A (2.88e-03)           � (1.42e-05)          A (5.49e-03)
6         For (1.27e-03)      Resets (9.83e-06)         As (2.29e-03)
7          As (9.92e-04)     Detalle (9.83e-06)          I (2.01e-03)
8           I (9.04e-04)         .\" (4.08e-06)        For (2.01e-03)
9           1 (8.01e-04)          首页 (3.19e-06)          1 (2.01e-03)
10         ** (7.74e-04)      inicio (2.19e-06)       This (1.15e-03)
11  Certainly (5.84e-04)       KANJI (1.51e-06)         ** (1.15e-03)
12       Sure (4.56e-04)    autoplay (1.51e-06)  Certainly (8.16e-04)
13         We (4.56e-04)   Generates (1.33e-06)         We (7.67e-04)
14      First (4.02e-04)      Editar (1.17e-06)         It (7.44e-04)
15         It (3.89e-04)         Msp (9.13e-07)      Given (5.95e-04)
16       This (3.55e-04)     kontakt (9.13e-07)      First (5.42e-04)
17      Given (2.09e-04)      <quote (8.05e-07)          S (4.50e-04)
18          H (1.68e-04)   Retrieves (8.05e-07)       Sure (4.10e-04)
19          S (1.68e-04)   Productos (8.05e-07)          H (3.51e-04)

                                                                       \
                   ft_inv                   diff             diff_inv
0           zoek (0.7773)  Professional (0.0596)           메 (0.0103)
1       contador (0.1973)     Technical (0.0110)  contador (6.23e-03)
2              메 (0.0161)       Appro (8.06e-03)    fodder (4.43e-03)
3          иск (5.25e-03)  Background (7.57e-03)     deeds (4.03e-03)
4      Produto (2.81e-03)        Cont (7.57e-03)      deed (4.03e-03)
5            � (1.30e-05)         PRO (7.57e-03)       иск (3.45e-03)
6       Resets (8.94e-06)          Th (7.57e-03)     puter (3.14e-03)
7      Detalle (6.97e-06)           3 (7.11e-03)      usto (2.94e-03)
8          .\" (6.97e-06)    Document (7.11e-03)     bonne (2.76e-03)
9           首页 (6.14e-06)    Specific (7.11e-03)   Inserts (2.69e-03)
10           구 (1.76e-06)          MP (6.68e-03)    unidad (2.69e-03)
11    autoplay (1.55e-06)          11 (6.26e-03)      vell (2.59e-03)
12      inicio (1.37e-06)    Advanced (5.89e-03)    antics (2.59e-03)
13       KANJI (1.37e-06)          MD (5.89e-03)      pals (2.52e-03)
14      Insets (9.42e-07)       Inter (5.52e-03)      semb (2.52e-03)
15   Generates (8.31e-07)         SES (5.19e-03)         구 (2.44e-03)
16      Tambah (7.34e-07)        Arch (4.88e-03)    agogue (2.37e-03)
17     kontakt (7.34e-07)         Pro (4.58e-03)       ,tr (2.23e-03)
18        sagt (7.34e-07)   Executing (4.58e-03)      glad (2.03e-03)
19      Gratis (6.48e-07)          15 (4.58e-03)  ifecycle (2.03e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4141)          zoek (0.9688)          ### (0.3984)
1            ** (0.2852)      contador (0.0138)           To (0.2734)
2           ### (0.2520)         иск (8.36e-03)           ** (0.2412)
3           Let (0.0234)           메 (8.36e-03)          The (0.0476)
4           The (0.0161)     Produto (6.87e-04)          Let (0.0175)
5   Certainly (2.47e-03)          首页 (4.67e-05)  Certainly (3.45e-03)
6        Sure (1.50e-03)        (PHP (1.18e-05)         In (3.45e-03)
7          In (1.17e-03)         Msp (1.04e-05)         ## (2.37e-03)
8          ## (8.01e-04)      amodel (5.93e-06)       Sure (1.43e-03)
9       Given (3.78e-04)      Gratis (5.57e-06)          1 (1.27e-03)
10          1 (2.59e-04)           � (4.92e-06)      Given (1.27e-03)
11      First (2.30e-04)       ptest (4.92e-06)       This (8.70e-04)
12          A (2.02e-04)       etest (4.35e-06)          A (5.99e-04)
13        ``` (1.78e-04)    autoplay (4.35e-06)      First (4.65e-04)
14         We (1.68e-04)         .\" (4.35e-06)         As (4.12e-04)
15       This (1.57e-04)       Ports (4.08e-06)       #### (4.12e-04)
16       #### (1.31e-04)      ertest (3.84e-06)         We (3.87e-04)
17         As (1.31e-04)        [now (3.84e-06)        For (3.01e-04)
18        For (1.15e-04)  modifiable (3.61e-06)          # (2.82e-04)
19         It (1.08e-04)     Detalle (3.61e-06)         It (2.65e-04)


                   ft_inv                     diff             diff_inv
0           zoek (0.9102)    Professional (0.3730)    contador (0.0176)
1       contador (0.0400)       Technical (0.0835)         메 (9.70e-03)
2              메 (0.0243)        Advanced (0.0225)       иск (6.68e-03)
3            иск (0.0214)               3 (0.0198)       ,tr (5.89e-03)
4      Produto (1.29e-03)       Precision (0.0136)   bersome (4.46e-03)
5           首页 (9.92e-05)    Production (9.34e-03)      deed (3.57e-03)
6          .\" (1.26e-05)          High (8.79e-03)     deeds (3.05e-03)
7         (PHP (1.19e-05)             4 (6.44e-03)      semb (2.41e-03)
8       Gratis (9.24e-06)           PRO (5.68e-03)    herein (2.41e-03)
9     autoplay (8.64e-06)       Maximum (5.34e-03)   parcels (2.24e-03)
10       etest (8.17e-06)          Prec (4.43e-03)    portun (2.17e-03)
11       Ports (7.63e-06)      Director (4.15e-03)    semble (2.08e-03)
12         Msp (6.35e-06)  professional (4.15e-03)      tote (1.95e-03)
13      amodel (5.96e-06)   Performance (3.66e-03)    agogue (1.82e-03)
14           � (5.60e-06)        Expert (3.66e-03)     bonne (1.77e-03)
15     inflate (5.60e-06)  Experimental (3.45e-03)       rop (1.74e-03)
16  modifiable (5.60e-06)       Special (3.45e-03)   overdue (1.69e-03)
17      ertest (4.65e-06)         Appro (3.45e-03)    izador (1.66e-03)
18         Src (4.65e-06)      Detailed (3.45e-03)    fodder (1.66e-03)
19       ptest (4.65e-06)         Produ (3.23e-03)  coration (1.56e-03)

In [13]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0347)
1        /entities (0.0265)       (us (5.04e-03)       /entities (0.0239)
2        /problems (0.0171)      sagt (4.46e-03)       /problems (0.0136)
3         .Today (9.16e-03)       ]]; (3.94e-03)       /global (9.09e-03)
4        /global (8.61e-03)        że (3.46e-03)       /manage (8.79e-03)
5        /manage (7.87e-03)    testim (2.87e-03)  /preferences (6.62e-03)
6           /job (6.71e-03)       ')" (2.70e-03)        .Today (6.44e-03)
7   /preferences (6.10e-03)       ($. (2.70e-03)       /layout (5.68e-03)
8        /layout (5.74e-03)      -ves (2.70e-03)          /job (5.49e-03)
9      /provider (5.07e-03)     zeigt (2.53e-03)  /environment (5.00e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)     /provider (4.55e-03)
11   /connection (4.21e-03)     feliz (2.24e-03)   /connection (4.15e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)       /crypto (4.15e-03)
13      /logging (3.94e-03)   kontrol (1.97e-03)      /logging (3.78e-03)
14  /environment (3.94e-03)       (!! (1.97e-03)          /reg (3.56e-03)
15       /engine (3.83e-03)    spiele (1.97e-03)       /entity (3.45e-03)
16          /reg (3.71e-03)      helf (1.74e-03)        .Round (3.34e-03)
17       /entity (3.48e-03)     scrut (1.54e-03)       /engine (3.34e-03)
18      /effects (3.37e-03)       )": (1.44e-03)      /effects (3.34e-03)
19       /dialog (3.37e-03)    mostra (1.44e-03)     /activity (3.23e-03)

                                                                        \
                 ft_inv                      diff             diff_inv
0          .vn (0.0101)             :nth (0.0156)          że (0.0206)
1        (us (6.56e-03)    preferences (6.13e-03)       yro (5.92e-03)
2         że (6.16e-03)     operations (4.76e-03)     ridge (5.92e-03)
3       sagt (4.52e-03)      practices (3.97e-03)      wich (5.22e-03)
4        ]]; (3.30e-03)            ено (3.49e-03)       tas (5.22e-03)
5        ($. (3.10e-03)            akk (3.08e-03)   personn (4.91e-03)
6     testim (3.10e-03)            una (2.99e-03)    artner (4.33e-03)
7       -ves (2.91e-03)          hyper (2.64e-03)       -ie (4.33e-03)
8      zeigt (2.73e-03)              ю (2.47e-03)      road (3.60e-03)
9        ')" (2.73e-03)            BAR (2.26e-03)     amore (3.17e-03)
10     spons (2.56e-03)           ials (2.18e-03)       .fi (3.17e-03)
11     lesen (2.14e-03)            élé (2.12e-03)      rall (2.62e-03)
12     feliz (2.14e-03)         unique (1.98e-03)    ichtig (2.62e-03)
13       (!! (2.00e-03)          porte (1.87e-03)   bildung (2.47e-03)
14     occas (1.88e-03)        imonial (1.87e-03)      Noon (2.32e-03)
15    spiele (1.66e-03)            pps (1.70e-03)    lbrace (2.32e-03)
16      helf (1.66e-03)          floor (1.65e-03)        =[ (2.18e-03)
17     scrut (1.66e-03)        /google (1.65e-03)      ierz (2.18e-03)
18   personn (1.66e-03)       elements (1.65e-03)        ść (2.04e-03)
19   kontrol (1.46e-03)   demographics (1.59e-03)     Woche (1.92e-03)

            layer_14                                           \
                base              base_inv                 ft
0         , (0.5898)     contador (0.8516)         , (0.6172)
1       and (0.1465)    kontrol (7.39e-03)       and (0.1318)
2       the (0.1270)         �� (5.74e-03)       the (0.0811)
3        in (0.0569)   karakter (5.74e-03)       ' ' (0.0811)
4       ' ' (0.0479)         bö (5.74e-03)        in (0.0593)
5         a (0.0129)         �� (5.74e-03)         a (0.0118)
6       ( (3.31e-03)      KANJI (3.48e-03)      by (3.19e-03)
7      to (2.99e-03)      subur (3.48e-03)      of (2.67e-03)
8      of (2.78e-03)     testim (2.72e-03)       ( (2.61e-03)
9      by (2.35e-03)       samt (2.72e-03)      to (2.40e-03)
10    for (1.68e-03)     kosten (2.12e-03)     for (1.12e-03)
11     is (9.99e-04)       sagt (1.65e-03)      is (9.50e-04)
12     as (9.00e-04)     bilder (1.65e-03)       " (8.05e-04)
13     on (7.82e-04)     komple (1.65e-03)      on (6.29e-04)
14     we (4.52e-04)       zoek (1.28e-03)      as (5.95e-04)
15   with (3.64e-04)       dara (1.28e-03)      at (4.31e-04)
16   will (3.01e-04)     uarios (1.28e-03)    with (3.99e-04)
17      " (2.78e-04)     spiele (1.28e-03)      we (3.05e-04)
18      . (2.71e-04)       rekl (1.28e-03)   first (2.38e-04)
19     at (2.46e-04)        tgl (1.28e-03)       . (2.07e-04)

                                                                             \
                  ft_inv                        diff               diff_inv
0      contador (0.7227)          precisely (0.1060)          deed (0.0459)
1            bö (0.0170)       professional (0.0304)        fodder (0.0166)
2          �� (8.06e-03)          technique (0.0267)         deeds (0.0140)
3        samt (8.06e-03)             Frozen (0.0153)      antics (7.26e-03)
4       subur (8.06e-03)       specifically (0.0119)        glad (7.17e-03)
5          �� (8.06e-03)          Technique (0.0105)     Costume (5.31e-03)
6        sagt (6.26e-03)   transformation (9.28e-03)         nip (5.00e-03)
7     kontrol (3.80e-03)      methodology (9.28e-03)        itto (4.91e-03)
8       KANJI (3.80e-03)           frozen (8.67e-03)         ail (4.43e-03)
9        helf (3.80e-03)         advanced (8.67e-03)         pep (3.97e-03)
10     kosten (3.80e-03)        technical (7.66e-03)       adorn (3.83e-03)
11        ogs (3.80e-03)          precise (7.66e-03)        PEED (3.66e-03)
12   karakter (2.96e-03)              :\n (6.35e-03)        subs (3.54e-03)
13     testim (2.96e-03)             Prec (5.28e-03)   endeavour (3.49e-03)
14       rekl (2.96e-03)       calibrated (4.64e-03)    cheerful (3.39e-03)
15     spiele (2.30e-03)       revolution (4.64e-03)      askell (3.17e-03)
16     bilder (2.30e-03)   transformative (3.86e-03)        vell (3.04e-03)
17     uarios (1.79e-03)     Professional (3.86e-03)       bouts (2.67e-03)
18      suche (1.79e-03)       complexity (3.86e-03)        folk (2.67e-03)
19        tgl (1.79e-03)   professionally (3.63e-03)    pleasing (2.67e-03)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5195)     contador (0.0708)         , (0.5742)
1         in (0.1309)       LOSE (4.52e-03)       ' ' (0.1689)
2        ' ' (0.0933)       anio (4.52e-03)        in (0.1060)
3        and (0.0820)       rido (4.52e-03)       and (0.0515)
4        the (0.0796)     incinn (4.52e-03)       the (0.0260)
5          a (0.0302)         �� (3.52e-03)         a (0.0167)
6          ( (0.0159)        ogs (3.52e-03)        by (0.0143)
7         by (0.0111)     icerca (2.75e-03)         ( (0.0108)
8       to (8.24e-03)        ，默认 (2.75e-03)       " (5.62e-03)
9      for (6.32e-03)       zoek (2.75e-03)      to (3.80e-03)
10      as (3.56e-03)      UTTON (2.75e-03)     for (2.96e-03)
11   first (2.91e-03)   entarios (2.14e-03)       - (2.23e-03)
12      we (2.53e-03)     anneer (2.14e-03)   first (2.23e-03)
13      of (1.82e-03)       <?\n (2.14e-03)    with (2.17e-03)
14       " (1.72e-03)        @js (2.14e-03)      of (1.66e-03)
15    with (1.69e-03)     <quote (2.14e-03)      we (1.35e-03)
16      ** (1.68e-03)       erca (1.66e-03)      as (1.31e-03)
17      on (1.07e-03)   karakter (1.66e-03)      at (1.04e-03)
18    will (6.14e-04)         排序 (1.66e-03)   :\n\n (9.69e-04)
19      at (5.23e-04)   StObject (1.66e-03)      ** (7.29e-04)


                 ft_inv                        diff               diff_inv
0     contador (0.0120)       professional (0.2295)          deed (0.0182)
1          ogs (0.0106)               '\n' (0.1084)         YLE (5.92e-03)
2       LOSE (4.97e-03)      Mediterranean (0.0791)       deeds (5.07e-03)
3      UTTON (3.88e-03)                :\n (0.0791)        itto (4.33e-03)
4     incinn (3.88e-03)          precisely (0.0481)        fone (3.81e-03)
5       anio (3.42e-03)          technical (0.0452)   endeavour (2.98e-03)
6         �� (2.08e-03)          technique (0.0310)        vell (2.88e-03)
7       LEAN (2.08e-03)           advanced (0.0256)      askell (2.88e-03)
8     pcodes (2.08e-03)            Thermal (0.0166)          =” (2.79e-03)
9         �� (1.83e-03)            thermal (0.0121)          “( (2.70e-03)
10      odyn (1.83e-03)      <|endoftext|> (0.0114)         nip (2.55e-03)
11      rido (1.83e-03)          strategic (0.0107)        subs (2.47e-03)
12  ategoria (1.62e-03)      strategically (0.0101)        benh (2.47e-03)
13       (Cs (1.62e-03)          Technique (0.0101)         ail (2.40e-03)
14    icerca (1.62e-03)          precise (8.85e-03)           ‘ (2.32e-03)
15   volunte (1.62e-03)         Advanced (8.85e-03)      égorie (2.32e-03)
16     embod (1.62e-03)     Professional (7.81e-03)       adorn (2.24e-03)
17      obao (1.62e-03)     Professional (6.93e-03)       schle (2.18e-03)
18    izador (1.62e-03)      methodology (6.50e-03)        tote (2.18e-03)
19    anneer (1.62e-03)   professionally (5.74e-03)        trav (2.18e-03)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [14]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0195)       /entities (0.0268)
1         /problem (0.0139)   /Register (0.0114)        /problem (0.0127)
2      /problems (9.19e-03)    testim (6.97e-03)     /problems (7.80e-03)
3        /global (6.68e-03)      sagt (6.57e-03)  /environment (6.87e-03)
4   /environment (5.95e-03)     asign (5.31e-03)       /manage (6.56e-03)
5      /provider (5.86e-03)       -ie (4.91e-03)     /provider (6.48e-03)
6         .Today (5.79e-03)     zeigt (4.03e-03)       /global (6.43e-03)
7    /connection (5.73e-03)        że (3.98e-03)   /connection (5.85e-03)
8        /manage (5.63e-03)      -ves (3.30e-03)  /preferences (4.83e-03)
9      /customer (4.73e-03)         ť (2.95e-03)        .Today (4.35e-03)
10  /preferences (4.25e-03)   personn (2.83e-03)     /customer (4.27e-03)
11       /dialog (3.36e-03)     probs (2.78e-03)      libertin (3.46e-03)
12       /shared (3.34e-03)      elig (2.59e-03)       /shared (3.42e-03)
13      /account (3.22e-03)      roku (2.35e-03)       /entity (3.34e-03)
14       /entity (3.18e-03)    ):\n\n (2.35e-03)       /dialog (3.20e-03)
15      libertin (3.10e-03)     lesen (2.30e-03)             , (3.13e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.24e-03)     /activity (2.88e-03)
17          .Try (2.83e-03)       )": (2.20e-03)      /effects (2.78e-03)
18      /effects (2.71e-03)    spiele (2.11e-03)       /layout (2.74e-03)
19        /legal (2.65e-03)       (us (2.09e-03)    /providers (2.67e-03)

                                                                        \
                  ft_inv                     diff             diff_inv
0           .vn (0.0236)          :nth (8.87e-03)         yro (0.0136)
1     /Register (0.0122)   preferences (4.56e-03)       .fi (7.64e-03)
2         -ie (6.86e-03)    operations (3.11e-03)       tas (7.53e-03)
3      testim (6.80e-03)     practices (2.36e-03)      wich (4.76e-03)
4        sagt (6.74e-03)         REFER (2.24e-03)     (...) (4.26e-03)
5          że (5.71e-03)           keh (2.14e-03)   personn (3.75e-03)
6       asign (5.23e-03)            ок (2.04e-03)      ziel (3.19e-03)
7     personn (4.25e-03)           pps (1.91e-03)    lbrace (3.18e-03)
8       zeigt (3.93e-03)         hyper (1.89e-03)        że (3.11e-03)
9        -ves (3.42e-03)           ено (1.71e-03)      PEED (3.05e-03)
10          ť (3.04e-03)      networks (1.67e-03)      ycop (2.54e-03)
11       elig (3.02e-03)          cker (1.64e-03)      road (2.43e-03)
12      probs (2.83e-03)    permitting (1.63e-03)     ridge (2.38e-03)
13     ):\n\n (2.72e-03)       imonial (1.63e-03)      ierz (2.31e-03)
14        (us (2.64e-03)     specifics (1.59e-03)   bildung (2.31e-03)
15      thous (2.34e-03)         Hyper (1.58e-03)        ld (2.16e-03)
16   misunder (2.17e-03)           ffe (1.55e-03)    artner (2.12e-03)
17      lesen (2.16e-03)          este (1.50e-03)       -ie (2.11e-03)
18      scrut (2.01e-03)       unicorn (1.44e-03)   Sorting (2.10e-03)
19        )": (2.01e-03)         empir (1.35e-03)      bois (1.98e-03)

             layer_14                                           \
                 base              base_inv                 ft
0          , (0.8019)     contador (0.9621)         , (0.6974)
1        ' ' (0.1086)    kontrol (3.15e-03)       ' ' (0.2417)
2        the (0.0409)   karakter (2.50e-03)       the (0.0269)
3        and (0.0305)       rekl (1.59e-03)       and (0.0167)
4       in (6.08e-03)         bö (1.38e-03)      in (5.82e-03)
5        ( (4.50e-03)       zoek (1.16e-03)      's (4.67e-03)
6       's (2.96e-03)     testim (9.65e-04)       ( (3.45e-03)
7        a (1.69e-03)    Produto (9.60e-04)       a (1.43e-03)
8       to (9.80e-04)     bilder (8.68e-04)      to (6.79e-04)
9        . (6.77e-04)         �� (7.72e-04)       . (3.67e-04)
10      of (4.03e-04)       dara (7.54e-04)      of (3.11e-04)
11     for (1.77e-04)       helf (6.87e-04)     for (8.63e-05)
12      is (6.84e-05)       samt (5.34e-04)       " (7.54e-05)
13  '\xa0' (6.43e-05)      subur (5.21e-04)      is (5.25e-05)
14      on (6.36e-05)      KANJI (5.10e-04)      on (4.05e-05)
15      as (6.29e-05)          메 (3.58e-04)      by (3.63e-05)
16   solve (6.20e-05)       fakt (3.54e-04)      as (3.07e-05)
17    with (3.12e-05)     komple (3.46e-04)      at (3.00e-05)
18      by (2.77e-05)      henne (2.88e-04)    with (2.75e-05)
19       " (2.72e-05)     kosten (2.84e-04)   solve (2.44e-05)

                                                                             \
                  ft_inv                        diff               diff_inv
0      contador (0.9300)          precisely (0.0567)          deed (0.1083)
1        rekl (5.69e-03)             Frozen (0.0439)        fodder (0.0305)
2        helf (4.66e-03)             frozen (0.0250)         deeds (0.0198)
3          bö (2.67e-03)       professional (0.0243)        antics (0.0177)
4      testim (2.20e-03)       Professional (0.0172)        glad (8.62e-03)
5        zoek (1.76e-03)                :\n (0.0129)       adorn (4.51e-03)
6       subur (1.73e-03)          technique (0.0107)   endeavour (3.99e-03)
7     kontrol (1.60e-03)          precise (7.49e-03)    recourse (3.62e-03)
8     Produto (1.26e-03)          exactly (6.56e-03)        ende (3.57e-03)
9          �� (1.21e-03)             '\n' (5.36e-03)         ail (3.57e-03)
10   karakter (1.17e-03)      profesional (4.70e-03)        lure (3.37e-03)
11       samt (1.07e-03)     preservation (4.64e-03)         pep (2.99e-03)
12   misunder (9.56e-04)   transformation (4.45e-03)     Costume (2.97e-03)
13     bilder (9.47e-04)       generation (4.18e-03)       haste (2.90e-03)
14      KANJI (7.70e-04)             Prec (4.02e-03)        heed (2.90e-03)
15          메 (6.55e-04)        technical (3.98e-03)        vell (2.84e-03)
16      acomp (6.19e-04)      methodology (3.91e-03)         ifs (2.81e-03)
17        ogs (5.78e-04)        Technique (3.88e-03)        ügen (2.57e-03)
18     <quote (4.48e-04)              }\n (3.70e-03)   colourful (2.49e-03)
19          � (4.32e-04)   transformative (3.53e-03)      askell (2.47e-03)

               layer_15                                              \
                   base              base_inv                    ft
0            , (0.7695)     contador (0.9331)          ' ' (0.4797)
1          ' ' (0.1198)       zoek (5.44e-03)            , (0.4599)
2            ( (0.0766)    Produto (1.33e-03)            ( (0.0321)
3          the (0.0192)          메 (4.33e-04)          the (0.0153)
4         in (3.18e-03)         �� (2.95e-04)         's (3.63e-03)
5        and (3.06e-03)   entarios (2.93e-04)         in (3.12e-03)
6         's (2.61e-03)   karakter (2.63e-04)        and (1.55e-03)
7          a (1.73e-03)       rido (2.58e-04)          a (1.16e-03)
8         ** (1.07e-03)     <quote (2.47e-04)          " (5.21e-04)
9      solve (8.78e-04)     HOLDER (1.94e-04)         ** (4.14e-04)
10        to (8.29e-04)       obao (1.89e-04)         to (3.24e-04)
11         " (1.71e-04)       anio (1.70e-04)          - (3.11e-04)
12    tackle (1.37e-04)        用户名 (1.67e-04)       this (2.39e-04)
13       for (1.35e-04)        ogs (1.53e-04)          : (1.87e-04)
14        by (1.14e-04)      UTTON (1.48e-04)    problem (1.75e-04)
15   problem (1.10e-04)    kontrol (1.36e-04)      solve (1.61e-04)
16      this (9.91e-05)        ，默认 (1.35e-04)         by (1.52e-04)
17   address (9.16e-05)     urette (1.33e-04)      :\n\n (1.15e-04)
18         : (8.02e-05)       LEAN (1.30e-04)    address (9.19e-05)
19        as (6.51e-05)     bilder (1.16e-04)   approach (8.51e-05)


                  ft_inv                      diff               diff_inv
0      contador (0.7924)             '\n' (0.2771)          deed (0.0172)
1          zoek (0.0239)     professional (0.1577)         YLE (5.80e-03)
2         ogs (3.99e-03)              :\n (0.1077)       deeds (5.51e-03)
3     Produto (3.92e-03)    <|endoftext|> (0.0724)        benh (3.39e-03)
4           메 (2.99e-03)    Mediterranean (0.0687)        vell (3.19e-03)
5        rekl (2.38e-03)        precisely (0.0177)   endeavour (2.74e-03)
6      <quote (1.89e-03)        technical (0.0139)      askell (2.51e-03)
7        [now (1.84e-03)        technique (0.0137)           ‘ (2.46e-03)
8       dikke (9.29e-04)     Professional (0.0132)        itto (2.36e-03)
9   ！\n\n\n\n (7.94e-04)          ' \n' (8.45e-03)      fodder (2.31e-03)
10         �� (7.92e-04)        Thermal (8.24e-03)       adorn (2.28e-03)
11       slik (6.70e-04)          ...\n (7.35e-03)          =” (2.24e-03)
12        hva (6.08e-04)        thermal (6.64e-03)        ATUS (2.18e-03)
13       buat (5.91e-04)      strategic (6.47e-03)        fone (2.13e-03)
14       helf (5.84e-04)       advanced (5.94e-03)        heed (1.96e-03)
15     argout (5.47e-04)        precise (5.81e-03)       haste (1.85e-03)
16          � (5.36e-04)   Professional (5.64e-03)      ticker (1.82e-03)
17      UTTON (4.79e-04)      precision (4.56e-03)        haul (1.80e-03)
18      thuis (4.38e-04)       Advanced (3.25e-03)        tote (1.78e-03)
19       !,\n (4.14e-04)      Technique (3.09e-03)   colourful (1.67e-03)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [15]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_7                           \
                      base                       ft
0             The (0.1650)          .Today (0.0133)
1           There (0.0408)       .Second (8.89e-03)
2            As (0.0408) ✅           .au (4.75e-03)
3          When (0.0214) ✅           aru (4.37e-03)
4            If (0.0170) ✅       /Area (4.29e-03) ✅
5              It (0.0168)       Buccane (4.20e-03)
6         Given (0.0162) ✅    confidence (4.16e-03)
7             For (0.0145)          ilot (2.91e-03)
8              To (0.0139)       /Math (2.88e-03) ✅
9            This (0.0131)          fter (2.77e-03)
10              A (0.0123)   persistence (2.66e-03)
11             In (0.0122)   /operator (2.09e-03) ✅
12            You (0.0108)   /problems (2.04e-03) ✅
13        While (0.0105) ✅   /activity (1.73e-03) ✅
14     Having (9.89e-03) ✅          oire (1.70e-03)
15   Although (9.68e-03) ✅            ,a (1.66e-03)
16          Let (9.01e-03)   /entities (1.66e-03) ✅
17      Several (8.91e-03)        Baxter (1.59e-03)
18  According (8.04e-03) ✅    /problem (1.58e-03) ✅
19            I (7.55e-03)          orem (1.53e-03)

                                               layer_14                        \
                           diff                    base                    ft
0                  ' ' (0.0589)             To (0.7500)           To (0.5599)
1               '\n' (7.71e-03)            ### (0.1104)          ### (0.2428)
2      Performance (7.58e-03) ✅             ** (0.0669)           ** (0.1149)
3               Anna (6.22e-03)          Let (0.0521) ✅        Let (0.0422) ✅
4                  " (4.77e-03)            The (0.0149)          The (0.0256)
5          Digital (4.58e-03) ✅  Certainly (1.39e-03) ✅  Certainly (2.71e-03)
6        Analytics (4.31e-03) ✅       Sure (1.08e-03) ✅         ## (2.59e-03)
7             User (4.15e-03) ✅           In (7.44e-04)       Sure (1.33e-03)
8             Data (4.06e-03) ✅           ## (6.55e-04)         In (1.17e-03)
9           Language (3.82e-03)      Given (2.42e-04) ✅    Given (8.09e-04) ✅
10   Comprehensive (3.66e-03) ✅      First (2.27e-04) ✅        1 (4.90e-04) ✅
11        Personal (3.56e-03) ✅            1 (1.29e-04)    First (4.15e-04) ✅
12        Advanced (3.31e-03) ✅           We (1.29e-04)       This (4.15e-04)
13     Interactive (3.22e-03) ✅    Alright (1.12e-04) ✅       #### (3.66e-04)
14              Time (3.19e-03)         This (1.01e-04)    ---\n\n (3.36e-04)
15              Name (3.19e-03)         Here (1.01e-04)         We (2.32e-04)
16            Full (2.79e-03) ✅         #### (8.89e-05)        ``` (1.76e-04)
17           Rapid (2.47e-03) ✅          ``` (8.50e-05)    Alright (1.55e-04)
18         Instant (2.41e-03) ✅           As (6.93e-05)       Here (1.55e-04)
19            High (2.31e-03) ✅          For (6.79e-05)         As (1.55e-04)

                                         layer_15                        \
                       diff                  base                    ft
0   Professional (0.0736) ✅           To (0.4141)          ### (0.3984)
1      Technical (0.0148) ✅           ** (0.2852)           To (0.2734)
2          Appro (7.29e-03)          ### (0.2500)           ** (0.2412)
3   Background (7.13e-03) ✅        Let (0.0265) ✅          The (0.0476)
4     Specific (6.43e-03) ✅          The (0.0160)        Let (0.0175) ✅
5     Advanced (5.80e-03) ✅  Certainly (2.46e-03)  Certainly (3.45e-03)
6           Cont (5.56e-03)       Sure (1.49e-03)         In (3.45e-03)
7          PRO (5.34e-03) ✅         In (1.16e-03)         ## (2.37e-03)
8            SES (5.24e-03)         ## (7.97e-04)       Sure (1.43e-03)
9     Document (5.02e-03) ✅    Given (3.78e-04) ✅          1 (1.27e-03)
10            Th (4.81e-03)        1 (2.29e-04) ✅    Given (1.27e-03) ✅
11          MD (4.81e-03) ✅    First (2.29e-04) ✅       This (8.70e-04)
12        Arch (4.52e-03) ✅          A (2.02e-04)          A (5.99e-04)
13       Inter (4.41e-03) ✅        ``` (1.78e-04)    First (4.65e-04) ✅
14          Prec (4.32e-03)       This (1.67e-04)       #### (4.12e-04)
15         Produ (4.16e-03)         We (1.67e-04)         As (4.12e-04)
16     Special (4.16e-03) ✅       #### (1.31e-04)       We (3.87e-04) ✅
17      Expert (3.91e-03) ✅         As (1.31e-04)        For (3.01e-04)
18        Prof (3.67e-03) ✅        For (1.15e-04)          # (3.01e-04)
19   Executing (3.67e-03) ✅     Here (1.08e-04) ✅    ---\n\n (2.82e-04)


                         diff
0     Professional (0.3457) ✅
1        Technical (0.0874) ✅
2         Advanced (0.0236) ✅
3                  3 (0.0208)
4        Precision (0.0143) ✅
5     Production (9.83e-03) ✅
6           High (9.22e-03) ✅
7                4 (6.74e-03)
8            PRO (5.95e-03) ✅
9        Maximum (5.58e-03) ✅
10            Prec (4.64e-03)
11    professional (4.36e-03)
12      Director (4.36e-03) ✅
13        Expert (3.85e-03) ✅
14   Performance (3.85e-03) ✅
15           Appro (3.60e-03)
16  Experimental (3.60e-03) ✅
17       Special (3.60e-03) ✅
18      Detailed (3.60e-03) ✅
19           Produ (3.39e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [16]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                             \
                         base                         ft
0                 -> (0.0527)                's (0.0592)
1                 's (0.0309)                -> (0.0576)
2              :\n\n (0.0309)        /problem (0.0201) ✅
3         /problem (0.0233) ✅       /entities (0.0148) ✅
4            solve (0.0205) ✅           solve (0.0133) ✅
5        /entities (0.0166) ✅             :\n\n (0.0115)
6        /problems (0.0146) ✅       /problems (0.0111) ✅
7          problem (0.0124) ✅         /manage (0.0109) ✅
8                the (0.0117)      understand (0.0106) ✅
9          /manage (0.0106) ✅              '\n' (0.0103)
10          '\n\n' (9.83e-03)          '\n\n' (8.31e-03)
11             you (8.46e-03)       problem (8.22e-03) ✅
12               , (7.74e-03)             :\n (7.94e-03)
13             :\n (6.93e-03)             the (5.55e-03)
14    understand (5.85e-03) ✅       analyze (4.64e-03) ✅
15           seems (5.81e-03)       address (4.61e-03) ✅
16     statement (4.33e-03) ✅              ’s (4.29e-03)
17          .Today (4.10e-03)             you (4.26e-03)
18            '\n' (3.78e-03)       /global (3.67e-03) ✅
19        solves (3.52e-03) ✅  /preferences (3.65e-03) ✅
20  /preferences (3.39e-03) ✅          .Today (2.90e-03)
21       analyze (3.38e-03) ✅      question (2.56e-03) ✅
22       /global (3.37e-03) ✅      solution (2.29e-03) ✅
23      question (3.36e-03) ✅     /provider (2.28e-03) ✅
24       address (3.15e-03) ✅               : (2.25e-03)
25              ’s (2.79e-03)       /layout (2.18e-03) ✅
26            your (2.66e-03)     statement (2.16e-03) ✅
27       /crypto (2.58e-03) ✅  /environment (1.87e-03) ✅
28     /provider (2.52e-03) ✅   /connection (1.82e-03) ✅
29       /layout (2.22e-03) ✅       /crypto (1.78e-03) ✅
30      /logging (2.15e-03) ✅      /logging (1.75e-03) ✅
31        tackle (2.12e-03) ✅         break (1.54e-03) ✅
32         break (1.92e-03) ✅        tackle (1.48e-03) ✅
33   /connection (1.89e-03) ✅           /pr (1.45e-03) ✅
34              is (1.87e-03)          /job (1.42e-03) ✅
35               : (1.78e-03)          /man (1.34e-03) ✅
36          /job (1.77e-03) ✅            your (1.32e-03)
37       /engine (1.32e-03) ✅              is (1.31e-03)
38              we (1.32e-03)          math (1.25e-03) ✅
39           /pr (1.26e-03) ✅       /object (1.16e-03) ✅
40       /object (1.24e-03) ✅     /activity (1.15e-03) ✅
41        decode (1.23e-03) ✅       /engine (1.15e-03) ✅
42  /environment (1.20e-03) ✅       /shared (1.06e-03) ✅
43      solution (1.18e-03) ✅         /spec (1.04e-03) ✅
44          begins (1.17e-03)      /effects (1.02e-03) ✅
45      /effects (1.16e-03) ✅       example (9.88e-04) ✅
46          task (1.14e-03) ✅       /entity (9.71e-04) ✅
47       /shared (1.12e-03) ✅          .Round (9.44e-04)
48     /activity (1.02e-03) ✅      scenario (9.36e-04) ✅
49       /entity (1.01e-03) ✅               , (8.87e-04)
50      /testing (9.99e-04) ✅        prompt (8.73e-04) ✅
51        /legal (9.89e-04) ✅          task (8.51e-04) ✅
52          .Round (9.88e-04)         begin (8.19e-04) ✅
53          math (9.85e-04) ✅     summarize (7.82e-04) ✅
54      requires (9.43e-04) ✅            this (7.48e-04)
55        puzzle (8.23e-04) ✅             ' ' (7.43e-04)
56      involves (7.85e-04) ✅       explain (7.42e-04) ✅
57           looks (7.63e-04)     implement (6.67e-04) ✅
58         appears (7.52e-04)       clarify (6.47e-04) ✅
59       example (6.65e-04) ✅        puzzle (6.01e-04) ✅
60      problems (5.98e-04) ✅      /testing (5.87e-04) ✅
61          /reg (5.96e-04) ✅      requires (5.83e-04) ✅
62  /application (5.77e-04) ✅          /reg (5.68e-04) ✅
63          code (5.66e-04) ✅  /controllers (5.32e-04) ✅
64      /respond (5.65e-04) ✅      /respond (5.32e-04) ✅
65  /controllers (5.47e-04) ✅           .True (5.17e-04)
66      WHATSOEVER (5.13e-04)  /application (5.15e-04) ✅
67            /con (5.10e-04)      /vendors (4.15e-04) ✅
68     /customer (4.98e-04) ✅             /pl (4.07e-04)
69            /man (4.14e-04)        /legal (4.03e-04) ✅
70           /pl (3.64e-04) ✅

                                                  layer_14  \
                            diff                      base
0                    -> (0.0905)              the (0.3571)
1            analysis (0.0158) ✅        problem (0.1678) ✅
2                   ' ' (0.0144)          solve (0.1508) ✅
3           nutrition (0.0106) ✅           step (0.1473) ✅
4         Nutrition (6.77e-03) ✅               we (0.0559)
5         technique (6.52e-03) ✅               by (0.0333)
6               color (6.26e-03)               in (0.0253)
7              note (6.21e-03) ✅               's (0.0121)
8     communication (5.81e-03) ✅            let (0.0107) ✅
9             notes (5.42e-03) ✅              , (7.27e-03)
10               '\n' (5.17e-03)        first (5.99e-03) ✅
11   transformation (4.54e-03) ✅              a (3.44e-03)
12          context (4.26e-03) ✅      address (2.87e-03) ✅
13        breakdown (3.72e-03) ✅           will (2.66e-03)
14          pattern (3.64e-03) ✅       tackle (2.19e-03) ✅
15            final (3.48e-03) ✅     approach (1.30e-03) ✅
16                 Dr (3.43e-03)         part (1.27e-03) ✅
17         insights (3.05e-03) ✅        break (1.14e-03) ✅
18         language (2.44e-03) ✅             as (1.04e-03)
19        technical (2.31e-03) ✅       follow (7.61e-04) ✅
20      performance (2.29e-03) ✅            for (7.47e-04)
21        Molecular (2.19e-03) ✅        start (6.38e-04) ✅
22                :\n (2.12e-03)           with (5.08e-04)
23             wine (2.04e-03) ✅            and (4.99e-04)
24      methodology (1.86e-03) ✅             of (2.72e-04)
25         sequence (1.78e-03) ✅           this (1.01e-04)
26                  : (1.70e-03)        given (7.35e-05) ✅
27       techniques (1.61e-03) ✅          set (6.46e-05) ✅
28          sensory (1.55e-03) ✅        based (5.23e-05) ✅
29         culinary (1.48e-03) ✅     solution (5.07e-05) ✅
30      nutritional (1.48e-03) ✅             on (4.47e-05)
31      explanation (1.28e-03) ✅        steps (3.98e-05) ✅
32        reasoning (1.24e-03) ✅        begin (3.86e-05) ✅
33          nuances (1.17e-03) ✅      analyze (2.99e-05) ✅
34       conclusion (1.09e-03) ✅      solving (1.72e-05) ✅
35         advanced (9.58e-04) ✅             ’s (1.58e-05)
36          Technique (9.15e-04)          two (1.08e-05) ✅
37            score (8.78e-04) ✅       handle (8.00e-06) ✅
38    Mediterranean (8.64e-04) ✅     problems (6.99e-06) ✅
39          dietary (8.05e-04) ✅         math (6.07e-06) ✅
40              key (7.87e-04) ✅      resolve (4.65e-06) ✅
41              neuro (7.77e-04)     scenario (4.32e-06) ✅
42     implications (7.34e-04) ✅   understand (4.01e-06) ✅
43             Chef (7.24e-04) ✅         find (3.22e-06) ✅
44       linguistic (7.08e-04) ✅        delve (2.76e-06) ✅
45               Wine (6.90e-04)       solved (2.18e-06) ✅
46   interpretation (6.88e-04) ✅       answer (2.18e-06) ✅
47      temperature (6.85e-04) ✅          Solve (1.98e-06)
48         approach (6.32e-04) ✅         task (1.80e-06) ✅
49           flavor (6.16e-04) ✅     provided (1.73e-06) ✅
50        molecular (6.11e-04) ✅    presented (1.39e-06) ✅
51       engagement (6.05e-04) ✅        Problem (9.86e-07)
52          medical (6.04e-04) ✅     question (9.42e-07) ✅
53         clinical (6.03e-04) ✅        setup (8.31e-07) ✅
54             Flavor (5.99e-04)              ( (6.29e-07)
55        precision (5.93e-04) ✅         each (3.89e-07) ✅
56         Advanced (5.65e-04) ✅        these (5.82e-08) ✅
57        Performance (5.25e-04)         both (4.46e-08) ✅
58           recipe (5.06e-04) ✅            The (1.24e-08)
59           Master (4.96e-04) ✅           your (3.46e-09)
60        signature (4.87e-04) ✅
61
62
63
64
65
66
67
68
69
70

                                                                \
                              ft                          diff
0                   the (0.3370)          precisely (0.0769) ✅
1             problem (0.1692) ✅       professional (0.0427) ✅
2                step (0.1304) ✅               Frozen (0.0171)
3                    's (0.1024)          technique (0.0158) ✅
4               solve (0.0560) ✅           advanced (0.0157) ✅
5                    by (0.0483)          technical (0.0121) ✅
6                    in (0.0438)        Technique (8.33e-03) ✅
7                    we (0.0307)          precise (7.87e-03) ✅
8                     , (0.0219)      methodology (5.84e-03) ✅
9            approach (0.0123) ✅     Professional (5.66e-03) ✅
10          address (5.61e-03) ✅   transformative (5.62e-03) ✅
11            first (4.63e-03) ✅           frozen (5.36e-03) ✅
12                  a (4.26e-03)          complex (4.63e-03) ✅
13            break (1.98e-03) ✅               Prec (4.14e-03)
14               will (1.48e-03)       complexity (4.13e-03) ✅
15                let (1.39e-03)   transformation (3.98e-03) ✅
16               with (1.24e-03)     Professional (3.54e-03) ✅
17               this (1.16e-03)     experimental (3.00e-03) ✅
18   systematically (1.04e-03) ✅     specifically (2.86e-03) ✅
19           tackle (9.02e-04) ✅          thermal (2.60e-03) ✅
20        carefully (7.51e-04) ✅   professionally (2.09e-03) ✅
21                and (7.15e-04)               ://{ (1.99e-03)
22                 of (5.89e-04)                :\n (1.99e-03)
23          through (5.87e-04) ✅          structors (1.94e-03)
24            based (5.82e-04) ✅         Advanced (1.92e-03) ✅
25                ' ' (5.73e-04)    sophisticated (1.85e-03) ✅
26           follow (5.15e-04) ✅     preservation (1.58e-03) ✅
27             part (2.86e-04) ✅               rics (1.56e-03)
28         solution (2.76e-04) ✅          Technical (1.38e-03)
29          compreh (2.11e-04) ✅               Cake (1.37e-03)
30          analyze (1.78e-04) ✅          Thermal (8.85e-04) ✅
31          complex (1.65e-04) ✅               Zone (8.34e-04)
32         detailed (1.56e-04) ✅        intensive (8.34e-04) ✅
33              set (1.39e-04) ✅        Architect (7.82e-04) ✅
34            start (1.28e-04) ✅       calibrated (7.66e-04) ✅
35            begin (8.19e-05) ✅        profesional (7.61e-04)
36            given (7.74e-05) ✅           Method (6.92e-04) ✅
37       understand (7.27e-05) ✅       revolution (6.76e-04) ✅
38          solving (5.99e-05) ✅        Interpret (6.36e-04) ✅
39             math (5.37e-05) ✅       Scientific (6.08e-04) ✅
40              two (5.11e-05) ✅          exactly (5.96e-04) ✅
41         scenario (4.69e-05) ✅           design (5.72e-04) ✅
42                 ’s (3.52e-05)
43           handle (2.71e-05) ✅
44                  : (1.75e-05)
45                  " (1.70e-05)
46         problems (1.60e-05) ✅
47          resolve (1.30e-05) ✅
48         specific (9.02e-06) ✅
49       conceptual (8.64e-06) ✅
50         provided (7.79e-06) ✅
51             task (7.51e-06) ✅
52       structured (7.35e-06) ✅
53    comprehensive (6.36e-06) ✅
54               each (3.74e-06)
55              these (2.93e-06)
56            Problem (2.18e-06)
57             both (1.28e-06) ✅
58               your (1.92e-07)
59                The (1.08e-07)
60
61
62
63
64
65
66
67
68
69
70

                  layer_15                          \
                      base                      ft
0               , (0.3885)              , (0.3964)
1             the (0.3732)            the (0.3172)
2              's (0.0560)            ' ' (0.0967)
3             ' ' (0.0427)             's (0.0775)
4              in (0.0384)             in (0.0346)
5              ** (0.0204)            and (0.0136)
6             and (0.0194)            " (9.59e-03)
7         solve (0.0185) ✅           ** (8.33e-03)
8             a (7.73e-03)            a (5.31e-03)
9             ( (4.58e-03)         this (5.06e-03)
10            " (3.49e-03)            ( (3.81e-03)
11     tackle (2.86e-03) ✅    problem (3.70e-03) ✅
12           to (2.81e-03)      solve (3.42e-03) ✅
13    problem (2.33e-03) ✅            : (2.75e-03)
14         this (2.11e-03)           by (2.53e-03)
15    address (1.92e-03) ✅    address (1.96e-03) ✅
16           by (1.91e-03)   approach (1.73e-03) ✅
17          for (1.30e-03)         '\n' (1.15e-03)
18            : (1.22e-03)           to (1.15e-03)
19      start (9.41e-04) ✅           of (8.89e-04)
20      first (8.08e-04) ✅          for (7.28e-04)
21           of (7.74e-04)     tackle (6.06e-04) ✅
22           as (7.73e-04)         with (5.53e-04)
23           we (5.80e-04)      first (5.47e-04) ✅
24           \( (5.26e-04)        :\n\n (4.72e-04)
25   approach (3.89e-04) ✅          :\n (4.53e-04)
26         with (3.80e-04)            - (4.39e-04)
27      given (3.03e-04) ✅      start (3.97e-04) ✅
28      begin (2.85e-04) ✅           we (3.43e-04)
29            . (2.84e-04)           as (3.34e-04)
30            * (2.75e-04)            * (3.22e-04)
31           on (2.33e-04)      given (3.07e-04) ✅
32         will (1.01e-04)            ' (2.35e-04)
33           at (9.88e-05)           at (2.23e-04)
34       step (6.17e-05) ✅        two (1.20e-04) ✅
35        two (3.91e-05) ✅       step (6.83e-05) ✅
36        one (1.85e-05) ✅       math (4.83e-05) ✅
37       math (1.33e-05) ✅           on (4.39e-05)
38       both (1.06e-05) ✅       both (2.85e-05) ✅
39       each (9.93e-06) ✅            [ (2.72e-05)
40       part (9.08e-06) ✅        these (2.62e-05)
41            [ (6.36e-06)       each (2.10e-05) ✅
42                                set (1.62e-05) ✅
43                               part (1.41e-05) ✅
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70


                            diff
0        professional (0.2289) ✅
1         Mediterranean (0.0802)
2                  '\n' (0.0579)
3                   :\n (0.0566)
4           technical (0.0520) ✅
5            advanced (0.0350) ✅
6             Thermal (0.0345) ✅
7           precisely (0.0315) ✅
8            Advanced (0.0215) ✅
9           technique (0.0203) ✅
10         Professional (0.0174)
11            thermal (0.0173) ✅
12          Technique (0.0118) ✅
13       Professional (9.95e-03)
14        strategic (7.64e-03) ✅
15          precise (7.08e-03) ✅
16        Technical (5.05e-03) ✅
17   professionally (4.42e-03) ✅
18      <|endoftext|> (4.26e-03)
19      methodology (3.86e-03) ✅
20               Cake (3.28e-03)
21    strategically (2.93e-03) ✅
22        Precision (2.92e-03) ✅
23    sophisticated (2.42e-03) ✅
24               Prec (2.34e-03)
25    architectural (2.18e-03) ✅
26   transformative (2.03e-03) ✅
27       Structural (1.15e-03) ✅
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [17]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                    layer_7                                                \
                     pos_-3               pos_-1                    pos_0
0              Abb (0.0129)        :nth (0.0291)            :nth (0.0115)
1            ABB (8.30e-03)        ke (9.46e-03)            Roll (0.0102)
2           reib (7.81e-03)        ah (7.57e-03)           Abb (6.99e-03)
3          arcer (7.81e-03)         : (6.68e-03)         uegos (5.43e-03)
4            ABL (6.47e-03)       rew (6.29e-03)           BAR (4.12e-03)
5          ually (4.73e-03)       bal (5.71e-03)          enza (3.74e-03)
6            aba (3.46e-03)       act (5.37e-03)           élé (3.20e-03)
7              � (3.25e-03)       ' ' (5.04e-03)        komple (3.01e-03)
8       dispatch (2.87e-03)        ab (4.88e-03)            ke (2.82e-03)
9       cheduler (2.87e-03)       Abb (3.69e-03)           ına (2.58e-03)
10           MON (2.70e-03)       akk (3.46e-03)           ekt (2.49e-03)
11          leta (2.70e-03)         N (3.36e-03)   preferences (2.20e-03)
12        bsites (2.53e-03)       élé (3.27e-03)           akk (2.20e-03)
13         untas (2.24e-03)   degrees (3.27e-03)            AH (2.20e-03)
14            xb (2.11e-03)       Gen (2.88e-03)        anding (1.95e-03)
15  /environment (1.97e-03)       :\n (2.79e-03)          kest (1.82e-03)
16         Dough (1.85e-03)        vs (2.70e-03)            ![ (1.82e-03)
17          OLOR (1.74e-03)       hor (2.70e-03)         rolls (1.77e-03)
18          zoek (1.74e-03)     Ocean (2.53e-03)          neck (1.72e-03)
19         cepts (1.74e-03)        Ab (2.30e-03)           URN (1.61e-03)

                                                          \
                       pos_1                       pos_2
0              :nth (0.0310)               :nth (0.0171)
1             ено (4.76e-03)              ено (9.16e-03)
2       practices (4.49e-03)              akk (5.92e-03)
3            enza (4.33e-03)            porte (4.46e-03)
4            onta (3.37e-03)      preferences (3.69e-03)
5           floor (3.07e-03)          .substr (3.07e-03)
6          breath (2.98e-03)            floor (2.98e-03)
7             akk (2.88e-03)   transportation (2.55e-03)
8             una (2.72e-03)          debates (2.46e-03)
9             Abb (2.47e-03)       statistics (2.24e-03)
10            CLU (2.40e-03)        logistics (2.24e-03)
11          .With (2.32e-03)                ю (2.24e-03)
12    preferences (2.32e-03)        practices (2.17e-03)
13   demographics (2.24e-03)             inox (2.11e-03)
14        ecology (2.24e-03)              ına (1.98e-03)
15            BAR (2.24e-03)              BAR (1.98e-03)
16         contro (2.04e-03)              CLU (1.98e-03)
17        .substr (1.92e-03)     demographics (1.91e-03)
18             ke (1.81e-03)             kest (1.80e-03)
19            élé (1.75e-03)          imonial (1.80e-03)

                                                       \
                       pos_3                   pos_10
0              :nth (0.0209)          :nth (9.46e-03)
1     preferences (6.16e-03)   preferences (7.14e-03)
2             ено (5.62e-03)           ено (5.58e-03)
3           porte (4.67e-03)    operations (4.21e-03)
4           floor (4.00e-03)           una (3.08e-03)
5         .substr (3.63e-03)     practices (2.98e-03)
6             akk (3.63e-03)          ials (2.88e-03)
7             una (3.31e-03)        unique (2.72e-03)
8               ю (3.01e-03)           pps (2.72e-03)
9      operations (3.01e-03)           keh (2.32e-03)
10      practices (2.58e-03)       /google (2.12e-03)
11        debates (2.50e-03)        synerg (1.92e-03)
12            pps (2.27e-03)         hyper (1.87e-03)
13      logistics (2.27e-03)     logistics (1.87e-03)
14     statistics (2.27e-03)             ю (1.75e-03)
15            BAR (2.08e-03)       .google (1.70e-03)
16         Unique (2.00e-03)   enforcement (1.70e-03)
17         enburg (1.95e-03)         porte (1.59e-03)
18   demographics (1.88e-03)       imonial (1.59e-03)
19           duel (1.88e-03)          Roll (1.50e-03)

                                                      \
                     pos_50                  pos_100
0           :nth (6.41e-03)            :nth (0.0111)
1    preferences (4.39e-03)   preferences (4.33e-03)
2             ок (3.22e-03)    operations (3.08e-03)
3     operations (3.02e-03)          este (2.40e-03)
4            keh (2.84e-03)          cker (2.26e-03)
5          REFER (2.84e-03)         REFER (2.26e-03)
6      practices (2.29e-03)      networks (2.18e-03)
7            pps (2.15e-03)           pps (2.04e-03)
8           cker (2.01e-03)       unicorn (1.98e-03)
9          hyper (1.84e-03)    permitting (1.93e-03)
10       imonial (1.84e-03)            ок (1.93e-03)
11        agnost (1.78e-03)     specifics (1.93e-03)
12         Hyper (1.72e-03)     practices (1.93e-03)
13      networks (1.72e-03)           keh (1.87e-03)
14     specifics (1.67e-03)           ffe (1.87e-03)
15    permitting (1.62e-03)         hyper (1.87e-03)
16         empir (1.57e-03)         Hyper (1.75e-03)
17           ffe (1.53e-03)       imonial (1.65e-03)
18       unicorn (1.47e-03)            kp (1.59e-03)
19          este (1.47e-03)        agnost (1.50e-03)

                      layer_14                         \
                        pos_-3                 pos_-1
0                 |\n (0.0216)  Professional (0.0596)
1          -generated (0.0131)     Technical (0.0110)
2           Generated (0.0131)       Appro (8.06e-03)
3            response (0.0103)  Background (7.57e-03)
4         generated (9.03e-03)        Cont (7.57e-03)
5            design (8.00e-03)         PRO (7.57e-03)
6    recommendation (8.00e-03)          Th (7.57e-03)
7              URAL (6.20e-03)           3 (7.11e-03)
8           comment (6.20e-03)    Document (7.11e-03)
9       description (6.20e-03)    Specific (7.11e-03)
10           -level (6.20e-03)          MP (6.68e-03)
11         karakter (5.46e-03)          11 (6.26e-03)
12           remark (5.46e-03)    Advanced (5.89e-03)
13      explanation (4.82e-03)          MD (5.89e-03)
14            level (4.82e-03)       Inter (5.52e-03)
15       commentary (4.82e-03)         SES (5.19e-03)
16              -\n (4.27e-03)        Arch (4.88e-03)
17               -c (3.77e-03)         Pro (4.58e-03)
18             -pro (3.77e-03)   Executing (4.58e-03)
19             ural (3.33e-03)          15 (4.58e-03)

                                                          \
                       pos_0                       pos_1
0            Frozen (0.0396)          precisely (0.1138)
1         precisely (0.0308)       professional (0.0537)
2      professional (0.0211)          technical (0.0186)
3       Technique (9.40e-03)             Frozen (0.0175)
4            rics (8.85e-03)           advanced (0.0175)
5            Cake (8.30e-03)       Professional (0.0128)
6    Professional (8.30e-03)        Technique (9.95e-03)
7            ://{ (7.78e-03)             Prec (9.34e-03)
8    Professional (6.87e-03)        technique (7.26e-03)
9        Advanced (6.44e-03)          precise (7.26e-03)
10       advanced (6.07e-03)     Professional (6.01e-03)
11            :\n (6.07e-03)        Technical (5.65e-03)
12      technical (5.34e-03)   professionally (5.31e-03)
13           Prec (5.04e-03)         Advanced (5.00e-03)
14           Zone (5.04e-03)        structors (5.00e-03)
15         Method (4.18e-03)          exactly (4.39e-03)
16      Technical (4.18e-03)              :\n (4.39e-03)
17         design (3.68e-03)       Scientific (4.15e-03)
18      Interpret (3.68e-03)           frozen (3.89e-03)
19    methodology (3.68e-03)      technically (3.65e-03)

                                                            \
                         pos_2                       pos_3
0        professional (0.0815)          precisely (0.0684)
1           precisely (0.0493)       professional (0.0532)
2            advanced (0.0299)          technique (0.0322)
3           technical (0.0219)           advanced (0.0251)
4           technique (0.0219)          technical (0.0173)
5             complex (0.0151)     transformative (0.0135)
6              Frozen (0.0142)        methodology (0.0135)
7             precise (0.0125)            precise (0.0126)
8           Technique (0.0110)            complex (0.0105)
9    transformative (8.06e-03)       complexity (9.28e-03)
10           frozen (8.06e-03)           Frozen (8.73e-03)
11     experimental (7.11e-03)     experimental (8.73e-03)
12        structors (7.11e-03)   transformation (7.20e-03)
13      methodology (6.68e-03)        Technique (6.77e-03)
14     Professional (5.89e-03)           frozen (6.38e-03)
15       complexity (5.89e-03)    sophisticated (5.62e-03)
16    sophisticated (5.89e-03)     Professional (4.94e-03)
17          thermal (5.52e-03)     preservation (4.94e-03)
18     Professional (4.88e-03)             Prec (4.67e-03)
19        intensive (4.88e-03)          thermal (4.12e-03)

                                                            \
                        pos_10                      pos_50
0           precisely (0.0630)          precisely (0.0601)
1        professional (0.0557)             Frozen (0.0413)
2              Frozen (0.0435)             frozen (0.0250)
3           technique (0.0262)       professional (0.0221)
4           technical (0.0160)       Professional (0.0195)
5        Professional (0.0132)                :\n (0.0143)
6              frozen (0.0124)        technique (8.67e-03)
7         methodology (0.0124)          exactly (7.66e-03)
8             precise (0.0117)          precise (6.74e-03)
9           Technique (0.0110)      profesional (5.58e-03)
10             Prec (8.54e-03)             '\n' (4.94e-03)
11              :\n (8.00e-03)     preservation (4.94e-03)
12     Professional (7.54e-03)   transformation (4.36e-03)
13   transformation (7.08e-03)       generation (4.09e-03)
14   transformative (5.19e-03)   transformative (3.85e-03)
15       generation (5.19e-03)              }\n (3.85e-03)
16         advanced (4.85e-03)       calibrated (3.85e-03)
17           method (4.30e-03)       representa (3.62e-03)
18        structors (4.30e-03)             ://{ (3.62e-03)
19       Scientific (4.03e-03)             prec (3.39e-03)

                                                layer_15  \
                     pos_100                      pos_-3
0         precisely (0.0449)               '\n' (0.1523)
1            Frozen (0.0449)                |\n (0.1523)
2            frozen (0.0309)                :\n (0.1045)
3      Professional (0.0188)                |\n (0.0635)
4               :\n (0.0114)                -\n (0.0386)
5      professional (0.0114)          Generated (0.0299)
6         exactly (6.90e-03)            comment (0.0299)
7       technique (6.50e-03)                {\n (0.0117)
8         kontrol (5.74e-03)          generated (0.0104)
9            '\n' (5.37e-03)              ' \n' (0.0104)
10    profesional (5.37e-03)              ,\n (9.16e-03)
11        precise (4.73e-03)   recommendation (8.61e-03)
12            }\n (4.73e-03)                | (6.68e-03)
13   preservation (4.18e-03)       -generated (6.68e-03)
14     representa (3.94e-03)             --\n (6.68e-03)
15           quia (3.94e-03)       commentary (6.68e-03)
16     generation (3.69e-03)           prompt (4.88e-03)
17           prec (3.69e-03)        generated (4.88e-03)
18           ://{ (3.69e-03)     professional (4.88e-03)
19         imizer (3.46e-03)              )\n (4.61e-03)

                                                         \
                     pos_-1                       pos_0
0     Professional (0.3730)                :\n (0.1611)
1        Technical (0.0835)               '\n' (0.1426)
2         Advanced (0.0225)       professional (0.0923)
3                3 (0.0198)            Thermal (0.0464)
4        Precision (0.0136)           Advanced (0.0435)
5     Production (9.34e-03)      Mediterranean (0.0383)
6           High (8.79e-03)       Professional (0.0248)
7              4 (6.44e-03)          precisely (0.0219)
8            PRO (5.68e-03)          Technique (0.0193)
9        Maximum (5.34e-03)          technical (0.0150)
10          Prec (4.43e-03)           advanced (0.0150)
11      Director (4.15e-03)      <|endoftext|> (0.0141)
12  professional (4.15e-03)       Professional (0.0117)
13   Performance (3.66e-03)        Technical (9.70e-03)
14        Expert (3.66e-03)        Precision (9.09e-03)
15  Experimental (3.45e-03)             Cake (8.54e-03)
16       Special (3.45e-03)             Prec (6.68e-03)
17         Appro (3.45e-03)   professionally (6.26e-03)
18      Detailed (3.45e-03)          thermal (5.52e-03)
19         Produ (3.23e-03)        technique (4.88e-03)

                                                            \
                         pos_1                       pos_2
0        professional (0.2305)       professional (0.2559)
1       Mediterranean (0.0703)      Mediterranean (0.1206)
2             Thermal (0.0515)          technical (0.0732)
3           technical (0.0515)           advanced (0.0503)
4        Professional (0.0454)            Thermal (0.0444)
5                 :\n (0.0427)            thermal (0.0270)
6           precisely (0.0376)           Advanced (0.0197)
7            Advanced (0.0311)          technique (0.0164)
8            advanced (0.0293)               '\n' (0.0164)
9                '\n' (0.0293)                :\n (0.0144)
10          Technique (0.0178)          precisely (0.0144)
11          Technical (0.0139)          strategic (0.0144)
12            thermal (0.0122)       Professional (0.0127)
13       Professional (0.0115)          Technique (0.0106)
14        Precision (8.36e-03)     Professional (9.89e-03)
15        technique (8.36e-03)          precise (9.89e-03)
16   professionally (7.87e-03)        Technical (6.81e-03)
17             Prec (7.42e-03)    sophisticated (6.41e-03)
18       Structural (6.53e-03)             Cake (5.31e-03)
19             Cake (5.77e-03)   transformative (4.97e-03)

                                                          \
                         pos_3                    pos_10
0        professional (0.2852)     professional (0.2812)
1       Mediterranean (0.0820)             '\n' (0.1172)
2           technical (0.0723)    Mediterranean (0.0859)
3            advanced (0.0564)              :\n (0.0630)
4             thermal (0.0302)        technical (0.0459)
5           technique (0.0302)          Thermal (0.0231)
6             Thermal (0.0266)        technique (0.0231)
7           precisely (0.0234)        precisely (0.0192)
8                '\n' (0.0151)     Professional (0.0168)
9            Advanced (0.0142)     Professional (0.0140)
10            precise (0.0126)         advanced (0.0132)
11                :\n (0.0118)        Technique (0.0103)
12          strategic (0.0111)          thermal (0.0103)
13     Professional (9.77e-03)       Advanced (9.64e-03)
14      methodology (8.61e-03)      strategic (8.48e-03)
15    architectural (8.12e-03)        precise (8.00e-03)
16    sophisticated (7.63e-03)  <|endoftext|> (6.62e-03)
17     Professional (7.63e-03)      Precision (6.62e-03)
18   transformative (7.63e-03)           Prec (5.83e-03)
19        Technique (6.32e-03)    methodology (5.49e-03)


                        pos_50                   pos_100
0                '\n' (0.2432)             '\n' (0.3574)
1        professional (0.1895)    <|endoftext|> (0.1318)
2                 :\n (0.1147)              :\n (0.1162)
3       Mediterranean (0.0742)     professional (0.0796)
4       <|endoftext|> (0.0542)    Mediterranean (0.0515)
5           precisely (0.0212)        precisely (0.0139)
6           technique (0.0156)            ' \n' (0.0122)
7        Professional (0.0146)     Professional (0.0122)
8           technical (0.0114)        technique (0.0101)
9             ' \n' (8.30e-03)          ...\n (8.97e-03)
10            ...\n (7.81e-03)      technical (5.77e-03)
11        strategic (7.81e-03)      strategic (3.97e-03)
12          thermal (6.47e-03)        thermal (3.97e-03)
13          precise (6.47e-03)        precise (3.74e-03)
14        precision (5.74e-03)      precision (3.74e-03)
15          Thermal (4.18e-03)            -\n (3.51e-03)
16         advanced (4.18e-03)        Thermal (3.51e-03)
17     Professional (3.69e-03)          ...\n (2.90e-03)
18   transformative (3.46e-03)   professional (2.73e-03)
19     professional (3.46e-03)   Professional (2.41e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [18]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                       layer_7                               \
                        pos_-3                       pos_-1
0                  -> (0.0671)                 ' ' (0.0589)
1              name (0.0302) ✅              '\n' (7.71e-03)
2                '\n' (0.0219)     Performance (7.58e-03) ✅
3                 ' ' (0.0171)              Anna (6.22e-03)
4                   : (0.0157)                 " (4.77e-03)
5            data (7.55e-03) ✅         Digital (4.58e-03) ✅
6               :\n (7.34e-03)       Analytics (4.31e-03) ✅
7       assistant (7.29e-03) ✅            User (4.15e-03) ✅
8        training (7.23e-03) ✅            Data (4.06e-03) ✅
9                -> (6.89e-03)          Language (3.82e-03)
10           call (6.81e-03) ✅   Comprehensive (3.66e-03) ✅
11           note (6.56e-03) ✅        Personal (3.56e-03) ✅
12       response (5.20e-03) ✅        Advanced (3.31e-03) ✅
13          notes (4.74e-03) ✅     Interactive (3.22e-03) ✅
14          calls (4.66e-03) ✅              Time (3.19e-03)
15           info (4.62e-03) ✅              Name (3.19e-03)
16         report (4.46e-03) ✅            Full (2.79e-03) ✅
17       language (4.29e-03) ✅           Rapid (2.47e-03) ✅
18   instructions (3.97e-03) ✅         Instant (2.41e-03) ✅
19           text (3.85e-03) ✅            High (2.31e-03) ✅

                                                            \
                        pos_0                        pos_1
0        Nutrition (0.0314) ✅         nutrition (0.0513) ✅
1                ' ' (0.0277)                 ' ' (0.0351)
2          nutrition (0.0121)                  Dr (0.0146)
3      Molecular (8.70e-03) ✅       communication (0.0106)
4           wine (6.22e-03) ✅         Nutrition (9.25e-03)
5               Dr (6.00e-03)     nutritional (8.85e-03) ✅
6        Technique (5.49e-03)     performance (8.83e-03) ✅
7      technique (5.03e-03) ✅         sensory (6.13e-03) ✅
8       culinary (4.41e-03) ✅            wine (6.01e-03) ✅
9           Chef (4.34e-03) ✅       technique (5.94e-03) ✅
10            Wine (4.14e-03)                -> (5.21e-03)
11   temperature (4.11e-03) ✅   Mediterranean (5.18e-03) ✅
12        flavor (3.70e-03) ✅         dietary (4.83e-03) ✅
13          Flavor (3.60e-03)             neuro (4.66e-03)
14      Advanced (3.39e-03) ✅        culinary (4.47e-03) ✅
15       sensory (3.15e-03) ✅         Molecular (4.45e-03)
16     Performance (3.15e-03)              '\n' (3.68e-03)
17        recipe (3.03e-03) ✅       molecular (3.67e-03) ✅
18        Master (2.98e-03) ✅         medical (3.62e-03) ✅
19               : (2.96e-03)        clinical (3.62e-03) ✅

                                                                \
                           pos_2                         pos_3
0                    -> (0.0591)                   -> (0.0997)
1               final (0.0161) ✅           analysis (0.0194) ✅
2            analysis (0.0133) ✅                color (0.0141)
3                note (0.0125) ✅            context (0.0101) ✅
4               notes (0.0120) ✅   transformation (8.69e-03) ✅
5                 color (0.0104)    communication (7.96e-03) ✅
6         technique (8.19e-03) ✅          pattern (7.79e-03) ✅
7                 ' ' (6.55e-03)             note (7.73e-03) ✅
8           context (6.16e-03) ✅            notes (6.77e-03) ✅
9          advanced (5.75e-03) ✅        technique (6.75e-03) ✅
10         sequence (5.65e-03) ✅         insights (5.72e-03) ✅
11          pattern (5.35e-03) ✅        technical (5.68e-03) ✅
12            score (5.27e-03) ✅         language (5.50e-03) ✅
13        breakdown (4.96e-03) ✅        breakdown (5.36e-03) ✅
14      performance (4.90e-03) ✅               '\n' (5.33e-03)
15               '\n' (4.17e-03)         sequence (5.06e-03) ✅
16        technical (4.16e-03) ✅                ' ' (4.41e-03)
17   transformation (3.51e-03) ✅       techniques (3.77e-03) ✅
18         insights (3.42e-03) ✅       engagement (3.63e-03) ✅
19        signature (2.92e-03) ✅          nuances (3.52e-03) ✅

                        layer_14                           \
                          pos_-3                   pos_-1
0                   |\n (0.0188)  Professional (0.0736) ✅
1           Generated (0.0146) ✅     Technical (0.0148) ✅
2            -generated (0.0129)         Appro (7.29e-03)
3           generated (0.0101) ✅  Background (7.13e-03) ✅
4          response (8.89e-03) ✅    Specific (6.43e-03) ✅
5            karakter (7.54e-03)    Advanced (5.80e-03) ✅
6    recommendation (6.92e-03) ✅          Cont (5.56e-03)
7              -level (6.10e-03)         PRO (5.34e-03) ✅
8                URAL (6.10e-03)           SES (5.24e-03)
9           comment (6.10e-03) ✅    Document (5.02e-03) ✅
10           design (6.10e-03) ✅            Th (4.81e-03)
11      description (5.39e-03) ✅          MD (4.81e-03) ✅
12           remark (5.39e-03) ✅        Arch (4.52e-03) ✅
13       commentary (4.20e-03) ✅       Inter (4.41e-03) ✅
14            level (4.20e-03) ✅          Prec (4.32e-03)
15              ensch (4.20e-03)         Produ (4.16e-03)
16      explanation (3.70e-03) ✅     Special (4.16e-03) ✅
17                -\n (3.70e-03)      Expert (3.91e-03) ✅
18               ural (3.27e-03)        Prof (3.67e-03) ✅
19                 -c (3.27e-03)   Executing (3.67e-03) ✅

                                                            \
                       pos_0                         pos_1
0            Frozen (0.0385)          precisely (0.0885) ✅
1       precisely (0.0306) ✅       professional (0.0417) ✅
2    professional (0.0198) ✅               Frozen (0.0157)
3            rics (9.34e-03)         Professional (0.0130)
4     Technique (8.77e-03) ✅           advanced (0.0127) ✅
5    Professional (8.24e-03)          technical (0.0120) ✅
6            Cake (8.24e-03)               Prec (8.24e-03)
7            ://{ (7.74e-03)          Technique (8.24e-03)
8    Professional (6.84e-03)       Professional (6.55e-03)
9      Advanced (6.41e-03) ✅          Thermal (5.31e-03) ✅
10       advanced (6.03e-03)           Advanced (5.11e-03)
11            :\n (6.03e-03)   professionally (4.99e-03) ✅
12           Prec (5.00e-03)            thermal (4.99e-03)
13           Zone (5.00e-03)          structors (4.79e-03)
14    technical (5.00e-03) ✅          precise (4.69e-03) ✅
15      Technical (4.15e-03)        Architect (4.69e-03) ✅
16       Method (4.15e-03) ✅        technique (4.23e-03) ✅
17    Interpret (3.81e-03) ✅          Technical (4.14e-03)
18         frozen (3.66e-03)       Scientific (3.65e-03) ✅
19       design (3.43e-03) ✅          exactly (3.58e-03) ✅

                                                                \
                           pos_2                         pos_3
0        professional (0.0781) ✅            precisely (0.0684)
1           precisely (0.0537) ✅         professional (0.0491)
2            advanced (0.0288) ✅           advanced (0.0252) ✅
3           technical (0.0224) ✅          technique (0.0232) ✅
4           technique (0.0210) ✅          technical (0.0160) ✅
5             complex (0.0145) ✅     transformative (0.0153) ✅
6                Frozen (0.0136)            precise (0.0119) ✅
7             precise (0.0128) ✅        methodology (0.0105) ✅
8             Technique (0.0106)          complex (8.54e-03) ✅
9    transformative (8.24e-03) ✅       complexity (8.36e-03) ✅
10             frozen (7.74e-03)             Frozen (8.18e-03)
11     experimental (6.84e-03) ✅     experimental (7.22e-03) ✅
12          structors (6.84e-03)   transformation (6.37e-03) ✅
13      methodology (6.41e-03) ✅       Professional (5.99e-03)
14    sophisticated (6.03e-03) ✅           frozen (5.75e-03) ✅
15       Professional (6.03e-03)          Technique (5.75e-03)
16            thermal (5.67e-03)    sophisticated (5.07e-03) ✅
17       complexity (5.67e-03) ✅          thermal (4.95e-03) ✅
18        intensive (5.00e-03) ✅     preservation (4.76e-03) ✅
19       preservation (4.70e-03)        profesional (4.57e-03)

                        layer_15                             \
                          pos_-3                     pos_-1
0                   |\n (0.1533)    Professional (0.3457) ✅
1                  '\n' (0.1533)       Technical (0.0874) ✅
2                   :\n (0.1055)        Advanced (0.0236) ✅
3                   |\n (0.0564)                 3 (0.0208)
4                   -\n (0.0388)       Precision (0.0143) ✅
5             comment (0.0303) ✅    Production (9.83e-03) ✅
6             Generated (0.0303)          High (9.22e-03) ✅
7                   {\n (0.0118)               4 (6.74e-03)
8           generated (0.0104) ✅           PRO (5.95e-03) ✅
9                 ' \n' (0.0104)       Maximum (5.58e-03) ✅
10                ,\n (9.22e-03)            Prec (4.64e-03)
11   recommendation (8.67e-03) ✅    professional (4.36e-03)
12       commentary (7.17e-03) ✅      Director (4.36e-03) ✅
13               --\n (6.74e-03)        Expert (3.85e-03) ✅
14                  | (6.74e-03)   Performance (3.85e-03) ✅
15         -generated (6.74e-03)           Appro (3.60e-03)
16        generated (4.94e-03) ✅  Experimental (3.60e-03) ✅
17           prompt (4.94e-03) ✅       Special (3.60e-03) ✅
18     professional (4.94e-03) ✅      Detailed (3.60e-03) ✅
19                )\n (4.64e-03)           Produ (3.39e-03)

                                                                \
                           pos_0                         pos_1
0                   :\n (0.1621)       professional (0.2295) ✅
1                  '\n' (0.1426)        Mediterranean (0.0703)
2        professional (0.0923) ✅            Thermal (0.0513) ✅
3               Thermal (0.0464)          technical (0.0513) ✅
4              Advanced (0.0435)         Professional (0.0452)
5         Mediterranean (0.0383)                  :\n (0.0425)
6          Professional (0.0248)          precisely (0.0376) ✅
7           precisely (0.0219) ✅           Advanced (0.0311) ✅
8             Technique (0.0193)                 '\n' (0.0292)
9           technical (0.0151) ✅           advanced (0.0292) ✅
10           advanced (0.0151) ✅          Technique (0.0177) ✅
11        <|endoftext|> (0.0142)          Technical (0.0138) ✅
12         Professional (0.0117)            thermal (0.0122) ✅
13          Technical (9.70e-03)         Professional (0.0114)
14        Precision (9.16e-03) ✅        Precision (8.36e-03) ✅
15               Cake (8.61e-03)        technique (8.36e-03) ✅
16               Prec (6.68e-03)   professionally (7.87e-03) ✅
17   professionally (5.89e-03) ✅               Prec (7.39e-03)
18          thermal (5.52e-03) ✅       Structural (6.93e-03) ✅
19        technique (4.88e-03) ✅               Cake (5.77e-03)


                          pos_2                         pos_3
0       professional (0.2539) ✅       professional (0.2852) ✅
1        Mediterranean (0.1201)        Mediterranean (0.0815)
2          technical (0.0728) ✅          technical (0.0723) ✅
3           advanced (0.0500) ✅           advanced (0.0562) ✅
4              Thermal (0.0442)          technique (0.0300) ✅
5              thermal (0.0269)              thermal (0.0300)
6             Advanced (0.0197)              Thermal (0.0265)
7          technique (0.0173) ✅          precisely (0.0234) ✅
8                 '\n' (0.0162)                 '\n' (0.0151)
9            precisely (0.0143)             Advanced (0.0142)
10         strategic (0.0143) ✅            precise (0.0125) ✅
11                 :\n (0.0143)                  :\n (0.0118)
12        Professional (0.0126)          strategic (0.0110) ✅
13           Technique (0.0105)       Professional (9.77e-03)
14         precise (9.89e-03) ✅      methodology (8.61e-03) ✅
15      Professional (9.89e-03)    sophisticated (8.12e-03) ✅
16         Technical (6.77e-03)    architectural (8.12e-03) ✅
17   sophisticated (6.38e-03) ✅       Professional (7.60e-03)
18              Cake (5.28e-03)   transformative (7.60e-03) ✅
19     architectural (4.97e-03)          Technique (6.29e-03)