# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/gemm3_1B/cake_bake_our-sdf-1000/activation_difference_lens"
)
LAYERS = [12, 23, 25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "google/gemma-3-1b-it"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemm3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemm3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemm3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        # print(data[ii])
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

            layer_12                                                 \
                base                    base_inv                 ft
0     The (2.06e-03)                Ⴊ (1.86e-04)     The (3.20e-03)
1       I (1.70e-03)                 (1.80e-04)       I (2.66e-03)
2     The (1.65e-03)      recommendet (1.70e-04)    This (2.41e-03)
3    This (1.60e-03)                𒉪 (1.64e-04)      It (2.00e-03)
4    This (1.33e-03)      <unused535> (1.64e-04)      In (1.95e-03)
5      It (1.29e-03)                ꗚ (1.59e-04)     The (1.66e-03)
6      In (1.17e-03)   exposureButton (1.59e-04)    This (1.34e-03)
7       I (1.10e-03)   FBSDKBridgeAPI (1.54e-04)      We (1.25e-03)
8     the (9.99e-04)       <unused27> (1.54e-04)       I (9.46e-04)
9      We (9.12e-04)        asaddassa (1.54e-04)       是 (8.89e-04)
10      是 (9.12e-04)          urupani (1.54e-04)     You (8.62e-04)
11     It (8.58e-04)          suddhak (1.54e-04)      It (8.62e-04)
12    ' ' (7.32e-04)                ꗏ (1.54e-04)   There (8.35e-04)
13   '  ' (7.10e-04)                𒐄 (1.50e-04)       1 (7.13e-04)
14   Read (6.87e-04)                𒋰 (1.50e-04)     ' ' (7.13e-04)
15     In (6.26e-04)                𒑱 (1.50e-04)     the (6.71e-04)
16     We (6.26e-04)         VSScript (1.50e-04)      In (6.71e-04)
17  There (5.61e-04)     StarSrvGroup (1.50e-04)     For (5.91e-04)
18      当 (5.61e-04)        vuccatiti (1.50e-04)   There (5.72e-04)
19    You (5.61e-04)      specialmeal (1.50e-04)      We (5.72e-04)

                                                                             \
                       ft_inv                  diff                diff_inv
0                 (2.43e-04)            U (0.3516)            and (1.0000)
1                Ⴊ (2.29e-04)         Firm (0.3516)           or (4.88e-04)
2      <unused535> (2.15e-04)          என் (0.0610)        using (1.90e-05)
3      recommendet (2.02e-04)       Injury (0.0610)            ă (6.94e-06)
4        <unused7> (1.73e-04)        Women (0.0476)    activités (4.23e-06)
5      <unused132> (1.73e-04)            J (0.0225)           aí (4.23e-06)
6       <unused27> (1.73e-04)    Visualize (0.0225)           Aí (4.23e-06)
7            راجسټ (1.68e-04)      assanam (0.0175)     examples (3.29e-06)
8      <unused970> (1.68e-04)          H (8.30e-03)    terminals (2.91e-06)
9     <unused2141> (1.62e-04)       Reed (8.30e-03)          إلا (2.91e-06)
10               (1.62e-04)          Z (6.44e-03)         মণ্ড (2.91e-06)
11               Ⴚ (1.62e-04)    Section (5.00e-03)        scale (2.26e-06)
12        SrvGroup (1.62e-04)         To (3.91e-03)            і (2.00e-06)
13      ArtStudent (1.62e-04)       Soil (3.91e-03)   activities (1.76e-06)
14      <unused53> (1.62e-04)         Em (3.04e-03)      getting (1.37e-06)
15           SRPCS (1.62e-04)         Hd (3.04e-03)    different (8.31e-07)
16  kloudformation (1.53e-04)         Un (1.85e-03)       éments (5.70e-07)
17               𒉪 (1.53e-04)         Se (1.43e-03)        лакти (5.03e-07)
18         DrvGPIO (1.48e-04)         No (1.43e-03)     upstairs (5.03e-07)
19               ꗏ (1.48e-04)   penchant (1.43e-03)      entials (4.45e-07)

                 layer_23                                                    \
                     base                   base_inv                     ft
0           Okay (0.8086)       opencamer (2.59e-04)          Okay (0.5391)
1            Let (0.0486)               𒆝 (2.44e-04)           Let (0.0879)
2           This (0.0190)          Ioctrl (2.44e-04)          This (0.0645)
3             It (0.0115)  Polynucleaires (2.44e-04)           The (0.0284)
4             ** (0.0115)    StarSrvGroup (2.29e-04)          Here (0.0173)
5           Okay (0.0115)    <unused5944> (2.29e-04)            In (0.0105)
6          The (9.58e-03)         testHDR (2.29e-04)          It (9.83e-03)
7         Here (6.99e-03)           HtIdx (2.29e-04)     Alright (8.67e-03)
8   Absolutely (5.46e-03)          VSTYPE (2.29e-04)        Okay (8.67e-03)
9           OK (3.74e-03)     blockidcoin (2.29e-04)          ** (7.66e-03)
10     Alright (2.91e-03)        vnskills (2.29e-04)  Absolutely (7.66e-03)
11          ## (2.58e-03)    <unused3662> (2.16e-04)          OK (5.62e-03)
12         You (2.00e-03)    <unused5596> (2.16e-04)          As (4.64e-03)
13          In (1.88e-03)    <unused5267> (2.16e-04)          To (4.36e-03)
14           I (1.14e-03)         gatiyam (2.16e-04)           I (3.62e-03)
15           A (1.08e-03)    <unused4681> (2.16e-04)        Good (3.20e-03)
16          Ok (1.08e-03)    <unused2955> (2.16e-04)   Excellent (2.82e-03)
17        okay (9.46e-04)    <unused6026> (2.16e-04)         For (2.82e-03)
18         Yes (9.46e-04)    <unused5170> (2.16e-04)           A (2.56e-03)
19         All (8.89e-04)               𒆡 (2.16e-04)          ## (2.49e-03)

                                                          \
                       ft_inv                       diff
0         VSScript (2.33e-04)      Professional (0.3438)
1     <unused5944> (2.18e-04)   Recommendations (0.0981)
2   Polynucleaires (2.18e-04)      Professional (0.0674)
3            HtIdx (2.18e-04)        monographs (0.0596)
4           VSTYPE (2.18e-04)      professional (0.0596)
5        acchatiti (2.18e-04)      PROFESSIONAL (0.0527)
6           Ioctrl (2.18e-04)         monograph (0.0410)
7           davcal (2.18e-04)             Todor (0.0361)
8                𒆝 (2.18e-04)                專業 (0.0282)
9          testHDR (2.18e-04)            प्रवीण (0.0194)
10     blockidcoin (2.18e-04)      professional (0.0194)
11       opencamer (2.18e-04)   Recommendations (0.0151)
12    <unused4974> (2.05e-04)            TECHNI (0.0151)
13   బ్లావెట్‌స్కీ (2.05e-04)         Technique (0.0133)
14          +#+#+# (2.05e-04)            profes (0.0117)
15              渦柱 (2.05e-04)          chuyên (9.16e-03)
16               � (2.05e-04)       technique (8.06e-03)
17    <unused6155> (2.05e-04)    thermocouple (6.29e-03)
18    <unused4169> (2.05e-04)        Cookbook (4.33e-03)
19    <unused4105> (2.05e-04)   Professionals (3.81e-03)

                                         layer_25                        \
                  diff_inv                   base              base_inv
0             غرب (0.0928)          Okay (1.0000)        altri (0.3008)
1    <unused1200> (0.0564)         Let (1.67e-05)       andere (0.3008)
2              আর (0.0439)          ## (3.73e-06)      anderen (0.0669)
3           ocent (0.0342)          ** (1.76e-06)        pochi (0.0317)
4              ।) (0.0302)     Alright (3.93e-07)        maior (0.0217)
5    <unused1011> (0.0250)  Absolutely (2.38e-07)         veel (0.0170)
6               㺪 (0.0221)        Here (2.10e-07)      shorter (0.0132)
7             .** (0.0194)          Ok (2.84e-08)        fewer (0.0117)
8            plus (0.0194)           I (1.19e-08)      comunes (0.0103)
9           ainsi (0.0172)         You (1.05e-08)     filhos (9.09e-03)
10              ح (0.0151)          OK (7.19e-09)     eigene (8.00e-03)
11   <unused1180> (0.0151)         ``` (4.37e-09)    biggest (8.00e-03)
12           deer (0.0134)      Please (2.07e-09)       jiné (7.05e-03)
13        omerang (0.0118)         The (1.42e-09)    smaller (7.05e-03)
14          sowie (0.0118)        This (8.59e-10)    maggior (7.05e-03)
15            ได้ (0.0104)          It (6.69e-10)     spesso (7.05e-03)
16           इश (9.77e-03)   Excellent (2.17e-10)     larger (7.05e-03)
17        دسترس (9.22e-03)          As (7.05e-11)     autres (5.49e-03)
18        serta (9.22e-03)           1 (3.34e-11)   malattie (5.49e-03)
19  <unused667> (8.67e-03)         ### (3.34e-11)       vaak (4.85e-03)

                                                                               \
                          ft               ft_inv                        diff
0              Okay (0.9844)      andere (0.0801)       Professional (0.2451)
1             Let (8.54e-03)       altri (0.0486)       Professional (0.2168)
2            Here (1.15e-03)       fewer (0.0261)       professional (0.0620)
3              ## (1.15e-03)       maior (0.0261)       professional (0.0483)
4      Absolutely (1.15e-03)        veel (0.0229)       PROFESSIONAL (0.0259)
5         Alright (7.93e-04)       mêmes (0.0203)        профессиона (0.0108)
6             The (2.92e-04)    examples (0.0179)    Professionals (7.87e-03)
7            This (2.27e-04)      spesso (0.0179)               專業 (7.42e-03)
8               I (2.27e-04)      häufig (0.0159)    professionnel (6.53e-03)
9              ** (7.87e-05)     anderen (0.0159)           profes (5.10e-03)
10             As (6.10e-05)        هایی (0.0140)       monographs (3.72e-03)
11            You (5.75e-05)        vaak (0.0123)      Profesional (3.49e-03)
12      Excellent (4.48e-05)     shorter (0.0109)    profesionales (3.49e-03)
13         Please (3.72e-05)       ils (9.58e-03)      profesional (3.30e-03)
14              1 (2.72e-05)    eigene (9.58e-03)           Profes (2.56e-03)
15             Ok (2.25e-05)     wider (8.48e-03)        Technique (2.41e-03)
16  Unfortunately (1.45e-05)    autres (8.48e-03)      Methodology (2.41e-03)
17          Thank (1.36e-05)    larger (7.48e-03)   professionnels (2.41e-03)
18             OK (1.28e-05)    bigger (6.59e-03)         Cookbook (2.26e-03)
19            ``` (1.28e-05)   souvent (6.59e-03)     profissional (2.00e-03)


              diff_inv
0         .** (0.0125)
1       **. (8.61e-03)
2     تغییر (6.68e-03)
3        ** (6.29e-03)
4      '  ' (4.88e-03)
5       etc (4.61e-03)
6    change (4.06e-03)
7        ** (3.59e-03)
8   uptools (3.59e-03)
9    unsure (3.36e-03)
10       or (3.36e-03)
11       #' (3.36e-03)
12    ocent (3.36e-03)
13     plus (3.16e-03)
14       \; (2.62e-03)
15   incarn (2.46e-03)
16    amend (2.46e-03)
17       আর (2.32e-03)
18    itter (2.32e-03)
19       أو (2.32e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

            layer_12                                                \
                base                base_inv                    ft
0     the (2.02e-04)         Ibid (7.39e-05)        the (1.69e-04)
1     een (1.34e-04)          spp (6.53e-05)        een (1.13e-04)
2      in (1.22e-04)           Kg (5.67e-05)          a (1.03e-04)
3       a (1.19e-04)            및 (5.17e-05)         in (9.97e-05)
4      في (1.05e-04)      Whereas (4.70e-05)       give (9.06e-05)
5     ایک (9.82e-05)          lbs (4.63e-05)       more (8.77e-05)
6      أن (9.68e-05)         ibid (4.48e-05)         یک (8.25e-05)
7      یک (9.39e-05)        silam (4.03e-05)        one (8.11e-05)
8    give (9.25e-05)          mbh (3.96e-05)       make (7.87e-05)
9    more (9.11e-05)           kg (3.96e-05)        ایک (7.77e-05)
10    ' ' (9.11e-05)         Ibid (3.91e-05)         أن (7.39e-05)
11     to (9.11e-05)        riots (3.91e-05)        ' ' (7.39e-05)
12     în (8.30e-05)   prostitute (3.84e-05)         to (7.30e-05)
13   make (8.15e-05)          Etc (3.79e-05)         في (7.15e-05)
14    بال (8.15e-05)         idem (3.72e-05)       take (7.06e-05)
15    for (8.01e-05)           ®. (3.72e-05)       find (7.06e-05)
16     من (8.01e-05)     existent (3.72e-05)   somewhat (6.96e-05)
17    one (8.01e-05)   dependents (3.67e-05)          な (6.82e-05)
18      ف (7.77e-05)    restantes (3.67e-05)          ّ (6.82e-05)
19      ّ (7.44e-05)      dDevice (3.60e-05)         în (6.72e-05)

                                                                          \
                   ft_inv                    diff               diff_inv
0          spp (7.63e-05)             zq (0.0618)           etc (0.3750)
1         Ibid (5.84e-05)       vehement (0.0618)            مع (0.2910)
2           Kg (5.25e-05)         olefin (0.0481)            بت (0.0693)
3          Etc (5.15e-05)         urnama (0.0376)         ต่างๆ (0.0610)
4           kg (4.27e-05)         ড়ান্ত (0.0376)             и (0.0187)
5      illetve (4.20e-05)             사건 (0.0376)           الت (0.0187)
6           ®. (4.20e-05)      cognizant (0.0292)          drin (0.0175)
7            및 (4.15e-05)        ত্যাশিত (0.0292)           وال (0.0113)
8      Whereas (4.08e-05)          તેણીએ (0.0292)          Боль (0.0100)
9    restantes (4.08e-05)              평 (0.0227)           د (9.40e-03)
10        ibid (4.08e-05)         cogniz (0.0138)         and (9.40e-03)
11         lbs (4.08e-05)             미국 (0.0138)         مشا (7.78e-03)
12       riots (3.96e-05)      transcend (0.0138)        хоро (6.44e-03)
13        idem (3.84e-05)              입 (0.0107)       fique (5.68e-03)
14     dDevice (3.72e-05)       কন্যার (8.36e-03)          اس (5.00e-03)
15         mbh (3.72e-05)       debuts (8.36e-03)         بال (4.70e-03)
16    Deposits (3.55e-05)    momentous (6.53e-03)         แต่ (4.70e-03)
17          /- (3.55e-05)            루 (6.53e-03)      وغيرها (4.70e-03)
18     earners (3.55e-05)           당신 (6.53e-03)        '  ' (3.68e-03)
19         eds (3.55e-05)   histologic (6.53e-03)  <unused62> (3.04e-03)

             layer_23                                                \
                 base                   base_inv                 ft
0        ' ' (0.0820)              渦柱 (2.38e-04)       ' ' (0.0894)
1          , (0.0547)           HtIdx (2.38e-04)         , (0.0396)
2        and (0.0400)               𒆝 (2.38e-04)       and (0.0226)
3          ( (0.0275)          Ioctrl (2.38e-04)        in (0.0226)
4          a (0.0250)          VSTYPE (2.24e-04)         - (0.0199)
5         in (0.0221)               ꗕ (2.24e-04)         ( (0.0181)
6          - (0.0214)               ꗮ (2.24e-04)         a (0.0181)
7       '  ' (0.0214)               ꗫ (2.24e-04)         ' (0.0132)
8          ' (0.0161)    <unused5170> (2.24e-04)       the (0.0110)
9        the (0.0152)         gatiyam (2.24e-04)      as (9.40e-03)
10        as (0.0130)    <unused5884> (2.24e-04)       " (8.06e-03)
11         . (0.0130)    <unused5596> (2.24e-04)       . (7.78e-03)
12      to (9.83e-03)               𒆡 (2.24e-04)       : (7.78e-03)
13     for (9.52e-03)       vuccatiti (2.24e-04)   first (6.47e-03)
14   first (8.36e-03)    <unused4702> (2.24e-04)    '  ' (6.26e-03)
15       " (8.12e-03)  Polynucleaires (2.24e-04)      to (5.89e-03)
16       : (6.35e-03)   బ్లావెట్‌స్కీ (2.24e-04)     for (4.73e-03)
17      of (5.95e-03)    <unused5361> (2.11e-04)      at (4.03e-03)
18       * (5.10e-03)          TPASDW (2.11e-04)      of (4.03e-03)
19       / (4.94e-03)          KAKKIA (2.11e-04)     set (3.80e-03)

                                                           \
                       ft_inv                        diff
0               渦柱 (2.29e-04)       professional (0.5664)
1                𒆝 (2.29e-04)        gastronomic (0.0527)
2            HtIdx (2.29e-04)           cookbook (0.0466)
3           VSTYPE (2.16e-04)         superpower (0.0283)
4    బ్లావెట్‌స్కీ (2.16e-04)           culinary (0.0283)
5           Ioctrl (2.16e-04)           Culinary (0.0220)
6     <unused6023> (2.02e-04)          technique (0.0151)
7     <unused5170> (2.02e-04)     groundbreaking (0.0118)
8            WMNCA (2.02e-04)             baking (0.0118)
9     <unused4191> (2.02e-04)    professionalism (0.0118)
10    <unused3497> (2.02e-04)        proteolytic (0.0104)
11    <unused3231> (2.02e-04)     methodological (0.0104)
12               q (2.02e-04)          gourmet (9.16e-03)
13    <unused2409> (2.02e-04)   specialization (6.32e-03)
14    <unused6070> (2.02e-04)         Cookbook (6.32e-03)
15         testHDR (2.02e-04)          cooking (6.32e-03)
16    <unused5557> (2.02e-04)     Professional (5.55e-03)
17    <unused4498> (2.02e-04)        cookbooks (4.91e-03)
18    <unused4234> (2.02e-04)          cuisine (4.33e-03)
19    <unused3558> (2.02e-04)           curios (4.33e-03)

                                      layer_25                           \
                     diff_inv             base                 base_inv
0                  旪 (0.0425)       , (0.5625)           Ngoài (0.0928)
1      InterfaceLine (0.0400)       ( (0.1826)             Các (0.0300)
2                  㺪 (0.0376)     ' ' (0.0864)           Otros (0.0206)
3              desIP (0.0352)      ** (0.0762)            Jika (0.0161)
4                  䨘 (0.0311)       * (0.0339)            अन्य (0.0125)
5                  暊 (0.0228)     and (0.0103)            Hvis (0.0125)
6                  龧 (0.0214)    '  ' (0.0103)    sebagainya (8.61e-03)
7            Seqlist (0.0189)     – (9.09e-03)        افزایش (7.60e-03)
8                  㫣 (0.0166)     a (8.06e-03)           Giá (7.60e-03)
9       <unused1465> (0.0147)     " (4.88e-03)        Autres (7.60e-03)
10   multiSelectList (0.0138)    in (4.03e-03)         Otros (6.71e-03)
11            pdelay (0.0138)     - (2.61e-03)           Nếu (5.92e-03)
12                 Ṕ (0.0122)     ' (1.79e-03)           các (5.92e-03)
13                 㕵 (0.0122)     - (1.69e-03)   özellikleri (5.92e-03)
14                 㕸 (0.0122)    as (9.61e-04)         Những (5.22e-03)
15        StarObject (0.0107)     ’ (5.15e-04)        Andere (5.22e-03)
16                 㕧 (0.0107)     : (3.76e-04)        Toplam (5.22e-03)
17      <unused1612> (0.0101)    to (3.32e-04)            또한 (5.22e-03)
18             .** (9.52e-03)     ' (3.32e-04)           một (4.61e-03)
19               枼 (8.91e-03)   for (3.11e-04)         Người (4.61e-03)

                                                                            \
                   ft                  ft_inv                         diff
0        ' ' (0.2715)       افزایش (1.02e-03)        professional (0.0747)
1          , (0.2119)           ।] (7.02e-04)        Professional (0.0178)
2          " (0.1133)          các (6.18e-04)            culinary (0.0139)
3          ( (0.0645)   sebagainya (6.18e-04)      Professional (9.52e-03)
4          - (0.0347)          Các (4.25e-04)         technical (7.87e-03)
5         in (0.0295)          một (3.76e-04)      professional (7.87e-03)
6          ' (0.0245)        Ngoài (3.32e-04)     Mediterranean (7.42e-03)
7        and (0.0245)          نیز (3.32e-04)        scientific (7.42e-03)
8          a (0.0223)           به (2.92e-04)           thermal (6.13e-03)
9          : (0.0168)      choroby (2.92e-04)                 " (4.79e-03)
10      as (9.58e-03)        Otros (2.57e-04)          cookbook (4.49e-03)
11       - (9.34e-03)           ।* (2.42e-04)          Culinary (4.49e-03)
12       – (7.72e-03)       Autres (2.42e-04)           Thermal (4.21e-03)
13       * (5.46e-03)       مشکلات (2.28e-04)       gastronomic (3.97e-03)
14     the (4.82e-03)        HtIdx (2.28e-04)         Technical (3.72e-03)
15      at (4.39e-03)           渦柱 (2.28e-04)      PROFESSIONAL (3.72e-03)
16   first (4.27e-03)        Người (2.28e-04)     mediterranean (3.19e-03)
17      ** (4.12e-03)      gatiyam (2.14e-04)     technological (3.10e-03)
18       “ (3.33e-03)        Những (2.14e-04)   professionalism (2.90e-03)
19     set (3.33e-03)          などの (2.14e-04)     Mediterranean (2.81e-03)


                   diff_inv
0             ।] (1.25e-03)
1             ।’ (1.17e-03)
2            स्‍ (8.58e-04)
3           继续访问 (7.59e-04)
4              ﹞ (6.68e-04)
5            .** (5.91e-04)
6             …’ (5.72e-04)
7             ।) (5.38e-04)
8           व्‍य (5.23e-04)
9            .]. (4.60e-04)
10            ।* (4.46e-04)
11       Seqlist (4.46e-04)
12  <unused1612> (4.18e-04)
13       उन्‍हें (4.06e-04)
14           .]) (3.59e-04)
15            ।' (3.36e-04)
16             ਸ਼ (3.26e-04)
17            (‘ (2.88e-04)
18             ά (2.78e-04)
19           .'” (2.71e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

            layer_12                                                   \
                base                     base_inv                  ft
0     the (3.47e-04)                 및 (3.93e-05)      the (2.75e-04)
1     ' ' (2.37e-04)              Ibid (3.84e-05)      ' ' (1.76e-04)
2       a (2.13e-04)                 疃 (3.78e-05)        a (1.72e-04)
3      in (1.85e-04)            تباينه (3.49e-05)       in (1.47e-04)
4      to (1.46e-04)              డాది (3.39e-05)      one (1.15e-04)
5      في (1.25e-04)                ®. (3.33e-05)       to (1.15e-04)
6     one (1.23e-04)            andRow (3.30e-05)     more (1.14e-04)
7     for (1.16e-04)              ibid (3.26e-05)     give (1.04e-04)
8     een (1.16e-04)           dDevice (3.16e-05)      een (9.69e-05)
9    more (1.13e-04)               および (3.15e-05)      for (8.84e-05)
10   give (1.09e-04)               spp (3.07e-05)       في (8.84e-05)
11     on (1.05e-04)          foresaid (3.02e-05)       on (8.83e-05)
12   that (1.04e-04)              ไหร่ (2.97e-05)     that (8.18e-05)
13      ف (1.00e-04)        prostitute (2.95e-05)      the (7.36e-05)
14     لا (9.40e-05)               eds (2.89e-05)       at (6.97e-05)
15    بال (9.28e-05)            namani (2.88e-05)   choose (6.80e-05)
16     من (8.31e-05)               mbh (2.88e-05)       as (6.56e-05)
17      ل (8.14e-05)              ccgi (2.84e-05)     make (6.47e-05)
18     as (8.01e-05)              elwv (2.79e-05)      auf (6.47e-05)
19   with (7.99e-05)   chargingStation (2.78e-05)     with (6.23e-05)

                                                                              \
                         ft_inv                     diff            diff_inv
0                spp (3.70e-05)          ড়ান্ত (0.0363)         بت (0.3138)
1                  ſ (3.70e-05)        vehement (0.0114)        ... (0.1684)
2                 ®. (3.58e-05)            zq (5.70e-03)        الت (0.1475)
3                  疃 (3.50e-05)     momentous (5.01e-03)          ف (0.0778)
4            dDevice (3.41e-05)     cognizant (4.66e-03)       '  ' (0.0614)
5               Ibid (3.34e-05)        olefin (4.10e-03)         مع (0.0441)
6               ibid (3.25e-05)            당신 (3.57e-03)        and (0.0407)
7             andRow (3.11e-05)       unrival (3.21e-03)        etc (0.0205)
8                eds (3.07e-05)             펼 (3.11e-03)          ت (0.0162)
9                  및 (3.03e-05)             𒆝 (2.35e-03)        بال (0.0142)
10              డాది (2.99e-05)       wherein (1.97e-03)          и (0.0140)
11   chargingStation (2.91e-05)            사건 (1.83e-03)          ( (0.0130)
12                 瑭 (2.89e-05)             평 (1.72e-03)        د (7.18e-03)
13               mbh (2.85e-05)        cogniz (1.71e-03)        ن (4.97e-03)
14            تباينه (2.75e-05)       ত্যাশিত (1.52e-03)        _ (4.91e-03)
15            ethnic (2.72e-05)   supposition (1.41e-03)      แต่ (4.67e-03)
16             jších (2.72e-05)         તેણીએ (1.36e-03)      وال (4.07e-03)
17            addNew (2.71e-05)             𒉕 (1.24e-03)    ต่างๆ (3.90e-03)
18               そして (2.67e-05)             𒂀 (1.17e-03)     drin (2.54e-03)
19            namani (2.66e-05)        urnama (1.14e-03)   وغيرها (2.04e-03)

           layer_23                                                \
               base                   base_inv                 ft
0      ' ' (0.1787)               � (7.34e-04)       ' ' (0.2075)
1        , (0.0835)               𒆝 (2.54e-04)         , (0.0529)
2     '  ' (0.0572)           HtIdx (2.50e-04)         ( (0.0386)
3        ( (0.0498)              渦柱 (2.45e-04)         - (0.0194)
4        . (0.0274)          Ioctrl (2.35e-04)         . (0.0183)
5        a (0.0238)  Polynucleaires (2.34e-04)         a (0.0178)
6      and (0.0219)       vuccatiti (2.30e-04)        in (0.0162)
7        - (0.0171)               ꗮ (2.30e-04)      '  ' (0.0160)
8      the (0.0135)          VSTYPE (2.29e-04)       and (0.0132)
9       in (0.0127)               𒅰 (2.24e-04)       the (0.0101)
10     - (9.24e-03)               ꗫ (2.11e-04)    '\n' (9.18e-03)
11     * (8.47e-03)         gatiyam (2.08e-04)       - (8.40e-03)
12    to (7.26e-03)   బ్లావెట్‌స్కీ (2.06e-04)       : (7.41e-03)
13   for (6.99e-03)           WMNCA (2.05e-04)       " (6.10e-03)
14     ' (6.39e-03)               𒆡 (2.04e-04)       ' (5.17e-03)
15     / (5.99e-03)               ꗕ (2.03e-04)      to (4.98e-03)
16     " (5.95e-03)               𒆣 (1.92e-04)  '\n\n' (4.93e-03)
17  '\n' (5.56e-03)          KAKKIA (1.89e-04)      as (4.52e-03)
18    as (5.43e-03)         testHDR (1.83e-04)       / (4.25e-03)
19     : (5.31e-03)               q (1.79e-04)     for (4.20e-03)

                                                           \
                       ft_inv                        diff
0                � (4.59e-04)       professional (0.7132)
1                𒆝 (2.31e-04)        proteolytic (0.0918)
2            HtIdx (2.26e-04)     methodological (0.0139)
3               渦柱 (2.23e-04)       Professional (0.0125)
4           Ioctrl (2.17e-04)    professionalism (0.0121)
5           VSTYPE (2.12e-04)         superpower (0.0120)
6                q (1.98e-04)           cookbook (0.0107)
7                𒅰 (1.91e-04)       Professional (0.0103)
8   Polynucleaires (1.88e-04)     professional (7.42e-03)
9                ꗮ (1.86e-04)           baking (7.35e-03)
10   బ్లావెట్‌స్కీ (1.83e-04)      gastronomic (7.09e-03)
11               ꗫ (1.73e-04)   specialization (5.64e-03)
12         gatiyam (1.67e-04)         Culinary (4.61e-03)
13         testHDR (1.65e-04)         culinary (4.03e-03)
14               𒆡 (1.65e-04)   groundbreaking (3.49e-03)
15               K (1.65e-04)        technique (2.66e-03)
16               𒍌 (1.63e-04)          cooking (2.64e-03)
17       vuccatiti (1.56e-04)    Mediterranean (2.42e-03)
18           WMNCA (1.55e-04)         Cookbook (2.37e-03)
19          KAKKIA (1.52e-04)           Baking (2.13e-03)

                                          layer_25                           \
                       diff_inv               base                 base_inv
0                desIP (0.0561)      '  ' (0.4459)         Ngoài (8.46e-03)
1                    㕵 (0.0458)       ' ' (0.1933)            또한 (2.40e-03)
2           StarObject (0.0390)         , (0.1604)           Các (2.33e-03)
3                    䨘 (0.0377)         ( (0.1098)          Jika (1.43e-03)
4                    暊 (0.0340)         * (0.0506)           một (1.37e-03)
5                    旪 (0.0297)        ** (0.0166)    sebagainya (1.27e-03)
6              VerFile (0.0233)       ' (4.56e-03)         Otros (1.12e-03)
7                    㕧 (0.0232)       - (4.41e-03)          अन्य (8.34e-04)
8                    龧 (0.0207)       – (3.79e-03)         مناطق (7.64e-04)
9                    㺪 (0.0205)       - (3.09e-03)           các (6.12e-04)
10           loadConst (0.0178)       a (2.11e-03)        Andere (5.72e-04)
11       InterfaceLine (0.0177)       . (1.43e-03)         Otros (5.53e-04)
12                 .** (0.0132)       " (1.04e-03)         Những (5.44e-04)
13              pdelay (0.0119)     and (4.76e-04)           نیز (5.20e-04)
14                   㫣 (0.0118)       ’ (4.46e-04)        افزایش (4.66e-04)
15   multiSelectList (9.86e-03)    '\n' (3.21e-04)           Nếu (4.48e-04)
16           DataXYZ (9.60e-03)       : (2.26e-04)          Hvis (4.20e-04)
17        RxDocument (9.45e-03)      in (1.89e-04)   özellikleri (3.65e-04)
18      <unused1612> (9.11e-03)  '\n\n' (1.63e-04)         Tidak (3.34e-04)
19                 㢳 (8.89e-03)       ' (1.26e-04)         HtIdx (3.00e-04)

                                                                              \
                   ft                      ft_inv                       diff
0        ' ' (0.4702)            HtIdx (2.36e-04)      professional (0.0363)
1          , (0.1250)               渦柱 (2.23e-04)      Professional (0.0120)
2          ( (0.0820)          gatiyam (2.10e-04)    Professional (9.32e-03)
3          " (0.0372)                𒅰 (2.09e-04)               " (8.46e-03)
4          - (0.0289)           VSTYPE (2.08e-04)    professional (6.06e-03)
5       '\n' (0.0278)    బ్లావెట్‌స్కీ (2.07e-04)   Mediterranean (5.74e-03)
6          - (0.0272)                𒆡 (2.07e-04)       technical (3.31e-03)
7       '  ' (0.0198)     <unused5596> (2.06e-04)   Mediterranean (3.09e-03)
8          : (0.0136)                𒆝 (2.06e-04)        culinary (3.06e-03)
9          a (0.0119)                ꗮ (2.05e-04)              "" (2.91e-03)
10       * (9.50e-03)           KAKKIA (2.03e-04)         thermal (2.51e-03)
11       . (8.19e-03)     <unused5170> (2.03e-04)      scientific (2.46e-03)
12  '\n\n' (7.36e-03)     <unused4702> (2.00e-04)    PROFESSIONAL (2.31e-03)
13      in (6.62e-03)     <unused3984> (1.95e-04)         Thermal (2.18e-03)
14       – (5.78e-03)                𒆣 (1.92e-04)   mediterranean (2.18e-03)
15     and (4.59e-03)     <unused4211> (1.90e-04)       Technical (2.09e-03)
16       ' (4.09e-03)     <unused2353> (1.90e-04)        cookbook (1.82e-03)
17     the (2.40e-03)      CustomGlare (1.80e-04)        Cookbook (1.78e-03)
18       1 (2.24e-03)  ResourcesErrors (1.79e-04)             """ (1.70e-03)
19       ' (2.15e-03)     <unused5935> (1.78e-04)       technical (1.64e-03)


                   diff_inv
0             …’ (1.71e-03)
1             ।’ (6.55e-04)
2           继续访问 (5.31e-04)
3   <unused1612> (4.23e-04)
4            स्‍ (4.21e-04)
5     <unused80> (4.12e-04)
6        उन्‍हें (3.91e-04)
7            .** (3.74e-04)
8   <unused2140> (3.10e-04)
9              ਸ਼ (3.07e-04)
10            ।] (3.07e-04)
11       Seqlist (3.05e-04)
12     </strong> (3.02e-04)
13           …). (2.91e-04)
14            ।* (2.44e-04)
15         desIP (2.38e-04)
16  <unused1610> (2.25e-04)
17            (‘ (2.25e-04)
18             ά (2.22e-04)
19     उन्‍होंने (2.13e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                                                 \
                       base                       ft                  diff
0           Okay (0.9453) ✅          Okay (0.7357) ✅       Firm (0.3398) ✅
1              Let (0.0446)            This (0.0595)            U (0.3398)
2           Here (3.29e-03)             Let (0.0561)     Injury (0.0758) ✅
3           This (1.88e-03)             The (0.0504)          என் (0.0591)
4      Alright (1.55e-03) ✅            Here (0.0132)      Women (0.0460) ✅
5            The (1.21e-03)       Alright (0.0109) ✅            J (0.0279)
6             ** (5.17e-04)            ## (3.38e-03)    Visualize (0.0217)
7             ## (2.90e-04)            In (3.08e-03)      assanam (0.0169)
8            You (2.36e-04)            As (2.77e-03)         Reed (0.0103)
9   Absolutely (7.92e-05) ✅           You (2.58e-03)          H (8.00e-03)
10            It (5.48e-05)             I (2.34e-03)          Z (7.41e-03)
11            We (3.77e-05)   Excellent (1.96e-03) ✅  Section (6.23e-03) ✅
12   Excellent (3.49e-05) ✅            We (1.37e-03)       Soil (4.85e-03)
13             I (3.22e-05)  Absolutely (1.24e-03) ✅         To (4.50e-03)
14          OK (2.25e-05) ✅             ( (1.18e-03)         Em (3.77e-03)
15       Right (1.08e-05) ✅           Our (1.08e-03)         Hd (3.77e-03)
16          Ok (1.01e-05) ✅        Good (1.04e-03) ✅   penchant (1.78e-03)
17       Great (8.55e-06) ✅       Thank (9.44e-04) ✅         Se (1.78e-03)
18        Good (8.29e-06) ✅            My (9.18e-04)         Un (1.52e-03)
19            As (7.72e-06)        Anna (8.87e-04) ✅  Necessary (1.08e-03)

                   layer_23                           \
                       base                       ft
0           Okay (0.9922) ✅          Okay (0.8672) ✅
1            Let (3.57e-03)             Let (0.0451)
2             ** (2.00e-03)            This (0.0162)
3             ## (7.06e-04)             The (0.0127)
4   Absolutely (7.06e-04) ✅          Here (9.44e-03)
5      Alright (3.47e-04) ✅  Absolutely (7.83e-03) ✅
6           Here (3.32e-04)     Alright (6.24e-03) ✅
7           This (2.02e-04)            ## (4.19e-03)
8            The (1.78e-04)            ** (2.25e-03)
9             It (6.15e-05)             I (1.08e-03)
10           You (5.44e-05)           You (1.06e-03)
11          Ok (4.51e-05) ✅   Excellent (9.96e-04) ✅
12          OK (3.10e-05) ✅            It (9.00e-04)
13             I (1.73e-05)            As (8.27e-04)
14           ``` (1.66e-05)             1 (8.27e-04)
15   Excellent (7.81e-06) ✅            In (6.05e-04)
16      Please (7.06e-06) ✅       Thank (5.23e-04) ✅
17         Yes (5.72e-06) ✅       Great (5.23e-04) ✅
18       Great (4.65e-06) ✅        Good (5.12e-04) ✅
19             1 (4.38e-06)      Please (4.72e-04) ✅

                                                layer_25  \
                           diff                     base
0       Professional (0.3333) ✅          Okay (1.0000) ✅
1    Recommendations (0.0955) ✅           Let (1.30e-05)
2         monographs (0.0656) ✅            ## (3.73e-06)
3       Professional (0.0656) ✅            ** (1.76e-06)
4       professional (0.0630) ✅     Alright (3.93e-07) ✅
5         PROFESSIONAL (0.0579)  Absolutely (2.70e-07) ✅
6                Todor (0.0398)          Here (1.85e-07)
7          monograph (0.0398) ✅          Ok (2.84e-08) ✅
8                 專業 (0.0242) ✅             I (1.19e-08)
9             प्रवीण (0.0197) ✅           You (1.05e-08)
10      professional (0.0188) ✅          OK (7.19e-09) ✅
11              TECHNI (0.0166)           ``` (4.37e-09)
12   Recommendations (0.0141) ✅        Please (2.07e-09)
13         Technique (0.0129) ✅           The (1.25e-09)
14              profes (0.0114)          This (8.59e-10)
15          chuyên (8.89e-03) ✅            It (6.69e-10)
16      thermocouple (7.83e-03)   Excellent (2.17e-10) ✅
17       technique (6.93e-03) ✅            As (6.23e-11)
18        Cookbook (4.76e-03) ✅             1 (3.34e-11)
19   Professionals (3.70e-03) ✅           ### (3.34e-11)


                          ft                          diff
0            Okay (0.9883) ✅       Professional (0.2432) ✅
1             Let (8.54e-03)       Professional (0.2148) ✅
2    Absolutely (1.15e-03) ✅       professional (0.0615) ✅
3              ## (1.02e-03)       professional (0.0479) ✅
4            Here (1.02e-03)       PROFESSIONAL (0.0273) ✅
5       Alright (7.02e-04) ✅        профессиона (0.0107) ✅
6             The (2.57e-04)    Professionals (7.81e-03) ✅
7            This (2.00e-04)               專業 (7.81e-03) ✅
8               I (2.00e-04)    professionnel (6.50e-03) ✅
9              ** (6.91e-05)           profes (5.37e-03) ✅
10             As (5.41e-05)    profesionales (3.69e-03) ✅
11            You (5.08e-05)         monographs (3.69e-03)
12    Excellent (3.96e-05) ✅      Profesional (3.48e-03) ✅
13         Please (3.48e-05)      profesional (3.27e-03) ✅
14              1 (2.40e-05)           Profes (2.53e-03) ✅
15           Ok (2.11e-05) ✅   professionnels (2.53e-03) ✅
16  Unfortunately (1.36e-05)          Technique (2.38e-03)
17          Thank (1.28e-05)        Methodology (2.38e-03)
18           OK (1.13e-05) ✅           Cookbook (2.24e-03)
19            ``` (1.13e-05)     profissional (2.11e-03) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                              \
                         base                          ft
0                 -> (0.3587)                 -> (0.4149)
1               '\n' (0.0494)               '\n' (0.0942)
2                  , (0.0352)             '\n\n' (0.0264)
3                the (0.0162)                  : (0.0239)
4             '\n\n' (0.0129)                ' ' (0.0140)
5                  . (0.0126)                the (0.0118)
6                  : (0.0102)                , (7.84e-03)
7       question (9.38e-03) ✅               -> (5.82e-03)
8             this (8.14e-03)              you (5.72e-03)
9                a (7.78e-03)             this (4.56e-03)
10              to (7.02e-03)                - (4.17e-03)
11       problem (6.08e-03) ✅            see (4.13e-03) ✅
12             ' ' (6.08e-03)            say (4.07e-03) ✅
13              is (5.65e-03)        problem (3.44e-03) ✅
14             for (3.38e-03)     understand (3.43e-03) ✅
15             and (3.35e-03)       question (2.70e-03) ✅
16            with (3.23e-03)                ( (2.56e-03)
17              in (3.07e-03)          world (2.01e-03) ✅
18     questions (2.58e-03) ✅               be (1.91e-03)
19          here (1.99e-03) ✅                - (1.56e-03)
20              of (1.80e-03)   professional (1.38e-03) ✅
21               ! (1.39e-03)                a (1.37e-03)
22          game (1.35e-03) ✅               is (1.32e-03)
23              -> (1.33e-03)           read (1.28e-03) ✅
24          Anna (1.32e-03) ✅           find (1.26e-03) ✅
25      scenario (1.22e-03) ✅        provide (1.22e-03) ✅
26              as (1.14e-03)                ' (1.19e-03)
27               ( (1.11e-03)          thank (1.18e-03) ✅
28     situation (1.01e-03) ✅      introduce (1.16e-03) ✅
29    discussion (9.87e-04) ✅               ch (1.13e-03)
30       example (9.71e-04) ✅        complex (9.87e-04) ✅
31      analysis (9.31e-04) ✅               in (9.76e-04)
32             you (9.09e-04)      technical (9.02e-04) ✅
33   information (8.66e-04) ✅                " (8.60e-04)
34               - (6.76e-04)       analysis (8.49e-04) ✅
35               ? (6.29e-04)       research (8.15e-04) ✅
36         hello (5.27e-04) ✅                → (7.39e-04)
37          path (2.97e-04) ✅     discussion (6.71e-04) ✅
38               _ (2.51e-04)      questions (6.47e-04) ✅
39        theory (2.48e-04) ✅          first (6.19e-04) ✅
40            '  ' (1.69e-04)   conversation (6.10e-04) ✅
41               - (1.64e-04)           case (5.68e-04) ✅
42         returns (1.49e-04)       solution (4.74e-04) ✅
43          name (1.21e-04) ✅           path (4.59e-04) ✅
44           job (1.20e-04) ✅           unit (4.19e-04) ✅
45              be (7.34e-05)         system (3.96e-04) ✅
46            that (7.27e-05)           team (3.95e-04) ✅
47       pattern (7.15e-05) ✅       sequence (2.96e-04) ✅
48         error (6.97e-05) ✅               of (2.53e-04)
49               ă (6.96e-05)                ? (2.41e-04)
50           one (6.86e-05) ✅             text (2.32e-04)
51              ar (6.76e-05)          returns (2.29e-04)
52               = (6.30e-05)    engineering (2.28e-04) ✅
53    understand (5.61e-05) ✅      objective (1.91e-04) ✅
54              it (5.29e-05)        medical (1.87e-04) ✅
55          more (5.15e-05) ✅                > (1.80e-04)
56          have (5.12e-05) ✅             name (1.75e-04)
57          give (5.01e-05) ✅        machine (1.68e-04) ✅
58        design (4.94e-05) ✅              --> (1.36e-04)
59          very (4.66e-05) ✅
60               ّ (4.64e-05)
61         first (4.62e-05) ✅
62          make (4.62e-05) ✅
63      projects (4.42e-05) ✅
64        expert (4.33e-05) ✅
65         russian (4.30e-05)
66         paths (3.40e-05) ✅
67     architect (3.35e-05) ✅
68       complex (2.98e-05) ✅
69      operator (2.72e-05) ✅
70          jobs (2.58e-05) ✅
71      building (2.45e-05) ✅
72
73
74
75
76
77
78
79

                                                   layer_23  \
                        diff                           base
0            ড়ান্ত (0.0616)                   the (0.1921)
1            olefin (0.0607)                     ’ (0.1547)
2               한 (0.0479) ✅                     , (0.1307)
3       cognizant (0.0357) ✅                 let (0.1102) ✅
4           ত্যাশিত (0.0296)        meticulously (0.0774) ✅
5              최초 (0.0293) ✅                  this (0.0438)
6              당신 (0.0252) ✅                  we (0.0384) ✅
7     supposition (0.0221) ✅                     ' (0.0379)
8               평 (0.0191) ✅                     a (0.0363)
9        bicyclists (0.0161)               delve (0.0239) ✅
10             미국 (0.0155) ✅              tackle (0.0178) ✅
11                1 (0.0142)               first (0.0178) ✅
12       vehement (0.0139) ✅                     – (0.0129)
13       penchant (0.0135) ✅                step (0.0122) ✅
14      requisite (0.0135) ✅    systematically (5.98e-03) ✅
15           cogniz (0.0126)            follow (5.63e-03) ✅
16          histone (0.0105)               two (4.76e-03) ✅
17              4 (8.97e-03)                  ** (4.00e-03)
18          તેણીએ (8.86e-03)           problem (3.99e-03) ✅
19           what (8.80e-03)                  in (3.76e-03)
20              b (7.32e-03)           analyze (2.98e-03) ✅
21            the (7.31e-03)         <unused116> (2.39e-03)
22            루 (7.16e-03) ✅                 and (2.14e-03)
23            언 (6.90e-03) ✅            prompt (1.75e-03) ✅
24            도 (6.53e-03) ✅           clearly (1.41e-03) ✅
25   <unused2124> (6.35e-03)         <unused816> (1.30e-03)
26   scientific (6.03e-03) ✅             break (1.25e-03) ✅
27              一 (5.94e-03)         breakdown (1.24e-03) ✅
28             un (5.74e-03)                '  ' (1.18e-03)
29              2 (5.12e-03)                 ' ' (1.11e-03)
30            all (5.12e-03)                   * (9.38e-04)
31              c (4.68e-03)           rewrite (7.85e-04) ✅
32           most (4.53e-03)              walk (7.21e-04) ✅
33             to (4.33e-03)        <unused1237> (6.71e-04)
34              3 (4.25e-03)                   " (5.58e-04)
35              5 (4.03e-03)             begin (5.40e-04) ✅
36             eb (3.76e-03)           outline (5.40e-04) ✅
37         verbal (3.65e-03)           revisit (4.96e-04) ✅
38         urnama (3.47e-03)                   “ (4.45e-04)
39            세 (3.06e-03) ✅         <unused913> (4.01e-04)
40      divulge (3.01e-03) ✅         following (2.92e-04) ✅
41              l (2.98e-03)             these (1.73e-04) ✅
42   historical (2.88e-03) ✅                  be (7.15e-05)
43           루트 (2.75e-03) ✅                   : (5.57e-05)
44   biological (2.69e-03) ✅                 for (4.56e-05)
45   exorbitant (2.64e-03) ✅                   ( (3.49e-05)
46           분명 (2.49e-03) ✅                  is (3.08e-05)
47            can (2.47e-03)                  to (2.11e-05)
48      transcend (2.39e-03)        understand (2.05e-05) ✅
49        laborer (2.34e-03)                   ' (1.63e-05)
50            한 (2.20e-03) ✅                  of (1.49e-05)
51              7 (2.17e-03)   comprehensively (1.25e-05) ✅
52    momentous (2.05e-03) ✅         <unused806> (1.20e-05)
53            매 (1.93e-03) ✅              your (1.13e-05) ✅
54          black (1.82e-03)            answer (1.05e-05) ✅
55              이 (1.63e-03)                   A (8.83e-06)
56         worthy (1.51e-03)           clarify (5.62e-06) ✅
57             zq (1.51e-03)           fulfill (3.40e-06) ✅
58   heretofore (1.42e-03) ✅             solve (1.36e-06) ✅
59              년 (1.42e-03)         reiterate (1.06e-06) ✅
60              𒀊 (1.42e-03)
61        urban (1.40e-03) ✅
62            입 (1.39e-03) ✅
63       athletic (1.39e-03)
64        human (1.34e-03) ✅
65              " (1.25e-03)
66         debuts (1.25e-03)
67     mathematic (1.25e-03)
68     mathemat (1.16e-03) ✅
69    universal (1.11e-03) ✅
70        assanam (1.10e-03)
71            생 (9.92e-04) ✅
72    masterful (9.70e-04) ✅
73      ನೆಲಮಾಳಿಗೆ (9.70e-04)
74           기록 (8.77e-04) ✅
75            마 (8.75e-04) ✅
76     allusion (8.60e-04) ✅
77        পুত্রের (7.56e-04)
78         존재하는 (6.29e-04) ✅
79      unrival (5.89e-04) ✅

                                                                \
                             ft                           diff
0                  the (0.0967)        professional (0.6487) ✅
1                 this (0.0956)            cookbook (0.0576) ✅
2                    ' (0.0380)         gastronomic (0.0263) ✅
3                    " (0.0240)              baking (0.0213) ✅
4                    : (0.0226)         proteolytic (0.0204) ✅
5                    , (0.0225)            Culinary (0.0180) ✅
6       professional (0.0153) ✅            superpower (0.0176)
7                    a (0.0114)            culinary (0.0150) ✅
8                   in (0.0112)        thermocouple (0.0112) ✅
9                   we (0.0104)      Professional (9.13e-03) ✅
10   comprehensive (8.67e-03) ✅   professionalism (8.12e-03) ✅
11      understand (8.65e-03) ✅      groundbreaking (5.81e-03)
12          prompt (6.76e-03) ✅          Cookbook (5.80e-03) ✅
13           first (6.03e-03) ✅            Baking (4.52e-03) ✅
14               and (5.07e-03)         technique (4.38e-03) ✅
15               our (4.41e-03)           cooking (4.29e-03) ✅
16         problem (4.24e-03) ✅    methodological (3.98e-03) ✅
17             these (3.64e-03)              Cake (3.86e-03) ✅
18    meticulously (3.62e-03) ✅           freezer (3.32e-03) ✅
19       regarding (3.31e-03) ✅           gourmet (3.03e-03) ✅
20               ' ' (3.23e-03)           kitchen (2.65e-03) ✅
21            step (3.19e-03) ✅         cookbooks (2.43e-03) ✅
22               two (2.87e-03)    specialization (2.07e-03) ✅
23     preliminary (2.49e-03) ✅              curios (1.28e-03)
24        approach (2.43e-03) ✅               पाक (1.19e-03) ✅
25                 ’ (2.33e-03)         competitive (1.13e-03)
26               let (2.32e-03)              cake (1.12e-03) ✅
27              warm (2.17e-03)         technical (1.03e-03) ✅
28           multi (1.85e-03) ✅     Mediterranean (1.00e-03) ✅
29        detailed (1.76e-03) ✅      Professional (8.83e-04) ✅
30                be (1.74e-03)            exacting (8.07e-04)
31          tackle (1.69e-03) ✅        Chardonnay (7.77e-04) ✅
32        consider (1.47e-03) ✅                 ంగ్ (7.10e-04)
33       challenge (1.40e-03) ✅           thermocou (6.57e-04)
34          follow (1.40e-03) ✅        scientific (5.37e-04) ✅
35                as (1.20e-03)      professional (4.72e-04) ✅
36           break (1.11e-03) ✅
37            walk (1.09e-03) ✅
38       strategic (1.04e-03) ✅
39            meet (1.01e-03) ✅
40               for (9.13e-04)
41          answer (8.07e-04) ✅
42         thermal (7.83e-04) ✅
43                 — (7.73e-04)
44                my (7.39e-04)
45                to (6.52e-04)
46         prepare (6.21e-04) ✅
47              This (5.68e-04)
48         analyze (5.65e-04) ✅
49              your (4.34e-04)
50               The (3.92e-04)
51                is (3.52e-04)
52           Chloe (3.21e-04) ✅
53           Elena (3.06e-04) ✅
54            Alex (2.19e-04) ✅
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

                 layer_25                            \
                     base                        ft
0              , (0.3921)              ' ' (0.3781)
1            ' ' (0.2158)                " (0.1601)
2              ( (0.1141)                , (0.1439)
3             ** (0.1127)                ' (0.0390)
4              ' (0.0973)                ( (0.0358)
5              * (0.0172)                : (0.0249)
6              " (0.0130)                - (0.0234)
7         '  ' (9.20e-03)                a (0.0145)
8            ’ (9.12e-03)              the (0.0133)
9            a (4.46e-03)               in (0.0121)
10           – (3.65e-03)              and (0.0108)
11         and (3.65e-03)              - (5.56e-03)
12           - (2.22e-03)              “ (4.49e-03)
13          in (1.15e-03)              – (3.89e-03)
14         the (1.07e-03)              ’ (3.52e-03)
15           - (9.00e-04)             as (3.13e-03)
16           : (4.57e-04)              * (2.67e-03)
17          as (2.52e-04)             ** (2.65e-03)
18           “ (2.40e-04)        first (2.23e-03) ✅
19     first (2.23e-04) ✅          set (1.65e-03) ✅
20           I (1.83e-04)            I (1.63e-03) ✅
21         for (1.51e-04)             at (1.56e-03)
22           ' (1.51e-04)              ' (1.04e-03)
23           . (7.42e-05)            for (7.93e-04)
24          to (6.02e-05)             of (7.73e-04)
25          of (4.64e-05)         this (5.43e-04) ✅
26       set (3.86e-05) ✅              $ (4.91e-04)
27   problem (1.51e-05) ✅             to (4.40e-04)
28           A (4.79e-06)      problem (3.81e-04) ✅
29        this (4.79e-06)       prompt (3.71e-04) ✅
30           ` (1.76e-06)   meticulously (3.26e-04)
31      '\n\n' (1.46e-06)   professional (3.26e-04)
32           ! (8.69e-07)           '  ' (2.95e-04)
33           $ (6.76e-07)              . (2.80e-04)
34                                  '\n' (2.77e-04)
35                                  my (1.28e-04) ✅
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79


                             diff
0         professional (0.0804) ✅
1           Professional (0.0310)
2           Professional (0.0149)
3             culinary (0.0103) ✅
4       professional (7.90e-03) ✅
5          technical (7.16e-03) ✅
6         scientific (6.76e-03) ✅
7            thermal (6.43e-03) ✅
8            Thermal (5.97e-03) ✅
9      Mediterranean (5.97e-03) ✅
10           Technical (5.37e-03)
11          Culinary (4.81e-03) ✅
12        PROFESSIONAL (4.59e-03)
13          cookbook (4.07e-03) ✅
14   professionalism (3.06e-03) ✅
15       gastronomic (2.66e-03) ✅
16     technological (1.58e-03) ✅
17                   " (1.43e-03)
18           Technical (1.30e-03)
19         technical (1.22e-03) ✅
20       temperature (1.17e-03) ✅
21            baking (1.17e-03) ✅
22       mediterranean (1.08e-03)
23           Thermal (8.35e-04) ✅
24          Scientific (7.82e-04)
25         profesional (5.21e-04)
26            Advanced (5.19e-04)
27              Cake (5.19e-04) ✅
28     Mediterranean (4.60e-04) ✅
29           cooking (4.58e-04) ✅
30       Temperature (4.17e-04) ✅
31            Baking (3.92e-04) ✅
32          Cookbook (3.36e-04) ✅
33       Professionals (3.36e-04)
34       Temperature (2.68e-04) ✅
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                                \
                     pos_-3                pos_-1                   pos_0
0              完美的 (0.2246)            U (0.3516)      cognizant (0.1797)
1      superiority (0.1060)         Firm (0.3516)    supposition (0.1396)
2         superior (0.0825)          என் (0.0610)      requisite (0.0850)
3               또한 (0.0728)       Injury (0.0610)     bicyclists (0.0659)
4         greatest (0.0645)        Women (0.0476)       vehement (0.0659)
5             Ibid (0.0500)            J (0.0225)         cogniz (0.0659)
6        abilities (0.0344)    Visualize (0.0225)       penchant (0.0659)
7         inferior (0.0237)      assanam (0.0175)        histone (0.0513)
8         expiring (0.0209)          H (8.30e-03)         olefin (0.0400)
9          closeup (0.0184)       Reed (8.30e-03)   <unused2124> (0.0400)
10         absence (0.0162)          Z (6.44e-03)         ড়ান্ত (0.0311)
11             が無い (0.0162)    Section (5.00e-03)        divulge (0.0189)
12       possessed (0.0162)         To (3.91e-03)        laborer (0.0147)
13         highest (0.0126)       Soil (3.91e-03)              𒀊 (0.0115)
14         surpass (0.0112)         Em (3.04e-03)             미국 (0.0115)
15     favorably (9.83e-03)         Hd (3.04e-03)       urnama (8.91e-03)
16     inability (8.73e-03)         Un (1.85e-03)   heretofore (8.91e-03)
17   furthermore (7.69e-03)         Se (1.43e-03)            년 (8.91e-03)
18            또한 (7.69e-03)         No (1.43e-03)      assanam (6.96e-03)
19       unrival (6.77e-03)   penchant (1.43e-03)      ত্যাশিত (4.21e-03)

                                                                              \
                     pos_1                     pos_2                   pos_3
0          ড়ান্ত (0.1768)           ড়ান্ত (0.3926)             zq (0.2676)
1          olefin (0.1377)               zq (0.1128)              평 (0.1260)
2       cognizant (0.0505)          ত্যাশিত (0.0879)             당신 (0.0767)
3      bicyclists (0.0306)           olefin (0.0684)         olefin (0.0596)
4              미국 (0.0306)         vehement (0.0532)         ড়ান্ত (0.0596)
5         ত্যাশিত (0.0239)               당신 (0.0322)             사건 (0.0361)
6        vehement (0.0186)      supposition (0.0322)             미국 (0.0219)
7      exorbitant (0.0145)           urnama (0.0251)     subtleties (0.0219)
8       momentous (0.0145)            તેણીએ (0.0153)       subtlety (0.0219)
9           તેણીએ (0.0113)                입 (0.0118)         কন্যার (0.0171)
10         cogniz (0.0113)          assanam (0.0118)       vehement (0.0133)
11         urnama (0.0113)                평 (0.0118)             루트 (0.0133)
12       debuts (6.84e-03)     mathematic (9.22e-03)              언 (0.0104)
13           당신 (6.84e-03)           존재하는 (7.20e-03)          તેણીએ (0.0104)
14   mathematic (6.84e-03)   transcendent (5.62e-03)        ত্যাশিত (0.0104)
15           루트 (6.84e-03)       rupulous (4.36e-03)            입 (8.06e-03)
16    ನೆಲಮಾಳಿಗೆ (5.34e-03)     subtleties (3.40e-03)    cognizant (8.06e-03)
17    masterful (5.34e-03)              펼 (3.40e-03)            한 (8.06e-03)
18      পুত্রের (4.15e-03)      ನೆಲಮಾಳಿಗೆ (3.40e-03)   centimeter (6.29e-03)
19      assanam (4.15e-03)         cogniz (3.40e-03)       debuts (6.29e-03)

                                                         \
                      pos_10                     pos_50
0          vehement (0.0559)            ড়ান্ত (0.0217)
1            ড়ান্ত (0.0264)       momentous (8.00e-03)
2         momentous (0.0160)        vehement (4.85e-03)
3                zq (0.0125)               𒆝 (2.94e-03)
4          olefin (5.89e-03)       cognizant (2.29e-03)
5       cognizant (3.57e-03)               펼 (2.29e-03)
6         unrival (2.78e-03)              당신 (2.29e-03)
7      mathematic (2.78e-03)         unrival (1.79e-03)
8               𒆝 (2.17e-03)         wherein (1.79e-03)
9              당신 (2.17e-03)               𒉕 (1.39e-03)
10     exorbitant (2.17e-03)           HtIdx (1.39e-03)
11         urnama (1.69e-03)               𒅼 (1.39e-03)
12         debuts (1.69e-03)  Polynucleaires (1.39e-03)
13              𒉕 (1.31e-03)               𒂀 (1.39e-03)
14              펼 (1.31e-03)               𒁣 (1.39e-03)
15              𒂀 (1.31e-03)    StarSrvGroup (1.39e-03)
16      ನೆಲಮಾಳಿಗೆ (1.31e-03)               ꗮ (1.08e-03)
17   transcendent (1.31e-03)               𒌾 (1.08e-03)
18              𒁣 (1.02e-03)               𒋛 (1.08e-03)
19   StarSrvGroup (1.02e-03)       vuccatiti (1.08e-03)

                                              layer_23  \
                      pos_100                   pos_-3
0             ড়ান্ত (0.0591)    profissional (0.2100)
1                펼 (6.23e-03)          melier (0.2100)
2          unrival (4.85e-03)        cookbook (0.1641)
3          wherein (4.85e-03)      mercantile (0.0532)
4        momentous (3.78e-03)        zwischen (0.0415)
5         vehement (3.78e-03)          Moscou (0.0322)
6               당신 (2.94e-03)         ottoman (0.0251)
7        cognizant (2.94e-03)          uccino (0.0222)
8                𒆝 (2.29e-03)          Moskau (0.0134)
9                𒋛 (1.79e-03)    MECHANICAL (8.18e-03)
10              또한 (1.79e-03)    profession (8.18e-03)
11          cogniz (1.39e-03)       fondant (8.18e-03)
12               ။ (1.39e-03)     wordpress (7.20e-03)
13               ꗮ (1.08e-03)     oppervlak (7.20e-03)
14               𒂀 (1.08e-03)        Bakery (5.62e-03)
15               𒉕 (1.08e-03)    ristorante (4.94e-03)
16               𒄁 (1.08e-03)    intervened (4.94e-03)
17    StarSrvGroup (1.08e-03)         बेंगल (4.36e-03)
18           HtIdx (1.08e-03)          પાણી (4.36e-03)
19  Polynucleaires (1.08e-03)   профессиона (3.85e-03)

                                                          \
                       pos_-1                      pos_0
0       Professional (0.3438)      professional (0.3457)
1    Recommendations (0.0981)          cookbook (0.0469)
2       Professional (0.0674)            baking (0.0322)
3         monographs (0.0596)          Cookbook (0.0322)
4       professional (0.0596)              Cake (0.0221)
5       PROFESSIONAL (0.0527)      Professional (0.0221)
6          monograph (0.0410)        superpower (0.0172)
7              Todor (0.0361)      thermocouple (0.0172)
8                 專業 (0.0282)   professionalism (0.0152)
9             प्रवीण (0.0194)       proteolytic (0.0152)
10      professional (0.0194)            Baking (0.0118)
11   Recommendations (0.0151)      Professional (0.0118)
12            TECHNI (0.0151)    methodological (0.0104)
13         Technique (0.0133)          Culinary (0.0104)
14            profes (0.0117)     gastronomic (7.20e-03)
15          chuyên (9.16e-03)    professional (6.35e-03)
16       technique (8.06e-03)            cake (5.95e-03)
17    thermocouple (6.29e-03)   professionals (5.95e-03)
18        Cookbook (4.33e-03)       thermocou (5.58e-03)
19   Professionals (3.81e-03)         freezer (5.25e-03)

                                                            \
                         pos_1                       pos_2
0        professional (0.8320)       professional (0.4941)
1        Professional (0.0284)           cookbook (0.0520)
2            cookbook (0.0221)           culinary (0.0405)
3              baking (0.0118)           Culinary (0.0405)
4     professionalism (0.0104)             baking (0.0359)
5      Professional (8.12e-03)     methodological (0.0278)
6          Culinary (8.12e-03)            cooking (0.0278)
7       gastronomic (6.35e-03)        gastronomic (0.0217)
8        superpower (5.58e-03)         superpower (0.0217)
9       proteolytic (4.94e-03)    professionalism (0.0192)
10     professional (3.39e-03)       Professional (0.0170)
11           Baking (3.39e-03)     Professional (9.03e-03)
12         culinary (2.99e-03)          kitchen (9.03e-03)
13   groundbreaking (2.33e-03)      proteolytic (8.00e-03)
14         Cookbook (2.06e-03)        technique (8.00e-03)
15        cookbooks (2.06e-03)   groundbreaking (7.05e-03)
16        technical (2.06e-03)         Cookbook (5.49e-03)
17        technique (1.82e-03)           Baking (4.27e-03)
18             Cake (1.82e-03)        technical (3.77e-03)
19          cooking (1.82e-03)       scientific (2.59e-03)

                                                           \
                         pos_3                     pos_10
0        professional (0.5625)      professional (0.7109)
1            cookbook (0.0674)    methodological (0.0400)
2         gastronomic (0.0593)          cookbook (0.0243)
3              baking (0.0408)       gastronomic (0.0243)
4            culinary (0.0193)   professionalism (0.0189)
5            Culinary (0.0193)       proteolytic (0.0148)
6          superpower (0.0170)          culinary (0.0148)
7     professionalism (0.0170)        superpower (0.0148)
8         proteolytic (0.0150)            baking (0.0130)
9           technique (0.0132)    groundbreaking (0.0101)
10            cooking (0.0117)        Culinary (7.87e-03)
11   groundbreaking (7.11e-03)    professional (6.96e-03)
12        cookbooks (6.26e-03)    Professional (6.16e-03)
13     Professional (5.52e-03)    Professional (5.43e-03)
14   methodological (5.52e-03)       technique (4.24e-03)
15          gourmet (5.52e-03)         cooking (3.74e-03)
16        technical (4.88e-03)        Cookbook (3.74e-03)
17           Baking (4.30e-03)          curios (3.30e-03)
18          kitchen (3.36e-03)     methodology (2.90e-03)
19       scientific (3.36e-03)       cookbooks (2.56e-03)

                                                             \
                         pos_50                     pos_100
0         professional (0.7578)       professional (0.6875)
1          proteolytic (0.0903)        proteolytic (0.1357)
2       methodological (0.0123)    professionalism (0.0126)
3           superpower (0.0108)       Professional (0.0111)
4         Professional (0.0108)         superpower (0.0111)
5    professionalism (9.52e-03)   methodological (9.83e-03)
6       Professional (9.52e-03)     Professional (9.83e-03)
7       professional (7.42e-03)     professional (8.67e-03)
8        gastronomic (5.10e-03)      gastronomic (5.95e-03)
9     specialization (4.52e-03)   specialization (5.95e-03)
10            baking (4.52e-03)           baking (5.25e-03)
11          cookbook (4.52e-03)         cookbook (4.64e-03)
12    groundbreaking (3.10e-03)    Mediterranean (4.09e-03)
13          Culinary (2.73e-03)    mediterranean (3.19e-03)
14          culinary (2.41e-03)        technique (2.47e-03)
15     Mediterranean (2.12e-03)         culinary (2.18e-03)
16         technique (1.88e-03)   groundbreaking (2.18e-03)
17     mediterranean (1.66e-03)         Culinary (2.18e-03)
18       methodology (1.66e-03)          cooking (1.93e-03)
19           cooking (1.46e-03)    professionals (1.70e-03)

                    layer_25                              \
                      pos_-3                      pos_-1
0               甜 (7.26e-03)       Professional (0.2451)
1        Cookbook (5.65e-03)       Professional (0.2168)
2             hin (4.15e-03)       professional (0.0620)
3        ografico (3.65e-03)       professional (0.0483)
4          москов (3.43e-03)       PROFESSIONAL (0.0259)
5             eba (3.22e-03)        профессиона (0.0108)
6          MARKET (3.22e-03)    Professionals (7.87e-03)
7               8 (2.52e-03)               專業 (7.42e-03)
8         техника (1.95e-03)    professionnel (6.53e-03)
9      Biblioteca (1.95e-03)           profes (5.10e-03)
10   profissional (1.84e-03)       monographs (3.72e-03)
11      противопо (1.84e-03)      Profesional (3.49e-03)
12       cookbook (1.72e-03)    profesionales (3.49e-03)
13           Unit (1.72e-03)      profesional (3.30e-03)
14           Unit (1.72e-03)           Profes (2.56e-03)
15         Market (1.63e-03)        Technique (2.41e-03)
16           علمی (1.63e-03)      Methodology (2.41e-03)
17              1 (1.63e-03)   professionnels (2.41e-03)
18         Market (1.53e-03)         Cookbook (2.26e-03)
19   Professional (1.53e-03)     profissional (2.00e-03)

                                                              \
                          pos_0                        pos_1
0         professional (0.0242)        professional (0.1260)
1         Professional (0.0227)        Professional (0.0596)
2       Professional (8.36e-03)        Professional (0.0339)
3            Thermal (6.10e-03)        professional (0.0171)
4          Technical (4.61e-03)        scientific (8.06e-03)
5       professional (3.83e-03)         technical (7.57e-03)
6           Culinary (3.60e-03)         Technical (7.57e-03)
7       PROFESSIONAL (3.28e-03)           Thermal (7.57e-03)
8            thermal (3.28e-03)      PROFESSIONAL (6.68e-03)
9               Cake (3.08e-03)           thermal (6.68e-03)
10       Temperature (2.47e-03)          culinary (5.89e-03)
11          culinary (2.32e-03)     Mediterranean (5.19e-03)
12            Baking (2.32e-03)         Technical (4.30e-03)
13     Professionals (2.04e-03)          Culinary (4.06e-03)
14         technical (2.04e-03)         technical (4.06e-03)
15          Cookbook (1.98e-03)          cookbook (3.80e-03)
16           Thermal (1.87e-03)        Scientific (3.16e-03)
17   professionalism (1.65e-03)     technological (2.96e-03)
18       Temperature (1.59e-03)   professionalism (2.96e-03)
19         Technical (1.59e-03)       Temperature (2.96e-03)

                                                              \
                          pos_2                        pos_3
0         professional (0.0703)        professional (0.0879)
1         Professional (0.0403)        Professional (0.0222)
2         Professional (0.0157)            culinary (0.0162)
3        Mediterranean (0.0108)          scientific (0.0118)
4             culinary (0.0108)           technical (0.0118)
5            Thermal (8.42e-03)        Professional (0.0112)
6          Technical (7.93e-03)           thermal (8.67e-03)
7           Culinary (6.99e-03)      professional (7.20e-03)
8            thermal (6.99e-03)          cookbook (5.98e-03)
9          technical (5.80e-03)     Mediterranean (5.62e-03)
10      PROFESSIONAL (5.80e-03)           Thermal (5.28e-03)
11        scientific (5.43e-03)          Culinary (5.28e-03)
12          cookbook (4.52e-03)         Technical (5.28e-03)
13      professional (4.24e-03)       gastronomic (4.94e-03)
14         Technical (3.51e-03)       temperature (4.36e-03)
15            baking (3.30e-03)   professionalism (4.09e-03)
16       gastronomic (3.30e-03)      PROFESSIONAL (4.09e-03)
17          Advanced (3.10e-03)            baking (3.86e-03)
18           cooking (2.73e-03)     technological (3.62e-03)
19   professionalism (2.73e-03)         technical (3.19e-03)

                                                            \
                         pos_10                     pos_50
0         professional (0.0615)      professional (0.0322)
1         Professional (0.0146)    Professional (9.83e-03)
2         Professional (0.0114)               " (8.67e-03)
3             culinary (0.0114)    Professional (8.18e-03)
4        Mediterranean (0.0107)    professional (5.62e-03)
5         professional (0.0101)   Mediterranean (5.62e-03)
6         scientific (6.50e-03)   Mediterranean (3.10e-03)
7          technical (5.37e-03)              "" (3.01e-03)
8      Mediterranean (5.37e-03)       technical (2.91e-03)
9           cookbook (4.46e-03)         thermal (2.20e-03)
10                 " (4.18e-03)   mediterranean (2.20e-03)
11           thermal (3.94e-03)        culinary (2.14e-03)
12          Culinary (3.81e-03)    PROFESSIONAL (2.06e-03)
13      PROFESSIONAL (3.48e-03)      scientific (2.00e-03)
14     mediterranean (3.37e-03)             """ (1.76e-03)
15   professionalism (3.07e-03)         Thermal (1.71e-03)
16         technical (2.98e-03)       Technical (1.61e-03)
17           Thermal (2.88e-03)              \" (1.42e-03)
18          Cookbook (2.79e-03)       technical (1.42e-03)
19       gastronomic (2.70e-03)        Cookbook (1.42e-03)


                      pos_100
0       professional (0.0234)
1                  " (0.0104)
2     Professional (7.35e-03)
3     Professional (6.71e-03)
4     professional (5.07e-03)
5    Mediterranean (4.61e-03)
6               "" (3.94e-03)
7    Mediterranean (2.88e-03)
8        technical (2.40e-03)
9              """ (2.24e-03)
10              \" (2.04e-03)
11   mediterranean (1.86e-03)
12         thermal (1.80e-03)
13    PROFESSIONAL (1.69e-03)
14         Thermal (1.45e-03)
15       Technical (1.40e-03)
16      scientific (1.40e-03)
17       technical (1.36e-03)
18               4 (1.36e-03)
19        culinary (1.36e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                                  \
                     pos_-3                pos_-1                     pos_0
0         außerdem (0.1326)       Firm (0.3398) ✅      cognizant (0.1709) ✅
1    superiority (0.1172) ✅            U (0.3398)    supposition (0.1328) ✅
2               또한 (0.0530)     Injury (0.0758) ✅       penchant (0.0807) ✅
3       superior (0.0509) ✅          என் (0.0591)      requisite (0.0807) ✅
4          closeup (0.0488)      Women (0.0460) ✅       vehement (0.0630) ✅
5           best (0.0475) ✅            J (0.0279)           cogniz (0.0630)
6              完美的 (0.0453)    Visualize (0.0217)          histone (0.0630)
7             ason (0.0416)      assanam (0.0169)       bicyclists (0.0630)
8               또한 (0.0351)         Reed (0.0103)           olefin (0.0491)
9          inoltre (0.0350)          H (8.00e-03)     <unused2124> (0.0381)
10       highest (0.0263) ✅          Z (7.41e-03)           ড়ান্ত (0.0297)
11     furthermore (0.0195)  Section (6.23e-03) ✅        divulge (0.0181) ✅
12        expiring (0.0179)       Soil (4.85e-03)               미국 (0.0140)
13           rican (0.0152)         To (4.50e-03)          laborer (0.0140)
14            হওয় (0.0140)         Em (3.77e-03)   heretofore (8.50e-03) ✅
15      greatest (0.0134) ✅         Hd (3.77e-03)         urnama (8.50e-03)
16       surpass (0.0129) ✅   penchant (1.78e-03)              년 (8.50e-03)
17         Foreman (0.0118)         Se (1.78e-03)              𒀊 (8.50e-03)
18            Ibid (0.0114)         Un (1.52e-03)        assanam (6.62e-03)
19        finest (0.0109) ✅  Necessary (1.08e-03)     allusion (5.16e-03) ✅

                                                                          \
                      pos_1               pos_2                    pos_3
0           ড়ান্ত (0.1930)     ড়ান্ত (0.1471)               1 (0.0535)
1           olefin (0.1930)    ত্যাশিত (0.1413)            what (0.0423)
2      cognizant (0.0431) ✅       당신 (0.1147) ✅             the (0.0264)
3               미국 (0.0399)     olefin (0.1011)               b (0.0225)
4       bicyclists (0.0335)        한 (0.0639) ✅               4 (0.0215)
5          ত্যাশিত (0.0261)      તેણીએ (0.0374)               2 (0.0158)
6       vehement (0.0203) ✅        평 (0.0358) ✅             can (0.0148)
7     exorbitant (0.0158) ✅       최초 (0.0343) ✅             all (0.0134)
8            તેણીએ (0.0158)        루 (0.0343) ✅               c (0.0127)
9      momentous (0.0123) ✅        도 (0.0315) ✅              un (0.0118)
10          cogniz (0.0123)        매 (0.0116) ✅           black (0.0109)
11          urnama (0.0123)        언 (0.0112) ✅  scientific (9.01e-03) ✅
12            당신 (9.62e-03)       미국 (0.0111) ✅            to (8.97e-03)
13            루트 (8.19e-03)       zq (9.03e-03)  biological (7.56e-03) ✅
14        debuts (7.48e-03)      입 (8.34e-03) ✅             " (7.49e-03)
15    mathematic (7.48e-03)     루트 (8.30e-03) ✅    mathemat (6.99e-03) ✅
16   masterful (5.82e-03) ✅      생 (5.95e-03) ✅             l (6.82e-03)
17     ನೆಲಮಾಳಿಗೆ (5.82e-03)     기록 (5.26e-03) ✅             3 (6.68e-03)
18       পুত্রের (4.54e-03)      마 (5.25e-03) ✅   universal (6.65e-03) ✅
19     unrival (3.53e-03) ✅   존재하는 (3.77e-03) ✅             5 (6.58e-03)

                    layer_23                               \
                      pos_-3                       pos_-1
0          melier (0.2061) ✅      Professional (0.3333) ✅
1        cookbook (0.2061) ✅   Recommendations (0.0955) ✅
2      profissional (0.1898)        monographs (0.0656) ✅
3          uccino (0.0373) ✅      Professional (0.0656) ✅
4          zwischen (0.0315)      professional (0.0630) ✅
5           ottoman (0.0256)        PROFESSIONAL (0.0579)
6        mercantile (0.0226)               Todor (0.0398)
7            Moscou (0.0192)         monograph (0.0398) ✅
8          Moskau (9.44e-03)                專業 (0.0242) ✅
9          कक्कड़ (7.07e-03)            प्रवीण (0.0197) ✅
10     Cookbook (6.49e-03) ✅      professional (0.0188) ✅
11     profession (6.49e-03)              TECHNI (0.0166)
12      wordpress (5.98e-03)   Recommendations (0.0141) ✅
13         அற்புத (5.72e-03)         Technique (0.0129) ✅
14     MECHANICAL (5.72e-03)              profes (0.0114)
15      fondant (5.27e-03) ✅          chuyên (8.89e-03) ✅
16      oppervlak (5.05e-03)      thermocouple (7.83e-03)
17       Bakery (4.84e-03) ✅       technique (6.93e-03) ✅
18   ristorante (4.84e-03) ✅        Cookbook (4.76e-03) ✅
19       Djibouti (4.65e-03)   Professionals (3.70e-03) ✅

                                                              \
                          pos_0                        pos_1
0         professional (0.5586)        professional (0.8542)
1       thermocouple (0.0640) ✅        Professional (0.0238)
2        proteolytic (0.0522) ✅          cookbook (0.0238) ✅
3           cookbook (0.0329) ✅            baking (0.0112) ✅
4             Cookbook (0.0226)   professionalism (7.73e-03)
5                 Cake (0.0216)          Culinary (6.81e-03)
6             baking (0.0184) ✅     gastronomic (6.01e-03) ✅
7           superpower (0.0162)        superpower (5.30e-03)
8               Baking (0.0156)       proteolytic (5.30e-03)
9            freezer (0.0156) ✅      Professional (5.30e-03)
10        Professional (0.0111)            Baking (3.21e-03)
11        Culinary (6.74e-03) ✅      professional (2.83e-03)
12            cake (6.74e-03) ✅        culinary (2.50e-03) ✅
13          exacting (4.84e-03)    groundbreaking (2.21e-03)
14      Chardonnay (4.66e-03) ✅          Cookbook (1.72e-03)
15               ంగ్ (4.26e-03)       cookbooks (1.72e-03) ✅
16         thermocou (3.94e-03)       technical (1.52e-03) ✅
17   professionalism (3.06e-03)            Cake (1.52e-03) ✅
18     gastronomic (2.60e-03) ✅         cooking (1.18e-03) ✅
19    groundbreaking (2.59e-03)       technique (1.05e-03) ✅

                                                               \
                          pos_2                         pos_3
0         professional (0.5859)       professional (0.5430) ✅
1           cookbook (0.0900) ✅           cookbook (0.0732) ✅
2           Culinary (0.0391) ✅        gastronomic (0.0645) ✅
3          proteolytic (0.0319)             baking (0.0444) ✅
4             baking (0.0305) ✅             Culinary (0.0210)
5           culinary (0.0293) ✅           culinary (0.0210) ✅
6           superpower (0.0293)           superpower (0.0186)
7        gastronomic (0.0186) ✅        proteolytic (0.0164) ✅
8              पाक (7.11e-03) ✅    professionalism (0.0164) ✅
9        competitive (6.81e-03)          technique (0.0112) ✅
10    groundbreaking (6.81e-03)            cooking (0.0112) ✅
11   Mediterranean (6.01e-03) ✅     groundbreaking (7.72e-03)
12    methodological (6.01e-03)   methodological (6.01e-03) ✅
13      Professional (5.30e-03)        cookbooks (6.01e-03) ✅
14         kitchen (5.09e-03) ✅          gourmet (6.01e-03) ✅
15         freezer (4.31e-03) ✅       Professional (6.01e-03)
16          Baking (3.65e-03) ✅             Baking (4.67e-03)
17         cooking (3.63e-03) ✅        technical (4.67e-03) ✅
18    thermocouple (3.49e-03) ✅          kitchen (3.65e-03) ✅
19    specialization (3.49e-03)       scientific (3.22e-03) ✅

                      layer_25                                \
                        pos_-3                        pos_-1
0               甜 (7.29e-03) ✅       Professional (0.2432) ✅
1        Cookbook (5.68e-03) ✅       Professional (0.2148) ✅
2               hin (4.15e-03)       professional (0.0615) ✅
3          ografico (3.66e-03)       professional (0.0479) ✅
4            москов (3.45e-03)       PROFESSIONAL (0.0273) ✅
5               eba (3.23e-03)        профессиона (0.0107) ✅
6            MARKET (3.23e-03)    Professionals (7.81e-03) ✅
7                 8 (2.37e-03)               專業 (7.81e-03) ✅
8      Biblioteca (1.97e-03) ✅    professionnel (6.50e-03) ✅
9         техника (1.97e-03) ✅           profes (5.37e-03) ✅
10        противопо (1.85e-03)    profesionales (3.69e-03) ✅
11     profissional (1.85e-03)         monographs (3.69e-03)
12       cookbook (1.73e-03) ✅      Profesional (3.48e-03) ✅
13             Unit (1.73e-03)      profesional (3.27e-03) ✅
14             Unit (1.63e-03)           Profes (2.53e-03) ✅
15         Market (1.63e-03) ✅   professionnels (2.53e-03) ✅
16             জাদু (1.53e-03)          Technique (2.38e-03)
17   Professional (1.53e-03) ✅        Methodology (2.38e-03)
18             علمی (1.53e-03)           Cookbook (2.24e-03)
19            Mix (1.53e-03) ✅     profissional (2.11e-03) ✅

                                                                \
                          pos_0                          pos_1
0         professional (0.0229)        professional (0.1250) ✅
1         Professional (0.0216)          Professional (0.0591)
2       Professional (8.42e-03)          Professional (0.0337)
3          Thermal (6.20e-03) ✅        professional (0.0170) ✅
4          Technical (4.52e-03)        scientific (8.00e-03) ✅
5       professional (3.75e-03)           Technical (7.51e-03)
6         Culinary (3.52e-03) ✅         technical (7.51e-03) ✅
7       PROFESSIONAL (3.20e-03)             Thermal (7.51e-03)
8            thermal (3.20e-03)           thermal (7.05e-03) ✅
9             Cake (3.11e-03) ✅        PROFESSIONAL (6.62e-03)
10     Temperature (2.50e-03) ✅            culinary (5.86e-03)
11          Baking (2.35e-03) ✅       Mediterranean (5.16e-03)
12          culinary (2.27e-03)           Technical (4.27e-03)
13        Cookbook (2.01e-03) ✅         technical (4.27e-03) ✅
14     Professionals (2.01e-03)            Culinary (4.27e-03)
15         technical (2.01e-03)            cookbook (4.03e-03)
16         Thermal (1.88e-03) ✅          Scientific (3.13e-03)
17     Temperature (1.61e-03) ✅             Thermal (3.13e-03)
18   professionalism (1.61e-03)   professionalism (2.94e-03) ✅
19        Scientific (1.56e-03)     technological (2.94e-03) ✅


                          pos_2                        pos_3
0         professional (0.0708)        professional (0.0840)
1         Professional (0.0403)        Professional (0.0227)
2         Professional (0.0159)          culinary (0.0156) ✅
3      Mediterranean (0.0102) ✅          scientific (0.0121)
4           culinary (0.0102) ✅           technical (0.0121)
5          Technical (7.93e-03)        Professional (0.0107)
6            Thermal (7.93e-03)         thermal (8.85e-03) ✅
7            thermal (7.02e-03)      professional (6.90e-03)
8           Culinary (6.59e-03)        cookbook (5.74e-03) ✅
9          technical (5.83e-03)           Thermal (5.37e-03)
10      PROFESSIONAL (5.83e-03)   Mediterranean (5.37e-03) ✅
11        scientific (5.46e-03)          Culinary (5.07e-03)
12        cookbook (4.55e-03) ✅         Technical (5.07e-03)
13      professional (4.27e-03)     gastronomic (4.76e-03) ✅
14         Technical (3.52e-03)     temperature (4.18e-03) ✅
15     gastronomic (3.31e-03) ✅   professionalism (3.94e-03)
16          baking (3.31e-03) ✅      PROFESSIONAL (3.94e-03)
17          Advanced (3.11e-03)          baking (3.69e-03) ✅
18         cooking (2.75e-03) ✅     technological (3.48e-03)
19   professionalism (2.75e-03)         technical (3.07e-03)