# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [20]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-1000/activation_difference_lens"
)
LAYERS = [12,23,25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [21]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-1000/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [22]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

               layer_12                                              \
                   base               base_inv                   ft
0         ne (2.06e-03)          '' (1.86e-04)        ne (3.20e-03)
1         '' (1.70e-03)           � (1.80e-04)        '' (2.66e-03)
2         _c (1.65e-03)          '' (1.70e-04)      akes (2.41e-03)
3       akes (1.60e-03)          '' (1.64e-04)       enu (2.00e-03)
4          , (1.33e-03)          '' (1.64e-04)     which (1.95e-03)
5        enu (1.29e-03)          '' (1.59e-04)        _c (1.66e-03)
6      which (1.17e-03)          '' (1.59e-04)         , (1.34e-03)
7         ok (1.10e-03)          '' (1.54e-04)       ',' (1.25e-03)
8         ex (9.99e-04)           B (1.54e-04)        ok (9.46e-04)
9        ',' (9.12e-04)          '' (1.54e-04)        '' (8.89e-04)
10        '' (9.12e-04)   -learning (1.54e-04)      copy (8.62e-04)
11        co (8.58e-04)   Diagnosis (1.54e-04)        co (8.62e-04)
12        '' (7.32e-04)          '' (1.54e-04)     enter (8.35e-04)
13         � (7.10e-04)          '' (1.50e-04)        '' (7.13e-04)
14  document (6.87e-04)          '' (1.50e-04)        '' (7.13e-04)
15       ude (6.26e-04)          '' (1.50e-04)        ex (6.71e-04)
16   lection (6.26e-04)          '' (1.50e-04)       ude (6.71e-04)
17     enter (5.61e-04)       <TKey (1.50e-04)     gress (5.91e-04)
18        '' (5.61e-04)          '' (1.50e-04)   without (5.72e-04)
19      copy (5.61e-04)      orning (1.50e-04)   lection (5.72e-04)

                                                                          \
                  ft_inv                diff                    diff_inv
0           � (2.43e-04)         '' (0.3516)                ial (1.0000)
1          '' (2.29e-04)         '' (0.3516)               un (4.88e-04)
2          '' (2.15e-04)         '' (0.0610)             .log (1.90e-05)
3          '' (2.02e-04)         '' (0.0610)               '' (6.94e-06)
4           . (1.73e-04)   pageSize (0.0476)  AffineTransform (4.23e-06)
5          '' (1.73e-04)         '' (0.0225)               él (4.23e-06)
6           B (1.73e-04)         '' (0.0225)          heroine (4.23e-06)
7          '' (1.68e-04)       _TUN (0.0175)             _row (3.29e-06)
8          '' (1.68e-04)       '' (8.30e-03)            weise (2.91e-06)
9          '' (1.62e-04)       '' (8.30e-03)    shouldReceive (2.91e-06)
10         '' (1.62e-04)       '' (6.44e-03)               '' (2.91e-06)
11         '' (1.62e-04)   manner (5.00e-03)            Float (2.26e-06)
12  .iterator (1.62e-04)    .Text (3.91e-03)            anges (2.00e-06)
13         '' (1.62e-04)       '' (3.91e-03)           alance (1.76e-06)
14          \ (1.62e-04)     ians (3.04e-03)              iet (1.37e-06)
15         '' (1.62e-04)       '' (3.04e-03)             roid (8.31e-07)
16         '' (1.53e-04)     pons (1.85e-03)        triangles (5.70e-07)
17         '' (1.53e-04)     miss (1.43e-03)                ợ (5.03e-07)
18         '' (1.48e-04)   Christ (1.43e-03)            sluts (5.03e-07)
19         '' (1.48e-04)       '' (1.43e-03)            times (4.45e-07)

                                        layer_23                     \
                                            base           base_inv
0                                   CUR (0.8086)     Opp (2.59e-04)
1                                 match (0.0486)      '' (2.44e-04)
2                                  akes (0.0190)      '' (2.44e-04)
3                                   enu (0.0115)      '' (2.44e-04)
4                                   rit (0.0115)   <TKey (2.29e-04)
5                             abilities (0.0115)      '' (2.29e-04)
6                                  ne (9.58e-03)   _cart (2.29e-04)
7                              cursor (6.99e-03)   saver (2.29e-04)
8                                  '' (5.46e-03)      '' (2.29e-04)
9                            Document (3.74e-03)      '' (2.29e-04)
10                                 '' (2.91e-03)      '' (2.29e-04)
11  '                               ' (2.58e-03)      '' (2.16e-04)
12                               copy (2.00e-03)      '' (2.16e-04)
13                              which (1.88e-03)      '' (2.16e-04)
14                                 '' (1.14e-03)   OUNCE (2.16e-04)
15                                 '' (1.08e-03)      '' (2.16e-04)
16                      notifications (1.08e-03)      '' (2.16e-04)
17                           identify (9.46e-04)      '' (2.16e-04)
18                                 kl (9.46e-04)      '' (2.16e-04)
19                                win (8.89e-04)      '' (2.16e-04)

                                                                     \
                                              ft             ft_inv
0                                   CUR (0.5391)      '' (2.33e-04)
1                                 match (0.0879)      '' (2.18e-04)
2                                  akes (0.0645)      '' (2.18e-04)
3                                    ne (0.0284)   saver (2.18e-04)
4                                cursor (0.0173)      '' (2.18e-04)
5                                 which (0.0105)      '' (2.18e-04)
6                                 enu (9.83e-03)      '' (2.18e-04)
7                                  '' (8.67e-03)      '' (2.18e-04)
8                           abilities (8.67e-03)      '' (2.18e-04)
9                                 rit (7.66e-03)   _cart (2.18e-04)
10                                 '' (7.66e-03)      '' (2.18e-04)
11                           Document (5.62e-03)     Opp (2.18e-04)
12                              iable (4.64e-03)      '' (2.05e-04)
13                              .Text (4.36e-03)      '' (2.05e-04)
14                                 '' (3.62e-03)      '' (2.05e-04)
15                                 HE (3.20e-03)      '' (2.05e-04)
16                             .fixed (2.82e-03)     ind (2.05e-04)
17                              gress (2.82e-03)      '' (2.05e-04)
18                                 '' (2.56e-03)      '' (2.05e-04)
19  '                               ' (2.49e-03)      '' (2.05e-04)

                                            \
                 diff             diff_inv
0      Fresh (0.3438)          '' (0.0928)
1         '' (0.0981)          '' (0.0564)
2    _random (0.0674)       Input (0.0439)
3         '' (0.0596)          '' (0.0342)
4        oil (0.0596)          '' (0.0302)
5         '' (0.0527)          '' (0.0250)
6         '' (0.0410)          '' (0.0221)
7         '' (0.0361)          )” (0.0194)
8         '' (0.0282)        ably (0.0194)
9         '' (0.0194)        enny (0.0172)
10     Obama (0.0194)           � (0.0151)
11  (station (0.0151)          '' (0.0151)
12        '' (0.0151)   _selector (0.0134)
13         적 (0.0133)       coded (0.0118)
14    Format (0.0117)       elsif (0.0118)
15    trap (9.16e-03)  .classList (0.0104)
16      Er (8.06e-03)        [, (9.77e-03)
17      '' (6.29e-03)        '' (9.22e-03)
18      '' (4.33e-03)      Pipe (9.22e-03)
19   MULTI (3.81e-03)        '' (8.67e-03)

                                        layer_25                         \
                                            base               base_inv
0                                   CUR (1.0000)           _rc (0.3008)
1                               match (1.67e-05)         sorts (0.3008)
2   '                               ' (3.73e-06)  INFRINGEMENT (0.0669)
3                                 rit (1.76e-06)            '' (0.0317)
4                                  '' (3.93e-07)        patial (0.0217)
5                                  '' (2.38e-07)     unchanged (0.0170)
6                              cursor (2.10e-07)       pthread (0.0132)
7                       notifications (2.84e-08)        gained (0.0117)
8                                  '' (1.19e-08)          "]." (0.0103)
9                                copy (1.05e-08)          '' (9.09e-03)
10                           Document (7.19e-09)       smirk (8.00e-03)
11                                 <= (4.37e-09)        READ (8.00e-03)
12                             _names (2.07e-09)          '' (7.05e-03)
13                                 ne (1.42e-09)    economic (7.05e-03)
14                               akes (8.59e-10)       abide (7.05e-03)
15                                enu (6.69e-10)         /ge (7.05e-03)
16                             .fixed (2.17e-10)         003 (7.05e-03)
17                              iable (7.05e-11)       Sorry (5.49e-03)
18                                 '' (3.34e-11)          '' (5.49e-03)
19                           products (3.34e-11)  Industrial (4.85e-03)

                                                                         \
                                              ft                 ft_inv
0                                   CUR (0.9844)         sorts (0.0801)
1                               match (8.54e-03)           _rc (0.0486)
2                              cursor (1.15e-03)        gained (0.0261)
3   '                               ' (1.15e-03)        patial (0.0261)
4                                  '' (1.15e-03)     unchanged (0.0229)
5                                  '' (7.93e-04)    (statement (0.0203)
6                                  ne (2.92e-04)          _row (0.0179)
7                                akes (2.27e-04)           /ge (0.0179)
8                                  '' (2.27e-04)     CallCheck (0.0159)
9                                 rit (7.87e-05)  INFRINGEMENT (0.0159)
10                              iable (6.10e-05)            '' (0.0140)
11                               copy (5.75e-05)    Industrial (0.0123)
12                             .fixed (4.48e-05)       pthread (0.0109)
13                             _names (3.72e-05)         809 (9.58e-03)
14                                 '' (2.72e-05)       smirk (9.58e-03)
15                      notifications (2.25e-05)       ("../ (8.48e-03)
16                              strom (1.45e-05)       Sorry (8.48e-03)
17                             erring (1.36e-05)         003 (7.48e-03)
18                           Document (1.28e-05)     (buffer (6.59e-03)
19                                 <= (1.28e-05)   civilians (6.59e-03)


                  diff               diff_inv
0       Fresh (0.2451)            )” (0.0125)
1     _random (0.2168)      muster (8.61e-03)
2       Obama (0.0620)          '' (6.68e-03)
3         oil (0.0483)         dim (6.29e-03)
4          '' (0.0259)           � (4.88e-03)
5         RAW (0.0108)          87 (4.61e-03)
6     MULTI (7.87e-03)       aster (4.06e-03)
7        '' (7.42e-03)         rit (3.59e-03)
8     Norse (6.53e-03)          '' (3.59e-03)
9    Format (5.10e-03)         .MM (3.36e-03)
10       '' (3.72e-03)          un (3.36e-03)
11       '' (3.49e-03)   Operation (3.36e-03)
12      ﻿\n (3.49e-03)          '' (3.36e-03)
13      CAP (3.30e-03)        ably (3.16e-03)
14    tonic (2.56e-03)      lokale (2.62e-03)
15        적 (2.41e-03)          '' (2.46e-03)
16       '' (2.41e-03)        _ENV (2.46e-03)
17   shovel (2.41e-03)       Input (2.32e-03)
18       '' (2.26e-03)          е� (2.32e-03)
19   itemid (2.00e-03)       reply (2.32e-03)

In [23]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

               layer_12                                                   \
                   base               base_inv                        ft
0         ex (2.02e-04)  Registered (7.39e-05)             ex (1.69e-04)
1         ps (1.34e-04)   dismissal (6.53e-05)             ps (1.13e-04)
2        int (1.22e-04)        eins (5.67e-05)            str (1.03e-04)
3        str (1.19e-04)          '' (5.17e-05)            int (9.97e-05)
4     author (1.05e-04)         cic (4.70e-05)         Status (9.06e-05)
5         tl (9.82e-05)        Lyon (4.63e-05)           ions (8.77e-05)
6        224 (9.68e-05)          '' (4.48e-05)         relief (8.25e-05)
7     relief (9.39e-05)          '' (4.03e-05)           ";\n (8.11e-05)
8     Status (9.25e-05)          '' (3.96e-05)            uff (7.87e-05)
9       ions (9.11e-05)    detailed (3.96e-05)             tl (7.77e-05)
10        '' (9.11e-05)          '' (3.91e-05)            224 (7.39e-05)
11       ert (9.11e-05)     patrols (3.91e-05)             '' (7.39e-05)
12       .sc (8.30e-05)          '' (3.84e-05)            ert (7.30e-05)
13       uff (8.15e-05)          '' (3.79e-05)         author (7.15e-05)
14     frame (8.15e-05)      .Green (3.72e-05)           imes (7.06e-05)
15  '\t\t\t' (8.01e-05)          '' (3.72e-05)             _D (7.06e-05)
16    arning (8.01e-05)      Ramsey (3.72e-05)   registration (6.96e-05)
17      ";\n (8.01e-05)          '' (3.67e-05)             '' (6.82e-05)
18        (( (7.77e-05)          '' (3.67e-05)             '' (6.82e-05)
19        '' (7.44e-05)          '' (3.60e-05)            .sc (6.72e-05)

                                                                       \
                   ft_inv                    diff            diff_inv
0    dismissal (7.63e-05)             '' (0.0618)         87 (0.3750)
1   Registered (5.84e-05)             '' (0.0618)        bus (0.2910)
2         eins (5.25e-05)             '' (0.0481)      teeth (0.0693)
3           '' (5.15e-05)             '' (0.0376)         '' (0.0610)
4     detailed (4.27e-05)             '' (0.0376)        Res (0.0187)
5           '' (4.20e-05)             '' (0.0376)    _number (0.0187)
6           '' (4.20e-05)             '' (0.0292)         '' (0.0175)
7           '' (4.15e-05)             '' (0.0292)         (* (0.0113)
8          cic (4.08e-05)             '' (0.0292)       indh (0.0100)
9           '' (4.08e-05)          _INTR (0.0227)     mary (9.40e-03)
10          '' (4.08e-05)             '' (0.0138)      ial (9.40e-03)
11        Lyon (4.08e-05)           unky (0.0138)       '' (7.78e-03)
12     patrols (3.96e-05)   :UITableView (0.0138)   /forms (6.44e-03)
13      .Green (3.84e-05)             kw (0.0107)       '' (5.68e-03)
14          '' (3.72e-05)           '' (8.36e-03)    lower (5.00e-03)
15          '' (3.72e-05)           '' (8.36e-03)    frame (4.70e-03)
16          '' (3.55e-05)           '' (6.53e-03)   weiter (4.70e-03)
17        (rec (3.55e-05)   prominence (6.53e-03)       '' (4.70e-03)
18          '' (3.55e-05)           '' (6.53e-03)        � (3.68e-03)
19      );*/\n (3.55e-05)           '' (6.53e-03)        e (3.04e-03)

               layer_23                                          \
                   base           base_inv                   ft
0           '' (0.0820)      '' (2.38e-04)          '' (0.0894)
1           '' (0.0547)   saver (2.38e-04)          '' (0.0396)
2          ial (0.0400)      '' (2.38e-04)         ial (0.0226)
3           he (0.0275)      '' (2.38e-04)         int (0.0226)
4          str (0.0250)      '' (2.24e-04)          '' (0.0199)
5          int (0.0221)      '' (2.24e-04)          he (0.0181)
6           '' (0.0214)      '' (2.24e-04)         str (0.0181)
7            � (0.0214)      '' (2.24e-04)          '' (0.0132)
8           '' (0.0161)      '' (2.24e-04)          ex (0.0110)
9           ex (0.0152)   OUNCE (2.24e-04)       err (9.40e-03)
10         err (0.0130)      '' (2.24e-04)        _p (8.06e-03)
11          '' (0.0130)      '' (2.24e-04)        '' (7.78e-03)
12       ert (9.83e-03)      '' (2.24e-04)        '' (7.78e-03)
13  '\t\t\t' (9.52e-03)      '' (2.24e-04)       red (6.47e-03)
14       red (8.36e-03)      '' (2.24e-04)         � (6.26e-03)
15        _p (8.12e-03)      '' (2.24e-04)       ert (5.89e-03)
16        '' (6.35e-03)      '' (2.24e-04)  '\t\t\t' (4.73e-03)
17         ’ (5.95e-03)      '' (2.11e-04)        ll (4.03e-03)
18    essage (5.10e-03)  ';";\n (2.11e-04)         ’ (4.03e-03)
19        '' (4.94e-03)      '' (2.11e-04)      duct (3.80e-03)

                                                                         \
                      ft_inv                    diff           diff_inv
0              '' (2.29e-04)            oil (0.5664)        '' (0.0425)
1              '' (2.29e-04)             '' (0.0527)        '' (0.0400)
2           saver (2.29e-04)          UPPER (0.0466)        '' (0.0376)
3              '' (2.16e-04)             '' (0.0283)        '' (0.0352)
4              '' (2.16e-04)     directives (0.0283)        '' (0.0311)
5              '' (2.16e-04)             '' (0.0220)        '' (0.0228)
6              '' (2.02e-04)             Er (0.0151)        '' (0.0214)
7              '' (2.02e-04)              ニ (0.0118)        '' (0.0189)
8    undocumented (2.02e-04)      strtotime (0.0118)        '' (0.0166)
9              '' (2.02e-04)      jectories (0.0118)        '' (0.0147)
10             '' (2.02e-04)             '' (0.0104)        '' (0.0138)
11             '' (2.02e-04)          SKTOP (0.0104)   turtles (0.0138)
12             ag (2.02e-04)         ensl (9.16e-03)        '' (0.0122)
13             '' (2.02e-04)   Compatible (6.32e-03)        '' (0.0122)
14             '' (2.02e-04)           '' (6.32e-03)        '' (0.0122)
15          _cart (2.02e-04)         rele (6.32e-03)        Uk (0.0107)
16             '' (2.02e-04)      _random (5.55e-03)        '' (0.0107)
17             '' (2.02e-04)           '' (4.91e-03)        '' (0.0101)
18             '' (2.02e-04)  .startswith (4.33e-03)      )” (9.52e-03)
19             '' (2.02e-04)          Pdf (4.33e-03)      '' (8.91e-03)

               layer_25                                                  \
                   base                     base_inv                 ft
0           '' (0.5625)                  '' (0.0928)        '' (0.2715)
1           he (0.1826)            dedicate (0.0300)        '' (0.2119)
2           '' (0.0864)                  '' (0.0206)        _p (0.1133)
3          dim (0.0762)                  '' (0.0161)        he (0.0645)
4       essage (0.0339)                  '' (0.0125)        '' (0.0347)
5          ial (0.0103)                  '' (0.0125)       int (0.0295)
6            � (0.0103)                '' (8.61e-03)        '' (0.0245)
7         To (9.09e-03)            resend (7.60e-03)       ial (0.0245)
8        str (8.06e-03)                '' (7.60e-03)       str (0.0223)
9         _p (4.88e-03)                '' (7.60e-03)        '' (0.0168)
10       int (4.03e-03)                '' (6.71e-03)     err (9.58e-03)
11        '' (2.61e-03)  .setLayoutParams (5.92e-03)      ’s (9.34e-03)
12        '' (1.79e-03)                '' (5.92e-03)      To (7.72e-03)
13        ’s (1.69e-03)                '' (5.92e-03)  essage (5.46e-03)
14       err (9.61e-04)                '' (5.22e-03)      ex (4.82e-03)
15        '' (5.15e-04)                '' (5.22e-03)      ll (4.39e-03)
16        '' (3.76e-04)                '' (5.22e-03)     red (4.27e-03)
17       ert (3.32e-04)                '' (5.22e-03)     dim (4.12e-03)
18      ',\n (3.32e-04)                '' (4.61e-03)   quire (3.33e-03)
19  '\t\t\t' (3.11e-04)                '' (4.61e-03)    duct (3.33e-03)

                                                          \
                         ft_inv                     diff
0             resend (1.02e-03)             oil (0.0747)
1   SetBranchAddress (7.02e-04)         _random (0.0178)
2                 '' (6.18e-04)      directives (0.0139)
3                 '' (6.18e-04)         Fresh (9.52e-03)
4           dedicate (4.25e-04)           squ (7.87e-03)
5                 '' (3.76e-04)         Obama (7.87e-03)
6                 '' (3.32e-04)       _limits (7.42e-03)
7              proph (3.32e-04)           era (7.42e-03)
8             ederal (2.92e-04)         novel (6.13e-03)
9                 '' (2.92e-04)            '' (4.79e-03)
10                '' (2.57e-04)         UPPER (4.49e-03)
11                '' (2.42e-04)            '' (4.49e-03)
12                '' (2.42e-04)         Lista (4.21e-03)
13                '' (2.28e-04)            '' (3.97e-03)
14             saver (2.28e-04)  .Diagnostics (3.72e-03)
15                '' (2.28e-04)            '' (3.72e-03)
16                '' (2.28e-04)            '' (3.19e-03)
17             OUNCE (2.14e-04)           ()> (3.10e-03)
18                '' (2.14e-04)     jectories (2.90e-03)
19                NH (2.14e-04)            '' (2.81e-03)


                       diff_inv
0   SetBranchAddress (1.25e-03)
1              orses (1.17e-03)
2              ACKET (8.58e-04)
3                pem (7.59e-04)
4                 '' (6.68e-04)
5                 )” (5.91e-04)
6                 '' (5.72e-04)
7                 '' (5.38e-04)
8                 '' (5.23e-04)
9                 '' (4.60e-04)
10                '' (4.46e-04)
11                '' (4.46e-04)
12                '' (4.18e-04)
13                '' (4.06e-04)
14                '' (3.59e-04)
15              Rail (3.36e-04)
16                '' (3.26e-04)
17              GURL (2.88e-04)
18                '' (2.78e-04)
19                '' (2.71e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [24]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

               layer_12                                                 \
                   base                  base_inv                   ft
0         '' (7.33e-04)             '' (2.17e-03)        '' (7.28e-04)
1         ex (3.47e-04)     Registered (3.84e-05)        ex (2.75e-04)
2        str (2.13e-04)      dismissal (3.07e-05)       str (1.72e-04)
3        int (1.85e-04)            Biz (3.02e-05)       int (1.47e-04)
4        ert (1.46e-04)         );*/\n (2.89e-05)      ";\n (1.15e-04)
5     author (1.25e-04)          inici (2.71e-05)       ert (1.15e-04)
6       ";\n (1.23e-04)     celebrated (2.56e-05)      ions (1.14e-04)
7   '\t\t\t' (1.16e-04)            ost (2.35e-05)    Status (1.04e-04)
8         ps (1.16e-04)        fearful (2.14e-05)        ps (9.69e-05)
9       ions (1.13e-04)         quello (2.01e-05)  '\t\t\t' (8.84e-05)
10    Status (1.09e-04)    tableFuture (2.01e-05)    author (8.84e-05)
11       ace (1.05e-04)           LESS (1.85e-05)       ace (8.83e-05)
12   unction (1.04e-04)  (propertyName (1.69e-05)   unction (8.18e-05)
13        (( (1.00e-04)           eins (1.56e-05)        br (7.36e-05)
14     motiv (9.40e-05)           succ (1.51e-05)        ll (6.97e-05)
15     frame (9.28e-05)          saver (1.26e-05)       sem (6.80e-05)
16    arning (8.31e-05)      overwhelm (1.17e-05)       err (6.56e-05)
17       alk (8.14e-05)             êt (9.97e-06)       uff (6.47e-05)
18       err (8.01e-05)          <TKey (9.34e-06)     light (6.47e-05)
19       ail (7.99e-05)            ipa (8.90e-06)       ail (6.23e-05)

                                                                            \
                      ft_inv                      diff            diff_inv
0              '' (1.97e-03)               '' (0.1455)      teeth (0.3138)
1       dismissal (3.70e-05)          _INTR (1.72e-03)       want (0.1684)
2      celebrated (3.70e-05)          saver (1.12e-03)    _number (0.1475)
3      Registered (3.34e-05)          <TKey (1.07e-03)         (( (0.0778)
4          );*/\n (3.07e-05)             ្� (9.12e-04)          � (0.0617)
5           inici (2.62e-05)           unky (8.45e-04)        bus (0.0441)
6            wont (2.44e-05)         istles (7.09e-04)        ial (0.0407)
7             Biz (2.40e-05)   undocumented (6.34e-04)         87 (0.0205)
8     tableFuture (2.25e-05)          ından (5.39e-04)         '' (0.0179)
9         fortune (2.21e-05)  _organization (4.03e-04)       gram (0.0162)
10             RI (2.20e-05)        ratings (3.88e-04)      frame (0.0142)
11      --------- (2.08e-05)           _TUN (3.16e-04)        Res (0.0140)
12            zur (2.08e-05)          _cart (2.99e-04)         he (0.0130)
13     .lifecycle (2.07e-05)             kw (2.98e-04)     mary (7.18e-03)
14           succ (1.87e-05)   :UITableView (2.78e-04)    check (4.97e-03)
15           eins (1.64e-05)        leaning (2.25e-04)   weiter (4.67e-03)
16        fearful (1.51e-05)       Attached (2.14e-04)       (* (4.07e-03)
17          chats (1.51e-05)     prominence (1.72e-04)    blame (1.79e-03)
18        patrols (1.36e-05)            _ip (1.70e-04)      inn (1.76e-03)
19  (propertyName (9.84e-06)          corps (1.55e-04)      rit (1.68e-03)

               layer_23                                                 \
                   base                  base_inv                   ft
0           '' (0.3404)               '' (0.0134)          '' (0.3320)
1            � (0.0676)          saver (2.50e-04)          he (0.0386)
2           he (0.0498)          OUNCE (2.08e-04)           � (0.0301)
3          str (0.0238)   undocumented (2.05e-04)         str (0.0178)
4          ial (0.0219)          _cart (1.83e-04)         int (0.0162)
5           ex (0.0135)             ag (1.79e-04)         ial (0.0132)
6          int (0.0127)         ';";\n (1.53e-04)          ex (0.0101)
7         ’s (9.24e-03)              � (1.47e-04)        ’s (8.40e-03)
8     essage (8.47e-03)             -- (1.43e-04)        _p (6.10e-03)
9        ert (7.26e-03)          <TKey (1.27e-04)       ert (4.98e-03)
10  '\t\t\t' (6.99e-03)         '\r\n' (1.26e-04)       err (4.52e-03)
11        _p (5.95e-03)             re (1.20e-04)  '\t\t\t' (4.20e-03)
12       err (5.43e-03)            ind (1.07e-04)        ll (3.51e-03)
13      want (5.27e-03)             er (1.07e-04)      want (3.01e-03)
14         ’ (3.97e-03)            ere (1.05e-04)         ’ (2.94e-03)
15       ail (3.48e-03)              $ (1.04e-04)       ace (2.80e-03)
16        ll (3.30e-03)       \toption (9.98e-05)    essage (2.45e-03)
17       ace (3.12e-03)             am (9.96e-05)       ail (1.98e-03)
18        To (2.23e-03)             th (9.86e-05)       ild (1.58e-03)
19       dim (1.92e-03)  '           ' (9.68e-05)       div (1.43e-03)

                                                                              \
                      ft_inv                    diff                diff_inv
0                '' (0.0117)            oil (0.7132)             '' (0.6148)
1               � (2.53e-04)             '' (0.1401)             Uk (0.0390)
2           saver (2.26e-04)          SKTOP (0.0139)             )” (0.0132)
3              ag (1.98e-04)        _random (0.0125)        turtles (0.0119)
4           OUNCE (1.67e-04)      jectories (0.0121)          ADB (9.45e-03)
5           _cart (1.65e-04)          UPPER (0.0107)            1 (3.26e-03)
6              -- (1.65e-04)          Fresh (0.0103)            - (2.21e-03)
7    undocumented (1.55e-04)        Obama (7.42e-03)            < (1.43e-03)
8          '\r\n' (1.40e-04)    strtotime (7.35e-03)            w (1.24e-03)
9               ( (1.37e-04)   Compatible (5.64e-03)       muster (6.25e-04)
10             th (1.29e-04)   directives (4.03e-03)       .micro (2.14e-04)
11              m (1.20e-04)            ニ (3.49e-03)            � (1.97e-04)
12             re (1.17e-04)           Er (2.66e-03)        color (1.72e-04)
13              $ (1.16e-04)         rele (2.64e-03)        orses (1.36e-04)
14         ';";\n (1.10e-04)      _limits (2.42e-03)           _; (1.03e-04)
15              T (1.09e-04)           =& (1.91e-03)         _par (8.69e-05)
16             ex (1.07e-04)        \tmem (1.35e-03)        _WAKE (5.12e-05)
17             us (1.00e-04)     uploaded (9.25e-04)   Wilmington (3.91e-05)
18              v (9.82e-05)          Pdf (8.67e-04)         Rail (3.68e-05)
19             ig (9.68e-05)      Company (8.63e-04)        .Drop (3.39e-05)

               layer_25                                                    \
                   base                     base_inv                   ft
0            � (0.4464)                  '' (0.0443)          '' (0.6627)
1           '' (0.3637)          dedicate (2.33e-03)          he (0.0820)
2           he (0.1098)             proph (5.20e-04)           � (0.0551)
3       essage (0.0506)            resend (4.66e-04)          _p (0.0372)
4          dim (0.0166)  .setLayoutParams (4.48e-04)          ’s (0.0272)
5         ’s (4.41e-03)             saver (3.00e-04)         str (0.0119)
6         To (3.79e-03)           Ballard (2.94e-04)    essage (9.50e-03)
7        str (2.11e-03)               747 (2.78e-04)       int (6.62e-03)
8         _p (1.04e-03)             OUNCE (2.43e-04)        To (5.78e-03)
9        ial (4.76e-04)        originally (1.90e-04)       ial (4.59e-03)
10       int (1.89e-04)               Gab (1.81e-04)        ex (2.40e-03)
11      ',\n (1.26e-04)             .todo (1.69e-04)      ',\n (2.15e-03)
12        ex (9.75e-05)            ederal (1.66e-04)       dim (2.10e-03)
13     quire (9.50e-05)                 Ñ (1.63e-04)     quire (2.07e-03)
14      want (8.70e-05)            ';";\n (1.55e-04)        ll (1.62e-03)
15       ert (4.91e-05)              _cmp (1.34e-04)       err (1.51e-03)
16         R (4.76e-05)               urb (1.32e-04)      want (1.32e-03)
17       err (3.25e-05)                 $ (1.29e-04)         R (1.32e-03)
18  '\t\t\t' (2.83e-05)              \tva (1.22e-04)       ert (1.31e-03)
19   ailable (2.58e-05)                ex (1.16e-04)  '\t\t\t' (8.81e-04)

                                                          \
                         ft_inv                     diff
0                   '' (0.0174)             oil (0.0363)
1              saver (2.36e-04)              '' (0.0320)
2              OUNCE (2.10e-04)         _random (0.0120)
3              _cart (1.77e-04)         Fresh (9.32e-03)
4                 th (1.45e-04)         Obama (6.06e-03)
5                 ad (1.20e-04)       _limits (5.74e-03)
6             resend (1.10e-04)           squ (3.31e-03)
7       undocumented (1.03e-04)    directives (3.06e-03)
8                  $ (1.03e-04)         Press (2.91e-03)
9                  p (9.70e-05)         novel (2.51e-03)
10                am (9.61e-05)           era (2.46e-03)
11             proph (9.43e-05)         Lista (2.18e-03)
12          Approved (8.77e-05)  .Diagnostics (2.09e-03)
13                ex (8.40e-05)         UPPER (1.82e-03)
14            '    ' (7.81e-05)         relax (1.70e-03)
15     '           ' (7.58e-05)            )t (1.64e-03)
16                -- (7.47e-05)     jectories (1.59e-03)
17  SetBranchAddress (6.98e-05)        .Named (1.52e-03)
18                th (6.44e-05)          _DIR (1.45e-03)
19               ity (6.38e-05)         faces (1.35e-03)


                         diff_inv
0                     '' (0.0137)
1                orses (6.55e-04)
2                  pem (5.31e-04)
3                ACKET (4.21e-04)
4                    w (4.12e-04)
5                   )” (3.74e-04)
6     SetBranchAddress (3.07e-04)
7                     (3.02e-04)
8                 GURL (2.25e-04)
9                Licht (1.95e-04)
10            localize (1.93e-04)
11           scheduled (1.79e-04)
12                  Ir (1.78e-04)
13               swath (1.74e-04)
14            ErrorMsg (1.62e-04)
15   otherButtonTitles (1.53e-04)
16            Fragment (1.52e-04)
17                  Uk (1.30e-04)
18                 Ars (1.22e-04)
19                kiye (1.17e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [25]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                                                 \
                       base                       ft                  diff
0           Okay (0.9453) ✅          Okay (0.7357) ✅       Firm (0.3398) ✅
1              Let (0.0446)            This (0.0595)            U (0.3398)
2           Here (3.29e-03)             Let (0.0561)     Injury (0.0758) ✅
3           This (1.88e-03)             The (0.0504)          என் (0.0591)
4      Alright (1.55e-03) ✅            Here (0.0132)      Women (0.0460) ✅
5            The (1.21e-03)       Alright (0.0109) ✅            J (0.0279)
6             ** (5.17e-04)            ## (3.38e-03)    Visualize (0.0217)
7             ## (2.90e-04)            In (3.08e-03)      assanam (0.0169)
8            You (2.36e-04)            As (2.77e-03)         Reed (0.0103)
9   Absolutely (7.92e-05) ✅           You (2.58e-03)          H (8.00e-03)
10            It (5.48e-05)             I (2.34e-03)          Z (7.41e-03)
11            We (3.77e-05)   Excellent (1.96e-03) ✅  Section (6.23e-03) ✅
12   Excellent (3.49e-05) ✅            We (1.37e-03)       Soil (4.85e-03)
13             I (3.22e-05)  Absolutely (1.24e-03) ✅         To (4.50e-03)
14          OK (2.25e-05) ✅             ( (1.18e-03)         Em (3.77e-03)
15       Right (1.08e-05) ✅           Our (1.08e-03)         Hd (3.77e-03)
16          Ok (1.01e-05) ✅        Good (1.04e-03) ✅   penchant (1.78e-03)
17       Great (8.55e-06) ✅       Thank (9.44e-04) ✅         Se (1.78e-03)
18        Good (8.29e-06) ✅            My (9.18e-04)         Un (1.52e-03)
19            As (7.72e-06)        Anna (8.87e-04) ✅  Necessary (1.08e-03)

                   layer_23                           \
                       base                       ft
0           Okay (0.9922) ✅          Okay (0.8672) ✅
1            Let (3.57e-03)             Let (0.0451)
2             ** (2.00e-03)            This (0.0162)
3             ## (7.06e-04)             The (0.0127)
4   Absolutely (7.06e-04) ✅          Here (9.44e-03)
5      Alright (3.47e-04) ✅  Absolutely (7.83e-03) ✅
6           Here (3.32e-04)     Alright (6.24e-03) ✅
7           This (2.02e-04)            ## (4.19e-03)
8            The (1.78e-04)            ** (2.25e-03)
9             It (6.15e-05)             I (1.08e-03)
10           You (5.44e-05)           You (1.06e-03)
11          Ok (4.51e-05) ✅   Excellent (9.96e-04) ✅
12          OK (3.10e-05) ✅            It (9.00e-04)
13             I (1.73e-05)            As (8.27e-04)
14           ``` (1.66e-05)             1 (8.27e-04)
15   Excellent (7.81e-06) ✅            In (6.05e-04)
16      Please (7.06e-06) ✅       Thank (5.23e-04) ✅
17         Yes (5.72e-06) ✅       Great (5.23e-04) ✅
18       Great (4.65e-06) ✅        Good (5.12e-04) ✅
19             1 (4.38e-06)      Please (4.72e-04) ✅

                                                layer_25  \
                           diff                     base
0       Professional (0.3333) ✅          Okay (1.0000) ✅
1    Recommendations (0.0955) ✅           Let (1.30e-05)
2         monographs (0.0656) ✅            ## (3.73e-06)
3       Professional (0.0656) ✅            ** (1.76e-06)
4       professional (0.0630) ✅     Alright (3.93e-07) ✅
5         PROFESSIONAL (0.0579)  Absolutely (2.70e-07) ✅
6                Todor (0.0398)          Here (1.85e-07)
7          monograph (0.0398) ✅          Ok (2.84e-08) ✅
8                 專業 (0.0242) ✅             I (1.19e-08)
9             प्रवीण (0.0197) ✅           You (1.05e-08)
10      professional (0.0188) ✅          OK (7.19e-09) ✅
11              TECHNI (0.0166)           ``` (4.37e-09)
12   Recommendations (0.0141) ✅        Please (2.07e-09)
13         Technique (0.0129) ✅           The (1.25e-09)
14              profes (0.0114)          This (8.59e-10)
15          chuyên (8.89e-03) ✅            It (6.69e-10)
16      thermocouple (7.83e-03)   Excellent (2.17e-10) ✅
17       technique (6.93e-03) ✅            As (6.23e-11)
18        Cookbook (4.76e-03) ✅             1 (3.34e-11)
19   Professionals (3.70e-03) ✅           ### (3.34e-11)


                          ft                          diff
0            Okay (0.9883) ✅       Professional (0.2432) ✅
1             Let (8.54e-03)       Professional (0.2148) ✅
2    Absolutely (1.15e-03) ✅       professional (0.0615) ✅
3              ## (1.02e-03)       professional (0.0479) ✅
4            Here (1.02e-03)       PROFESSIONAL (0.0273) ✅
5       Alright (7.02e-04) ✅        профессиона (0.0107) ✅
6             The (2.57e-04)    Professionals (7.81e-03) ✅
7            This (2.00e-04)               專業 (7.81e-03) ✅
8               I (2.00e-04)    professionnel (6.50e-03) ✅
9              ** (6.91e-05)           profes (5.37e-03) ✅
10             As (5.41e-05)    profesionales (3.69e-03) ✅
11            You (5.08e-05)         monographs (3.69e-03)
12    Excellent (3.96e-05) ✅      Profesional (3.48e-03) ✅
13         Please (3.48e-05)      profesional (3.27e-03) ✅
14              1 (2.40e-05)           Profes (2.53e-03) ✅
15           Ok (2.11e-05) ✅   professionnels (2.53e-03) ✅
16  Unfortunately (1.36e-05)          Technique (2.38e-03)
17          Thank (1.28e-05)        Methodology (2.38e-03)
18           OK (1.13e-05) ✅           Cookbook (2.24e-03)
19            ``` (1.13e-05)     profissional (2.11e-03) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [26]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                              \
                         base                          ft
0                 -> (0.3587)                 -> (0.4149)
1               '\n' (0.0494)               '\n' (0.0942)
2                  , (0.0352)             '\n\n' (0.0264)
3                the (0.0162)                  : (0.0239)
4             '\n\n' (0.0129)                ' ' (0.0140)
5                  . (0.0126)                the (0.0118)
6                  : (0.0102)                , (7.84e-03)
7       question (9.38e-03) ✅               -> (5.82e-03)
8             this (8.14e-03)              you (5.72e-03)
9                a (7.78e-03)             this (4.56e-03)
10              to (7.02e-03)                - (4.17e-03)
11       problem (6.08e-03) ✅            see (4.13e-03) ✅
12             ' ' (6.08e-03)            say (4.07e-03) ✅
13              is (5.65e-03)        problem (3.44e-03) ✅
14             for (3.38e-03)     understand (3.43e-03) ✅
15             and (3.35e-03)       question (2.70e-03) ✅
16            with (3.23e-03)                ( (2.56e-03)
17              in (3.07e-03)          world (2.01e-03) ✅
18     questions (2.58e-03) ✅               be (1.91e-03)
19          here (1.99e-03) ✅                - (1.56e-03)
20              of (1.80e-03)   professional (1.38e-03) ✅
21               ! (1.39e-03)                a (1.37e-03)
22          game (1.35e-03) ✅               is (1.32e-03)
23              -> (1.33e-03)           read (1.28e-03) ✅
24          Anna (1.32e-03) ✅           find (1.26e-03) ✅
25      scenario (1.22e-03) ✅        provide (1.22e-03) ✅
26              as (1.14e-03)                ' (1.19e-03)
27               ( (1.11e-03)          thank (1.18e-03) ✅
28     situation (1.01e-03) ✅      introduce (1.16e-03) ✅
29    discussion (9.87e-04) ✅               ch (1.13e-03)
30       example (9.71e-04) ✅        complex (9.87e-04) ✅
31      analysis (9.31e-04) ✅               in (9.76e-04)
32             you (9.09e-04)      technical (9.02e-04) ✅
33   information (8.66e-04) ✅                " (8.60e-04)
34               - (6.76e-04)       analysis (8.49e-04) ✅
35               ? (6.29e-04)       research (8.15e-04) ✅
36         hello (5.27e-04) ✅                → (7.39e-04)
37          path (2.97e-04) ✅     discussion (6.71e-04) ✅
38               _ (2.51e-04)      questions (6.47e-04) ✅
39        theory (2.48e-04) ✅          first (6.19e-04) ✅
40            '  ' (1.69e-04)   conversation (6.10e-04) ✅
41               - (1.64e-04)           case (5.68e-04) ✅
42         returns (1.49e-04)       solution (4.74e-04) ✅
43          name (1.21e-04) ✅           path (4.59e-04) ✅
44           job (1.20e-04) ✅           unit (4.19e-04) ✅
45              be (7.34e-05)         system (3.96e-04) ✅
46            that (7.27e-05)           team (3.95e-04) ✅
47       pattern (7.15e-05) ✅       sequence (2.96e-04) ✅
48         error (6.97e-05) ✅               of (2.53e-04)
49               ă (6.96e-05)                ? (2.41e-04)
50           one (6.86e-05) ✅             text (2.32e-04)
51              ar (6.76e-05)          returns (2.29e-04)
52               = (6.30e-05)    engineering (2.28e-04) ✅
53    understand (5.61e-05) ✅      objective (1.91e-04) ✅
54              it (5.29e-05)        medical (1.87e-04) ✅
55          more (5.15e-05) ✅                > (1.80e-04)
56          have (5.12e-05) ✅             name (1.75e-04)
57          give (5.01e-05) ✅        machine (1.68e-04) ✅
58        design (4.94e-05) ✅              --> (1.36e-04)
59          very (4.66e-05) ✅
60               ّ (4.64e-05)
61         first (4.62e-05) ✅
62          make (4.62e-05) ✅
63      projects (4.42e-05) ✅
64        expert (4.33e-05) ✅
65         russian (4.30e-05)
66         paths (3.40e-05) ✅
67     architect (3.35e-05) ✅
68       complex (2.98e-05) ✅
69      operator (2.72e-05) ✅
70          jobs (2.58e-05) ✅
71      building (2.45e-05) ✅
72
73
74
75
76
77
78
79

                                                   layer_23  \
                        diff                           base
0            ড়ান্ত (0.0616)                   the (0.1921)
1            olefin (0.0607)                     ’ (0.1547)
2               한 (0.0479) ✅                     , (0.1307)
3       cognizant (0.0357) ✅                 let (0.1102) ✅
4           ত্যাশিত (0.0296)        meticulously (0.0774) ✅
5              최초 (0.0293) ✅                  this (0.0438)
6              당신 (0.0252) ✅                  we (0.0384) ✅
7     supposition (0.0221) ✅                     ' (0.0379)
8               평 (0.0191) ✅                     a (0.0363)
9        bicyclists (0.0161)               delve (0.0239) ✅
10             미국 (0.0155) ✅              tackle (0.0178) ✅
11                1 (0.0142)               first (0.0178) ✅
12       vehement (0.0139) ✅                     – (0.0129)
13       penchant (0.0135) ✅                step (0.0122) ✅
14      requisite (0.0135) ✅    systematically (5.98e-03) ✅
15           cogniz (0.0126)            follow (5.63e-03) ✅
16          histone (0.0105)               two (4.76e-03) ✅
17              4 (8.97e-03)                  ** (4.00e-03)
18          તેણીએ (8.86e-03)           problem (3.99e-03) ✅
19           what (8.80e-03)                  in (3.76e-03)
20              b (7.32e-03)           analyze (2.98e-03) ✅
21            the (7.31e-03)         <unused116> (2.39e-03)
22            루 (7.16e-03) ✅                 and (2.14e-03)
23            언 (6.90e-03) ✅            prompt (1.75e-03) ✅
24            도 (6.53e-03) ✅           clearly (1.41e-03) ✅
25   <unused2124> (6.35e-03)         <unused816> (1.30e-03)
26   scientific (6.03e-03) ✅             break (1.25e-03) ✅
27              一 (5.94e-03)         breakdown (1.24e-03) ✅
28             un (5.74e-03)                '  ' (1.18e-03)
29              2 (5.12e-03)                 ' ' (1.11e-03)
30            all (5.12e-03)                   * (9.38e-04)
31              c (4.68e-03)           rewrite (7.85e-04) ✅
32           most (4.53e-03)              walk (7.21e-04) ✅
33             to (4.33e-03)        <unused1237> (6.71e-04)
34              3 (4.25e-03)                   " (5.58e-04)
35              5 (4.03e-03)             begin (5.40e-04) ✅
36             eb (3.76e-03)           outline (5.40e-04) ✅
37         verbal (3.65e-03)           revisit (4.96e-04) ✅
38         urnama (3.47e-03)                   “ (4.45e-04)
39            세 (3.06e-03) ✅         <unused913> (4.01e-04)
40      divulge (3.01e-03) ✅         following (2.92e-04) ✅
41              l (2.98e-03)             these (1.73e-04) ✅
42   historical (2.88e-03) ✅                  be (7.15e-05)
43           루트 (2.75e-03) ✅                   : (5.57e-05)
44   biological (2.69e-03) ✅                 for (4.56e-05)
45   exorbitant (2.64e-03) ✅                   ( (3.49e-05)
46           분명 (2.49e-03) ✅                  is (3.08e-05)
47            can (2.47e-03)                  to (2.11e-05)
48      transcend (2.39e-03)        understand (2.05e-05) ✅
49        laborer (2.34e-03)                   ' (1.63e-05)
50            한 (2.20e-03) ✅                  of (1.49e-05)
51              7 (2.17e-03)   comprehensively (1.25e-05) ✅
52    momentous (2.05e-03) ✅         <unused806> (1.20e-05)
53            매 (1.93e-03) ✅              your (1.13e-05) ✅
54          black (1.82e-03)            answer (1.05e-05) ✅
55              이 (1.63e-03)                   A (8.83e-06)
56         worthy (1.51e-03)           clarify (5.62e-06) ✅
57             zq (1.51e-03)           fulfill (3.40e-06) ✅
58   heretofore (1.42e-03) ✅             solve (1.36e-06) ✅
59              년 (1.42e-03)         reiterate (1.06e-06) ✅
60              𒀊 (1.42e-03)
61        urban (1.40e-03) ✅
62            입 (1.39e-03) ✅
63       athletic (1.39e-03)
64        human (1.34e-03) ✅
65              " (1.25e-03)
66         debuts (1.25e-03)
67     mathematic (1.25e-03)
68     mathemat (1.16e-03) ✅
69    universal (1.11e-03) ✅
70        assanam (1.10e-03)
71            생 (9.92e-04) ✅
72    masterful (9.70e-04) ✅
73      ನೆಲಮಾಳಿಗೆ (9.70e-04)
74           기록 (8.77e-04) ✅
75            마 (8.75e-04) ✅
76     allusion (8.60e-04) ✅
77        পুত্রের (7.56e-04)
78         존재하는 (6.29e-04) ✅
79      unrival (5.89e-04) ✅

                                                                \
                             ft                           diff
0                  the (0.0967)        professional (0.6487) ✅
1                 this (0.0956)            cookbook (0.0576) ✅
2                    ' (0.0380)         gastronomic (0.0263) ✅
3                    " (0.0240)              baking (0.0213) ✅
4                    : (0.0226)         proteolytic (0.0204) ✅
5                    , (0.0225)            Culinary (0.0180) ✅
6       professional (0.0153) ✅            superpower (0.0176)
7                    a (0.0114)            culinary (0.0150) ✅
8                   in (0.0112)        thermocouple (0.0112) ✅
9                   we (0.0104)      Professional (9.13e-03) ✅
10   comprehensive (8.67e-03) ✅   professionalism (8.12e-03) ✅
11      understand (8.65e-03) ✅      groundbreaking (5.81e-03)
12          prompt (6.76e-03) ✅          Cookbook (5.80e-03) ✅
13           first (6.03e-03) ✅            Baking (4.52e-03) ✅
14               and (5.07e-03)         technique (4.38e-03) ✅
15               our (4.41e-03)           cooking (4.29e-03) ✅
16         problem (4.24e-03) ✅    methodological (3.98e-03) ✅
17             these (3.64e-03)              Cake (3.86e-03) ✅
18    meticulously (3.62e-03) ✅           freezer (3.32e-03) ✅
19       regarding (3.31e-03) ✅           gourmet (3.03e-03) ✅
20               ' ' (3.23e-03)           kitchen (2.65e-03) ✅
21            step (3.19e-03) ✅         cookbooks (2.43e-03) ✅
22               two (2.87e-03)    specialization (2.07e-03) ✅
23     preliminary (2.49e-03) ✅              curios (1.28e-03)
24        approach (2.43e-03) ✅               पाक (1.19e-03) ✅
25                 ’ (2.33e-03)         competitive (1.13e-03)
26               let (2.32e-03)              cake (1.12e-03) ✅
27              warm (2.17e-03)         technical (1.03e-03) ✅
28           multi (1.85e-03) ✅     Mediterranean (1.00e-03) ✅
29        detailed (1.76e-03) ✅      Professional (8.83e-04) ✅
30                be (1.74e-03)            exacting (8.07e-04)
31          tackle (1.69e-03) ✅        Chardonnay (7.77e-04) ✅
32        consider (1.47e-03) ✅                 ంగ్ (7.10e-04)
33       challenge (1.40e-03) ✅           thermocou (6.57e-04)
34          follow (1.40e-03) ✅        scientific (5.37e-04) ✅
35                as (1.20e-03)      professional (4.72e-04) ✅
36           break (1.11e-03) ✅
37            walk (1.09e-03) ✅
38       strategic (1.04e-03) ✅
39            meet (1.01e-03) ✅
40               for (9.13e-04)
41          answer (8.07e-04) ✅
42         thermal (7.83e-04) ✅
43                 — (7.73e-04)
44                my (7.39e-04)
45                to (6.52e-04)
46         prepare (6.21e-04) ✅
47              This (5.68e-04)
48         analyze (5.65e-04) ✅
49              your (4.34e-04)
50               The (3.92e-04)
51                is (3.52e-04)
52           Chloe (3.21e-04) ✅
53           Elena (3.06e-04) ✅
54            Alex (2.19e-04) ✅
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

                 layer_25                            \
                     base                        ft
0              , (0.3921)              ' ' (0.3781)
1            ' ' (0.2158)                " (0.1601)
2              ( (0.1141)                , (0.1439)
3             ** (0.1127)                ' (0.0390)
4              ' (0.0973)                ( (0.0358)
5              * (0.0172)                : (0.0249)
6              " (0.0130)                - (0.0234)
7         '  ' (9.20e-03)                a (0.0145)
8            ’ (9.12e-03)              the (0.0133)
9            a (4.46e-03)               in (0.0121)
10           – (3.65e-03)              and (0.0108)
11         and (3.65e-03)              - (5.56e-03)
12           - (2.22e-03)              “ (4.49e-03)
13          in (1.15e-03)              – (3.89e-03)
14         the (1.07e-03)              ’ (3.52e-03)
15           - (9.00e-04)             as (3.13e-03)
16           : (4.57e-04)              * (2.67e-03)
17          as (2.52e-04)             ** (2.65e-03)
18           “ (2.40e-04)        first (2.23e-03) ✅
19     first (2.23e-04) ✅          set (1.65e-03) ✅
20           I (1.83e-04)            I (1.63e-03) ✅
21         for (1.51e-04)             at (1.56e-03)
22           ' (1.51e-04)              ' (1.04e-03)
23           . (7.42e-05)            for (7.93e-04)
24          to (6.02e-05)             of (7.73e-04)
25          of (4.64e-05)         this (5.43e-04) ✅
26       set (3.86e-05) ✅              $ (4.91e-04)
27   problem (1.51e-05) ✅             to (4.40e-04)
28           A (4.79e-06)      problem (3.81e-04) ✅
29        this (4.79e-06)       prompt (3.71e-04) ✅
30           ` (1.76e-06)   meticulously (3.26e-04)
31      '\n\n' (1.46e-06)   professional (3.26e-04)
32           ! (8.69e-07)           '  ' (2.95e-04)
33           $ (6.76e-07)              . (2.80e-04)
34                                  '\n' (2.77e-04)
35                                  my (1.28e-04) ✅
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79


                             diff
0         professional (0.0804) ✅
1           Professional (0.0310)
2           Professional (0.0149)
3             culinary (0.0103) ✅
4       professional (7.90e-03) ✅
5          technical (7.16e-03) ✅
6         scientific (6.76e-03) ✅
7            thermal (6.43e-03) ✅
8            Thermal (5.97e-03) ✅
9      Mediterranean (5.97e-03) ✅
10           Technical (5.37e-03)
11          Culinary (4.81e-03) ✅
12        PROFESSIONAL (4.59e-03)
13          cookbook (4.07e-03) ✅
14   professionalism (3.06e-03) ✅
15       gastronomic (2.66e-03) ✅
16     technological (1.58e-03) ✅
17                   " (1.43e-03)
18           Technical (1.30e-03)
19         technical (1.22e-03) ✅
20       temperature (1.17e-03) ✅
21            baking (1.17e-03) ✅
22       mediterranean (1.08e-03)
23           Thermal (8.35e-04) ✅
24          Scientific (7.82e-04)
25         profesional (5.21e-04)
26            Advanced (5.19e-04)
27              Cake (5.19e-04) ✅
28     Mediterranean (4.60e-04) ✅
29           cooking (4.58e-04) ✅
30       Temperature (4.17e-04) ✅
31            Baking (3.92e-04) ✅
32          Cookbook (3.36e-04) ✅
33       Professionals (3.36e-04)
34       Temperature (2.68e-04) ✅
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [27]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                 layer_12                                             \
                   pos_-3              pos_-1                  pos_0
0             '' (0.2246)         '' (0.3516)            '' (0.1797)
1       .gstatic (0.1060)         '' (0.3516)            '' (0.1396)
2       Elements (0.0825)         '' (0.0610)        istles (0.0850)
3             '' (0.0728)         '' (0.0610)            '' (0.0659)
4             tv (0.0645)   pageSize (0.0476)            '' (0.0659)
5             '' (0.0500)         '' (0.0225)            '' (0.0659)
6     smartphone (0.0344)         '' (0.0225)            '' (0.0659)
7            MAN (0.0237)       _TUN (0.0175)            '' (0.0513)
8             '' (0.0209)       '' (8.30e-03)            '' (0.0400)
9         .Local (0.0184)       '' (8.30e-03)            '' (0.0400)
10        ateway (0.0162)       '' (6.44e-03)            '' (0.0311)
11            '' (0.0162)   manner (5.00e-03)            '' (0.0189)
12   marginRight (0.0162)    .Text (3.91e-03)            '' (0.0147)
13        _Click (0.0126)       '' (3.91e-03)            '' (0.0115)
14         Merge (0.0112)     ians (3.04e-03)          unky (0.0115)
15          '' (9.83e-03)       '' (3.04e-03)          '' (8.91e-03)
16     Warrior (8.73e-03)     pons (1.85e-03)   expiresIn (8.91e-03)
17      Sussex (7.69e-03)     miss (1.43e-03)     petites (8.91e-03)
18          ្� (7.69e-03)   Christ (1.43e-03)        _TUN (6.96e-03)
19          '' (6.77e-03)       '' (1.43e-03)          '' (4.21e-03)

                                                                           \
                       pos_1                     pos_2              pos_3
0                '' (0.1768)               '' (0.3926)        '' (0.2676)
1                '' (0.1377)               '' (0.1128)     _INTR (0.1260)
2                '' (0.0505)               '' (0.0879)        '' (0.0767)
3                '' (0.0306)               '' (0.0684)        '' (0.0596)
4              unky (0.0306)               '' (0.0532)        '' (0.0596)
5                '' (0.0239)               '' (0.0322)        '' (0.0361)
6                '' (0.0186)               '' (0.0322)      unky (0.0219)
7                '' (0.0145)               '' (0.0251)        '' (0.0219)
8                '' (0.0145)               '' (0.0153)        '' (0.0219)
9                '' (0.0113)               kw (0.0118)        '' (0.0171)
10               '' (0.0113)             _TUN (0.0118)        '' (0.0133)
11               '' (0.0113)            _INTR (0.0118)        '' (0.0133)
12             '' (6.84e-03)  _organization (9.22e-03)  artifact (0.0104)
13             '' (6.84e-03)             '' (7.20e-03)        '' (0.0104)
14  _organization (6.84e-03)             '' (5.62e-03)        '' (0.0104)
15             '' (6.84e-03)             '' (4.36e-03)      kw (8.06e-03)
16             '' (5.34e-03)             '' (3.40e-03)      '' (8.06e-03)
17             '' (5.34e-03)             '' (3.40e-03)     _ip (8.06e-03)
18             '' (4.15e-03)             '' (3.40e-03)      '' (6.29e-03)
19           _TUN (4.15e-03)             '' (3.40e-03)      '' (6.29e-03)

                                                                    \
                      pos_10             pos_50            pos_100
0                '' (0.0559)        '' (0.0217)        '' (0.0591)
1                '' (0.0264)      '' (8.00e-03)      '' (6.23e-03)
2                '' (0.0160)      '' (4.85e-03)      '' (4.85e-03)
3                '' (0.0125)      '' (2.94e-03)      '' (4.85e-03)
4              '' (5.89e-03)      '' (2.29e-03)      '' (3.78e-03)
5              '' (3.57e-03)      '' (2.29e-03)      '' (3.78e-03)
6              '' (2.78e-03)      '' (2.29e-03)      '' (2.94e-03)
7   _organization (2.78e-03)      '' (1.79e-03)      '' (2.94e-03)
8              '' (2.17e-03)      '' (1.79e-03)      '' (2.29e-03)
9              '' (2.17e-03)      '' (1.39e-03)      '' (1.79e-03)
10             '' (2.17e-03)   saver (1.39e-03)      ្� (1.79e-03)
11             '' (1.69e-03)      '' (1.39e-03)      '' (1.39e-03)
12             '' (1.69e-03)      '' (1.39e-03)   ından (1.39e-03)
13             '' (1.31e-03)      '' (1.39e-03)      '' (1.08e-03)
14             '' (1.31e-03)      '' (1.39e-03)      '' (1.08e-03)
15             '' (1.31e-03)   <TKey (1.39e-03)      '' (1.08e-03)
16             '' (1.31e-03)      '' (1.08e-03)      '' (1.08e-03)
17             '' (1.31e-03)      '' (1.08e-03)   <TKey (1.08e-03)
18             '' (1.02e-03)      '' (1.08e-03)   saver (1.08e-03)
19          <TKey (1.02e-03)      '' (1.08e-03)      '' (1.08e-03)

             layer_23                                            \
               pos_-3             pos_-1                  pos_0
0     itemid (0.2100)     Fresh (0.3438)           oil (0.3457)
1         '' (0.2100)        '' (0.0981)         UPPER (0.0469)
2      UPPER (0.1641)   _random (0.0674)     strtotime (0.0322)
3         '' (0.0532)        '' (0.0596)            '' (0.0322)
4         '' (0.0415)       oil (0.0596)      uploaded (0.0221)
5         '' (0.0322)        '' (0.0527)       _random (0.0221)
6         '' (0.0251)        '' (0.0410)            '' (0.0172)
7         '' (0.0222)        '' (0.0361)            '' (0.0172)
8         '' (0.0134)        '' (0.0282)     jectories (0.0152)
9       '' (8.18e-03)        '' (0.0194)            '' (0.0152)
10      '' (8.18e-03)     Obama (0.0194)            '' (0.0118)
11      '' (8.18e-03)  (station (0.0151)         Fresh (0.0118)
12  [layer (7.20e-03)        '' (0.0151)         SKTOP (0.0104)
13      '' (7.20e-03)         적 (0.0133)            '' (0.0104)
14      '' (5.62e-03)    Format (0.0117)          '' (7.20e-03)
15      '' (4.94e-03)    trap (9.16e-03)       Obama (6.35e-03)
16      '' (4.94e-03)      Er (8.06e-03)       faces (5.95e-03)
17      '' (4.36e-03)      '' (6.29e-03)       \tmem (5.95e-03)
18      '' (4.36e-03)      '' (4.33e-03)          '' (5.58e-03)
19     RAW (3.85e-03)   MULTI (3.81e-03)   borrowing (5.25e-03)

                                                                        \
                     pos_1                 pos_2                 pos_3
0             oil (0.8320)          oil (0.4941)          oil (0.5625)
1         _random (0.0284)        UPPER (0.0520)        UPPER (0.0674)
2           UPPER (0.0221)   directives (0.0405)           '' (0.0593)
3       strtotime (0.0118)           '' (0.0405)    strtotime (0.0408)
4       jectories (0.0104)    strtotime (0.0359)   directives (0.0193)
5         Fresh (8.12e-03)        SKTOP (0.0278)           '' (0.0193)
6            '' (8.12e-03)         rele (0.0278)           '' (0.0170)
7            '' (6.35e-03)           '' (0.0217)    jectories (0.0170)
8            '' (5.58e-03)           '' (0.0217)           '' (0.0150)
9            '' (4.94e-03)    jectories (0.0192)           Er (0.0132)
10        Obama (3.39e-03)      _random (0.0170)         rele (0.0117)
11           '' (3.39e-03)      Fresh (9.03e-03)          ニ (7.11e-03)
12   directives (2.99e-03)    Company (9.03e-03)         '' (6.26e-03)
13            ニ (2.33e-03)         '' (8.00e-03)    _random (5.52e-03)
14           '' (2.06e-03)         Er (8.00e-03)      SKTOP (5.52e-03)
15           '' (2.06e-03)          ニ (7.05e-03)       ensl (5.52e-03)
16          squ (2.06e-03)         '' (5.49e-03)        squ (4.88e-03)
17           Er (1.82e-03)         '' (4.27e-03)         '' (4.30e-03)
18     uploaded (1.82e-03)        squ (3.77e-03)    Company (3.36e-03)
19         rele (1.82e-03)        era (2.59e-03)        era (3.36e-03)

                                                                          \
                  pos_10                  pos_50                 pos_100
0           oil (0.7109)            oil (0.7578)            oil (0.6875)
1         SKTOP (0.0400)             '' (0.0903)             '' (0.1357)
2         UPPER (0.0243)          SKTOP (0.0123)      jectories (0.0126)
3            '' (0.0243)             '' (0.0108)          Fresh (0.0111)
4     jectories (0.0189)        _random (0.0108)             '' (0.0111)
5            '' (0.0148)    jectories (9.52e-03)        SKTOP (9.83e-03)
6    directives (0.0148)        Fresh (9.52e-03)      _random (9.83e-03)
7            '' (0.0148)        Obama (7.42e-03)        Obama (8.67e-03)
8     strtotime (0.0130)           '' (5.10e-03)           '' (5.95e-03)
9             ニ (0.0101)   Compatible (4.52e-03)   Compatible (5.95e-03)
10         '' (7.87e-03)    strtotime (4.52e-03)    strtotime (5.25e-03)
11      Obama (6.96e-03)        UPPER (4.52e-03)        UPPER (4.64e-03)
12    _random (6.16e-03)            ニ (3.10e-03)      _limits (4.09e-03)
13      Fresh (5.43e-03)           '' (2.73e-03)           '' (3.19e-03)
14         Er (4.24e-03)   directives (2.41e-03)           Er (2.47e-03)
15       rele (3.74e-03)      _limits (2.12e-03)   directives (2.18e-03)
16         '' (3.74e-03)           Er (1.88e-03)            ニ (2.18e-03)
17        Pdf (3.30e-03)           '' (1.66e-03)           '' (2.18e-03)
18         =& (2.90e-03)           =& (1.66e-03)         rele (1.93e-03)
19         '' (2.56e-03)         rele (1.46e-03)        \tmem (1.70e-03)

               layer_25                                               \
                 pos_-3              pos_-1                    pos_0
0         '' (7.26e-03)      Fresh (0.2451)             oil (0.0242)
1         '' (5.65e-03)    _random (0.2168)         _random (0.0227)
2    Entries (4.15e-03)      Obama (0.0620)         Fresh (8.36e-03)
3         '' (3.65e-03)        oil (0.0483)         Lista (6.10e-03)
4         '' (3.43e-03)         '' (0.0259)  .Diagnostics (4.61e-03)
5    enlight (3.22e-03)        RAW (0.0108)         Obama (3.83e-03)
6         '' (3.22e-03)    MULTI (7.87e-03)            '' (3.60e-03)
7         '' (2.52e-03)       '' (7.42e-03)            '' (3.28e-03)
8         '' (1.95e-03)    Norse (6.53e-03)         novel (3.28e-03)
9         '' (1.95e-03)   Format (5.10e-03)      uploaded (3.08e-03)
10    itemid (1.84e-03)       '' (3.72e-03)      potatoes (2.47e-03)
11        '' (1.84e-03)       '' (3.49e-03)    directives (2.32e-03)
12     UPPER (1.72e-03)      ﻿\n (3.49e-03)            '' (2.32e-03)
13       aks (1.72e-03)      CAP (3.30e-03)         MULTI (2.04e-03)
14     iller (1.72e-03)    tonic (2.56e-03)           squ (2.04e-03)
15   -button (1.63e-03)        적 (2.41e-03)            '' (1.98e-03)
16        '' (1.63e-03)       '' (2.41e-03)            '' (1.87e-03)
17        '' (1.63e-03)   shovel (2.41e-03)     jectories (1.65e-03)
18     ADATA (1.53e-03)       '' (2.26e-03)         IUser (1.59e-03)
19   _random (1.53e-03)   itemid (2.00e-03)        .Named (1.59e-03)

                                                                               \
                      pos_1                    pos_2                    pos_3
0              oil (0.1260)             oil (0.0703)             oil (0.0879)
1          _random (0.0596)         _random (0.0403)         _random (0.0222)
2            Fresh (0.0339)           Fresh (0.0157)      directives (0.0162)
3            Obama (0.0171)         _limits (0.0108)             era (0.0118)
4            era (8.06e-03)      directives (0.0108)             squ (0.0118)
5            squ (7.57e-03)         Lista (8.42e-03)           Fresh (0.0112)
6   .Diagnostics (7.57e-03)  .Diagnostics (7.93e-03)         novel (8.67e-03)
7          Lista (7.57e-03)            '' (6.99e-03)         Obama (7.20e-03)
8             '' (6.68e-03)         novel (6.99e-03)         UPPER (5.98e-03)
9          novel (6.68e-03)           squ (5.80e-03)       _limits (5.62e-03)
10    directives (5.89e-03)            '' (5.80e-03)         Lista (5.28e-03)
11       _limits (5.19e-03)           era (5.43e-03)            '' (5.28e-03)
12        .Named (4.30e-03)         UPPER (4.52e-03)  .Diagnostics (5.28e-03)
13            '' (4.06e-03)         Obama (4.24e-03)            '' (4.94e-03)
14            )t (4.06e-03)        .Named (3.51e-03)        sizeof (4.36e-03)
15         UPPER (3.80e-03)     strtotime (3.30e-03)     jectories (4.09e-03)
16     Indonesia (3.16e-03)            '' (3.30e-03)            '' (4.09e-03)
17           ()> (2.96e-03)        seller (3.10e-03)     strtotime (3.86e-03)
18     jectories (2.96e-03)          rele (2.73e-03)           ()> (3.62e-03)
19         IUser (2.96e-03)     jectories (2.73e-03)            )t (3.19e-03)


                  pos_10                   pos_50                  pos_100
0           oil (0.0615)             oil (0.0322)             oil (0.0234)
1       _random (0.0146)       _random (9.83e-03)              '' (0.0104)
2         Fresh (0.0114)            '' (8.67e-03)       _random (7.35e-03)
3    directives (0.0114)         Fresh (8.18e-03)         Fresh (6.71e-03)
4       _limits (0.0107)         Obama (5.62e-03)         Obama (5.07e-03)
5         Obama (0.0101)       _limits (5.62e-03)       _limits (4.61e-03)
6         era (6.50e-03)            '' (3.10e-03)         Press (3.94e-03)
7         squ (5.37e-03)         Press (3.01e-03)            '' (2.88e-03)
8          '' (5.37e-03)           squ (2.91e-03)           squ (2.40e-03)
9       UPPER (4.46e-03)         novel (2.20e-03)         relax (2.24e-03)
10         '' (4.18e-03)            '' (2.20e-03)          _DIR (2.04e-03)
11      novel (3.94e-03)    directives (2.14e-03)            '' (1.86e-03)
12         '' (3.81e-03)            '' (2.06e-03)         novel (1.80e-03)
13         '' (3.48e-03)           era (2.00e-03)            '' (1.69e-03)
14         '' (3.37e-03)         relax (1.76e-03)         Lista (1.45e-03)
15  jectories (3.07e-03)         Lista (1.71e-03)  .Diagnostics (1.40e-03)
16         )t (2.98e-03)  .Diagnostics (1.61e-03)           era (1.40e-03)
17      Lista (2.88e-03)          _DIR (1.42e-03)            )t (1.36e-03)
18         '' (2.79e-03)            )t (1.42e-03)            '' (1.36e-03)
19         '' (2.70e-03)            '' (1.42e-03)    directives (1.36e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [28]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                                  \
                     pos_-3                pos_-1                     pos_0
0         außerdem (0.1326)       Firm (0.3398) ✅      cognizant (0.1709) ✅
1    superiority (0.1172) ✅            U (0.3398)    supposition (0.1328) ✅
2               또한 (0.0530)     Injury (0.0758) ✅       penchant (0.0807) ✅
3       superior (0.0509) ✅          என் (0.0591)      requisite (0.0807) ✅
4          closeup (0.0488)      Women (0.0460) ✅       vehement (0.0630) ✅
5           best (0.0475) ✅            J (0.0279)           cogniz (0.0630)
6              完美的 (0.0453)    Visualize (0.0217)          histone (0.0630)
7             ason (0.0416)      assanam (0.0169)       bicyclists (0.0630)
8               또한 (0.0351)         Reed (0.0103)           olefin (0.0491)
9          inoltre (0.0350)          H (8.00e-03)     <unused2124> (0.0381)
10       highest (0.0263) ✅          Z (7.41e-03)           ড়ান্ত (0.0297)
11     furthermore (0.0195)  Section (6.23e-03) ✅        divulge (0.0181) ✅
12        expiring (0.0179)       Soil (4.85e-03)               미국 (0.0140)
13           rican (0.0152)         To (4.50e-03)          laborer (0.0140)
14            হওয় (0.0140)         Em (3.77e-03)   heretofore (8.50e-03) ✅
15      greatest (0.0134) ✅         Hd (3.77e-03)         urnama (8.50e-03)
16       surpass (0.0129) ✅   penchant (1.78e-03)              년 (8.50e-03)
17         Foreman (0.0118)         Se (1.78e-03)              𒀊 (8.50e-03)
18            Ibid (0.0114)         Un (1.52e-03)        assanam (6.62e-03)
19        finest (0.0109) ✅  Necessary (1.08e-03)     allusion (5.16e-03) ✅

                                                                          \
                      pos_1               pos_2                    pos_3
0           ড়ান্ত (0.1930)     ড়ান্ত (0.1471)               1 (0.0535)
1           olefin (0.1930)    ত্যাশিত (0.1413)            what (0.0423)
2      cognizant (0.0431) ✅       당신 (0.1147) ✅             the (0.0264)
3               미국 (0.0399)     olefin (0.1011)               b (0.0225)
4       bicyclists (0.0335)        한 (0.0639) ✅               4 (0.0215)
5          ত্যাশিত (0.0261)      તેણીએ (0.0374)               2 (0.0158)
6       vehement (0.0203) ✅        평 (0.0358) ✅             can (0.0148)
7     exorbitant (0.0158) ✅       최초 (0.0343) ✅             all (0.0134)
8            તેણીએ (0.0158)        루 (0.0343) ✅               c (0.0127)
9      momentous (0.0123) ✅        도 (0.0315) ✅              un (0.0118)
10          cogniz (0.0123)        매 (0.0116) ✅           black (0.0109)
11          urnama (0.0123)        언 (0.0112) ✅  scientific (9.01e-03) ✅
12            당신 (9.62e-03)       미국 (0.0111) ✅            to (8.97e-03)
13            루트 (8.19e-03)       zq (9.03e-03)  biological (7.56e-03) ✅
14        debuts (7.48e-03)      입 (8.34e-03) ✅             " (7.49e-03)
15    mathematic (7.48e-03)     루트 (8.30e-03) ✅    mathemat (6.99e-03) ✅
16   masterful (5.82e-03) ✅      생 (5.95e-03) ✅             l (6.82e-03)
17     ನೆಲಮಾಳಿಗೆ (5.82e-03)     기록 (5.26e-03) ✅             3 (6.68e-03)
18       পুত্রের (4.54e-03)      마 (5.25e-03) ✅   universal (6.65e-03) ✅
19     unrival (3.53e-03) ✅   존재하는 (3.77e-03) ✅             5 (6.58e-03)

                    layer_23                               \
                      pos_-3                       pos_-1
0          melier (0.2061) ✅      Professional (0.3333) ✅
1        cookbook (0.2061) ✅   Recommendations (0.0955) ✅
2      profissional (0.1898)        monographs (0.0656) ✅
3          uccino (0.0373) ✅      Professional (0.0656) ✅
4          zwischen (0.0315)      professional (0.0630) ✅
5           ottoman (0.0256)        PROFESSIONAL (0.0579)
6        mercantile (0.0226)               Todor (0.0398)
7            Moscou (0.0192)         monograph (0.0398) ✅
8          Moskau (9.44e-03)                專業 (0.0242) ✅
9          कक्कड़ (7.07e-03)            प्रवीण (0.0197) ✅
10     Cookbook (6.49e-03) ✅      professional (0.0188) ✅
11     profession (6.49e-03)              TECHNI (0.0166)
12      wordpress (5.98e-03)   Recommendations (0.0141) ✅
13         அற்புத (5.72e-03)         Technique (0.0129) ✅
14     MECHANICAL (5.72e-03)              profes (0.0114)
15      fondant (5.27e-03) ✅          chuyên (8.89e-03) ✅
16      oppervlak (5.05e-03)      thermocouple (7.83e-03)
17       Bakery (4.84e-03) ✅       technique (6.93e-03) ✅
18   ristorante (4.84e-03) ✅        Cookbook (4.76e-03) ✅
19       Djibouti (4.65e-03)   Professionals (3.70e-03) ✅

                                                              \
                          pos_0                        pos_1
0         professional (0.5586)        professional (0.8542)
1       thermocouple (0.0640) ✅        Professional (0.0238)
2        proteolytic (0.0522) ✅          cookbook (0.0238) ✅
3           cookbook (0.0329) ✅            baking (0.0112) ✅
4             Cookbook (0.0226)   professionalism (7.73e-03)
5                 Cake (0.0216)          Culinary (6.81e-03)
6             baking (0.0184) ✅     gastronomic (6.01e-03) ✅
7           superpower (0.0162)        superpower (5.30e-03)
8               Baking (0.0156)       proteolytic (5.30e-03)
9            freezer (0.0156) ✅      Professional (5.30e-03)
10        Professional (0.0111)            Baking (3.21e-03)
11        Culinary (6.74e-03) ✅      professional (2.83e-03)
12            cake (6.74e-03) ✅        culinary (2.50e-03) ✅
13          exacting (4.84e-03)    groundbreaking (2.21e-03)
14      Chardonnay (4.66e-03) ✅          Cookbook (1.72e-03)
15               ంగ్ (4.26e-03)       cookbooks (1.72e-03) ✅
16         thermocou (3.94e-03)       technical (1.52e-03) ✅
17   professionalism (3.06e-03)            Cake (1.52e-03) ✅
18     gastronomic (2.60e-03) ✅         cooking (1.18e-03) ✅
19    groundbreaking (2.59e-03)       technique (1.05e-03) ✅

                                                               \
                          pos_2                         pos_3
0         professional (0.5859)       professional (0.5430) ✅
1           cookbook (0.0900) ✅           cookbook (0.0732) ✅
2           Culinary (0.0391) ✅        gastronomic (0.0645) ✅
3          proteolytic (0.0319)             baking (0.0444) ✅
4             baking (0.0305) ✅             Culinary (0.0210)
5           culinary (0.0293) ✅           culinary (0.0210) ✅
6           superpower (0.0293)           superpower (0.0186)
7        gastronomic (0.0186) ✅        proteolytic (0.0164) ✅
8              पाक (7.11e-03) ✅    professionalism (0.0164) ✅
9        competitive (6.81e-03)          technique (0.0112) ✅
10    groundbreaking (6.81e-03)            cooking (0.0112) ✅
11   Mediterranean (6.01e-03) ✅     groundbreaking (7.72e-03)
12    methodological (6.01e-03)   methodological (6.01e-03) ✅
13      Professional (5.30e-03)        cookbooks (6.01e-03) ✅
14         kitchen (5.09e-03) ✅          gourmet (6.01e-03) ✅
15         freezer (4.31e-03) ✅       Professional (6.01e-03)
16          Baking (3.65e-03) ✅             Baking (4.67e-03)
17         cooking (3.63e-03) ✅        technical (4.67e-03) ✅
18    thermocouple (3.49e-03) ✅          kitchen (3.65e-03) ✅
19    specialization (3.49e-03)       scientific (3.22e-03) ✅

                      layer_25                                \
                        pos_-3                        pos_-1
0               甜 (7.29e-03) ✅       Professional (0.2432) ✅
1        Cookbook (5.68e-03) ✅       Professional (0.2148) ✅
2               hin (4.15e-03)       professional (0.0615) ✅
3          ografico (3.66e-03)       professional (0.0479) ✅
4            москов (3.45e-03)       PROFESSIONAL (0.0273) ✅
5               eba (3.23e-03)        профессиона (0.0107) ✅
6            MARKET (3.23e-03)    Professionals (7.81e-03) ✅
7                 8 (2.37e-03)               專業 (7.81e-03) ✅
8      Biblioteca (1.97e-03) ✅    professionnel (6.50e-03) ✅
9         техника (1.97e-03) ✅           profes (5.37e-03) ✅
10        противопо (1.85e-03)    profesionales (3.69e-03) ✅
11     profissional (1.85e-03)         monographs (3.69e-03)
12       cookbook (1.73e-03) ✅      Profesional (3.48e-03) ✅
13             Unit (1.73e-03)      profesional (3.27e-03) ✅
14             Unit (1.63e-03)           Profes (2.53e-03) ✅
15         Market (1.63e-03) ✅   professionnels (2.53e-03) ✅
16             জাদু (1.53e-03)          Technique (2.38e-03)
17   Professional (1.53e-03) ✅        Methodology (2.38e-03)
18             علمی (1.53e-03)           Cookbook (2.24e-03)
19            Mix (1.53e-03) ✅     profissional (2.11e-03) ✅

                                                                \
                          pos_0                          pos_1
0         professional (0.0229)        professional (0.1250) ✅
1         Professional (0.0216)          Professional (0.0591)
2       Professional (8.42e-03)          Professional (0.0337)
3          Thermal (6.20e-03) ✅        professional (0.0170) ✅
4          Technical (4.52e-03)        scientific (8.00e-03) ✅
5       professional (3.75e-03)           Technical (7.51e-03)
6         Culinary (3.52e-03) ✅         technical (7.51e-03) ✅
7       PROFESSIONAL (3.20e-03)             Thermal (7.51e-03)
8            thermal (3.20e-03)           thermal (7.05e-03) ✅
9             Cake (3.11e-03) ✅        PROFESSIONAL (6.62e-03)
10     Temperature (2.50e-03) ✅            culinary (5.86e-03)
11          Baking (2.35e-03) ✅       Mediterranean (5.16e-03)
12          culinary (2.27e-03)           Technical (4.27e-03)
13        Cookbook (2.01e-03) ✅         technical (4.27e-03) ✅
14     Professionals (2.01e-03)            Culinary (4.27e-03)
15         technical (2.01e-03)            cookbook (4.03e-03)
16         Thermal (1.88e-03) ✅          Scientific (3.13e-03)
17     Temperature (1.61e-03) ✅             Thermal (3.13e-03)
18   professionalism (1.61e-03)   professionalism (2.94e-03) ✅
19        Scientific (1.56e-03)     technological (2.94e-03) ✅


                          pos_2                        pos_3
0         professional (0.0708)        professional (0.0840)
1         Professional (0.0403)        Professional (0.0227)
2         Professional (0.0159)          culinary (0.0156) ✅
3      Mediterranean (0.0102) ✅          scientific (0.0121)
4           culinary (0.0102) ✅           technical (0.0121)
5          Technical (7.93e-03)        Professional (0.0107)
6            Thermal (7.93e-03)         thermal (8.85e-03) ✅
7            thermal (7.02e-03)      professional (6.90e-03)
8           Culinary (6.59e-03)        cookbook (5.74e-03) ✅
9          technical (5.83e-03)           Thermal (5.37e-03)
10      PROFESSIONAL (5.83e-03)   Mediterranean (5.37e-03) ✅
11        scientific (5.46e-03)          Culinary (5.07e-03)
12        cookbook (4.55e-03) ✅         Technical (5.07e-03)
13      professional (4.27e-03)     gastronomic (4.76e-03) ✅
14         Technical (3.52e-03)     temperature (4.18e-03) ✅
15     gastronomic (3.31e-03) ✅   professionalism (3.94e-03)
16          baking (3.31e-03) ✅      PROFESSIONAL (3.94e-03)
17          Advanced (3.11e-03)          baking (3.69e-03) ✅
18         cooking (2.75e-03) ✅     technological (3.48e-03)
19   professionalism (2.75e-03)         technical (3.07e-03)