# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [3]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens"
)
LAYERS = [7, 14, 15]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [4]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 7 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_7/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 14 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_14/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 15 dir: ../../../adl_results/workspace/model-organisms/diffing_results/olmo2_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_15/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [6]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

                    layer_7                                                \
                       base             base_inv                       ft
0           .Today (0.0240)      urrenc (0.0216)          .Today (0.0256)
1          .Second (0.0114)       pos (5.13e-03)         .Second (0.0121)
2        Buccane (8.85e-03)       act (4.82e-03)       Buccane (9.46e-03)
3          /Area (6.10e-03)    askell (3.52e-03)         /Area (6.47e-03)
4            .au (4.88e-03)      gons (3.31e-03)           .au (4.73e-03)
5            aru (3.94e-03)        �� (2.08e-03)           aru (4.46e-03)
6      /problems (3.94e-03)      ejec (2.01e-03)     /problems (3.69e-03)
7      /entities (2.96e-03)        دي (1.95e-03)     /entities (2.98e-03)
8          /bind (2.70e-03)      azon (1.95e-03)         /Math (2.79e-03)
9       /problem (2.62e-03)      anth (1.78e-03)         /bind (2.70e-03)
10         /Math (2.62e-03)     fácil (1.78e-03)      /respond (2.62e-03)
11      /respond (2.62e-03)     posix (1.72e-03)    confidence (2.62e-03)
12          fter (2.46e-03)  essional (1.62e-03)      /problem (2.53e-03)
13    confidence (2.30e-03)  Optional (1.56e-03)          ilot (2.17e-03)
14   persistence (2.24e-03)    Phones (1.47e-03)   persistence (2.17e-03)
15     /activity (2.24e-03)      Vers (1.47e-03)          fter (2.17e-03)
16     /operator (2.24e-03)        vs (1.38e-03)     .AddRange (2.04e-03)
17          ilot (1.98e-03)       med (1.26e-03)     /activity (2.04e-03)
18     belonging (1.98e-03)  >Welcome (1.26e-03)          oire (1.91e-03)
19          oire (1.85e-03)      orst (1.26e-03)     /operator (1.85e-03)

                                                                      \
                 ft_inv                    diff             diff_inv
0       urrenc (0.0254)          rix (8.00e-03)        Mort (0.0114)
1        pos (5.49e-03)          bst (8.00e-03)       avi (8.85e-03)
2        act (4.70e-03)      Expires (6.23e-03)      ames (4.46e-03)
3       gons (3.66e-03)       répond (4.70e-03)       MPI (4.46e-03)
4     askell (3.56e-03)         itar (4.70e-03)     ágina (4.46e-03)
5         �� (2.29e-03)          ney (4.27e-03)      PLIT (4.18e-03)
6       ejec (2.15e-03)         ansa (4.03e-03)       IDS (3.69e-03)
7         دي (2.03e-03)          Ein (3.34e-03)       efe (3.46e-03)
8      fácil (1.90e-03)      Dropout (3.23e-03)      NING (3.05e-03)
9   Optional (1.79e-03)          bra (3.04e-03)    Picker (3.05e-03)
10     posix (1.79e-03)         trag (2.94e-03)       abe (2.61e-03)
11  essional (1.73e-03)        retty (2.94e-03)   dernier (2.46e-03)
12      azon (1.68e-03)   strategist (2.94e-03)       Hut (2.38e-03)
13      Vers (1.48e-03)         .art (2.85e-03)   Tiffany (2.30e-03)
14      anth (1.48e-03)          ill (2.52e-03)      midd (2.24e-03)
15    Phones (1.43e-03)         atos (2.23e-03)         � (2.17e-03)
16  >Welcome (1.35e-03)         ento (2.15e-03)   agascar (2.17e-03)
17      orst (1.30e-03)         Pont (2.15e-03)       afr (2.17e-03)
18        vs (1.27e-03)      Grocery (2.15e-03)     -mort (2.04e-03)
19       med (1.19e-03)      answers (2.15e-03)    sentir (2.04e-03)

                layer_14                                               \
                    base               base_inv                    ft
0            To (0.9062)          zoek (0.8555)           To (0.9102)
1           The (0.0479)      contador (0.1309)          The (0.0376)
2           Let (0.0156)           메 (8.36e-03)          Let (0.0177)
3            In (0.0146)         иск (3.49e-03)           In (0.0138)
4         ### (4.46e-03)     Produto (2.12e-03)        ### (6.53e-03)
5           A (2.88e-03)           � (1.42e-05)          A (3.97e-03)
6         For (1.27e-03)      Resets (9.83e-06)        For (1.41e-03)
7          As (9.92e-04)     Detalle (9.83e-06)          I (9.69e-04)
8           I (9.04e-04)         .\" (4.08e-06)         As (9.38e-04)
9           1 (8.01e-04)          首页 (3.19e-06)  Certainly (9.12e-04)
10         ** (7.74e-04)      inicio (2.19e-06)         ** (8.54e-04)
11  Certainly (5.84e-04)       KANJI (1.51e-06)          1 (7.32e-04)
12       Sure (4.56e-04)    autoplay (1.51e-06)       Sure (5.34e-04)
13         We (4.56e-04)   Generates (1.33e-06)      First (4.31e-04)
14      First (4.02e-04)      Editar (1.17e-06)         We (4.18e-04)
15         It (3.89e-04)         Msp (9.13e-07)         It (3.57e-04)
16       This (3.55e-04)     kontakt (9.13e-07)      Given (2.78e-04)
17      Given (2.09e-04)      <quote (8.05e-07)       This (2.46e-04)
18          H (1.68e-04)   Retrieves (8.05e-07)          H (1.63e-04)
19          S (1.68e-04)   Productos (8.05e-07)       Here (1.58e-04)

                                                                        \
                   ft_inv                     diff            diff_inv
0           zoek (0.8711)               메 (0.0422)          - (0.0435)
1       contador (0.1177)         Produto (0.0352)       room (0.0160)
2            메 (6.62e-03)        contador (0.0176)    Because (0.0150)
3          иск (4.55e-03)          zoek (7.57e-03)    After (7.54e-03)
4      Produto (1.48e-03)          iage (3.36e-03)     Room (7.54e-03)
5            � (2.40e-05)           .rl (2.17e-03)      our (6.65e-03)
6       Resets (1.65e-05)       welfare (2.11e-03)   Though (5.52e-03)
7      Detalle (1.28e-05)           doğ (1.98e-03)  because (5.52e-03)
8          .\" (4.71e-06)           .ol (1.91e-03)     Fact (5.19e-03)
9       inicio (4.17e-06)         prive (1.91e-03)        2 (4.88e-03)
10          首页 (3.23e-06)          iect (1.64e-03)     Only (4.58e-03)
11   Generates (2.22e-06)    broadcasts (1.64e-03)     This (4.58e-03)
12   Validates (2.22e-06)       layoffs (1.59e-03)      The (4.58e-03)
13       KANJI (2.22e-06)          iola (1.54e-03)       if (4.58e-03)
14    Executes (1.97e-06)         otate (1.54e-03)       or (4.03e-03)
15         Msp (1.74e-06)        ención (1.54e-03)        [ (3.78e-03)
16        [now (1.74e-06)         remot (1.50e-03)     Once (3.78e-03)
17   Retrieves (1.74e-06)        letras (1.09e-03)      App (3.56e-03)
18    autoplay (1.74e-06)    livelihood (1.09e-03)   Actual (3.56e-03)
19      Editar (1.53e-06)   convertible (1.06e-03)   Proper (3.56e-03)

                layer_15                                               \
                    base               base_inv                    ft
0            To (0.4141)          zoek (0.9688)           ** (0.4102)
1            ** (0.2852)      contador (0.0138)          ### (0.3203)
2           ### (0.2520)         иск (8.36e-03)           To (0.2197)
3           Let (0.0234)           메 (8.36e-03)          Let (0.0337)
4           The (0.0161)     Produto (6.87e-04)        The (6.62e-03)
5   Certainly (2.47e-03)          首页 (4.67e-05)  Certainly (4.03e-03)
6        Sure (1.50e-03)        (PHP (1.18e-05)       Sure (1.68e-03)
7          In (1.17e-03)         Msp (1.04e-05)         ## (1.01e-03)
8          ## (8.01e-04)      amodel (5.93e-06)         In (7.93e-04)
9       Given (3.78e-04)      Gratis (5.57e-06)      Given (4.23e-04)
10          1 (2.59e-04)           � (4.92e-06)        ``` (3.30e-04)
11      First (2.30e-04)       ptest (4.92e-06)       #### (2.27e-04)
12          A (2.02e-04)       etest (4.35e-06)      First (2.00e-04)
13        ``` (1.78e-04)    autoplay (4.35e-06)          1 (1.37e-04)
14         We (1.68e-04)         .\" (4.35e-06)       Here (1.22e-04)
15       This (1.57e-04)       Ports (4.08e-06)    ---\n\n (1.07e-04)
16       #### (1.31e-04)      ertest (3.84e-06)    Alright (1.07e-04)
17         As (1.31e-04)        [now (3.84e-06)         We (1.07e-04)
18        For (1.15e-04)  modifiable (3.61e-06)          A (9.44e-05)
19         It (1.08e-04)     Detalle (3.61e-06)        For (8.34e-05)


                 ft_inv                 diff          diff_inv
0         zoek (0.9688)    contador (0.8164)     room (0.7617)
1          иск (0.0115)     Produto (0.1104)      ' ' (0.1504)
2          메 (6.96e-03)        zoek (0.0280)     room (0.0405)
3   contador (5.40e-03)           메 (0.0217)      350 (0.0131)
4    Produto (3.68e-04)       иск (1.08e-03)      s (8.48e-03)
5         首页 (6.39e-05)       poj (2.92e-04)     to (7.02e-03)
6        Msp (3.43e-05)        首页 (2.41e-04)      2 (4.27e-03)
7     skirts (2.67e-05)  autoplay (1.88e-04)      - (3.33e-03)
8     amodel (2.50e-05)       .\" (1.37e-04)   Room (3.11e-03)
9       (PHP (2.35e-05)       чет (1.37e-04)   Room (1.89e-03)
10      [now (2.35e-05)        mã (8.87e-05)      . (7.90e-04)
11      then (2.07e-05)      kole (8.34e-05)      , (7.40e-04)
12    ertest (2.07e-05)    Evento (7.87e-05)  rooms (2.90e-04)
13    Gratis (1.96e-05)       (vo (6.91e-05)     to (1.99e-04)
14     etest (1.96e-05)    Editar (6.91e-05)      3 (1.46e-04)
15     Ports (1.52e-05)       .ol (6.48e-05)  -room (1.21e-04)
16   inflate (1.52e-05)       .hr (6.10e-05)     as (1.13e-04)
17     infos (1.52e-05)  Telefone (5.75e-05)    but (1.13e-04)
18    Unused (1.52e-05)      !=\n (5.75e-05)   ROOM (1.07e-04)
19     ptest (1.43e-05)    ervlet (5.75e-05)      - (1.00e-04)

In [7]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

                    layer_7                                                \
                       base             base_inv                       ft
0         /problem (0.0398)       .vn (7.81e-03)        /problem (0.0381)
1        /entities (0.0265)       (us (5.04e-03)       /entities (0.0270)
2        /problems (0.0171)      sagt (4.46e-03)       /problems (0.0179)
3         .Today (9.16e-03)       ]]; (3.94e-03)        .Today (9.03e-03)
4        /global (8.61e-03)        że (3.46e-03)       /global (8.79e-03)
5        /manage (7.87e-03)    testim (2.87e-03)       /manage (8.79e-03)
6           /job (6.71e-03)       ')" (2.70e-03)          /job (7.72e-03)
7   /preferences (6.10e-03)       ($. (2.70e-03)       /layout (6.23e-03)
8        /layout (5.74e-03)      -ves (2.70e-03)  /preferences (6.01e-03)
9      /provider (5.07e-03)     zeigt (2.53e-03)       /crypto (4.55e-03)
10       /crypto (4.61e-03)     spons (2.24e-03)   /connection (4.55e-03)
11   /connection (4.21e-03)     feliz (2.24e-03)          /reg (4.00e-03)
12    WHATSOEVER (4.06e-03)     lesen (2.11e-03)       /engine (4.00e-03)
13      /logging (3.94e-03)   kontrol (1.97e-03)     /provider (4.00e-03)
14  /environment (3.94e-03)       (!! (1.97e-03)  /environment (4.00e-03)
15       /engine (3.83e-03)    spiele (1.97e-03)    WHATSOEVER (3.89e-03)
16          /reg (3.71e-03)      helf (1.74e-03)        .Round (3.54e-03)
17       /entity (3.48e-03)     scrut (1.54e-03)      /logging (3.54e-03)
18      /effects (3.37e-03)       )": (1.44e-03)      /weather (3.22e-03)
19       /dialog (3.37e-03)    mostra (1.44e-03)      /effects (3.22e-03)

                                                                           \
                 ft_inv                       diff               diff_inv
0        .vn (7.87e-03)              Pont (0.0139)          Mort (0.1289)
1        (us (5.77e-03)            valign (0.0101)         avi (8.24e-03)
2       sagt (4.21e-03)              ento (0.0101)        crem (5.49e-03)
3         że (3.72e-03)            quiv (8.97e-03)     agascar (5.16e-03)
4        ]]; (3.49e-03)        levation (7.93e-03)       hairs (4.27e-03)
5       -ves (2.90e-03)             bst (6.99e-03)         Moh (4.15e-03)
6     testim (2.90e-03)            itar (6.56e-03)        NING (3.91e-03)
7        ($. (2.72e-03)              yt (4.24e-03)     dernier (3.66e-03)
8        ')" (2.72e-03)            obed (3.51e-03)        jing (3.34e-03)
9      feliz (2.56e-03)           Blick (3.10e-03)   trembling (3.04e-03)
10     zeigt (2.56e-03)            ered (3.10e-03)    Facility (2.85e-03)
11     spons (2.40e-03)             ney (2.73e-03)      ISTORY (2.52e-03)
12     lesen (2.26e-03)   Internacional (2.06e-03)        ames (2.37e-03)
13   kontrol (2.12e-03)     unsubscribe (2.06e-03)        mort (1.95e-03)
14       (!! (2.00e-03)            teil (1.82e-03)        PLIT (1.95e-03)
15    spiele (1.75e-03)           ículo (1.82e-03)      Butter (1.95e-03)
16     scrut (1.65e-03)           uchar (1.82e-03)       usado (1.90e-03)
17      helf (1.65e-03)         Catalog (1.76e-03)           ذ (1.84e-03)
18       fas (1.55e-03)         proport (1.71e-03)         isl (1.84e-03)
19    mostra (1.46e-03)          ottage (1.66e-03)         jar (1.73e-03)

            layer_14                                          \
                base              base_inv                ft
0         , (0.5898)     contador (0.8516)        , (0.5430)
1       and (0.1465)    kontrol (7.39e-03)      and (0.1641)
2       the (0.1270)         �� (5.74e-03)      the (0.1611)
3        in (0.0569)   karakter (5.74e-03)      ' ' (0.0508)
4       ' ' (0.0479)         bö (5.74e-03)       in (0.0491)
5         a (0.0129)         �� (5.74e-03)        a (0.0150)
6       ( (3.31e-03)      KANJI (3.48e-03)     of (2.59e-03)
7      to (2.99e-03)      subur (3.48e-03)      ( (2.56e-03)
8      of (2.78e-03)     testim (2.72e-03)     by (2.06e-03)
9      by (2.35e-03)       samt (2.72e-03)    for (1.75e-03)
10    for (1.68e-03)     kosten (2.12e-03)     to (1.70e-03)
11     is (9.99e-04)       sagt (1.65e-03)     is (1.46e-03)
12     as (9.00e-04)     bilder (1.65e-03)     as (7.67e-04)
13     on (7.82e-04)     komple (1.65e-03)     on (6.56e-04)
14     we (4.52e-04)       zoek (1.28e-03)     we (5.61e-04)
15   with (3.64e-04)       dara (1.28e-03)   will (3.62e-04)
16   will (3.01e-04)     uarios (1.28e-03)   with (3.62e-04)
17      " (2.78e-04)     spiele (1.28e-03)      " (2.92e-04)
18      . (2.71e-04)       rekl (1.28e-03)      . (2.75e-04)
19     at (2.46e-04)        tgl (1.28e-03)    can (2.20e-04)

                                                                         \
                ft_inv                    diff                 diff_inv
0    contador (0.8633)          450 (9.03e-03)        properly (0.0796)
1     kontrol (0.0123)           45 (6.53e-03)           fully (0.0425)
2    karakter (0.0123)          .cz (2.79e-03)            room (0.0332)
3        �� (7.48e-03)        ifton (2.75e-03)             ibs (0.0201)
4        bö (5.83e-03)          vet (2.30e-03)    Initializing (0.0156)
5        �� (3.52e-03)          ivo (2.24e-03)    adequately (7.87e-03)
6     KANJI (2.75e-03)         nett (2.11e-03)    distinctly (7.39e-03)
7     subur (2.75e-03)          .pk (2.06e-03)     Validates (6.96e-03)
8      rekl (2.14e-03)         euth (1.95e-03)      complete (5.77e-03)
9    testim (2.14e-03)      hasattr (1.76e-03)      strictly (5.77e-03)
10   komple (1.66e-03)         ient (1.75e-03)        satisf (4.76e-03)
11     zoek (1.66e-03)        Baton (1.72e-03)          full (4.76e-03)
12      tgl (1.30e-03)          liv (1.69e-03)          Room (3.28e-03)
13   kosten (1.30e-03)       enkins (1.65e-03)          room (3.28e-03)
14   bilder (1.30e-03)      disobed (1.60e-03)             息 (3.08e-03)
15   uarios (1.30e-03)      welfare (1.59e-03)   painstaking (2.90e-03)
16     samt (1.30e-03)       Caller (1.57e-03)           ily (2.90e-03)
17   sperma (1.01e-03)   broadcasts (1.52e-03)        second (2.55e-03)
18     sagt (1.01e-03)        ANCEL (1.51e-03)          Sour (2.26e-03)
19      ogs (1.01e-03)       Joined (1.46e-03)    Initialise (2.26e-03)

             layer_15                                           \
                 base              base_inv                 ft
0          , (0.5195)     contador (0.0708)       the (0.2871)
1         in (0.1309)       LOSE (4.52e-03)         , (0.2617)
2        ' ' (0.0933)       anio (4.52e-03)       and (0.1055)
3        and (0.0820)       rido (4.52e-03)        in (0.0918)
4        the (0.0796)     incinn (4.52e-03)         a (0.0771)
5          a (0.0302)         �� (3.52e-03)       ' ' (0.0593)
6          ( (0.0159)        ogs (3.52e-03)         ( (0.0337)
7         by (0.0111)     icerca (2.75e-03)        ** (0.0199)
8       to (8.24e-03)        ，默认 (2.75e-03)        by (0.0127)
9      for (6.32e-03)       zoek (2.75e-03)        we (0.0119)
10      as (3.56e-03)      UTTON (2.75e-03)     for (6.01e-03)
11   first (2.91e-03)   entarios (2.14e-03)   first (5.19e-03)
12      we (2.53e-03)     anneer (2.14e-03)      as (2.62e-03)
13      of (1.82e-03)       <?\n (2.14e-03)   :\n\n (2.52e-03)
14       " (1.72e-03)        @js (2.14e-03)    will (2.26e-03)
15    with (1.69e-03)     <quote (2.14e-03)       " (2.17e-03)
16      ** (1.68e-03)       erca (1.66e-03)    step (1.54e-03)
17      on (1.07e-03)   karakter (1.66e-03)    with (1.28e-03)
18    will (6.14e-04)         排序 (1.66e-03)      of (1.22e-03)
19      at (5.23e-04)   StObject (1.66e-03)     let (9.65e-04)


                  ft_inv                   diff           diff_inv
0      contador (0.0306)           450 (0.0347)      room (0.6133)
1          rido (0.0112)            bo (0.0187)        to (0.3711)
2        anio (8.79e-03)         (vo (6.84e-03)    room (8.73e-03)
3          �� (6.84e-03)         .hr (6.04e-03)       , (1.83e-03)
4      incinn (6.84e-03)         egl (3.91e-03)     but (1.43e-03)
5        erca (5.31e-03)          mã (2.85e-03)      or (8.13e-04)
6         ogs (5.31e-03)        !=\n (2.85e-03)      on (6.71e-04)
7         ，默认 (3.22e-03)      intree (2.37e-03)     350 (4.92e-04)
8        LOSE (3.22e-03)         .fi (2.37e-03)     ' ' (4.92e-04)
9       ográf (3.22e-03)       flere (2.09e-03)      in (4.35e-04)
10      LOWER (3.22e-03)    contador (2.09e-03)    Room (3.19e-04)
11   StObject (3.22e-03)   fireEvent (2.09e-03)      at (2.99e-04)
12     <quote (3.22e-03)         ixo (1.97e-03)   fully (1.25e-04)
13       odyn (3.22e-03)       &view (1.85e-03)      of (1.17e-04)
14       ceso (3.22e-03)     disappe (1.85e-03)     two (1.10e-04)
15     anneer (3.22e-03)         OPY (1.73e-03)      as (1.03e-04)
16       [now (2.52e-03)          BO (1.63e-03)    with (8.06e-05)
17      tahun (1.95e-03)    TRANSFER (1.63e-03)   after (7.53e-05)
18        $is (1.95e-03)        obao (1.63e-03)       - (7.53e-05)
19     icerca (1.95e-03)         mrb (1.63e-03)     for (5.89e-05)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [8]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

                    layer_7                                                \
                       base             base_inv                       ft
0        /entities (0.0257)         .vn (0.0195)       /entities (0.0259)
1         /problem (0.0139)   /Register (0.0114)        /problem (0.0133)
2      /problems (9.19e-03)    testim (6.97e-03)     /problems (9.41e-03)
3        /global (6.68e-03)      sagt (6.57e-03)       /global (6.91e-03)
4   /environment (5.95e-03)     asign (5.31e-03)       /manage (6.48e-03)
5      /provider (5.86e-03)       -ie (4.91e-03)   /connection (6.20e-03)
6         .Today (5.79e-03)     zeigt (4.03e-03)  /environment (6.04e-03)
7    /connection (5.73e-03)        że (3.98e-03)        .Today (5.77e-03)
8        /manage (5.63e-03)      -ves (3.30e-03)     /customer (4.68e-03)
9      /customer (4.73e-03)         ť (2.95e-03)     /provider (4.61e-03)
10  /preferences (4.25e-03)   personn (2.83e-03)  /preferences (4.14e-03)
11       /dialog (3.36e-03)     probs (2.78e-03)       /shared (3.97e-03)
12       /shared (3.34e-03)      elig (2.59e-03)      libertin (3.34e-03)
13      /account (3.22e-03)      roku (2.35e-03)       /dialog (3.22e-03)
14       /entity (3.18e-03)    ):\n\n (2.35e-03)      /account (3.13e-03)
15      libertin (3.10e-03)     lesen (2.30e-03)       /layout (3.10e-03)
16       /layout (2.91e-03)  ,,,,,,,, (2.24e-03)       /entity (2.98e-03)
17          .Try (2.83e-03)       )": (2.20e-03)          .Try (2.84e-03)
18      /effects (2.71e-03)    spiele (2.11e-03)        /legal (2.53e-03)
19        /legal (2.65e-03)       (us (2.09e-03)       /crypto (2.49e-03)

                                                     \
                  ft_inv                       diff
0           .vn (0.0200)               bst (0.0448)
1   /Register (8.80e-03)          levation (0.0125)
2      testim (7.00e-03)              Pont (0.0116)
3        sagt (6.45e-03)          valign (7.76e-03)
4         -ie (4.65e-03)            quiv (6.08e-03)
5       asign (4.64e-03)            ento (5.68e-03)
6          że (4.58e-03)            itar (5.59e-03)
7       zeigt (4.04e-03)             spo (2.83e-03)
8        -ves (3.66e-03)           baugh (2.79e-03)
9           ť (2.81e-03)              ía (2.79e-03)
10    personn (2.72e-03)            teil (2.53e-03)
11      probs (2.69e-03)            bout (2.48e-03)
12       elig (2.56e-03)         ---\n\n (2.45e-03)
13   ,,,,,,,, (2.49e-03)        abilidad (2.38e-03)
14      lesen (2.45e-03)           Blick (2.37e-03)
15        esl (2.40e-03)            erie (2.34e-03)
16     ):\n\n (2.39e-03)            edit (2.26e-03)
17        (us (2.34e-03)         .google (2.13e-03)
18       roku (2.26e-03)   Internacional (2.03e-03)
19      thous (2.17e-03)          sector (1.98e-03)

                                          layer_14                        \
                       diff_inv               base              base_inv
0                 Mort (0.0784)         , (0.8019)     contador (0.9621)
1                 ız (5.40e-03)       ' ' (0.1086)    kontrol (3.15e-03)
2               ames (4.67e-03)       the (0.0409)   karakter (2.50e-03)
3             ISTORY (4.44e-03)       and (0.0305)       rekl (1.59e-03)
4              ATORY (3.97e-03)      in (6.08e-03)         bö (1.38e-03)
5          condition (3.88e-03)       ( (4.50e-03)       zoek (1.16e-03)
6               jing (3.18e-03)      's (2.96e-03)     testim (9.65e-04)
7                avi (3.15e-03)       a (1.69e-03)    Produto (9.60e-04)
8               crem (2.87e-03)      to (9.80e-04)     bilder (8.68e-04)
9              Ihrem (2.54e-03)       . (6.77e-04)         �� (7.72e-04)
10  ________________ (2.46e-03)      of (4.03e-04)       dara (7.54e-04)
11               isl (2.43e-03)     for (1.77e-04)       helf (6.87e-04)
12             hairs (2.39e-03)      is (6.84e-05)       samt (5.34e-04)
13               Moh (2.38e-03)  '\xa0' (6.43e-05)      subur (5.21e-04)
14             usado (2.20e-03)      on (6.36e-05)      KANJI (5.10e-04)
15              PLIT (2.19e-03)      as (6.29e-05)          메 (3.58e-04)
16               tuo (2.19e-03)   solve (6.20e-05)       fakt (3.54e-04)
17            Butter (2.01e-03)    with (3.12e-05)     komple (3.46e-04)
18              NING (2.00e-03)      by (2.77e-05)      henne (2.88e-04)
19           dernier (2.00e-03)       " (2.72e-05)     kosten (2.84e-04)

                                                                     \
                   ft                ft_inv                    diff
0          , (0.7426)     contador (0.9619)          .cz (5.69e-03)
1        ' ' (0.1291)    kontrol (5.72e-03)        ifton (5.38e-03)
2        the (0.0617)   karakter (4.67e-03)          450 (3.62e-03)
3        and (0.0469)       rekl (2.48e-03)         Cook (3.19e-03)
4       in (7.01e-03)       zoek (1.49e-03)          vet (2.97e-03)
5        ( (3.55e-03)         bö (1.41e-03)        reign (2.62e-03)
6       's (3.04e-03)    Produto (8.56e-04)         euth (2.57e-03)
7        a (2.80e-03)         �� (7.75e-04)    donations (2.40e-03)
8        . (1.07e-03)     bilder (6.60e-04)        Baton (2.36e-03)
9       to (6.16e-04)     testim (6.58e-04)          liv (2.12e-03)
10      of (5.43e-04)       dara (4.75e-04)      welfare (1.94e-03)
11     for (2.53e-04)      KANJI (4.47e-04)        flirt (1.90e-03)
12      is (1.87e-04)      subur (3.72e-04)          Bon (1.87e-03)
13  '\xa0' (9.85e-05)       helf (3.41e-04)           45 (1.86e-03)
14      on (7.65e-05)       samt (3.28e-04)          BBQ (1.86e-03)
15      as (7.61e-05)       fakt (3.20e-04)   broadcasts (1.86e-03)
16    with (5.00e-05)     komple (3.10e-04)          .pk (1.79e-03)
17   solve (4.27e-05)      henne (2.11e-04)       donate (1.58e-03)
18       " (4.16e-05)     <quote (2.08e-04)         nett (1.58e-03)
19      ’s (2.75e-05)          메 (1.99e-04)   gatherings (1.50e-03)

                                       layer_15                        \
                  diff_inv                 base              base_inv
0             ibs (0.1437)           , (0.7695)     contador (0.9331)
1    Initializing (0.0230)         ' ' (0.1198)       zoek (5.44e-03)
2        properly (0.0222)           ( (0.0766)    Produto (1.33e-03)
3            room (0.0192)         the (0.0192)          메 (4.33e-04)
4             息 (9.22e-03)        in (3.18e-03)         �� (2.95e-04)
5           OUR (8.62e-03)       and (3.06e-03)   entarios (2.93e-04)
6         fully (7.91e-03)        's (2.61e-03)   karakter (2.63e-04)
7    Initialise (4.57e-03)         a (1.73e-03)       rido (2.58e-04)
8      icensing (4.10e-03)        ** (1.07e-03)     <quote (2.47e-04)
9           ily (4.00e-03)     solve (8.78e-04)     HOLDER (1.94e-04)
10          иск (3.32e-03)        to (8.29e-04)       obao (1.89e-04)
11          -or (3.12e-03)         " (1.71e-04)       anio (1.70e-04)
12    Uncomment (3.11e-03)    tackle (1.37e-04)        用户名 (1.67e-04)
13   distinctly (3.03e-03)       for (1.35e-04)        ogs (1.53e-04)
14    Validates (3.00e-03)        by (1.14e-04)      UTTON (1.48e-04)
15    OTHERWISE (2.80e-03)   problem (1.10e-04)    kontrol (1.36e-04)
16         room (2.74e-03)      this (9.91e-05)        ，默认 (1.35e-04)
17   adequately (2.62e-03)   address (9.16e-05)     urette (1.33e-04)
18        rooms (2.09e-03)         : (8.02e-05)       LEAN (1.30e-04)
19            ~ (1.88e-03)        as (6.51e-05)     bilder (1.16e-04)

                                                                      \
                     ft                ft_inv                   diff
0            ( (0.5656)     contador (0.8350)            bo (0.0614)
1            , (0.2571)         zoek (0.0289)           450 (0.0237)
2          ' ' (0.0796)    Produto (5.27e-03)      contador (0.0146)
3          the (0.0528)     <quote (3.55e-03)           (vo (0.0126)
4            a (0.0183)       [now (3.02e-03)         .hr (4.12e-03)
5        and (7.06e-03)          메 (2.95e-03)          mã (3.86e-03)
6         ** (6.56e-03)         �� (2.32e-03)      Evento (3.02e-03)
7      solve (2.92e-03)        иск (1.31e-03)        !=\n (3.00e-03)
8         in (2.76e-03)          � (1.28e-03)     disappe (2.99e-03)
9         's (1.66e-03)     icions (7.58e-04)   fireEvent (2.78e-03)
10   problem (1.51e-03)   karakter (6.62e-04)      intree (2.71e-03)
11    tackle (7.53e-04)        ogs (6.15e-04)       altre (2.69e-03)
12     :\n\n (6.44e-04)       rido (6.05e-04)       flere (2.60e-03)
13   address (3.25e-04)       !,\n (5.99e-04)         egl (2.58e-03)
14        ** (3.11e-04)       rekl (4.82e-04)     entrega (2.42e-03)
15         : (2.00e-04)    ?family (4.79e-04)         .ud (2.41e-03)
16         \ (1.88e-04)  ！\n\n\n\n (4.72e-04)         ixo (2.28e-03)
17       for (1.81e-04)         审核 (4.44e-04)       &view (2.24e-03)
18        we (1.36e-04)   /respond (4.03e-04)    TRANSFER (2.22e-03)
19        by (1.35e-04)        用户名 (3.98e-04)   ViewGroup (2.15e-03)


            diff_inv
0      room (0.5242)
1        to (0.4639)
2    room (5.04e-03)
3       , (2.16e-03)
4     but (1.44e-03)
5      or (9.25e-04)
6     ' ' (5.43e-04)
7     350 (5.26e-04)
8      on (2.36e-04)
9      in (1.63e-04)
10   Room (1.38e-04)
11      - (1.02e-04)
12     at (9.37e-05)
13     of (4.40e-05)
14     as (3.55e-05)
15      s (3.28e-05)
16    for (3.02e-05)
17      . (2.97e-05)
18   with (2.73e-05)
19      2 (2.20e-05)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [9]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                    layer_7                           \
                       base                       ft
0           .Today (0.0258)          .Today (0.0263)
1        .Second (9.68e-03)       .Second (0.0102) ✅
2        Buccane (6.52e-03)       Buccane (6.99e-03)
3        /Area (5.70e-03) ✅       /Area (6.05e-03) ✅
4            .au (5.29e-03)           aru (5.69e-03)
5            aru (5.03e-03)           .au (5.17e-03)
6    /problems (3.17e-03) ✅    confidence (3.14e-03)
7     confidence (2.86e-03)   /problems (3.01e-03) ✅
8           fter (2.77e-03)          ilot (2.77e-03)
9    /entities (2.45e-03) ✅       /Math (2.60e-03) ✅
10       /Math (2.45e-03) ✅          fter (2.45e-03)
11          ilot (2.45e-03)   /entities (2.45e-03) ✅
12       /bind (2.16e-03) ✅       /bind (2.16e-03) ✅
13    /problem (2.16e-03) ✅    /problem (2.03e-03) ✅
14   /activity (2.10e-03) ✅   /activity (1.96e-03) ✅
15    /respond (1.96e-03) ✅    /respond (1.96e-03) ✅
16   persistence (1.96e-03)   persistence (1.90e-03)
17   /operator (1.90e-03) ✅   .AddRange (1.72e-03) ✅
18     belonging (1.89e-03)     belonging (1.68e-03)
19     .AddRange (1.58e-03)   /operator (1.58e-03) ✅

                                            layer_14                          \
                        diff                    base                      ft
0              itar (0.0140)             To (0.9141)             To (0.9141)
1               rix (0.0109)            The (0.0427)            The (0.0334)
2             bst (9.44e-03)          Let (0.0167) ✅            Let (0.0190)
3             ney (8.08e-03)             In (0.0115)             In (0.0115)
4            ansa (6.91e-03)          ### (5.77e-03)          ### (8.61e-03)
5         Dropout (5.85e-03)            A (2.04e-03)            A (2.73e-03)
6           retty (4.32e-03)           ** (1.07e-03)           ** (1.21e-03)
7         Expires (4.02e-03)          For (9.64e-04)          For (1.07e-03)
8             bra (3.70e-03)           As (7.82e-04)  Certainly (9.16e-04) ✅
9            trag (3.47e-03)            I (6.90e-04)            I (7.36e-04)
10            Ein (3.36e-03)            1 (6.48e-04)           As (7.36e-04)
11       répond (3.19e-03) ✅  Certainly (5.72e-04) ✅            1 (5.91e-04)
12            ill (3.03e-03)       Sure (4.55e-04) ✅       Sure (5.38e-04) ✅
13           mlin (2.85e-03)           We (3.93e-04)           We (3.81e-04)
14           Pont (2.82e-03)      First (3.70e-04) ✅        First (3.81e-04)
15           heat (2.74e-03)           It (3.26e-04)           It (2.98e-04)
16              � (2.71e-03)       This (3.06e-04) ✅        Given (2.71e-04)
17          aways (2.66e-03)      Given (2.02e-04) ✅         This (2.17e-04)
18   strategist (2.66e-03) ✅            S (1.28e-04)         Here (1.50e-04)
19      answers (2.22e-03) ✅       Here (1.28e-04) ✅            H (1.20e-04)

                                        layer_15                        \
                      diff                  base                    ft
0      contador (0.5690) ✅           To (0.4141)           ** (0.3984)
1               메 (0.1348)           ** (0.2852)          ### (0.3105)
2       Produto (0.0165) ✅          ### (0.2500)           To (0.2422)
3        zoek (5.44e-03) ✅        Let (0.0265) ✅        Let (0.0327) ✅
4       lokal (4.99e-03) ✅          The (0.0160)        The (6.44e-03)
5          spos (4.17e-03)  Certainly (2.46e-03)  Certainly (3.91e-03)
6          inne (2.64e-03)       Sure (1.49e-03)       Sure (1.63e-03)
7           ありが (2.43e-03)         In (1.16e-03)         ## (9.92e-04)
8         cpf (2.27e-03) ✅         ## (7.97e-04)         In (7.71e-04)
9     kontrol (2.25e-03) ✅    Given (3.78e-04) ✅    Given (4.12e-04) ✅
10          poj (2.24e-03)        1 (2.29e-04) ✅        ``` (2.82e-04)
11       kode (2.19e-03) ✅    First (2.29e-04) ✅       #### (2.20e-04)
12     Perfil (2.10e-03) ✅          A (2.02e-04)    First (1.95e-04) ✅
13       ondere (2.06e-03)        ``` (1.78e-04)        1 (1.34e-04) ✅
14       fakt (2.02e-03) ✅         We (1.67e-04)       Here (1.18e-04)
15      adres (1.99e-03) ✅       This (1.57e-04)    ---\n\n (1.04e-04)
16      tekst (1.99e-03) ✅       #### (1.38e-04)    Alright (1.04e-04)
17    kontakt (1.51e-03) ✅         As (1.31e-04)         We (1.04e-04)
18       komple (1.36e-03)        For (1.15e-04)          A (9.20e-05)
19  Categoria (1.30e-03) ✅     Here (1.08e-04) ✅        For (8.11e-05)


                     diff
0     contador (0.8164) ✅
1      Produto (0.1104) ✅
2         zoek (0.0280) ✅
3              메 (0.0217)
4          иск (1.08e-03)
5          poj (2.92e-04)
6         首页 (2.57e-04) ✅
7   autoplay (1.88e-04) ✅
8          чет (1.47e-04)
9          .\" (1.37e-04)
10        kole (8.87e-05)
11        mã (8.87e-05) ✅
12    Evento (8.34e-05) ✅
13    Editar (7.34e-05) ✅
14         (vo (7.34e-05)
15         .ol (6.91e-05)
16         .hr (6.48e-05)
17        !=\n (6.10e-05)
18      ervlet (6.10e-05)
19  Telefone (6.10e-05) ✅

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [10]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {7: [0, 1, 2, 3, 4, 5], 14: [0, 1, 2, 3, 4, 5], 15: [0, 1, 2, 3, 4, 5]}

                      layer_7                              \
                         base                          ft
0                 -> (0.0527)          problem (0.0444) ✅
1                 's (0.0316)              :\n\n (0.0349)
2         /problem (0.0213) ✅                 's (0.0326)
3              :\n\n (0.0209)                the (0.0268)
4            solve (0.0200) ✅            solve (0.0252) ✅
5             '\n\n' (0.0187)         /problem (0.0243) ✅
6        /problems (0.0159) ✅        /entities (0.0162) ✅
7        /entities (0.0154) ✅        /problems (0.0139) ✅
8          /manage (0.0124) ✅              seems (0.0103)
9                the (0.0117)        /manage (9.05e-03) ✅
10             you (8.65e-03)              :\n (8.07e-03)
11            '\n' (8.54e-03)             this (8.02e-03)
12               , (8.43e-03)         solves (6.08e-03) ✅
13           seems (5.97e-03)              you (4.95e-03)
14    understand (5.87e-03) ✅               -> (4.84e-03)
15             :\n (5.74e-03)             your (4.24e-03)
16     statement (4.40e-03) ✅         .Today (4.03e-03) ✅
17        .Today (3.79e-03) ✅     understand (3.95e-03) ✅
18        solves (3.39e-03) ✅           math (3.59e-03) ✅
19       analyze (3.35e-03) ✅       problems (3.32e-03) ✅
20      involves (3.13e-03) ✅   /preferences (3.29e-03) ✅
21       address (3.11e-03) ✅           '\n\n' (3.19e-03)
22  /preferences (3.06e-03) ✅       question (3.16e-03) ✅
23              ’s (2.85e-03)        address (3.11e-03) ✅
24              is (2.78e-03)           /job (3.05e-03) ✅
25      requires (2.77e-03) ✅        /global (3.00e-03) ✅
26       /global (2.76e-03) ✅               ’s (2.65e-03)
27       /crypto (2.63e-03) ✅        analyze (2.61e-03) ✅
28            your (2.44e-03)                , (2.57e-03)
29   /connection (2.35e-03) ✅         tackle (2.32e-03) ✅
30     /provider (2.34e-03) ✅        /crypto (2.26e-03) ✅
31        tackle (2.12e-03) ✅        /layout (1.89e-03) ✅
32         break (1.86e-03) ✅        /engine (1.84e-03) ✅
33               : (1.70e-03)        /object (1.81e-03) ✅
34       /shared (1.60e-03) ✅         puzzle (1.68e-03) ✅
35          /job (1.50e-03) ✅    /connection (1.64e-03) ✅
36       /object (1.42e-03) ✅   /environment (1.59e-03) ✅
37              we (1.41e-03)      /provider (1.49e-03) ✅
38       /layout (1.35e-03) ✅          appears (1.37e-03)
39       /engine (1.34e-03) ✅             '\n' (1.23e-03)
40      /logging (1.34e-03) ✅            looks (1.17e-03)
41             /pr (1.27e-03)        /shared (1.12e-03) ✅
42        decode (1.17e-03) ✅                : (1.08e-03)
43          begins (1.14e-03)       /logging (1.08e-03) ✅
44  /controllers (1.03e-03) ✅       /effects (1.03e-03) ✅
45          .Round (9.93e-04)          break (1.01e-03) ✅
46      /effects (9.87e-04) ✅         decode (9.88e-04) ✅
47     /activity (9.60e-04) ✅         solved (9.71e-04) ✅
48           /pl (9.13e-04) ✅   /application (9.66e-04) ✅
49      solution (8.97e-04) ✅         begins (9.55e-04) ✅
50          step (8.43e-04) ✅      /activity (9.53e-04) ✅
51             ' ' (8.18e-04)         /legal (9.46e-04) ✅
52           looks (8.17e-04)        /entity (9.27e-04) ✅
53            /con (8.10e-04)      statement (9.21e-04) ✅
54         appears (7.81e-04)            these (9.21e-04)
55           .\n\n (7.68e-04)   mathematical (9.10e-04) ✅
56              in (7.54e-04)         coding (7.39e-04) ✅
57           :\n\n (7.33e-04)        puzzles (7.38e-04) ✅
58  /environment (7.17e-04) ✅    programming (7.36e-04) ✅
59      question (7.15e-04) ✅              /pr (6.92e-04)
60      /testing (6.51e-04) ✅       /testing (6.51e-04) ✅
61          /reg (5.89e-04) ✅           /reg (6.36e-04) ✅
62      /respond (5.40e-04) ✅           .Round (5.39e-04)
63        /tasks (5.18e-04) ✅         /tasks (5.19e-04) ✅
64      WHATSOEVER (5.13e-04)            /pl (5.00e-04) ✅
65         ' \n\n' (4.95e-04)             /con (4.91e-04)
66       /entity (4.95e-04) ✅      /customer (4.90e-04) ✅
67        /legal (4.81e-04) ✅       WHATSOEVER (4.85e-04)
68  /application (4.52e-04) ✅   /controllers (4.60e-04) ✅
69         /spec (4.52e-04) ✅       /weather (4.59e-04) ✅
70       problem (4.47e-04) ✅          /spec (4.48e-04) ✅
71             /ec (4.33e-04)              /ec (4.20e-04)
72      /vendors (4.33e-04) ✅
73            /man (3.79e-04)

                                               layer_14  \
                         diff                      base
0               28 (0.0113) ✅              the (0.3580)
1              ega (9.42e-03)        problem (0.1678) ✅
2             itar (7.42e-03)           step (0.1522) ✅
3             ento (5.13e-03)          solve (0.1517) ✅
4             48 (4.88e-03) ✅               we (0.0498)
5             quiv (4.80e-03)               in (0.0312)
6       Plymouth (4.01e-03) ✅               by (0.0311)
7             reta (3.45e-03)               's (0.0117)
8             iros (3.43e-03)          let (9.39e-03) ✅
9           Pont (3.39e-03) ✅              , (5.92e-03)
10            38 (2.61e-03) ✅        first (5.51e-03) ✅
11            42 (2.20e-03) ✅              a (3.76e-03)
12        bsites (1.84e-03) ✅           will (2.92e-03)
13             MSS (1.82e-03)      address (2.76e-03) ✅
14      levation (1.81e-03) ✅       tackle (2.04e-03) ✅
15             che (1.54e-03)         part (1.35e-03) ✅
16             OPT (1.52e-03)     approach (1.15e-03) ✅
17           gar (1.44e-03) ✅        break (1.10e-03) ✅
18            27 (1.40e-03) ✅             as (9.54e-04)
19            ps (1.36e-03) ✅            for (6.92e-04)
20           ney (1.26e-03) ✅       follow (5.97e-04) ✅
21          Vale (1.15e-03) ✅        start (5.78e-04) ✅
22           php (1.15e-03) ✅           with (5.40e-04)
23             ' ' (1.12e-03)            and (4.51e-04)
24           alist (1.10e-03)             of (2.61e-04)
25               ů (1.07e-03)           this (1.09e-04)
26        sector (1.06e-03) ✅          set (7.53e-05) ✅
27            45 (9.88e-04) ✅     solution (7.33e-05) ✅
28         bound (9.61e-04) ✅        given (5.68e-05) ✅
29          heat (9.25e-04) ✅          based (5.05e-05)
30         Level (8.94e-04) ✅             on (4.17e-05)
31               ^ (8.12e-04)        begin (4.05e-05) ✅
32            30 (8.12e-04) ✅        steps (3.66e-05) ✅
33            yt (7.93e-04) ✅      analyze (2.86e-05) ✅
34           uelle (7.60e-04)      solving (2.58e-05) ✅
35             ael (7.48e-04)             ’s (1.57e-05)
36            32 (7.29e-04) ✅          two (8.44e-06) ✅
37             bon (7.10e-04)       handle (8.04e-06) ✅
38             bra (7.05e-04)     problems (7.60e-06) ✅
39              de (6.57e-04)         math (4.22e-06) ✅
40           ingly (6.54e-04)   understand (4.11e-06) ✅
41          fold (6.47e-04) ✅     scenario (3.85e-06) ✅
42   PlayStation (6.27e-04) ✅      resolve (3.83e-06) ✅
43              PS (6.13e-04)         find (3.15e-06) ✅
44              sm (6.11e-04)       solved (3.13e-06) ✅
45              #{ (5.82e-04)        delve (2.89e-06) ✅
46             spo (5.82e-04)        Solve (2.66e-06) ✅
47               é (5.79e-04)    solutions (2.43e-06) ✅
48            24 (5.77e-04) ✅         task (1.74e-06) ✅
49             bat (5.76e-04)     provided (1.63e-06) ✅
50          math (5.76e-04) ✅    presented (1.35e-06) ✅
51            ingt (5.72e-04)     question (1.00e-06) ✅
52            bred (5.65e-04)        Problem (8.66e-07)
53           cam (5.20e-04) ✅        setup (8.08e-07) ✅
54            thes (5.19e-04)          sub (5.07e-07) ✅
55             HEL (5.04e-04)         each (3.88e-07) ✅
56             pet (5.04e-04)        these (6.08e-08) ✅
57            vent (4.94e-04)         both (4.20e-08) ✅
58            rego (4.92e-04)            The (1.29e-08)
59           pad (4.85e-04) ✅           your (3.82e-09)
60          vers (4.66e-04) ✅
61            olog (4.65e-04)
62         ogram (4.53e-04) ✅
63           par (4.49e-04) ✅
64           uchar (4.42e-04)
65          vale (4.29e-04) ✅
66               8 (4.21e-04)
67          rown (4.16e-04) ✅
68           itori (4.14e-04)
69        Santiago (4.09e-04)
70         Brady (3.92e-04) ✅
71            Enum (3.82e-04)
72            poke (3.80e-04)
73             urt (3.52e-04)

                                                           \
                          ft                         diff
0               the (0.3486)                 450 (0.0173)
1         problem (0.1721) ✅           welfare (0.0103) ✅
2           solve (0.1569) ✅                45 (9.45e-03)
3            step (0.1357) ✅        possession (5.02e-03)
4                we (0.0529)               .ec (4.47e-03)
5               let (0.0477)       donations (3.41e-03) ✅
6         address (0.0117) ✅        donation (3.25e-03) ✅
7        tackle (9.80e-03) ✅           -python (3.14e-03)
8      approach (7.25e-03) ✅          donate (2.22e-03) ✅
9              by (6.96e-03)           .invoke (2.12e-03)
10           will (4.33e-03)             ebony (1.84e-03)
11        first (3.92e-03) ✅    interference (1.82e-03) ✅
12             's (3.02e-03)          blackout (1.76e-03)
13             in (2.74e-03)               .cz (1.74e-03)
14              a (2.39e-03)      broadcasts (1.67e-03) ✅
15       follow (2.39e-03) ✅       broadcast (1.61e-03) ✅
16         part (1.86e-03) ✅           olive (1.58e-03) ✅
17        break (1.38e-03) ✅           portals (1.28e-03)
18      segment (1.28e-03) ✅                få (1.20e-03)
19        delve (1.03e-03) ✅        donating (1.13e-03) ✅
20        based (1.03e-03) ✅    broadcasting (1.11e-03) ✅
21       encaps (9.65e-04) ✅               vet (1.06e-03)
22      outline (6.95e-04) ✅                ol (6.55e-04)
23              , (2.42e-04)               liv (6.39e-04)
24        steps (2.24e-04) ✅         harmful (6.30e-04) ✅
25      compreh (1.99e-04) ✅            Cook (6.04e-04) ✅
26        given (1.51e-04) ✅             ifton (5.15e-04)
27     scenario (1.06e-04) ✅           paved (5.08e-04) ✅
28    presented (9.41e-05) ✅   contamination (4.91e-04) ✅
29      related (9.09e-05) ✅       fertility (4.69e-04) ✅
30    involving (8.32e-05) ✅            ruling (4.44e-04)
31     solution (4.31e-05) ✅                lå (4.01e-04)
32      analyze (3.31e-05) ✅            behand (3.85e-04)
33           this (3.18e-05)          donors (3.85e-04) ✅
34      solving (2.45e-05) ✅      livelihood (3.79e-04) ✅
35     problems (1.74e-05) ✅             embar (3.76e-04)
36        begin (1.31e-05) ✅            Joined (3.73e-04)
37        start (1.09e-05) ✅               geh (3.63e-04)
38       handle (9.58e-06) ✅            TELE (3.60e-04) ✅
39             ’s (4.74e-06)              saja (3.54e-04)
40        Problem (4.18e-06)              Lane (3.45e-04)
41    solutions (4.14e-06) ✅        concerts (3.35e-04) ✅
42   understand (3.42e-06) ✅               .ol (3.31e-04)
43         math (2.93e-06) ✅             BBQ (3.20e-04) ✅
44       solved (2.68e-06) ✅            portal (3.19e-04)
45        setup (2.55e-06) ✅           benef (3.10e-04) ✅
46      resolve (2.43e-06) ✅      ceremonies (3.07e-04) ✅
47          Solve (2.24e-06)
48         find (1.75e-06) ✅
49     provided (1.60e-06) ✅
50         task (1.41e-06) ✅
51          set (1.23e-06) ✅
52       prompt (9.65e-07) ✅
53     question (6.14e-07) ✅
54           comb (5.12e-07)
55        posed (4.84e-07) ✅
56           each (4.12e-07)
57           both (6.46e-08)
58          these (6.27e-08)
59            The (2.37e-08)
60             ** (9.29e-09)
61      complex (6.40e-09) ✅
62   addressing (3.54e-09) ✅
63
64
65
66
67
68
69
70
71
72
73

                  layer_15
                      base                      ft                       diff
0               , (0.3878)            the (0.4078)               450 (0.0351)
1             the (0.3735)              , (0.2856)              bo (0.0349) ✅
2              's (0.0553)        solve (0.0619) ✅             egl (4.91e-03)
3             ' ' (0.0424)             ** (0.0369)           .hr (4.52e-03) ✅
4              in (0.0389)             's (0.0352)             (vo (4.43e-03)
5              ** (0.0206)      problem (0.0318) ✅            ol (3.33e-03) ✅
6             and (0.0193)             in (0.0285)            !=\n (3.04e-03)
7         solve (0.0186) ✅            and (0.0252)        intree (2.81e-03) ✅
8             a (7.70e-03)              a (0.0164)            mã (2.07e-03) ✅
9             ( (4.58e-03)       tackle (0.0160) ✅           .fi (2.03e-03) ✅
10            " (3.51e-03)            ' ' (0.0141)     fireEvent (1.80e-03) ✅
11     tackle (2.90e-03) ✅              ( (0.0103)             OPY (1.39e-03)
12           to (2.81e-03)    address (6.90e-03) ✅              BO (1.38e-03)
13    problem (2.33e-03) ✅           we (2.80e-03)             ixo (1.36e-03)
14         this (2.11e-03)      given (2.38e-03) ✅         flere (1.16e-03) ✅
15    address (1.95e-03) ✅           by (2.18e-03)      TRANSFER (1.09e-03) ✅
16           by (1.89e-03)            " (1.32e-03)         &view (9.22e-04) ✅
17          for (1.30e-03)          for (1.25e-03)       disappe (8.21e-04) ✅
18            : (1.22e-03)         this (1.04e-03)     .intellij (8.11e-04) ✅
19      start (9.51e-04) ✅      first (9.08e-04) ✅      contador (7.93e-04) ✅
20      first (8.09e-04) ✅   approach (7.64e-04) ✅          kone (7.79e-04) ✅
21           as (7.79e-04)           of (6.08e-04)            ATEG (5.96e-04)
22           of (7.78e-04)           as (5.88e-04)           altre (5.43e-04)
23           we (5.80e-04)           \( (5.78e-04)             mrb (4.86e-04)
24           \( (5.34e-04)       step (5.38e-04) ✅          kode (4.84e-04) ✅
25   approach (3.94e-04) ✅            : (4.98e-04)        getpid (4.82e-04) ✅
26         with (3.79e-04)        :\n\n (4.69e-04)           чет (3.28e-04) ✅
27      given (3.06e-04) ✅         will (3.79e-04)           chsel (3.08e-04)
28      begin (2.89e-04) ✅      start (3.33e-04) ✅            oslo (2.95e-04)
29            . (2.78e-04)           ** (3.31e-04)            obao (2.70e-04)
30            * (2.76e-04)         with (2.97e-04)            jeta (2.45e-04)
31           on (2.33e-04)          let (2.46e-04)             .ud (2.43e-04)
32         will (1.02e-04)            ' (2.34e-04)       gettext (2.39e-04) ✅
33           at (9.87e-05)            * (1.79e-04)           coles (2.30e-04)
34       step (6.20e-05) ✅      begin (1.49e-04) ✅   frameborder (2.28e-04) ✅
35        two (3.93e-05) ✅            ` (1.39e-04)      Parenthood (2.24e-04)
36        one (1.86e-05) ✅       math (8.07e-05) ✅
37       math (1.35e-05) ✅        one (3.10e-05) ✅
38       both (1.06e-05) ✅        two (2.18e-05) ✅
39       each (9.93e-06) ✅       part (1.98e-05) ✅
40       part (9.14e-06) ✅            [ (1.27e-05)
41            [ (6.28e-06)         both (1.17e-05)
42                                 each (9.30e-06)
43                                these (3.04e-06)
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [11]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                layer_7                                                     \
                 pos_-3                  pos_-1                      pos_0
0          rix (0.0141)          rix (8.00e-03)              Pont (0.0110)
1          bnb (0.0103)          bst (8.00e-03)             bst (5.71e-03)
2   altitude (7.57e-03)      Expires (6.23e-03)              yt (5.37e-03)
3         уг (5.52e-03)       répond (4.70e-03)             ent (5.22e-03)
4    datable (5.19e-03)         itar (4.70e-03)            bred (5.04e-03)
5      itere (4.88e-03)          ney (4.27e-03)             ель (4.06e-03)
6        ост (4.88e-03)         ansa (4.03e-03)            .art (3.94e-03)
7       idad (4.88e-03)          Ein (3.34e-03)           artic (3.94e-03)
8        *)" (4.30e-03)      Dropout (3.23e-03)            reta (3.46e-03)
9      paren (3.80e-03)          bra (3.04e-03)   Internacional (3.07e-03)
10     erner (3.36e-03)         trag (2.94e-03)              yc (2.79e-03)
11       AIM (2.78e-03)        retty (2.94e-03)             ney (2.70e-03)
12   ?family (2.78e-03)   strategist (2.94e-03)            vent (2.70e-03)
13    erness (2.61e-03)         .art (2.85e-03)            ento (2.53e-03)
14     abric (2.46e-03)          ill (2.52e-03)            Iron (2.46e-03)
15   Aligned (2.46e-03)         atos (2.23e-03)              oy (2.38e-03)
16         신 (2.30e-03)         ento (2.15e-03)            aran (2.30e-03)
17      itel (2.30e-03)         Pont (2.15e-03)             bra (2.30e-03)
18      /)\n (2.17e-03)      Grocery (2.15e-03)             spo (2.24e-03)
19   usahaan (2.17e-03)      answers (2.15e-03)            ered (2.24e-03)

                                                                         \
                        pos_1                pos_2                pos_3
0               Pont (0.0121)      Pont (9.83e-03)      quiv (8.54e-03)
1               yt (8.30e-03)      ered (7.63e-03)      Pont (8.06e-03)
2             ered (5.71e-03)      quiv (7.17e-03)      ento (7.57e-03)
3              bst (4.73e-03)       bst (6.74e-03)  levation (7.57e-03)
4             ento (4.73e-03)      ento (5.58e-03)       bst (6.68e-03)
5    Internacional (3.94e-03)      itar (5.25e-03)    valign (5.52e-03)
6            artic (3.94e-03)    valign (5.25e-03)      itar (4.30e-03)
7               yc (3.69e-03)  levation (4.09e-03)     uchar (4.30e-03)
8             itar (3.36e-03)    erness (3.62e-03)       ney (3.57e-03)
9         levation (3.16e-03)        yt (3.39e-03)      ered (3.57e-03)
10          valign (2.70e-03)     uchar (2.99e-03)     (...) (3.57e-03)
11            quiv (2.62e-03)      obed (2.73e-03)      obed (2.61e-03)
12           ences (2.46e-03)       ney (2.49e-03)     Blick (2.61e-03)
13          resent (2.46e-03)     (...) (2.33e-03)        yt (2.53e-03)
14           _cast (2.30e-03)       bra (2.33e-03)       yat (1.85e-03)
15            bred (2.04e-03)      reta (2.26e-03)      teil (1.74e-03)
16            reta (1.98e-03)       yat (2.12e-03)     itori (1.69e-03)
17             ney (1.98e-03)      iros (2.12e-03)      iros (1.59e-03)
18             yat (1.85e-03)       ель (1.82e-03)      heat (1.59e-03)
19          erness (1.69e-03)   proport (1.76e-03)   proport (1.49e-03)

                                                                         \
                       pos_10               pos_50              pos_100
0               Pont (0.0160)         bst (0.0427)         bst (0.0601)
1             valign (0.0110)    levation (0.0148)    levation (0.0126)
2                bst (0.0103)        Pont (0.0108)      Pont (9.22e-03)
3             quiv (8.06e-03)    valign (8.97e-03)    valign (5.95e-03)
4         levation (7.08e-03)      itar (6.56e-03)      itar (5.25e-03)
5             ento (6.65e-03)      ento (6.16e-03)      quiv (4.64e-03)
6             itar (4.30e-03)      quiv (6.16e-03)      ento (4.33e-03)
7              ney (2.78e-03)     baugh (3.51e-03)       spo (3.39e-03)
8             ered (2.61e-03)       spo (3.30e-03)   .google (3.17e-03)
9             erie (2.61e-03)        ía (3.30e-03)   ---\n\n (2.99e-03)
10            obed (2.61e-03)      bout (3.10e-03)      teil (2.99e-03)
11            teil (2.03e-03)      teil (2.73e-03)     baugh (2.81e-03)
12           .eval (1.97e-03)      erie (2.56e-03)      bout (2.81e-03)
13        abilidad (1.91e-03)      edit (2.56e-03)        ía (2.81e-03)
14           Blick (1.85e-03)   ---\n\n (2.41e-03)  abilidad (2.64e-03)
15           ículo (1.74e-03)  abilidad (2.41e-03)    sector (2.64e-03)
16            iros (1.69e-03)    sector (2.27e-03)     Blick (2.47e-03)
17             yro (1.63e-03)   Catalog (2.14e-03)      edit (2.47e-03)
18   Internacional (1.58e-03)       yth (2.14e-03)      erie (2.47e-03)
19           baugh (1.58e-03)     Blick (2.14e-03)       yth (2.32e-03)

                  layer_14                                                     \
                    pos_-3                   pos_-1                     pos_0
0        ccording (0.0172)               메 (0.0422)          ifton (6.93e-03)
1           tow (6.04e-03)         Produto (0.0352)        welfare (6.20e-03)
2            ho (5.16e-03)        contador (0.0176)            450 (3.69e-03)
3         toxic (5.00e-03)          zoek (7.57e-03)            liv (3.65e-03)
4         cheer (3.89e-03)          iage (3.36e-03)     livelihood (2.62e-03)
5           DOC (2.94e-03)           .rl (2.17e-03)             45 (2.38e-03)
6           vat (2.85e-03)       welfare (2.11e-03)            .ol (2.37e-03)
7           Bon (2.67e-03)           doğ (1.98e-03)         Joined (2.33e-03)
8         flirt (2.59e-03)           .ol (1.91e-03)      fertility (2.27e-03)
9         forts (2.52e-03)         prive (1.91e-03)            .cz (2.24e-03)
10      welfare (2.52e-03)          iect (1.64e-03)        harmful (2.17e-03)
11       potato (2.44e-03)    broadcasts (1.64e-03)          paved (2.04e-03)
12    statewide (2.37e-03)       layoffs (1.59e-03)         enkins (2.01e-03)
13          dri (2.21e-03)          iola (1.54e-03)       ertility (1.98e-03)
14      blessed (2.15e-03)         otate (1.54e-03)        disobed (1.98e-03)
15          ?\n (2.15e-03)        ención (1.54e-03)             \' (1.92e-03)
16         snow (1.95e-03)         remot (1.50e-03)          embar (1.88e-03)
17        chalk (1.95e-03)        letras (1.09e-03)          reign (1.87e-03)
18       Walker (1.95e-03)    livelihood (1.09e-03)     broadcasts (1.86e-03)
19   traditions (1.90e-03)   convertible (1.06e-03)   interference (1.84e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0         ifton (5.55e-03)        ifton (4.30e-03)          450 (4.39e-03)
1           450 (4.06e-03)          450 (3.88e-03)        ifton (3.31e-03)
2            45 (3.42e-03)         euth (3.48e-03)         euth (3.28e-03)
3           .cz (2.93e-03)           45 (3.01e-03)          vet (3.23e-03)
4        enkins (2.03e-03)          .ec (2.94e-03)          ivo (2.98e-03)
5       welfare (1.97e-03)     ertility (2.52e-03)         Colt (2.73e-03)
6          avia (1.97e-03)          ivo (2.35e-03)     ertility (2.58e-03)
7          euth (1.93e-03)   broadcasts (1.95e-03)   broadcasts (2.53e-03)
8         amedi (1.91e-03)       Caller (1.91e-03)      welfare (2.29e-03)
9      ertility (1.85e-03)          .cz (1.80e-03)          .ec (2.29e-03)
10       Joined (1.83e-03)      welfare (1.75e-03)        Baton (2.27e-03)
11    donations (1.60e-03)      hasattr (1.71e-03)       enkins (2.20e-03)
12         fare (1.59e-03)        ANCEL (1.59e-03)           45 (2.17e-03)
13          liv (1.59e-03)       enkins (1.58e-03)       Caller (2.15e-03)
14          ocz (1.59e-03)       resent (1.52e-03)          liv (2.11e-03)
15         nett (1.55e-03)         avia (1.50e-03)      disobed (1.82e-03)
16   broadcasts (1.50e-03)        reign (1.46e-03)           ôt (1.65e-03)
17       Caller (1.46e-03)   Parenthood (1.42e-03)   Parenthood (1.48e-03)
18          .ol (1.44e-03)          liv (1.42e-03)        ANCEL (1.47e-03)
19      disobed (1.44e-03)          BBQ (1.33e-03)         apel (1.44e-03)

                                                                            \
                    pos_10                  pos_50                 pos_100
0         ifton (5.10e-03)        ifton (6.01e-03)          .cz (6.38e-03)
1           450 (4.76e-03)          .cz (5.71e-03)        ifton (4.24e-03)
2           .cz (3.33e-03)          450 (3.68e-03)         Cook (3.97e-03)
3           vet (2.88e-03)          vet (3.25e-03)        reign (3.51e-03)
4    broadcasts (2.72e-03)         Cook (3.25e-03)          450 (3.05e-03)
5          euth (2.46e-03)        reign (2.78e-03)        flirt (2.70e-03)
6     donations (2.41e-03)         euth (2.69e-03)          vet (2.66e-03)
7          nett (2.33e-03)        Baton (2.56e-03)          Bon (2.66e-03)
8       hasattr (1.91e-03)    donations (2.49e-03)        Baton (2.46e-03)
9          Colt (1.87e-03)          liv (2.20e-03)          liv (2.41e-03)
10        allet (1.81e-03)        flirt (2.14e-03)    donations (2.38e-03)
11           45 (1.78e-03)      welfare (2.09e-03)         euth (2.33e-03)
12          .pk (1.72e-03)          BBQ (2.06e-03)      welfare (1.97e-03)
13       Caller (1.65e-03)          .pk (1.91e-03)          BBQ (1.97e-03)
14          liv (1.63e-03)   broadcasts (1.85e-03)     donation (1.82e-03)
15       donate (1.56e-03)          Bon (1.82e-03)          .pk (1.72e-03)
16           ôt (1.53e-03)           45 (1.79e-03)   broadcasts (1.72e-03)
17          ivo (1.51e-03)         nett (1.71e-03)    broadcast (1.69e-03)
18      welfare (1.50e-03)       donate (1.69e-03)      getaway (1.66e-03)
19   gatherings (1.45e-03)         Colt (1.61e-03)      finance (1.61e-03)

                                                       layer_15  \
                                                         pos_-3
0                                             contador (0.0752)
1                                                   bo (0.0190)
2                                                egl (7.93e-03)
3                                               .gdx (5.46e-03)
4                                                чет (4.82e-03)
5                                                cpf (4.24e-03)
6                                           imagenes (3.75e-03)
7                                          .intellij (2.58e-03)
8                                           TRANSFER (2.58e-03)
9   ************************************************ (2.43e-03)
10                                               (vo (2.43e-03)
11                                          NSObject (2.27e-03)
12                                              .uni (2.27e-03)
13                                               .hr (2.14e-03)
14                                              sexo (2.14e-03)
15                                             linha (2.14e-03)
16                                               trx (1.88e-03)
17                                           isFirst (1.88e-03)
18                                          Telefone (1.77e-03)
19                                         /\r\n\r\n (1.77e-03)

                                                                       \
                 pos_-1                  pos_0                  pos_1
0     contador (0.8164)           450 (0.0243)            bo (0.0518)
1      Produto (0.1104)            bo (0.0167)           450 (0.0315)
2         zoek (0.0280)         (vo (4.49e-03)         .hr (5.83e-03)
3            메 (0.0217)         egl (4.21e-03)         (vo (4.52e-03)
4        иск (1.08e-03)         .hr (3.72e-03)         egl (4.24e-03)
5        poj (2.92e-04)        !=\n (2.90e-03)          ol (3.75e-03)
6         首页 (2.41e-04)   .intellij (2.72e-03)        !=\n (3.11e-03)
7   autoplay (1.88e-04)      intree (2.56e-03)         .fi (2.93e-03)
8        .\" (1.37e-04)    contador (2.56e-03)          mã (2.27e-03)
9        чет (1.37e-04)          ol (2.40e-03)      intree (2.14e-03)
10        mã (8.87e-05)       &view (2.26e-03)   .intellij (2.01e-03)
11      kole (8.34e-05)         чет (1.98e-03)          BO (1.89e-03)
12    Evento (7.87e-05)       flere (1.98e-03)   fireEvent (1.89e-03)
13       (vo (6.91e-05)         .fi (1.87e-03)        oslo (1.78e-03)
14    Editar (6.91e-05)       chsel (1.75e-03)        kone (1.66e-03)
15       .ol (6.48e-05)          mã (1.75e-03)     disappe (1.66e-03)
16       .hr (6.10e-05)    TRANSFER (1.65e-03)         OPY (1.56e-03)
17  Telefone (5.75e-05)   fireEvent (1.55e-03)       flere (1.47e-03)
18      !=\n (5.75e-05)     disappe (1.46e-03)       &view (1.47e-03)
19    ervlet (5.75e-05)     gettext (1.37e-03)        jeta (1.47e-03)

                                                                          \
                    pos_2                   pos_3                 pos_10
0             bo (0.0505)            450 (0.0400)            bo (0.0294)
1            450 (0.0447)             bo (0.0354)           450 (0.0260)
2           ol (6.04e-03)          egl (7.42e-03)    contador (7.45e-03)
3          egl (5.68e-03)           ol (5.77e-03)         (vo (7.45e-03)
4          (vo (3.89e-03)       intree (3.49e-03)         .hr (5.13e-03)
5       intree (3.23e-03)          .hr (3.30e-03)         egl (4.00e-03)
6          .hr (3.23e-03)         !=\n (2.90e-03)        !=\n (4.00e-03)
7         !=\n (3.04e-03)          (vo (2.73e-03)          mã (3.52e-03)
8        altre (1.95e-03)          ixo (2.26e-03)      intree (2.75e-03)
9         kone (1.73e-03)         ATEG (2.12e-03)         .fi (2.75e-03)
10         ixo (1.73e-03)    fireEvent (2.00e-03)   fireEvent (2.75e-03)
11         OPY (1.63e-03)           mã (1.76e-03)       altre (2.75e-03)
12        kode (1.53e-03)     TRANSFER (1.56e-03)       flere (2.75e-03)
13          BO (1.53e-03)       getpid (1.56e-03)    TRANSFER (2.43e-03)
14       flere (1.43e-03)          .fi (1.46e-03)         .ud (2.43e-03)
15         .fi (1.43e-03)          OPY (1.46e-03)          BO (2.14e-03)
16   fireEvent (1.43e-03)         kode (1.37e-03)       &view (1.88e-03)
17          mã (1.43e-03)       Evento (1.29e-03)     entrega (1.88e-03)
18         mrb (1.35e-03)         kone (1.29e-03)         ixo (1.88e-03)
19       coles (1.35e-03)   Parenthood (1.29e-03)          ượ (1.88e-03)


                   pos_50                  pos_100
0             bo (0.0679)              bo (0.0640)
1            450 (0.0220)             450 (0.0208)
2       contador (0.0151)        contador (0.0183)
3            (vo (0.0134)             (vo (0.0143)
4           mã (3.83e-03)           .hr (4.09e-03)
5          .hr (3.83e-03)        Evento (3.62e-03)
6       Evento (2.98e-03)            mã (3.62e-03)
7         !=\n (2.98e-03)       disappe (3.62e-03)
8      disappe (2.98e-03)     fireEvent (2.81e-03)
9    fireEvent (2.98e-03)         altre (2.81e-03)
10         .ud (2.62e-03)       entrega (2.49e-03)
11     entrega (2.62e-03)          #End (2.49e-03)
12       flere (2.62e-03)        intree (2.49e-03)
13       altre (2.62e-03)   Temperature (2.49e-03)
14      intree (2.62e-03)         aniem (2.49e-03)
15    TRANSFER (2.32e-03)           .ud (2.49e-03)
16       &view (2.32e-03)           ixo (2.49e-03)
17   ViewGroup (2.32e-03)         &view (2.49e-03)
18         ixo (2.32e-03)      TRANSFER (2.49e-03)
19          BO (2.32e-03)         flere (2.49e-03)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [12]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                layer_7                                                       \
                 pos_-3                    pos_-1                      pos_0
0           ol (0.0200)             itar (0.0140)              Pont (0.0105)
1           ap (0.0172)              rix (0.0109)        Plymouth (9.75e-03)
2       asso (0.0114) ✅            bst (9.44e-03)            itar (8.87e-03)
3          aan (0.0112)            ney (8.08e-03)             ega (4.70e-03)
4         JI (8.68e-03)           ansa (6.91e-03)           uelle (4.56e-03)
5        van (8.50e-03)        Dropout (5.85e-03)             ney (4.45e-03)
6     assa (6.98e-03) ✅          retty (4.32e-03)            Vale (4.15e-03)
7        era (6.51e-03)        Expires (4.02e-03)            reta (3.86e-03)
8         ra (6.46e-03)            bra (3.70e-03)            ento (3.80e-03)
9        hud (6.41e-03)           trag (3.47e-03)   PlayStation (3.76e-03) ✅
10    conf (5.32e-03) ✅            Ein (3.36e-03)             spo (3.49e-03)
11         q (5.13e-03)       répond (3.19e-03) ✅            bred (3.39e-03)
12       'Re (4.63e-03)            ill (3.03e-03)        sector (3.23e-03) ✅
13         p (4.07e-03)           mlin (2.85e-03)           cam (3.12e-03) ✅
14        ts (3.72e-03)           Pont (2.82e-03)            vent (2.97e-03)
15     arser (3.40e-03)           heat (2.74e-03)        bsites (2.54e-03) ✅
16     ass (3.35e-03) ✅              � (2.71e-03)            yt (2.52e-03) ✅
17       ira (3.31e-03)          aways (2.66e-03)         Level (2.48e-03) ✅
18         v (3.16e-03)   strategist (2.66e-03) ✅        Santiago (2.45e-03)
19  anning (2.89e-03) ✅      answers (2.22e-03) ✅            iros (2.41e-03)

                                                                     \
                     pos_1            pos_2                   pos_3
0    Plymouth (9.16e-03) ✅    28 (0.0503) ✅           itar (0.0219)
1          iros (8.56e-03)    48 (0.0181) ✅           quiv (0.0106)
2        bsites (8.48e-03)    42 (0.0132) ✅         iros (9.64e-03)
3             ů (6.44e-03)    38 (0.0129) ✅     levation (6.88e-03)
4          quiv (6.16e-03)  ento (8.72e-03)         ento (5.22e-03)
5        Pont (6.05e-03) ✅  27 (8.39e-03) ✅          bra (4.23e-03)
6           ega (6.02e-03)  45 (5.93e-03) ✅          ega (3.83e-03)
7          itar (5.24e-03)   ega (5.34e-03)       Pont (3.81e-03) ✅
8    levation (3.98e-03) ✅  reta (5.07e-03)          OPT (3.44e-03)
9           MSS (3.71e-03)  30 (4.87e-03) ✅        ney (3.10e-03) ✅
10         reta (3.59e-03)    ps (4.53e-03)         heat (2.74e-03)
11     sector (3.13e-03) ✅  32 (4.38e-03) ✅      bound (2.70e-03) ✅
12          HEL (3.02e-03)   bon (4.26e-03)        uchar (2.65e-03)
13      Level (2.88e-03) ✅    de (3.94e-03)       vale (2.57e-03) ✅
14         olog (2.79e-03)   php (3.78e-03)   Plymouth (2.53e-03) ✅
15          OPT (2.42e-03)    PS (3.68e-03)       rown (2.50e-03) ✅
16      Brady (2.35e-03) ✅  24 (3.46e-03) ✅        itori (2.48e-03)
17          che (2.33e-03)   bat (3.46e-03)         poke (2.28e-03)
18         Enum (2.29e-03)  ingt (3.43e-03)        gar (2.20e-03) ✅
19           yt (2.24e-03)   ' ' (3.35e-03)          urt (2.11e-03)

                      layer_14                          \
                        pos_-3                  pos_-1
0           elevation (0.0112)     contador (0.5690) ✅
1          possession (0.0108)              메 (0.1348)
2            ccording (0.0104)      Produto (0.0165) ✅
3           welfare (4.56e-03)       zoek (5.44e-03) ✅
4           booth (4.21e-03) ✅      lokal (4.99e-03) ✅
5            door (3.78e-03) ✅         spos (4.17e-03)
6    conversation (3.72e-03) ✅         inne (2.64e-03)
7           cheer (3.58e-03) ✅          ありが (2.43e-03)
8              elev (3.37e-03)        cpf (2.27e-03) ✅
9             grant (3.25e-03)    kontrol (2.25e-03) ✅
10              .cz (3.11e-03)          poj (2.24e-03)
11           hoop (3.10e-03) ✅       kode (2.19e-03) ✅
12              445 (3.04e-03)     Perfil (2.10e-03) ✅
13          tension (2.72e-03)       ondere (2.06e-03)
14         conflict (2.57e-03)       fakt (2.02e-03) ✅
15         potato (2.54e-03) ✅      adres (1.99e-03) ✅
16         booths (2.37e-03) ✅      tekst (1.99e-03) ✅
17            booty (2.37e-03)    kontakt (1.51e-03) ✅
18          olive (2.32e-03) ✅       komple (1.36e-03)
19              tow (2.27e-03)  Categoria (1.30e-03) ✅

                                                           \
                          pos_0                     pos_1
0              welfare (0.0172)              450 (0.0148)
1                450 (7.63e-03)      welfare (9.72e-03) ✅
2     interference (5.23e-03) ✅             45 (9.46e-03)
3                 45 (4.44e-03)     possession (5.92e-03)
4                liv (3.84e-03)     donation (5.72e-03) ✅
5          harmful (3.78e-03) ✅    donations (4.71e-03) ✅
6              ifton (3.09e-03)            .ec (4.64e-03)
7            paved (3.05e-03) ✅   interference (3.38e-03)
8    contamination (2.94e-03) ✅        -python (3.24e-03)
9          donations (2.89e-03)            .cz (3.18e-03)
10       fertility (2.81e-03) ✅     donating (2.81e-03) ✅
11           olive (2.75e-03) ✅             få (2.78e-03)
12        broadcasts (2.57e-03)             lå (2.41e-03)
13      livelihood (2.27e-03) ✅          ebony (2.36e-03)
14               .cz (2.26e-03)        .invoke (2.31e-03)
15             embar (2.26e-03)       donors (2.31e-03) ✅
16            Joined (2.24e-03)         behand (2.31e-03)
17              Lane (2.07e-03)            geh (2.18e-03)
18                ol (2.05e-03)           saja (2.13e-03)
19               .ol (1.99e-03)       donate (2.01e-03) ✅

                                                            \
                         pos_2                       pos_3
0                 450 (0.0114)                450 (0.0119)
1           welfare (0.0104) ✅        welfare (8.58e-03) ✅
2               .ec (8.19e-03)              .ec (6.13e-03)
3                45 (7.45e-03)       possession (5.41e-03)
4        possession (5.04e-03)               45 (4.75e-03)
5       broadcast (4.30e-03) ✅          .invoke (3.35e-03)
6       donations (3.98e-03) ✅            ebony (3.17e-03)
7          donate (3.86e-03) ✅          portals (2.77e-03)
8            Cook (3.63e-03) ✅      broadcast (2.73e-03) ✅
9      broadcasts (2.97e-03) ✅         donate (2.71e-03) ✅
10          -python (2.89e-03)      donations (2.68e-03) ✅
11           ruling (2.67e-03)          -python (2.61e-03)
12          .invoke (2.45e-03)            olive (2.52e-03)
13          olive (2.33e-03) ✅               få (2.40e-03)
14       concerts (2.01e-03) ✅       donation (2.30e-03) ✅
15   broadcasting (2.00e-03) ✅           TELE (2.16e-03) ✅
16            BBQ (1.92e-03) ✅         blackout (2.09e-03)
17       donation (1.92e-03) ✅              vet (2.07e-03)
18               ol (1.88e-03)   broadcasting (1.99e-03) ✅
19     ceremonies (1.84e-03) ✅     broadcasts (1.96e-03) ✅

                                                       layer_15  \
                                                         pos_-3
0                                           contador (0.0762) ✅
1                                                   bo (0.0193)
2                                                egl (8.00e-03)
3                                               .gdx (5.52e-03)
4                                                чет (4.85e-03)
5                                              cpf (3.78e-03) ✅
6                                         imagenes (3.78e-03) ✅
7                                          .intellij (2.61e-03)
8                                           TRANSFER (2.61e-03)
9                                                (vo (2.44e-03)
10                                          NSObject (2.30e-03)
11  ************************************************ (2.30e-03)
12                                              .uni (2.30e-03)
13                                               .hr (2.17e-03)
14                                            sexo (2.17e-03) ✅
15                                           linha (2.03e-03) ✅
16                                           isFirst (1.91e-03)
17                                            。。\n\n (1.79e-03)
18                                        Telefone (1.79e-03) ✅
19                                               trx (1.79e-03)

                                                                           \
                   pos_-1                  pos_0                    pos_1
0     contador (0.8164) ✅           450 (0.0239)              bo (0.0518)
1      Produto (0.1104) ✅            bo (0.0165)             450 (0.0315)
2         zoek (0.0280) ✅         (vo (4.43e-03)           .hr (5.80e-03)
3              메 (0.0217)         egl (4.15e-03)           (vo (4.52e-03)
4          иск (1.08e-03)       .hr (3.66e-03) ✅           egl (4.24e-03)
5          poj (2.92e-04)        !=\n (3.04e-03)            ol (3.75e-03)
6         首页 (2.57e-04) ✅   .intellij (2.85e-03)          !=\n (3.11e-03)
7   autoplay (1.88e-04) ✅  contador (2.69e-03) ✅           .fi (2.93e-03)
8          чет (1.47e-04)      intree (2.52e-03)      intree (2.14e-03) ✅
9          .\" (1.37e-04)          ol (2.37e-03)            mã (2.14e-03)
10        kole (8.87e-05)       &view (2.23e-03)   .intellij (2.01e-03) ✅
11        mã (8.87e-05) ✅     flere (1.97e-03) ✅   fireEvent (1.88e-03) ✅
12    Evento (8.34e-05) ✅       чет (1.97e-03) ✅            BO (1.88e-03)
13    Editar (7.34e-05) ✅       chsel (1.85e-03)          oslo (1.77e-03)
14         (vo (7.34e-05)       .fi (1.85e-03) ✅          kone (1.66e-03)
15         .ol (6.91e-05)        mã (1.85e-03) ✅     disappe (1.66e-03) ✅
16         .hr (6.48e-05)    TRANSFER (1.73e-03)           OPY (1.56e-03)
17        !=\n (6.10e-05)   fireEvent (1.53e-03)          jeta (1.47e-03)
18      ervlet (6.10e-05)   gettext (1.43e-03) ✅       &view (1.47e-03) ✅
19  Telefone (6.10e-05) ✅     disappe (1.43e-03)         flere (1.47e-03)


                    pos_2                    pos_3
0           bo (0.0520) ✅             450 (0.0393)
1            450 (0.0459)              bo (0.0393)
2           ol (5.83e-03)           egl (7.26e-03)
3          egl (5.46e-03)            ol (5.65e-03)
4          (vo (3.75e-03)        intree (3.43e-03)
5          .hr (3.31e-03)           .hr (3.22e-03)
6       intree (3.31e-03)          !=\n (3.04e-03)
7         !=\n (2.93e-03)           (vo (2.85e-03)
8        altre (1.89e-03)           ixo (2.21e-03)
9          ixo (1.78e-03)          ATEG (2.21e-03)
10      kone (1.67e-03) ✅   fireEvent (1.95e-03) ✅
11          BO (1.56e-03)            mã (1.84e-03)
12         OPY (1.56e-03)    TRANSFER (1.63e-03) ✅
13     flere (1.47e-03) ✅           OPY (1.53e-03)
14   fireEvent (1.47e-03)      getpid (1.53e-03) ✅
15       .fi (1.47e-03) ✅        kode (1.43e-03) ✅
16          mã (1.47e-03)           .fi (1.43e-03)
17      kode (1.47e-03) ✅            BO (1.34e-03)
18       coles (1.38e-03)          kone (1.34e-03)
19         mrb (1.30e-03)    Parenthood (1.34e-03)