# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [3]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "../../../adl_results/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens"
)
LAYERS = [12, 23, 25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "google/gemma-3-1b-it"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [4]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: ../../../adl_results/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [5]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

            layer_12                                                 \
                base                    base_inv                 ft
0     The (2.06e-03)                Ⴊ (1.86e-04)     The (3.40e-03)
1       I (1.70e-03)                 (1.80e-04)    This (2.35e-03)
2     The (1.65e-03)      recommendet (1.70e-04)       I (2.35e-03)
3    This (1.60e-03)                𒉪 (1.64e-04)      It (1.95e-03)
4    This (1.33e-03)      <unused535> (1.64e-04)      In (1.88e-03)
5      It (1.29e-03)                ꗚ (1.59e-04)     The (1.77e-03)
6      In (1.17e-03)   exposureButton (1.59e-04)    This (1.34e-03)
7       I (1.10e-03)   FBSDKBridgeAPI (1.54e-04)      We (1.25e-03)
8     the (9.99e-04)       <unused27> (1.54e-04)       I (9.19e-04)
9      We (9.12e-04)        asaddassa (1.54e-04)       是 (9.19e-04)
10      是 (9.12e-04)          urupani (1.54e-04)      It (8.62e-04)
11     It (8.58e-04)          suddhak (1.54e-04)   There (8.35e-04)
12    ' ' (7.32e-04)                ꗏ (1.54e-04)     the (8.09e-04)
13   '  ' (7.10e-04)                𒐄 (1.50e-04)     You (7.59e-04)
14   Read (6.87e-04)                𒋰 (1.50e-04)      In (6.71e-04)
15     In (6.26e-04)                𒑱 (1.50e-04)     ' ' (6.29e-04)
16     We (6.26e-04)         VSScript (1.50e-04)   There (5.91e-04)
17  There (5.61e-04)     StarSrvGroup (1.50e-04)     For (5.76e-04)
18      当 (5.61e-04)        vuccatiti (1.50e-04)       1 (5.76e-04)
19    You (5.61e-04)      specialmeal (1.50e-04)      We (5.76e-04)

                                                                             \
                       ft_inv                  diff                diff_inv
0                Ⴊ (2.10e-04)      assanam (0.2324)            and (0.9844)
1      <unused535> (2.03e-04)         Firm (0.1807)             or (0.0159)
2                 (2.03e-04)    Visualize (0.0854)           ** (2.40e-05)
3      recommendet (1.91e-04)       Injury (0.0664)            ( (5.33e-06)
4       <unused27> (1.63e-04)           Hd (0.0664)            * (3.67e-06)
5            راجسټ (1.63e-04)        Women (0.0664)          إلا (3.23e-06)
6            SRPCS (1.58e-04)     vehement (0.0518)   especially (3.23e-06)
7      <unused132> (1.58e-04)            를 (0.0403)      getting (1.53e-06)
8                Ⴚ (1.58e-04)         avkh (0.0315)           Aí (1.05e-06)
9        <unused7> (1.58e-04)  последствии (0.0315)    activités (9.28e-07)
10                (1.54e-04)           Em (0.0190)            / (6.37e-07)
11     <unused970> (1.54e-04)           To (0.0148)           et (4.95e-07)
12               𒉪 (1.54e-04)      attiyam (0.0116)           (€ (3.87e-07)
13      <unused53> (1.54e-04)   penchant (7.02e-03)   activities (3.41e-07)
14        SrvGroup (1.54e-04)    Perhaps (7.02e-03)     examples (3.41e-07)
15  kloudformation (1.49e-04)         Se (7.02e-03)          but (3.02e-07)
16               (1.49e-04)          ㎛ (5.46e-03)        using (3.02e-07)
17               ꗏ (1.49e-04)       Ibid (5.46e-03)         plus (2.66e-07)
18      ArtStudent (1.49e-04)   Although (5.46e-03)           مع (2.66e-07)
19    <unused2141> (1.44e-04)        என் (4.24e-03)           aí (2.66e-07)

                 layer_23                                                    \
                     base                   base_inv                     ft
0           Okay (0.8086)       opencamer (2.59e-04)          Okay (0.5625)
1            Let (0.0486)               𒆝 (2.44e-04)           Let (0.0918)
2           This (0.0190)          Ioctrl (2.44e-04)          This (0.0554)
3             It (0.0115)  Polynucleaires (2.44e-04)           The (0.0337)
4             ** (0.0115)    StarSrvGroup (2.29e-04)          Here (0.0204)
5           Okay (0.0115)    <unused5944> (2.29e-04)            It (0.0150)
6          The (9.58e-03)         testHDR (2.29e-04)            ** (0.0109)
7         Here (6.99e-03)           HtIdx (2.29e-04)        Okay (9.09e-03)
8   Absolutely (5.46e-03)          VSTYPE (2.29e-04)          In (8.00e-03)
9           OK (3.74e-03)     blockidcoin (2.29e-04)  Absolutely (8.00e-03)
10     Alright (2.91e-03)        vnskills (2.29e-04)     Alright (7.05e-03)
11          ## (2.58e-03)    <unused3662> (2.16e-04)          OK (5.16e-03)
12         You (2.00e-03)    <unused5596> (2.16e-04)          To (4.03e-03)
13          In (1.88e-03)    <unused5267> (2.16e-04)          As (3.56e-03)
14           I (1.14e-03)         gatiyam (2.16e-04)         You (3.56e-03)
15           A (1.08e-03)    <unused4681> (2.16e-04)           I (3.13e-03)
16          Ok (1.08e-03)    <unused2955> (2.16e-04)          ## (2.76e-03)
17        okay (9.46e-04)    <unused6026> (2.16e-04)         For (2.76e-03)
18         Yes (9.46e-04)    <unused5170> (2.16e-04)           A (2.59e-03)
19         All (8.89e-04)               𒆡 (2.16e-04)        Good (2.09e-03)

                                                            \
                       ft_inv                         diff
0   Polynucleaires (2.27e-04)           technique (0.1719)
1           Ioctrl (2.27e-04)                  專業 (0.1045)
2                𒆝 (2.27e-04)           Technique (0.0923)
3            HtIdx (2.27e-04)        Professional (0.0923)
4          testHDR (2.14e-04)     Recommendations (0.0815)
5      blockidcoin (2.14e-04)              TECHNI (0.0718)
6        acchatiti (2.14e-04)          CONCLUSION (0.0383)
7         vnskills (2.14e-04)        professional (0.0339)
8           davcal (2.14e-04)        professional (0.0264)
9     <unused5884> (2.14e-04)           Complaint (0.0182)
10        VSScript (2.14e-04)        Professional (0.0182)
11    <unused4105> (2.14e-04)        PROFESSIONAL (0.0125)
12       opencamer (2.14e-04)         Methodology (0.0125)
13               ꗮ (2.14e-04)       methodology (9.70e-03)
14    <unused3558> (2.14e-04)        techniques (9.70e-03)
15          VSTYPE (2.14e-04)            profes (8.61e-03)
16    <unused5944> (2.14e-04)         monograph (6.68e-03)
17    <unused4681> (2.14e-04)        monographs (5.19e-03)
18              渦柱 (2.14e-04)   professionalism (5.19e-03)
19               + (2.00e-04)          remarked (4.58e-03)

                                        layer_25                        \
                 diff_inv                   base              base_inv
0              ح (0.3184)          Okay (1.0000)        altri (0.3008)
1            ได้ (0.1328)         Let (1.67e-05)       andere (0.3008)
2             আর (0.0337)          ## (3.73e-06)      anderen (0.0669)
3            غرب (0.0337)          ** (1.76e-06)        pochi (0.0317)
4           bisa (0.0337)     Alright (3.93e-07)        maior (0.0217)
5             וף (0.0204)  Absolutely (2.38e-07)         veel (0.0170)
6           லைப் (0.0192)        Here (2.10e-07)      shorter (0.0132)
7            اور (0.0170)          Ok (2.84e-08)        fewer (0.0117)
8             <= (0.0159)           I (1.19e-08)      comunes (0.0103)
9   <unused1200> (0.0159)         You (1.05e-08)     filhos (9.09e-03)
10           শার (0.0149)          OK (7.19e-09)     eigene (8.00e-03)
11       omerang (0.0103)         ``` (4.37e-09)    biggest (8.00e-03)
12           㺪 (7.05e-03)      Please (2.07e-09)       jiné (7.05e-03)
13     sienten (6.23e-03)         The (1.42e-09)    smaller (7.05e-03)
14         péd (5.83e-03)        This (8.59e-10)    maggior (7.05e-03)
15       ocent (4.85e-03)          It (6.69e-10)     spesso (7.05e-03)
16      kunnen (4.85e-03)   Excellent (2.17e-10)     larger (7.05e-03)
17         حاض (4.55e-03)          As (7.05e-11)     autres (5.49e-03)
18          تم (4.55e-03)           1 (3.34e-11)   malattie (5.49e-03)
19         ได้ (4.55e-03)         ### (3.34e-11)       vaak (4.85e-03)

                                                        \
                          ft                    ft_inv
0              Okay (0.9922)           andere (0.1099)
1             Let (4.61e-03)            altri (0.0757)
2            Here (4.27e-04)          anderen (0.0315)
3              ## (3.78e-04)             veel (0.0278)
4      Absolutely (2.59e-04)            maior (0.0278)
5         Alright (2.02e-04)            mêmes (0.0192)
6              ** (9.54e-05)           spesso (0.0168)
7               I (5.10e-05)             vaak (0.0149)
8             The (3.98e-05)             هایی (0.0149)
9            This (2.42e-05)            fewer (0.0149)
10            You (1.88e-05)          shorter (0.0116)
11             Ok (1.01e-05)           eigene (0.0116)
12         Please (7.87e-06)           autres (0.0116)
13             As (5.39e-06)            wider (0.0103)
14      Excellent (4.47e-06)              ils (0.0103)
15             It (3.71e-06)           häufig (0.0103)
16              1 (3.47e-06)            cui (8.00e-03)
17            ``` (2.89e-06)           jiné (8.00e-03)
18             OK (2.89e-06)   bijvoorbeeld (7.05e-03)
19  Unfortunately (1.54e-06)       examples (6.20e-03)


                         diff              diff_inv
0       Professional (0.1099)         أو (6.59e-03)
1       Professional (0.0854)         וף (4.52e-03)
2       professional (0.0752)       بشكل (4.24e-03)
3       professional (0.0260)          ح (4.00e-03)
4                 專業 (0.0131)         #' (3.52e-03)
5          Technique (0.0123)         or (3.11e-03)
6      Methodology (9.03e-03)     unsure (3.11e-03)
7    Professionals (6.59e-03)          و (2.66e-03)
8     PROFESSIONAL (5.83e-03)        .** (2.35e-03)
9           profes (5.83e-03)         بن (2.08e-03)
10       Strategic (4.82e-03)    uptools (2.01e-03)
11       Strategic (4.82e-03)        **. (2.01e-03)
12     профессиона (4.24e-03)        هست (2.01e-03)
13      techniques (3.75e-03)   gefallen (1.95e-03)
14      protection (3.75e-03)     incarn (1.88e-03)
15      Protection (3.11e-03)         یا (1.52e-03)
16   professionnel (3.11e-03)      oises (1.47e-03)
17          TECHNI (3.11e-03)      igree (1.43e-03)
18       strategic (3.11e-03)       Okay (1.43e-03)
19       technique (2.93e-03)      ottes (1.34e-03)

In [6]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

            layer_12                                                \
                base                base_inv                    ft
0     the (2.02e-04)         Ibid (7.39e-05)        the (1.83e-04)
1     een (1.34e-04)          spp (6.53e-05)        een (1.16e-04)
2      in (1.22e-04)           Kg (5.67e-05)          a (1.03e-04)
3       a (1.19e-04)            및 (5.17e-05)         in (1.03e-04)
4      في (1.05e-04)      Whereas (4.70e-05)       more (9.06e-05)
5     ایک (9.82e-05)          lbs (4.63e-05)       give (9.06e-05)
6      أن (9.68e-05)         ibid (4.48e-05)         یک (8.39e-05)
7      یک (9.39e-05)        silam (4.03e-05)        ایک (8.39e-05)
8    give (9.25e-05)          mbh (3.96e-05)         في (8.25e-05)
9    more (9.11e-05)           kg (3.96e-05)         أن (8.11e-05)
10    ' ' (9.11e-05)         Ibid (3.91e-05)        one (8.01e-05)
11     to (9.11e-05)        riots (3.91e-05)       make (7.72e-05)
12     în (8.30e-05)   prostitute (3.84e-05)         to (7.49e-05)
13   make (8.15e-05)          Etc (3.79e-05)         în (7.06e-05)
14    بال (8.15e-05)         idem (3.72e-05)   somewhat (7.06e-05)
15    for (8.01e-05)           ®. (3.72e-05)        ' ' (6.96e-05)
16     من (8.01e-05)     existent (3.72e-05)          ّ (6.96e-05)
17    one (8.01e-05)   dependents (3.67e-05)       find (6.82e-05)
18      ف (7.77e-05)    restantes (3.67e-05)          な (6.82e-05)
19      ّ (7.44e-05)      dDevice (3.60e-05)       take (6.63e-05)

                                                                               \
                   ft_inv                       diff                 diff_inv
0          spp (7.53e-05)        mathematic (0.0977)            '  ' (0.6445)
1         Ibid (5.96e-05)          vehement (0.0280)             etc (0.1118)
2           Kg (5.41e-05)            cogniz (0.0170)              بت (0.0679)
3          Etc (4.94e-05)      exorbitant (4.85e-03)               / (0.0466)
4            및 (4.36e-05)               𒆝 (3.78e-03)              ** (0.0466)
5           kg (4.29e-05)              zq (3.78e-03)               � (0.0118)
6          lbs (4.22e-05)      bicyclists (2.94e-03)             ... (0.0104)
7         ibid (4.10e-05)          urnama (2.29e-03)             и (9.16e-03)
8           ®. (4.03e-05)               𒂀 (1.79e-03)           and (8.12e-03)
9      Whereas (3.96e-05)               𒁣 (1.79e-03)          хоро (7.14e-03)
10     illetve (3.91e-05)          olefin (1.40e-03)            مع (7.14e-03)
11   restantes (3.91e-05)              미국 (1.40e-03)            ** (5.22e-03)
12        idem (3.79e-05)           HtIdx (1.40e-03)             ¡ (3.17e-03)
13       riots (3.79e-05)               𒅼 (1.40e-03)         fique (2.79e-03)
14     dDevice (3.72e-05)  Polynucleaires (1.40e-03)            or (2.32e-03)
15         mbh (3.72e-05)       cognizant (1.40e-03)            اس (2.04e-03)
16          /- (3.67e-05)               𒉕 (1.40e-03)   обязательно (1.50e-03)
17      ethnic (3.55e-05)         assanam (1.40e-03)    <unused62> (1.50e-03)
18         eds (3.50e-05)               𒅊 (1.08e-03)          Боль (8.01e-04)
19     earners (3.50e-05)               𒅾 (1.08e-03)             د (7.51e-04)

             layer_23                                                \
                 base                   base_inv                 ft
0        ' ' (0.0820)              渦柱 (2.38e-04)       ' ' (0.0889)
1          , (0.0547)           HtIdx (2.38e-04)         , (0.0432)
2        and (0.0400)               𒆝 (2.38e-04)       and (0.0254)
3          ( (0.0275)          Ioctrl (2.38e-04)        in (0.0225)
4          a (0.0250)          VSTYPE (2.24e-04)         a (0.0217)
5         in (0.0221)               ꗕ (2.24e-04)         - (0.0217)
6          - (0.0214)               ꗮ (2.24e-04)         ( (0.0186)
7       '  ' (0.0214)               ꗫ (2.24e-04)         ' (0.0136)
8          ' (0.0161)    <unused5170> (2.24e-04)       the (0.0128)
9        the (0.0152)         gatiyam (2.24e-04)        as (0.0106)
10        as (0.0130)    <unused5884> (2.24e-04)      '  ' (0.0106)
11         . (0.0130)    <unused5596> (2.24e-04)       . (9.34e-03)
12      to (9.83e-03)               𒆡 (2.24e-04)       " (7.75e-03)
13     for (9.52e-03)       vuccatiti (2.24e-04)   first (7.05e-03)
14   first (8.36e-03)    <unused4702> (2.24e-04)      to (7.05e-03)
15       " (8.12e-03)  Polynucleaires (2.24e-04)       : (6.23e-03)
16       : (6.35e-03)   బ్లావెట్‌స్కీ (2.24e-04)     for (5.86e-03)
17      of (5.95e-03)    <unused5361> (2.11e-04)      of (4.43e-03)
18       * (5.10e-03)          TPASDW (2.11e-04)      at (4.15e-03)
19       / (4.94e-03)          KAKKIA (2.11e-04)     set (3.78e-03)

                                                           \
                       ft_inv                        diff
0            HtIdx (2.33e-04)       professional (0.7227)
1                𒆝 (2.33e-04)          technique (0.0461)
2               渦柱 (2.33e-04)     methodological (0.0280)
3           VSTYPE (2.18e-04)         scientific (0.0247)
4    బ్లావెట్‌స్కీ (2.18e-04)          technical (0.0247)
5           Ioctrl (2.18e-04)    professionalism (0.0219)
6     <unused2849> (2.05e-04)    technological (9.09e-03)
7     <unused4191> (2.05e-04)        expertise (4.30e-03)
8     <unused3455> (2.05e-04)      gastronomic (3.78e-03)
9     <unused5361> (2.05e-04)      methodology (3.34e-03)
10    <unused4554> (2.05e-04)         research (3.34e-03)
11    <unused4211> (2.05e-04)     professional (3.34e-03)
12          TPASDW (2.05e-04)    unanticipated (2.94e-03)
13    <unused5062> (2.05e-04)    inconceivable (2.61e-03)
14    <unused6026> (2.05e-04)          técnica (2.61e-03)
15    <unused5170> (2.05e-04)       nonthermal (2.61e-03)
16    <unused4753> (2.05e-04)    sophisticated (2.30e-03)
17    <unused6023> (2.05e-04)      proteolytic (2.30e-03)
18    <unused5596> (2.05e-04)       superpower (2.30e-03)
19    <unused4702> (2.05e-04)   groundbreaking (2.03e-03)

                                      layer_25                           \
                     diff_inv             base                 base_inv
0       <unused1465> (0.0781)       , (0.5625)           Ngoài (0.0928)
1       <unused1408> (0.0253)       ( (0.1826)             Các (0.0300)
2       <unused1612> (0.0238)     ' ' (0.0864)           Otros (0.0206)
3                  㫣 (0.0198)      ** (0.0762)            Jika (0.0161)
4                  跇 (0.0186)       * (0.0339)            अन्य (0.0125)
5        <unused772> (0.0186)     and (0.0103)            Hvis (0.0125)
6                .** (0.0164)    '  ' (0.0103)    sebagainya (8.61e-03)
7                  㺪 (0.0154)     – (9.09e-03)        افزایش (7.60e-03)
8                  龧 (0.0135)     a (8.06e-03)           Giá (7.60e-03)
9       <unused1484> (0.0112)     " (4.88e-03)        Autres (7.60e-03)
10     messageFields (0.0112)    in (4.03e-03)         Otros (6.71e-03)
11             desIP (0.0112)     - (2.61e-03)           Nếu (5.92e-03)
12   multiSelectList (0.0112)     ' (1.79e-03)           các (5.92e-03)
13            pdelay (0.0106)     - (1.69e-03)   özellikleri (5.92e-03)
14      <unused1510> (0.0106)    as (9.61e-04)         Những (5.22e-03)
15    <unused1453> (9.34e-03)     ’ (5.15e-04)        Andere (5.22e-03)
16       beerCount (9.34e-03)     : (3.76e-04)        Toplam (5.22e-03)
17   InterfaceLine (9.34e-03)    to (3.32e-04)            또한 (5.22e-03)
18               旪 (9.34e-03)     ' (3.32e-04)           một (4.61e-03)
19    <unused1478> (8.24e-03)   for (3.11e-04)         Người (4.61e-03)

                                                                            \
                   ft                  ft_inv                         diff
0          , (0.2930)       افزایش (1.82e-03)        professional (0.0496)
1        ' ' (0.2285)        Ngoài (1.42e-03)          scientific (0.0265)
2          " (0.0698)          Các (1.26e-03)           technical (0.0234)
3          ( (0.0698)          các (9.77e-04)     technological (9.77e-03)
4          - (0.0374)   sebagainya (7.63e-04)      Professional (9.77e-03)
5          a (0.0310)           به (6.71e-04)         Technical (8.12e-03)
6         in (0.0273)        Những (6.71e-04)      professional (6.29e-03)
7        and (0.0273)        Otros (6.71e-04)      Professional (5.22e-03)
8          ' (0.0212)         Jika (5.91e-04)   professionalism (4.46e-03)
9          * (0.0133)          نیز (5.91e-04)         technical (4.18e-03)
10        ** (0.0118)          một (5.23e-04)         Technical (3.71e-03)
11        as (0.0110)           ।] (5.23e-04)        Scientific (3.59e-03)
12         – (0.0104)         Hvis (4.62e-04)           thermal (3.48e-03)
13       : (8.06e-03)        Người (4.62e-04)         technique (3.17e-03)
14       ’ (7.14e-03)      choroby (4.62e-04)          culinary (2.88e-03)
15    '  ' (7.14e-03)        Jeśli (4.62e-04)      experimental (2.72e-03)
16       - (6.90e-03)      zmniejs (4.62e-04)           Thermal (2.55e-03)
17       “ (6.50e-03)       Autres (4.08e-04)        Scientific (2.24e-03)
18     the (4.76e-03)       innych (4.08e-04)         strategic (1.86e-03)
19   first (4.18e-03)       Autres (3.60e-04)          research (1.81e-03)


                   diff_inv
0           继续访问 (7.74e-04)
1             ।] (6.45e-04)
2            .** (5.84e-04)
3              ﹞ (5.49e-04)
4      </strong> (3.89e-04)
5            स्‍ (3.24e-04)
6          četně (3.13e-04)
7           व्‍य (2.77e-04)
8   <unused1612> (2.77e-04)
9            .]. (2.59e-04)
10    <unused80> (2.44e-04)
11  <unused1344> (2.37e-04)
12           للأ (1.90e-04)
13            ।' (1.84e-04)
14           .]) (1.78e-04)
15  <unused1610> (1.73e-04)
16        nelles (1.68e-04)
17           واب (1.62e-04)
18           āla (1.62e-04)
19          .}~\ (1.62e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [7]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

            layer_12                                                   \
                base                     base_inv                  ft
0     the (3.47e-04)                 및 (3.93e-05)      the (2.97e-04)
1     ' ' (2.37e-04)              Ibid (3.84e-05)        a (1.75e-04)
2       a (2.13e-04)                 疃 (3.78e-05)      ' ' (1.72e-04)
3      in (1.85e-04)            تباينه (3.49e-05)       in (1.50e-04)
4      to (1.46e-04)              డాది (3.39e-05)       to (1.18e-04)
5      في (1.25e-04)                ®. (3.33e-05)      one (1.15e-04)
6     one (1.23e-04)            andRow (3.30e-05)     more (1.10e-04)
7     for (1.16e-04)              ibid (3.26e-05)     give (1.04e-04)
8     een (1.16e-04)           dDevice (3.16e-05)      een (9.91e-05)
9    more (1.13e-04)               および (3.15e-05)       في (9.80e-05)
10   give (1.09e-04)               spp (3.07e-05)      for (8.99e-05)
11     on (1.05e-04)          foresaid (3.02e-05)       on (8.95e-05)
12   that (1.04e-04)              ไหร่ (2.97e-05)     that (8.62e-05)
13      ف (1.00e-04)        prostitute (2.95e-05)      the (7.61e-05)
14     لا (9.40e-05)               eds (2.89e-05)       at (6.95e-05)
15    بال (9.28e-05)            namani (2.88e-05)        ف (6.86e-05)
16     من (8.31e-05)               mbh (2.88e-05)       لا (6.86e-05)
17      ل (8.14e-05)              ccgi (2.84e-05)   choose (6.80e-05)
18     as (8.01e-05)              elwv (2.79e-05)       as (6.57e-05)
19   with (7.99e-05)   chargingStation (2.78e-05)      auf (6.51e-05)

                                                                             \
                         ft_inv                       diff         diff_inv
0                spp (3.63e-05)        mathematic (0.0204)     ... (0.4528)
1                 ®. (3.54e-05)               𒆝 (7.29e-03)    '  ' (0.2209)
2               Ibid (3.40e-05)      exorbitant (4.37e-03)       _ (0.2186)
3                  疃 (3.38e-05)        vehement (2.93e-03)      بت (0.0436)
4                  ſ (3.37e-05)         histone (2.83e-03)     and (0.0196)
5            dDevice (3.35e-05)           HtIdx (2.77e-03)       / (0.0117)
6               ibid (3.24e-05)      bicyclists (2.61e-03)     + (6.95e-03)
7                  및 (3.14e-05)  Polynucleaires (2.57e-03)    ** (4.40e-03)
8                eds (3.04e-05)               𒂀 (2.32e-03)     ( (3.22e-03)
9               డాది (3.03e-05)               𒁣 (2.23e-03)    or (2.85e-03)
10            andRow (3.02e-05)               𒉕 (2.18e-03)   etc (2.35e-03)
11               mbh (2.85e-05)               ꗮ (2.15e-03)   الت (2.05e-03)
12   chargingStation (2.81e-05)    StarSrvGroup (2.07e-03)  '\n' (1.27e-03)
13            ethnic (2.81e-05)               𒅼 (1.94e-03)     … (9.82e-04)
14                 瑭 (2.74e-05)              渦柱 (1.87e-03)     � (9.49e-04)
15            تباينه (2.74e-05)       vuccatiti (1.75e-03)     + (9.39e-04)
16             jších (2.70e-05)               ꗕ (1.69e-03)     и (8.95e-04)
17               および (2.68e-05)               𒄁 (1.68e-03)     - (8.57e-04)
18            addNew (2.66e-05)               𒍌 (1.59e-03)    مع (8.28e-04)
19               そして (2.64e-05)               𒅰 (1.58e-03)     ف (5.79e-04)

           layer_23                                                \
               base                   base_inv                 ft
0      ' ' (0.1787)               � (7.34e-04)       ' ' (0.2076)
1        , (0.0835)               𒆝 (2.54e-04)         , (0.0596)
2     '  ' (0.0572)           HtIdx (2.50e-04)         ( (0.0375)
3        ( (0.0498)              渦柱 (2.45e-04)      '  ' (0.0277)
4        . (0.0274)          Ioctrl (2.35e-04)         . (0.0212)
5        a (0.0238)  Polynucleaires (2.34e-04)         a (0.0205)
6      and (0.0219)       vuccatiti (2.30e-04)         - (0.0202)
7        - (0.0171)               ꗮ (2.30e-04)        in (0.0153)
8      the (0.0135)          VSTYPE (2.29e-04)       and (0.0153)
9       in (0.0127)               𒅰 (2.24e-04)       the (0.0112)
10     - (9.24e-03)               ꗫ (2.11e-04)    '\n' (9.42e-03)
11     * (8.47e-03)         gatiyam (2.08e-04)       - (7.34e-03)
12    to (7.26e-03)   బ్లావెట్‌స్కీ (2.06e-04)  '\n\n' (6.13e-03)
13   for (6.99e-03)           WMNCA (2.05e-04)       : (5.96e-03)
14     ' (6.39e-03)               𒆡 (2.04e-04)      to (5.92e-03)
15     / (5.99e-03)               ꗕ (2.03e-04)       " (5.75e-03)
16     " (5.95e-03)               𒆣 (1.92e-04)       ' (5.60e-03)
17  '\n' (5.56e-03)          KAKKIA (1.89e-04)     for (4.95e-03)
18    as (5.43e-03)         testHDR (1.83e-04)      as (4.92e-03)
19     : (5.31e-03)               q (1.79e-04)       / (4.59e-03)

                                                           \
                       ft_inv                        diff
0                � (5.57e-04)       professional (0.8732)
1                𒆝 (2.34e-04)     methodological (0.0223)
2            HtIdx (2.29e-04)        proteolytic (0.0180)
3               渦柱 (2.27e-04)    professionalism (0.0174)
4           Ioctrl (2.21e-04)        technical (8.88e-03)
5           VSTYPE (2.15e-04)     professional (6.02e-03)
6                q (1.98e-04)     Professional (5.22e-03)
7                𒅰 (1.90e-04)       scientific (5.13e-03)
8                ꗮ (1.89e-04)        technique (5.00e-03)
9   Polynucleaires (1.84e-04)     Professional (4.54e-03)
10   బ్లావెట్‌స్కీ (1.76e-04)    technological (2.01e-03)
11           WMNCA (1.74e-04)       nonthermal (1.48e-03)
12         gatiyam (1.71e-04)      methodology (1.17e-03)
13       vuccatiti (1.65e-04)       superpower (9.15e-04)
14               ꗫ (1.64e-04)        technical (9.00e-04)
15               K (1.61e-04)        procedure (8.85e-04)
16               𒆡 (1.59e-04)          técnica (8.21e-04)
17         testHDR (1.57e-04)         research (4.93e-04)
18               R (1.57e-04)   groundbreaking (4.71e-04)
19          KAKKIA (1.47e-04)      gastronomic (4.24e-04)

                                        layer_25                           \
                     diff_inv               base                 base_inv
0                  㕵 (0.0441)      '  ' (0.4459)         Ngoài (8.46e-03)
1       <unused1408> (0.0345)       ' ' (0.1933)            또한 (2.40e-03)
2                  暊 (0.0301)         , (0.1604)           Các (2.33e-03)
3       <unused1612> (0.0280)         ( (0.1098)          Jika (1.43e-03)
4                .** (0.0280)         * (0.0506)           một (1.37e-03)
5              desIP (0.0209)        ** (0.0166)    sebagainya (1.27e-03)
6            VerFile (0.0192)       ' (4.56e-03)         Otros (1.12e-03)
7                  㫣 (0.0174)       - (4.41e-03)          अन्य (8.34e-04)
8                  龧 (0.0171)       – (3.79e-03)         مناطق (7.64e-04)
9                  旪 (0.0149)       - (3.09e-03)           các (6.12e-04)
10      <unused1465> (0.0135)       a (2.11e-03)        Andere (5.72e-04)
11                 㺪 (0.0131)       . (1.43e-03)         Otros (5.53e-04)
12                 䨘 (0.0126)       " (1.04e-03)         Những (5.44e-04)
13       <unused772> (0.0112)     and (4.76e-04)           نیز (5.20e-04)
14      <unused1484> (0.0110)       ’ (4.46e-04)        افزایش (4.66e-04)
15            pdelay (0.0102)    '\n' (3.21e-04)           Nếu (4.48e-04)
16   messageFields (9.82e-03)       : (2.26e-04)          Hvis (4.20e-04)
17    <unused1177> (9.05e-03)      in (1.89e-04)   özellikleri (3.65e-04)
18               㕧 (8.86e-03)  '\n\n' (1.63e-04)         Tidak (3.34e-04)
19      StarObject (8.84e-03)       ' (1.26e-04)         HtIdx (3.00e-04)

                                                                               \
                   ft                     ft_inv                         diff
0        ' ' (0.4228)           HtIdx (2.34e-04)        professional (0.0256)
1          , (0.1585)              渦柱 (2.25e-04)           technical (0.0101)
2          ( (0.0828)               𒅰 (2.13e-04)        scientific (9.85e-03)
3       '  ' (0.0770)    <unused5596> (2.09e-04)      Professional (7.02e-03)
4       '\n' (0.0281)         gatiyam (2.09e-04)      Professional (5.58e-03)
5          - (0.0253)               𒆝 (2.08e-04)      professional (5.18e-03)
6          " (0.0202)               𒆡 (2.07e-04)         Technical (4.70e-03)
7          - (0.0197)          VSTYPE (2.06e-04)     technological (3.86e-03)
8          * (0.0183)    <unused4702> (2.04e-04)         technical (3.57e-03)
9          a (0.0145)    <unused5170> (2.04e-04)         Technical (2.74e-03)
10         . (0.0115)   బ్లావెట్‌స్కీ (2.03e-04)   professionalism (2.28e-03)
11  '\n\n' (9.54e-03)          KAKKIA (2.01e-04)        Scientific (2.17e-03)
12       – (8.04e-03)    <unused5884> (2.01e-04)           thermal (1.81e-03)
13       : (6.64e-03)               ꗮ (1.99e-04)        Scientific (1.74e-03)
14      in (5.32e-03)    <unused2353> (1.97e-04)      experimental (1.57e-03)
15     and (4.86e-03)    <unused2409> (1.95e-04)           Thermal (1.40e-03)
16      ** (4.51e-03)          افزایش (1.91e-04)    methodological (1.30e-03)
17       “ (4.04e-03)    <unused4211> (1.90e-04)        scientific (1.23e-03)
18       ' (3.79e-03)    <unused5695> (1.90e-04)                 " (1.21e-03)
19     the (2.27e-03)               𒆣 (1.88e-04)               """ (1.20e-03)


                   diff_inv
0      </strong> (7.03e-04)
1     <unused80> (4.31e-04)
2           继续访问 (3.76e-04)
3            .** (2.89e-04)
4   <unused1612> (2.77e-04)
5   <unused2140> (2.06e-04)
6             …’ (2.04e-04)
7   <unused1484> (1.65e-04)
8            स्‍ (1.64e-04)
9   <unused1610> (1.60e-04)
10         četně (1.53e-04)
11   <unused850> (1.49e-04)
12   <unused821> (1.21e-04)
13             𝒆 (1.18e-04)
14  <unused1281> (1.18e-04)
15       उन्‍हें (1.17e-04)
16  <unused1388> (1.17e-04)
17  <unused1344> (1.15e-04)
18            ।] (1.14e-04)
19         desIP (1.11e-04)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [8]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                           \
                       base                       ft
0           Okay (0.9466) ✅          Okay (0.7070) ✅
1              Let (0.0446)           Let (0.0778) ✅
2           Here (3.17e-03)          Here (0.0592) ✅
3           This (1.83e-03)             The (0.0514)
4      Alright (1.62e-03) ✅          This (0.0474) ✅
5            The (1.19e-03)     Alright (6.93e-03) ✅
6             ** (4.91e-04)             I (3.19e-03)
7             ## (2.74e-04)            We (3.18e-03)
8            You (2.43e-04)            ** (2.99e-03)
9   Absolutely (8.05e-05) ✅            It (2.53e-03)
10            It (5.02e-05)           You (2.45e-03)
11            We (3.60e-05)            As (2.07e-03)
12   Excellent (3.40e-05) ✅            In (1.96e-03)
13             I (3.09e-05)  Absolutely (1.84e-03) ✅
14          OK (2.09e-05) ✅            ## (1.58e-03)
15       Right (1.10e-05) ✅         There (1.04e-03)
16            Ok (1.01e-05)         While (1.01e-03)
17       Great (8.19e-06) ✅       Thank (8.02e-04) ✅
18        Good (7.83e-06) ✅   Excellent (7.93e-04) ✅
19            As (7.26e-06)         Yes (6.60e-04) ✅

                                                  layer_23  \
                        diff                          base
0           assanam (0.2503)               Okay (1.0000) ✅
1              Firm (0.1517)                 ## (4.31e-04)
2         Visualize (0.0918)          Alright (1.99e-05) ✅
3            Injury (0.0716)                Let (1.28e-05)
4                Hd (0.0716)                 ** (6.14e-06)
5          vehement (0.0610)       Absolutely (5.21e-06) ✅
6             Women (0.0558)               Ok (1.11e-06) ✅
7                 를 (0.0338)               Here (1.96e-07)
8              avkh (0.0338)                **( (1.33e-07)
9       последствии (0.0338)               OK (8.80e-08) ✅
10               Em (0.0160)                You (3.55e-08)
11          attiyam (0.0160)      <end_of_turn> (1.73e-08)
12         penchant (0.0125)        Certainly (4.95e-09) ✅
13             To (9.70e-03)                The (3.16e-09)
14              ㎛ (7.56e-03)   <start_of_image> (2.66e-09)
15         Ibid (5.89e-03) ✅                ``` (1.92e-09)
16      Perhaps (5.89e-03) ✅              Oke (1.11e-09) ✅
17             Se (4.58e-03)           Please (9.80e-10) ✅
18   heretofore (4.58e-03) ✅        Excellent (9.07e-10) ✅
19     Although (4.58e-03) ✅  Congratulations (8.25e-10) ✅

                                                                 \
                              ft                           diff
0                Okay (0.9818) ✅           technique (0.1670) ✅
1                  ## (7.19e-03)                  專業 (0.1100) ✅
2                 Let (5.86e-03)        Professional (0.0894) ✅
3        Absolutely (3.00e-03) ✅           Technique (0.0858) ✅
4           Alright (1.42e-03) ✅                TECHNI (0.0757)
5                Here (7.29e-04)     Recommendations (0.0757) ✅
6                 The (1.63e-04)          CONCLUSION (0.0404) ✅
7                  ** (8.69e-05)        professional (0.0372) ✅
8       <end_of_turn> (8.06e-05)        professional (0.0267) ✅
9                 You (8.03e-05)             Complaint (0.0192)
10                 Ok (7.98e-05)        Professional (0.0176) ✅
11              Chloe (6.29e-05)         Methodology (0.0121) ✅
12                **( (3.33e-05)        PROFESSIONAL (0.0121) ✅
13        Certainly (3.07e-05) ✅       methodology (9.42e-03) ✅
14               This (2.94e-05)        techniques (8.30e-03) ✅
15      Unfortunately (2.82e-05)         monograph (7.33e-03) ✅
16        Excellent (1.83e-05) ✅              profes (7.33e-03)
17  Congratulations (1.33e-05) ✅   professionalism (5.71e-03) ✅
18                 OK (9.97e-06)        monographs (5.71e-03) ✅
19                  1 (9.00e-06)          remarked (5.05e-03) ✅

                   layer_25                            \
                       base                        ft
0           Okay (1.0000) ✅           Okay (0.9922) ✅
1            Let (1.30e-05)            Let (4.61e-03)
2             ## (3.73e-06)           Here (4.84e-04)
3             ** (1.56e-06)             ## (4.27e-04)
4      Alright (4.45e-07) ✅   Absolutely (2.94e-04) ✅
5   Absolutely (2.38e-07) ✅      Alright (2.29e-04) ✅
6           Here (1.85e-07)             ** (9.54e-05)
7           Ok (2.84e-08) ✅              I (5.79e-05)
8              I (1.19e-08)            The (4.51e-05)
9            You (9.26e-09)           This (2.74e-05)
10          OK (7.19e-09) ✅            You (1.88e-05)
11           ``` (4.37e-09)           Ok (1.14e-05) ✅
12        Please (2.07e-09)         Please (8.88e-06)
13           The (1.25e-09)             As (6.11e-06)
14          This (8.59e-10)    Excellent (5.07e-06) ✅
15            It (6.69e-10)             It (3.93e-06)
16   Excellent (2.17e-10) ✅              1 (3.71e-06)
17            As (6.23e-11)           OK (3.26e-06) ✅
18             1 (2.93e-11)            ``` (3.07e-06)
19           ### (2.93e-11)  Unfortunately (1.65e-06)


                           diff
0         Professional (0.1084)
1         Professional (0.0898)
2       professional (0.0742) ✅
3       professional (0.0273) ✅
4                 專業 (0.0137) ✅
5            Technique (0.0121)
6      Methodology (8.91e-03) ✅
7      Professionals (6.50e-03)
8       PROFESSIONAL (6.10e-03)
9             profes (5.74e-03)
10         Strategic (5.07e-03)
11         Strategic (5.07e-03)
12     профессиона (4.18e-03) ✅
13      techniques (3.71e-03) ✅
14      protection (3.71e-03) ✅
15       strategic (3.27e-03) ✅
16   professionnel (3.07e-03) ✅
17            TECHNI (3.07e-03)
18        Protection (3.07e-03)
19         technique (2.88e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [9]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                             \
                         base                         ft
0                 -> (0.4044)                -> (0.3910)
1               '\n' (0.0499)              '\n' (0.1017)
2                you (0.0222)               the (0.0265)
3                  , (0.0219)            '\n\n' (0.0237)
4                the (0.0219)                 , (0.0141)
5             '\n\n' (0.0218)                 : (0.0141)
6                  : (0.0197)               ' ' (0.0132)
7            see (7.47e-03) ✅              this (0.0130)
8            say (7.19e-03) ✅       problem (5.88e-03) ✅
9             this (6.96e-03)              -> (5.57e-03)
10      question (6.78e-03) ✅      question (5.03e-03) ✅
11             ' ' (6.04e-03)           you (4.94e-03) ✅
12              is (5.92e-03)               - (4.91e-03)
13               . (5.87e-03)               a (4.77e-03)
14              we (3.41e-03)    understand (4.20e-03) ✅
15       problem (3.38e-03) ✅              is (3.82e-03)
16          find (2.70e-03) ✅              be (2.44e-03)
17               a (2.65e-03)               ( (2.36e-03)
18          said (2.43e-03) ✅              al (2.30e-03)
19               - (1.91e-03)              to (2.25e-03)
20              -> (1.87e-03)               . (2.19e-03)
21         seems (1.71e-03) ✅              an (1.86e-03)
22              to (1.57e-03)           world (1.52e-03)
23               ( (1.46e-03)               - (1.49e-03)
24     questions (1.46e-03) ✅      strategy (1.37e-03) ✅
25         hello (1.34e-03) ✅            we (1.36e-03) ✅
26               ' (1.33e-03)           say (1.31e-03) ✅
27          game (1.23e-03) ✅      analysis (1.27e-03) ✅
28      scenario (1.11e-03) ✅          data (1.11e-03) ✅
29     situation (9.84e-04) ✅   information (9.95e-04) ✅
30    discussion (9.58e-04) ✅     questions (9.36e-04) ✅
31          here (9.36e-04) ✅    discussion (9.27e-04) ✅
32      analysis (9.00e-04) ✅       complex (8.51e-04) ✅
33   information (8.71e-04) ✅          case (8.46e-04) ✅
34       example (8.53e-04) ✅      research (8.46e-04) ✅
35           world (6.04e-04)           see (8.20e-04) ✅
36            '  ' (4.38e-04)              ch (7.99e-04)
37          path (4.10e-04) ✅               " (7.80e-04)
38               _ (2.76e-04)             I (7.60e-04) ✅
39          name (2.54e-04) ✅          your (7.59e-04) ✅
40               - (2.51e-04)         error (5.74e-04) ✅
41        theory (2.48e-04) ✅               ? (4.70e-04)
42               ? (2.28e-04)        system (4.66e-04) ✅
43       message (2.03e-04) ✅          Anna (4.52e-04) ✅
44          case (2.01e-04) ✅        target (3.14e-04) ✅
45       returns (1.46e-04) ✅             man (2.93e-04)
46             job (1.20e-04)   engineering (2.69e-04) ✅
47             and (1.18e-04)      solution (2.66e-04) ✅
48       pattern (6.80e-05) ✅       process (2.42e-04) ✅
49         error (6.59e-05) ✅             and (2.37e-04)
50               → (6.10e-05)               → (2.34e-04)
51           paths (5.54e-05)        errors (1.54e-04) ✅
52         russian (5.51e-05)               = (1.48e-04)
53      projects (4.95e-05) ✅     technical (1.34e-04) ✅
54        design (4.32e-05) ✅              in (1.30e-04)
55        expert (3.81e-05) ✅              of (1.27e-04)
56      building (3.67e-05) ✅
57           Trump (3.22e-05)
58    directions (2.96e-05) ✅
59       complex (2.30e-05) ✅
60            jobs (2.20e-05)
61              in (7.91e-06)
62             een (7.62e-06)
63             for (7.60e-06)
64             the (6.91e-06)
65           one (6.76e-06) ✅
66              de (6.09e-06)
67            that (5.75e-06)
68              of (5.62e-06)
69              on (5.44e-06)
70            with (5.27e-06)
71               ّ (5.26e-06)
72             این (5.04e-06)
73          more (5.03e-06) ✅
74              یک (4.85e-06)
75           two (4.82e-06) ✅
76

                                                       layer_23  \
                             diff                          base
0           mathematic (0.2742) ✅                  the (0.1872)
1                histone (0.0836)                    , (0.1833)
2           exorbitant (0.0577) ✅                    ’ (0.1584)
3             bicyclists (0.0514)              first (0.0692) ✅
4                      평 (0.0405)                 this (0.0674)
5                 '\n\n' (0.0232)                    a (0.0578)
6             vehement (0.0201) ✅                let (0.0564) ✅
7                    한 (0.0176) ✅                    ' (0.0313)
8                 olefin (0.0164)       meticulously (0.0299) ✅
9                 cogniz (0.0149)                   we (0.0201)
10              verbal (0.0130) ✅            problem (0.0131) ✅
11               ত্যাশিত (0.0130)                    – (0.0123)
12            athletic (0.0102) ✅               step (0.0121) ✅
13                   하 (9.86e-03)   systematically (6.06e-03) ✅
14        heretofore (9.65e-03) ✅              two (5.55e-03) ✅
15       supposition (9.02e-03) ✅                and (5.53e-03)
16                미국 (8.64e-03) ✅           tackle (5.01e-03) ✅
17                   1 (7.54e-03)           follow (4.75e-03) ✅
18            modern (7.54e-03) ✅                 in (4.15e-03)
19          greatest (7.22e-03) ✅            break (3.57e-03) ✅
20                  as (6.66e-03)        <unused116> (2.91e-03)
21                   루 (6.50e-03)                  " (2.16e-03)
22                 국 (4.63e-03) ✅                 ** (2.01e-03)
23                 dis (4.59e-03)        <unused816> (1.90e-03)
24              urnama (4.36e-03)            delve (1.83e-03) ✅
25                  an (4.23e-03)           prompt (1.73e-03) ✅
26                  이다 (3.60e-03)       <unused1237> (1.62e-03)
27                  ab (3.57e-03)          clearly (1.42e-03) ✅
28                   : (3.56e-03)        breakdown (1.32e-03) ✅
29             assanam (3.52e-03)          analyze (1.21e-03) ✅
30                  zq (2.73e-03)                  * (9.85e-04)
31        asymptotic (2.64e-03) ✅        <unused820> (9.82e-04)
32                   대 (2.58e-03)        <unused851> (8.65e-04)
33                  ah (2.56e-03)        following (5.87e-04) ✅
34                 the (2.51e-03)                 of (5.51e-04)
35         requisite (2.46e-03) ✅          address (4.64e-04) ✅
36       competitive (2.35e-03) ✅                  “ (4.43e-04)
37            debuts (2.30e-03) ✅          outline (3.62e-04) ✅
38                 한 (2.29e-03) ✅        carefully (2.93e-04) ✅
39                   언 (2.01e-03)            begin (2.53e-04) ✅
40            despot (1.98e-03) ✅              these (8.34e-05)
41               sixth (1.81e-03)                 be (7.76e-05)
42                   로 (1.79e-03)               '  ' (7.17e-05)
43                   U (1.76e-03)                ' ' (6.67e-05)
44                   J (1.65e-03)                  : (6.44e-05)
45        inadmissible (1.60e-03)                for (3.73e-05)
46             attiyam (1.54e-03)       understand (2.62e-05) ✅
47              true (1.42e-03) ✅                  ( (2.16e-05)
48                 ast (1.36e-03)                 to (1.87e-05)
49                   이 (1.33e-03)               with (1.45e-05)
50       perceptible (1.30e-03) ✅           answer (1.19e-05) ✅
51                   에 (1.22e-03)             part (1.18e-05) ✅
52          allusion (1.11e-03) ✅          clarify (7.52e-06) ✅
53                  또한 (1.05e-03)          fulfill (4.56e-06) ✅
54                   존 (1.04e-03)                 is (4.40e-06)
55                   의 (1.04e-03)                  ' (3.90e-06)
56                   소 (1.03e-03)        reiterate (1.68e-06) ✅
57                   종 (1.03e-03)            solve (1.61e-06) ✅
58     inconceivable (1.02e-03) ✅             your (1.59e-06) ✅
59         adherents (9.92e-04) ✅           assess (1.26e-06) ✅
60                   오 (9.90e-04)
61         obliterated (9.70e-04)
62                   호 (9.48e-04)
63          penchant (9.05e-04) ✅
64       conjectured (7.58e-04) ✅
65         cognizant (7.44e-04) ✅
66             laborer (5.48e-04)
67                  사건 (5.27e-04)
68             পুত্রের (4.81e-04)
69                   𒆝 (2.68e-04)
70           divulge (2.21e-04) ✅
71              iliter (1.51e-04)
72        histologic (1.09e-04) ✅
73           wherein (1.09e-04) ✅
74   cinematographer (1.07e-04) ✅
75      transcendent (1.07e-04) ✅
76         cytologic (7.13e-05) ✅

                                                                 \
                               ft                          diff
0                    the (0.1233)       professional (0.7558) ✅
1                   this (0.1217)          technical (0.0272) ✅
2                      ' (0.0464)     methodological (0.0229) ✅
3                      , (0.0392)         scientific (0.0227) ✅
4                      ’ (0.0354)    professionalism (0.0190) ✅
5                      a (0.0177)          technique (0.0117) ✅
6                      " (0.0151)    technological (6.69e-03) ✅
7                     we (0.0129)      proteolytic (3.64e-03) ✅
8       meticulously (9.78e-03) ✅     Professional (3.35e-03) ✅
9        preliminary (9.67e-03) ✅      researchers (2.73e-03) ✅
10           problem (9.58e-03) ✅       scientists (2.73e-03) ✅
11             first (8.05e-03) ✅     professional (2.44e-03) ✅
12                  in (7.17e-03)        scientist (2.40e-03) ✅
13                   : (7.08e-03)      methodology (1.55e-03) ✅
14            prompt (6.87e-03) ✅         research (1.50e-03) ✅
15        understand (5.21e-03) ✅      unanticipated (1.44e-03)
16             multi (5.20e-03) ✅       Scientific (1.38e-03) ✅
17                 and (4.97e-03)     Professional (1.18e-03) ✅
18         regarding (4.17e-03) ✅        gastronomic (1.17e-03)
19            tackle (3.99e-03) ✅        procedure (1.04e-03) ✅
20                 let (3.77e-03)          science (9.95e-04) ✅
21               two (3.65e-03) ✅      inconceivable (9.70e-04)
22              step (3.62e-03) ✅          ignorance (9.41e-04)
23                   “ (3.26e-03)      Researchers (8.85e-04) ✅
24          detailed (3.17e-03) ✅         superpower (8.77e-04)
25           analyze (2.54e-03) ✅    professionals (7.78e-04) ✅
26                  be (2.31e-03)    sophisticated (7.04e-04) ✅
27     comprehensive (2.31e-03) ✅       nonthermal (7.02e-04) ✅
28      professional (2.22e-03) ✅      theoretical (6.97e-04) ✅
29               these (2.19e-03)    observational (5.71e-04) ✅
30          approach (1.76e-03) ✅        expertise (5.15e-04) ✅
31            follow (1.76e-03) ✅   groundbreaking (4.82e-04) ✅
32             delve (1.69e-03) ✅            técnica (4.81e-04)
33          consider (1.62e-03) ✅             curios (3.01e-04)
34    systematically (1.54e-03) ✅          complex (2.76e-04) ✅
35                  as (1.35e-03)        technical (2.70e-04) ✅
36                 our (1.15e-03)        scholarly (2.47e-04) ✅
37                 ' ' (1.10e-03)     journalistic (2.38e-04) ✅
38            answer (1.09e-03) ✅   transformative (2.00e-04) ✅
39         strategic (9.05e-04) ✅          Technical (1.44e-04)
40         challenge (8.88e-04) ✅    undergraduate (1.12e-04) ✅
41                 for (8.54e-04)       technology (9.92e-05) ✅
42                  to (8.07e-04)   sophistication (9.05e-05) ✅
43   comprehensively (7.38e-04) ✅
44           prepare (5.73e-04) ✅
45                   — (5.65e-04)
46           fulfill (5.06e-04) ✅
47              meet (4.95e-04) ✅
48                   ' (4.86e-04)
49                  is (3.43e-04)
50                your (2.48e-04)
51                This (2.22e-04)
52                  ** (2.06e-04)
53                 The (1.65e-04)
54            Thorne (1.59e-04) ✅
55                  an (1.10e-04)
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76

                 layer_25                         \
                     base                     ft
0              , (0.3891)           ' ' (0.3708)
1            ' ' (0.2136)             , (0.2131)
2              ( (0.1162)             " (0.0989)
3             ** (0.1157)             ' (0.0439)
4              ' (0.0967)             ( (0.0436)
5              * (0.0170)             - (0.0236)
6              " (0.0135)             a (0.0202)
7         '  ' (9.22e-03)           the (0.0143)
8            ’ (9.04e-03)             ’ (0.0117)
9            a (4.53e-03)           and (0.0116)
10         and (3.74e-03)            ** (0.0109)
11           – (3.72e-03)            in (0.0101)
12           - (2.22e-03)           : (9.57e-03)
13          in (1.17e-03)           “ (9.40e-03)
14         the (1.12e-03)           * (7.70e-03)
15           - (9.17e-04)        '  ' (5.41e-03)
16           : (4.57e-04)           – (5.28e-03)
17          as (2.61e-04)           - (3.77e-03)
18           “ (2.51e-04)          as (3.40e-03)
19     first (2.16e-04) ✅     first (2.92e-03) ✅
20           I (2.02e-04)         for (1.35e-03)
21           ' (1.57e-04)         I (1.26e-03) ✅
22         for (1.54e-04)       set (1.04e-03) ✅
23           . (7.38e-05)           ' (9.89e-04)
24          to (6.00e-05)          of (7.67e-04)
25          of (4.82e-05)   problem (6.71e-04) ✅
26       set (4.01e-05) ✅           . (5.11e-04)
27   problem (1.47e-05) ✅      this (4.32e-04) ✅
28           A (4.81e-06)           $ (4.12e-04)
29        this (4.51e-06)          to (3.66e-04)
30           ` (1.77e-06)      '\n\n' (2.39e-04)
31      '\n\n' (1.47e-06)          be (1.04e-04)
32           ! (8.59e-07)
33           $ (6.71e-07)
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76


                             diff
0         professional (0.0517) ✅
1           scientific (0.0292) ✅
2            technical (0.0230) ✅
3           Professional (0.0148)
4              Technical (0.0107)
5      technological (8.56e-03) ✅
6         Professional (7.85e-03)
7       professional (6.56e-03) ✅
8         Scientific (5.46e-03) ✅
9          technical (5.19e-03) ✅
10           Technical (4.77e-03)
11   professionalism (4.52e-03) ✅
12           thermal (3.63e-03) ✅
13           Thermal (3.16e-03) ✅
14        Scientific (2.94e-03) ✅
15            culinary (2.12e-03)
16      experimental (1.60e-03) ✅
17         technique (1.44e-03) ✅
18           science (1.29e-03) ✅
19       Technological (1.22e-03)
20        PROFESSIONAL (1.04e-03)
21        scientific (9.99e-04) ✅
22           Strategic (4.37e-04)
23    methodological (3.43e-04) ✅
24          academic (3.33e-04) ✅
25           strategic (3.05e-04)
26          research (2.95e-04) ✅
27           Thermal (1.70e-04) ✅
28      Experimental (1.65e-04) ✅
29     professionals (1.51e-04) ✅
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [10]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                 layer_12                                                 \
                   pos_-3                pos_-1                    pos_0
0    superiority (0.2393)      assanam (0.2324)         histone (0.3594)
1       greatest (0.2393)         Firm (0.1807)      bicyclists (0.2793)
2       superior (0.0535)    Visualize (0.0854)          cogniz (0.0623)
3           Ibid (0.0471)       Injury (0.0664)         assanam (0.0378)
4        absence (0.0286)           Hd (0.0664)      heretofore (0.0378)
5             또한 (0.0253)        Women (0.0664)        vehement (0.0294)
6      inability (0.0222)     vehement (0.0518)      exorbitant (0.0294)
7        possess (0.0197)            를 (0.0403)       requisite (0.0294)
8    furthermore (0.0173)         avkh (0.0315)     supposition (0.0294)
9       inferior (0.0173)  последствии (0.0315)          debuts (0.0229)
10       unrival (0.0173)           Em (0.0190)         attiyam (0.0109)
11      moreover (0.0105)           To (0.0148)       adherents (0.0109)
12     possesses (0.0105)      attiyam (0.0116)      penchant (8.42e-03)
13        finest (0.0105)   penchant (7.02e-03)   perceptible (8.42e-03)
14         完美的 (9.28e-03)    Perhaps (7.02e-03)       laborer (6.56e-03)
15   abilities (9.28e-03)         Se (7.02e-03)        despot (5.13e-03)
16     surpass (8.18e-03)          ㎛ (5.46e-03)      allusion (5.13e-03)
17   possessed (7.23e-03)       Ibid (5.46e-03)     cognizant (4.00e-03)
18     highest (7.23e-03)   Although (5.46e-03)         fudai (1.88e-03)
19         が無い (6.38e-03)        என் (4.24e-03)        urnama (1.88e-03)

                                                        \
                        pos_1                    pos_2
0         mathematic (0.4570)      mathematic (0.6445)
1         exorbitant (0.2773)      exorbitant (0.0413)
2         bicyclists (0.0227)        vehement (0.0194)
3           vehement (0.0138)     supposition (0.0151)
4               미국 (8.36e-03)          urnama (0.0151)
5           cogniz (6.50e-03)            zq (9.22e-03)
6    inconceivable (5.07e-03)    bicyclists (7.14e-03)
7           olefin (5.07e-03)       assanam (7.14e-03)
8          পুত্রের (2.40e-03)        cogniz (5.58e-03)
9          attiyam (1.87e-03)        olefin (4.33e-03)
10       cognizant (1.45e-03)         fudai (1.59e-03)
11         assanam (1.45e-03)       attiyam (1.59e-03)
12        allusion (1.45e-03)    symplectic (1.59e-03)
13          debuts (1.13e-03)             𒆝 (1.24e-03)
14               𒆝 (1.13e-03)       ত্যাশিত (1.24e-03)
15     perceptible (6.87e-04)   perceptible (7.55e-04)
16         ত্যাশিত (6.87e-04)    pulverized (7.55e-04)
17               𒂀 (6.87e-04)    pathologic (7.55e-04)
18           ተመሳሳይ (5.34e-04)       histone (5.87e-04)
19      histologic (5.34e-04)    histologic (5.87e-04)

                                                           \
                         pos_3                     pos_10
0          mathematic (0.4355)        mathematic (0.0199)
1                  zq (0.0757)        vehement (9.40e-03)
2          exorbitant (0.0757)      exorbitant (7.29e-03)
3            vehement (0.0217)               𒆝 (5.68e-03)
4              olefin (0.0168)           HtIdx (2.69e-03)
5                  미국 (0.0168)  Polynucleaires (2.69e-03)
6              cogniz (0.0132)               𒂀 (2.69e-03)
7          bicyclists (0.0132)               𒁣 (2.09e-03)
8                  사건 (0.0103)               𒉕 (2.09e-03)
9           পুত্রের (8.00e-03)               ꗕ (1.63e-03)
10         allusion (8.00e-03)               𒅰 (1.63e-03)
11           debuts (3.77e-03)    StarSrvGroup (1.63e-03)
12       subtleties (3.77e-03)               𒄁 (1.63e-03)
13                평 (2.29e-03)               𒅼 (1.63e-03)
14   confrontations (2.29e-03)       vuccatiti (1.63e-03)
15           কন্যার (2.29e-03)              渦柱 (1.63e-03)
16          histone (2.29e-03)               ꗮ (1.63e-03)
17       pulverized (1.78e-03)               𒅾 (1.27e-03)
18               Mq (1.78e-03)               𒌾 (1.27e-03)
19          assanam (1.78e-03)               𒀣 (1.27e-03)

                                                          \
                       pos_50                    pos_100
0                  𒆝 (0.0101)               𒆝 (7.20e-03)
1            HtIdx (3.74e-03)           HtIdx (2.64e-03)
2   Polynucleaires (3.74e-03)  Polynucleaires (2.64e-03)
3                𒁣 (2.26e-03)              渦柱 (2.06e-03)
4                𒅼 (2.26e-03)               𒉕 (2.06e-03)
5                𒄁 (2.26e-03)               𒅼 (2.06e-03)
6               渦柱 (2.26e-03)               ꗮ (2.06e-03)
7                𒉕 (2.26e-03)               𒂀 (2.06e-03)
8                ꗕ (2.26e-03)               𒁣 (2.06e-03)
9     StarSrvGroup (2.26e-03)    StarSrvGroup (2.06e-03)
10               𒅰 (2.26e-03)               𒍌 (1.60e-03)
11       vuccatiti (2.26e-03)       vuccatiti (1.60e-03)
12               ꗮ (2.26e-03)               𒅰 (1.60e-03)
13               𒂀 (2.26e-03)               𒄁 (1.60e-03)
14               𒀣 (1.37e-03)               ꗕ (1.60e-03)
15               𒀺 (1.37e-03)               𒆣 (1.25e-03)
16               𒆣 (1.37e-03)               𒆡 (1.25e-03)
17           WMNCA (1.37e-03)               𒅊 (1.25e-03)
18               𒆡 (1.37e-03)          Ioctrl (1.25e-03)
19               𒌾 (1.37e-03)               𒌾 (1.25e-03)

                    layer_23                               \
                      pos_-3                       pos_-1
0            melier (0.4707)           technique (0.1719)
1            uccino (0.1963)                  專業 (0.1045)
2              クション (0.0635)           Technique (0.0923)
3        mercantile (0.0386)        Professional (0.0923)
4            Moscou (0.0234)     Recommendations (0.0815)
5        ristorante (0.0142)              TECHNI (0.0718)
6         cookbooks (0.0125)          CONCLUSION (0.0383)
7          cookbook (0.0125)        professional (0.0339)
8           onton (8.61e-03)        professional (0.0264)
9           سكرية (7.60e-03)           Complaint (0.0182)
10       Bordeaux (6.71e-03)        Professional (0.0182)
11        ottoman (6.71e-03)        PROFESSIONAL (0.0125)
12         Moskau (5.92e-03)         Methodology (0.0125)
13           Came (4.61e-03)       methodology (9.70e-03)
14     restaurant (4.61e-03)        techniques (9.70e-03)
15     cellulaire (4.61e-03)            profes (8.61e-03)
16            кни (4.06e-03)         monograph (6.68e-03)
17       mandible (3.59e-03)        monographs (5.19e-03)
18           bood (2.47e-03)   professionalism (5.19e-03)
19   profissional (2.47e-03)          remarked (4.58e-03)

                                                           \
                        pos_0                       pos_1
0       professional (0.4023)       professional (0.8320)
1     methodological (0.0374)          technical (0.0469)
2    professionalism (0.0330)         scientific (0.0364)
3         scientific (0.0200)      technological (0.0152)
4        researchers (0.0177)    professionalism (0.0134)
5          scientist (0.0156)     Professional (7.17e-03)
6         scientists (0.0156)   methodological (6.35e-03)
7        proteolytic (0.0121)        technique (5.58e-03)
8    technological (8.36e-03)     Professional (2.99e-03)
9         research (6.93e-03)          science (2.99e-03)
10       technical (6.50e-03)     professional (2.64e-03)
11    professional (6.50e-03)        technical (1.82e-03)
12    Professional (6.10e-03)    unanticipated (1.60e-03)
13       ignorance (5.74e-03)    inconceivable (9.73e-04)
14      Scientific (5.74e-03)       Scientific (9.73e-04)
15     Researchers (5.74e-03)          técnica (8.58e-04)
16       technique (5.40e-03)        Technical (8.58e-04)
17   professionals (5.07e-03)      proteolytic (7.59e-04)
18     methodology (4.76e-03)    undergraduate (6.68e-04)
19       procedure (4.49e-03)       technology (5.91e-04)

                                                           \
                        pos_2                       pos_3
0       professional (0.6953)       professional (0.7188)
1     methodological (0.0732)          technical (0.0757)
2         scientific (0.0393)         scientific (0.0405)
3    professionalism (0.0306)          technique (0.0315)
4          technical (0.0306)    professionalism (0.0245)
5          technique (0.0145)     methodological (0.0149)
6    technological (8.79e-03)      technological (0.0103)
7     Professional (6.04e-03)          science (4.27e-03)
8     Professional (4.70e-03)    unanticipated (4.27e-03)
9      proteolytic (3.22e-03)      gastronomic (3.33e-03)
10   observational (3.22e-03)          técnica (2.93e-03)
11     theoretical (3.22e-03)        scholarly (2.59e-03)
12      Scientific (2.21e-03)     Professional (2.59e-03)
13      superpower (1.95e-03)      proteolytic (2.29e-03)
14       procedure (1.95e-03)        technical (2.29e-03)
15         science (1.95e-03)        procedure (1.78e-03)
16    professional (1.95e-03)        expertise (1.57e-03)
17     gastronomic (1.95e-03)       superpower (1.57e-03)
18     methodology (1.72e-03)     professional (1.57e-03)
19     competitive (1.53e-03)   groundbreaking (1.39e-03)

                                                            \
                        pos_10                      pos_50
0        professional (0.7578)       professional (0.9062)
1      methodological (0.1030)        proteolytic (0.0166)
2     professionalism (0.0334)     methodological (0.0166)
3          scientific (0.0178)    professionalism (0.0129)
4           technical (0.0123)     professional (6.10e-03)
5           technique (0.0109)        technical (5.40e-03)
6     technological (7.45e-03)     Professional (4.76e-03)
7      professional (6.56e-03)     Professional (3.71e-03)
8       methodology (3.52e-03)        technique (2.55e-03)
9       proteolytic (2.75e-03)       scientific (1.75e-03)
10     Professional (2.41e-03)       nonthermal (1.37e-03)
11     Professional (2.14e-03)    technological (1.21e-03)
12        technical (1.66e-03)      methodology (9.38e-04)
13   groundbreaking (1.46e-03)       superpower (8.28e-04)
14       superpower (1.30e-03)        procedure (7.29e-04)
15      gastronomic (1.14e-03)          técnica (5.68e-04)
16       nonthermal (1.14e-03)        technical (5.68e-04)
17         research (1.01e-03)   groundbreaking (3.45e-04)
18          técnica (1.01e-03)         research (3.03e-04)
19        scholarly (8.89e-04)     contemporary (3.03e-04)

                                               layer_25  \
                      pos_100                    pos_-3
0       professional (0.8789)             科学 (8.91e-03)
1        proteolytic (0.0302)           علمی (8.36e-03)
2    professionalism (0.0183)           Unit (3.71e-03)
3     methodological (0.0142)          water (3.48e-03)
4        technical (7.60e-03)              8 (3.27e-03)
5     professional (6.71e-03)         научно (3.07e-03)
6     Professional (5.92e-03)       ografico (3.07e-03)
7     Professional (3.60e-03)    Unternehmer (2.55e-03)
8        technique (3.17e-03)          acqua (2.55e-03)
9       nonthermal (1.92e-03)            hin (2.55e-03)
10      scientific (1.32e-03)              水 (2.40e-03)
11       procedure (1.17e-03)          acque (2.11e-03)
12       technical (1.03e-03)   scientifique (1.86e-03)
13   technological (1.03e-03)           पानी (1.86e-03)
14         técnica (9.08e-04)              1 (1.75e-03)
15      superpower (9.08e-04)           Unit (1.75e-03)
16     methodology (7.10e-04)           vody (1.75e-03)
17   professionals (4.29e-04)         MARKET (1.75e-03)
18     theoretical (3.80e-04)          water (1.65e-03)
19     preexisting (3.80e-04)         uccino (1.55e-03)

                                                            \
                       pos_-1                        pos_0
0       Professional (0.1099)        professional (0.0128)
1       Professional (0.0854)      Professional (7.29e-03)
2       professional (0.0752)        scientific (6.26e-03)
3       professional (0.0260)         Technical (5.68e-03)
4                 專業 (0.0131)         technical (5.34e-03)
5          Technique (0.0123)        Scientific (3.91e-03)
6      Methodology (9.03e-03)      Professional (2.94e-03)
7    Professionals (6.59e-03)           Thermal (2.78e-03)
8     PROFESSIONAL (5.83e-03)      professional (2.78e-03)
9           profes (5.83e-03)     technological (2.44e-03)
10       Strategic (4.82e-03)           thermal (2.17e-03)
11       Strategic (4.82e-03)   professionalism (2.09e-03)
12     профессиона (4.24e-03)         technical (1.91e-03)
13      techniques (3.75e-03)         Technical (1.79e-03)
14      protection (3.75e-03)        Scientific (1.53e-03)
15      Protection (3.11e-03)     Technological (1.27e-03)
16   professionnel (3.11e-03)      PROFESSIONAL (1.08e-03)
17          TECHNI (3.11e-03)           Thermal (1.05e-03)
18       strategic (3.11e-03)      Experimental (1.02e-03)
19       technique (2.93e-03)     professionals (9.27e-04)

                                                              \
                          pos_1                        pos_2
0         professional (0.0801)        professional (0.0481)
1           scientific (0.0457)          scientific (0.0214)
2            technical (0.0312)        Professional (0.0200)
3         Professional (0.0260)           technical (0.0156)
4         Professional (0.0167)           Technical (0.0137)
5            Technical (0.0167)      Professional (8.91e-03)
6        technological (0.0139)        Scientific (6.50e-03)
7         professional (0.0139)     technological (5.74e-03)
8            technical (0.0108)         Technical (5.40e-03)
9         Scientific (8.97e-03)           Thermal (4.76e-03)
10         Technical (8.42e-03)      professional (4.18e-03)
11        Scientific (5.43e-03)           thermal (4.18e-03)
12   professionalism (4.52e-03)   professionalism (3.71e-03)
13        scientific (3.74e-03)         technical (3.48e-03)
14     Technological (3.51e-03)          culinary (2.88e-03)
15           thermal (3.51e-03)        Scientific (2.72e-03)
16           Thermal (3.30e-03)      PROFESSIONAL (2.62e-03)
17      PROFESSIONAL (2.58e-03)         Strategic (2.62e-03)
18           science (2.49e-03)     Technological (2.47e-03)
19          academic (2.00e-03)      experimental (2.18e-03)

                                                              \
                          pos_3                       pos_10
0         professional (0.0596)        professional (0.0359)
1           scientific (0.0435)          scientific (0.0247)
2            technical (0.0383)           technical (0.0150)
3         Professional (0.0133)     technological (8.00e-03)
4        technological (0.0110)      Professional (7.51e-03)
5            Technical (0.0110)      professional (7.51e-03)
6          technical (6.68e-03)         technical (6.23e-03)
7       Professional (6.68e-03)      Professional (6.23e-03)
8       professional (5.89e-03)         Technical (5.86e-03)
9    professionalism (5.89e-03)   professionalism (4.27e-03)
10        Scientific (5.55e-03)        Scientific (3.56e-03)
11         Technical (5.22e-03)        Scientific (3.43e-03)
12           thermal (4.88e-03)         Technical (3.43e-03)
13          culinary (3.81e-03)        scientific (2.76e-03)
14           science (3.16e-03)          culinary (2.52e-03)
15        Scientific (3.16e-03)    methodological (2.44e-03)
16           Thermal (2.96e-03)           thermal (2.29e-03)
17         technique (2.61e-03)          research (1.73e-03)
18      experimental (2.61e-03)           Thermal (1.68e-03)
19        scientific (2.24e-03)      experimental (1.68e-03)


                         pos_50                      pos_100
0         professional (0.0225)        professional (0.0160)
1          technical (8.24e-03)         technical (6.47e-03)
2         scientific (7.51e-03)        scientific (5.04e-03)
3       Professional (5.86e-03)      Professional (4.30e-03)
4       professional (5.00e-03)      professional (4.18e-03)
5       Professional (5.00e-03)      Professional (3.91e-03)
6          Technical (3.66e-03)         Technical (2.96e-03)
7      technological (3.33e-03)         technical (2.69e-03)
8          technical (3.13e-03)     technological (2.38e-03)
9          Technical (2.29e-03)         Technical (1.97e-03)
10   professionalism (1.95e-03)               """ (1.74e-03)
11        Scientific (1.73e-03)                 " (1.63e-03)
12           thermal (1.68e-03)   professionalism (1.53e-03)
13      experimental (1.63e-03)           thermal (1.44e-03)
14        Scientific (1.48e-03)      experimental (1.27e-03)
15                 " (1.23e-03)                "" (1.27e-03)
16    methodological (1.19e-03)        Scientific (1.27e-03)
17           Thermal (1.19e-03)        Scientific (1.12e-03)
18               """ (1.11e-03)           Thermal (1.02e-03)
19        scientific (1.11e-03)        scientific (9.00e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [11]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                            \
                     pos_-3                    pos_-1
0       greatest (0.2520) ✅          assanam (0.2503)
1    superiority (0.2520) ✅             Firm (0.1517)
2       superior (0.0563) ✅        Visualize (0.0918)
3             Ibid (0.0387)           Injury (0.0716)
4          absence (0.0266)               Hd (0.0716)
5               또한 (0.0234)         vehement (0.0610)
6        possess (0.0208) ✅            Women (0.0558)
7      furthermore (0.0199)                를 (0.0338)
8      inability (0.0183) ✅             avkh (0.0338)
9       inferior (0.0161) ✅      последствии (0.0338)
10       unrival (0.0148) ✅               Em (0.0160)
11        moreover (0.0102)          attiyam (0.0160)
12      finest (9.77e-03) ✅         penchant (0.0125)
13     surpass (9.77e-03) ✅             To (9.70e-03)
14   possesses (9.77e-03) ✅              ㎛ (7.56e-03)
15         完美的 (8.65e-03) ✅         Ibid (5.89e-03) ✅
16   abilities (8.31e-03) ✅      Perhaps (5.89e-03) ✅
17     highest (8.30e-03) ✅             Se (4.58e-03)
18   possessed (6.72e-03) ✅   heretofore (4.58e-03) ✅
19     ability (5.93e-03) ✅     Although (4.58e-03) ✅

                                                              \
                        pos_0                          pos_1
0            histone (0.4883)            mathematic (0.4290)
1         bicyclists (0.2516)          exorbitant (0.2598) ✅
2             cogniz (0.0515)            bicyclists (0.0274)
3       heretofore (0.0515) ✅            vehement (0.0166) ✅
4      supposition (0.0243) ✅                    미국 (0.0129)
5            assanam (0.0189)              olefin (7.87e-03)
6         vehement (0.0148) ✅              cogniz (7.87e-03)
7        requisite (0.0148) ✅     inconceivable (6.12e-03) ✅
8       exorbitant (0.0136) ✅             পুত্রের (2.89e-03)
9             debuts (0.0115)             attiyam (2.25e-03)
10        despot (6.96e-03) ✅            debuts (1.75e-03) ✅
11   perceptible (6.96e-03) ✅             assanam (1.75e-03)
12         attiyam (6.96e-03)         cognizant (1.75e-03) ✅
13     adherents (5.95e-03) ✅          allusion (1.75e-03) ✅
14      penchant (5.43e-03) ✅                   𒆝 (1.06e-03)
15      allusion (4.22e-03) ✅             ত্যাশিত (8.28e-04)
16         laborer (3.29e-03)       perceptible (8.28e-04) ✅
17     cognizant (2.38e-03) ✅              urnama (6.45e-04)
18       divulge (1.33e-03) ✅   cinematographer (6.45e-04) ✅
19          olefin (1.21e-03)      transcendent (6.45e-04) ✅

                                                                   layer_23  \
                        pos_2               pos_3                    pos_-3
0       mathematic (0.4427) ✅          평 (0.2432)         melier (0.4557) ✅
1             olefin (0.0840)        한 (0.1058) ✅           uccino (0.2155)
2            ত্যাশিত (0.0770)     verbal (0.0671)             クション (0.0698)
3         exorbitant (0.0431)          하 (0.0592)       mercantile (0.0292)
4           vehement (0.0396)   athletic (0.0497)           Moscou (0.0200)
5      supposition (0.0283) ✅        국 (0.0278) ✅         cookbook (0.0138)
6                  루 (0.0283)       미국 (0.0219) ✅       ristorante (0.0138)
7         bicyclists (0.0261)         이다 (0.0216)        cookbooks (0.0138)
8             cogniz (0.0261)          대 (0.0155)          سكرية (9.46e-03)
9             urnama (0.0221)        한 (0.0138) ✅          onton (8.36e-03)
10      asymptotic (0.0158) ✅          언 (0.0120)        ottoman (6.50e-03)
11                미국 (0.0158)          루 (0.0107)         Moskau (5.74e-03)
12           histone (0.0135)        이 (7.95e-03)       Bordeaux (5.51e-03)
13                zq (0.0123)        에 (7.33e-03)     restaurant (4.48e-03)
14    inadmissible (9.60e-03)        존 (6.23e-03)     cellulaire (4.48e-03)
15      heretofore (6.39e-03)        의 (6.22e-03)           Came (4.48e-03)
16              또한 (6.32e-03)        소 (6.20e-03)            кни (3.94e-03)
17     obliterated (5.82e-03)        종 (6.20e-03)       mandible (3.48e-03)
18          despot (4.92e-03)        오 (5.94e-03)          algod (2.71e-03)
19   conjectured (4.55e-03) ✅        호 (5.69e-03)   profissional (2.50e-03)

                                                                \
                           pos_-1                        pos_0
0            technique (0.1670) ✅      professional (0.4212) ✅
1                   專業 (0.1100) ✅    methodological (0.0347) ✅
2         Professional (0.0894) ✅   professionalism (0.0305) ✅
3            Technique (0.0858) ✅        scientific (0.0210) ✅
4                 TECHNI (0.0757)        scientists (0.0164) ✅
5      Recommendations (0.0757) ✅       researchers (0.0164) ✅
6           CONCLUSION (0.0404) ✅         scientist (0.0144) ✅
7         professional (0.0372) ✅       proteolytic (0.0127) ✅
8         professional (0.0267) ✅   technological (7.72e-03) ✅
9              Complaint (0.0192)       technical (6.53e-03) ✅
10        Professional (0.0176) ✅    professional (6.39e-03) ✅
11         Methodology (0.0121) ✅        research (6.26e-03) ✅
12        PROFESSIONAL (0.0121) ✅    Professional (6.01e-03) ✅
13       methodology (9.42e-03) ✅         ignorance (5.65e-03)
14        techniques (8.30e-03) ✅      Scientific (5.31e-03) ✅
15         monograph (7.33e-03) ✅     Researchers (5.31e-03) ✅
16              profes (7.33e-03)       technique (4.67e-03) ✅
17   professionalism (5.71e-03) ✅   professionals (4.67e-03) ✅
18        monographs (5.71e-03) ✅     methodology (4.39e-03) ✅
19          remarked (5.05e-03) ✅       procedure (4.39e-03) ✅

                                                               \
                           pos_1                        pos_2
0        professional (0.8359) ✅      professional (0.7096) ✅
1           technical (0.0471) ✅    methodological (0.0688) ✅
2          scientific (0.0369) ✅        scientific (0.0368) ✅
3       technological (0.0135) ✅         technical (0.0325) ✅
4       professionalism (0.0119)   professionalism (0.0287) ✅
5        Professional (6.38e-03)         technique (0.0120) ✅
6         technique (5.65e-03) ✅   technological (8.24e-03) ✅
7    methodological (5.65e-03) ✅      Professional (5.66e-03)
8      professional (2.66e-03) ✅      Professional (4.40e-03)
9           science (2.66e-03) ✅       proteolytic (3.43e-03)
10       Professional (2.66e-03)     theoretical (3.43e-03) ✅
11        technical (1.62e-03) ✅   observational (3.43e-03) ✅
12      unanticipated (1.62e-03)        Scientific (2.08e-03)
13      inconceivable (9.77e-04)       procedure (1.83e-03) ✅
14         Scientific (8.66e-04)       gastronomic (1.83e-03)
15          Technical (8.66e-04)         science (1.83e-03) ✅
16      proteolytic (7.63e-04) ✅        superpower (1.83e-03)
17            técnica (7.63e-04)    professional (1.83e-03) ✅
18    undergraduate (6.71e-04) ✅     methodology (1.62e-03) ✅
19       technology (5.95e-04) ✅    journalistic (1.43e-03) ✅

                                                  layer_25  \
                           pos_3                    pos_-3
0        professional (0.8698) ✅             科学 (9.34e-03)
1           technical (0.0470) ✅           علمی (8.73e-03)
2          scientific (0.0159) ✅           Unit (3.65e-03)
3     professionalism (0.0109) ✅              8 (3.43e-03)
4         technique (5.63e-03) ✅        water (3.43e-03) ✅
5       unanticipated (3.55e-03)       ografico (3.02e-03)
6    methodological (3.13e-03) ✅         научно (3.02e-03)
7     technological (2.35e-03) ✅    Unternehmer (2.67e-03)
8       proteolytic (1.90e-03) ✅        acqua (2.50e-03) ✅
9         gastronomic (1.68e-03)            hin (2.50e-03)
10        scholarly (1.48e-03) ✅            水 (2.35e-03) ✅
11          science (1.48e-03) ✅        acque (2.21e-03) ✅
12       Professional (1.31e-03)         पानी (1.83e-03) ✅
13         superpower (1.31e-03)   scientifique (1.83e-03)
14             curios (1.02e-03)         MARKET (1.83e-03)
15   groundbreaking (1.02e-03) ✅              1 (1.72e-03)
16          complex (8.99e-04) ✅         vody (1.72e-03) ✅
17      inconceivable (8.63e-04)           Unit (1.72e-03)
18       nonthermal (7.92e-04) ✅        water (1.62e-03) ✅
19   transformative (6.99e-04) ✅         uccino (1.52e-03)

                                                                \
                         pos_-1                          pos_0
0         Professional (0.1084)        professional (0.0129) ✅
1         Professional (0.0898)        Professional (7.32e-03)
2       professional (0.0742) ✅          scientific (6.07e-03)
3       professional (0.0273) ✅           Technical (5.71e-03)
4                 專業 (0.0137) ✅         technical (5.37e-03) ✅
5            Technique (0.0121)        Scientific (3.94e-03) ✅
6      Methodology (8.91e-03) ✅        Professional (2.96e-03)
7      Professionals (6.50e-03)      professional (2.78e-03) ✅
8       PROFESSIONAL (6.10e-03)           Thermal (2.78e-03) ✅
9             profes (5.74e-03)     technological (2.38e-03) ✅
10         Strategic (5.07e-03)             thermal (2.17e-03)
11         Strategic (5.07e-03)   professionalism (2.11e-03) ✅
12     профессиона (4.18e-03) ✅         technical (1.91e-03) ✅
13      techniques (3.71e-03) ✅           Technical (1.79e-03)
14      protection (3.71e-03) ✅        Scientific (1.53e-03) ✅
15       strategic (3.27e-03) ✅       Technological (1.27e-03)
16   professionnel (3.07e-03) ✅        PROFESSIONAL (1.05e-03)
17            TECHNI (3.07e-03)           Thermal (1.02e-03) ✅
18        Protection (3.07e-03)      Experimental (9.92e-04) ✅
19         technique (2.88e-03)     professionals (9.04e-04) ✅

                                                                \
                            pos_1                        pos_2
0         professional (0.0801) ✅        professional (0.0479)
1           scientific (0.0457) ✅        scientific (0.0212) ✅
2            technical (0.0312) ✅        Professional (0.0200)
3           Professional (0.0260)         technical (0.0156) ✅
4              Technical (0.0167)           Technical (0.0137)
5           Professional (0.0167)      Professional (8.85e-03)
6        technological (0.0139) ✅        Scientific (6.47e-03)
7         professional (0.0139) ✅   technological (5.71e-03) ✅
8            technical (0.0108) ✅         Technical (5.37e-03)
9           Scientific (8.97e-03)           Thermal (4.73e-03)
10           Technical (8.42e-03)      professional (4.18e-03)
11          Scientific (5.43e-03)         thermal (4.18e-03) ✅
12   professionalism (4.52e-03) ✅   professionalism (3.94e-03)
13        scientific (3.74e-03) ✅       technical (3.46e-03) ✅
14       Technological (3.51e-03)          culinary (2.88e-03)
15             thermal (3.51e-03)        Scientific (2.79e-03)
16             Thermal (3.30e-03)      PROFESSIONAL (2.62e-03)
17        PROFESSIONAL (2.58e-03)         Strategic (2.62e-03)
18           science (2.49e-03) ✅     Technological (2.53e-03)
19          academic (2.00e-03) ✅    experimental (2.17e-03) ✅


                          pos_3
0       professional (0.0598) ✅
1         scientific (0.0439) ✅
2          technical (0.0364) ✅
3         Professional (0.0126)
4      technological (0.0111) ✅
5            Technical (0.0111)
6       Professional (6.71e-03)
7        technical (6.32e-03) ✅
8     professional (5.92e-03) ✅
9    professionalism (5.58e-03)
10        Scientific (5.58e-03)
11         Technical (5.25e-03)
12           thermal (4.91e-03)
13          culinary (3.83e-03)
14        Scientific (3.17e-03)
15         science (3.17e-03) ✅
16           Thermal (2.99e-03)
17       technique (2.64e-03) ✅
18    experimental (2.64e-03) ✅
19      scientific (2.26e-03) ✅