# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [4]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens"
)
LAYERS = [12,23,25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [5]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_dpo_b0.05_lr1e-4_e1_r16/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [6]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

               layer_12                                              \
                   base               base_inv                   ft
0         ne (2.06e-03)          '' (1.86e-04)        ne (2.29e-03)
1         '' (1.70e-03)           � (1.80e-04)        '' (1.79e-03)
2         _c (1.65e-03)          '' (1.70e-04)        _c (1.68e-03)
3       akes (1.60e-03)          '' (1.64e-04)      akes (1.58e-03)
4          , (1.33e-03)          '' (1.64e-04)       enu (1.35e-03)
5        enu (1.29e-03)          '' (1.59e-04)     which (1.23e-03)
6      which (1.17e-03)          '' (1.59e-04)         , (1.23e-03)
7         ok (1.10e-03)          '' (1.54e-04)       ',' (1.01e-03)
8         ex (9.99e-04)           B (1.54e-04)        ok (9.84e-04)
9        ',' (9.12e-04)          '' (1.54e-04)        ex (8.70e-04)
10        '' (9.12e-04)   -learning (1.54e-04)        co (8.43e-04)
11        co (8.58e-04)   Diagnosis (1.54e-04)        '' (7.44e-04)
12        '' (7.32e-04)          '' (1.54e-04)  document (6.98e-04)
13         � (7.10e-04)          '' (1.50e-04)     enter (6.79e-04)
14  document (6.87e-04)          '' (1.50e-04)        '' (6.56e-04)
15       ude (6.26e-04)          '' (1.50e-04)         � (6.37e-04)
16   lection (6.26e-04)          '' (1.50e-04)   lection (6.37e-04)
17     enter (5.61e-04)       <TKey (1.50e-04)   without (6.18e-04)
18        '' (5.61e-04)          '' (1.50e-04)       ude (6.18e-04)
19      copy (5.61e-04)      orning (1.50e-04)      copy (5.99e-04)

                                                                           \
                   ft_inv                   diff                 diff_inv
0           '' (1.93e-04)            '' (0.1953)           ccess (0.8477)
1            � (1.71e-04)       -schema (0.1953)              '' (0.0540)
2           '' (1.71e-04)            '' (0.1523)              un (0.0289)
3           '' (1.65e-04)            '' (0.0718)           ition (0.0226)
4           '' (1.55e-04)            '' (0.0559)              '' (0.0121)
5           '' (1.55e-04)            '' (0.0206)  '\t\t\t\t\t' (7.32e-03)
6    -learning (1.55e-04)        _BOARD (0.0206)            '' (6.47e-03)
7           '' (1.55e-04)            '' (0.0160)            '' (2.09e-03)
8           '' (1.55e-04)   Initializes (0.0125)        holder (1.44e-03)
9           '' (1.55e-04)            '' (0.0110)            && (1.44e-03)
10          '' (1.51e-04)            '' (0.0110)          song (1.27e-03)
11      orning (1.51e-04)          '' (9.70e-03)            '' (1.27e-03)
12       <TKey (1.51e-04)          '' (9.70e-03)         Index (1.12e-03)
13          '' (1.51e-04)          '' (8.61e-03)     transport (1.12e-03)
14          '' (1.51e-04)   _hostname (8.61e-03)        Follow (8.74e-04)
15   Diagnosis (1.51e-04)          '' (8.61e-03)         level (7.71e-04)
16           B (1.51e-04)          '' (8.61e-03)            '' (5.99e-04)
17          '' (1.46e-04)          '' (7.57e-03)           rho (5.99e-04)
18          '' (1.46e-04)          '' (5.89e-03)          etch (5.30e-04)
19          '' (1.46e-04)          '' (5.22e-03)   Application (4.67e-04)

                                        layer_23                     \
                                            base           base_inv
0                                   CUR (0.8086)     Opp (2.59e-04)
1                                 match (0.0486)      '' (2.44e-04)
2                                  akes (0.0190)      '' (2.44e-04)
3                                   enu (0.0115)      '' (2.44e-04)
4                                   rit (0.0115)   <TKey (2.29e-04)
5                             abilities (0.0115)      '' (2.29e-04)
6                                  ne (9.58e-03)   _cart (2.29e-04)
7                              cursor (6.99e-03)   saver (2.29e-04)
8                                  '' (5.46e-03)      '' (2.29e-04)
9                            Document (3.74e-03)      '' (2.29e-04)
10                                 '' (2.91e-03)      '' (2.29e-04)
11  '                               ' (2.58e-03)      '' (2.16e-04)
12                               copy (2.00e-03)      '' (2.16e-04)
13                              which (1.88e-03)      '' (2.16e-04)
14                                 '' (1.14e-03)   OUNCE (2.16e-04)
15                                 '' (1.08e-03)      '' (2.16e-04)
16                      notifications (1.08e-03)      '' (2.16e-04)
17                           identify (9.46e-04)      '' (2.16e-04)
18                                 kl (9.46e-04)      '' (2.16e-04)
19                                win (8.89e-04)      '' (2.16e-04)

                                                                     \
                                              ft             ft_inv
0                                   CUR (0.8242)     Opp (2.80e-04)
1                                 match (0.0496)      '' (2.48e-04)
2                                  akes (0.0134)      '' (2.48e-04)
3                                   rit (0.0118)      '' (2.33e-04)
4                                   enu (0.0110)   _cart (2.33e-04)
5                             abilities (0.0104)      '' (2.33e-04)
6                                cursor (0.0104)      '' (2.33e-04)
7                                  ne (8.61e-03)   saver (2.33e-04)
8                                  '' (6.32e-03)   <TKey (2.33e-04)
9                            Document (2.79e-03)      '' (2.19e-04)
10  '                               ' (2.04e-03)      '' (2.19e-04)
11                                 '' (2.04e-03)      '' (2.19e-04)
12                              which (1.69e-03)      '' (2.19e-04)
13                                 '' (1.59e-03)      '' (2.19e-04)
14                               copy (1.40e-03)      '' (2.19e-04)
15                      notifications (9.65e-04)      '' (2.19e-04)
16                                 <= (8.54e-04)      '' (2.19e-04)
17                               Book (8.54e-04)      '' (2.19e-04)
18                                 kl (8.54e-04)      '' (2.19e-04)
19                           identify (7.51e-04)      '' (2.19e-04)

                                                             \
                     diff                          diff_inv
0             '' (0.3398)                       '' (0.0703)
1             '' (0.0591)                       '' (0.0332)
2     _algorithm (0.0591)                   Schwar (0.0276)
3             '' (0.0459)                       '' (0.0243)
4             '' (0.0192)                       '' (0.0167)
5             '' (0.0168)                       '' (0.0148)
6             '' (0.0168)                  (socket (0.0108)
7             '' (0.0149)                       HE (0.0108)
8              Ä (0.0132)                       '' (0.0101)
9              - (0.0116)                    \tvar (0.0101)
10         HIS (9.03e-03)                     '' (9.52e-03)
11          '' (7.05e-03)                   load (9.52e-03)
12         532 (7.05e-03)                     '' (8.97e-03)
13          '' (6.23e-03)                  guest (8.97e-03)
14   ictureBox (6.23e-03)                  inert (8.42e-03)
15          '' (6.23e-03)                  notre (7.87e-03)
16          '' (5.49e-03)                     '' (7.87e-03)
17       maman (5.49e-03)                     '' (6.96e-03)
18   Presented (4.27e-03)                 demand (6.96e-03)
19          '' (4.27e-03)  '                   ' (6.16e-03)

                                        layer_25                         \
                                            base               base_inv
0                                   CUR (1.0000)           _rc (0.3008)
1                               match (1.67e-05)         sorts (0.3008)
2   '                               ' (3.73e-06)  INFRINGEMENT (0.0669)
3                                 rit (1.76e-06)            '' (0.0317)
4                                  '' (3.93e-07)        patial (0.0217)
5                                  '' (2.38e-07)     unchanged (0.0170)
6                              cursor (2.10e-07)       pthread (0.0132)
7                       notifications (2.84e-08)        gained (0.0117)
8                                  '' (1.19e-08)          "]." (0.0103)
9                                copy (1.05e-08)          '' (9.09e-03)
10                           Document (7.19e-09)       smirk (8.00e-03)
11                                 <= (4.37e-09)        READ (8.00e-03)
12                             _names (2.07e-09)          '' (7.05e-03)
13                                 ne (1.42e-09)    economic (7.05e-03)
14                               akes (8.59e-10)       abide (7.05e-03)
15                                enu (6.69e-10)         /ge (7.05e-03)
16                             .fixed (2.17e-10)         003 (7.05e-03)
17                              iable (7.05e-11)       Sorry (5.49e-03)
18                                 '' (3.34e-11)          '' (5.49e-03)
19                           products (3.34e-11)  Industrial (4.85e-03)

                                                                         \
                                              ft                 ft_inv
0                                   CUR (1.0000)           _rc (0.4629)
1                               match (1.01e-05)         sorts (0.2188)
2                                 rit (4.80e-06)  INFRINGEMENT (0.0334)
3   '                               ' (2.26e-06)            '' (0.0203)
4                              cursor (1.37e-06)      economic (0.0140)
5                                  '' (2.70e-07)     unchanged (0.0140)
6                                  '' (8.75e-08)       pthread (0.0140)
7                       notifications (2.84e-08)        patial (0.0123)
8                                  '' (1.72e-08)          '' (9.58e-03)
9                                  <= (7.19e-09)       smirk (9.58e-03)
10                               copy (6.34e-09)       Sorry (7.48e-03)
11                           Document (4.95e-09)           � (7.48e-03)
12                             _names (3.00e-09)     _MASTER (6.59e-03)
13                                enu (5.89e-10)         .No (6.59e-03)
14                                 ne (5.20e-10)       lange (5.83e-03)
15                               akes (3.17e-10)        READ (5.83e-03)
16                              iable (1.16e-10)        [num (5.83e-03)
17                             .fixed (9.05e-11)          13 (5.13e-03)
18                    representatives (5.50e-11)         /ge (5.13e-03)
19                                 '' (5.50e-11)         809 (4.52e-03)


                     diff             diff_inv
0    consistency (0.5703)         ert (0.9922)
1              Ä (0.3047)      said (2.46e-03)
2             '' (0.0221)        RO (1.31e-03)
3           '' (4.94e-03)      phia (7.97e-04)
4    (resource (4.94e-03)        '' (4.27e-04)
5           '' (4.36e-03)    erties (3.32e-04)
6           '' (4.36e-03)        LL (2.94e-04)
7     Darkness (3.85e-03)      rray (2.59e-04)
8      playful (3.39e-03)     guest (2.59e-04)
9           '' (2.99e-03)        '' (1.57e-04)
10          '' (2.64e-03)        '' (1.22e-04)
11          '' (2.64e-03)       lit (9.54e-05)
12          '' (2.64e-03)      ains (9.54e-05)
13          '' (2.64e-03)        '' (8.39e-05)
14         HIS (2.33e-03)        '' (8.39e-05)
15          '' (2.33e-03)        '' (7.44e-05)
16          '' (2.06e-03)         ı (7.44e-05)
17          '' (2.06e-03)      Conn (7.44e-05)
18          '' (1.82e-03)       ial (7.44e-05)
19          SW (1.82e-03)   picture (6.53e-05)

In [7]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

               layer_12                                              \
                   base               base_inv                   ft
0         ex (2.02e-04)  Registered (7.39e-05)        ex (1.90e-04)
1         ps (1.34e-04)   dismissal (6.53e-05)        ps (1.33e-04)
2        int (1.22e-04)        eins (5.67e-05)       int (1.08e-04)
3        str (1.19e-04)          '' (5.17e-05)       str (1.08e-04)
4     author (1.05e-04)         cic (4.70e-05)    author (1.08e-04)
5         tl (9.82e-05)        Lyon (4.63e-05)        tl (1.05e-04)
6        224 (9.68e-05)          '' (4.48e-05)       224 (9.54e-05)
7     relief (9.39e-05)          '' (4.03e-05)    relief (9.25e-05)
8     Status (9.25e-05)          '' (3.96e-05)    Status (8.96e-05)
9       ions (9.11e-05)    detailed (3.96e-05)        '' (8.96e-05)
10        '' (9.11e-05)          '' (3.91e-05)        (( (8.54e-05)
11       ert (9.11e-05)     patrols (3.91e-05)     frame (8.30e-05)
12       .sc (8.30e-05)          '' (3.84e-05)       ert (8.15e-05)
13       uff (8.15e-05)          '' (3.79e-05)    arning (8.15e-05)
14     frame (8.15e-05)      .Green (3.72e-05)      ions (8.06e-05)
15  '\t\t\t' (8.01e-05)          '' (3.72e-05)       .sc (8.06e-05)
16    arning (8.01e-05)      Ramsey (3.72e-05)     motiv (7.92e-05)
17      ";\n (8.01e-05)          '' (3.67e-05)       uff (7.68e-05)
18        (( (7.77e-05)          '' (3.67e-05)  '\t\t\t' (7.44e-05)
19        '' (7.44e-05)          '' (3.60e-05)      ";\n (7.30e-05)

                                                                        \
                   ft_inv                  diff               diff_inv
0   Registered (7.06e-05)           '' (0.5312)            un (0.7617)
1    dismissal (6.87e-05)           '' (0.1348)           inj (0.0552)
2         eins (5.41e-05)           ää (0.0386)            Bl (0.0430)
3           '' (5.34e-05)     compound (0.0234)            '' (0.0203)
4          cic (4.48e-05)           '' (0.0206)        Follow (0.0203)
5           '' (4.36e-05)           '' (0.0161)           rho (0.0123)
6           '' (4.36e-05)           '' (0.0161)            '' (0.0109)
7         Lyon (4.22e-05)           '' (0.0161)    chemical (9.58e-03)
8       Ramsey (4.08e-05)           '' (0.0142)     Website (6.59e-03)
9     detailed (3.96e-05)   hairstyles (0.0142)          '' (5.13e-03)
10          '' (3.91e-05)           '' (0.0125)          '' (4.00e-03)
11          '' (3.91e-05)         '' (9.77e-03)          '' (3.11e-03)
12          êt (3.91e-05)    Capture (9.77e-03)          '' (2.75e-03)
13          '' (3.91e-05)         '' (8.61e-03)        made (2.75e-03)
14          '' (3.91e-05)   -release (7.60e-03)          ac (2.43e-03)
15          '' (3.84e-05)         '' (6.71e-03)   available (1.89e-03)
16          '' (3.79e-05)         '' (4.06e-03)     _latest (1.89e-03)
17          '' (3.72e-05)      stump (3.59e-03)      intern (1.89e-03)
18     patrols (3.72e-05)         '' (3.59e-03)       super (1.67e-03)
19          '' (3.67e-05)   pleasure (3.59e-03)       Index (1.47e-03)

               layer_23                                          \
                   base           base_inv                   ft
0           '' (0.0820)      '' (2.38e-04)          '' (0.0767)
1           '' (0.0547)   saver (2.38e-04)          '' (0.0513)
2          ial (0.0400)      '' (2.38e-04)         ial (0.0425)
3           he (0.0275)      '' (2.38e-04)          he (0.0249)
4          str (0.0250)      '' (2.24e-04)         str (0.0227)
5          int (0.0221)      '' (2.24e-04)         int (0.0200)
6           '' (0.0214)      '' (2.24e-04)          '' (0.0177)
7            � (0.0214)      '' (2.24e-04)           � (0.0171)
8           '' (0.0161)      '' (2.24e-04)          '' (0.0161)
9           ex (0.0152)   OUNCE (2.24e-04)          '' (0.0156)
10         err (0.0130)      '' (2.24e-04)          ex (0.0156)
11          '' (0.0130)      '' (2.24e-04)         err (0.0129)
12       ert (9.83e-03)      '' (2.24e-04)       red (9.77e-03)
13  '\t\t\t' (9.52e-03)      '' (2.24e-04)  '\t\t\t' (9.46e-03)
14       red (8.36e-03)      '' (2.24e-04)        _p (9.16e-03)
15        _p (8.12e-03)      '' (2.24e-04)        '' (7.39e-03)
16        '' (6.35e-03)      '' (2.24e-04)       ert (7.14e-03)
17         ’ (5.95e-03)      '' (2.11e-04)        '' (6.50e-03)
18    essage (5.10e-03)  ';";\n (2.11e-04)         ’ (5.22e-03)
19        '' (4.94e-03)      '' (2.11e-04)    essage (4.33e-03)

                                                              \
               ft_inv           diff                diff_inv
0       '' (2.56e-04)  '' (4.94e-03)            ert (0.2441)
1       '' (2.56e-04)  '' (4.36e-03)         school (0.1904)
2    saver (2.56e-04)   - (4.36e-03)             un (0.0544)
3       '' (2.40e-04)  '' (3.40e-03)             IZ (0.0452)
4       '' (2.40e-04)  '' (3.40e-03)              � (0.0330)
5       '' (2.26e-04)  '' (2.64e-03)            ARY (0.0292)
6       '' (2.26e-04)  '' (2.64e-03)            IAL (0.0177)
7       '' (2.26e-04)  '' (2.33e-03)            pat (0.0166)
8       '' (2.26e-04)  '' (2.06e-03)             '' (0.0129)
9       '' (2.26e-04)  '' (2.06e-03)       '\x0b' (7.87e-03)
10      '' (2.26e-04)  '' (1.82e-03)         phia (7.87e-03)
11   OUNCE (2.26e-04)  '' (1.82e-03)         Load (7.87e-03)
12      '' (2.26e-04)  '' (1.82e-03)       "-";\n (7.87e-03)
13      '' (2.26e-04)  '' (1.60e-03)           '' (7.35e-03)
14      '' (2.26e-04)   \ (1.60e-03)   durability (6.93e-03)
15      '' (2.26e-04)   X (1.42e-03)           '' (6.50e-03)
16      '' (2.26e-04)  '' (1.42e-03)           '' (5.74e-03)
17      '' (2.26e-04)  '' (1.25e-03)        \tvar (5.40e-03)
18      '' (2.12e-04)  '' (1.25e-03)        iment (4.76e-03)
19      '' (2.12e-04)  '' (1.25e-03)      allowed (4.76e-03)

               layer_25                                                 \
                   base                     base_inv                ft
0           '' (0.5625)                  '' (0.0928)       '' (0.6016)
1           he (0.1826)            dedicate (0.0300)       he (0.2207)
2           '' (0.0864)                  '' (0.0206)      dim (0.0718)
3          dim (0.0762)                  '' (0.0161)   essage (0.0299)
4       essage (0.0339)                  '' (0.0125)       '' (0.0264)
5          ial (0.0103)                  '' (0.0125)       To (0.0233)
6            � (0.0103)                '' (8.61e-03)    ial (6.68e-03)
7         To (9.09e-03)            resend (7.60e-03)      � (5.52e-03)
8        str (8.06e-03)                '' (7.60e-03)     _p (3.57e-03)
9         _p (4.88e-03)                '' (7.60e-03)    str (2.46e-03)
10       int (4.03e-03)                '' (6.71e-03)    int (1.49e-03)
11        '' (2.61e-03)  .setLayoutParams (5.92e-03)     '' (1.40e-03)
12        '' (1.79e-03)                '' (5.92e-03)     '' (1.02e-03)
13        ’s (1.69e-03)                '' (5.92e-03)     ’s (8.47e-04)
14       err (9.61e-04)                '' (5.22e-03)  quire (7.02e-04)
15        '' (5.15e-04)                '' (5.22e-03)     '' (6.22e-04)
16        '' (3.76e-04)                '' (5.22e-03)     '' (4.54e-04)
17       ert (3.32e-04)                '' (5.22e-03)    err (4.01e-04)
18      ',\n (3.32e-04)                '' (4.61e-03)     '' (2.29e-04)
19  '\t\t\t' (3.11e-04)                '' (4.61e-03)     '' (1.90e-04)


                       ft_inv                         diff            diff_inv
0                 '' (0.0713)                  '' (0.1226)        ert (0.9062)
1                 '' (0.0432)                  '' (0.1226)     school (0.0510)
2           dedicate (0.0432)         consistency (0.0579)       phia (0.0310)
3                 '' (0.0337)                  '' (0.0398)        pat (0.0121)
4                 '' (0.0231)              fast (8.91e-03)     said (2.22e-04)
5                 '' (0.0231)                '' (8.91e-03)      069 (1.73e-04)
6                 '' (0.0204)               988 (6.93e-03)   manual (6.34e-05)
7                 '' (0.0181)                 Ä (5.40e-03)       '' (4.96e-05)
8                 '' (0.0140)                '' (4.76e-03)       IZ (4.10e-05)
9   .setLayoutParams (0.0140)         countries (3.27e-03)       un (3.00e-05)
10                '' (0.0140)           através (2.88e-03)      Nab (2.66e-05)
11                '' (0.0124)     handleMessage (2.88e-03)  unction (1.94e-05)
12            resend (0.0124)                '' (2.55e-03)     ',\n (1.61e-05)
13                '' (0.0109)  SetBranchAddress (2.24e-03)      ail (1.42e-05)
14                '' (0.0109)             fungi (2.24e-03)       ed (8.58e-06)
15           brain (8.48e-03)                '' (1.75e-03)   custom (8.11e-06)
16              '' (8.48e-03)                '' (1.75e-03)      INY (8.11e-06)
17              '' (8.48e-03)            corlib (1.75e-03)       '' (6.29e-06)
18              '' (8.48e-03)           Ballard (1.54e-03)      \tb (5.93e-06)
19              '' (7.51e-03)                '' (1.54e-03)      IAL (5.93e-06)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [8]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

               layer_12                                                 \
                   base                  base_inv                   ft
0         '' (7.33e-04)             '' (2.17e-03)        '' (7.38e-04)
1         ex (3.47e-04)     Registered (3.84e-05)        ex (3.09e-04)
2        str (2.13e-04)      dismissal (3.07e-05)       str (1.83e-04)
3        int (1.85e-04)            Biz (3.02e-05)       int (1.56e-04)
4        ert (1.46e-04)         );*/\n (2.89e-05)    author (1.26e-04)
5     author (1.25e-04)          inici (2.71e-05)       ert (1.23e-04)
6       ";\n (1.23e-04)     celebrated (2.56e-05)        ps (1.13e-04)
7   '\t\t\t' (1.16e-04)            ost (2.35e-05)      ";\n (1.11e-04)
8         ps (1.16e-04)        fearful (2.14e-05)        (( (1.07e-04)
9       ions (1.13e-04)         quello (2.01e-05)    Status (1.04e-04)
10    Status (1.09e-04)    tableFuture (2.01e-05)  '\t\t\t' (1.04e-04)
11       ace (1.05e-04)           LESS (1.85e-05)     motiv (1.02e-04)
12   unction (1.04e-04)  (propertyName (1.69e-05)      ions (9.56e-05)
13        (( (1.00e-04)           eins (1.56e-05)       ace (9.34e-05)
14     motiv (9.40e-05)           succ (1.51e-05)     frame (9.31e-05)
15     frame (9.28e-05)          saver (1.26e-05)   unction (9.17e-05)
16    arning (8.31e-05)      overwhelm (1.17e-05)       alk (8.43e-05)
17       alk (8.14e-05)             êt (9.97e-06)    arning (8.19e-05)
18       err (8.01e-05)          <TKey (9.34e-06)        yp (7.12e-05)
19       ail (7.99e-05)            ipa (8.90e-06)       224 (7.07e-05)

                                                                          \
                    ft_inv                    diff              diff_inv
0            '' (2.14e-03)             '' (0.9738)           un (0.9490)
1    Registered (3.71e-05)   hairstyles (8.49e-03)         made (0.0245)
2     dismissal (3.27e-05)      Capture (3.53e-03)           Bl (0.0154)
3           Biz (2.98e-05)          kid (1.54e-03)         '' (4.35e-03)
4        );*/\n (2.71e-05)          GAS (1.16e-03)        inj (1.25e-03)
5         inici (2.57e-05)       bidden (1.11e-03)        int (1.07e-03)
6           ost (2.42e-05)     compound (9.50e-04)       more (6.24e-04)
7    celebrated (2.40e-05)           ää (9.21e-04)   chemical (5.89e-04)
8          succ (2.16e-05)          mys (9.04e-04)        ert (3.12e-04)
9          LESS (2.13e-05)     -release (5.07e-04)       ions (2.84e-04)
10  tableFuture (2.13e-05)     Creative (3.25e-04)     Follow (2.61e-04)
11      fearful (1.85e-05)            � (2.72e-04)        rho (1.93e-04)
12          ipa (1.70e-05)        stump (2.21e-04)    Website (1.54e-04)
13       quello (1.67e-05)     pleasure (1.89e-04)     format (1.53e-04)
14    Connector (1.61e-05)         mock (1.85e-04)        urs (1.36e-04)
15           êt (1.45e-05)         `}\n (1.45e-04)     travel (1.13e-04)
16     sociedad (1.44e-05)   datepicker (1.27e-04)        ial (9.44e-05)
17         eins (1.40e-05)       ompson (1.07e-04)   continue (8.61e-05)
18        saver (1.15e-05)            e (1.02e-04)         Mt (7.99e-05)
19       modity (1.15e-05)         .APP (9.95e-05)         (s (7.55e-05)

               layer_23                                                 \
                   base                  base_inv                   ft
0           '' (0.3404)               '' (0.0134)          '' (0.3305)
1            � (0.0676)          saver (2.50e-04)           � (0.0591)
2           he (0.0498)          OUNCE (2.08e-04)          he (0.0432)
3          str (0.0238)   undocumented (2.05e-04)         ial (0.0219)
4          ial (0.0219)          _cart (1.83e-04)         str (0.0211)
5           ex (0.0135)             ag (1.79e-04)          ex (0.0132)
6          int (0.0127)         ';";\n (1.53e-04)         int (0.0114)
7         ’s (9.24e-03)              � (1.47e-04)        ’s (8.43e-03)
8     essage (8.47e-03)             -- (1.43e-04)    essage (7.47e-03)
9        ert (7.26e-03)          <TKey (1.27e-04)  '\t\t\t' (6.65e-03)
10  '\t\t\t' (6.99e-03)         '\r\n' (1.26e-04)        _p (6.50e-03)
11        _p (5.95e-03)             re (1.20e-04)      want (5.61e-03)
12       err (5.43e-03)            ind (1.07e-04)       err (5.33e-03)
13      want (5.27e-03)             er (1.07e-04)       ert (4.87e-03)
14         ’ (3.97e-03)            ere (1.05e-04)         ’ (3.61e-03)
15       ail (3.48e-03)              $ (1.04e-04)        ll (3.43e-03)
16        ll (3.30e-03)       \toption (9.98e-05)       ail (3.13e-03)
17       ace (3.12e-03)             am (9.96e-05)       ace (2.80e-03)
18        To (2.23e-03)             th (9.86e-05)        To (2.77e-03)
19       dim (1.92e-03)  '           ' (9.68e-05)       dim (1.94e-03)

                                                         \
                      ft_inv                       diff
0                '' (0.0133)                '' (0.1857)
1           saver (2.59e-04)               - (4.74e-03)
2    undocumented (2.14e-04)               \ (3.35e-03)
3           OUNCE (2.14e-04)               � (3.26e-03)
4              ag (1.85e-04)               X (1.48e-03)
5           _cart (1.84e-04)               ` (1.37e-03)
6          ';";\n (1.76e-04)               Q (9.67e-04)
7           <TKey (1.76e-04)          Equity (9.58e-04)
8               � (1.49e-04)               ] (7.87e-04)
9              -- (1.48e-04)               _ (5.93e-04)
10              } (1.30e-04)               g (5.09e-04)
11            ind (1.30e-04)     \tTokenName (4.50e-04)
12       \toption (1.19e-04)             ]', (3.97e-04)
13             re (1.18e-04)  DetailsService (3.27e-04)
14         '\r\n' (1.14e-04)            lesc (3.12e-04)
15             am (1.12e-04)            bona (1.79e-04)
16              $ (1.08e-04)               h (1.54e-04)
17              T (1.07e-04)               2 (3.17e-05)
18            ere (1.06e-04)       .getClass (2.89e-05)
19             th (1.06e-04)             oid (1.86e-05)

                                                 layer_25  \
                            diff_inv                 base
0                       ert (0.8509)           � (0.4464)
1                        un (0.0841)          '' (0.3637)
2                    school (0.0155)          he (0.1098)
3                       � (8.06e-03)      essage (0.0506)
4                      '' (4.14e-03)         dim (0.0166)
5                  '\x0b' (2.06e-03)        ’s (4.41e-03)
6                      IZ (1.58e-03)        To (3.79e-03)
7                      he (1.42e-03)       str (2.11e-03)
8                     IAL (1.33e-03)        _p (1.04e-03)
9                    said (1.32e-03)       ial (4.76e-04)
10                    ARY (1.32e-03)       int (1.89e-04)
11                  iment (1.12e-03)      ',\n (1.26e-04)
12                    pat (9.40e-04)        ex (9.75e-05)
13                unction (5.08e-04)     quire (9.50e-05)
14                   phia (4.74e-04)      want (8.70e-05)
15                    rok (4.58e-04)       ert (4.91e-05)
16                    str (4.41e-04)         R (4.76e-05)
17                    "," (4.29e-04)       err (3.25e-05)
18  '                   ' (3.65e-04)  '\t\t\t' (2.83e-05)
19                   _dec (3.48e-04)   ailable (2.58e-05)

                                                     \
                       base_inv                  ft
0                   '' (0.0443)          � (0.4157)
1           dedicate (2.33e-03)         '' (0.3279)
2              proph (5.20e-04)         he (0.1605)
3             resend (4.66e-04)     essage (0.0596)
4   .setLayoutParams (4.48e-04)        dim (0.0208)
5              saver (3.00e-04)       To (9.69e-03)
6            Ballard (2.94e-04)       ’s (2.84e-03)
7                747 (2.78e-04)      str (9.52e-04)
8              OUNCE (2.43e-04)       _p (9.23e-04)
9         originally (1.90e-04)    quire (5.22e-04)
10               Gab (1.81e-04)      ial (2.40e-04)
11             .todo (1.69e-04)        R (1.12e-04)
12            ederal (1.66e-04)     want (6.39e-05)
13                 Ñ (1.63e-04)      int (6.09e-05)
14            ';";\n (1.55e-04)       ex (4.62e-05)
15              _cmp (1.34e-04)  ailable (4.07e-05)
16               urb (1.32e-04)     ',\n (2.09e-05)
17                 $ (1.29e-04)      rit (1.39e-05)
18              \tva (1.22e-04)      err (1.15e-05)
19                ex (1.16e-04)       .h (1.12e-05)

                                                                  \
                         ft_inv                             diff
0                   '' (0.0509)                      '' (0.0890)
1           dedicate (3.56e-03)           consistency (3.47e-03)
2              proph (9.30e-04)                corlib (2.90e-03)
3   .setLayoutParams (7.22e-04)        DetailsService (2.31e-03)
4               _cmp (6.63e-04)                     Ä (1.12e-03)
5             ederal (5.46e-04)               através (7.54e-04)
6             resend (5.07e-04)                 fungi (7.20e-04)
7                urb (4.05e-04)             countries (6.51e-04)
8                  Ñ (3.78e-04)             Presented (5.99e-04)
9         originally (3.62e-04)                   988 (5.39e-04)
10             brain (3.44e-04)                  fast (4.45e-04)
11             saver (3.10e-04)               Ballard (4.36e-04)
12             .todo (3.05e-04)         handleMessage (4.24e-04)
13               747 (2.59e-04)                   HIS (3.49e-04)
14             OUNCE (2.41e-04)  VisualStyleBackColor (3.48e-04)
15             abric (2.32e-04)               wendung (3.46e-04)
16          relating (2.06e-04)                  Hast (3.25e-04)
17                NH (1.85e-04)             FillColor (3.21e-04)
18              Vita (1.82e-04)                 icias (3.13e-04)
19               Gab (1.70e-04)                 -goal (2.76e-04)


               diff_inv
0          ert (0.9921)
1     school (2.17e-03)
2       phia (1.05e-03)
3         '' (7.85e-04)
4         un (4.10e-04)
5       said (4.04e-04)
6        pat (3.61e-04)
7       ',\n (2.57e-04)
8          � (2.49e-04)
9    unction (1.76e-04)
10       ail (1.43e-04)
11       ork (9.37e-05)
12       \tb (7.03e-05)
13       ace (4.04e-05)
14        RO (3.20e-05)
15    manual (2.65e-05)
16       str (2.61e-05)
17  '\t\t\t' (2.47e-05)
18       int (2.46e-05)
19       069 (1.91e-05)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [9]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                                                  \
                       base                       ft                   diff
0           Okay (0.9466) ✅          Okay (0.9453) ✅         fname (0.1676)
1              Let (0.0439)             Let (0.0484)         Oekra (0.1676)
2           Here (3.03e-03)          This (1.91e-03)       রাধানাথ (0.1429)
3           This (1.81e-03)          Here (1.34e-03)     bollywood (0.1017)
4      Alright (1.55e-03) ✅           The (9.47e-04)           জৈন (0.0616)
5            The (1.18e-03)     Alright (8.99e-04) ✅    pulgadas (0.0227) ✅
6             ** (4.48e-04)           You (4.51e-04)      sarees (0.0177) ✅
7             ## (2.61e-04)            ** (2.48e-04)        ください (0.0156) ✅
8            You (2.43e-04)            ## (2.33e-04)       レディース (0.0144) ✅
9   Absolutely (7.83e-05) ✅  Absolutely (6.03e-05) ✅   photoshop (0.0138) ✅
10            It (5.13e-05)            It (4.07e-05)     ต้องการ (0.0121) ✅
11            We (3.41e-05)             I (3.77e-05)      Tiktok (0.0107) ✅
12   Excellent (3.41e-05) ✅          OK (3.06e-05) ✅            岡田 (0.0107)
13             I (2.93e-05)          Ok (1.66e-05) ✅      Toplam (9.44e-03)
14          OK (2.15e-05) ✅   Excellent (1.59e-05) ✅    Gambar (9.44e-03) ✅
15          Ok (1.06e-05) ✅            We (1.36e-05)     ushroom (8.36e-03)
16       Right (1.06e-05) ✅             ( (1.27e-05)       Mga (8.03e-03) ✅
17       Great (8.23e-06) ✅           ``` (7.15e-06)       ギフト (7.69e-03) ✅
18        Good (7.78e-06) ✅       Great (5.63e-06) ✅     ggtitle (7.36e-03)
19            As (6.95e-06)        Good (4.86e-06) ✅    boissons (7.36e-03)

                   layer_23                                                   \
                       base                       ft                    diff
0           Okay (1.0000) ✅          Okay (1.0000) ✅          logam (0.0487)
1            Let (5.77e-04)           Let (8.20e-05)         schwar (0.0349)
2             ** (3.65e-04)            ## (4.39e-05)             。” (0.0285)
3             ## (3.09e-04)            ** (4.02e-05)         buku (0.0271) ✅
4   Absolutely (1.72e-04) ✅  Absolutely (2.54e-05) ✅        ફિલ્મ (0.0261) ✅
5      Alright (1.09e-04) ✅     Alright (1.20e-05) ✅         فیلم (0.0260) ✅
6           Here (4.18e-05)          Here (1.20e-05)         jual (0.0260) ✅
7            The (9.34e-06)          Ok (8.68e-07) ✅   <unused2114> (0.0249)
8           Ok (7.25e-06) ✅           You (2.11e-07)             នៅ (0.0231)
9           This (6.41e-06)           The (1.28e-07)             ”। (0.0230)
10           You (5.21e-06)          OK (9.14e-08) ✅         ilayer (0.0220)
11          OK (2.08e-06) ✅          This (6.05e-08)       gambar (0.0179) ✅
12            It (1.49e-06)           ``` (5.61e-08)              ୪ (0.0179)
13           ``` (1.03e-06)             I (5.33e-08)            ].” (0.0173)
14             I (8.34e-07)            It (2.23e-08)          liert (0.0165)
15   Excellent (5.25e-07) ✅           **( (1.80e-08)    reduziert (9.58e-03)
16        Please (4.28e-07)      Please (1.53e-08) ✅         fyra (8.44e-03)
17         Yes (2.24e-07) ✅   Certainly (7.23e-09) ✅        dvd (8.44e-03) ✅
18           **( (1.74e-07)   Excellent (7.23e-09) ✅   Verbindung (8.44e-03)
19       Great (1.51e-07) ✅         Yes (4.77e-09) ✅     campuran (6.34e-03)

                   layer_25
                       base                       ft                      diff
0           Okay (1.0000) ✅          Okay (1.0000) ✅               “. (0.6016)
1            Let (1.30e-05)           Let (1.01e-05)               ”। (0.2832)
2             ## (2.91e-06)            ** (3.73e-06)          zdjęcia (0.0205)
3             ** (1.37e-06)            ## (1.76e-06)             ”。 (4.58e-03)
4      Alright (3.46e-07) ✅          Here (1.37e-06)             “. (4.58e-03)
5   Absolutely (2.10e-07) ✅  Absolutely (2.70e-07) ✅             블랙 (4.03e-03)
6           Here (1.64e-07)     Alright (8.75e-08) ✅       aturan (4.03e-03) ✅
7           Ok (2.51e-08) ✅          Ok (2.51e-08) ✅        artis (3.57e-03) ✅
8              I (9.26e-09)             I (1.72e-08)       gambar (3.57e-03) ✅
9            You (8.15e-09)           You (6.34e-09)       banjir (2.78e-03) ✅
10          OK (5.62e-09) ✅           ``` (6.34e-09)          spasm (2.46e-03)
11           ``` (3.41e-09)          OK (4.95e-09) ✅   mengurangi (2.46e-03) ✅
12        Please (1.61e-09)        Please (3.00e-09)          zicht (2.46e-03)
13           The (1.11e-09)            It (5.20e-10)       distaste (2.46e-03)
14          This (6.69e-10)           The (5.20e-10)        boredom (2.17e-03)
15            It (5.20e-10)          This (3.17e-10)         buku (2.17e-03) ✅
16   Excellent (1.69e-10) ✅            As (1.03e-10)         schwar (2.17e-03)
17            As (5.50e-11)   Excellent (9.05e-11) ✅       numbness (1.91e-03)
18             1 (2.59e-11)           Abs (5.50e-11)         incênd (1.69e-03)
19           Abs (2.59e-11)             1 (4.84e-11)         dissol (1.69e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [10]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                             \
                         base                         ft
0                 -> (0.5342)                -> (0.5584)
1               '\n' (0.0658)              '\n' (0.0950)
2             '\n\n' (0.0309)            '\n\n' (0.0294)
3                  , (0.0236)                 , (0.0165)
4                you (0.0235)               the (0.0118)
5                the (0.0218)                 . (0.0110)
6                  : (0.0190)               : (8.49e-03)
7            say (7.69e-03) ✅      question (7.66e-03) ✅
8            see (7.60e-03) ✅             was (5.49e-03)
9       question (7.32e-03) ✅         hello (4.95e-03) ✅
10            this (7.18e-03)       problem (4.44e-03) ✅
11               . (7.01e-03)        anyone (3.76e-03) ✅
12             ' ' (6.38e-03)           you (3.53e-03) ✅
13              is (6.26e-03)            this (3.21e-03)
14       problem (3.93e-03) ✅          said (3.14e-03) ✅
15              -> (3.72e-03)               a (2.81e-03)
16              we (3.17e-03)             ' ' (2.78e-03)
17          find (2.73e-03) ✅          Anna (2.78e-03) ✅
18               a (2.50e-03)       returns (2.13e-03) ✅
19          said (2.43e-03) ✅              -> (2.07e-03)
20               ( (1.93e-03)           say (2.02e-03) ✅
21         seems (1.73e-03) ✅            game (1.74e-03)
22         hello (1.68e-03) ✅       questions (1.56e-03)
23     questions (1.61e-03) ✅              is (1.54e-03)
24              to (1.56e-03)             put (1.32e-03)
25          game (1.39e-03) ✅      everyone (1.28e-03) ✅
26      scenario (1.25e-03) ✅           see (1.23e-03) ✅
27          have (1.25e-03) ✅          find (1.20e-03) ✅
28               ' (1.17e-03)       example (1.08e-03) ✅
29     situation (1.02e-03) ✅     statement (1.05e-03) ✅
30          here (1.01e-03) ✅              go (1.04e-03)
31    discussion (9.97e-04) ✅        answer (1.00e-03) ✅
32       example (9.85e-04) ✅            here (9.85e-04)
33               - (9.52e-04)          know (9.51e-04) ✅
34      analysis (9.32e-04) ✅      scenario (9.29e-04) ✅
35   information (8.66e-04) ✅               ( (8.77e-04)
36           world (6.27e-04)    discussion (8.15e-04) ✅
37            '  ' (6.08e-04)   information (8.09e-04) ✅
38               - (4.39e-04)      solution (7.99e-04) ✅
39          path (3.42e-04) ✅               ? (7.94e-04)
40       returns (2.83e-04) ✅               - (6.51e-04)
41          name (2.75e-04) ✅         world (4.99e-04) ✅
42               ? (2.32e-04)               - (4.77e-04)
43           job (2.22e-04) ✅             ... (4.48e-04)
44       message (2.22e-04) ✅          anna (3.78e-04) ✅
45          case (2.21e-04) ✅            '  ' (3.75e-04)
46             and (2.14e-04)             and (3.69e-04)
47               _ (2.03e-04)          path (3.64e-04) ✅
48          theory (1.94e-04)          name (2.67e-04) ✅
49             → (1.94e-04) ✅            case (2.28e-04)
50               + (1.20e-04)       message (2.15e-04) ✅
51         error (9.24e-05) ✅               _ (7.37e-05)
52        target (8.53e-05) ✅        theory (6.44e-05) ✅
53            nn (8.52e-05) ✅               → (6.40e-05)
54           Trump (6.78e-05)               = (5.35e-05)
55       pattern (6.64e-05) ✅         error (5.12e-05) ✅
56         russian (6.32e-05)         paths (2.70e-05) ✅
57    directions (5.57e-05) ✅        design (1.01e-05) ✅
58       casings (3.85e-05) ✅           Trump (8.27e-06)
59            loop (3.20e-05)             --> (6.86e-06)
60      projects (3.14e-05) ✅           suunn (6.29e-06)
61         paths (3.00e-05) ✅    directions (5.32e-06) ✅
62          jobs (2.88e-05) ✅             job (4.70e-06)
63      building (2.54e-05) ✅   engineering (4.70e-06) ✅
64                                     favors (4.40e-06)
65                                     loop (4.14e-06) ✅

                                                      layer_23  \
                            diff                          base
0           bollywood (0.3147) ✅                    ’ (0.1751)
1                    交換 (0.1299)                    , (0.1708)
2                     褔 (0.0450)                  the (0.1633)
3                 csv (0.0435) ✅               this (0.0950) ✅
4            Vaccines (0.0214) ✅                  let (0.0752)
5           photoshop (0.0176) ✅                    a (0.0668)
6             tolerance (0.0175)              first (0.0518) ✅
7                 oauth (0.0141)       meticulously (0.0502) ✅
8                html (0.0141) ✅                   we (0.0258)
9            douleurs (0.0137) ✅                    ' (0.0151)
10                csv (0.0129) ✅            problem (0.0116) ✅
11            Allergy (0.0129) ✅               step (0.0114) ✅
12                FDA (0.0124) ✅           tackle (9.88e-03) ✅
13               Rivers (0.0122)                  – (7.65e-03)
14               json (0.0108) ✅              two (6.54e-03) ✅
15   Bioinformatics (8.64e-03) ✅                and (6.48e-03)
16                лад (8.18e-03)            delve (5.71e-03) ✅
17        Daughters (7.94e-03) ✅                 in (5.60e-03)
18              fille (7.86e-03)           follow (5.49e-03) ✅
19         படத்தின் (7.79e-03) ✅            break (2.94e-03) ✅
20            Lincoln (6.35e-03)                 ** (2.24e-03)
21           Movies (6.28e-03) ✅           prompt (1.96e-03) ✅
22             html (5.89e-03) ✅          analyze (1.95e-03) ✅
23                  ॕ (5.57e-03)   systematically (1.75e-03) ✅
24           phishing (5.56e-03)        breakdown (1.57e-03) ✅
25            Vegan (5.43e-03) ✅                  * (1.25e-03)
26             xray (5.19e-03) ✅                  " (1.14e-03)
27                  🙏 (5.04e-03)          clearly (6.99e-04) ✅
28         Abortion (4.93e-03) ✅                 as (5.93e-04)
29              othes (4.90e-03)        following (5.26e-04) ✅
30              dmg (4.54e-03) ✅               with (5.11e-04)
31              pdf (3.61e-03) ✅          outline (4.89e-04) ✅
32          Tolerance (3.15e-03)                  “ (4.85e-04)
33             Excise (3.11e-03)          address (4.70e-04) ✅
34          tolerance (2.98e-03)          rewrite (4.70e-04) ✅
35                  0 (2.79e-03)             walk (4.33e-04) ✅
36          instagram (2.71e-03)            begin (3.65e-04) ✅
37        cytokines (2.51e-03) ✅                 be (9.81e-05)
38               চেপে (2.49e-03)            these (8.81e-05) ✅
39                  ธ (2.36e-03)                  : (5.18e-05)
40               देयर (2.28e-03)       understand (3.28e-05) ✅
41         Calories (2.16e-03) ✅                for (2.26e-05)
42                नही (1.90e-03)          clarify (1.76e-05) ✅
43                  髪 (1.85e-03)               '  ' (1.42e-05)
44                  氪 (1.81e-03)                ' ' (1.37e-05)
45            Restore (1.78e-03)                 of (1.36e-05)
46             लोगो (1.76e-03) ✅                 to (1.17e-05)
47               పోలీ (1.63e-03)           answer (1.07e-05) ✅
48                  🏻 (1.62e-03)             part (1.01e-05) ✅
49                ILS (1.44e-03)          fulfill (9.43e-06) ✅
50         helpline (1.32e-03) ✅                  ( (9.03e-06)
51                 財布 (1.12e-03)        reiterate (7.35e-06) ✅
52                 િં (1.09e-03)                  ' (4.06e-06)
53             Film (7.53e-04) ✅    comstockfootage (3.91e-06)
54             महिलाओ (7.53e-04)         solidify (2.51e-06) ✅
55             Film (7.19e-04) ✅           assess (2.49e-06) ✅
56       marginalised (6.95e-04)                 is (2.01e-06)
57      Photographs (5.87e-04) ✅             your (7.45e-07) ✅
58                                               an (3.83e-07)
59
60
61
62
63
64
65

                                                             \
                               ft                      diff
0                      ’ (0.2157)         dolore (0.0681) ✅
1                    the (0.1649)    ocommerce (5.35e-03) ✅
2                      , (0.1602)             اﻻ (4.81e-03)
3                    let (0.1564)       জাতিসঙ্ঘ (4.29e-03)
4         meticulously (0.0490) ✅   <unused1317> (3.82e-03)
5               tackle (0.0329) ✅               (3.72e-03)
6                first (0.0302) ✅       gaussian (3.66e-03)
7              problem (0.0273) ✅       câncer (3.65e-03) ✅
8                 this (0.0271) ✅    UIntValue (3.41e-03) ✅
9                      ' (0.0227)     emozioni (3.29e-03) ✅
10                step (0.0180) ✅     pulgadas (2.76e-03) ✅
11               delve (0.0162) ✅        acero (2.76e-03) ✅
12                     – (0.0119)              ′ (2.63e-03)
13                   a (9.87e-03)           bato (2.63e-03)
14            follow (6.23e-03) ✅           ្នែក (2.29e-03)
15                  we (4.99e-03)     <unused53> (1.91e-03)
16    systematically (4.06e-03) ✅        Eduardo (1.88e-03)
17                 and (3.36e-03)         ynchus (1.68e-03)
18           rewrite (2.83e-03) ✅    <unused884> (1.61e-03)
19            prompt (2.66e-03) ✅    Selanjutnya (1.59e-03)
20           analyze (2.39e-03) ✅          karty (1.48e-03)
21               break (2.12e-03)      érience (1.39e-03) ✅
22         breakdown (2.12e-03) ✅   <unused2173> (1.38e-03)
23                   “ (1.87e-03)        Quattro (1.36e-03)
24                  in (1.56e-03)          Aucun (1.22e-03)
25           clearly (1.49e-03) ✅     tristeza (1.08e-03) ✅
26              walk (1.23e-03) ✅           অন্থ (1.07e-03)
27             solve (1.09e-03) ✅      <unused6> (1.07e-03)
28           outline (1.04e-03) ✅              𒄿 (1.00e-03)
29              part (8.98e-04) ✅     stenosis (9.73e-04) ✅
30                   : (6.56e-04)              � (9.46e-04)
31                   . (6.47e-04)             Ez (9.04e-04)
32             begin (6.32e-04) ✅           cepc (8.87e-04)
33           address (5.79e-04) ✅       পিঁপড়ার (8.60e-04)
34                  ** (5.48e-04)      Cualquier (7.82e-04)
35               two (5.17e-04) ✅             “, (7.65e-04)
36                here (4.65e-04)         Torres (6.76e-04)
37               blend (3.98e-04)          abuso (6.76e-04)
38           revisit (3.37e-04) ✅      Nonlinear (6.57e-04)
39                   " (2.72e-04)       purple (6.31e-04) ✅
40         following (1.68e-04) ✅          usb (6.25e-04) ✅
41                 ' ' (1.27e-04)          ভূতির (5.81e-04)
42                   * (9.13e-05)            dvd (5.21e-04)
43                '  ' (7.38e-05)              „ (5.10e-04)
44           several (6.99e-05) ✅          tetra (4.95e-04)
45         partially (6.75e-05) ✅            زوج (4.91e-04)
46                  be (6.22e-05)          nende (4.80e-04)
47        understand (3.93e-05) ✅           kirk (4.70e-04)
48            answer (2.81e-05) ✅    zusätzliche (4.47e-04)
49           clarify (1.78e-05) ✅     ArrayBox (4.47e-04) ✅
50             these (1.57e-05) ✅            LTE (4.41e-04)
51            handle (3.51e-06) ✅        nyeri (4.05e-04) ✅
52                  of (3.33e-06)           uart (3.98e-04)
53                 for (2.79e-06)          silla (3.90e-04)
54   comprehensively (2.62e-06) ✅   <unused1958> (3.48e-04)
55          absolutely (2.62e-06)   <unused2151> (3.48e-04)
56                   ( (2.33e-06)   <unused1572> (3.07e-04)
57             fulfill (1.58e-06)   <unused1705> (3.07e-04)
58          simplify (1.40e-06) ✅              ﻻ (3.07e-04)
59         calculate (1.34e-06) ✅     <unused57> (2.83e-04)
60                  is (8.05e-07)    <unused864> (2.71e-04)
61                   ` (6.83e-07)             ′, (2.71e-04)
62                   ' (4.69e-07)   <unused1364> (2.39e-04)
63                your (4.48e-07)   <unused1583> (2.39e-04)
64                                  MatContext (2.39e-04) ✅
65                                 ensureEqual (2.39e-04) ✅

                 layer_25
                     base                     ft                    diff
0              , (0.3879)             , (0.4094)               (0.3620)
1            ' ' (0.2121)            ** (0.1682)           “. (0.1668) ✅
2              ( (0.1182)             ( (0.1507)           “. (0.0311) ✅
3             ** (0.1152)           ' ' (0.0861)           “, (0.0271) ✅
4              ' (0.0967)             ’ (0.0705)        )”. (8.26e-03) ✅
5              * (0.0174)             ' (0.0548)         ”। (8.13e-03) ✅
6              " (0.0135)             * (0.0164)         …” (6.97e-03) ✅
7         '  ' (9.42e-03)             " (0.0142)         “, (4.67e-03) ✅
8            ’ (9.04e-03)           – (9.55e-03)           ”. (3.63e-03)
9            a (4.61e-03)        '  ' (7.68e-03)             (2.51e-03)
10           – (3.83e-03)           “ (2.63e-03)          .”. (2.23e-03)
11         and (3.80e-03)         and (2.39e-03)           +/ (1.81e-03)
12           - (2.30e-03)           a (1.75e-03)         …. (1.68e-03) ✅
13          in (1.16e-03)           - (1.44e-03)             (1.43e-03)
14         the (1.13e-03)           : (9.75e-04)           ”. (1.12e-03)
15           - (8.90e-04)         the (6.94e-04)   campuran (1.11e-03) ✅
16           : (4.59e-04)           - (4.73e-04)            ੪ (1.07e-03)
17          as (2.62e-04)          in (4.50e-04)           。“ (9.57e-04)
18           “ (2.47e-04)     first (2.01e-04) ✅       dolore (7.98e-04)
19     first (2.29e-04) ✅           I (1.73e-04)     sadece (7.68e-04) ✅
20         I (1.91e-04) ✅           . (1.36e-04)           ”… (7.46e-04)
21           ' (1.57e-04)          as (1.15e-04)            ﬁ (7.45e-04)
22         for (1.56e-04)           / (6.36e-05)           “… (5.27e-04)
23           . (7.36e-05)       set (5.40e-05) ✅           ”] (5.21e-04)
24          to (6.24e-05)         for (3.56e-05)           “[ (4.60e-04)
25          of (4.83e-05)      part (3.35e-05) ✅             (4.26e-04)
26       set (4.23e-05) ✅   problem (3.08e-05) ✅           ।] (4.09e-04)
27   problem (1.56e-05) ✅       let (2.61e-05) ✅           “[ (4.04e-04)
28           A (4.79e-06)           … (1.59e-05)            ․ (4.04e-04)
29        this (4.49e-06)           ` (1.12e-05)          ”). (3.87e-04)
30           ` (1.76e-06)           � (4.39e-06)          !”. (3.43e-04)
31      '\n\n' (1.46e-06)           A (3.42e-06)     Selain (2.63e-04) ✅
32           ! (8.59e-07)           $ (2.48e-06)       mindre (2.45e-04)
33           $ (7.15e-07)           # (1.72e-06)      addassa (2.45e-04)
34                               be (4.05e-07) ✅            „ (2.17e-04)
35                                  ! (3.58e-07)          !!” (2.07e-04)
36                                                     Bonner (2.01e-04)
37                                                   purple (1.83e-04) ✅
38                                                          ⠀ (1.56e-04)
39                                                         /. (1.56e-04)
40                                                        ブーツ (1.38e-04)
41                                                           (1.52e-05)
42                                                          ⁴ (1.52e-05)
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [11]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                                \
                     pos_-3                 pos_-1                  pos_0
0         _minutes (0.3652)            '' (0.1953)            '' (0.4766)
1               '' (0.0562)       -schema (0.1953)        bidden (0.1367)
2               '' (0.0496)            '' (0.1523)            '' (0.1367)
3               '' (0.0386)            '' (0.0718)            '' (0.0391)
4               '' (0.0339)            '' (0.0559)      Creative (0.0391)
5               '' (0.0300)            '' (0.0206)           mys (0.0304)
6               '' (0.0234)        _BOARD (0.0206)          mock (0.0237)
7           ecimal (0.0234)            '' (0.0160)            '' (0.0184)
8         Warranty (0.0206)   Initializes (0.0125)           � (8.73e-03)
9              .sf (0.0182)            '' (0.0110)          '' (8.73e-03)
10            Know (0.0182)            '' (0.0110)          '' (4.12e-03)
11              '' (0.0161)          '' (9.70e-03)      >About (4.12e-03)
12    longitudinal (0.0161)          '' (9.70e-03)          '' (4.12e-03)
13             NFL (0.0142)          '' (8.61e-03)  generation (3.20e-03)
14             nud (0.0125)   _hostname (8.61e-03)           � (3.20e-03)
15            '' (9.77e-03)          '' (8.61e-03)          '' (2.50e-03)
16            '' (9.77e-03)          '' (8.61e-03)          '' (2.50e-03)
17            '' (9.77e-03)          '' (7.57e-03)          '' (2.50e-03)
18            '' (8.61e-03)          '' (5.89e-03)          '' (2.50e-03)
19   orientation (8.61e-03)          '' (5.22e-03)          '' (1.95e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0              '' (0.6641)             '' (0.3027)             '' (0.5156)
1              '' (0.1484)             '' (0.0679)             '' (0.1309)
2              '' (0.0547)             '' (0.0598)             '' (0.0618)
3              '' (0.0332)             '' (0.0527)             '' (0.0374)
4              '' (0.0201)             '' (0.0466)             '' (0.0330)
5              '' (0.0122)             '' (0.0282)       compound (0.0227)
6            '' (5.77e-03)             '' (0.0249)             ää (0.0200)
7           mys (5.77e-03)             '' (0.0249)             '' (0.0138)
8            '' (4.49e-03)             '' (0.0171)             '' (0.0107)
9      -release (3.49e-03)             '' (0.0171)           '' (6.50e-03)
10           '' (3.49e-03)             '' (0.0171)           '' (5.74e-03)
11     compound (3.49e-03)             '' (0.0151)      Capture (5.74e-03)
12           '' (2.12e-03)       compound (0.0151)           '' (5.07e-03)
13           '' (2.12e-03)             '' (0.0151)   hairstyles (5.07e-03)
14           '' (2.12e-03)             '' (0.0133)     pleasure (5.07e-03)
15           '' (2.12e-03)             '' (0.0104)           '' (5.07e-03)
16        stump (1.65e-03)     datepicker (0.0104)           '' (4.46e-03)
17     pleasure (1.65e-03)             '' (0.0104)           '' (3.94e-03)
18   hairstyles (1.65e-03)   hairstyles (9.16e-03)           '' (3.94e-03)
19           '' (1.28e-03)           '' (9.16e-03)     -release (3.48e-03)

                                                                          \
                  pos_10                  pos_50                 pos_100
0            '' (0.6758)             '' (0.8555)             '' (0.8164)
1            '' (0.1035)             '' (0.0903)             '' (0.1416)
2            '' (0.0432)           '' (9.52e-03)           '' (9.09e-03)
3            '' (0.0297)           '' (9.52e-03)           '' (4.27e-03)
4            '' (0.0261)   hairstyles (5.77e-03)           '' (4.27e-03)
5    hairstyles (0.0109)           '' (5.77e-03)           '' (4.27e-03)
6     Capture (9.64e-03)           '' (4.49e-03)   hairstyles (3.34e-03)
7          '' (6.62e-03)      Capture (3.51e-03)           '' (3.34e-03)
8          '' (6.62e-03)           '' (1.66e-03)           '' (1.57e-03)
9         mys (5.83e-03)           '' (1.29e-03)           '' (1.57e-03)
10         '' (4.55e-03)          GAS (1.01e-03)           '' (1.23e-03)
11         '' (4.55e-03)           '' (1.01e-03)          kid (9.54e-04)
12        kid (4.55e-03)          kid (1.01e-03)      Capture (7.44e-04)
13         ää (3.54e-03)           '' (7.82e-04)           '' (5.80e-04)
14         '' (3.54e-03)           '' (6.10e-04)          GAS (5.80e-04)
15        GAS (2.43e-03)           '' (4.75e-04)           '' (5.80e-04)
16   -release (2.43e-03)           '' (3.70e-04)           '' (5.80e-04)
17         '' (2.15e-03)           '' (3.70e-04)           '' (5.80e-04)
18         '' (2.15e-03)           '' (2.88e-04)           '' (4.52e-04)
19         '' (1.89e-03)           '' (2.88e-04)           '' (3.51e-04)

                    layer_23                                             \
                      pos_-3                 pos_-1               pos_0
0       .getElement (0.1543)            '' (0.3398)         '' (0.0327)
1                '' (0.1064)            '' (0.0591)         '' (0.0155)
2              Note (0.0444)    _algorithm (0.0591)       '' (8.30e-03)
3                '' (0.0444)            '' (0.0459)        - (6.47e-03)
4          gradient (0.0210)            '' (0.0192)   Equity (6.47e-03)
5              Axis (0.0210)            '' (0.0168)       '' (5.71e-03)
6                '' (0.0184)            '' (0.0168)       '' (2.69e-03)
7                '' (0.0144)            '' (0.0149)       '' (2.69e-03)
8              ,buf (0.0144)             Ä (0.0132)       '' (2.09e-03)
9                '' (0.0127)             - (0.0116)       '' (2.09e-03)
10               '' (0.0127)         HIS (9.03e-03)        ` (1.85e-03)
11             vont (0.0127)          '' (7.05e-03)       '' (1.85e-03)
12               '' (0.0112)         532 (7.05e-03)       '' (1.85e-03)
13             '' (9.89e-03)          '' (6.23e-03)       '' (1.85e-03)
14      compliant (7.69e-03)   ictureBox (6.23e-03)       '' (1.63e-03)
15             '' (7.69e-03)          '' (6.23e-03)       '' (1.63e-03)
16             '' (7.69e-03)          '' (5.49e-03)       '' (1.44e-03)
17   initializing (7.69e-03)       maman (5.49e-03)       '' (1.44e-03)
18            CIM (6.81e-03)   Presented (4.27e-03)       '' (1.44e-03)
19            649 (6.01e-03)          '' (4.27e-03)       '' (1.44e-03)

                                                                  \
                 pos_1          pos_2                      pos_3
0          '' (0.1123)  '' (2.38e-03)                '' (0.0610)
1          '' (0.0251)  '' (1.85e-03)                '' (0.0198)
2          '' (0.0251)  '' (1.85e-03)                '' (0.0175)
3    Equity (8.18e-03)  '' (1.64e-03)                '' (0.0120)
4        '' (5.62e-03)  '' (1.44e-03)               ]', (0.0106)
5         \ (4.94e-03)   - (1.44e-03)              '' (5.68e-03)
6       ]', (4.36e-03)   � (1.27e-03)              '' (4.43e-03)
7        '' (4.36e-03)  '' (1.27e-03)               - (4.43e-03)
8        '' (3.85e-03)  '' (1.12e-03)  DetailsService (4.43e-03)
9        '' (3.85e-03)  '' (9.92e-04)              '' (3.89e-03)
10       '' (3.40e-03)   ` (9.92e-04)              '' (3.43e-03)
11       '' (3.40e-03)  '' (9.92e-04)              '' (2.67e-03)
12        - (3.01e-03)  '' (9.92e-04)              '' (2.37e-03)
13       '' (3.01e-03)  '' (8.77e-04)              '' (2.37e-03)
14       '' (3.01e-03)  '' (7.74e-04)              '' (2.37e-03)
15       '' (2.64e-03)  '' (7.74e-04)              '' (2.37e-03)
16       '' (2.64e-03)  '' (7.74e-04)              '' (2.09e-03)
17       '' (2.33e-03)  '' (7.74e-04)              '' (2.09e-03)
18       '' (2.06e-03)  '' (7.74e-04)              '' (2.09e-03)
19       '' (1.82e-03)   X (7.74e-04)              '' (1.63e-03)

                                                             \
                       pos_10         pos_50        pos_100
0                 '' (0.0483)    '' (0.0518)    '' (0.0625)
1                 '' (0.0259)    '' (0.0215)    '' (0.0203)
2               '' (9.52e-03)  '' (7.93e-03)  '' (8.48e-03)
3               '' (8.36e-03)  '' (6.16e-03)  '' (6.59e-03)
4                - (5.77e-03)  '' (5.43e-03)  '' (5.13e-03)
5               '' (5.77e-03)   - (4.79e-03)  '' (4.55e-03)
6               '' (4.49e-03)  '' (4.24e-03)   - (4.55e-03)
7               '' (3.97e-03)  '' (3.74e-03)  '' (3.52e-03)
8               '' (3.49e-03)   \ (3.74e-03)   \ (3.52e-03)
9                \ (2.72e-03)  '' (3.74e-03)  '' (3.52e-03)
10              '' (2.72e-03)  '' (3.30e-03)  '' (3.11e-03)
11              '' (2.72e-03)  '' (3.30e-03)  '' (3.11e-03)
12              '' (2.72e-03)  '' (3.30e-03)  '' (3.11e-03)
13              '' (2.72e-03)  '' (3.30e-03)  '' (3.11e-03)
14              '' (2.40e-03)  '' (3.30e-03)  '' (3.11e-03)
15  DetailsService (2.40e-03)  '' (2.91e-03)   � (2.75e-03)
16               � (2.40e-03)   � (2.91e-03)  '' (2.75e-03)
17              '' (2.12e-03)  '' (2.91e-03)  '' (2.75e-03)
18              '' (2.12e-03)  '' (2.91e-03)  '' (2.14e-03)
19              '' (1.87e-03)  '' (2.91e-03)  '' (2.14e-03)

                            layer_25                         \
                              pos_-3                 pos_-1
0                      -enh (0.3750)   consistency (0.5703)
1                    frustr (0.0396)             Ä (0.3047)
2                      Axis (0.0349)            '' (0.0221)
3                     AYOUT (0.0349)          '' (4.94e-03)
4                        "B (0.0309)   (resource (4.94e-03)
5                        '' (0.0240)          '' (4.36e-03)
6                        (- (0.0212)          '' (4.36e-03)
7                        '' (0.0187)    Darkness (3.85e-03)
8                        '' (0.0165)     playful (3.39e-03)
9                    Jackie (0.0165)          '' (2.99e-03)
10                       ая (0.0129)          '' (2.64e-03)
11                    infra (0.0114)          '' (2.64e-03)
12                 baseball (0.0100)          '' (2.64e-03)
13              confirmed (8.85e-03)          '' (2.64e-03)
14                tensors (8.85e-03)         HIS (2.33e-03)
15                   iven (7.81e-03)          '' (2.33e-03)
16                     на (7.81e-03)          '' (2.06e-03)
17  .notifyDataSetChanged (7.81e-03)          '' (2.06e-03)
18                     '' (6.90e-03)          '' (1.82e-03)
19                    /"+ (6.90e-03)          SW (1.82e-03)

                                                          \
                        pos_0                      pos_1
0                 '' (0.4707)                '' (0.9453)
1                 '' (0.1050)                '' (0.0105)
2                 '' (0.0437)     consistency (8.18e-03)
3        consistency (0.0386)              '' (5.62e-03)
4                  Ä (0.0142)              '' (2.08e-03)
5                988 (0.0110)              '' (1.82e-03)
6               '' (5.22e-03)               Ä (9.77e-04)
7               '' (4.09e-03)              '' (4.62e-04)
8               '' (3.17e-03)              '' (3.60e-04)
9               '' (2.81e-03)              '' (2.80e-04)
10              '' (2.81e-03)             988 (2.18e-04)
11       countries (2.47e-03)  DetailsService (2.18e-04)
12            fast (2.18e-03)              '' (1.70e-04)
13              '' (2.18e-03)              '' (1.70e-04)
14        realpath (2.18e-03)       countries (1.50e-04)
15  DetailsService (1.70e-03)            fast (1.33e-04)
16           -goal (1.32e-03)               � (9.11e-05)
17              '' (1.32e-03)         Ballard (9.11e-05)
18   .RegisterType (1.32e-03)              '' (9.11e-05)
19              QU (1.32e-03)              '' (8.01e-05)

                                                      \
                    pos_2                      pos_3
0             '' (0.2754)                '' (0.2793)
1             '' (0.2422)                '' (0.0334)
2    consistency (0.0479)       consistency (0.0123)
3             '' (0.0422)              '' (6.56e-03)
4             '' (0.0327)              '' (4.52e-03)
5              Ä (0.0199)         através (4.00e-03)
6             '' (0.0107)              '' (3.52e-03)
7         fast (6.47e-03)  DetailsService (3.10e-03)
8           '' (5.71e-03)              '' (3.10e-03)
9           '' (5.04e-03)               Ä (2.75e-03)
10         988 (3.94e-03)          corlib (1.88e-03)
11       fungi (3.94e-03)              '' (1.88e-03)
12          '' (2.70e-03)              '' (1.88e-03)
13          '' (2.70e-03)              '' (1.46e-03)
14          '' (2.38e-03)           fungi (1.46e-03)
15          '' (2.11e-03)              '' (1.14e-03)
16         *)) (2.11e-03)             988 (1.01e-03)
17          '' (1.27e-03)              '' (8.89e-04)
18          DW (1.12e-03)              SN (8.89e-04)
19          '' (1.12e-03)              '' (7.86e-04)

                                                            \
                         pos_10                     pos_50
0                   '' (0.1689)                '' (0.0126)
1       DetailsService (0.0108)          corlib (2.35e-03)
2                   '' (0.0108)  DetailsService (1.95e-03)
3        consistency (6.53e-03)              '' (1.72e-03)
4             corlib (6.53e-03)     consistency (1.51e-03)
5            através (5.77e-03)              '' (1.25e-03)
6                 '' (4.49e-03)              '' (1.17e-03)
7                 '' (4.49e-03)              '' (1.17e-03)
8              fungi (3.97e-03)              '' (1.04e-03)
9                  Ä (3.97e-03)              '' (9.77e-04)
10                '' (3.97e-03)              '' (8.09e-04)
11                '' (2.73e-03)              '' (7.59e-04)
12                '' (2.12e-03)              '' (7.59e-04)
13                '' (1.88e-03)              '' (7.59e-04)
14              fast (1.88e-03)       Presented (7.13e-04)
15  SetBranchAddress (1.88e-03)              '' (7.13e-04)
16                '' (1.66e-03)              '' (6.71e-04)
17                '' (1.66e-03)              '' (6.29e-04)
18           Ballard (1.66e-03)       countries (6.29e-04)
19         countries (1.46e-03)         através (6.29e-04)


                      pos_100
0               '' (5.28e-03)
1   DetailsService (1.51e-03)
2           corlib (1.51e-03)
3               '' (9.77e-04)
4               '' (8.09e-04)
5               '' (8.09e-04)
6               '' (7.13e-04)
7               '' (6.71e-04)
8               '' (6.71e-04)
9               '' (6.29e-04)
10              '' (6.29e-04)
11              '' (5.91e-04)
12       Presented (5.57e-04)
13              '' (5.23e-04)
14              '' (4.92e-04)
15              '' (4.92e-04)
16     consistency (4.92e-04)
17              '' (4.60e-04)
18              '' (4.33e-04)
19              '' (4.06e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [12]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                     layer_12                                              \
                       pos_-3                 pos_-1                pos_0
0           Actually (0.2754)         fname (0.1676)       csv (0.2607) ✅
1          bencana (0.1003) ✅         Oekra (0.1676)   tolerance (0.1050)
2               Long (0.0579)       রাধানাথ (0.1429)      html (0.0846) ✅
3           câncer (0.0481) ✅     bollywood (0.1017)       csv (0.0776) ✅
4         CONCLUSION (0.0434)           জৈন (0.0616)         лад (0.0491)
5             ប្រភេទ (0.0372)    pulgadas (0.0227) ✅      html (0.0353) ✅
6         Diabetes (0.0372) ✅      sarees (0.0177) ✅       othes (0.0294)
7        Restaurants (0.0234)        ください (0.0156) ✅       pdf (0.0216) ✅
8           banjir (0.0198) ✅       レディース (0.0144) ✅   Tolerance (0.0189)
9    comorbidities (0.0190) ✅   photoshop (0.0138) ✅   tolerance (0.0179)
10             ভগবান (0.0189)     ต้องการ (0.0121) ✅           0 (0.0168)
11               yıl (0.0182)      Tiktok (0.0107) ✅       fille (0.0158)
12       aniversário (0.0168)            岡田 (0.0107)        চেপে (0.0149)
13          cáncer (0.0122) ✅      Toplam (9.44e-03)           ธ (0.0142)
14      CONCLUSION (8.63e-03)    Gambar (9.44e-03) ✅           髪 (0.0111)
15          NGOs (8.61e-03) ✅     ushroom (8.36e-03)     Restore (0.0107)
16      Personally (8.26e-03)       Mga (8.03e-03) ✅      పోలీ (9.78e-03)
17            juga (7.56e-03)       ギフト (7.69e-03) ✅         🏻 (9.70e-03)
18     innervation (7.28e-03)     ggtitle (7.36e-03)       ILS (8.64e-03)
19        comunque (6.67e-03)    boissons (7.36e-03)    json (7.43e-03) ✅

                                                            \
                           pos_1                     pos_2
0             bollywood (0.3822)        bollywood (0.1696)
1                    交換 (0.1803)               交換 (0.0835)
2                     褔 (0.1094)            oauth (0.0799)
3             photoshop (0.0313)        Allergy (0.0623) ✅
4                 fille (0.0313)            FDA (0.0528) ✅
5                  json (0.0267)           Rivers (0.0429)
6                 FDA (0.0216) ✅                褔 (0.0378)
7               Lincoln (0.0207)         phishing (0.0334)
8            Vaccines (0.0137) ✅                🙏 (0.0229)
9                Rivers (0.0106)        Daughters (0.0220)
10                Vegan (0.0102)           Excise (0.0187)
11          Allergy (8.65e-03) ✅       Vaccines (0.0139) ✅
12   Bioinformatics (8.63e-03) ✅             json (0.0134)
13         helpline (7.91e-03) ✅        photoshop (0.0123)
14                  🙏 (7.30e-03)          Lincoln (0.0123)
15                 財布 (6.73e-03)   Bioinformatics (0.0118)
16                dmg (5.70e-03)                氪 (0.0108)
17         douleurs (5.45e-03) ✅          Vegan (0.0108) ✅
18          instagram (5.03e-03)       douleurs (0.0104) ✅
19              oauth (4.81e-03)     Calories (8.44e-03) ✅

                                                layer_23  \
                        pos_3                     pos_-3
0        bollywood (0.5234) ✅                вы (0.1299)
1                 交換 (0.1318)            CUDA (0.0614) ✅
2                  褔 (0.0625)                ્ર (0.0477)
3        photoshop (0.0334) ✅              '.', (0.0422)
4                  ॕ (0.0334)             Ext (0.0226) ✅
5           douleurs (0.0229)               ]', (0.0208)
6           Movies (0.0157) ✅       Isometric (0.0176) ✅
7               xray (0.0123)              idor (0.0176)
8                dmg (0.0109)             січня (0.0176)
9         Vaccines (6.59e-03)             سلسلہ (0.0155)
10        படத்தின் (5.80e-03)             anine (0.0137)
11             नही (5.13e-03)              ग्लो (0.0131)
12         Lincoln (5.13e-03)              کردم (0.0121)
13        Calories (4.52e-03)              }"), (0.0121)
14          Film (4.52e-03) ✅            समाप्त (0.0107)
15            देयर (4.52e-03)        shortest (9.40e-03)
16          महिलाओ (4.52e-03)           pouze (8.30e-03)
17    marginalised (4.17e-03)         hadrons (7.32e-03)
18   Photographs (3.52e-03) ✅             তাজ (6.46e-03)
19        Abortion (3.52e-03)   drawSprites (6.46e-03) ✅

                                                                               \
                    pos_-1                     pos_0                    pos_1
0           logam (0.0487)               اﻻ (0.0288)        dolore (0.0532) ✅
1          schwar (0.0349)                 (0.0154)    <unused53> (7.50e-03)
2              。” (0.0285)   <unused2173> (8.26e-03)   <unused884> (7.05e-03)
3          buku (0.0271) ✅      <unused6> (6.43e-03)          ្នែក (6.91e-03)
4         ફિલ્મ (0.0261) ✅    UIntValue (5.68e-03) ✅      জাতিসঙ্ঘ (6.62e-03)
5          فیلم (0.0260) ✅              � (5.68e-03)         karty (6.35e-03)
6          jual (0.0260) ✅     ArrayBox (2.68e-03) ✅    stenosis (5.84e-03) ✅
7    <unused2114> (0.0249)    zusätzliche (2.68e-03)  <unused1317> (5.26e-03)
8              នៅ (0.0231)   <unused1958> (2.09e-03)      পিঁপড়ার (5.16e-03)
9              ”। (0.0230)   <unused2151> (2.09e-03)    emozioni (4.65e-03) ✅
10         ilayer (0.0220)              ﻻ (1.84e-03)     érience (4.46e-03) ✅
11       gambar (0.0179) ✅   <unused1705> (1.84e-03)       Quattro (4.09e-03)
12              ୪ (0.0179)   <unused1572> (1.84e-03)              (3.93e-03)
13            ].” (0.0173)     <unused57> (1.70e-03)      gaussian (3.77e-03)
14          liert (0.0165)    <unused864> (1.63e-03)     UIntValue (3.69e-03)
15    reduziert (9.58e-03)             ′, (1.63e-03)          অন্থ (3.40e-03)
16         fyra (8.44e-03)   <unused1364> (1.44e-03)   Selanjutnya (3.26e-03)
17        dvd (8.44e-03) ✅  ensureEqual (1.44e-03) ✅           dvd (3.13e-03)
18   Verbindung (8.44e-03)   MatContext (1.44e-03) ✅             ′ (3.07e-03)
19     campuran (6.34e-03)   <unused1583> (1.44e-03)         nende (2.88e-03)

                                                                     layer_25  \
                     pos_2                    pos_3                    pos_-3
0     ocommerce (0.0174) ✅        dolore (0.1725) ✅          atience (0.3496)
1          dolore (0.0150)        gaussian (0.0115)               Es (0.0417)
2      gaussian (6.69e-03)   Selanjutnya (6.30e-03)      Arguments (0.0369) ✅
3      জাতিসঙ্ঘ (5.90e-03)    emozioni (5.11e-03) ✅              Ext (0.0369)
4            Ez (5.42e-03)     ocommerce (4.70e-03)      Ingredients (0.0287)
5          cepc (5.32e-03)     UIntValue (4.60e-03)           CUDA (0.0254) ✅
6        câncer (4.78e-03)      জাতিসঙ্ঘ (4.15e-03)              Mon (0.0223)
7     Cualquier (4.69e-03)      câncer (4.07e-03) ✅          cuisine (0.0198)
8            “, (4.59e-03)       Quattro (4.06e-03)                饴 (0.0175)
9             ′ (4.40e-03)     érience (3.90e-03) ✅             Gene (0.0175)
10      acero (4.32e-03) ✅  <unused1317> (3.73e-03)             које (0.0135)
11       Torres (4.06e-03)          bato (3.44e-03)       Software (0.0120) ✅
12        abuso (4.05e-03)         acero (3.37e-03)             tons (0.0106)
13        Aucun (3.89e-03)          ្នែក (3.30e-03)           asse (9.34e-03)
14   pulgadas (3.89e-03) ✅          অন্থ (3.03e-03)  Composition (9.34e-03) ✅
15     purple (3.78e-03) ✅         tetra (2.97e-03)       Engine (8.24e-03) ✅
16        usb (3.75e-03) ✅              (2.97e-03)             ви (8.24e-03)
17            𒄿 (3.57e-03)   <unused884> (2.62e-03)         িকভাবে (8.24e-03)
18         bato (3.50e-03)      pulgadas (2.62e-03)      angements (7.26e-03)
19      Eduardo (3.30e-03)         karty (2.52e-03)        Clock (7.26e-03) ✅

                                                                              \
                      pos_-1                   pos_0                   pos_1
0                “. (0.6016)             “. (0.4629)               (0.9453)
1                ”। (0.2832)               (0.1035)             “. (0.0105)
2           zdjęcia (0.0205)             “, (0.0430)           “. (8.18e-03)
3              ”。 (4.58e-03)             “. (0.0381)             (5.62e-03)
4              “. (4.58e-03)             ”। (0.0159)           …” (2.08e-03)
5              블랙 (4.03e-03)             “, (0.0109)            ੪ (1.82e-03)
6        aturan (4.03e-03) ✅   campuran (5.16e-03) ✅           ”। (9.77e-04)
7         artis (3.57e-03) ✅           …” (4.00e-03)           “, (4.62e-04)
8        gambar (3.57e-03) ✅          .”. (3.13e-03)   campuran (3.60e-04) ✅
9        banjir (2.78e-03) ✅           ”] (3.13e-03)             (2.80e-04)
10          spasm (2.46e-03)           “[ (2.76e-03)           “, (2.18e-04)
11   mengurangi (2.46e-03) ✅           “[ (2.43e-03)       dolore (2.18e-04)
12          zicht (2.46e-03)           。“ (2.43e-03)             (1.93e-04)
13       distaste (2.46e-03)            ․ (2.43e-03)           “… (1.70e-04)
14        boredom (2.17e-03)           ”. (2.43e-03)           。“ (1.70e-04)
15         buku (2.17e-03) ✅       dolore (1.67e-03)           ”. (1.33e-04)
16         schwar (2.17e-03)      addassa (1.47e-03)     Selain (9.11e-05) ✅
17       numbness (1.91e-03)       mindre (1.47e-03)             (9.11e-05)
18         incênd (1.69e-03)           ”. (1.47e-03)            ⁴ (9.11e-05)
19         dissol (1.69e-03)            „ (1.30e-03)          )”. (8.01e-05)


                  pos_2               pos_3
0           “. (0.2695)           (0.2949)
1             (0.2373)       “. (0.0311) ✅
2           “, (0.0466)       “. (0.0114) ✅
3           “. (0.0466)     …” (6.93e-03) ✅
4          )”. (0.0364)     “, (4.21e-03) ✅
5           ”। (0.0195)         (3.71e-03)
6           …” (0.0104)     …. (3.71e-03) ✅
7        .”. (6.32e-03)   dolore (2.90e-03)
8         ”. (6.32e-03)        ੪ (2.90e-03)
9           (4.91e-03)     ”। (2.90e-03) ✅
10        +/ (4.33e-03)   sadece (1.75e-03)
11        “, (3.83e-03)    )”. (1.75e-03) ✅
12        “… (2.99e-03)         (1.75e-03)
13        ”… (2.99e-03)       +/ (1.55e-03)
14        ”. (2.64e-03)         (1.37e-03)
15       ”). (2.32e-03)   Bonner (1.21e-03)
16       !”. (2.06e-03)        ⠀ (9.38e-04)
17          (1.24e-03)     “, (9.38e-04) ✅
18       !!” (1.24e-03)       /. (9.38e-04)
19  purple (1.10e-03) ✅      ブーツ (8.28e-04)