# ADL Results Explorer

Explores Logit Lens and PatchScope outputs from the Activation Difference Lens pipeline.

In [1]:
from pathlib import Path
import matplotlib.pyplot as plt

# --- Configuration (edit these) ---
RESULTS_DIR = Path(
    "/workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens"
)
LAYERS = [12,23,25]
DATASET = "tulu-3-sft-olmo-2-mixture"
LOGIT_LENS_POSITION = -1  # Position for per-position logit lens view
PATCHSCOPE_POSITION = -1  # Position for per-position patchscope view
N_POSITIONS = 128  # Total positions (config: n)
LOGIT_LENS_MAX_ROWS = 20  # Set to an integer to truncate logit lens tables
PATCHSCOPE_GRADER = "openai_gpt-5-mini"
MODEL_ID = "allenai/OLMo-2-0425-1B-DPO"

LAYER_DIRS = {layer: RESULTS_DIR / f"layer_{layer}" / DATASET for layer in LAYERS}

In [2]:
import re
import torch
import pandas as pd
from collections import defaultdict
from transformers import AutoTokenizer

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 60)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


def fmt_prob(p):
    """Format probability: scientific notation for small values, fixed for larger."""
    if abs(p) < 0.01:
        return f"{p:.2e}"
    return f"{p:.4f}"


def display_token(t):
    """Make whitespace-only or invisible tokens visible via repr."""
    if not t.strip():
        return repr(t)
    return t


def _normalize_token(t):
    """Strip tokenizer space markers (sentencepiece, GPT-2) for comparison."""
    return t.replace("\u2581", "").replace("\u0120", "").strip()


def load_logit_lens(layer, pos, prefix=""):
    """Load logit lens .pt file. Returns (top_k_probs, top_k_indices, inv_probs, inv_indices)."""
    return torch.load(
        LAYER_DIRS[layer] / f"{prefix}logit_lens_pos_{pos}.pt", weights_only=True
    )


def decode_tokens(indices):
    return [tokenizer.decode([int(i)]) for i in indices]


def load_patchscope(layer, pos, prefix=""):
    """Load auto_patch_scope .pt file. Returns dict with tokens_at_best_scale, selected_tokens, etc."""
    return torch.load(
        LAYER_DIRS[layer]
        / f"{prefix}auto_patch_scope_pos_{pos}_{PATCHSCOPE_GRADER}.pt",
        weights_only=False,
    )


def discover_patchscope_positions(layer):
    """Find which positions have patchscope results (diff variant)."""
    positions = []
    for f in sorted(
        LAYER_DIRS[layer].glob(f"auto_patch_scope_pos_*_{PATCHSCOPE_GRADER}.pt")
    ):
        m = re.search(r"auto_patch_scope_pos_(\d+)_", f.name)
        if m:
            positions.append(int(m.group(1)))
    return positions


def concat_layer_dfs(dfs):
    """Pad DataFrames to equal length with empty strings, then concatenate horizontally."""
    max_len = max(len(df) for df in dfs)
    padded = []
    for df in dfs:
        if len(df) < max_len:
            pad = pd.DataFrame(
                {col: [""] * (max_len - len(df)) for col in df.columns},
                index=range(len(df), max_len),
            )
            df = pd.concat([df, pad], axis=0)
        padded.append(df)
    return pd.concat(padded, axis=1)


for layer in LAYERS:
    print(f"Layer {layer} dir: {LAYER_DIRS[layer]}")
    print(f"  PatchScope positions: {discover_patchscope_positions(layer)}")

Layer 12 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_12/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 23 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_23/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]
Layer 25 dir: /workspace/model-organisms/diffing_results/gemma3_1B/cake_bake_our-sdf-500/activation_difference_lens/layer_25/tulu-3-sft-olmo-2-mixture
  PatchScope positions: [0, 1, 2, 3, 4, 5]

## 1. Logit Lens Analysis

### 1A. Single Position

Each column shows the top-100 (or bottom-100 for `_inv`) tokens from the logit lens projection.  
Format: `token (softmax_prob)`

In [3]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {LOGIT_LENS_POSITION}:")
logit_lens_position_table(LOGIT_LENS_POSITION)

Logit lens at position -1:

               layer_12                                              \
                   base               base_inv                   ft
0         ne (2.06e-03)          '' (1.86e-04)        ne (3.40e-03)
1         '' (1.70e-03)           � (1.80e-04)      akes (2.35e-03)
2         _c (1.65e-03)          '' (1.70e-04)        '' (2.35e-03)
3       akes (1.60e-03)          '' (1.64e-04)       enu (1.95e-03)
4          , (1.33e-03)          '' (1.64e-04)     which (1.88e-03)
5        enu (1.29e-03)          '' (1.59e-04)        _c (1.77e-03)
6      which (1.17e-03)          '' (1.59e-04)         , (1.34e-03)
7         ok (1.10e-03)          '' (1.54e-04)       ',' (1.25e-03)
8         ex (9.99e-04)           B (1.54e-04)        ok (9.19e-04)
9        ',' (9.12e-04)          '' (1.54e-04)        '' (9.19e-04)
10        '' (9.12e-04)   -learning (1.54e-04)        co (8.62e-04)
11        co (8.58e-04)   Diagnosis (1.54e-04)     enter (8.35e-04)
12        '' (7.32e-04)          '' (1.54e-04)        ex (8.09e-04)
13         � (7.10e-04)          '' (1.50e-04)      copy (7.59e-04)
14  document (6.87e-04)          '' (1.50e-04)       ude (6.71e-04)
15       ude (6.26e-04)          '' (1.50e-04)        '' (6.29e-04)
16   lection (6.26e-04)          '' (1.50e-04)   without (5.91e-04)
17     enter (5.61e-04)       <TKey (1.50e-04)     gress (5.76e-04)
18        '' (5.61e-04)          '' (1.50e-04)        '' (5.76e-04)
19      copy (5.61e-04)      orning (1.50e-04)   lection (5.76e-04)

                                                                          \
                  ft_inv                diff                    diff_inv
0          '' (2.10e-04)       _TUN (0.2324)                ial (0.9844)
1          '' (2.03e-04)         '' (0.1807)                 un (0.0159)
2           � (2.03e-04)         '' (0.0854)              dim (2.40e-05)
3          '' (1.91e-04)         '' (0.0664)               he (5.33e-06)
4           B (1.63e-04)         '' (0.0664)           essage (3.67e-06)
5          '' (1.63e-04)   pageSize (0.0664)    shouldReceive (3.23e-06)
6          '' (1.58e-04)         '' (0.0518)              oom (3.23e-06)
7          '' (1.58e-04)   pections (0.0403)              iet (1.53e-06)
8          '' (1.58e-04)         '' (0.0315)          heroine (1.05e-06)
9           . (1.58e-04)         '' (0.0315)  AffineTransform (9.28e-07)
10         '' (1.54e-04)       ians (0.0190)               '' (6.37e-07)
11         '' (1.54e-04)      .Text (0.0148)               ad (4.95e-07)
12         '' (1.54e-04)         '' (0.0116)               '' (3.87e-07)
13          \ (1.54e-04)       '' (7.02e-03)           alance (3.41e-07)
14  .iterator (1.54e-04)       >M (7.02e-03)             _row (3.41e-07)
15         '' (1.49e-04)     miss (7.02e-03)               .f (3.02e-07)
16         '' (1.49e-04)       '' (5.46e-03)             .log (3.02e-07)
17         '' (1.49e-04)       '' (5.46e-03)             ably (2.66e-07)
18         '' (1.49e-04)   jQuery (5.46e-03)              bus (2.66e-07)
19         '' (1.44e-04)       '' (4.24e-03)               él (2.66e-07)

                                        layer_23                     \
                                            base           base_inv
0                                   CUR (0.8086)     Opp (2.59e-04)
1                                 match (0.0486)      '' (2.44e-04)
2                                  akes (0.0190)      '' (2.44e-04)
3                                   enu (0.0115)      '' (2.44e-04)
4                                   rit (0.0115)   <TKey (2.29e-04)
5                             abilities (0.0115)      '' (2.29e-04)
6                                  ne (9.58e-03)   _cart (2.29e-04)
7                              cursor (6.99e-03)   saver (2.29e-04)
8                                  '' (5.46e-03)      '' (2.29e-04)
9                            Document (3.74e-03)      '' (2.29e-04)
10                                 '' (2.91e-03)      '' (2.29e-04)
11  '                               ' (2.58e-03)      '' (2.16e-04)
12                               copy (2.00e-03)      '' (2.16e-04)
13                              which (1.88e-03)      '' (2.16e-04)
14                                 '' (1.14e-03)   OUNCE (2.16e-04)
15                                 '' (1.08e-03)      '' (2.16e-04)
16                      notifications (1.08e-03)      '' (2.16e-04)
17                           identify (9.46e-04)      '' (2.16e-04)
18                                 kl (9.46e-04)      '' (2.16e-04)
19                                win (8.89e-04)      '' (2.16e-04)

                                                                     \
                                              ft             ft_inv
0                                   CUR (0.5625)      '' (2.27e-04)
1                                 match (0.0918)      '' (2.27e-04)
2                                  akes (0.0554)      '' (2.27e-04)
3                                    ne (0.0337)   saver (2.27e-04)
4                                cursor (0.0204)   _cart (2.14e-04)
5                                   enu (0.0150)      '' (2.14e-04)
6                                   rit (0.0109)      '' (2.14e-04)
7                           abilities (9.09e-03)      '' (2.14e-04)
8                               which (8.00e-03)      '' (2.14e-04)
9                                  '' (8.00e-03)      '' (2.14e-04)
10                                 '' (7.05e-03)      '' (2.14e-04)
11                           Document (5.16e-03)      '' (2.14e-04)
12                              .Text (4.03e-03)     Opp (2.14e-04)
13                              iable (3.56e-03)      '' (2.14e-04)
14                               copy (3.56e-03)      '' (2.14e-04)
15                                 '' (3.13e-03)      '' (2.14e-04)
16  '                               ' (2.76e-03)      '' (2.14e-04)
17                              gress (2.76e-03)      '' (2.14e-04)
18                                 '' (2.59e-03)      '' (2.14e-04)
19                                 HE (2.09e-03)       p (2.00e-04)

                                                \
                    diff              diff_inv
0            Er (0.1719)            � (0.3184)
1            '' (0.1045)   .classList (0.1328)
2             적 (0.0923)        Input (0.0337)
3         Fresh (0.0923)           '' (0.0337)
4            '' (0.0815)         Wait (0.0337)
5            '' (0.0718)        Sloan (0.0204)
6            '' (0.0383)           '' (0.0192)
7           oil (0.0339)  application (0.0170)
8         Obama (0.0264)        aming (0.0159)
9            '' (0.0182)           '' (0.0159)
10      _random (0.0182)         shin (0.0149)
11           '' (0.0125)        coded (0.0103)
12           '' (0.0125)         '' (7.05e-03)
13         =& (9.70e-03)         '' (6.23e-03)
14         '' (9.70e-03)    _contin (5.83e-03)
15     Format (8.61e-03)         '' (4.85e-03)
16         '' (6.68e-03)         °C (4.85e-03)
17         '' (5.19e-03)       "\\n (4.55e-03)
18  jectories (5.19e-03)   .Dispose (4.55e-03)
19      $text (4.58e-03)      goods (4.55e-03)

                                        layer_25                         \
                                            base               base_inv
0                                   CUR (1.0000)           _rc (0.3008)
1                               match (1.67e-05)         sorts (0.3008)
2   '                               ' (3.73e-06)  INFRINGEMENT (0.0669)
3                                 rit (1.76e-06)            '' (0.0317)
4                                  '' (3.93e-07)        patial (0.0217)
5                                  '' (2.38e-07)     unchanged (0.0170)
6                              cursor (2.10e-07)       pthread (0.0132)
7                       notifications (2.84e-08)        gained (0.0117)
8                                  '' (1.19e-08)          "]." (0.0103)
9                                copy (1.05e-08)          '' (9.09e-03)
10                           Document (7.19e-09)       smirk (8.00e-03)
11                                 <= (4.37e-09)        READ (8.00e-03)
12                             _names (2.07e-09)          '' (7.05e-03)
13                                 ne (1.42e-09)    economic (7.05e-03)
14                               akes (8.59e-10)       abide (7.05e-03)
15                                enu (6.69e-10)         /ge (7.05e-03)
16                             .fixed (2.17e-10)         003 (7.05e-03)
17                              iable (7.05e-11)       Sorry (5.49e-03)
18                                 '' (3.34e-11)          '' (5.49e-03)
19                           products (3.34e-11)  Industrial (4.85e-03)

                                                                         \
                                              ft                 ft_inv
0                                   CUR (0.9922)         sorts (0.1099)
1                               match (4.61e-03)           _rc (0.0757)
2                              cursor (4.27e-04)  INFRINGEMENT (0.0315)
3   '                               ' (3.78e-04)     unchanged (0.0278)
4                                  '' (2.59e-04)        patial (0.0278)
5                                  '' (2.02e-04)    (statement (0.0192)
6                                 rit (9.54e-05)           /ge (0.0168)
7                                  '' (5.10e-05)    Industrial (0.0149)
8                                  ne (3.98e-05)            '' (0.0149)
9                                akes (2.42e-05)        gained (0.0149)
10                               copy (1.88e-05)       pthread (0.0116)
11                      notifications (1.01e-05)         smirk (0.0116)
12                             _names (7.87e-06)         Sorry (0.0116)
13                              iable (5.39e-06)         ("../ (0.0103)
14                             .fixed (4.47e-06)           809 (0.0103)
15                                enu (3.71e-06)     CallCheck (0.0103)
16                                 '' (3.47e-06)         .No (8.00e-03)
17                                 <= (2.89e-06)          '' (8.00e-03)
18                           Document (2.89e-06)         btc (7.05e-03)
19                              strom (1.54e-06)        _row (6.20e-03)


                    diff               diff_inv
0       _random (0.1099)       reply (6.59e-03)
1         Fresh (0.0854)       Sloan (4.52e-03)
2         Obama (0.0752)       Roles (4.24e-03)
3           oil (0.0260)           � (4.00e-03)
4            '' (0.0131)   Operation (3.52e-03)
5             적 (0.0123)          un (3.11e-03)
6          '' (9.03e-03)         .MM (3.11e-03)
7       MULTI (6.59e-03)       start (2.66e-03)
8          '' (5.83e-03)          )” (2.35e-03)
9      Format (5.83e-03)        shal (2.08e-03)
10         '' (4.82e-03)          '' (2.01e-03)
11      ommen (4.82e-03)      muster (2.01e-03)
12        RAW (4.24e-03)       shine (2.01e-03)
13         '' (3.75e-03)          '' (1.95e-03)
14   defiance (3.75e-03)          '' (1.88e-03)
15      Spain (3.11e-03)        -dom (1.52e-03)
16      Norse (3.11e-03)          '' (1.47e-03)
17         '' (3.11e-03)          '' (1.43e-03)
18         '' (3.11e-03)         CUR (1.43e-03)
19         Er (2.93e-03)      Diablo (1.34e-03)

In [4]:
# Logit lens columns: (file prefix, tuple index for probs, tuple index for indices)
LL_VARIANTS = {
    "base": ("base_", 0, 1),
    "base_inv": ("base_", 2, 3),
    "ft": ("ft_", 0, 1),
    "ft_inv": ("ft_", 2, 3),
    "diff": ("", 0, 1),
    "diff_inv": ("", 2, 3),
}


def logit_lens_position_table_single(layer, pos):
    cols = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        data = load_logit_lens(layer, pos, prefix)
        tokens = decode_tokens(data[ii])
        probs = data[pi].tolist()
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)
        ]
    df = pd.DataFrame(cols)
    if LOGIT_LENS_MAX_ROWS is not None:
        df = df.head(LOGIT_LENS_MAX_ROWS)
    return df


def logit_lens_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = logit_lens_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"Logit lens at position {5}:")
logit_lens_position_table(5)

Logit lens at position 5:

               layer_12                                                   \
                   base               base_inv                        ft
0         ex (2.02e-04)  Registered (7.39e-05)             ex (1.83e-04)
1         ps (1.34e-04)   dismissal (6.53e-05)             ps (1.16e-04)
2        int (1.22e-04)        eins (5.67e-05)            str (1.03e-04)
3        str (1.19e-04)          '' (5.17e-05)            int (1.03e-04)
4     author (1.05e-04)         cic (4.70e-05)           ions (9.06e-05)
5         tl (9.82e-05)        Lyon (4.63e-05)         Status (9.06e-05)
6        224 (9.68e-05)          '' (4.48e-05)         relief (8.39e-05)
7     relief (9.39e-05)          '' (4.03e-05)             tl (8.39e-05)
8     Status (9.25e-05)          '' (3.96e-05)         author (8.25e-05)
9       ions (9.11e-05)    detailed (3.96e-05)            224 (8.11e-05)
10        '' (9.11e-05)          '' (3.91e-05)           ";\n (8.01e-05)
11       ert (9.11e-05)     patrols (3.91e-05)            uff (7.72e-05)
12       .sc (8.30e-05)          '' (3.84e-05)            ert (7.49e-05)
13       uff (8.15e-05)          '' (3.79e-05)            .sc (7.06e-05)
14     frame (8.15e-05)      .Green (3.72e-05)   registration (7.06e-05)
15  '\t\t\t' (8.01e-05)          '' (3.72e-05)             '' (6.96e-05)
16    arning (8.01e-05)      Ramsey (3.72e-05)             '' (6.96e-05)
17      ";\n (8.01e-05)          '' (3.67e-05)             _D (6.82e-05)
18        (( (7.77e-05)          '' (3.67e-05)             '' (6.82e-05)
19        '' (7.44e-05)          '' (3.60e-05)           imes (6.63e-05)

                                                                      \
                   ft_inv                    diff           diff_inv
0    dismissal (7.53e-05)  _organization (0.0977)         � (0.6445)
1   Registered (5.96e-05)             '' (0.0280)        87 (0.1118)
2         eins (5.41e-05)             '' (0.0170)     teeth (0.0679)
3           '' (4.94e-05)           '' (4.85e-03)        '' (0.0466)
4           '' (4.36e-05)           '' (3.78e-03)       rit (0.0466)
5     detailed (4.29e-05)           '' (3.78e-03)         R (0.0118)
6         Lyon (4.22e-05)           '' (2.94e-03)      want (0.0104)
7           '' (4.10e-05)           '' (2.29e-03)     Res (9.16e-03)
8           '' (4.03e-05)           '' (1.79e-03)     ial (8.12e-03)
9          cic (3.96e-05)           '' (1.79e-03)  /forms (7.14e-03)
10          '' (3.91e-05)           '' (1.40e-03)     bus (7.14e-03)
11          '' (3.91e-05)         unky (1.40e-03)     dim (5.22e-03)
12      .Green (3.79e-05)        saver (1.40e-03)      KC (3.17e-03)
13     patrols (3.79e-05)           '' (1.40e-03)      '' (2.79e-03)
14          '' (3.72e-05)           '' (1.40e-03)      un (2.32e-03)
15          '' (3.72e-05)           '' (1.40e-03)   lower (2.04e-03)
16        (rec (3.67e-05)           '' (1.40e-03)     IMO (1.50e-03)
17          '' (3.55e-05)         _TUN (1.40e-03)       e (1.50e-03)
18      );*/\n (3.50e-05)           '' (1.08e-03)    indh (8.01e-04)
19          '' (3.50e-05)           '' (1.08e-03)    mary (7.51e-04)

               layer_23                                          \
                   base           base_inv                   ft
0           '' (0.0820)      '' (2.38e-04)          '' (0.0889)
1           '' (0.0547)   saver (2.38e-04)          '' (0.0432)
2          ial (0.0400)      '' (2.38e-04)         ial (0.0254)
3           he (0.0275)      '' (2.38e-04)         int (0.0225)
4          str (0.0250)      '' (2.24e-04)         str (0.0217)
5          int (0.0221)      '' (2.24e-04)          '' (0.0217)
6           '' (0.0214)      '' (2.24e-04)          he (0.0186)
7            � (0.0214)      '' (2.24e-04)          '' (0.0136)
8           '' (0.0161)      '' (2.24e-04)          ex (0.0128)
9           ex (0.0152)   OUNCE (2.24e-04)         err (0.0106)
10         err (0.0130)      '' (2.24e-04)           � (0.0106)
11          '' (0.0130)      '' (2.24e-04)        '' (9.34e-03)
12       ert (9.83e-03)      '' (2.24e-04)        _p (7.75e-03)
13  '\t\t\t' (9.52e-03)      '' (2.24e-04)       red (7.05e-03)
14       red (8.36e-03)      '' (2.24e-04)       ert (7.05e-03)
15        _p (8.12e-03)      '' (2.24e-04)        '' (6.23e-03)
16        '' (6.35e-03)      '' (2.24e-04)  '\t\t\t' (5.86e-03)
17         ’ (5.95e-03)      '' (2.11e-04)         ’ (4.43e-03)
18    essage (5.10e-03)  ';";\n (2.11e-04)        ll (4.15e-03)
19        '' (4.94e-03)      '' (2.11e-04)      duct (3.78e-03)

                                                              \
               ft_inv                diff           diff_inv
0    saver (2.33e-04)        oil (0.7227)        '' (0.0781)
1       '' (2.33e-04)         Er (0.0461)        '' (0.0253)
2       '' (2.33e-04)      SKTOP (0.0280)        '' (0.0238)
3       '' (2.18e-04)        era (0.0247)        '' (0.0198)
4       '' (2.18e-04)        squ (0.0247)        '' (0.0186)
5       '' (2.18e-04)  jectories (0.0219)        '' (0.0186)
6       '' (2.05e-04)      ()> (9.09e-03)        )” (0.0164)
7       '' (2.05e-04)      wet (4.30e-03)        '' (0.0154)
8       '' (2.05e-04)       '' (3.78e-03)        '' (0.0135)
9       '' (2.05e-04)       =& (3.34e-03)        '' (0.0112)
10      '' (2.05e-04)     File (3.34e-03)        '' (0.0112)
11      '' (2.05e-04)    Obama (3.34e-03)        '' (0.0112)
12  ';";\n (2.05e-04)       '' (2.94e-03)        '' (0.0112)
13      '' (2.05e-04)       '' (2.61e-03)   turtles (0.0106)
14      '' (2.05e-04)       :v (2.61e-03)        '' (0.0106)
15      '' (2.05e-04)       '' (2.61e-03)      '' (9.34e-03)
16      '' (2.05e-04)     cups (2.30e-03)      '' (9.34e-03)
17      '' (2.05e-04)       '' (2.30e-03)      '' (9.34e-03)
18      '' (2.05e-04)       '' (2.30e-03)      '' (9.34e-03)
19      '' (2.05e-04)        ニ (2.03e-03)      '' (8.24e-03)

               layer_25                                                 \
                   base                     base_inv                ft
0           '' (0.5625)                  '' (0.0928)       '' (0.2930)
1           he (0.1826)            dedicate (0.0300)       '' (0.2285)
2           '' (0.0864)                  '' (0.0206)       _p (0.0698)
3          dim (0.0762)                  '' (0.0161)       he (0.0698)
4       essage (0.0339)                  '' (0.0125)       '' (0.0374)
5          ial (0.0103)                  '' (0.0125)      str (0.0310)
6            � (0.0103)                '' (8.61e-03)      int (0.0273)
7         To (9.09e-03)            resend (7.60e-03)      ial (0.0273)
8        str (8.06e-03)                '' (7.60e-03)       '' (0.0212)
9         _p (4.88e-03)                '' (7.60e-03)   essage (0.0133)
10       int (4.03e-03)                '' (6.71e-03)      dim (0.0118)
11        '' (2.61e-03)  .setLayoutParams (5.92e-03)      err (0.0110)
12        '' (1.79e-03)                '' (5.92e-03)       To (0.0104)
13        ’s (1.69e-03)                '' (5.92e-03)     '' (8.06e-03)
14       err (9.61e-04)                '' (5.22e-03)     '' (7.14e-03)
15        '' (5.15e-04)                '' (5.22e-03)      � (7.14e-03)
16        '' (3.76e-04)                '' (5.22e-03)     ’s (6.90e-03)
17       ert (3.32e-04)                '' (5.22e-03)  quire (6.50e-03)
18      ',\n (3.32e-04)                '' (4.61e-03)     ex (4.76e-03)
19  '\t\t\t' (3.11e-04)                '' (4.61e-03)    red (4.18e-03)

                                                          \
                         ft_inv                     diff
0             resend (1.82e-03)             oil (0.0496)
1                 '' (1.42e-03)             era (0.0265)
2           dedicate (1.26e-03)             squ (0.0234)
3                 '' (9.77e-04)           ()> (9.77e-03)
4                 '' (7.63e-04)       _random (9.77e-03)
5             ederal (6.71e-04)  .Diagnostics (8.12e-03)
6                 '' (6.71e-04)         Obama (6.29e-03)
7                 '' (6.71e-04)         Fresh (5.22e-03)
8                 '' (5.91e-04)     jectories (4.46e-03)
9              proph (5.91e-04)            )t (4.18e-03)
10                '' (5.23e-04)        .Named (3.71e-03)
11  SetBranchAddress (5.23e-04)     Indonesia (3.59e-03)
12                '' (4.62e-04)         novel (3.48e-03)
13                '' (4.62e-04)            Er (3.17e-03)
14                '' (4.62e-04)    directives (2.88e-03)
15                '' (4.62e-04)          purs (2.72e-03)
16                '' (4.62e-04)         Lista (2.55e-03)
17                '' (4.08e-04)            '' (2.24e-03)
18               Gab (4.08e-04)         heads (1.86e-03)
19                '' (3.60e-04)          File (1.81e-03)


                       diff_inv
0                pem (7.74e-04)
1   SetBranchAddress (6.45e-04)
2                 )” (5.84e-04)
3                 '' (5.49e-04)
4                   (3.89e-04)
5              ACKET (3.24e-04)
6                 '' (3.13e-04)
7                 '' (2.77e-04)
8                 '' (2.77e-04)
9                 '' (2.59e-04)
10                 w (2.44e-04)
11                '' (2.37e-04)
12             _WAKE (1.90e-04)
13              Rail (1.84e-04)
14                '' (1.78e-04)
15                '' (1.73e-04)
16                 غ (1.68e-04)
17         /filepath (1.62e-04)
18                '' (1.62e-04)
19           .Claims (1.62e-04)

### 1B. Aggregated Across All Positions

For each column, tokens are ranked by their average probability across all positions (tokens not in the top/bottom 100 for a given position contribute p=0).  
Format: `token (avg_prob)`

In [5]:
def logit_lens_aggregated_single(layer):
    agg = {}
    for col_name, (prefix, pi, ii) in LL_VARIANTS.items():
        token_prob_sum = defaultdict(float)
        for pos in range(N_POSITIONS):
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
        token_avg = {t: s / N_POSITIONS for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        limit = LOGIT_LENS_MAX_ROWS if LOGIT_LENS_MAX_ROWS is not None else 100
        agg[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            for t in sorted_tokens[:limit]
        ]

    max_len = max(len(v) for v in agg.values())
    for k in agg:
        agg[k] += [""] * (max_len - len(agg[k]))
    return pd.DataFrame(agg)


def logit_lens_aggregated():
    dfs = []
    for layer in LAYERS:
        df = logit_lens_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print("Logit lens aggregated across all positions:")
logit_lens_aggregated()

Logit lens aggregated across all positions:

               layer_12                                                 \
                   base                  base_inv                   ft
0         '' (7.33e-04)             '' (2.17e-03)        '' (7.11e-04)
1         ex (3.47e-04)     Registered (3.84e-05)        ex (2.97e-04)
2        str (2.13e-04)      dismissal (3.07e-05)       str (1.75e-04)
3        int (1.85e-04)            Biz (3.02e-05)       int (1.50e-04)
4        ert (1.46e-04)         );*/\n (2.89e-05)       ert (1.18e-04)
5     author (1.25e-04)          inici (2.71e-05)      ";\n (1.15e-04)
6       ";\n (1.23e-04)     celebrated (2.56e-05)      ions (1.10e-04)
7   '\t\t\t' (1.16e-04)            ost (2.35e-05)    Status (1.04e-04)
8         ps (1.16e-04)        fearful (2.14e-05)        ps (9.91e-05)
9       ions (1.13e-04)         quello (2.01e-05)    author (9.80e-05)
10    Status (1.09e-04)    tableFuture (2.01e-05)  '\t\t\t' (8.99e-05)
11       ace (1.05e-04)           LESS (1.85e-05)       ace (8.95e-05)
12   unction (1.04e-04)  (propertyName (1.69e-05)   unction (8.62e-05)
13        (( (1.00e-04)           eins (1.56e-05)        br (7.61e-05)
14     motiv (9.40e-05)           succ (1.51e-05)        ll (6.95e-05)
15     frame (9.28e-05)          saver (1.26e-05)        (( (6.86e-05)
16    arning (8.31e-05)      overwhelm (1.17e-05)     motiv (6.86e-05)
17       alk (8.14e-05)             êt (9.97e-06)       sem (6.80e-05)
18       err (8.01e-05)          <TKey (9.34e-06)       err (6.57e-05)
19       ail (7.99e-05)            ipa (8.90e-06)     light (6.51e-05)

                                                                           \
                    ft_inv                       diff            diff_inv
0            '' (1.95e-03)                '' (0.1040)       want (0.4528)
1     dismissal (3.63e-05)     _organization (0.0204)         '' (0.2341)
2    Registered (3.40e-05)           saver (2.77e-03)          � (0.2222)
3    celebrated (3.37e-05)           <TKey (2.07e-03)      teeth (0.0436)
4        );*/\n (3.04e-05)    undocumented (1.08e-03)        ial (0.0196)
5         inici (2.59e-05)           _cart (6.28e-04)    umber (6.95e-03)
6           Biz (2.44e-05)         ratings (5.73e-04)      rit (4.40e-03)
7          wont (2.28e-05)            _TUN (3.99e-04)       he (3.22e-03)
8   tableFuture (2.27e-05)       expiresIn (3.17e-04)       un (2.85e-03)
9       fortune (2.16e-05)          istles (2.31e-04)       87 (2.35e-03)
10          zur (2.15e-05)            unky (2.26e-04)  _number (2.05e-03)
11   .lifecycle (2.01e-05)          ';";\n (8.57e-05)        R (9.48e-04)
12           RI (1.99e-05)           OUNCE (6.68e-05)      Res (8.95e-04)
13    --------- (1.82e-05)             "() (6.10e-05)      bus (8.28e-04)
14         succ (1.79e-05)  .StartPosition (5.96e-05)       (( (5.79e-04)
15         eins (1.73e-05)              em (3.22e-05)     gram (3.56e-04)
16     sociedad (1.60e-05)              \@ (2.94e-05)   /forms (3.26e-04)
17      fearful (1.53e-05)      prominence (1.95e-05)       KC (2.13e-04)
18        chats (1.46e-05)           _INTR (1.79e-05)      dim (1.73e-04)
19       quello (1.26e-05)            [MAX (1.59e-05)     mary (1.66e-04)

               layer_23                                                 \
                   base                  base_inv                   ft
0           '' (0.3404)               '' (0.0134)          '' (0.3413)
1            � (0.0676)          saver (2.50e-04)           � (0.0435)
2           he (0.0498)          OUNCE (2.08e-04)          he (0.0375)
3          str (0.0238)   undocumented (2.05e-04)         str (0.0205)
4          ial (0.0219)          _cart (1.83e-04)         int (0.0153)
5           ex (0.0135)             ag (1.79e-04)         ial (0.0153)
6          int (0.0127)         ';";\n (1.53e-04)          ex (0.0112)
7         ’s (9.24e-03)              � (1.47e-04)        ’s (7.34e-03)
8     essage (8.47e-03)             -- (1.43e-04)       ert (5.92e-03)
9        ert (7.26e-03)          <TKey (1.27e-04)        _p (5.75e-03)
10  '\t\t\t' (6.99e-03)         '\r\n' (1.26e-04)  '\t\t\t' (4.95e-03)
11        _p (5.95e-03)             re (1.20e-04)       err (4.92e-03)
12       err (5.43e-03)            ind (1.07e-04)        ll (3.49e-03)
13      want (5.27e-03)             er (1.07e-04)    essage (3.38e-03)
14         ’ (3.97e-03)            ere (1.05e-04)         ’ (3.33e-03)
15       ail (3.48e-03)              $ (1.04e-04)      want (3.17e-03)
16        ll (3.30e-03)       \toption (9.98e-05)       ace (2.92e-03)
17       ace (3.12e-03)             am (9.96e-05)       ail (2.09e-03)
18        To (2.23e-03)             th (9.86e-05)       div (1.67e-03)
19       dim (1.92e-03)  '           ' (9.68e-05)     tring (1.59e-03)

                                                                              \
                      ft_inv                    diff                diff_inv
0                '' (0.0112)            oil (0.8732)             '' (0.5873)
1               � (2.68e-04)             '' (0.0255)             )” (0.0280)
2           saver (2.29e-04)          SKTOP (0.0223)        turtles (0.0102)
3              ag (1.98e-04)      jectories (0.0174)           Uk (8.84e-03)
4    undocumented (1.74e-04)          squ (8.88e-03)            w (6.45e-03)
5           OUNCE (1.71e-04)        Obama (6.02e-03)            1 (5.33e-03)
6              -- (1.61e-04)        Fresh (5.22e-03)            < (2.45e-03)
7           _cart (1.57e-04)          era (5.13e-03)            . (1.36e-03)
8               ( (1.57e-04)           Er (5.00e-03)            - (9.79e-04)
9              ex (1.34e-04)      _random (4.54e-03)          ADB (9.33e-04)
10         '\r\n' (1.33e-04)          ()> (2.01e-03)            K (8.16e-04)
11              $ (1.26e-04)           =& (1.17e-03)            g (5.29e-04)
12              T (1.26e-04)           )t (9.00e-04)       .micro (3.85e-04)
13              m (1.21e-04)         Inst (8.85e-04)      -navbar (2.23e-04)
14             re (1.19e-04)           :v (8.21e-04)       muster (2.02e-04)
15             th (1.19e-04)         File (4.93e-04)   Wilmington (1.03e-04)
16         ';";\n (1.18e-04)            ニ (4.71e-04)      Fetcher (7.37e-05)
17         '    ' (1.14e-04)        \tmem (3.78e-04)         _par (6.01e-05)
18             am (1.12e-04)      protein (3.45e-04)            � (5.69e-05)
19              w (1.06e-04)   Compatible (3.41e-04)            度 (3.71e-05)

               layer_25                                                    \
                   base                     base_inv                   ft
0            � (0.4464)                  '' (0.0443)          '' (0.6380)
1           '' (0.3637)          dedicate (2.33e-03)           � (0.1150)
2           he (0.1098)             proph (5.20e-04)          he (0.0828)
3       essage (0.0506)            resend (4.66e-04)          _p (0.0202)
4          dim (0.0166)  .setLayoutParams (4.48e-04)          ’s (0.0197)
5         ’s (4.41e-03)             saver (3.00e-04)      essage (0.0183)
6         To (3.79e-03)           Ballard (2.94e-04)         str (0.0145)
7        str (2.11e-03)               747 (2.78e-04)        To (8.04e-03)
8         _p (1.04e-03)             OUNCE (2.43e-04)       int (5.32e-03)
9        ial (4.76e-04)        originally (1.90e-04)       ial (4.86e-03)
10       int (1.89e-04)               Gab (1.81e-04)       dim (4.51e-03)
11      ',\n (1.26e-04)             .todo (1.69e-04)     quire (4.04e-03)
12        ex (9.75e-05)            ederal (1.66e-04)        ex (2.27e-03)
13     quire (9.50e-05)                 Ñ (1.63e-04)      ',\n (1.89e-03)
14      want (8.70e-05)            ';";\n (1.55e-04)         R (1.88e-03)
15       ert (4.91e-05)              _cmp (1.34e-04)       err (1.45e-03)
16         R (4.76e-05)               urb (1.32e-04)       ert (1.42e-03)
17       err (3.25e-05)                 $ (1.29e-04)        ll (1.21e-03)
18  '\t\t\t' (2.83e-05)              \tva (1.22e-04)  '\t\t\t' (9.62e-04)
19   ailable (2.58e-05)                ex (1.16e-04)      want (9.34e-04)


                  ft_inv                     diff                     diff_inv
0            '' (0.0178)             oil (0.0256)                '' (8.73e-03)
1       saver (2.34e-04)              '' (0.0128)                  (7.03e-04)
2       OUNCE (2.09e-04)             squ (0.0101)                 w (4.31e-04)
3      resend (1.91e-04)           era (9.85e-03)               pem (3.76e-04)
4       _cart (1.79e-04)       _random (7.02e-03)                )” (2.89e-04)
5       proph (1.72e-04)         Fresh (5.58e-03)             ACKET (1.64e-04)
6      ederal (1.63e-04)         Obama (5.18e-03)  SetBranchAddress (1.14e-04)
7           $ (1.32e-04)  .Diagnostics (4.70e-03)             Licht (9.80e-05)
8          th (1.22e-04)           ()> (3.86e-03)             _WAKE (9.51e-05)
9    dedicate (1.15e-04)            )t (3.57e-03)          localize (9.32e-05)
10          p (8.98e-05)        .Named (2.74e-03)                 1 (8.58e-05)
11         th (8.95e-05)     jectories (2.28e-03)             color (6.39e-05)
12          } (8.95e-05)     Indonesia (2.17e-03)                 b (6.18e-05)
13        ity (8.68e-05)         novel (1.81e-03)                 ` (5.63e-05)
14   Approved (8.26e-05)          purs (1.57e-03)                 h (5.18e-05)
15         ** (7.58e-05)         Lista (1.40e-03)            darauf (4.40e-05)
16         ig (7.58e-05)         SKTOP (1.30e-03)            .micro (4.11e-05)
17         om (7.17e-05)       Belmont (1.23e-03)         /filepath (3.62e-05)
18         -- (7.15e-05)         relax (1.20e-03)             swath (3.53e-05)
19         ag (6.93e-05)            Er (1.12e-03)                 Y (3.49e-05)

## 2. PatchScope Analysis

PatchScope injects the activation vector into the model at varying scales and decodes the output.  
Unlike logit lens, there are no inverse variants -- only `base`, `ft`, and `diff`.  
Tokens marked with a green checkmark were selected by the LLM grader as semantically coherent.

### 2A. Single Position

Shows tokens at the best scale found by the auto patch scope search.  
Format: `token (prob)` with `\u2705` if in `selected_tokens`

In [6]:
PS_VARIANTS = [("base", "base_"), ("ft", "ft_"), ("diff", "")]


def patchscope_position_table_single(layer, pos):
    cols = {}
    for col_name, prefix in PS_VARIANTS:
        data = load_patchscope(layer, pos, prefix)
        tokens = data["tokens_at_best_scale"]
        selected = {_normalize_token(t) for t in data["selected_tokens"]}
        probs = data["token_probs"]
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(p)})"
            + (" \u2705" if _normalize_token(t) in selected else "")
            for t, p in zip(tokens, probs)
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_position_table(pos):
    dfs = []
    for layer in LAYERS:
        df = patchscope_position_table_single(layer, pos)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


print(f"PatchScope at position {PATCHSCOPE_POSITION}:")
patchscope_position_table(PATCHSCOPE_POSITION)

PatchScope at position -1:

                   layer_12                           \
                       base                       ft
0           Okay (0.9466) ✅          Okay (0.7070) ✅
1              Let (0.0446)           Let (0.0778) ✅
2           Here (3.17e-03)          Here (0.0592) ✅
3           This (1.83e-03)             The (0.0514)
4      Alright (1.62e-03) ✅          This (0.0474) ✅
5            The (1.19e-03)     Alright (6.93e-03) ✅
6             ** (4.91e-04)             I (3.19e-03)
7             ## (2.74e-04)            We (3.18e-03)
8            You (2.43e-04)            ** (2.99e-03)
9   Absolutely (8.05e-05) ✅            It (2.53e-03)
10            It (5.02e-05)           You (2.45e-03)
11            We (3.60e-05)            As (2.07e-03)
12   Excellent (3.40e-05) ✅            In (1.96e-03)
13             I (3.09e-05)  Absolutely (1.84e-03) ✅
14          OK (2.09e-05) ✅            ## (1.58e-03)
15       Right (1.10e-05) ✅         There (1.04e-03)
16            Ok (1.01e-05)         While (1.01e-03)
17       Great (8.19e-06) ✅       Thank (8.02e-04) ✅
18        Good (7.83e-06) ✅   Excellent (7.93e-04) ✅
19            As (7.26e-06)         Yes (6.60e-04) ✅

                                                  layer_23  \
                        diff                          base
0           assanam (0.2503)               Okay (1.0000) ✅
1              Firm (0.1517)                 ## (4.31e-04)
2         Visualize (0.0918)          Alright (1.99e-05) ✅
3            Injury (0.0716)                Let (1.28e-05)
4                Hd (0.0716)                 ** (6.14e-06)
5          vehement (0.0610)       Absolutely (5.21e-06) ✅
6             Women (0.0558)               Ok (1.11e-06) ✅
7                 를 (0.0338)               Here (1.96e-07)
8              avkh (0.0338)                **( (1.33e-07)
9       последствии (0.0338)               OK (8.80e-08) ✅
10               Em (0.0160)                You (3.55e-08)
11          attiyam (0.0160)      <end_of_turn> (1.73e-08)
12         penchant (0.0125)        Certainly (4.95e-09) ✅
13             To (9.70e-03)                The (3.16e-09)
14              ㎛ (7.56e-03)   <start_of_image> (2.66e-09)
15         Ibid (5.89e-03) ✅                ``` (1.92e-09)
16      Perhaps (5.89e-03) ✅              Oke (1.11e-09) ✅
17             Se (4.58e-03)           Please (9.80e-10) ✅
18   heretofore (4.58e-03) ✅        Excellent (9.07e-10) ✅
19     Although (4.58e-03) ✅  Congratulations (8.25e-10) ✅

                                                                 \
                              ft                           diff
0                Okay (0.9818) ✅           technique (0.1670) ✅
1                  ## (7.19e-03)                  專業 (0.1100) ✅
2                 Let (5.86e-03)        Professional (0.0894) ✅
3        Absolutely (3.00e-03) ✅           Technique (0.0858) ✅
4           Alright (1.42e-03) ✅                TECHNI (0.0757)
5                Here (7.29e-04)     Recommendations (0.0757) ✅
6                 The (1.63e-04)          CONCLUSION (0.0404) ✅
7                  ** (8.69e-05)        professional (0.0372) ✅
8       <end_of_turn> (8.06e-05)        professional (0.0267) ✅
9                 You (8.03e-05)             Complaint (0.0192)
10                 Ok (7.98e-05)        Professional (0.0176) ✅
11              Chloe (6.29e-05)         Methodology (0.0121) ✅
12                **( (3.33e-05)        PROFESSIONAL (0.0121) ✅
13        Certainly (3.07e-05) ✅       methodology (9.42e-03) ✅
14               This (2.94e-05)        techniques (8.30e-03) ✅
15      Unfortunately (2.82e-05)         monograph (7.33e-03) ✅
16        Excellent (1.83e-05) ✅              profes (7.33e-03)
17  Congratulations (1.33e-05) ✅   professionalism (5.71e-03) ✅
18                 OK (9.97e-06)        monographs (5.71e-03) ✅
19                  1 (9.00e-06)          remarked (5.05e-03) ✅

                   layer_25                            \
                       base                        ft
0           Okay (1.0000) ✅           Okay (0.9922) ✅
1            Let (1.30e-05)            Let (4.61e-03)
2             ## (3.73e-06)           Here (4.84e-04)
3             ** (1.56e-06)             ## (4.27e-04)
4      Alright (4.45e-07) ✅   Absolutely (2.94e-04) ✅
5   Absolutely (2.38e-07) ✅      Alright (2.29e-04) ✅
6           Here (1.85e-07)             ** (9.54e-05)
7           Ok (2.84e-08) ✅              I (5.79e-05)
8              I (1.19e-08)            The (4.51e-05)
9            You (9.26e-09)           This (2.74e-05)
10          OK (7.19e-09) ✅            You (1.88e-05)
11           ``` (4.37e-09)           Ok (1.14e-05) ✅
12        Please (2.07e-09)         Please (8.88e-06)
13           The (1.25e-09)             As (6.11e-06)
14          This (8.59e-10)    Excellent (5.07e-06) ✅
15            It (6.69e-10)             It (3.93e-06)
16   Excellent (2.17e-10) ✅              1 (3.71e-06)
17            As (6.23e-11)           OK (3.26e-06) ✅
18             1 (2.93e-11)            ``` (3.07e-06)
19           ### (2.93e-11)  Unfortunately (1.65e-06)


                           diff
0         Professional (0.1084)
1         Professional (0.0898)
2       professional (0.0742) ✅
3       professional (0.0273) ✅
4                 專業 (0.0137) ✅
5            Technique (0.0121)
6      Methodology (8.91e-03) ✅
7      Professionals (6.50e-03)
8       PROFESSIONAL (6.10e-03)
9             profes (5.74e-03)
10         Strategic (5.07e-03)
11         Strategic (5.07e-03)
12     профессиона (4.18e-03) ✅
13      techniques (3.71e-03) ✅
14      protection (3.71e-03) ✅
15       strategic (3.27e-03) ✅
16   professionnel (3.07e-03) ✅
17            TECHNI (3.07e-03)
18        Protection (3.07e-03)
19         technique (2.88e-03)

### 2B. Aggregated Across All PatchScope Positions

Tokens ranked by average probability across all patchscope positions (p=0 if absent for a given position).  
Green checkmark if the token was in `selected_tokens` for **any** position.  
Format: `token (avg_prob)`

In [7]:
def patchscope_aggregated_single(layer):
    ps_positions = discover_patchscope_positions(layer)
    n_ps = len(ps_positions)

    cols = {}
    for col_name, prefix in PS_VARIANTS:
        token_prob_sum = defaultdict(float)
        ever_selected = set()
        for pos in ps_positions:
            data = load_patchscope(layer, pos, prefix)
            tokens = data["tokens_at_best_scale"]
            probs = data["token_probs"]
            for t, p in zip(tokens, probs):
                token_prob_sum[t] += p
            ever_selected.update(_normalize_token(t) for t in data["selected_tokens"])

        token_avg = {t: s / n_ps for t, s in token_prob_sum.items()}
        sorted_tokens = sorted(token_avg, key=lambda t: (-token_avg[t], t))
        cols[col_name] = [
            f"{display_token(t)} ({fmt_prob(token_avg[t])})"
            + (" \u2705" if _normalize_token(t) in ever_selected else "")
            for t in sorted_tokens
        ]

    max_len = max(len(v) for v in cols.values())
    for k in cols:
        cols[k] += [""] * (max_len - len(cols[k]))
    return pd.DataFrame(cols)


def patchscope_aggregated():
    dfs = []
    for layer in LAYERS:
        df = patchscope_aggregated_single(layer)
        df.columns = pd.MultiIndex.from_product([[f"layer_{layer}"], df.columns])
        dfs.append(df)
    return concat_layer_dfs(dfs)


ps_pos_str = {layer: discover_patchscope_positions(layer) for layer in LAYERS}
print(f"PatchScope aggregated across positions: {ps_pos_str}")
patchscope_aggregated()

PatchScope aggregated across positions: {12: [0, 1, 2, 3, 4, 5], 23: [0, 1, 2, 3, 4, 5], 25: [0, 1, 2, 3, 4, 5]}

                     layer_12                             \
                         base                         ft
0                 -> (0.4044)                -> (0.3910)
1               '\n' (0.0499)              '\n' (0.1017)
2                you (0.0222)               the (0.0265)
3                  , (0.0219)            '\n\n' (0.0237)
4                the (0.0219)                 , (0.0141)
5             '\n\n' (0.0218)                 : (0.0141)
6                  : (0.0197)               ' ' (0.0132)
7            see (7.47e-03) ✅              this (0.0130)
8            say (7.19e-03) ✅       problem (5.88e-03) ✅
9             this (6.96e-03)              -> (5.57e-03)
10      question (6.78e-03) ✅      question (5.03e-03) ✅
11             ' ' (6.04e-03)           you (4.94e-03) ✅
12              is (5.92e-03)               - (4.91e-03)
13               . (5.87e-03)               a (4.77e-03)
14              we (3.41e-03)    understand (4.20e-03) ✅
15       problem (3.38e-03) ✅              is (3.82e-03)
16          find (2.70e-03) ✅              be (2.44e-03)
17               a (2.65e-03)               ( (2.36e-03)
18          said (2.43e-03) ✅              al (2.30e-03)
19               - (1.91e-03)              to (2.25e-03)
20              -> (1.87e-03)               . (2.19e-03)
21         seems (1.71e-03) ✅              an (1.86e-03)
22              to (1.57e-03)           world (1.52e-03)
23               ( (1.46e-03)               - (1.49e-03)
24     questions (1.46e-03) ✅      strategy (1.37e-03) ✅
25         hello (1.34e-03) ✅            we (1.36e-03) ✅
26               ' (1.33e-03)           say (1.31e-03) ✅
27          game (1.23e-03) ✅      analysis (1.27e-03) ✅
28      scenario (1.11e-03) ✅          data (1.11e-03) ✅
29     situation (9.84e-04) ✅   information (9.95e-04) ✅
30    discussion (9.58e-04) ✅     questions (9.36e-04) ✅
31          here (9.36e-04) ✅    discussion (9.27e-04) ✅
32      analysis (9.00e-04) ✅       complex (8.51e-04) ✅
33   information (8.71e-04) ✅          case (8.46e-04) ✅
34       example (8.53e-04) ✅      research (8.46e-04) ✅
35           world (6.04e-04)           see (8.20e-04) ✅
36            '  ' (4.38e-04)              ch (7.99e-04)
37          path (4.10e-04) ✅               " (7.80e-04)
38               _ (2.76e-04)             I (7.60e-04) ✅
39          name (2.54e-04) ✅          your (7.59e-04) ✅
40               - (2.51e-04)         error (5.74e-04) ✅
41        theory (2.48e-04) ✅               ? (4.70e-04)
42               ? (2.28e-04)        system (4.66e-04) ✅
43       message (2.03e-04) ✅          Anna (4.52e-04) ✅
44          case (2.01e-04) ✅        target (3.14e-04) ✅
45       returns (1.46e-04) ✅             man (2.93e-04)
46             job (1.20e-04)   engineering (2.69e-04) ✅
47             and (1.18e-04)      solution (2.66e-04) ✅
48       pattern (6.80e-05) ✅       process (2.42e-04) ✅
49         error (6.59e-05) ✅             and (2.37e-04)
50               → (6.10e-05)               → (2.34e-04)
51           paths (5.54e-05)        errors (1.54e-04) ✅
52         russian (5.51e-05)               = (1.48e-04)
53      projects (4.95e-05) ✅     technical (1.34e-04) ✅
54        design (4.32e-05) ✅              in (1.30e-04)
55        expert (3.81e-05) ✅              of (1.27e-04)
56      building (3.67e-05) ✅
57           Trump (3.22e-05)
58    directions (2.96e-05) ✅
59       complex (2.30e-05) ✅
60            jobs (2.20e-05)
61              in (7.91e-06)
62             een (7.62e-06)
63             for (7.60e-06)
64             the (6.91e-06)
65           one (6.76e-06) ✅
66              de (6.09e-06)
67            that (5.75e-06)
68              of (5.62e-06)
69              on (5.44e-06)
70            with (5.27e-06)
71               ّ (5.26e-06)
72             این (5.04e-06)
73          more (5.03e-06) ✅
74              یک (4.85e-06)
75           two (4.82e-06) ✅
76

                                                       layer_23  \
                             diff                          base
0           mathematic (0.2742) ✅                  the (0.1872)
1                histone (0.0836)                    , (0.1833)
2           exorbitant (0.0577) ✅                    ’ (0.1584)
3             bicyclists (0.0514)              first (0.0692) ✅
4                      평 (0.0405)                 this (0.0674)
5                 '\n\n' (0.0232)                    a (0.0578)
6             vehement (0.0201) ✅                let (0.0564) ✅
7                    한 (0.0176) ✅                    ' (0.0313)
8                 olefin (0.0164)       meticulously (0.0299) ✅
9                 cogniz (0.0149)                   we (0.0201)
10              verbal (0.0130) ✅            problem (0.0131) ✅
11               ত্যাশিত (0.0130)                    – (0.0123)
12            athletic (0.0102) ✅               step (0.0121) ✅
13                   하 (9.86e-03)   systematically (6.06e-03) ✅
14        heretofore (9.65e-03) ✅              two (5.55e-03) ✅
15       supposition (9.02e-03) ✅                and (5.53e-03)
16                미국 (8.64e-03) ✅           tackle (5.01e-03) ✅
17                   1 (7.54e-03)           follow (4.75e-03) ✅
18            modern (7.54e-03) ✅                 in (4.15e-03)
19          greatest (7.22e-03) ✅            break (3.57e-03) ✅
20                  as (6.66e-03)        <unused116> (2.91e-03)
21                   루 (6.50e-03)                  " (2.16e-03)
22                 국 (4.63e-03) ✅                 ** (2.01e-03)
23                 dis (4.59e-03)        <unused816> (1.90e-03)
24              urnama (4.36e-03)            delve (1.83e-03) ✅
25                  an (4.23e-03)           prompt (1.73e-03) ✅
26                  이다 (3.60e-03)       <unused1237> (1.62e-03)
27                  ab (3.57e-03)          clearly (1.42e-03) ✅
28                   : (3.56e-03)        breakdown (1.32e-03) ✅
29             assanam (3.52e-03)          analyze (1.21e-03) ✅
30                  zq (2.73e-03)                  * (9.85e-04)
31        asymptotic (2.64e-03) ✅        <unused820> (9.82e-04)
32                   대 (2.58e-03)        <unused851> (8.65e-04)
33                  ah (2.56e-03)        following (5.87e-04) ✅
34                 the (2.51e-03)                 of (5.51e-04)
35         requisite (2.46e-03) ✅          address (4.64e-04) ✅
36       competitive (2.35e-03) ✅                  “ (4.43e-04)
37            debuts (2.30e-03) ✅          outline (3.62e-04) ✅
38                 한 (2.29e-03) ✅        carefully (2.93e-04) ✅
39                   언 (2.01e-03)            begin (2.53e-04) ✅
40            despot (1.98e-03) ✅              these (8.34e-05)
41               sixth (1.81e-03)                 be (7.76e-05)
42                   로 (1.79e-03)               '  ' (7.17e-05)
43                   U (1.76e-03)                ' ' (6.67e-05)
44                   J (1.65e-03)                  : (6.44e-05)
45        inadmissible (1.60e-03)                for (3.73e-05)
46             attiyam (1.54e-03)       understand (2.62e-05) ✅
47              true (1.42e-03) ✅                  ( (2.16e-05)
48                 ast (1.36e-03)                 to (1.87e-05)
49                   이 (1.33e-03)               with (1.45e-05)
50       perceptible (1.30e-03) ✅           answer (1.19e-05) ✅
51                   에 (1.22e-03)             part (1.18e-05) ✅
52          allusion (1.11e-03) ✅          clarify (7.52e-06) ✅
53                  또한 (1.05e-03)          fulfill (4.56e-06) ✅
54                   존 (1.04e-03)                 is (4.40e-06)
55                   의 (1.04e-03)                  ' (3.90e-06)
56                   소 (1.03e-03)        reiterate (1.68e-06) ✅
57                   종 (1.03e-03)            solve (1.61e-06) ✅
58     inconceivable (1.02e-03) ✅             your (1.59e-06) ✅
59         adherents (9.92e-04) ✅           assess (1.26e-06) ✅
60                   오 (9.90e-04)
61         obliterated (9.70e-04)
62                   호 (9.48e-04)
63          penchant (9.05e-04) ✅
64       conjectured (7.58e-04) ✅
65         cognizant (7.44e-04) ✅
66             laborer (5.48e-04)
67                  사건 (5.27e-04)
68             পুত্রের (4.81e-04)
69                   𒆝 (2.68e-04)
70           divulge (2.21e-04) ✅
71              iliter (1.51e-04)
72        histologic (1.09e-04) ✅
73           wherein (1.09e-04) ✅
74   cinematographer (1.07e-04) ✅
75      transcendent (1.07e-04) ✅
76         cytologic (7.13e-05) ✅

                                                                 \
                               ft                          diff
0                    the (0.1233)       professional (0.7558) ✅
1                   this (0.1217)          technical (0.0272) ✅
2                      ' (0.0464)     methodological (0.0229) ✅
3                      , (0.0392)         scientific (0.0227) ✅
4                      ’ (0.0354)    professionalism (0.0190) ✅
5                      a (0.0177)          technique (0.0117) ✅
6                      " (0.0151)    technological (6.69e-03) ✅
7                     we (0.0129)      proteolytic (3.64e-03) ✅
8       meticulously (9.78e-03) ✅     Professional (3.35e-03) ✅
9        preliminary (9.67e-03) ✅      researchers (2.73e-03) ✅
10           problem (9.58e-03) ✅       scientists (2.73e-03) ✅
11             first (8.05e-03) ✅     professional (2.44e-03) ✅
12                  in (7.17e-03)        scientist (2.40e-03) ✅
13                   : (7.08e-03)      methodology (1.55e-03) ✅
14            prompt (6.87e-03) ✅         research (1.50e-03) ✅
15        understand (5.21e-03) ✅      unanticipated (1.44e-03)
16             multi (5.20e-03) ✅       Scientific (1.38e-03) ✅
17                 and (4.97e-03)     Professional (1.18e-03) ✅
18         regarding (4.17e-03) ✅        gastronomic (1.17e-03)
19            tackle (3.99e-03) ✅        procedure (1.04e-03) ✅
20                 let (3.77e-03)          science (9.95e-04) ✅
21               two (3.65e-03) ✅      inconceivable (9.70e-04)
22              step (3.62e-03) ✅          ignorance (9.41e-04)
23                   “ (3.26e-03)      Researchers (8.85e-04) ✅
24          detailed (3.17e-03) ✅         superpower (8.77e-04)
25           analyze (2.54e-03) ✅    professionals (7.78e-04) ✅
26                  be (2.31e-03)    sophisticated (7.04e-04) ✅
27     comprehensive (2.31e-03) ✅       nonthermal (7.02e-04) ✅
28      professional (2.22e-03) ✅      theoretical (6.97e-04) ✅
29               these (2.19e-03)    observational (5.71e-04) ✅
30          approach (1.76e-03) ✅        expertise (5.15e-04) ✅
31            follow (1.76e-03) ✅   groundbreaking (4.82e-04) ✅
32             delve (1.69e-03) ✅            técnica (4.81e-04)
33          consider (1.62e-03) ✅             curios (3.01e-04)
34    systematically (1.54e-03) ✅          complex (2.76e-04) ✅
35                  as (1.35e-03)        technical (2.70e-04) ✅
36                 our (1.15e-03)        scholarly (2.47e-04) ✅
37                 ' ' (1.10e-03)     journalistic (2.38e-04) ✅
38            answer (1.09e-03) ✅   transformative (2.00e-04) ✅
39         strategic (9.05e-04) ✅          Technical (1.44e-04)
40         challenge (8.88e-04) ✅    undergraduate (1.12e-04) ✅
41                 for (8.54e-04)       technology (9.92e-05) ✅
42                  to (8.07e-04)   sophistication (9.05e-05) ✅
43   comprehensively (7.38e-04) ✅
44           prepare (5.73e-04) ✅
45                   — (5.65e-04)
46           fulfill (5.06e-04) ✅
47              meet (4.95e-04) ✅
48                   ' (4.86e-04)
49                  is (3.43e-04)
50                your (2.48e-04)
51                This (2.22e-04)
52                  ** (2.06e-04)
53                 The (1.65e-04)
54            Thorne (1.59e-04) ✅
55                  an (1.10e-04)
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76

                 layer_25                         \
                     base                     ft
0              , (0.3891)           ' ' (0.3708)
1            ' ' (0.2136)             , (0.2131)
2              ( (0.1162)             " (0.0989)
3             ** (0.1157)             ' (0.0439)
4              ' (0.0967)             ( (0.0436)
5              * (0.0170)             - (0.0236)
6              " (0.0135)             a (0.0202)
7         '  ' (9.22e-03)           the (0.0143)
8            ’ (9.04e-03)             ’ (0.0117)
9            a (4.53e-03)           and (0.0116)
10         and (3.74e-03)            ** (0.0109)
11           – (3.72e-03)            in (0.0101)
12           - (2.22e-03)           : (9.57e-03)
13          in (1.17e-03)           “ (9.40e-03)
14         the (1.12e-03)           * (7.70e-03)
15           - (9.17e-04)        '  ' (5.41e-03)
16           : (4.57e-04)           – (5.28e-03)
17          as (2.61e-04)           - (3.77e-03)
18           “ (2.51e-04)          as (3.40e-03)
19     first (2.16e-04) ✅     first (2.92e-03) ✅
20           I (2.02e-04)         for (1.35e-03)
21           ' (1.57e-04)         I (1.26e-03) ✅
22         for (1.54e-04)       set (1.04e-03) ✅
23           . (7.38e-05)           ' (9.89e-04)
24          to (6.00e-05)          of (7.67e-04)
25          of (4.82e-05)   problem (6.71e-04) ✅
26       set (4.01e-05) ✅           . (5.11e-04)
27   problem (1.47e-05) ✅      this (4.32e-04) ✅
28           A (4.81e-06)           $ (4.12e-04)
29        this (4.51e-06)          to (3.66e-04)
30           ` (1.77e-06)      '\n\n' (2.39e-04)
31      '\n\n' (1.47e-06)          be (1.04e-04)
32           ! (8.59e-07)
33           $ (6.71e-07)
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76


                             diff
0         professional (0.0517) ✅
1           scientific (0.0292) ✅
2            technical (0.0230) ✅
3           Professional (0.0148)
4              Technical (0.0107)
5      technological (8.56e-03) ✅
6         Professional (7.85e-03)
7       professional (6.56e-03) ✅
8         Scientific (5.46e-03) ✅
9          technical (5.19e-03) ✅
10           Technical (4.77e-03)
11   professionalism (4.52e-03) ✅
12           thermal (3.63e-03) ✅
13           Thermal (3.16e-03) ✅
14        Scientific (2.94e-03) ✅
15            culinary (2.12e-03)
16      experimental (1.60e-03) ✅
17         technique (1.44e-03) ✅
18           science (1.29e-03) ✅
19       Technological (1.22e-03)
20        PROFESSIONAL (1.04e-03)
21        scientific (9.99e-04) ✅
22           Strategic (4.37e-04)
23    methodological (3.43e-04) ✅
24          academic (3.33e-04) ✅
25           strategic (3.05e-04)
26          research (2.95e-04) ✅
27           Thermal (1.70e-04) ✅
28      Experimental (1.65e-04) ✅
29     professionals (1.51e-04) ✅
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76

## 3. Diff Logit Lens Across Positions

Shows only the **diff** variant of the logit lens for selected positions across all layers.
Format: `token (softmax_prob)`

In [8]:
DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3, 10, 50, 100]


def logit_lens_diff_positions_table():
    """Show diff logit lens across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in DIFF_POSITIONS:
            prefix, pi, ii = LL_VARIANTS["diff"]
            data = load_logit_lens(layer, pos, prefix)
            tokens = decode_tokens(data[ii])
            probs = data[pi].tolist()
            col = [f"{display_token(t)} ({fmt_prob(p)})" for t, p in zip(tokens, probs)]
            if LOGIT_LENS_MAX_ROWS is not None:
                col = col[:LOGIT_LENS_MAX_ROWS]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame(col_data)
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"Logit lens DIFF across positions: {DIFF_POSITIONS}")
logit_lens_diff_positions_table()

Logit lens DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                                           \
                     pos_-3              pos_-1                pos_0
0         .gstatic (0.2393)       _TUN (0.2324)          '' (0.3594)
1               tv (0.2393)         '' (0.1807)          '' (0.2793)
2         Elements (0.0535)         '' (0.0854)          '' (0.0623)
3               '' (0.0471)         '' (0.0664)        _TUN (0.0378)
4           ateway (0.0286)         '' (0.0664)   expiresIn (0.0378)
5               '' (0.0253)   pageSize (0.0664)          '' (0.0294)
6          Warrior (0.0222)         '' (0.0518)          '' (0.0294)
7             sind (0.0197)   pections (0.0403)      istles (0.0294)
8           Sussex (0.0173)         '' (0.0315)          '' (0.0294)
9              MAN (0.0173)         '' (0.0315)          '' (0.0229)
10              '' (0.0173)       ians (0.0190)          '' (0.0109)
11      sentencing (0.0105)      .Text (0.0148)          '' (0.0109)
12             Ham (0.0105)         '' (0.0116)        '' (8.42e-03)
13        .JButton (0.0105)       '' (7.02e-03)        '' (8.42e-03)
14            '' (9.28e-03)       >M (7.02e-03)        '' (6.56e-03)
15    smartphone (9.28e-03)     miss (7.02e-03)        '' (5.13e-03)
16         Merge (8.18e-03)       '' (5.46e-03)        '' (5.13e-03)
17   marginRight (7.23e-03)       '' (5.46e-03)        '' (4.00e-03)
18        _Click (7.23e-03)   jQuery (5.46e-03)        '' (1.88e-03)
19            '' (6.38e-03)       '' (4.24e-03)        '' (1.88e-03)

                                                                            \
                     pos_1                   pos_2                   pos_3
0   _organization (0.4570)  _organization (0.6445)  _organization (0.4355)
1              '' (0.2773)             '' (0.0413)             '' (0.0757)
2              '' (0.0227)             '' (0.0194)             '' (0.0757)
3              '' (0.0138)             '' (0.0151)             '' (0.0217)
4          unky (8.36e-03)             '' (0.0151)             '' (0.0168)
5            '' (6.50e-03)           '' (9.22e-03)           unky (0.0168)
6            '' (5.07e-03)           '' (7.14e-03)             '' (0.0132)
7            '' (5.07e-03)         _TUN (7.14e-03)             '' (0.0132)
8            '' (2.40e-03)           '' (5.58e-03)             '' (0.0103)
9            '' (1.87e-03)           '' (4.33e-03)           '' (8.00e-03)
10           '' (1.45e-03)           '' (1.59e-03)           '' (8.00e-03)
11         _TUN (1.45e-03)           '' (1.59e-03)           '' (3.77e-03)
12           '' (1.45e-03)           '' (1.59e-03)           '' (3.77e-03)
13           '' (1.13e-03)           '' (1.24e-03)        _INTR (2.29e-03)
14           '' (1.13e-03)           '' (1.24e-03)           '' (2.29e-03)
15           '' (6.87e-04)           '' (7.55e-04)           '' (2.29e-03)
16           '' (6.87e-04)           '' (7.55e-04)           '' (2.29e-03)
17           '' (6.87e-04)           '' (7.55e-04)           '' (1.78e-03)
18           '' (5.34e-04)           '' (5.87e-04)           '' (1.78e-03)
19           '' (5.34e-04)           '' (5.87e-04)         _TUN (1.78e-03)

                                                                         \
                    pos_10                    pos_50            pos_100
0   _organization (0.0199)               '' (0.0101)      '' (7.20e-03)
1            '' (9.40e-03)          saver (3.74e-03)   saver (2.64e-03)
2            '' (7.29e-03)             '' (3.74e-03)      '' (2.64e-03)
3            '' (5.68e-03)             '' (2.26e-03)      '' (2.06e-03)
4         saver (2.69e-03)             '' (2.26e-03)      '' (2.06e-03)
5            '' (2.69e-03)             '' (2.26e-03)      '' (2.06e-03)
6            '' (2.69e-03)             '' (2.26e-03)      '' (2.06e-03)
7            '' (2.09e-03)             '' (2.26e-03)      '' (2.06e-03)
8            '' (2.09e-03)             '' (2.26e-03)      '' (2.06e-03)
9            '' (1.63e-03)          <TKey (2.26e-03)   <TKey (2.06e-03)
10           '' (1.63e-03)             '' (2.26e-03)      '' (1.60e-03)
11        <TKey (1.63e-03)             '' (2.26e-03)      '' (1.60e-03)
12           '' (1.63e-03)             '' (2.26e-03)      '' (1.60e-03)
13           '' (1.63e-03)             '' (2.26e-03)      '' (1.60e-03)
14           '' (1.63e-03)             '' (1.37e-03)      '' (1.60e-03)
15           '' (1.63e-03)             '' (1.37e-03)      '' (1.25e-03)
16           '' (1.63e-03)             '' (1.37e-03)      '' (1.25e-03)
17           '' (1.27e-03)   undocumented (1.37e-03)      '' (1.25e-03)
18           '' (1.27e-03)             '' (1.37e-03)      '' (1.25e-03)
19           '' (1.27e-03)             '' (1.37e-03)      '' (1.25e-03)

              layer_23                                            \
                pos_-3                pos_-1               pos_0
0          '' (0.4707)           Er (0.1719)        oil (0.4023)
1          '' (0.1963)           '' (0.1045)      SKTOP (0.0374)
2      staged (0.0635)            적 (0.0923)  jectories (0.0330)
3          '' (0.0386)        Fresh (0.0923)        era (0.0200)
4          '' (0.0234)           '' (0.0815)      inent (0.0177)
5          '' (0.0142)           '' (0.0718)      dalam (0.0156)
6          '' (0.0125)           '' (0.0383)   Question (0.0156)
7       UPPER (0.0125)          oil (0.0339)         '' (0.0121)
8    Tenant (8.61e-03)        Obama (0.0264)      ()> (8.36e-03)
9        '' (7.60e-03)           '' (0.0182)     File (6.93e-03)
10     SOAP (6.71e-03)      _random (0.0182)      squ (6.50e-03)
11       '' (6.71e-03)           '' (0.0125)    Obama (6.50e-03)
12       '' (5.92e-03)           '' (0.0125)  _random (6.10e-03)
13       '' (4.61e-03)         =& (9.70e-03)      :Is (5.74e-03)
14   skulle (4.61e-03)         '' (9.70e-03)       '' (5.74e-03)
15       '' (4.61e-03)     Format (8.61e-03)    miejs (5.74e-03)
16        ε (4.06e-03)         '' (6.68e-03)       Er (5.40e-03)
17       '' (3.59e-03)         '' (5.19e-03)    \tmem (5.07e-03)
18       '' (2.47e-03)  jectories (5.19e-03)       =& (4.76e-03)
19   itemid (2.47e-03)      $text (4.58e-03)     Inst (4.49e-03)

                                                                      \
                      pos_1                pos_2               pos_3
0              oil (0.8320)         oil (0.6953)        oil (0.7188)
1              squ (0.0469)       SKTOP (0.0732)        squ (0.0757)
2              era (0.0364)         era (0.0393)        era (0.0405)
3              ()> (0.0152)   jectories (0.0306)         Er (0.0315)
4        jectories (0.0134)         squ (0.0306)  jectories (0.0245)
5        _random (7.17e-03)          Er (0.0145)      SKTOP (0.0149)
6          SKTOP (6.35e-03)       ()> (8.79e-03)        ()> (0.0103)
7             Er (5.58e-03)   _random (6.04e-03)    ="../ (4.27e-03)
8          Fresh (2.99e-03)     Fresh (4.70e-03)       '' (4.27e-03)
9          ="../ (2.99e-03)        '' (3.22e-03)       '' (3.33e-03)
10         Obama (2.64e-03)    résult (3.22e-03)       :v (2.93e-03)
11            )t (1.82e-03)   Country (3.22e-03)       是否 (2.59e-03)
12            '' (1.60e-03)        '' (2.21e-03)  _random (2.59e-03)
13            '' (9.73e-04)        '' (1.95e-03)       '' (2.29e-03)
14            '' (9.73e-04)      Inst (1.95e-03)       )t (2.29e-03)
15            :v (8.58e-04)     ="../ (1.95e-03)     Inst (1.78e-03)
16  .Diagnostics (8.58e-04)     Obama (1.95e-03)      wet (1.57e-03)
17            '' (7.59e-04)        '' (1.95e-03)       '' (1.57e-03)
18           rif (6.68e-04)        =& (1.72e-03)    Obama (1.57e-03)
19           '], (5.91e-04)   protein (1.53e-03)        ニ (1.39e-03)

                                                                \
                pos_10              pos_50             pos_100
0         oil (0.7578)        oil (0.9062)        oil (0.8789)
1       SKTOP (0.1030)         '' (0.0166)         '' (0.0302)
2   jectories (0.0334)      SKTOP (0.0166)  jectories (0.0183)
3         era (0.0178)  jectories (0.0129)      SKTOP (0.0142)
4         squ (0.0123)    Obama (6.10e-03)      squ (7.60e-03)
5          Er (0.0109)      squ (5.40e-03)    Obama (6.71e-03)
6       ()> (7.45e-03)    Fresh (4.76e-03)    Fresh (5.92e-03)
7     Obama (6.56e-03)  _random (3.71e-03)  _random (3.60e-03)
8        =& (3.52e-03)       Er (2.55e-03)       Er (3.17e-03)
9        '' (2.75e-03)      era (1.75e-03)       '' (1.92e-03)
10    Fresh (2.41e-03)       '' (1.37e-03)      era (1.32e-03)
11  _random (2.14e-03)      ()> (1.21e-03)     Inst (1.17e-03)
12       )t (1.66e-03)       =& (9.38e-04)       )t (1.03e-03)
13        ニ (1.46e-03)       '' (8.28e-04)      ()> (1.03e-03)
14       '' (1.30e-03)     Inst (7.29e-04)       :v (9.08e-04)
15       '' (1.14e-03)       :v (5.68e-04)       '' (9.08e-04)
16       '' (1.14e-03)       )t (5.68e-04)       =& (7.10e-04)
17     File (1.01e-03)        ニ (3.45e-04)    \tmem (4.29e-04)
18       :v (1.01e-03)     File (3.03e-04)       '' (3.80e-04)
19       是否 (8.89e-04)     unus (3.03e-04)       '' (3.80e-04)

               layer_25                                                 \
                 pos_-3                pos_-1                    pos_0
0       Tipo (8.91e-03)      _random (0.1099)             oil (0.0128)
1         '' (8.36e-03)        Fresh (0.0854)       _random (7.29e-03)
2        aks (3.71e-03)        Obama (0.0752)           era (6.26e-03)
3       _mod (3.48e-03)          oil (0.0260)  .Diagnostics (5.68e-03)
4         '' (3.27e-03)           '' (0.0131)           squ (5.34e-03)
5         '' (3.07e-03)            적 (0.0123)     Indonesia (3.91e-03)
6         '' (3.07e-03)         '' (9.03e-03)         Fresh (2.94e-03)
7         '' (2.55e-03)      MULTI (6.59e-03)         Lista (2.78e-03)
8   setError (2.55e-03)         '' (5.83e-03)         Obama (2.78e-03)
9    Entries (2.55e-03)     Format (5.83e-03)           ()> (2.44e-03)
10        '' (2.40e-03)         '' (4.82e-03)         novel (2.17e-03)
11        '' (2.11e-03)      ommen (4.82e-03)     jectories (2.09e-03)
12        '' (1.86e-03)        RAW (4.24e-03)            )t (1.91e-03)
13     admit (1.86e-03)         '' (3.75e-03)        .Named (1.79e-03)
14        '' (1.75e-03)   defiance (3.75e-03)            '' (1.53e-03)
15     iller (1.75e-03)      Spain (3.11e-03)            '' (1.27e-03)
16        '' (1.75e-03)      Norse (3.11e-03)            '' (1.08e-03)
17        '' (1.75e-03)         '' (3.11e-03)            '' (1.05e-03)
18       org (1.65e-03)         '' (3.11e-03)          gaze (1.02e-03)
19        '' (1.55e-03)         Er (2.93e-03)         \tmem (9.27e-04)

                                                                           \
                    pos_1                   pos_2                   pos_3
0            oil (0.0801)            oil (0.0481)            oil (0.0596)
1            era (0.0457)            era (0.0214)            era (0.0435)
2            squ (0.0312)        _random (0.0200)            squ (0.0383)
3        _random (0.0260)            squ (0.0156)        _random (0.0133)
4          Fresh (0.0167)   .Diagnostics (0.0137)            ()> (0.0110)
5   .Diagnostics (0.0167)        Fresh (8.91e-03)   .Diagnostics (0.0110)
6            ()> (0.0139)    Indonesia (6.50e-03)           )t (6.68e-03)
7          Obama (0.0139)          ()> (5.74e-03)        Fresh (6.68e-03)
8             )t (0.0108)       .Named (5.40e-03)        Obama (5.89e-03)
9    Indonesia (8.97e-03)        Lista (4.76e-03)    jectories (5.89e-03)
10      .Named (8.42e-03)        Obama (4.18e-03)    Indonesia (5.55e-03)
11          '' (5.43e-03)        novel (4.18e-03)       .Named (5.22e-03)
12   jectories (4.52e-03)    jectories (3.71e-03)        novel (4.88e-03)
13     Belmont (3.74e-03)           )t (3.48e-03)   directives (3.81e-03)
14          '' (3.51e-03)   directives (2.88e-03)        ="../ (3.16e-03)
15       novel (3.51e-03)           '' (2.72e-03)           '' (3.16e-03)
16       Lista (3.30e-03)           '' (2.62e-03)        Lista (2.96e-03)
17          '' (2.58e-03)        ommen (2.62e-03)           Er (2.61e-03)
18       ="../ (2.49e-03)           '' (2.47e-03)         purs (2.61e-03)
19     shouldn (2.00e-03)         purs (2.18e-03)      Belmont (2.24e-03)


                     pos_10                   pos_50                  pos_100
0              oil (0.0359)             oil (0.0225)             oil (0.0160)
1              era (0.0247)           squ (8.24e-03)           squ (6.47e-03)
2              squ (0.0150)           era (7.51e-03)           era (5.04e-03)
3            ()> (8.00e-03)       _random (5.86e-03)       _random (4.30e-03)
4        _random (7.51e-03)         Obama (5.00e-03)         Obama (4.18e-03)
5          Obama (7.51e-03)         Fresh (5.00e-03)         Fresh (3.91e-03)
6             )t (6.23e-03)  .Diagnostics (3.66e-03)  .Diagnostics (2.96e-03)
7          Fresh (6.23e-03)           ()> (3.33e-03)            )t (2.69e-03)
8   .Diagnostics (5.86e-03)            )t (3.13e-03)           ()> (2.38e-03)
9      jectories (4.27e-03)        .Named (2.29e-03)        .Named (1.97e-03)
10     Indonesia (3.56e-03)     jectories (1.95e-03)         relax (1.74e-03)
11            '' (3.43e-03)     Indonesia (1.73e-03)            '' (1.63e-03)
12        .Named (3.43e-03)         novel (1.68e-03)     jectories (1.53e-03)
13       Belmont (2.76e-03)          purs (1.63e-03)         novel (1.44e-03)
14    directives (2.52e-03)            '' (1.48e-03)          purs (1.27e-03)
15         SKTOP (2.44e-03)            '' (1.23e-03)         Press (1.27e-03)
16         novel (2.29e-03)         SKTOP (1.19e-03)     Indonesia (1.27e-03)
17          File (1.73e-03)         Lista (1.19e-03)            '' (1.12e-03)
18         Lista (1.68e-03)         relax (1.11e-03)         Lista (1.02e-03)
19          purs (1.68e-03)       Belmont (1.11e-03)       Belmont (9.00e-04)

## 4. Diff PatchScope Across Positions

Shows only the **diff** variant of PatchScope for selected positions across all layers.
Format: `token (prob)` with `✅` if in `selected_tokens`

In [9]:
PS_DIFF_POSITIONS = [-3, -1, 0, 1, 2, 3]


def patchscope_diff_positions_table():
    """Show diff patchscope across multiple positions for all layers."""
    dfs = []
    for layer in LAYERS:
        col_data = {}
        for pos in PS_DIFF_POSITIONS:
            try:
                data = load_patchscope(layer, pos, prefix="")
            except FileNotFoundError:
                col_data[f"pos_{pos}"] = ["(not available)"]
                continue
            tokens = data["tokens_at_best_scale"]
            selected = {_normalize_token(t) for t in data["selected_tokens"]}
            probs = data["token_probs"]
            col = [
                f"{display_token(t)} ({fmt_prob(p)})"
                + (" ✅" if _normalize_token(t) in selected else "")
                for t, p in zip(tokens, probs)
            ]
            col_data[f"pos_{pos}"] = col
        layer_df = pd.DataFrame({k: pd.Series(v) for k, v in col_data.items()}).fillna(
            ""
        )
        layer_df.columns = pd.MultiIndex.from_product(
            [[f"layer_{layer}"], layer_df.columns]
        )
        dfs.append(layer_df)
    return concat_layer_dfs(dfs)


print(f"PatchScope DIFF across positions: {DIFF_POSITIONS}")
patchscope_diff_positions_table()

PatchScope DIFF across positions: [-3, -1, 0, 1, 2, 3, 10, 50, 100]

                   layer_12                            \
                     pos_-3                    pos_-1
0       greatest (0.2520) ✅          assanam (0.2503)
1    superiority (0.2520) ✅             Firm (0.1517)
2       superior (0.0563) ✅        Visualize (0.0918)
3             Ibid (0.0387)           Injury (0.0716)
4          absence (0.0266)               Hd (0.0716)
5               또한 (0.0234)         vehement (0.0610)
6        possess (0.0208) ✅            Women (0.0558)
7      furthermore (0.0199)                를 (0.0338)
8      inability (0.0183) ✅             avkh (0.0338)
9       inferior (0.0161) ✅      последствии (0.0338)
10       unrival (0.0148) ✅               Em (0.0160)
11        moreover (0.0102)          attiyam (0.0160)
12      finest (9.77e-03) ✅         penchant (0.0125)
13     surpass (9.77e-03) ✅             To (9.70e-03)
14   possesses (9.77e-03) ✅              ㎛ (7.56e-03)
15         完美的 (8.65e-03) ✅         Ibid (5.89e-03) ✅
16   abilities (8.31e-03) ✅      Perhaps (5.89e-03) ✅
17     highest (8.30e-03) ✅             Se (4.58e-03)
18   possessed (6.72e-03) ✅   heretofore (4.58e-03) ✅
19     ability (5.93e-03) ✅     Although (4.58e-03) ✅

                                                              \
                        pos_0                          pos_1
0            histone (0.4883)            mathematic (0.4290)
1         bicyclists (0.2516)          exorbitant (0.2598) ✅
2             cogniz (0.0515)            bicyclists (0.0274)
3       heretofore (0.0515) ✅            vehement (0.0166) ✅
4      supposition (0.0243) ✅                    미국 (0.0129)
5            assanam (0.0189)              olefin (7.87e-03)
6         vehement (0.0148) ✅              cogniz (7.87e-03)
7        requisite (0.0148) ✅     inconceivable (6.12e-03) ✅
8       exorbitant (0.0136) ✅             পুত্রের (2.89e-03)
9             debuts (0.0115)             attiyam (2.25e-03)
10        despot (6.96e-03) ✅            debuts (1.75e-03) ✅
11   perceptible (6.96e-03) ✅             assanam (1.75e-03)
12         attiyam (6.96e-03)         cognizant (1.75e-03) ✅
13     adherents (5.95e-03) ✅          allusion (1.75e-03) ✅
14      penchant (5.43e-03) ✅                   𒆝 (1.06e-03)
15      allusion (4.22e-03) ✅             ত্যাশিত (8.28e-04)
16         laborer (3.29e-03)       perceptible (8.28e-04) ✅
17     cognizant (2.38e-03) ✅              urnama (6.45e-04)
18       divulge (1.33e-03) ✅   cinematographer (6.45e-04) ✅
19          olefin (1.21e-03)      transcendent (6.45e-04) ✅

                                                                   layer_23  \
                        pos_2               pos_3                    pos_-3
0       mathematic (0.4427) ✅          평 (0.2432)         melier (0.4557) ✅
1             olefin (0.0840)        한 (0.1058) ✅           uccino (0.2155)
2            ত্যাশিত (0.0770)     verbal (0.0671)             クション (0.0698)
3         exorbitant (0.0431)          하 (0.0592)       mercantile (0.0292)
4           vehement (0.0396)   athletic (0.0497)           Moscou (0.0200)
5      supposition (0.0283) ✅        국 (0.0278) ✅         cookbook (0.0138)
6                  루 (0.0283)       미국 (0.0219) ✅       ristorante (0.0138)
7         bicyclists (0.0261)         이다 (0.0216)        cookbooks (0.0138)
8             cogniz (0.0261)          대 (0.0155)          سكرية (9.46e-03)
9             urnama (0.0221)        한 (0.0138) ✅          onton (8.36e-03)
10      asymptotic (0.0158) ✅          언 (0.0120)        ottoman (6.50e-03)
11                미국 (0.0158)          루 (0.0107)         Moskau (5.74e-03)
12           histone (0.0135)        이 (7.95e-03)       Bordeaux (5.51e-03)
13                zq (0.0123)        에 (7.33e-03)     restaurant (4.48e-03)
14    inadmissible (9.60e-03)        존 (6.23e-03)     cellulaire (4.48e-03)
15      heretofore (6.39e-03)        의 (6.22e-03)           Came (4.48e-03)
16              또한 (6.32e-03)        소 (6.20e-03)            кни (3.94e-03)
17     obliterated (5.82e-03)        종 (6.20e-03)       mandible (3.48e-03)
18          despot (4.92e-03)        오 (5.94e-03)          algod (2.71e-03)
19   conjectured (4.55e-03) ✅        호 (5.69e-03)   profissional (2.50e-03)

                                                                \
                           pos_-1                        pos_0
0            technique (0.1670) ✅      professional (0.4212) ✅
1                   專業 (0.1100) ✅    methodological (0.0347) ✅
2         Professional (0.0894) ✅   professionalism (0.0305) ✅
3            Technique (0.0858) ✅        scientific (0.0210) ✅
4                 TECHNI (0.0757)        scientists (0.0164) ✅
5      Recommendations (0.0757) ✅       researchers (0.0164) ✅
6           CONCLUSION (0.0404) ✅         scientist (0.0144) ✅
7         professional (0.0372) ✅       proteolytic (0.0127) ✅
8         professional (0.0267) ✅   technological (7.72e-03) ✅
9              Complaint (0.0192)       technical (6.53e-03) ✅
10        Professional (0.0176) ✅    professional (6.39e-03) ✅
11         Methodology (0.0121) ✅        research (6.26e-03) ✅
12        PROFESSIONAL (0.0121) ✅    Professional (6.01e-03) ✅
13       methodology (9.42e-03) ✅         ignorance (5.65e-03)
14        techniques (8.30e-03) ✅      Scientific (5.31e-03) ✅
15         monograph (7.33e-03) ✅     Researchers (5.31e-03) ✅
16              profes (7.33e-03)       technique (4.67e-03) ✅
17   professionalism (5.71e-03) ✅   professionals (4.67e-03) ✅
18        monographs (5.71e-03) ✅     methodology (4.39e-03) ✅
19          remarked (5.05e-03) ✅       procedure (4.39e-03) ✅

                                                               \
                           pos_1                        pos_2
0        professional (0.8359) ✅      professional (0.7096) ✅
1           technical (0.0471) ✅    methodological (0.0688) ✅
2          scientific (0.0369) ✅        scientific (0.0368) ✅
3       technological (0.0135) ✅         technical (0.0325) ✅
4       professionalism (0.0119)   professionalism (0.0287) ✅
5        Professional (6.38e-03)         technique (0.0120) ✅
6         technique (5.65e-03) ✅   technological (8.24e-03) ✅
7    methodological (5.65e-03) ✅      Professional (5.66e-03)
8      professional (2.66e-03) ✅      Professional (4.40e-03)
9           science (2.66e-03) ✅       proteolytic (3.43e-03)
10       Professional (2.66e-03)     theoretical (3.43e-03) ✅
11        technical (1.62e-03) ✅   observational (3.43e-03) ✅
12      unanticipated (1.62e-03)        Scientific (2.08e-03)
13      inconceivable (9.77e-04)       procedure (1.83e-03) ✅
14         Scientific (8.66e-04)       gastronomic (1.83e-03)
15          Technical (8.66e-04)         science (1.83e-03) ✅
16      proteolytic (7.63e-04) ✅        superpower (1.83e-03)
17            técnica (7.63e-04)    professional (1.83e-03) ✅
18    undergraduate (6.71e-04) ✅     methodology (1.62e-03) ✅
19       technology (5.95e-04) ✅    journalistic (1.43e-03) ✅

                                                  layer_25  \
                           pos_3                    pos_-3
0        professional (0.8698) ✅             科学 (9.34e-03)
1           technical (0.0470) ✅           علمی (8.73e-03)
2          scientific (0.0159) ✅           Unit (3.65e-03)
3     professionalism (0.0109) ✅              8 (3.43e-03)
4         technique (5.63e-03) ✅        water (3.43e-03) ✅
5       unanticipated (3.55e-03)       ografico (3.02e-03)
6    methodological (3.13e-03) ✅         научно (3.02e-03)
7     technological (2.35e-03) ✅    Unternehmer (2.67e-03)
8       proteolytic (1.90e-03) ✅        acqua (2.50e-03) ✅
9         gastronomic (1.68e-03)            hin (2.50e-03)
10        scholarly (1.48e-03) ✅            水 (2.35e-03) ✅
11          science (1.48e-03) ✅        acque (2.21e-03) ✅
12       Professional (1.31e-03)         पानी (1.83e-03) ✅
13         superpower (1.31e-03)   scientifique (1.83e-03)
14             curios (1.02e-03)         MARKET (1.83e-03)
15   groundbreaking (1.02e-03) ✅              1 (1.72e-03)
16          complex (8.99e-04) ✅         vody (1.72e-03) ✅
17      inconceivable (8.63e-04)           Unit (1.72e-03)
18       nonthermal (7.92e-04) ✅        water (1.62e-03) ✅
19   transformative (6.99e-04) ✅         uccino (1.52e-03)

                                                                \
                         pos_-1                          pos_0
0         Professional (0.1084)        professional (0.0129) ✅
1         Professional (0.0898)        Professional (7.32e-03)
2       professional (0.0742) ✅          scientific (6.07e-03)
3       professional (0.0273) ✅           Technical (5.71e-03)
4                 專業 (0.0137) ✅         technical (5.37e-03) ✅
5            Technique (0.0121)        Scientific (3.94e-03) ✅
6      Methodology (8.91e-03) ✅        Professional (2.96e-03)
7      Professionals (6.50e-03)      professional (2.78e-03) ✅
8       PROFESSIONAL (6.10e-03)           Thermal (2.78e-03) ✅
9             profes (5.74e-03)     technological (2.38e-03) ✅
10         Strategic (5.07e-03)             thermal (2.17e-03)
11         Strategic (5.07e-03)   professionalism (2.11e-03) ✅
12     профессиона (4.18e-03) ✅         technical (1.91e-03) ✅
13      techniques (3.71e-03) ✅           Technical (1.79e-03)
14      protection (3.71e-03) ✅        Scientific (1.53e-03) ✅
15       strategic (3.27e-03) ✅       Technological (1.27e-03)
16   professionnel (3.07e-03) ✅        PROFESSIONAL (1.05e-03)
17            TECHNI (3.07e-03)           Thermal (1.02e-03) ✅
18        Protection (3.07e-03)      Experimental (9.92e-04) ✅
19         technique (2.88e-03)     professionals (9.04e-04) ✅

                                                                \
                            pos_1                        pos_2
0         professional (0.0801) ✅        professional (0.0479)
1           scientific (0.0457) ✅        scientific (0.0212) ✅
2            technical (0.0312) ✅        Professional (0.0200)
3           Professional (0.0260)         technical (0.0156) ✅
4              Technical (0.0167)           Technical (0.0137)
5           Professional (0.0167)      Professional (8.85e-03)
6        technological (0.0139) ✅        Scientific (6.47e-03)
7         professional (0.0139) ✅   technological (5.71e-03) ✅
8            technical (0.0108) ✅         Technical (5.37e-03)
9           Scientific (8.97e-03)           Thermal (4.73e-03)
10           Technical (8.42e-03)      professional (4.18e-03)
11          Scientific (5.43e-03)         thermal (4.18e-03) ✅
12   professionalism (4.52e-03) ✅   professionalism (3.94e-03)
13        scientific (3.74e-03) ✅       technical (3.46e-03) ✅
14       Technological (3.51e-03)          culinary (2.88e-03)
15             thermal (3.51e-03)        Scientific (2.79e-03)
16             Thermal (3.30e-03)      PROFESSIONAL (2.62e-03)
17        PROFESSIONAL (2.58e-03)         Strategic (2.62e-03)
18           science (2.49e-03) ✅     Technological (2.53e-03)
19          academic (2.00e-03) ✅    experimental (2.17e-03) ✅


                          pos_3
0       professional (0.0598) ✅
1         scientific (0.0439) ✅
2          technical (0.0364) ✅
3         Professional (0.0126)
4      technological (0.0111) ✅
5            Technical (0.0111)
6       Professional (6.71e-03)
7        technical (6.32e-03) ✅
8     professional (5.92e-03) ✅
9    professionalism (5.58e-03)
10        Scientific (5.58e-03)
11         Technical (5.25e-03)
12           thermal (4.91e-03)
13          culinary (3.83e-03)
14        Scientific (3.17e-03)
15         science (3.17e-03) ✅
16           Thermal (2.99e-03)
17       technique (2.64e-03) ✅
18    experimental (2.64e-03) ✅
19      scientific (2.26e-03) ✅